### ISSUE TITLE
bootloader github workflow

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#1022]
We need to guard firmware\bootloader within CI

make -f src/Makefile

**Comment by rusefi** [comment]
#1020 was breaking master in this exact area :(

**Comment by rusefi** [comment]
@mck1117 since you've just broken bootloader compilation I hope it would make sense for you to implement this change?

**Comment by mck1117** [comment]
Yes - I'll fix it

**Comment by rusefi** [comment]
@mck1117 same plea

> @mck1117 since you've just broken bootloader compilation I hope it would make sense for you to implement this change?
