### ISSUE TITLE
Try -fdump-tree-all-graph

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#1079]
gcc has "-fdump-tree-all-graph"
So with
USE_OPT += -fdump-tree-all-graph
we get a bunch of .dot files which could be used to produce some sweet flow diagrams?

**Comment by mck1117** [comment]
do we not already get those diagrams from doxygen?

**Comment by rusefi** [comment]
Foxygen is a file or method diagram? Here we have complete vode flow as a diagram

**Comment by rusefillc** [comment]
https://xyproblem.info/ unclear, closing
