### ISSUE TITLE
Support stepper control with a pair of H-Bridges

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#1088]
You can control a stepper with two H bridges, like the pair of TLE9201 found on Proteus.  We currently only support controlling a stepper with a real stepper IC with step/dir pins.

**Comment by rusefi** [comment]
Would TLE8888 use the same two-H-bridges code once we have TLE8888-specific initialization?

**Comment by rusefi** [comment]
Which part of this picture is our case @mck1117  ?

![image](https://user-images.githubusercontent.com/7377949/73611934-5ecb4b80-45b5-11ea-8881-630cbe135903.png)

**Comment by rusefillc** [comment]
this works for while.
