### ISSUE TITLE
Three wire idle air valve - double solenoid

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#1122]
Bosch 280140553
When not connected, is semi open, 2 coils one is closing it other opens it.

https://rusefi.com/forum/viewtopic.php?f=2&t=1661

**Comment by rusefi** [comment]
@dron0gus is this similar to the Subaru you've mentioned?

**Comment by dron0gus** [comment]
Yes. Looks similar. I'll try to get subaru valve for tests.

**Comment by rusefi** [comment]
@dron0gus I've made some skeleton changes for this feature but not the most important part of the change

**Comment by OrchardPerformance** [comment]
@dron0gus  - Does your commit mean this can be closed?

**Comment by dron0gus** [comment]
Until someone (I?) will test and report bug[s] - yes.
