### ISSUE TITLE
"pins" does not show smart pins on MRE

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#1138]
PIN_REPO_SIZE = 128
BOARD_EXT_PINREPOPINS = 24
x1 TLE8888

looks like cycle does not touch TLE8888 enum range?

```
		for (unsigned int i = getNumBrainPins() ; i < getNumBrainPins() + BOARD_EXT_PINREPOPINS /* gpiochips_get_total_pins()*/ ; i++) {

```

![image](https://user-images.githubusercontent.com/7377949/74177565-fc52fa80-4c07-11ea-9d4b-5da55991b658.png)

**Comment by rusefi** [comment]
@dron0gus?

**Comment by dron0gus** [comment]
https://github.com/rusefi/rusefi/pull/1125/commits/e043f266c41ad3c1b2ad69e7df3d426e576f92b9 should fix.

**Comment by dron0gus** [comment]
Please check https://github.com/rusefi/rusefi/pull/1125

**Comment by rusefi** [comment]
Fixed in master thank you @dron0gus
