### ISSUE TITLE
Multi spark

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#1151]
Multiple sparks can help persuade ignition at low rpm/poor mixing/etc.  Shortly after the first "normal" spark is fired, we charge the coil again and fire again.  This will need parameters to control spark count vs. rpm (more sparks at low speed, fewer at high speed).

http://dtec.net.au/Multi%20Spark%20Ignition.htm

**Comment by mck1117** [comment]
Prototype of multispark settings UI:
![image](https://user-images.githubusercontent.com/568254/76281977-a9df1b00-6253-11ea-9da1-571891c6a703.png)

**Comment by OrchardPerformance** [comment]
@mck1117 - As this is now implemented and merged should we close this?
