### ISSUE TITLE
racecapture integration

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#1163]
racecapture integration via CAN?

**Comment by rusefi** [comment]
offtopic: they use PCBs for case ends!

![image](https://user-images.githubusercontent.com/7377949/75616998-ea89b680-5b26-11ea-86f9-0f9f90eca0f0.png)

**Comment by mck1117** [comment]
I have part of this done - it's why I did #1156

**Comment by mck1117** [comment]
this is done now - our verbose CAN format has been added as a preset to the RaceCapture firmware!
