### ISSUE TITLE
Another 55 pin footprint and breakout board for Motronic connector

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#1167]
We have a breakout board for 963063 https://github.com/rusefi/rusefi/tree/master/hardware/963063-15_55_pin_connector

There is a bit different compatible connector with smaller spacing between terminal rows on the PCB and two plastic alignment pins. This connector is used by Bosch Motronic and we plan to use since Motronic case is larger than Yanvar case.

We do NOT have GERBERS for the "other" version (PN unknow)

We need a Kicad module/footprint/component for the "other" version and a breakout board for that "other 55"

**Comment by rusefi** [comment]
See also https://rusefi.com/forum/viewtopic.php?p=35546#p35546

**Comment by rusefi** [comment]
Another way to say the same:


We have motronic gerbers, no motronic  kicad. motronic kicad is needed.

looks like 963063 kicad could be a great starting point for motronic connector

i believe PCB footprint row spacing would need to go down and two holes would be needed for pivoting pins

**Comment by rusefi** [comment]
![image](https://user-images.githubusercontent.com/7377949/75847483-54b38d00-5dad-11ea-84e4-24a99001d41d.png)

**Comment by rusefi** [comment]
here are the non-kicad gerbers

open question what's going on with row spacing - what is footprint row spacing on this PCB? my assumption was that we are dealing with two different spacings but maybe this assumption is wrong?

[yanvar51_gerber.zip](https://github.com/rusefi/rusefi/files/4285607/yanvar51_gerber.zip)

**Comment by ksmola** [comment]
Is this done? I built gerbers (and eagle files) of a 55pin Motronic connector. I designed a pcb to use a standalone ECU 'plug and play' in the Motronic case with original connector so I know they fit.

**Comment by rusefi** [comment]
this is done https://github.com/rusefi/rusefi/tree/master/hardware/breakout_55_pin
