### ISSUE TITLE
DFU utility does not work with latest STM32CubeProgrammer drivers?

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#1170]
See https://rusefi.com/forum/viewtopic.php?p=35602#p35602

**Comment by rusefi** [comment]
Looks like ST did not update DfuUtil, same version 3.0.6 is on the website?

* Version            : V3.0.6
* Date               : 01-June-2018

**Comment by chaoschris** [comment]
Tested it also with version 3.0.6 direct  from STM:

C:\Program Files (x86)\STMicroelectronics\Software\DfuSe v3.0.6\Sources\Binary\R
elease>dir
 Volume in Laufwerk C: hat keine Bezeichnung.
 Volumeseriennummer: 0081-9799

 Verzeichnis von C:\Program Files (x86)\STMicroelectronics\Software\DfuSe v3.0.6
\Sources\Binary\Release

03.03.2020  16:56    <DIR>          .
03.03.2020  16:56    <DIR>          ..
10.06.2018  23:54            49.664 DfuFileMgr.exe
10.06.2018  22:24            28.160 DfuSeCommand.exe
10.06.2018  23:33         1.925.632 DfuSeDemo.exe
10.06.2018  23:41             4.303 SLA0044.txt
10.06.2018  21:38            72.704 STDFU.dll
10.06.2018  23:33            33.792 STDFUFiles.dll
10.06.2018  23:45            28.672 STDFUPRT.dll
29.09.2012  21:17         1.480.704 STDFUTester.exe
10.06.2018  21:35         1.800.192 STTubeDevice30.dll
               9 Datei(en),      5.423.823 Bytes
               2 Verzeichnis(se), 96.039.772.160 Bytes frei

C:\Program Files (x86)\STMicroelectronics\Software\DfuSe v3.0.6\Sources\Binary\R
elease>DfuSeCommand.exe -c -d --v
0 Device(s) found. Plug your DFU Device !
file does not exist

 Press any key to continue ...

**Comment by chaoschris** [comment]
Trying to send the dfu file brings up error 12340005, but i'm sure this has nothing to do with the error as DfuSe didn't find any device to connect to....

C:\Program Files (x86)\STMicroelectronics\Software\DfuSe v3.0.6\Sources\Binary\R
elease>DfuSeCommand.exe -c -d --v --fn rusefi.dfu
0 Device(s) found. Plug your DFU Device !

Target 00: Error Code: Unknown error 0x12340005.
Target: 00
Error Code: Unknown error 0x12340005.
TransferSize: 0
DFU State: (Unknown 0x76)
DFU Status: STATUS_OK
Request: (unknown 0x062A8AB5).
CurrentNBlock: 0xB0000000
CurrentLength: 0x300076FB
Percent: 0

**Comment by chaoschris** [comment]
And i forgot to mention, same behaviour on Windows 7 64Bit

**Comment by rusefi** [comment]
Let's discuss this at https://app.slack.com/client/T4NJHQ8QZ/CF80PQGMV/details/members

**Comment by rusefi** [comment]
Windows 7 stuff works for me today with the following driver:

![image](https://user-images.githubusercontent.com/7377949/76368499-dbfd8500-6306-11ea-9aff-823b22b46283.png)

**Comment by mck1117** [comment]
Win10 does NOT work for me, shows this as the driver:
![image](https://user-images.githubusercontent.com/568254/76368785-90d77800-62ee-11ea-8fc1-bf03165909b7.png)

Device vid/pid is 0483:df11, so that's certainly the correct device.  STM32CubeProgrammer can connect to it properly, but the rusEfi console can't, failing with the following error:

```
Giving time for USB enumeration...
Executing .\.\DfuSe/DfuSeCommand.exe -c -d --v --fn ..\rusefi.dfu
0 Device(s) found. Plug your DFU Device ! 

Target 00: Error Code: Unknown error 0x12340005. 
Target: 00
Error Code: Unknown error 0x12340005. 
TransferSize: 0
DFU State: STATE_IDLE
DFU Status: STATUS_OK
Request: (unknown 0x1C222AA3). 
CurrentNBlock: 0x1975052D
CurrentLength: 0x75FDEB
Percent: 0
```

Note that it did successfully connect to the firmware and reboot it to DFU mode, but couldn't connect.

**Comment by rusefi** [comment]
I was trying to reproduce the issue on my Windows 10:

1) step one - launch rusEfi console, hit "Auto DFU"
2) Device manager shows "stm32 boot-loader" non functioning device, drivers did NOT miraculously appear
2) I hit "update drivers", "automatic"

and I got the (good?) driver installed - maybe I've played with rusEfi driver bundle here before?
![image](https://user-images.githubusercontent.com/7377949/76369807-326cc280-630b-11ea-8051-8a3ae8243818.png)

and at the end I have NOT working DFU like this:

![image](https://user-images.githubusercontent.com/7377949/76369892-7cee3f00-630b-11ea-951c-053d022646b4.png)

which could be another issue not the original issue reported here?

**Comment by rusefi** [comment]
https://wiki.st.com/stm32mpu/wiki/STM32CubeProgrammer mentions uninstalling our current DfuSe driver. 

Looks like STM32CubeProgrammer is the new way for stm32 DFU.

Looks like one day we would need to migrate to this new way.

**Comment by rusefillc** [comment]
We've migrated to STM32 BOOTLOADER driver
