### ISSUE TITLE
rusEfi console does not start under AdoptOpenJDK

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#1181]
I am sure I have java 8 installed yet rusEfi console launcher says it requires version 1.7

console definitely should run under Azul or any other java 8

**Comment by rusefi** [comment]
working on following windows 7:

![image](https://user-images.githubusercontent.com/7377949/76369243-54fddc00-6309-11ea-97fc-bda82f532eeb.png)

**Comment by mck1117** [comment]
On Windows 10 build 18362 I show:
```
PS C:\Users\matth> java -version
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)
```

**Comment by rusefi** [comment]
Does not start under

![image](https://user-images.githubusercontent.com/7377949/76369341-9e4e2b80-6309-11ea-9405-034b9f12b56f.png)

**Comment by rusefi** [comment]
On my Windows 10 does not start under 

![image](https://user-images.githubusercontent.com/7377949/76369361-aad28400-6309-11ea-82f3-589899885eb5.png)

**Comment by mck1117** [comment]
installed at
```
PS C:\Users\matth> (get-command java).Source
C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe
```

**Comment by rusefi** [comment]
Works on my Windows 10 under another java

![image](https://user-images.githubusercontent.com/7377949/76369556-524fb680-630a-11ea-8699-ba63689e586f.png)

**Comment by mi-hol** [comment]
runs with AdoptOpenJDK using PowerShell 7 as command shell using below command
`."C:\Program Files\jdk8u345-b01\jre\bin\java.exe" -jar "C:\Program Files\snapshot_20220914_125452_mre_f4_rusefi\console\rusefi_console.jar"`


Unfortunately the misleading "Java Runtime Environment 1.7.0" information is still displayed.
![2022-11-06 12_06_06-C__Program Files_snapshot_20220914_125452_mre_f4_rusefi_console](https://user-images.githubusercontent.com/22799428/200169633-faed54e9-4f71-4234-9f2a-6bb49a1fb4eb.png)

Java 7 is only available from ORACLE with a personal account!

I searched with 'site:github.com/rusefi/rusefi "Java Runtime Environment 1.7.0"' and other strings but had no hit unfortunately.
Could the text & code be updated to reference Java 8?

**Comment by rusefillc** [comment]
@mi-hol see https://github.com/rusefi/rusefi/tree/master/misc/console_launcher we use an external tool to create those .exe files

I've just used fresh version of the tool maybe it would help please test with latest snapshot once it builds in 30 minutes?

**Comment by mi-hol** [comment]
@rusefillc many thanks for this quick response :)

![image](https://user-images.githubusercontent.com/22799428/200179834-f21785dd-3024-41a3-a7f9-c17452a81c30.png)

due to "unknown publisher" but then displays dependency on Java 8
![image](https://user-images.githubusercontent.com/22799428/200179899-ba2ab8c5-c7f7-4104-8b0b-a9d969b0bed9.png)

Shall I open a new issue for  "unknown publisher"?

**Comment by rusefillc** [comment]
I assume that "unknown published" is a pre-existing condition

And it sounds like java version check was not fixed by http://launch4j.sourceforge.net/ people. Please help by poking http://launch4j.sourceforge.net/ people directly and linking http://launch4j.sourceforge.net/ here?

**Comment by mi-hol** [comment]
I didn't find a wiki page for the simulator in special use-cases cases like "explain running with a specific JAVA version in case multiple JAVA versions are installed".
Theredore my second suggestion would be a wiki page to explain running with several use-cases. 
Would that make sense?

**Comment by mi-hol** [comment]
> I assume that "unknown published" is a pre-existing condition

very likely true

> And it sounds like java version check was not fixed by http://launch4j.sourceforge.net/ people.

not sure to understand this comment. From my view it was fixed but these days JAVA 11 or even later version are defaults /as on my PC).

**Comment by rusefillc** [comment]
@mi-hol I've lost you big time. I am not aware of any relationship between rusefi_simulator.exe and java.

**Comment by rusefillc** [comment]
@mi-hol this ticket is about rusefi_console.exe "rusEFI console launcher" let's keep it focus on only rusefi_console.exe

**Comment by mi-hol** [comment]
> I've lost you big time. I am not aware of any relationship between rusefi_simulator.exe and java.

The initial issue "rusEfi console does not start under AdoptOpenJDK" seems solved

Apologize, my fault, I got confused by below message :(
![image](https://user-images.githubusercontent.com/22799428/200191208-fe4adb3a-1f14-4bb4-99d5-2a8ec4293cf1.png)

**Comment by rusefillc** [comment]
Closing this one, looking forward any new separate reports!
