### ISSUE TITLE
setHardwareUsTimer too large

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#123]
With version 5333

See http://tapatalk.imageshack.com/v2/14/11/16/d7367a5c9ded7e7a38ef809459b5430b.jpg
See http://rusefi.com/forum/viewtopic.php?f=9&t=728&p=12376#p12374

Reported by: rusefi

**Comment by mck1117** [comment]
I highly suspect this is gone, as it was last poked 5 years ago
