### ISSUE TITLE
Trigger emulator runs even if no pins are set

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#1253]
PWM is still being generated - but no output pins nor self stimulation are configured, spending a bunch of CPU cycles that do exactly nothing.

**Comment by rusefi** [comment]
Those CPU cycles serve for code simplicity :)

**Comment by mck1117** [comment]
![image](https://user-images.githubusercontent.com/568254/78400226-25aa5a00-75ab-11ea-8e0a-0a7ae5e3c205.png)
