### ISSUE TITLE
Start using dual bank mode

### ISSUE THREAD

**Issue by 960** [rusefi/rusefi#1255]
STM32F7 (And others?) has dual banks that enables us to "Read while write", and store the flash in real-time with engine running.

In the F7, we have had a issue with loosing flash, but I ran into this issue again today.

Refering to this:

https://www.st.com/resource/en/application_note/dm00266999-stm32f7-series-flash-memory-dual-bank-mode-stmicroelectronics.pdf

**Comment by mck1117** [comment]
we use dual bank on f7 and h7
