### ISSUE TITLE
ETB sometimes runs at 100% duty cycle while flashing

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#1261]
We need some `enableSafeMode()` / `disableSafeMode()` to enable while erasing/writing flash memory, as that blocks the CPU.  Currently if you start erasing flash while PWM is in the high part of the duty cycle, then we get stuck at 100% duty cycle. This is bad! It pins the throttle open!

**Comment by rusefi** [comment]
Is this same for any pwm like iac or vvt?

**Comment by mck1117** [comment]
Yes, same for those too.

**Comment by mck1117** [comment]
fixed with #1283
