### ISSUE TITLE
CI should generate code automatically

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#1276]
CI should invoke two code generators so that we validate against modified .txt files

**Comment by rusefi** [comment]
@mck1117 this would have prevented broken master today

let me attempt a fix

**Comment by chuckwagoncomputing** [comment]
Could this issue be clarified? It might be something I'm interested in doing, but I have no idea which code should be generated.

**Comment by mck1117** [comment]
I think this is done. I think it just mean "run the various gen_config in CI"
