### ISSUE TITLE
pin defaults are dangerous on microRusEfi

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#1308]
pin defaults used by microRusEfi at https://github.com/rusefi/rusefi/blob/master/firmware/config/boards/st_stm32f4/board.h

for example PD4 default is pretty bad :(

**Comment by rusefi** [comment]
@dron0gus @mck1117 what is the status of this issue?

**Comment by mck1117** [comment]
They are no longer as dangerous as they were.  They are now safe except in cases of spurious stm32 reset (without TLE8888 reset).  Open question whether we want to improve further with board-specific `board.h` files or not.

**Comment by rusefi** [comment]
spurious stm32 reset (without TLE8888 reset) would be taken care by HW changes
