### ISSUE TITLE
ETB tunerstudio 3D map scaling

### ISSUE THREAD

**Issue by 125jdavis** [rusefi/rusefi#1312]
1. All values in ETB map are set to -2147483648 by default. 
2. 3D map scaling is odd, doesn't show shape of map because limits are too large

![ETB Table](https://user-images.githubusercontent.com/24885463/79623587-21258b80-80eb-11ea-862a-7baa0f4cf4f8.png)
![ETB 3D MAP](https://user-images.githubusercontent.com/24885463/79623591-22ef4f00-80eb-11ea-87d2-8682cc691c44.png)

* [ Not using hardware]

**Comment by rusefi** [comment]
This is odd. What do you mean "not using hardware"? While tunerstudio has a feature for defaults without hardware we rely on hardware or similar to provide defaults. How is simulator working for you?

**Comment by 125jdavis** [comment]
I don't have any hardware, I just loaded the Frankenso .ini but every table, curve, and scalar is empty. 
I haven't connected to the simulator yet, still trying to figure out how all this stuff works.

**Comment by rusefi** [comment]
While technically we can make an extra effort to provide defaults into .ini we also kind of do not bother since high effort low benefit

**Comment by mck1117** [comment]
Good catch on #2 - the limits are indeed wrong.  I'll fix that!

**Comment by mck1117** [comment]
Units are wrong too.

**Comment by mck1117** [comment]
That looks better!

![image](https://user-images.githubusercontent.com/568254/79630687-4248a500-8108-11ea-8a5a-ace1ad830cee.png)
