### ISSUE TITLE
FISO curves need edit table

### ISSUE THREAD

**Issue by 125jdavis** [rusefi/rusefi#1313]
FISO curves don't have a table for editing.

![FISO Curves](https://user-images.githubusercontent.com/24885463/79624283-b37b5e80-80ee-11ea-909b-10dd481e6b41.png)

* [ ]

**Comment by mck1117** [comment]
Again this is because you don't have a tune loaded.  If you hit the little `...` in the top right corner, it'll show the table values, and you'll see they're all zeroes.

**Comment by mck1117** [comment]
This is what the defaults look like:

![image](https://user-images.githubusercontent.com/568254/79630764-019d5b80-8109-11ea-998a-905c5ee5c660.png)

**Comment by 125jdavis** [comment]
My mistake! I got connection to the simulator finally, so I should stop reporting false issues soon...
