### ISSUE TITLE
Log file usability epic

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#1337]
There is an interest to improve log persistence, access and publishing

1) we need to improve logging on SD card and SPI flash
2) we need to improve access to those logs via USB
3) we need some solution to automatically upload logs if home wifi is detected

**Comment by stefanst** [comment]
Getting access to logs via USB is of high importance. Having logs on SD cards inside the ECU case is good, but accessing it will require tools and patience in many cases. Access via USB is very important for convenience.

**Comment by mck1117** [comment]
We have USB access to logs on SD card!
