### ISSUE TITLE
Race condition in OutputPin::setValue

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#1353]
OutputPin::setValue uses `palWritePad`.

`palWritePad` is implemented by reading the port, permuting bits, and then writing the port to set the pin to the desired state.

This operation is not atomic - if a context switch occurs inbetween reading the previous state and writing the state and it sets an output pin on the same port, it's possible for the IO port to get in to an incorrect state.

See the warning in the header near `palWritePad`:

```
* @note    The operation is not guaranteed to be atomic on all the
 *          architectures, for atomicity and/or portability reasons you may
 *          need to enclose port I/O operations between @p osalSysLock() and
 *          @p osalSysUnlock().
```

On the stm32, the macros `palSetPad` and `palClearPad` ARE indeed atomic, since they write to the `BSRR` registers (single instruction to set/clear a bit in the `ODR`).

**Comment by mck1117** [comment]
I have no evidence that this has actually happened - the window for an interrupt to happen between the read/write is at most 3-5 cycles long, so it would require some incredible luck.  However, the effects could be pretty bad: firing a coil early (or late), closing an injector early or late, etc.

**Comment by dron0gus** [comment]
Looks like GPIOv2 LLD is used for STM32F4xx:
```
#define pal_lld_writegroup(port, mask, offset, bits)                        \
  ((port)->BSRR.W = ((~(bits) & (mask)) << (16U + (offset))) |              \
                     (((bits) & (mask)) << (offset)))
```

**Comment by mck1117** [comment]
Oh, I'm not sure how I missed that. I thought the implementation I'd seen was read-modify-write, but evidently not.
