### ISSUE TITLE
Rev limiter causes sync loss on 60-2

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#1360]
bumping the rev limit can cause loss of trigger sync

This code is suspect - we probably don't have time to be printing while in trigger callbacks:
```
if (limitedSpark || limitedFuel) {
	// todo: this is not really a warning
	warning(CUSTOM_SKIPPING_STROKE, "skipping stroke due to rpm=%d", rpm);
}
```

**Comment by mck1117** [comment]
credit to @960 for pointing this out

**Comment by OrchardPerformance** [comment]
@mck1117 - Do we think this is now resolved?

**Comment by mck1117** [comment]
yes, it is
