### ISSUE TITLE
reduce significant figures in FSIO settings

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#1387]
No need for so many digits:

<img width="349" alt="image" src="https://user-images.githubusercontent.com/568254/80751634-05ed4f80-8adf-11ea-85fc-26ce0667bd33.png">

**Comment by rusefi** [comment]
Drew has complaint that UI is confusing with most important digits not visible

User does not care about significant figures, used really cares about poor UI experience with most important digits not being visible in TS
