### ISSUE TITLE
Maybe mention board name in TS signature?

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#1412]
do we want to have board name mentioned in TS signature to make tunes board-specific?

**Comment by rusefi** [comment]
@andreika-git @mck1117 what is your opinion on this?

**Comment by mck1117** [comment]
It appears that TS does indeed complain if you try and load a tune for the wrong signature, so this would prevent errors from users loading a tune for the wrong board.

![image](https://user-images.githubusercontent.com/568254/82625848-0f784d80-9b9b-11ea-8e81-7a7fdc1aece8.png)

**Comment by mck1117** [comment]
this is done?
