### ISSUE TITLE
Dynamic pin change: VSS ans trigger

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#1413]
At the moment VSS and/or trigger pin changes are not applied on the fly. I believe those should be applied on the fly.

Matthew Kennedy:
and the two independently functional cleverness are destructively interfering
advanced idiocy is extremely useful
here's a workaround for now:
set both trigger inputs, and VSS input to NONE
press burn
restart ECU (unplug + replug all USB)
set correct pins in TS

**Comment by mck1117** [comment]
dynamic pin change works great with these
