### ISSUE TITLE
what is the root cause of rusEFI spi not accepting so many SD cards?

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#1417]
do we know if Arduino has a better success rate via same SPI? could it be that we have defects in rusEFI?

**Comment by rusefi** [comment]
@stefanst FYI

**Comment by mck1117** [comment]
Apparently some newer SD/SDHC cards have dropped support for SPI mode.

https://forum.4dsystems.com.au/node/1869

>  "Please note that Kingston Technology does not manufacture and subsequently test its range of flash card products to be used for the purpose of being addressed under the SPI mode."

**Comment by rusefi** [comment]
Maybe ChipGenius is a tool to look at card ID? I have not found better options to replace ReadCardInfo.zip from above link

also Frankenso to Arduino comparison would still make sense :)

**Comment by rusefi** [comment]
there is 
![image](https://user-images.githubusercontent.com/7377949/81501930-ec9b8e80-92a8-11ea-991e-48a72dddb6d6.png)

there is uSD-4GB-Industrial 
![image](https://user-images.githubusercontent.com/7377949/81501939-f6bd8d00-92a8-11ea-95a1-5229b2158bf3.png)

**Comment by rusefi** [comment]
Many good for us cards shown at https://rusefi.com/forum/viewtopic.php?p=36528#p36528
