### ISSUE TITLE
use switch to enable/disable logging

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#1444]
On rising edge: create new log, start logging
On falling edge: stop logging, flush, close log file

**Comment by rusefi** [comment]
See also #272

**Comment by rusefillc** [comment]
Maybe lua to control logging or logging file name?

**Comment by rusefillc** [comment]
@mck1117 what is this file about? SD logging? TS logging? console logging?

**Comment by mck1117** [comment]
This was about enable/disable SD logging with a switch. I'm not sure we need this.

We can reopen if somebody appears and demands it.
