### ISSUE TITLE
"TLE8888 SR Unexpected response" does not work as intended

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#1466]
somehow this validation works for me but not for two users?

Jokeri
Jacob

**Comment by rusefi** [comment]
![img_20200522_123229](https://user-images.githubusercontent.com/7377949/82667283-85190380-9c05-11ea-80c8-e38d2f1b922d.jpg)
![img_20200522_123240](https://user-images.githubusercontent.com/7377949/82667285-85b19a00-9c05-11ea-9e2a-673e3c7ba0c0.jpg)

**Comment by OrchardPerformance** [comment]
I think this is the same as I saw yesterday as well. 
I had a response of "0" from an older V0.3 MRE board 
https://files.slack.com/files-pri/T4NJHQ8QZ-F014EM60HH7/image.png

**Comment by rusefi** [comment]
Looks like it actually works AS intended! Looks like it was a proper alert in case of Jacob - TLE was in fact not being powered!

**Comment by OrchardPerformance** [comment]
I am sure it was not powered in my case, I thought that was the reason for the lack of response.

**Comment by rusefi** [comment]
@OrchardPerformance below 7v vbatt it should not even try to communicate

**Comment by mck1117** [comment]
Should the error message be something more useful?
```
if (voltage > 7) {
    bool success = attempt_comms();
    if (!success) {
         error("please check your wiring/tle8888/etc, something is wrong");
    }
}
```
