### ISSUE TITLE
move gcov CI to github actions

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#1467]
at the moment gcov requires linux, windows tool chain did not work for me so far

at the moment CI runs in a VM linux on a box which does too many things in parallel already. let's try moving gcov CI to GH actions

open question how artifact would be consumed and published on current location but first step let's produce the artifact

**Comment by chuckwagoncomputing** [comment]
run_gcov.sh uses variables RUSEFI_DOXYGEN_FTP_USER, RUSEFI_DOXYGEN_FTP_PASS, and RUSEFI_FTP_SERVER.
You could put these values in Github secrets, and we could pass them to the run_gcov.sh script, which would be modified to accept them as arguments.

**Comment by chuckwagoncomputing** [comment]
Like this:
https://github.com/chuckwagoncomputing/rusefi/blob/gcovaction/.github/workflows/build-unit-tests.yaml

ci_gcov.sh is just the modified version of run_gcov.sh.

**Comment by rusefi** [comment]
https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets sweet let me do this

**Comment by rusefi** [comment]
three secrets added

**Comment by rusefi** [comment]
next issue

cp: cannot stat '../build/obj/*': No such file or directory
./unit_tests/ci_gcov.sh: line 21: lcov: command not found
./unit_tests/ci_gcov.sh: line 22: genhtml: command not found
./unit_tests/ci_gcov.sh: line 24: ncftpput: command not found

**Comment by chuckwagoncomputing** [comment]
yes, I'm still working on it

**Comment by rusefi** [comment]
@chuckwagoncomputing 
current non-GH jenkins for GCOV is also not Windows it uses run_gcov.sh

new ci_gcov.sh reminds me of run_gcov.sh

what is the probability of ci_gcov.sh duplicating parts of run_gcov.sh?

**Comment by chuckwagoncomputing** [comment]
Should be able to close this now.
