### ISSUE TITLE
GH action to produce DFU

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#1468]
GH actions are cool and we are already using .bin files!

let's produce .dfu files as well and use those as well :)

**Comment by rusefi** [comment]
@mck1117 @dron0gus can you help?

need to find a xxx2dfu tool for linux

**Comment by chuckwagoncomputing** [comment]
hex2dfu compiles and runs on linux, I don't have a board to test it on though.
There is also https://github.com/OpenMusicKontrollers/dfuse_pack/
I haven't tried it.

**Comment by rusefi** [comment]
https://github.com/encedo/hex2dfu this one?

please get an stm32f407discovery or MRE to test on :) also need to script it into github action

**Comment by chuckwagoncomputing** [comment]
I used the rusefi/hex2dfu fork, as I understood it had a bug fix.

**Comment by chuckwagoncomputing** [comment]
The workflows aren't showing up in my actions tab in my fork for some reason, so I can't test the workflow, so I guess I'll just go ahead and submit a PR.

**Comment by chuckwagoncomputing** [comment]
Looks like it made a DFU, now someone with hardware ought to make sure it flashes correctly.

**Comment by rusefi** [comment]
@OrchardPerformance can you please test?

**Comment by rusefi** [comment]
I assume this works
