### ISSUE TITLE
Expose all, most or many state variables to TS via Outputs region stitching

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#1471]
TS gauges work of a single continuous buffer, TS has a feature of only requesting things visible to the user or needed for other reason

We have a desire to be the most use-friendly ECU around. The more internal state is exposed via gauges the better, there is probably no risk to overexpose.

At the moment we have automation to manage configuration memory region, similar automation should be used to manage gauges region. While TS expects a continues region we can have a collection of regions in RAM and dynamic index resolve based on what TS is requesting. This way we would eliminate current logic of taking internal variable and copying it into gauges region.

**Comment by mck1117** [comment]
TS fixed their slow output channel problem, operation "one huge output page" is a go!
