### ISSUE TITLE
mass air flow output channel scaling needs help

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#1472]
![image](https://user-images.githubusercontent.com/568254/82743793-ee436880-9d24-11ea-940f-508149ee3df3.png)

We can't handle over 655.35 kg/hr of mass flow.  My engine flows this amount at 4200 rpm, and then 50% more at 6500.

**Comment by OrchardPerformance** [comment]
Yep that's a problem. 
Just for the log or internal to the firmware? 
Do we need to start using g/s in the ECU and outputting the kg/h as a single decimal place?

**Comment by rusefi** [comment]
not internal to ecu for sure

we can just change binary logging scale by any factor

**Comment by mck1117** [comment]
right, should have clarified, this is just a problem with the output channel scaling.  The ECU uses float internally so it's not a problem.

**Comment by mck1117** [comment]
fixed in #1566
