### ISSUE TITLE
.logicdata files are a bit broken

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#1482]
we can now produce .logicdata files!

but Saleae tool crashes while attempting to open those :(

**Comment by rusefi** [comment]
![image](https://user-images.githubusercontent.com/7377949/83915928-35c4ee00-a742-11ea-8ca3-9dfa47bfaa5a.png)

**Comment by rusefi** [comment]
[logs.zip](https://github.com/rusefi/rusefi/files/4738114/logs.zip)

@andreika-git

**Comment by rusefi** [comment]
![image](https://user-images.githubusercontent.com/7377949/83916242-d1eef500-a742-11ea-9226-c6c346ded74e.png)

**Comment by rusefi** [comment]
I think I am using the latest version?

![image](https://user-images.githubusercontent.com/7377949/83916396-1f6b6200-a743-11ea-9c9d-7a8a6f8af2f2.png)

**Comment by rusefi** [comment]
@andreika-git LogicdataStreamFileSandbox added and even that file is not well :(

[sandbox.zip](https://github.com/rusefi/rusefi/files/4738149/sandbox.zip)

**Comment by rusefi** [comment]
Anyway https://support.saleae.com/faq/technical-faq/can-i-create-or-edit-logicdata-files :)

**Comment by andreika-git** [comment]
The footer is not written, "@Override" problem: writeFooter(Writer) is not overridden by writeFooter()

**Comment by rusefi** [comment]
Some progress was done - footer is now written either always or at least sometimes.

Sandbox file now works!

Longer real files still do not work :( can you please see if you can identify more issues? fresh logs attached

[logs.zip](https://github.com/rusefi/rusefi/files/4738814/logs.zip)

**Comment by rusefi** [comment]
Now with event buffer still does not work :( 

[logs.zip](https://github.com/rusefi/rusefi/files/4740174/logs.zip)

**Comment by rusefi** [comment]
@andreika-git 

![image](https://user-images.githubusercontent.com/7377949/83947186-880a1b80-a7e3-11ea-9614-1eaf1a3f9ca8.png)

**Comment by andreika-git** [comment]
The timestamps should be 0-based (like from the start). Maybe just try to subtract the first timestamp from the remaining ones?

**Comment by andreika-git** [comment]
#1484
