### ISSUE TITLE
code generator - reduce the gap between Windows and Linux

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#1492]
at the moment we have to manually sync gen_config.bat and gen_config.sh since all the parameters are hard-coded inside those platform-specific scripts

@ksmola got hit by that when .sh got outdated around firing order parameter

a proper fix would be to extract parameters into input file(s) so that one file could be modified and both scripts for both platforms would still work fine

**Comment by chuckwagoncomputing** [comment]
If mingw is required anyway, couldn't we use just the .sh script?

**Comment by chuckwagoncomputing** [comment]
I know this is low priority, but for what it's worth if you want to stick with having both .bat and .sh scripts, I can do the .sh side of things but I have know batch file knowledge whatsoever.

**Comment by rusefi** [comment]
Using the same .sh on both Windows and Linux us actually an interesting idea!
