### ISSUE TITLE
[github] build board bundles using GH Actions

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#1499]
At the moment slow Windows build server takes more than an hour to build all bundles for https://rusefi.com/build_server/ once case see difference in timestamps

between our new sh.exe cross-platform trick and GH secrets we shall migrate https://github.com/rusefi/rusefi/tree/master/misc/jenkins/compile_other_versions to bash and move to GH

a milestone would be to convert https://github.com/rusefi/rusefi/blob/master/misc/jenkins/build_working_folder.bat first

**Comment by chuckwagoncomputing** [comment]
I think we should set up a secondary location to upload bundles to until this is completed. Maybe just a subdirectory of the build_server. Once everything is working properly, we can shut down the windows server and change the upload directory of the github action.

**Comment by rusefi** [comment]
works for me - just subfolder in the same folder?

to test locally you would probably need a unit box and your own FTP server

**Comment by chuckwagoncomputing** [comment]
The FTP server I have. Do you mean ECU by "unit box"?

**Comment by rusefi** [comment]
@chuckwagoncomputing no sorry it was Unix box to run the scripts, but technically Cygwin would also work.

**Comment by chuckwagoncomputing** [comment]
Ok gotcha. Most of my computers are Unix boxes. ;)

**Comment by chuckwagoncomputing** [comment]
Should this be run with every push, or maybe once daily? Because we can do that.

**Comment by rusefi** [comment]
I'd say every push, why not?

At the moment it slowly runs at every push. Usually when we push we want at least one of these bundles.

**Comment by rusefi** [comment]
@chuckwagoncomputing see latest commit for some "build\rusefi.bin" WIN vs Linux drama

**Comment by chuckwagoncomputing** [comment]
Oh good grief. :facepalm:

**Comment by chuckwagoncomputing** [comment]
Should be fixed by #1583
