### ISSUE TITLE
ERIKA: Tachomenter implementation

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#15]
We should evaluate ERIKA rtos. Someone has to setup the toolchain and write some prototype code, for instance a tachometer:
handle position sensor events > calculate > output to serial

Reported by: rusefi

**Comment by rusefi** [comment]
Aborting for now

**Comment by 960** [comment]
Reopening this, as we really need rusefi to run at a Tricore

http://git.edi.lv/vitalijs.fescenko/Erika_OS_Aurix_TC29x_port

**Comment by mck1117** [comment]
should close?

**Comment by rusefillc** [comment]
let's keep as a dream

**Comment by mck1117** [comment]
> let's keep as a dream

does that mean close? what's an ERIKA?

**Comment by rusefillc** [comment]
http://erika.tuxfamily.org/drupal/

they now say stm32f4discovery is supported

**Comment by mck1117** [comment]
**switching RTOS** seems like a major distraction

**Comment by rusefillc** [comment]
Fair point, let's wait for a better defined problem statement.
