### ISSUE TITLE
Only two .ini files got auto-generated

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#1519]
Expected behavior is for many .ini files to be refreshed together

![image](https://user-images.githubusercontent.com/7377949/85096681-093db700-b1c3-11ea-8307-b0e270fe8fd3.png)

**Comment by rusefi** [comment]
One bug fixed

next bug to fix: need to revive kinetis generation!

```
#cd config\boards\kinetis\config
#!gen_config.bat
```
it apparently got lost while migrating from bat to .sh

FYI @chuckwagoncomputing

**Comment by chuckwagoncomputing** [comment]
Why does kinetis have its own gen_config script?

**Comment by rusefi** [comment]
@chuckwagoncomputing historical reasons mostly. it has some different parameters but overall could be part of the unified script.

One use-case is when kinetis was more actively developer it was easier to gen only kinetis

**Comment by rusefi** [comment]
just fixed Proteus - that was a typo

still no idea why rusefi.ini not generated/commited @chuckwagoncomputing

**Comment by rusefi** [comment]
rusefi.ini is the remaining issue @chuckwagoncomputing

**Comment by rusefi** [comment]
makes no sense but it works! thank you!!!
