### ISSUE TITLE
Next Performance Frontier

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#1525]
we can reliably generate and process 20,000 RPM with 60/2 trigger wheel

![image](https://user-images.githubusercontent.com/7377949/85204878-924d0f00-b2e5-11ea-8e0b-e502417515e8.png)

rusEFI hangs-up with glue LED not blinking at 25,000

![image](https://user-images.githubusercontent.com/7377949/85204906-c58f9e00-b2e5-11ea-9429-fa90e5f266fc.png)

**Comment by rusefillc** [comment]
@mck1117 keep or close?

**Comment by mck1117** [comment]
I'm pretty happy with the perf these days.
