### ISSUE TITLE
java: support compilation by both 8 and 11

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#1526]
My personal preference is to compile using java 8
the only change needed to compile by JDK 11 is 
```
            <!-- uncomment if you want to compile under java 11
            please remove the space between '-' and '-add-exports' it should be double-dash
                        <compilerarg line="- -add-exports java.xml/com.sun.org.apache.xerces.internal.parsers=ALL-UNNAMED"/>
                        <compilerarg line="- -add-exports java.xml/com.sun.org.apache.xml.internal.serialize=ALL-UNNAMED"/>
                        -->
```

technically it's possible to adjust build.xml to detect what JDK version is used and add those compilerarg conditionally

**Comment by rusefillc** [comment]
@dron0gus says https://stackoverflow.com/questions/52502189/java-11-package-javax-xml-bind-does-not-exist 

could be as easy as adding jaxb into classpath but depends on gradle migration which was a bit postponed

**Comment by rusefillc** [comment]
a proper healthy solution here would be to finish gradle migration (a lot was done already) and then make gradle conditional

**Comment by rusefillc** [comment]
https://newrelic.com/resources/report/2022-state-of-java-ecosystem


says 50/50

![image](https://user-images.githubusercontent.com/48498823/187819066-d5eacc31-86f4-4076-ada6-614bdf7f7845.png)
