### ISSUE TITLE
update_version.bat does not work on Windows

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#1529]
![image](https://user-images.githubusercontent.com/7377949/85246855-e35e1f80-b419-11ea-9c25-c10b476d3a30.png)

**Comment by rusefi** [comment]
@chuckwagoncomputing

**Comment by chuckwagoncomputing** [comment]
It works for me. Is git in your path? I'm using cygwin git.

**Comment by rusefi** [comment]
I've changed PATH from standalone git to cygwin git, still does not work

![image](https://user-images.githubusercontent.com/7377949/85333981-88273e00-b4a8-11ea-803a-31ed52bc2da4.png)

**Comment by chuckwagoncomputing** [comment]
Welp, the reason it was working for me was because I hadn't pulled this change in on my windows machine yet. PR incoming.

**Comment by rusefi** [comment]
@chuckwagoncomputing it is OK to make a joke about testing less?

**Comment by chuckwagoncomputing** [comment]
Is there a sheepish face emoji?

**Comment by rusefi** [comment]
GH does not allow custom emoji but Slack does :)
