### ISSUE TITLE
failed generation does not fail

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#1550]
we print "error generating" but we do not fail the whole job somehow :(

![image](https://user-images.githubusercontent.com/7377949/86190897-a37ef280-bb13-11ea-8c17-8e7bfb05dd15.png)

**Comment by rusefi** [comment]
@chuckwagoncomputing @andreika-git need help...

**Comment by chuckwagoncomputing** [comment]
Yep, this is my problem. Fix coming up along with the converted jenkins scripts.

**Comment by chuckwagoncomputing** [comment]
This should be fixed by #1554
