### ISSUE TITLE
default bundle is not generated

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#1559]
Looks like https://rusefi.com/build_server/rusefi_bundle.zip is not generated at the moment?

@chuckwagoncomputing poke

**Comment by chuckwagoncomputing** [comment]
This should be fixed by #1562

**Comment by rusefi** [comment]
Thank you @chuckwagoncomputing this is now resolved see https://rusefi.com/build_server/autoupdate/

@andreika-git FYI
