### ISSUE TITLE
TS integration: something is wrong

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#156]
something is wrong with flat table editing - often individual cell edits are lost.

3D table editor seems to work perfectly: each individual cell change I see a 'write chunk size 4' packet in the serial port, I respond to it with a CRC zero-size payload OK message.

The flat table editor - for the same exact table - I am having sporadic issues where individual value changes are often not sent to my controller. UI shows new value for some time, then I edit another cell which actually results in the same 'write chunk size 4' message and at that point the faulty cells get rolled back to the original, unchanged values.

I have also noticed that after flat table editor is opened the request is send to read all the already displayed content from the controller. On the other hand if I open 3D editor, no request is send - the data is just displayed from known state. Is there a reason for this inconsistency? Is it because table editor is older code or different piece of code or something like that?

Reported by: rusefi

**Comment by mck1117** [comment]
this is probably fixed and at least very stale
