### ISSUE TITLE
rusEFI console produces invalid .logicdata files

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#1563]
I've attempted to record 60/2 trigger at 6000 RPM and this seems to produce a file which crashes Logic Analyzer on open :(

one of the attached .logicdata opens while the other does not

[logs.zip](https://github.com/rusefi/rusefi/files/4870298/logs.zip)

**Comment by rusefi** [comment]
@andreika-git @mck1117 any interest?

**Comment by rusefi** [comment]
@andreika-git ping any ideas?

**Comment by rusefillc** [comment]
maybe related to #1621

**Comment by rusefillc** [comment]
@andreika-git still an issue :(


[logs.zip](https://github.com/rusefi/rusefi/files/6255189/logs.zip)

**Comment by rusefillc** [comment]
[logs_hellen.zip](https://github.com/rusefi/rusefi/files/6256186/logs_hellen.zip)

[logs_proteus.zip](https://github.com/rusefi/rusefi/files/6256187/logs_proteus.zip)

**Comment by andreika-git** [comment]
Status update:
1) CSV writer doesn't write coil & injector flags (channels 5 and 6), so we cannot compare .csv to .logicdata adequately.
  To fix this, we need to add 2 more fields to TSHighSpeedLog.java (isCoil() and isInjector())
  Needless to say, we'll need a fresh set of .csv + .logicdata files for testing after that.
2) But, if we write "false" to channels 5+6, then .logicdata seems to work. You can test it with CompositeParser.java:
`boolean coil = false; /*EnumIniField.getBit(flags, 4);*/`
`boolean injector  = false; /*EnumIniField.getBit(flags, 5);*/`
  This is a temporary solution, until we fix the first issue.

**Comment by rusefillc** [comment]
Fresh logs with CSV improvement

[logs.zip](https://github.com/rusefi/rusefi/files/6305380/logs.zip)

**Comment by rusefillc** [comment]
i believe that the workaround has not solved the problem completely

[april20-with-workaround.zip](https://github.com/rusefi/rusefi/files/6340589/april20-with-workaround.zip)

**Comment by andreika-git** [comment]
i believe that the faulty rusEFI_trigger_log_2021-04-20_00_23_11_956.logicdata was recorded WITHOUT the workaround, on an older firmware version.

**Comment by rusefillc** [comment]
@andreika-git do you mean console without workaround? arm firmware was not changed right?

**Comment by andreika-git** [comment]
Yes. It seems that the console used to record this file didn't have the workaround (AFAIK the workaround only changes CompositeParser.java, not the firmware).

How could I know it? 
* If I take the LogicdataStreamFileCsvSandbox converter WITHOUT the workaround and convert rusEFI_trigger_log_2021-04-20_00_23_11_958.csv to .logicdata, I get the result almost byte-identical to yours (i.e. the faulty file).
* But if a take the same java converter WITH the workaround, it produces a completely different file (larger by 20 bytes), and the resulting .logicdata is recognized by the viewer!

**Comment by rusefillc** [comment]
Looks like files with less than 32768 events are fine while files with more than 32768 events are failing

Looks like some magic IDs are version-specific. @andreika-git do you remember what _exact_ version of Logic Analyzer software you have reverse-engineered?

**Comment by rusefillc** [comment]
1.2.40 allows 16 channel simulation, actually 16D+16A

![image](https://user-images.githubusercontent.com/48498823/211710100-4c40e1ae-05f1-49ca-97ce-2ce9eaf0449d.png)

[16-channel-digital-simulated.zip](https://github.com/rusefi/rusefi/files/10388628/16-channel-digital-simulated.zip)

**Comment by rusefillc** [comment]
Related to #2963

**Comment by rusefillc** [comment]
On the positive side there is progress I can open file using 1.2.40 "open capture" action in UI

![image](https://user-images.githubusercontent.com/48498823/215318684-21c1ce19-addd-4f1e-8851-54cde5d3e44f.png)
