### ISSUE TITLE
Signature for F4 MRE firmware wrong in 20200703 fw.

### ISSUE THREAD

**Issue by stefanst** [rusefi/rusefi#1565]
After downloading and flashing MRE bundle (F4) on July 3rd 2020, I had the following error in TS:
![image](https://user-images.githubusercontent.com/709317/86502292-92322200-bd6f-11ea-800c-cb2a7a870aab.png)
@andreika-git

**Comment by andreika-git** [comment]
https://github.com/rusefi/rusefi/pull/1569

**Comment by rusefi** [comment]
@stefanst please validate
