### ISSUE TITLE
Fuel level sensing should support a curve, not just linear

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#1571]
My fuel level sender is quite nonlinear:

![image](https://user-images.githubusercontent.com/568254/86540097-32df2980-beb7-11ea-81cd-df5530963fff.png)

Using linear interpolation between the endpoints, an indicated 80% is actually only 56% full.

**Comment by OrchardPerformance** [comment]
Most level senders will be linear for the actual sender but suffer huge non-linearity in output as the tank is not a constant cross section. 
+1 for using a curve for fuel sender.

**Comment by mck1117** [comment]
Yes, I think my sender is linear with respect to angle, but the angle isn't linear with respect to fuel level (my tank is however roughly a rectangular prism, so the level is roughly proportional to the fill).
