### ISSUE TITLE
DFU file name inside default bundle

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#1575]
we have rusefi.bin but rusefi_.dfu (With "_")

![image](https://user-images.githubusercontent.com/7377949/86545658-419cff00-befe-11ea-8aed-614d19eaac4d.png)

@chuckwagoncomputing

**Comment by rusefi** [comment]
Let's make it rusefi_default.dfu to make naming a bit more consistent?

"rusefi.bin" having same name across all bundles is another issue for another day

in light of recent performance optimizations we can actually get rid of "_no_assert" and have only one set of files in the default bundle, that would make things just a bit more consistent

@chuckwagoncomputing

**Comment by chuckwagoncomputing** [comment]
It should have been rusefi.dfu, but it seems I introduced a bug. (No surprise)
If we rename it to rusefi_default, do you want the .bin changed too?

**Comment by rusefi** [comment]
not bin yet please
