### ISSUE TITLE
OBD2 PID for short term fuel trim

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#1576]
We have short term fuel trim, so we should expose it with an OBD2 PID

**Comment by OrchardPerformance** [comment]
Do we know the PID needed for STFT?

**Comment by mck1117** [comment]
we do, see #1652. implemented, but needs testing

**Comment by OrchardPerformance** [comment]
I have a gutted elm reader that I could rig an mre too, that do it?

**Comment by mck1117** [comment]
STFT tested, but I don't have a tool that can read the equivalence ratio PID.  @OrchardPerformance, can yours read it?

**Comment by OrchardPerformance** [comment]
Nope, simple pic only

**Comment by mck1117** [comment]
this is done and works!
