### ISSUE TITLE
Log upload fails 

### ISSUE THREAD

**Issue by stefanst** [rusefi/rusefi#1580]
Trouble with log upload. 
I can select it, it gets analyzed, I get "seems OK". After clicking upload it's nowhere to be found.
[2020-07-07_20.51.26.zip](https://github.com/rusefi/rusefi/files/4887901/2020-07-07_20.51.26.zip)

**Comment by rusefi** [comment]
should be rusefi/web_backend issue

could be same root issue as https://github.com/rusefi/web_backend/issues/54

**Comment by rusefi** [comment]
@andreika-git

**Comment by rusefi** [comment]
@stefanst we can recover this log if you post your .ini file here

**Comment by stefanst** [comment]
99% certain that's the correct *.ini
[rusefi_mre_f4.zip](https://github.com/rusefi/rusefi/files/4891987/rusefi_mre_f4.zip)

**Comment by stefanst** [comment]
Screenshot of upload attempt
![image](https://user-images.githubusercontent.com/709317/86953271-2f9ba600-c122-11ea-9a5c-c73cdcfc2c7a.png)

**Comment by rusefi** [comment]
@andreika-git see report above - even with .ini uploaded we have an error?

**Comment by stefanst** [comment]
There was no change in behavior observable after the new .ini was uploaded.

**Comment by rusefi** [comment]
@stefanst please confirm that you have hit "upload"?

**Comment by stefanst** [comment]
Upload has been hit. 
@andreika-git made changes and issue is resolved.
