### ISSUE TITLE
migrate amazing idle and A/C from FSIO to less opaque TS

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#1581]
@stefanst FYI

**Comment by rusefi** [comment]
@stefanst first step new "extra" properties

![image](https://user-images.githubusercontent.com/7377949/86869683-fec95b80-c0a4-11ea-8859-705968fb5a68.png)

**Comment by rusefi** [comment]
FSIO can access those via

cfg_ACIDLEEXTRAOFFSET
cfg_ACIDLEEXTRAMIN

**Comment by rusefi** [comment]
Just switched FSIO into "extra" not "replace" logic

my testing uses the following formulas:
```
	engineConfiguration->useFSIO12ForIdleOffset = true;
	setFsioExpression(QUOTE(MAGIC_OFFSET_FOR_IDLE_OFFSET), "ac_on_switch 0 cfg_acIdleExtraOffset if" PASS_ENGINE_PARAMETER_SUFFIX);

	engineConfiguration->useFSIO13ForIdleMinValue = true;
	setFsioExpression(QUOTE(MAGIC_OFFSET_FOR_IDLE_MIN_VALUE), "ac_on_switch 0 cfg_acIdleExtraMin if" PASS_ENGINE_PARAMETER_SUFFIX);
```

**Comment by stefanst** [comment]
This seems to work with following FSIO formulas:
1: "ac_on_switch rpm 900 > time_since_ac_on_switch 0.6 > & &" for AC compressor out
2: "ac_on_switch rpm 900 > time_since_ac_on_switch 0.3 > & &" for AC fan out
12: "ac_on_switch cfg_ACIDLEEXTRAOFFSET 0 if" for extra offset
13: "ac_on_switch cfg_ACIDLEEXTRAMIN 0 if" for extra min

Old values "offset 2" and "min 2" should be removed from TS

**Comment by rusefillc** [comment]
@stefanst says

AC fan and AC compressor get switched using FSIO. Look at this tune: https://rusefi.com/online/view.php?msq=172
Under "FSIO Formulas" outputs 1 and 2 are AC compressor and AC fan respectively.

**Comment by rusefillc** [comment]
We have acFanRelay and acRelayPin we just have to add control logic

**Comment by mck1117** [comment]
done with #2745
