### ISSUE TITLE
Use bash rather than sh

### ISSUE THREAD

**Issue by chuckwagoncomputing** [rusefi/rusefi#1584]
I used sh instead of bash in scripts because that seemed to be the precedent on this project, and also because it seemed it would be more portable.
It turns out that most (all?) linux distributions symlink sh to a different shell. I speculate that the cause of #1521 was my using bash-only features without realizing it, which didn't work in Ubuntu's dash.
My suggestion would be to explicitly use bash rather than sh. This is a simple change but I thought perhaps I should get some input first.

**Comment by rusefi** [comment]
works for me as long as it works :)
