### ISSUE TITLE
kinetis auto gen does not auto gen

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#1587]
kinetis build fails due to not updated generated stuff

and gen_config does not fail :(

**Comment by rusefi** [comment]
@chuckwagoncomputing please please?

**Comment by chuckwagoncomputing** [comment]
And even worse, every build configures for all boards. Which means if one fails, they all fail.
Why does kinetis have it's own gen_config script?

**Comment by chuckwagoncomputing** [comment]
As @mck1117 has pointed out, there are a lot of orthogonality issues in the build scripts. That can be fixed, but there will be >=one more Jenkins-only script created. That means we can make changes to builds and break Jenkins without realizing it, but I think the risk is worth it, and I'll definitely do what I can to minimize the risk.

**Comment by rusefi** [comment]
@chuckwagoncomputing kinetis has it's own script because it has it's own hw enums, i.e. some of the input parameters are custom for kinetis.

**Comment by mck1117** [comment]
kinetis builds with the normal makefile just like stm32... Just look at the old `build-firmware.yaml` (prior to it generating bundle)

**Comment by rusefi** [comment]
@mck1117 kinetis code generation is a bit custom

**Comment by chuckwagoncomputing** [comment]
I've submitted a pull request for this. I'll open another issue for orthogonality issues.
