### ISSUE TITLE
idle live docs might be broken

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#1588]
idleinfo says AUTO 
live docs says NOT

![image](https://user-images.githubusercontent.com/7377949/87207090-138e3500-c2d9-11ea-9587-b02fd39be4bf.png)

![image](https://user-images.githubusercontent.com/7377949/87207127-2e60a980-c2d9-11ea-9a40-d33d2a548b54.png)

**Comment by mck1117** [comment]
those live docs are gone
