### ISSUE TITLE
TunerStudio: implement pages

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#159]
Reported by: rusefi

**Comment by mck1117** [comment]
this is long fixed

**Comment by rusefi** [comment]
@mck1117 I believe this is NOT fixed - we do use pages in TS. It could be that we do not care for pages.

**Comment by mck1117** [comment]
I don't mean fixed as in "we have pages".  I mean that the issue that prompted this has long since been solved, and we don't need pages, and the single gigantor page works fine.
