### ISSUE TITLE
Injectors #1 and #5 stick open

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#1592]
![image](https://user-images.githubusercontent.com/568254/87219273-9a113980-c30e-11ea-9bb0-bafc63d7184d.png)

Something is wrong with the overlapping injection logic with fuel scheduling.  The counter is getting incremented for those cylinders, but never decremented.  Commenting out the overlapping injection logic makes it go away.

**Comment by mck1117** [comment]
[TunerStudioDebugPackage.zip](https://github.com/rusefi/rusefi/files/4906455/TunerStudioDebugPackage.zip)

**Comment by mck1117** [comment]
Debugging notes:
during schedule rebuild in the transition from batch to sequential, we cancel all outstanding injector open/close events, and on my engine this process occurs during the time that cylinders 1 and 5 have an injector open.

**Comment by rusefi** [comment]
@mck1117 can you please elaborate on how was this screenshot produces? real vehicle cranking? some sort of simulation?

can you please attach raw .logicdata?

did you try reproducing this with a unit test?

**Comment by mck1117** [comment]
Here's the `.logicdata`:
[bad-batch-to-seq.zip](https://github.com/rusefi/rusefi/files/4923287/bad-batch-to-seq.zip)

This was first observed on a real engine that actually stuck the injectors open, dumping 350cc/min of gas in to cylinders 1 and 5 😲

**Comment by rusefi** [comment]
how was the logic data captured? looks like capture has started before the event.

**Comment by mck1117** [comment]
of course, I started the capture, then activated self stim

**Comment by rusefi** [comment]
@mck1117 what would I need to do to reproduce this in NJ?

**Comment by mck1117** [comment]
This happens when a few conditions are met:
1. During cranking, the sync point where we switch mode from cranking -> running occurs while one or more injectors are open
2. Before the injector closes, another trigger tooth (which could be the same tooth from 1) triggers a reschedule of the open injector
  
This resets and re-schedules any existing events that were already scheduled - including the one that was supposed to decrement `overlappingCounter` and close the injector.  This causes `overlappingCounter` to get out of sync with reality, as indeed the injector has been opened once that had no matching closure.

The fix is to reset that overlap counter any time we do a full reschedule that has the potential to get the world out of sync.

**Comment by mck1117** [comment]
Here's a tune that triggers the issue:
[TunerStudioDebugPackage.zip](https://github.com/rusefi/rusefi/files/4942626/TunerStudioDebugPackage.zip)
And corresponding .logicdata when enabling self stim with that tune:
[new_bad.zip](https://github.com/rusefi/rusefi/files/4942642/new_bad.zip)
![image](https://user-images.githubusercontent.com/568254/87862377-2d94cc80-c904-11ea-8526-58f0281d4940.png)

**Comment by rusefillc** [comment]
logicdata work in progress

![image](https://user-images.githubusercontent.com/48498823/87951997-47a2ec00-ca77-11ea-92ed-e1b9a6088073.png)

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/87972286-a32fa280-ca94-11ea-8d11-61fce93d7afa.png)
