### ISSUE TITLE
Batch fuel cylinder pairings are wrong

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#1593]
8 cylinder engine, firing order 18726543.

![image](https://user-images.githubusercontent.com/568254/87221291-b7023880-c31f-11ea-94b5-6970f4494904.png)

Cylinder pairings in the above trace:
1-5, 2-6, 3-7, 4-8

In reality they should be: 1-6, 8-5, 7-4, 2-3

Potentially related to #1592

**Comment by OrchardPerformance** [comment]
Hence why 1 and 5 were sticking on, its actually channel 1 that is sticking on then.

**Comment by mck1117** [comment]
Yep.  That's why that pair was sticking on.
