### ISSUE TITLE
REO Tune upload error

### ISSUE THREAD

**Issue by stefanst** [rusefi/rusefi#1598]
![Log_Upload_error](https://user-images.githubusercontent.com/709317/87229689-49362b00-c378-11ea-9ecd-9b06d15a5f6b.png)
[2020-07-01_11.00.27.zip](https://github.com/rusefi/rusefi/files/4907287/2020-07-01_11.00.27.zip)

**Comment by rusefi** [comment]
@andreika-git

**Comment by andreika-git** [comment]
https://github.com/rusefi/msqur/commit/a1a204698654eb65da8d4670f3808651c6718c9f
