### ISSUE TITLE
TunerStudio: floating VE does not work

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#160]
I have a number of 16x16 tables, all use F32 type. All but one use "1" multiplier but my VE table uses 100 multiplier.

Problem: I can edit fuel and AFR table, but I cannot edit VE table which uses 100 multiplier, which seems like the only difference between them.

	fuelTable					 = array, F32, 8248, [16x16],"ms", 1, 0, 0.0, 300.0, 2
	veTable						 = array, F32, 10552, [16x16],"%", 100, 0, 0, 100.0, 2
	afrTable					 = array, F32, 11704, [16x16],"deg", 1, 0, 0, 25.0, 2

See video: https://www.youtube.com/watch?v=V1QL0Rj7RxE

Reported by: rusefi

**Comment by OrchardPerformance** [comment]
I assume this is now fixed as no one else is talking about it?
