### ISSUE TITLE
MRE bundle has default ini

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#1611]
![image](https://user-images.githubusercontent.com/7377949/87840129-05f22580-c86c-11ea-9670-5c72af92267d.png)

**Comment by rusefi** [comment]
@chuckwagoncomputing

**Comment by rusefi** [comment]
https://github.com/rusefi/rusefi/tree/master/firmware/tunerstudio/generated has .ini files as a work-around @stefanst

**Comment by chuckwagoncomputing** [comment]
#1612 should fix this.

**Comment by chuckwagoncomputing** [comment]
This can be closed, can't it?
