### ISSUE TITLE
Weird VAG: DC motor idle valve not ETB

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#1637]
@Abricosvw has https://en.wikipedia.org/wiki/Volkswagen_Passat_(B4) which has cable driven throttle and DC motor based IAC

We would love to support this hardware configuration

According to @Abricosvw there are Toyotas the the same setup

See https://www.youtube.com/watch?v=dR5kFb1eiqw

**Comment by rusefillc** [comment]
@mck1117 any interest?

**Comment by Abricosvw** [comment]
![Screenshot_20200725-141718](https://user-images.githubusercontent.com/35018246/88463558-9e4a6480-ce81-11ea-9a4c-91b3118b2883.jpg)
![Screenshot_20200725-141725](https://user-images.githubusercontent.com/35018246/88463559-9ee2fb00-ce81-11ea-90ac-7a473fc9772b.jpg)

**Comment by Abricosvw** [comment]
Toyota have 2 flaps
One cable
One Etb idle

**Comment by Abricosvw** [comment]
![Screenshot_20200725-141944](https://user-images.githubusercontent.com/35018246/88463616-faad8400-ce81-11ea-9914-32e56e8236ff.jpg)
![Screenshot_20200725-141951](https://user-images.githubusercontent.com/35018246/88463617-fb461a80-ce81-11ea-8766-2fca97047068.jpg)
![Screenshot_20200725-142000](https://user-images.githubusercontent.com/35018246/88463618-fb461a80-ce81-11ea-89f2-47f71ec18039.jpg)

**Comment by Abricosvw** [comment]
Nissan have 2 flaps
One cable
One Etb idle

**Comment by rusefillc** [comment]
We shall focus on VAG only here to keep things easier

**Comment by rusefillc** [comment]
https://youtu.be/fQSfJgjDjwU

**Comment by mck1117** [comment]
All of the "second throttle plate" options are traction control, IIRC.  They're sprung open, and closed by the traction control computer to manage wheel slip.  I think those engines have a normal idle solenoid.

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/88482514-b11b7280-cf2f-11ea-9659-998457a9a9a3.png)

**Comment by rusefillc** [comment]
@Abricosvw reports that this works now
