### ISSUE TITLE
Idle Control Terminology

### ISSUE THREAD

**Issue by ksmola** [rusefi/rusefi#1646]
Currently we differentiate idle control by either being in  _Manual_ or _Automatic_ mode. This is in contrast to what most ECU manufacturers call _Open Loop - Closed Loop_. 

The motivation behind calling it Automatic/Manual mode was making it easier to understand for non-technical users. Big question, should we follow industry standards or find a mnemonic that's easier to use/understand?

**Comment by mck1117** [comment]
done!
