### ISSUE TITLE
pure java 3D view for romraider

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#165]
looks like romraider which we now use for table editing uses a native 3D library which is only windows or linux (see romraider / lib folder)

rusEfi codebase already has (but not uses really) another 3D map library which is used in the (currently hidden) engine stimulation pane.

we should migrate the table editor 3D view to use the 3D map tool we have in rusEfi lib/ folder

Reported by: rusefi

**Comment by OrchardPerformance** [comment]
Is this solved? Is this dead? 
Kill? 
Seems like a low priority thing as most tuning is via TS

**Comment by rusefi** [comment]
i believe we need an open source tuning option one day, not solved.

**Comment by rusefillc** [comment]
https://github.com/RomRaider/RomRaider/issues/70
