### ISSUE TITLE
invoke gen_enums_to_string

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#1655]
we have amazing actions which generate a lot but somehow not gen_enum_to_string, we shall mitigate!

maybe problem is that we do not have caching behavior in that tool? not sure.

**Comment by chuckwagoncomputing** [comment]
Is this used by documentation? Or just firmware?

**Comment by rusefillc** [comment]
firmware only

when we change enum headers we need to regenerate methods which print those enums in nice human form

**Comment by chuckwagoncomputing** [comment]
This can be closed
