### ISSUE TITLE
TunerStudio: old decimal is mixed with new numeric

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#167]
=======================
open only table editor, set values to 3.33, burn
close table, open 3D - you see 3.33 in 3D view as expected.
close 3D view, set value to 4.44 via table editor, close table editor
open 3D view - see 4.44 as expected, everything works as long as you only have either table or 3D view opened at the same time
=======================
Now the issue:
have 2.12 value in table editor
have both table editor and 3D editor opened simulaniously
set new value to 4.00 in table editor

result: 4.12 value in 3D editor, this value mixes numeric part of "4.00" with decimal part of "2.12"
=======================

https://www.youtube.com/watch?v=5Wd8iKrKNww
https://www.youtube.com/watch?v=hGH_5J0qEaM

Reported by: rusefi

**Comment by OrchardPerformance** [comment]
Assuming this has also been fixed or we would be hearing about it on slack?
