### ISSUE TITLE
SD card enabled bricks Discovery board in frankenso config

### ISSUE THREAD

**Issue by stefanst** [rusefi/rusefi#1678]
Firmware version 20200807 for frankenso bricks the discovery board when "Enable SD Card" is set to "true". 
I can write the new config, SD card will log. Everything works, but after a reboot of the board it will brick.  Erase chip and re-flash of FW will fix it. 
Tune: [https://rusefi.com/online/view.php?msq=166](url)

**Comment by mck1117** [comment]
I think this bug was fixed by #1894
