### ISSUE TITLE
Плохо правится Coolant temp fuel correction из TS

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#171]
1) Открыть ТС
2) Открыть окно Coolant temp fuel correction
3) попробовать перетягивать мышкой вершины кривой - они перепрыгивают с шагом 100, а надо 1
4) попробовать вбивать число в ячейках - иногда правится иногда нет - закономерность не понимаю

Reported by: mocia

**Comment by OrchardPerformance** [comment]
I believe this is fixed and can be closed. 
I followed the replication steps and was not able to replicate in the current version. 
Moving the curve steps by 0.01 and typing into the cells moves the curve correctly.
