### ISSUE TITLE
Android build fails in PRs

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#1712]
At the moment Android build always fails in PR due to lack of key password secret. We need the following logic:

for compilation in master
bash ./gradlew build
for compilation in PRs
bash ./gradlew bundle

for artifact upload in master
          path: ./android/app/build/outputs/apk/release/rusEFI-release.apk
for artifact upload in PRs
          path: ./android/app/build/outputs/apk/release/rusEFI-release-unsigned.apk

for FTP upload in master
        run: java_console/upload_server.sh ${{ secrets.RUSEFI_BUILD_FTP_USER }} ${{ secrets.RUSEFI_BUILD_FTP_PASS }} ${{ secrets.RUSEFI_FTP_SERVER }} . android/app/build/outputs/apk/release/rusEFI-release.apk

for FTP in PRs - nothing

**Comment by chuckwagoncomputing** [comment]
This can be closed
