### ISSUE TITLE
Tokenisation of multipler expressions

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#1735]
PHP consumer of .ini files is not ready for {1/10} syntax so we have to evaluate that in code generation

At the moment code generation does not handle comma within string token properly

"Max Air Flow, kg/h",        1,     0,  0.0,    1000.0,  1

**Comment by andreika-git** [comment]
https://github.com/rusefi/msqur/commit/2666c8a3558e57068c99dac2c6bc29bc73565570
