### ISSUE TITLE
Proteus Tunerstudio does not allow selecting digital inputs for AC switch pin setting

### ISSUE THREAD

**Issue by ZHoob2004** [rusefi/rusefi#1756]
Unable to select digital inputs 1-6 as options for ac switch pin. As-is, there is no way to configure a low-side a/c switch.

**Comment by rusefillc** [comment]
Works for me

![image](https://user-images.githubusercontent.com/48498823/92337942-d47f2480-f07a-11ea-8b56-208dc816d552.png)

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi/blob/master/firmware/config/boards/proteus/mapping.yaml looks good

**Comment by rusefillc** [comment]
this is more than just a TS problem

at the moment we have a mess with input switches - some are implemented as ADC inputs not digital inputs for historical reasons

**Comment by rusefillc** [comment]
```
	adc_channel_e hipOutputChannel;
	adc_channel_e acSwitchAdc;A/C button input handled as analogue input
	adc_channel_e vRefAdcChannel;
```

acSwitchAdc would have to be changed into acSwitch without ADC and actual pin polling code would need to be changed

**Comment by chuckwagoncomputing** [comment]
Is anyone using acSwitchAdc? Can I get rid of it without messing anyone's config up?

**Comment by ZHoob2004** [comment]
The fsio code I got from @stefanst uses acSwitchAdc

**Comment by rusefillc** [comment]
proper fix would be to convert all adc switches into digital inputs

na6 pnp uses acSwitch

**Comment by chuckwagoncomputing** [comment]
Why was it implemented as ADC in the first place?

**Comment by rusefillc** [comment]
at the time that was the quickest way to implement an input

**Comment by chuckwagoncomputing** [comment]
This can be closed

**Comment by rusefillc** [comment]
This is now fixed, ac input is now digital not adc
