### ISSUE TITLE
Plugin browsing of SD card logs limited to 16 files

### ISSUE THREAD

**Issue by stefanst** [rusefi/rusefi#1767]
It appears that the plugin only lists 16 files. And it also seems to miss the 2nd digit. So in my list the first 9 logs have sensible names, but from log 10 on they are all named "rusefi_1.mlg". assuming that mlg files with numbers of 20 and higher would be listed as "rusefi_2.mlg"

![image](https://user-images.githubusercontent.com/709317/92338796-a3a1ee00-f080-11ea-8e31-030c7f22ff35.png)

**Comment by stefanst** [comment]
This naming infidelity also causes an inability to download or delete files with numbers 10 or higher.

**Comment by rusefillc** [comment]
MS3 protocol which we do not HAVE to use but WANT to use uses legacy DOS short 8+3 file names

in light of this current RE log files prefix was changed from "rusefi_" to just "re_"

16 files is my laziness, this could be expanded but for now one can just remove files until one has not more than 16?

**Comment by stefanst** [comment]
Wow, I;m not sure I have previously run into the DOS 8+3 restriction in this millennium. Last millennium? Yes.

And sure 16 files is acceptable for now and laziness is, at times, forgivable.

**Comment by mck1117** [comment]
significantly mitigated by completing #140 via #2349

**Comment by mck1117** [comment]
Fixed by removing weird TS SD protocol, replaced with USB MSD.
