### ISSUE TITLE
Output pin init/deinit needs a linked list

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#1803]
at the moment we have too much inconsistent copy-paste around output pin management, need improvements

**Comment by rusefillc** [comment]
Same idea as #1800

**Comment by chuckwagoncomputing** [comment]
Are you going to finish this, or should I combine this and what I have done in #1800?

**Comment by chuckwagoncomputing** [comment]
And what's the reasoning behind a separate RegisteredOutputPin class rather than just including it in OutputPin?

**Comment by rusefillc** [comment]
@chuckwagoncomputing yes planning to make progress on this

Separate class for two reasons: I want to start with a subset since not 100% sure how it would apply universally. 2nd reason maybe it would be nice to separate different layers and do OOP. Better OOP would be composition not inheritance maybe in the future, do not know yet.i am just slowly moving forward

**Comment by chuckwagoncomputing** [comment]
I'm a bit surprised, as slowly moving forward is not your usual approach. I was hoping to have this functionality in place so I don't have to manage pins manually in #1752, which is otherwise ready.

Could we have a class for pin registration that could be reused by both OutputPin and ButtonDebounce?

**Comment by rusefillc** [comment]
I am pretty distracted for next 8 days :( things would probably get faster in 8+ days from now.

**Comment by rusefillc** [comment]
Status update: reality is in the way :(

**Comment by chuckwagoncomputing** [comment]
Status update? @rusefillc

**Comment by rusefillc** [comment]
I think I am finished with what I wanted to implement
