### ISSUE TITLE
Presets are not user friendly

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#1810]
Users are missing the warning on the presets dialog and still hit 'burn' and get write error. We need a better approach to preset buttons.

**Comment by rusefillc** [comment]
See https://rusefi.com/forum/viewtopic.php?f=3&t=1836&p=37875#p37875

**Comment by rusefillc** [comment]
We have two options:

1) move presets buttons from TS to plugin or console - this would hide 'Burn' button, the down side is more complexity to even locate the buttons

2) keep the UI as is but make ECU reboot on preset command

**Comment by mck1117** [comment]
Here's an idea: when a preset button is pressed, trigger a fatal error on the ECU that says "please reboot ECU to apply preset".  It'll force the user to disconnect/reconnect gracefully instead of the ECU rebooting itself.

**Comment by rusefillc** [comment]
I like this idea!!!

**Comment by mck1117** [comment]
![image](https://user-images.githubusercontent.com/568254/98032740-4ea4fe80-1dc9-11eb-85d8-3a18af4179fb.png)

Oh yeah, I like this.
