### ISSUE TITLE
unit test for launch control

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#1817]
we really need unit tests for launch control @shadowm60

**Comment by shadowm60** [comment]
i understand, it is in work

**Comment by rusefillc** [comment]
@shadowm60 poke

can I help to kick start you with this?

**Comment by shadowm60** [comment]
Yes i do need some help.

Basically how this function is working, it has a periodikTimer task that checks the activation conditions. I would need to somehow run this from unit_tests to check enable/disable conditions. I did not managed to run this from unit_test.
In the meanwhile i found a bug while testing it in the car, and i do not want to fix it if it is not urgent, and no unit tests available.

@mck1117 sad that i should check the timing calculation only, but the whole logic/important stuff is in the periodic fast timer.
I just realized i could move this in a function that it is called from periodic task, then just call this.
Let me check it today and we can discuss about it on slack.

**Comment by mck1117** [comment]
that's not quite what I said - I said you should try to refactor so that the PeriodicTask doesn't just have the whole implementation plopped in one function.

Here's an example of what I mean: https://github.com/rusefi/rusefi/pull/1967

This is much easier to write tests for, since you can test each piece individually, then mock out that that functionality to test whoever consumes it.

**Comment by mck1117** [comment]
@shadowm60 if you want help with google mocks hit me up on slack, I'm happy to help walk you through it if that'd be helpful

**Comment by shadowm60** [comment]
Ok, miss understood it then, i'll look into it and then if i still need help, we can talk, thanks

**Comment by rusefillc** [comment]
See #1972

https://rusefi.com/docs/unit_tests_coverage/firmware/controllers/algo/launch_control.cpp.gcov.html

**Comment by shadowm60** [comment]
I think this can be closed. We have 98% test covarage
