### ISSUE TITLE
cypress into GHA

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#1819]
#1790 seems to compile in master now!

next step would be including it into GHA CI

**Comment by rusefillc** [comment]
We have progress!

Now we need to fix the source code to make it compile on linux

the drama is about  #include "UsbDevice.h" vs usbdevice.h real file name 

funny think that #include "usbdevice.h" is also present!

@andreika-git need your help - what file name is right? which of imports is wrong?

**Comment by andreika-git** [comment]
https://github.com/rusefi/rusefi/pull/1821

**Comment by andreika-git** [comment]
Maybe we need to rename build_cypress -> build?

**Comment by andreika-git** [comment]
It seems that renaming didn't help.. Still cannot find build/rusefi.hex and failing? 
Can you please merge #1821 and check what's going on?
