### ISSUE TITLE
Reduce "cd .." code duplication

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#1822]
Folder structure for custom boards is very rigid and custom.sh file have to contain exactly "cd ../../.." as #1819 has shown un

Let's actually move that copy-pasted "cd ../../.." config/boards/common_make.sh if that makes sense?

**Comment by chuckwagoncomputing** [comment]
hellen needs ../../../.. because its compile script is in the cypress subdirectory. So should we have `cd ..` in its compile script?

**Comment by rusefillc** [comment]
because of  ../../../.. in hellen it was only working partially, I have since moved it one folder up and this has proven successful.

in light of that I suggest to enforce  "cd ../../.." but having it in the common place once
