### ISSUE TITLE
60/2 perf grab

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#1850]
10K
![image](https://user-images.githubusercontent.com/48498823/95006561-ea2d2e80-05d3-11eb-95ed-b363ae80eee4.png)

20K
![image](https://user-images.githubusercontent.com/48498823/95006564-f44f2d00-05d3-11eb-91dd-514fc9a4e2ea.png)

**Comment by rusefillc** [comment]
Current success rate:

![image](https://user-images.githubusercontent.com/48498823/95006646-aab31200-05d4-11eb-863a-d6ad5a352625.png)

**Comment by rusefillc** [comment]
curious thing that HW CI runs 60/2 with useOnlyRisingEdgeForTrigger = false, i.e. it uses Hall 60/2

nothing wrong about it, just that HW CI does twice the work of "regular" VR 60/2

**Comment by mck1117** [comment]
can close?
