### ISSUE TITLE
acceleration enrichment should be disabled for some time after hard rpm limit

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#187]
we should disable acceleration enrichment if we just had an rpm hard limit within the last X seconds

Reported by: rusefi

**Comment by mck1117** [comment]
this is done

**Comment by rusefi** [comment]
@mck1117 please clarify which lines of what file in your opinion is disabling AE for some time after hard limit?

**Comment by mck1117** [comment]
ok well I suppose the bug should actually be "there's an option in TS that isn't wired up to anything".  All the config is there, and it doesn't actually do anything 😛

**Comment by rusefillc** [comment]
No one seems to care
