### ISSUE TITLE
Trigger sync lost every 2^32 CPU cycles

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#1873]
Something is wrong with hardware trigger inputs - I'm losing sync exactly every 2^32 cpu cycles, or 25.59 seconds.

![image](https://user-images.githubusercontent.com/568254/95691425-03396f00-0bd4-11eb-8324-b461afdca552.png)

![image](https://user-images.githubusercontent.com/568254/95691433-12202180-0bd4-11eb-9228-c07631f68b06.png)

**Comment by mck1117** [comment]
CLT, IAT, TPS also drop out just before the trigger error

**Comment by rusefillc** [comment]
I believe I have three boards WITH this issue and one board WITHOUT

I do not have definitive data but I have a feeling that the affected boards are stm32f427 while the happy board is stm32f407

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi/releases/tag/20200831 not affected?

**Comment by mck1117** [comment]
Here's a hint:

![image](https://user-images.githubusercontent.com/568254/95693050-1d2c7f00-0bdf-11eb-8c48-cb3ceb6d148f.png)

**Comment by rusefillc** [comment]
caused by #1858
