### ISSUE TITLE
debounce unintended auto-increment bug (was: Proteus TCU gear shift configuration)

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#1927]
I have two push buttons wires between GND and

```
	// "Digital 1" green
	engineConfiguration->tcuUpshiftButtonPin = GPIOC_6;
	// "Digital 6" white
	engineConfiguration->tcuDownshiftButtonPin = GPIOE_15;
```

actual results while powered only from +5v not +12v:

start-up
![image](https://user-images.githubusercontent.com/48498823/98070987-5e0b6280-1e30-11eb-80f2-820b8b338bad.png)

if I push button on WHITE "tcuDownshiftButtonPin " button I get "3" for a moment and then it returns to "4"

if I push button on GREEN tcuUpshiftButtonPin ONCE, I get _three_ back and forth 4 > 3 > 4 > 3 > 4 on the gauge

**Comment by mck1117** [comment]
5v vs 12v shouldn't matter, the digital inputs on Proteus don't care how the board is powered.  So long as the switches are connected to ground, they should work fine.

**Comment by rusefillc** [comment]
What debugging features do I have? Do we have button event counts / can we add button even counter?

**Comment by rusefillc** [comment]
it looks like 0 and 1 are inverted which could be a configuration change but

@chuckwagoncomputing could "4" on start be a defect - do we expect button keep help keep ticking up or only tick once?

**Comment by rusefillc** [comment]
we have three separate issues here:

1) in my configuration I needed to set "pullup" mode - that I will take care of

2) BUG: at the moment if you hold the button ON forever, "events" are happening with "timeout" frequency - that's a bug. there should be only 1 event if button is not being toggled

3) WAT? we have some weirdness in the code https://github.com/rusefi/rusefi/blob/7bfa18295a5e87883d3f56e6056f76cb03f74fa9/firmware/hw_layer/debounce.cpp#L102 maybe a merge conflict resolution has left stopConfiguration() method inside readPin where it totally looks unintended?

**Comment by chuckwagoncomputing** [comment]
2 was actually intentional, but now that I think about it, it isn't what you would expect to happen.

**Comment by mck1117** [comment]
wait, what is 1? the board has hardware pullups, the setting in the config does literally nothing (unless the input needs to be inverted?)

**Comment by rusefillc** [comment]
yes, #1 does sw inverting

**Comment by chuckwagoncomputing** [comment]
I'd like some more input on changing this (And whether we should). I implemented it as it is because some buttons you want to be able to hold to continuously increment, but now I see that perhaps that should be implemented on a higher level if it is desired.
Can we decide precisely what behavior we want?

**Comment by rusefillc** [comment]
@chuckwagoncomputing let's begin from the beginning

what is the use-case for auto-increment? what is the user story here?

**Comment by chuckwagoncomputing** [comment]
The first thing that comes to mind is cruise control speed adjustment, which I use all the time when I'm driving.
I've come to terms with the fact that auto-increment shouldn't be in the basic debounce method, even if it is somewhere in the debounce class.
My question is: What SHOULD be in the basic debounce method?

**Comment by rusefillc** [comment]
since we have no cruise control plans (do we?) as of Jan 2, 2020 this is clearly a solution looking for a problem

my preference is to focus on very specific use-cases. I know that for starter we should NOT have forever starter in case of wiring issues. I know that in case of up-shift/down-shift i am NOT looking for auto-increment at this point.

**Comment by chuckwagoncomputing** [comment]
1. If I hold the button, should the debounce function return true every time it is called? Currently, we have two functions, one that does and one that doesn't.

**Comment by rusefillc** [comment]
the whole event polling model does not fit in my brain anyway

events mean listeners to me

my preference is not to touch anything here unless we HAVE to change things. please help me understand the urgency here.

**Comment by chuckwagoncomputing** [comment]
So you think this issue should be closed?
