### ISSUE TITLE
config generator is very very slow due to heavy debug logging

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#1941]
`gen_config.sh` et al are quite slow, exclusively due to their use of logging every single thing that happens.

For example:

```
matthew@WIN-MOII5AJU4GS:/mnt/c/Users/matth/github/rusefi/firmware$ time ./gen_config.sh

... output snipped ...

real    0m55.701s
user    0m21.828s
sys     0m8.438s
matthew@WIN-MOII5AJU4GS:/mnt/c/Users/matth/github/rusefi/firmware$ time ./gen_config.sh > /dev/null

real    0m6.664s
user    0m8.969s
sys     0m2.891s
```

8.4x speedup just by ignoring everything printed to stdout!

**Comment by chuckwagoncomputing** [comment]
Is this on MacOS? I just timed it (on Linux) and it took 6.569 seconds.

**Comment by rusefillc** [comment]
@chuckwagoncomputing this is not merged yet since I would like for helpful messages to not be just wiped out

**Comment by mck1117** [comment]
gen is pretty quick these days
