### ISSUE TITLE
occasional tunerstudio CRC errors 

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#1943]
I see about 1 CRC error per second when TS is updating at ~100hz.

I'm pretty sure what's happening is that another thread is preempting the TS thread during the CRC calculation, and that other thread happens to write the output channel struct.  Then when the packet is sent, the CRC doesn't match the data!

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi/pull/1944 fails CI even with https://github.com/rusefi/rusefi/pull/1947

at the moment master is green with partial rollback - only "large" method is used https://github.com/rusefi/rusefi/commit/842372e69afd0657c98c17e121ebd41dec6315fd

**Comment by rusefillc** [comment]
is it time to unit test both sr5WriteCrcPacketSmall and sr5WriteCrcPacketLarge?

**Comment by rusefillc** [comment]
this rollback seems to be making the biggest difference - https://github.com/rusefi/rusefi/commit/7cba09b3faacd8b3ffa31aa928a47fae66157390 @mck1117

**Comment by rusefillc** [comment]
👍
