### ISSUE TITLE
TPS usability issues

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#1954]
1) at the moment we have red indicator for when TPS on 1st ETB is broken but no indicator for 2nd ETB TPS issues

2) at the moment we have auto-calibrate ETB TPS feature which currently does not detect very broken TPS. very broken TPS in my case returns more or less 5v at both open and closed. in case of open and close showing such similar voltage we should probably fatal or else?

**Comment by mck1117** [comment]
part 1 done in #2016 
part 2 done in #2017
