### ISSUE TITLE
Fuel pump should turn on at the first sign of engine rotation

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#1961]
![image](https://user-images.githubusercontent.com/568254/99464351-c5bfb400-28ec-11eb-9d11-a8c8c6208adb.png)

We were cranking for 0.7 second before we got valid RPM.  When we started injecting fuel, the pump hadn't caught up yet, so fuel pressure dropped almost 150kpa as the engine started.  Had the pump been turned on at the first sign of a trigger event occuring, the pump would already be up to speed by the time we started injecting fuel.  With compensation turned on I get a noticable improvement in starting quality since the pressure drop is compensated by additional pulse width.  That same benefit is available if we don't let the pressure drop in the first place.

**Comment by rusefillc** [comment]
@mck1117 I will take care of it in the next 2-6 days

**Comment by shadowm60** [comment]
Any updates on this topic? with the cold weather, faster start-up time is a good thing.

**Comment by rusefillc** [comment]
this is falling down the priority list :( I will probably NOT make progress in the next two weeks :(

**Comment by mck1117** [comment]
If we want to be a good, usable, smart ecu...

**Comment by rusefillc** [comment]
If we want to be a good, usable, smart ecu in my opinion we have a lot of work in front of us.

@shadowm60 thank you for your DM with the magic code location, it was really helpful!

**Comment by rusefillc** [comment]
@mck1117 @shadowm60 half of implementation is pushed
in my opinion we need to implement 'time_since_shaft_movement' or something like that

also see code comments wondering if Proteus has a bug which MRE does not have due to difference in EFI_MAIN_RELAY_CONTROL? it's a bit confusing let's put it this way :(

In my dreams we would need test coverage here as well :)

**Comment by mck1117** [comment]
> EFI_MAIN_RELAY_CONTROL

eh? The main relay stays on fine, it's the fuel pump relay that doesn't turn on until valid RPM signal exists

**Comment by mck1117** [comment]
the recently added `util/timer.h` class may be of use here

**Comment by rusefillc** [comment]
@mck1117 @andreika-git  there is some magic which seems relevant here

```
	case LE_METHOD_TIME_SINCE_BOOT:
#if EFI_MAIN_RELAY_CONTROL
		// in main relay control mode, we return the number of seconds since the ignition is turned on
		// (or negative if the ignition key is switched off)
		return engine->getTimeIgnitionSeconds();
#else
		return getTimeNowSeconds();
#endif /* EFI_MAIN_RELAY_CONTROL */
```

**Comment by mck1117** [comment]
Yes, the fuel pump primes for N seconds, then turns on once we get RPM.  In the time between getting RPM signal (we also start injecting fuel!) and the pump catching up, I lose almost HALF my fuel pressure.  Priming works fine.  The pump just needs to turn on earlier so the drop doesn't happen once injections start.

**Comment by rusefillc** [comment]
fuel pump is usually controlled by FSIO
in my opinion we need to implement 'time_since_shaft_movement' for FSIO

see back-up non-FSIO implementation for reference
