### ISSUE TITLE
Starter is engaged on start-up in pull-up configuration

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#1969]
this issue is a bit different from #1965 which is already fixed:

now starter is ENGAGED on start-up until I touch toggle first time! timeout later starter is DISENGAGED, and at that point it starts to work as expected.

**Comment by rusefillc** [comment]
"set engine_type 63" to set v12 config with start button and starter control
"debounce" to see input states
"gpio_pins" to see output states

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/100301130-7ff69180-2f65-11eb-9789-80c8c1263e1f.png)

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/100301805-fa73e100-2f66-11eb-8d09-ba7d81a5c88d.png)

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/100301982-58082d80-2f67-11eb-93b9-fe1155599f7a.png)

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi/commit/47fbb92bffab8a89a2ba9b4adb1acb63a7e369a5 has changed currentLogicValue default value from "#define INITIAL_PIN_STATE -1" since that currentLogicValue was breaking pull-up debounce use-case

**Comment by rusefillc** [comment]
See https://github.com/rusefi/rusefi/pull/1990

**Comment by mck1117** [comment]
is this fixed now?
