### ISSUE TITLE
automation around outputs section

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#197]
At the moment we are manually maintaining three files with similar content:
C outputs structure
.ini outputs structure
java outputs structure

there should be one source of truth and code generation for outputs

**Comment by mck1117** [comment]
what does this mean? afaik the dev console uses TS output channels to display gauges

**Comment by rusefillc** [comment]
Yes, most of the ticket was done. the only remaining part is "auto-generating offsets (?)"

**Comment by mck1117** [comment]
why not close and create a new ticket

**Comment by rusefillc** [comment]
Progress was made we now have all the automation we need to make higher level progress!
