### ISSUE TITLE
GPPWM usability: note? code? some sort of reminder to distinguish which channel is what

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#1974]
say you have 4 GPPWM and you are supposed to remember which one is which? that's nasty

shall we add free text "Name" field? Drop-down with 256 options?

**Comment by shadowm60** [comment]
I just add comment on my window, note for me that GPPWM outputx is for function y.
I think this is the best way, user just have to use his organizational skills, i think we cannot make it better with a drop-down and put 256 possibilities that can be done with that, and of course save that option on fw.

**Comment by mck1117** [comment]
comments are now stored with gppwm
