### ISSUE TITLE
Coolant temp shows "F" in new project

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#1996]
I am not getting it. How is my coolant gauge still showing "F" even in brand new project?

![image](https://user-images.githubusercontent.com/48498823/100832621-3e1e8d00-3436-11eb-8495-e3a0c7d3ba7a.png)

**Comment by rusefillc** [comment]
@mck1117 it's a it's a bug/feature????!!!! in TS
if you re-pick the gauge (right click menu) it shows C

**Comment by rusefillc** [comment]
One day someone should ask TS people.

**Comment by mck1117** [comment]
email sent to TS folks

**Comment by mck1117** [comment]
`#set CELSIUS`

and/or

`useLegacyFTempUnits = false`

**Comment by rusefillc** [comment]
@ElDominio it says "F" while in reality it's "C"

it's TS bug which TS has resolved in recent beta, not yet resolved in release of TS

workaround is to change gauge to something not temperature and then to switch it back to CLT
