### ISSUE TITLE
all triggers should be documented way nicer

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2001]
https://github.com/rusefi/rusefi/wiki/All-Supported-Triggers is lame
we can do better

Update:
https://github.com/rusefi/rusefi/wiki/All-Supported-Triggers is much nicer now

**Comment by rusefillc** [comment]
@ksmola I wanted to ask your help with design of individual images and overall https://github.com/rusefi/rusefi/wiki/All-Supported-Triggers


![image](https://user-images.githubusercontent.com/48498823/101055576-06a80180-3558-11eb-94de-6552719c2a7b.png)

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/101056025-87ff9400-3558-11eb-9088-dff3232445e9.png)

**Comment by rusefillc** [comment]
See also https://github.com/rusefi/rusefi/issues/2022

**Comment by mck1117** [comment]
I believe this to be the tdc mark

<img width="939" alt="image" src="https://user-images.githubusercontent.com/568254/101272946-d58d2400-3745-11eb-9a61-7d4f66d587e5.png">

based on

![image](https://user-images.githubusercontent.com/568254/101272979-0ec59400-3746-11eb-84d7-e41faf4e80e1.png)

rusEFI trigger sync point is at 310 degrees ATDC #1 (aka trigger offset = 50)

**Comment by rusefillc** [comment]
by the way we can learn from https://gitlab.com/libreems-suite/ardu-stim/-/blob/master/ardustim/wheel_defs.h

**Comment by rusefillc** [comment]
just for reference, before flip & TDC on top

![image](https://user-images.githubusercontent.com/48498823/101831527-084b6980-3b04-11eb-9fb3-b6a1cbcec442.png)

![image](https://user-images.githubusercontent.com/48498823/101831566-15685880-3b04-11eb-9794-98aa25100aa8.png)

**Comment by rusefillc** [comment]
![trigger_3](https://user-images.githubusercontent.com/48498823/101845533-e7dbd900-3b1c-11eb-8a37-0f43ddcc8415.png)

**Comment by rusefillc** [comment]
![trigger_27](https://user-images.githubusercontent.com/48498823/101847049-553d3900-3b20-11eb-9c93-2c00f7b14ee5.png)

**Comment by rusefillc** [comment]
![trigger_27](https://user-images.githubusercontent.com/48498823/101847757-f24ca180-3b21-11eb-91f6-959573459906.png)

**Comment by rusefillc** [comment]
subaru

![image](https://user-images.githubusercontent.com/48498823/101850094-1494ee00-3b27-11eb-896f-36c33a0ae82c.png)

![image](https://user-images.githubusercontent.com/48498823/101850279-7a817580-3b27-11eb-8ba9-3f053b354d2d.png)

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/101850521-e49a1a80-3b27-11eb-9cfd-df21e1ac3643.png)

**Comment by rusefillc** [comment]
@chuckwagoncomputing this depends on #2059 2059

**Comment by rusefillc** [comment]
A lot of progress was made here, closing this one - will create separate tickets if new ideas (and time) happen
