### ISSUE TITLE
MRE pin reuse state validation fails - TLE FB voltage?

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2006]
![image](https://user-images.githubusercontent.com/48498823/101085894-15a1aa80-357e-11eb-8e6d-e99691b2e2fa.png)

**Comment by rusefillc** [comment]
See https://rusefi.com/forum/viewtopic.php?p=38731#p38731 for more info

it looks like we still have TLE8888 feedback and that feedback is what's causing the issue with pin state validation?

**Comment by rusefillc** [comment]
@dron0gus

**Comment by mck1117** [comment]
> it looks like we still have TLE8888 feedback and that feedback is what's causing the issue with pin state validation?

I don't think that's the problem.  In this case the pin was set to inverted, so we expected to read back a 1.  Which...we did?  So it's clearly not a hardware problem.  Software is interpreting the pin read wrong.

**Comment by mck1117** [comment]
Nope.  It's better than that.  The bug is that the validation check didn't work at all with pins set to inverted.
