### ISSUE TITLE
6.1 Hemi V8 decoder

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2010]
https://speeduino.com/forum/viewtopic.php?f=12&t=80&start=160#p42604

![image](https://user-images.githubusercontent.com/48498823/101124491-30e3d880-35c5-11eb-9fe0-914fad0fc58b.png)

"That 36+2-2 just like srt4 neon"

**Comment by rusefillc** [comment]
Well, that's a tricky wheel! it's symmetrical  for one front (16 + 16 same events) and not symmetrical on the other front (15 + 17)

weird thing is that for this to be decoded by rusEFI we would need trackingGap = 17!

Current implementation of "trackingGap = 17" would check all 17 gaps deep while this wheel decoder would be more efficient if only gap #0 and gap #14 is checked

**Comment by rusefillc** [comment]
in rusEFI it's oriented like this

![101124491-30e3d880-35c5-11eb-9fe0-914fad0fc58b](https://user-images.githubusercontent.com/48498823/101217988-49e59b80-3650-11eb-8962-806ef5926d60.png)

**Comment by rusefillc** [comment]
from right-middle point (rusEFI wheels rendering start at right-middle point), counter clockwise:

16 teeth
huge gap
15 teeth
huge tooth

===================


current reality:

16 teeth
huge gap
15 teeth
huge tooth

it matches!


![image](https://user-images.githubusercontent.com/48498823/101218230-b52f6d80-3650-11eb-919b-b23f1d70acea.png)

**Comment by mck1117** [comment]
wait - does this actually need huge gap tracking length? the huge tooth and huge gap are different widths - one is missing 2 teeth, and the other is maybe 3
