### ISSUE TITLE
launch control

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#203]
TODO add description

Reported by: rusefi

**Comment by rusefi** [comment]
Also as a patch at https://rusefi.com/forum/viewtopic.php?f=5&t=871&p=28713#p16592

**Comment by rusefi** [comment]
Alternative patch available at https://rusefi.com/forum/viewtopic.php?f=5&t=871&p=33881#p33593

**Comment by rusefillc** [comment]
there is an opinion that this is now done, will create separate tickets if any changes or issues
