### ISSUE TITLE
Passat B6 canned config: GDI injector deadtime to like flat 0.2ms

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2049]
B6 config

you should set your injector deadtime to like flat 0.2ms

no compensation for battery voltage, boost voltage on gdi board is constant

**Comment by mck1117** [comment]
Why does this need an issue? Just set the table values to all 200us or whatever.

**Comment by rusefillc** [comment]
my process is engine config in the code. I do not manually deal with tables since too many devices vehicles and context switches. GIT repo is the storage for vehicle configurations for me.

**Comment by rusefillc** [comment]
Also need to hard-code:

```
1214 cc/min
"High"
"Sensed Rail Pressure"
10000 kPa
```

**Comment by rusefillc** [comment]
this ticket is about default settings in https://github.com/rusefi/rusefi/blob/master/firmware/config/engines/vw_b6.cpp
