### ISSUE TITLE
TS, .ini: "Idle position sensor" missing label in "Wastegate and idle position sensors" menu

### ISSUE THREAD

**Issue by tmbryhn** [rusefi/rusefi#2056]
Duplicate "Wastegate..." entry in .ini TS config file.
Confirmed for "rusefi.ini" and "rusefi_proteus_f4.ini" files.

![BugReport_Idle position sensor](https://user-images.githubusercontent.com/42359163/101915730-4dd06b00-3bc6-11eb-98da-ae503b2f9eee.jpg)

**Comment by rusefillc** [comment]
@tmbryhn thank you for the report!

can you please try again? does it look better now?

if we still have an issue please post how does it display in TS in a bad way?

**Comment by tmbryhn** [comment]
Downloaded the latest rusefi-master, and it displays "Idle position sensor" now :)
I'll remember to upload pic from TS in addition next time.
Case closed.
