### ISSUE TITLE
console functional tests don't work

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#2096]
freshly downloaded console from build server:

![image](https://user-images.githubusercontent.com/568254/102576339-25ef7480-40aa-11eb-83c5-4df7215e6359.png)

**Comment by rusefillc** [comment]
yep, that's due to JUnit conversion :(

i think I know how to fix

**Comment by rusefillc** [comment]
Maybe use ant to scan for tests and write list of tests into .jar manifest property?

like http://ant.apache.org/manual/Tasks/pathconvert.html

**Comment by mck1117** [comment]
done in #2132
