### ISSUE TITLE
TCU usability

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2118]
* DBG status for solenoids

* bench test buttons for solenoids?

**Comment by chuckwagoncomputing** [comment]
Is this the DBG status referred to?
https://github.com/rusefi/rusefi/wiki/Debug-Fields

**Comment by rusefillc** [comment]
yes, but wiki could be outdated https://github.com/rusefi/rusefi/wiki/Debug-Fields

**Comment by chuckwagoncomputing** [comment]
This is done, and can be closed.
