### ISSUE TITLE
non-calibrated TPS causes FATAL. Auto-calibrate does not work in FATAL

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2151]
non-calibrated ETB TPS causes FATAL. ETB auto-calibrate does not work in FATAL

we probably want better usability here

**Comment by mck1117** [comment]
which fatal error? screenshot of TS?

**Comment by rusefillc** [comment]
this all started from bad h-bridge solder. auto-calibrate tps gets invalid settings with calibrate button. so fatal is about invalid Tps calibration

**Comment by rusefillc** [comment]
@mck1117 close this one as done?
