### ISSUE TITLE
More data into Mercedes table

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2177]
We need to merge c180 and e320 info into https://docs.google.com/spreadsheets/d/1I-lZKRajTiEGFUXdZpXEtKF2pymlOo-lPahy3cLMnl4

@shadowm60 knows about c180

https://github.com/rusefi/rusefi/wiki/1999-e320 knows about e320

**Comment by shadowm60** [comment]
C180 is updated, on the e320, i do not have all the information's regarding sensors, should i search for all of them?

**Comment by rusefillc** [comment]
@shadowm60 just some reasonable effort based on schamatics, as long as we know input/output/else it's already a lot

**Comment by rusefillc** [comment]
stale ticket we have the board ready
