### ISSUE TITLE
something going wrong with fueling

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#2193]
reproduces from the `testMazdaProtege` CI test

`set engine_type 14`
`rpm 200`
`enable self_stimulation`
`rpm 260`
`rpm 200`
`rpm 2000`

![image](https://user-images.githubusercontent.com/568254/103740355-ebdc0900-4fab-11eb-87f0-9e2606ccfbfa.png)

**Comment by mck1117** [comment]
it seems to be tps accel enrich related?

**Comment by rusefillc** [comment]
Is this a consequence of https://github.com/rusefi/rusefi/pull/2159?

**Comment by mck1117** [comment]
no, the field written by that PR is only read by TS, nothing internal to the firmware actually uses it

**Comment by mck1117** [comment]
![image](https://user-images.githubusercontent.com/568254/104107882-e107c980-5274-11eb-8d66-d8a1887cdfb3.png)

**Comment by mck1117** [comment]
problem was introduced in 4420218994661e2f598a5a375e33b76db3a8603c
