### ISSUE TITLE
2D interpolation for other than float

### ISSUE THREAD

**Issue by 960** [rusefi/rusefi#2197]
Could we have a template for 2D interpolation of other types than float?'

Like we have for 3D tables

**Comment by 960** [comment]
Just tested at a curve:

```
./controllers/algo/airmass/airmass.cpp:28:66: error: invalid operands of types 'uint8_t [8]' {aka 'unsigned char [8]'} and 'int' to binary 'operator/'
   28 |   float idleVe = interpolate2d("idleVe", rpm, config->idleVeBins / RPM_1_BYTE_PACKING_MULT, config->idleVe * PACK_MULT_VE);
      |                                               ~~~~~~~~~~~~~~~~~~ ^
      |                                                       |
      |                                                       uint8_t [8] {aka unsigned char [8]}
./controllers/algo/airmass/airmass.cpp:28:108: error: invalid operands of types 'uint16_t [8]' {aka 'short unsigned int [8]'} and 'int' to binary 'operator*'
   28 |   float idleVe = interpolate2d("idleVe", rpm, config->idleVeBins / RPM_1_BYTE_PACKING_MULT, config->idleVe * PACK_MULT_VE);
      |                                                                                             ~~~~~~~~~~~~~~ ^
      |                                                                                                     |
      |                                                                                                     uint16_t [8] {aka short unsigned int [8]}
```

**Comment by mck1117** [comment]
the error says exactly what you can't do - you're trying to multiply an array by a scalar

**Comment by 960** [comment]
But isnt that what we do with the tables bins?

Like all the coolant bins would be nice to offset -40, and scaling the values.

**Comment by mck1117** [comment]
`interpolate2d("idleVe", rpm / RPM_1_BYTE_PACKING_MULT, config->idleVeBins, config->idleVe) / PACK_MULT_VE`

**Comment by 960** [comment]
Ah, ok..

Thanks :-)

**Comment by 960** [comment]
By the way, 3d tables with different sized load axis vs rpm axis doesnt work.

Also, is it possible to use different typedefs at the axis for 3d maps?

**Comment by mck1117** [comment]
can you elaborate on "doesn't work"

**Comment by 960** [comment]
It doesnt return value from right place in map.

I dont remember exactly, but when I swapped LOAD_COUNT / RPM_COUNT in table helper it got better, but still wrong.

Tested at several tables

**Comment by mck1117** [comment]
You're going to have to give more detail than that.  What table? Real example please?
