### ISSUE TITLE
Need Connector Pictures

### ISSUE THREAD

**Issue by chuckwagoncomputing** [rusefi/rusefi#2237]
Could we get some pictures of connector faces?
I would like them placed in firmware/config/boards/<board-name>/connectors/
With the name of the file to match the .yaml file they are a photo of

- [x] Proteus
- [x] microRusEFI
- [x] Hellen72
- [x] Hellen128
- [x] Frankenso

**Comment by rusefillc** [comment]
![proteus_connector](https://user-images.githubusercontent.com/48498823/106359749-982aba00-62e2-11eb-9fa1-7c7c4d0325a0.JPG)

**Comment by rusefillc** [comment]
![hellen128_connector](https://user-images.githubusercontent.com/48498823/106359831-096a6d00-62e3-11eb-823d-19168d7677a8.JPG)

**Comment by rusefillc** [comment]
![hellen72_connector](https://user-images.githubusercontent.com/48498823/106360181-1b4d0f80-62e5-11eb-9be1-500e4a5a85ae.JPG)

**Comment by rusefillc** [comment]
Life is in the way of MRE

**Comment by rusefillc** [comment]
![microRusEFI-48](https://user-images.githubusercontent.com/48498823/107888699-fe672d80-6edb-11eb-9119-6ff76390d269.JPG)

![microRusEFI-body](https://user-images.githubusercontent.com/48498823/107888700-fe672d80-6edb-11eb-95e4-5a109fb450f6.JPG)

MRE photos are not amazing but hopefully acceptable

I need a brighter day or try at new house with Frankenso, so far Frankenso was not acceptable

**Comment by andreika-git** [comment]
This is for Hellen81 board pinout:
![Hellen81_connector](https://user-images.githubusercontent.com/15104768/107976369-1add9580-6fc2-11eb-8178-e440e9869858.jpg)

**Comment by rusefillc** [comment]
![connector64](https://user-images.githubusercontent.com/48498823/108542478-caac4f00-72b1-11eb-810b-a259f5daac92.JPG)

**Comment by rusefillc** [comment]
121 would be used on https://github.com/rusefi/hellen121vag which we hope to make open source this Sunday

121 would also be used on https://github.com/rusefi/hellen121nissan

![connector121](https://user-images.githubusercontent.com/48498823/108543706-68544e00-72b3-11eb-9ef2-6b89054a5e9b.JPG)

**Comment by rusefillc** [comment]
154 might be useful one day BigProteus or Hellen154_9.7 whatever comes first :)

![connector154](https://user-images.githubusercontent.com/48498823/108543804-8fab1b00-72b3-11eb-8f49-cd6897edc637.JPG)

**Comment by chuckwagoncomputing** [comment]
Closing this. If we need more, we can create an issue for them. Thanks for the contributions.
