### ISSUE TITLE
self-stim inverted coil

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2242]
while this is reported on Hellen I am failing to imagine how this could be a HW issue

here we have self-stimulation which causes first logical channel to be inverted
also note uneven injection while MAP is even
"miata vvt" trigger

![image](https://user-images.githubusercontent.com/48498823/105902593-daa37c80-5fec-11eb-8c62-9f0e39ecacca.png)

**Comment by rusefillc** [comment]
https://rusefi.com/online/view.php?msq=412 is the config

**Comment by rusefillc** [comment]
@stefanst also worth noting that "Miata VVT" is a special case - we only self-stimulate crank sensor not VVT cam sensor. While this should not cause this ^^^ result it's definitely a bit of a special case.

**Comment by stefanst** [comment]
It's not purely a self-stim problem. The inversion also happens with the jimstim. The signal on the jimstim is fairly authentic for crank and cam (Miata NB1 - non-VVT).
I have not checked for uneven-ness of injection using jimstim.

**Comment by rusefillc** [comment]
at this point the priority is on replicating this on non-Hellen hardware in any way shape or form.

**Comment by rusefillc** [comment]
I assume this is not an issue
