### ISSUE TITLE
hellen128 connector yaml file

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2253]
hellen128 is WIP
we have photo at https://github.com/rusefi/rusefi/issues/2237

we have pinout at https://docs.google.com/spreadsheets/d/1I-lZKRajTiEGFUXdZpXEtKF2pymlOo-lPahy3cLMnl4

**Comment by chuckwagoncomputing** [comment]
Should I create a hellen/hellen128/connectors directory? Or is it going to go somewhere else?

**Comment by rusefillc** [comment]
yes let's do hellen/hellen128/connectors for now

**Comment by chuckwagoncomputing** [comment]
Does Hellen128 have connector A? It's not in the picture, but it's listed in the spreadsheet?

**Comment by chuckwagoncomputing** [comment]
Oh nevermind, I see it now. I thought it was part of B.

**Comment by rusefillc** [comment]
A and B are especially weird on this one

**Comment by chuckwagoncomputing** [comment]
Might as well close this
