### ISSUE TITLE
Модернизировать регулятор холостого хода

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#226]
Уже есть регулятор ХХ, но он подымает обороты до нужных в течении ~1 минуты, а это ОЧЕНЬ долго
нужно сделать реакцию на проседания оборотов рескую с реским добавлением воздуха.
**Например:** Указаны у нас 1000об/мин, мозги их держат. Человек выжимает сцепление, включает 1ю передачу, и начинает трогатся с места - обороты мгновенно начинают просаживатся и машина глохнет, если не добавить воздуха
**То как нужно:** в течении 0.3 - 0.5 сек нужно реагировать на реское падение оборотов и добавлять воздух через регулятор
**Моменты: ** В большенстве авто для этих целей есть концевики отдельные, например:
1) Концевик определяющий в данный момент педаль газа полностью отпущена (человек не подгазовует)
2) Концевик нейтральной передачи/включённой передачи (что-бы знать включена-ли передача в данный момент)
можно их использовать для того что-бы определить наверняка что человек трогается с места без нажатия на газ (на холостом ходу), а значит вести какую-то более жесткую политику холостого хода (быстрее и больше добавлять воздух, не боясь поднять обороты до 1500 например, при выставленных 1000 на ХХ)

Reported by: mixal-bl4

**Comment by OrchardPerformance** [comment]
Close this one and move the (translated?) Russian to #4? 
Keep all issues on one place?

**Comment by rusefi** [comment]
I would ask @andreika-git to decide on this one

**Comment by andreika-git** [comment]
I think that both this one and #4 are obsolete and too vague. We cannot just make the idle control "better" somehow or simply "modernize" it from 2017 state (which we already did in a way). 
I think we need to close them and then:
1) test the current idle control implementation;
2) if there are any specific issues found, we create them afresh.
