### ISSUE TITLE
vBatt -> SensorType::vBatt

### ISSUE THREAD

**Issue by andreika-git** [rusefi/rusefi#2260]
We need to refactor vBatt sensor to use the new sensor C++ framework.
getVBatt() should be replaced to a more universal getOrDefault()

**Comment by rusefillc** [comment]
@mck1117 any interest at least to start?

**Comment by mck1117** [comment]
That's a thing I can do, yeah

**Comment by OrchardPerformance** [comment]
Merged, Close?

**Comment by rusefillc** [comment]
looks like we've got progress but overall clean-up not finished yet, we still have getVBatt(DECLARE_ENGINE_PARAMETER_SIGNATURE) method?

@mck1117?

**Comment by rusefillc** [comment]
we have one last piece

```
	// todo: remove this variable, replace with Sensor::get(SensorType::vbatt).value_or(VBAT_FALLBACK_VALUE)
	// todo: https://github.com/rusefi/rusefi/issues/2260
	float vBatt = 0;
```
