### ISSUE TITLE
GM/Daewoo 60/2/2/2 Trigger Pattern

### ISSUE THREAD

**Issue by hewball** [rusefi/rusefi#2264]
Trigger output from the optical sensors in my GM/Daewoo Distributor on the F8CV Engine

single inside tooth in the manual is referenced as TDC

![pattern](https://user-images.githubusercontent.com/1329868/106542060-10d98280-653e-11eb-895b-ce2a02e9d373.png)
![wheel](https://user-images.githubusercontent.com/1329868/106542066-13d47300-653e-11eb-8dde-3e79a468b218.jpg)

**Comment by rusefillc** [comment]
physical position of that single tooth looks a bit different from signal snippet maybe sensors are a bit offset?

open question if I got the relative position of that single tooth right

**Comment by rusefillc** [comment]
i assume this is done until someone tells otherwise
