### ISSUE TITLE
Акселерация по формулам

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#227]
Нинешнея акселерация при реском газе - никуда не годится. если выставить, что-бы было нормально если что более-мение реско нажать на газ и смесь была хорошей - то при реском нажатии в полный газ - смесь уже будет плохая
и на оборот, если выставить на реский в пол - то при небольшой акселерации уже будут проблемы:(
помню мы говорили, что были формулы, что-бы рассчитывать впрыск и сделать нормальную акселерацию без каких-либо доп.настроек

Reported by: mixal-bl4

**Comment by OrchardPerformance** [comment]
This is resolved by the X-tau wall wetting and the new TPS.dot enrichment. 
This can be closed.
