### ISSUE TITLE
printf via swo

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#230]
need to get SWO debug output working
see ITM_SendChar

Reported by: rusefi

**Comment by rusefi** [comment]
See also https://geektimes.ru/post/287748/

**Comment by rusefi** [comment]
http://bgamari.github.io/posts/2014-10-31-semihosting.html

**Comment by rusefillc** [comment]
@jharvey says v2 clones might not have the HW for SWO?

https://deepbluembedded.com/stm32-debugging-with-st-link-v2-swd-serial-wire-viewer/

**Comment by jharvey** [comment]
Also keep an eye on the USB drives. Windows likes to grab the wrong driver. Make sure you have the latest rev under device manager --> STM32 STLink --> update driver --> Browse my computer --> Let me pick --> should be official ST, and probably V2.1.0.0 or newer.

**Comment by jharvey** [comment]
Also make sure to upgrade the STLink programmer firmware to the latest.

**Comment by mck1117** [comment]
Do we care about swo? Console output has very good performance (tested to >1k messages per second) over USB, works on all boards, and doesn't conflict with an SPI pin like SWO does.

**Comment by rusefillc** [comment]
This came up outside of RE, we have very little priority for SWO

**Comment by mck1117** [comment]
Got it 👍

**Comment by jharvey** [comment]
Confirmed official STLinkV2 from Digikey did not have the SWO pin connected, even though it did have the "official" not 'clone" pinout. Works just fine when STM32F429-discover's SWD header is used. 
https://www.digikey.com/en/products/detail/adafruit-industries-llc/2548/6827110

**Comment by jharvey** [comment]
Also in OCD you will need to run commands something like this. 
```
monitor init
monitor tpiu config internal - uart off 168000000 250000
monitor itm ports on
monitor tcl_trace on
```
If you are connected to OCD via telnet port (4444) you need the "monitor" command. You can alternatively add those commands to an OCD launch script and if sent as switches to the OCD program, you do not need the "monitor" part of the command. 

The "tcl_trace on" is special and requires to be be sent to the tcl server which is typically on port 6666. I did this by installing Cygwin with Python3 and git. Then I ran the below commands in Cygwin.
```
git clone https://github.com/z4yx/Cortex-SWO-Decoder.git
cd Cortex-SWO-Decoder/
python3 swo_parser.py 168000000
```
The 168000000 is your SYSCLK, in my case it was 168MHz generated by a 12MHz XTAL. 

This python script will then open a tcl connection, and will send commands including "tcl_trace on" If "tcl_trace on" is not acknowledged to be successful, you will not see any ITM data on the telnet port. If all goes well you'll see the acknowledge on the telnet port (4444). If you are sending data via ITM_SendChar((uint8_t)c) or similar command, you should see that character echo'ed on the telnet port. 

You can either monitor the printed characters via the python scrips output, or you can use putty on localhost:4444 to see the telnet data.

**Comment by mck1117** [comment]
Our text logging works really well.  Not sure this is useful right now.
