### ISSUE TITLE
pinouts shall be nicer and shinier

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2351]
People have spoken - https://rusefi.com/docs/pinouts/ shall be shinier and color-coded

shall we have a default common scheme for color per function instead of coloring each individual pin?

https://rusefi.com/forum/viewtopic.php?p=39791#p39791

**Comment by rusefillc** [comment]
Relates to #2237

**Comment by chuckwagoncomputing** [comment]
Are they nice enough and shiny enough now?

**Comment by rusefillc** [comment]
Yes it is!
