### ISSUE TITLE
ETB calibrations, TS buttons wording for TPS1 and 2

### ISSUE THREAD

**Issue by rmracingelectronics** [rusefi/rusefi#2362]
On tunerstudio it is not always clear if the buttons/options refeer to TPS1 and in the throttle position sensor 1 of ETB1 or TPS as in ETB1 TPS 1 and 2, I would sugest to only use the word TPS when talking about the throttle position sensor and not the ETB itself.

**Comment by mck1117** [comment]
This is now fixed.
