### ISSUE TITLE
No channel for TPS-2 ADC count/position (redundant TPS)

### ISSUE THREAD

**Issue by rmracingelectronics** [rusefi/rusefi#2363]
I didn't found a way to see the position and calibration values for the redundant tps on ETB1

**Comment by mck1117** [comment]
it is assumed that you will use auto calibrate on an ETB

**Comment by rmracingelectronics** [comment]
Because if there is a problem on the second TPS you need to have access to info about what the ecu is seeing or you can't diagnose properly, just my 5 cent
