### ISSUE TITLE
Unit-test for FSIO built-in expressions

### ISSUE THREAD

**Issue by andreika-git** [rusefi/rusefi#2370]
We have a general test coverage for FSIO (test_logic_expression.cpp), but we need to make sure that all built-in expressions (e.g. MAIN_RELAY_LOGIC) also work or at least are valid.

**Comment by OrchardPerformance** [comment]
I think this is a good idea, especially if we want to create a few expressions to assist with engine protection. 
Any "approved expressions" that we choose to put out should be tested to work.

**Comment by mck1117** [comment]
FSIO going away, so we can close this.
