### ISSUE TITLE
better pin conflict handling

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#238]
1) проблема в следующем, есть порты PC8 PD12 PD13 PD14 PD15, они доступны в настройках, как порты выходов(к примеру форсунок), но при этом уже настроины как порты индикации лед, при этом настроек индекации нет. и конда я выбераю их как порты выхода, блок выдает критическую ошибку. 

2) также присутствует проблема с аналоговыми входами совподающие с пинами режимов загрузки, что приводит к уходу блока в тестовый режим, или загруске с базовыми настройками.

Reported by: rusefi

**Comment by mck1117** [comment]
I guess this is probably fixed or at least very stale
