### ISSUE TITLE
map 121 pin volkswagen

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2385]
need to map all 121 pins

![image](https://user-images.githubusercontent.com/48498823/108791448-1af30d80-754d-11eb-89f0-6b6993b78818.png)

https://github.com/rusefi/rusefi/blob/master/firmware/config/boards/hellen/hellen121vag/connectors/main.jpg

https://github.com/rusefi/rusefi/blob/master/firmware/config/boards/hellen/hellen121vag/connectors/main.yaml

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/108791600-758c6980-754d-11eb-933f-9f323af8df3a.png)

**Comment by mck1117** [comment]
this will be of some help: https://github.com/rusefi/hellen121vag/blob/main/boards/hellen121vag-a/board/hellen121vag-a-schematic.pdf

**Comment by rusefillc** [comment]
maybe CAM is the one missing?

**Comment by rusefillc** [comment]
CAM has stm32 not board names

https://files.slack.com/files-pri/T4NJHQ8QZ-F026UGDUM0R/received_872360346686658.jpeg

**Comment by mck1117** [comment]
Crank too

**Comment by BeerMoneyMotorsports** [comment]
Pins 82(Crank - ) and 90(Crank + ) come into this module below then it outputs crank in to GPIOB_1.  Im not sure how to map these pins correctly?

![image](https://user-images.githubusercontent.com/82395131/123819236-9ed85000-d8c7-11eb-9049-e6c1aebd0232.png)

![image](https://user-images.githubusercontent.com/82395131/123819334-b283b680-d8c7-11eb-992b-5a072cc11253.png)
![image](https://user-images.githubusercontent.com/82395131/123819432-c4655980-d8c7-11eb-8613-3296144beaae.png)

**Comment by BeerMoneyMotorsports** [comment]
I do not see an issue with the Cam pin mapping.  

![image](https://user-images.githubusercontent.com/82395131/123820276-769d2100-d8c8-11eb-9bbd-7bb16b26b135.png)

**Comment by rusefillc** [comment]
stm32 has one digital pin for crank signal
121 board connector has two pins for VR

to have both 121 board pins on the pinout le't keep both crank+ and crank- in the mapping

to have a nice stm32 name for the digital pin (PB1 you are saying?) let's have this one on crank+

and crank- would live without stm32 pin

**Comment by BeerMoneyMotorsports** [comment]
@rusefillc This is how i set it in the yaml. 

![image](https://user-images.githubusercontent.com/82395131/123821342-4efa8880-d8c9-11eb-9f78-48fcbd2bbe73.png)

**Comment by rusefillc** [comment]
function: Crank Sensor
function: IN_CRANK-

that's inconsistent

overall I am lost

**Comment by BeerMoneyMotorsports** [comment]
@rusefillc  Im not sure why it is not showing up correctly in TS?  Even with that inconsistency, it should show up "82 - VR".  Im proposing these changes below to test.  

![image](https://user-images.githubusercontent.com/82395131/123872776-8ab24400-d903-11eb-8422-45e151b2c5fa.png)

**Comment by rusefillc** [comment]
We are now blocked by https://github.com/rusefi/rusefi/issues/2880 :(

**Comment by rusefillc** [comment]
also I doubt that analog_inputs would help here :(

**Comment by BeerMoneyMotorsports** [comment]
The analog addition is to be in sync with how it is done in other yamls for the crank.   It is something i missed when first building this yaml.

**Comment by mck1117** [comment]
I don't think we want or need the analog option there.

**Comment by rusefillc** [comment]
looks like mostly done
