### ISSUE TITLE
H7 nucleo build does not have artifacts

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2389]
do we expect PR builds to attach artifacts?

![image](https://user-images.githubusercontent.com/48498823/108925848-5522e480-760b-11eb-987a-a94489b888ce.png)

**Comment by mck1117** [comment]
not just h7, no build is uploading artifacts - see the 66 warnings, 3x per build

**Comment by rusefillc** [comment]
lazy attempt pushed

**Comment by rusefillc** [comment]
did I make it worse?

**Comment by chuckwagoncomputing** [comment]
It seems to be working now. What changed that broke it?

**Comment by chuckwagoncomputing** [comment]
This is the results of trying with mre_f4.
```
david@ubuntuvm:~/rusefi$ ls firmware/deliver/
rusefi.bin  rusefi.dfu  rusefi.elf  rusefi.hex
```

**Comment by mck1117** [comment]
this is fixed I think?
