### ISSUE TITLE
MRE 0.3 F7 board fata error with CPU temp error

### ISSUE THREAD

**Issue by shadowm60** [rusefi/rusefi#2390]
Had this error today while driving at multiple times, i could not connect to anything, so it is not something that could be easily reproduced, most of the time happened while idle-ing or near idle rpm's.

![temp_error1](https://user-images.githubusercontent.com/15788573/108956267-1d9e5180-7678-11eb-8094-83d4022e550f.PNG)
![temp_error2](https://user-images.githubusercontent.com/15788573/108956283-268f2300-7678-11eb-8e86-e6b92a03839b.PNG)
 
tune: https://rusefi.com/online/view.php?msq=432
Log: <tbd> issues uploading due to bad connection

Reported error code in log: OBD_PCM_Processor_Fault = 606,

**Comment by rusefillc** [comment]
@shadowm60 please try latest firmware see change by @mck1117

**Comment by shadowm60** [comment]
Ok, i'll flash it in a few hours

**Comment by shadowm60** [comment]
@rusefillc it is working perfectly, 40 minute drive, no issues, in the same route i had 5 fails with the old sw. So from my point of view we can close this.

**Comment by mck1117** [comment]
excellent - glad it fixed it!

**Comment by rusefillc** [comment]
👍 thank you for reporting back
