### ISSUE TITLE
SD card doesn't work on H7

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#2395]
USB mass storage enumerates, but you can't actually read/write the volume

smells like something is wrong with DMA or cache

**Comment by mck1117** [comment]
spiReceive is reading an extra byte at the beginning - switching from spiReceive to spiReceiveSmall shifts the whole response over by one byte, and the SD card works properly

**Comment by mck1117** [comment]
![image](https://user-images.githubusercontent.com/568254/109058838-564e2300-7698-11eb-8066-86ab1cc5f07f.png)

**Comment by rusefillc** [comment]
and whyyyyyy?

**Comment by mck1117** [comment]
currently reading the silicon errata for the h7...

**Comment by mck1117** [comment]
Woohoo, silicon defect!

![image](https://user-images.githubusercontent.com/568254/109074815-15143e00-76ad-11eb-8a56-b9a96df8d3c8.png)

Adding a hardware reset to the MMC SPI driver just before the DMA spiSend/spiReceive calls seems to fix it, and I can read/write files without issue.

**Comment by rusefillc** [comment]
@mck1117 close or not?

**Comment by andreika-git** [comment]
Do we have a plan to fix it in master?

**Comment by andreika-git** [comment]
@mck1117 Maybe we should prepare our Chibios patch for SPI reset to fix MMC?

**Comment by rusefillc** [comment]
@andreika-git there is progress here ^^^
