### ISSUE TITLE
implement SDIO/SDMMC for SD card

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#2397]
SPI works, but SDIO/SDMMC works better.  It's a little CPU cheaper, and a lot faster.  Plus, it's not broken on the H7 like SPI.

**Comment by rusefillc** [comment]
a better clone of #683?

**Comment by mck1117** [comment]
oops, that's what I get for not searching

**Comment by mck1117** [comment]
we can close #683 too
