### ISSUE TITLE
TDC Trigger Position on rarely used triggers

### ISSUE THREAD

**Issue by hewball** [rusefi/rusefi#2428]
Cyl 1 Spark Varies based on engine position before cranking 

able to repeat cyl 1 spark location all 120 degrees apart based on engine position before starting cranking with starter

Trigger Pattern 60/2/2/2
timing set to fixed, with timing light able to reproduce as needed

![2021-03-07_11_41_16_179rpm_0_maf_0 0](https://user-images.githubusercontent.com/1329868/110239221-d752c780-7f80-11eb-8b2d-3b4530a59a0d.png)

this was one the one triggering on 0 reference on motor
![2021-03-07_11_40_40_534rpm_346_maf_0 0](https://user-images.githubusercontent.com/1329868/110239223-d883f480-7f80-11eb-8a55-f3197fc5ad80.png) 

![2021-03-07_11_40_23_765rpm_352_maf_0 0](https://user-images.githubusercontent.com/1329868/110239225-d91c8b00-7f80-11eb-942e-a720cdfe255a.png)

for more testing 
Single Tooth without Cam 

![2021-03-07_12_04_25_618rpm_0_maf_0 0](https://user-images.githubusercontent.com/1329868/110239318-43353000-7f81-11eb-80a7-6406720c7bd3.png)

Single Tooth with Cam

![2021-03-07_12_05_52_467rpm_0_maf_0 0](https://user-images.githubusercontent.com/1329868/110239327-4fb98880-7f81-11eb-8196-2d4be469c16d.png)

**Comment by rusefillc** [comment]
Thank you for the defect report! this issue has affected a few of the trigger shaped which no one uses

trigger shape has smarter self-validation now so we should be safe for all future triggers

Please report back if you see any change/progress at all?
