### ISSUE TITLE
github actions shouldn't commit ramdisk_image.h and ramdisk_image_compressed.h

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#2436]
These files are meant to be generated on demand for a build, and not checked in every time.  The action currently just commits the full diff every time, but needs to filter these out.

**Comment by mck1117** [comment]
@chuckwagoncomputing FYI

**Comment by chuckwagoncomputing** [comment]
Maybe this isn't the time and place to ask this, but what are we getting out of pushing generated configs to the repo?

**Comment by mck1117** [comment]
it's nice to be able to
```
git clone ...
cd firmware
make
```
and have it work

**Comment by mck1117** [comment]
But we don't necessarily need the tunerstudio generated stuff checked in - that could get removed, and just manually `git add` the few header files that the firmware needs to build
