### ISSUE TITLE
bench test should be more precise

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2440]
at the moment (fuel and else) bench test commands accept fractional input but in the end only use integer part of input

```
		chThdSleepMicroseconds(onTimeUs);
		output->setValue(false);
		chThdSleepMicroseconds(offTimeUs);

```

JPh is asking for this to be more precise and use the fractional number not just intereger

**Comment by mck1117** [comment]
We're limited on the accuracy of `chThdSleep*` because we tick at 1ms - so we can only sleep for integer multiples of 1ms.

**Comment by mck1117** [comment]
old system was pretty terrible - other threads could preempt, so we were really only accurate within a few hundred microseconds, which is pretty useless for injectors that have opening times of ~300us these days.
