### ISSUE TITLE
fail hard if  fuel pressure compensation mode set to "sensed pressure", but you have no fuel pressure sensor configured

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2445]
Let's FATAL in case of invalid configuration

let's also FATAL in case of a very broken fuel pressure, or at least default and warn?

**Comment by mck1117** [comment]
> Let's FATAL in case of invalid configuration

yes

> let's also FATAL in case of a very broken fuel pressure, or at least default and warn?

o, fatal error upon failed external sensor is not acceptable.  We already detect sensor failure and use the default (un-adjusted) injector flow rate

**Comment by rusefillc** [comment]
👍
