### ISSUE TITLE
false positive GHA drama

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2446]
why did https://github.com/rusefi/rusefi/runs/2092138201 fail?

**Comment by mck1117** [comment]
Here's what happened:
- Commit X triggers a build
- Commit X+1 occurs
- Build from commit X tries to push to master, but master is now in the future.

**Comment by chuckwagoncomputing** [comment]
I vote ignore this.

**Comment by rusefillc** [comment]
i cannot ignore it, its too many of these

is this made worse by image commit? lets disable image commit until we can fix it?

**Comment by chuckwagoncomputing** [comment]
OK, I thought is was rare. We can reduce the chances of it happening by pulling just before pushing.

**Comment by rusefillc** [comment]
fixed by #2447

**Comment by chuckwagoncomputing** [comment]
Is this fixed?

**Comment by rusefillc** [comment]
yes!
