### ISSUE TITLE
gen_config.sh code duplication

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2451]
At the moment we have one universal and three custom gen_config.sh scripts

we have "-firing_order controllers/algo/firing_order.h" and many related magic copy-pasted four times

we need to reduce copy-paste between those four files

**Comment by chuckwagoncomputing** [comment]
The custom scripts have:
```
 -with_c_defines false \
 -initialize_to_zero false \
 -c_defines ${BOARD_DIR}/config/controllers/algo/rusefi_generated.h \
 -c_destination ${BOARD_DIR}/config/controllers/algo/engine_configuration_generated_structures.h \
```
Additionally, the subaru_eg33 script has:
```
 -enumInputFile ${BOARD_DIR}/rusefi_hw_enums.h \
```

What do the first two lines do?
What is the purpose of the second two? Why the custom output locations?
Why does the subaru board need it's own rusefi_hw_enums.h?

**Comment by rusefillc** [comment]
Some poor documentation pushed about two lines

custom hw enum is related to

```
	MC33810_0_OUT_0 = 184,
	MC33810_0_OUT_1 = 185,
	MC33810_0_OUT_2 = 186,
	MC33810_0_OUT_3 = 187,
	MC33810_0_GD_0  = 188,
	MC33810_0_GD_1  = 189,
	MC33810_0_GD_2  = 190,
	MC33810_0_GD_3  = 191,

	MC33810_1_OUT_0 = 192,
	MC33810_1_OUT_1 = 193,
	MC33810_1_OUT_2 = 194,
	MC33810_1_OUT_3 = 195,
	MC33810_1_GD_0  = 196,
	MC33810_1_GD_1  = 197,
	MC33810_1_GD_2  = 198,
	MC33810_1_GD_3  = 199,
```

i.e. we have pretty questionable considerations for external GPIO handling. Some boards have one external TLE8888 port extended while others have two MC33810 and all this has to live in a byte for now.

**Comment by chuckwagoncomputing** [comment]
also there is ` -Drusefi.generator.lazyfile.enabled=true \`
What does this do?

**Comment by rusefillc** [comment]
@chuckwagoncomputing ``rusefi.generator.lazyfile.enabled`` was dead code, it is no longer with us
