### ISSUE TITLE
MRE adapter 94 documentation

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2462]
I think i found the issue with the no comms while in the car. Pin 1S is for usb data- but it goes to the heater controller on the chassis side.

I have removed jp23 and 24 to isolate it from the chassis

**Comment by stefanst** [comment]
Correct. Pin 1S had caused trouble before.

**Comment by rusefillc** [comment]
@stefanst please make notes on relevant wiki pages

**Comment by mi-hol** [comment]
@rusefillc I'd be happy to update wiki but due to missing URL I'm unclear and search has no good hits but only pdf docs.
What is the wiki URL?
![image](https://user-images.githubusercontent.com/22799428/214960670-b566decd-29a5-4214-9b5f-01b229d6a73e.png)

**Comment by mi-hol** [comment]
> don't care

is a strange concept to me because somebody will read the wrong information.
Only option I see is delete or correct!

**Comment by rusefillc** [comment]
Delete

**Comment by mi-hol** [comment]
@rusefillc happy to delete but need required permissions granted for organization rusefi (see my slack message)

**Comment by mi-hol** [comment]
can below MRE adapter docs be deleted too?
![image](https://user-images.githubusercontent.com/22799428/215092425-41504921-d4f7-45f2-970c-c3fdef33ec5f.png)
