### ISSUE TITLE
V-Twin support: more documentation and/or more code?

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2501]
For uneven firing order we have timing_offset_cylinder

Open question if we shall use same or similar setting for injection

**Comment by rusefillc** [comment]
270-450-270-450 could be the firing for Suzuki Intruder VS1400 GLP, 1987-2007

**Comment by OrchardPerformance** [comment]
For port fuel injection timing is less important. 
It would run just fine with the second cylinder injection "mistimed", however for completeness and GDI use it would be worth solving. 
Suggest combining this fix with individual cylinder trim.

**Comment by mck1117** [comment]
This was done in #3650, that table now controls everything for that cylinder, not just ignition.
