### ISSUE TITLE
microRusEfi "aux reuse" outputs missing from ini

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#2513]
Where did they go? They're missing from the ini.

**Comment by chuckwagoncomputing** [comment]
Can someone explain to me again what the aux reuse pins are? I asked about them when I was converting the ini, but I must not have understood well enough to get it converted properly, and now I've forgotten.

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/115155009-d3b86300-a04b-11eb-9030-93c414009dad.png)

this is about a hack extending MRE outputs count by giving four of analog inputs an alternative function of being a low side output:

same four pins could be either an analog input or low side output, depending on how 0R jumpers are populated. Not at the same time obviously.

**Comment by BeerMoneyMotorsports** [comment]
any update for this?  MRE48 utilizes AV10 as a ground output for the AC relay when AC is enabled.  This is not a selectable output in the tune.

**Comment by rusefillc** [comment]
worst case we would have to locate a version of .ini where this was working and manually fix current generated .ini files as a stop gap solution :(
