### ISSUE TITLE
linking error on jenkins and Andrey's windows desktop

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2520]
build/obj/engine_configuration.o:engine_configuration.cpp:(.rdata$.refptr.engineConfiguration[.refptr.engineConfiguration]+0x0): undefined reference to `engineConfiguration'

```
Compiling tooth_logger.cpp
Compiling log_field.cpp
Linking build/rusefi_test
/usr/lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld: build/obj/engine_configuration.o:engine_configuration.cpp:(.rdata$.refptr.engineConfiguration[.refptr.engineConfiguration]+0x0): undefined reference to `engineConfiguration'
collect2: error: ld returned 1 exit status
make: *** [rules.mk:172: build/rusefi_test] Error 1
"make -j8 all" terminated with exit code 2. Build might be incomplete.
```

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi/pull/2508

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi/commit/1dffcf5729d5fcf9d31efc6b7baf98373662dc57

**Comment by mck1117** [comment]
what compiler version do you have? can you `arm-none-eabi-gcc -v`?

**Comment by rusefillc** [comment]
that's unit test linking error

![image](https://user-images.githubusercontent.com/48498823/113495912-bff4f480-94c2-11eb-8935-ee4e63b72c97.png)

![image](https://user-images.githubusercontent.com/48498823/113495922-d13e0100-94c2-11eb-97eb-6ba8f05eca85.png)

matches 9.2.0 in issue description

**Comment by mck1117** [comment]
I would try to update if you can, I have `arm-none-eabi-gcc` 9.3.1, and `x86_64-linux-gnu-gcc` 10.2.0

**Comment by rusefillc** [comment]
gcc bump to 10.2 made no difference

make after clean:
```
Compiling tooth_logger.cpp
Compiling log_field.cpp
Linking build/rusefi_test
/usr/lib/gcc/x86_64-w64-mingw32/10/../../../../x86_64-w64-mingw32/bin/ld: build/obj/engine_configuration.o:engine_configuration.cpp:(.rdata$.refptr.engineConfiguration[.refptr.engineConfiguration]+0x0): undefined reference to `engineConfiguration'
collect2: error: ld returned 1 exit status
make: *** [rules.mk:172: build/rusefi_test] Error 1
"make -j8 all" terminated with exit code 2. Build might be incomplete.

```

![image](https://user-images.githubusercontent.com/48498823/113496273-01d36a00-94c6-11eb-82b5-65b6c967dec0.png)

![image](https://user-images.githubusercontent.com/48498823/113496276-09930e80-94c6-11eb-95ba-1b8b504cc4f3.png)

**Comment by rusefillc** [comment]
is that second time we are hitting linker optimization being different between win and unix?
