### ISSUE TITLE
Specific board just does not save configuration / always reset to default on boot

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2541]
I have a microRusEFI which just does not save config changes

```
2021-04-11_22_37_30_561: EngineState: Writing pending configuration...
2021-04-11_22_37_30_562: EngineState: FLASH_SUCCESS
2021-04-11_22_37_30_562: EngineState: confirmation_writeconfig:11
```
but on next boot everything is back to defaults

**Comment by rusefillc** [comment]
@mck1117 says

![image](https://user-images.githubusercontent.com/48498823/114797765-e0923980-9d61-11eb-838f-589784dc404b.png)

**Comment by mck1117** [comment]
either this MCU is:
- fake
- failed QC yet made it out anyway (?)
- damaged from soldering (unlikely that it's damaged exactly in to being an F429VET)

**Comment by rusefillc** [comment]
got this MCU from JLC

Thank you @mck1117 for the analysis I guess case closed

**Comment by mck1117** [comment]
I posted on eevblog for fun: https://www.eevblog.com/forum/microcontrollers/did-i-actually-find-a-defective-stm32/msg3549397/

**Comment by rusefillc** [comment]
same or similar batch @
![Uploading 20210415_142922.jpg…]()

same or similar batch
