### ISSUE TITLE
Proteus QC build not starting

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2542]
rusefi_bundle_proteus_f4_hardware_QC_special_build New Year Tomorrow works
as expected: serial port is available, 1200 RPM

rusefi_bundle_proteus_f4_hardware_QC_special_build Potato Chip Day
MSD with .ini file loads a while later, console connects but in console we see fatal error "HW" and sometimes just fails to connect to serial at all

**Comment by mck1117** [comment]
did you try a nightly?

**Comment by rusefillc** [comment]
master looks good
