### ISSUE TITLE
Log upload issue with instantrpm debug mode

### ISSUE THREAD

**Issue by stefanst** [rusefi/rusefi#2546]
The instantrpm debug mode introduces a second "drpm" field. This in turn will make the Log uploader to rusefi.online throw up it's little hands in despair and error out. 
[2021-04-12_22.28.39.mlg.zip](https://github.com/rusefi/rusefi/files/6300913/2021-04-12_22.28.39.mlg.zip)

**Comment by mck1117** [comment]
is this an internal (SD) log, or via tunerstudio?

**Comment by stefanst** [comment]
That's Tunerstudio.
