### ISSUE TITLE
DRAM SDRAM

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2551]
Sweet RAM...
there are definitely legit use-cases for RAM

**Comment by rusefillc** [comment]
https://docs.rs-online.com/b72f/0900766b815247be.pdf tells us that Discovery kit with STM32F429ZI MCU has used IS42S16400J chip

https://jlcpcb.com/parts/componentSearch?searchTxt=sdram

![image](https://user-images.githubusercontent.com/48498823/114796939-146c5f80-9d60-11eb-809b-df18ca43b824.png)

**Comment by rusefillc** [comment]
See also https://github.com/andreika-git/hellen-one/issues/29

**Comment by rusefillc** [comment]
That's community see SDRAMConfig

**Comment by rusefillc** [comment]
I have pushed some not-yet-working code a while back and no time/brain to look into this further.

Just FYU @racer-coder STM32F429I-DISC1 is in stock at digikey and it has SDRAM on board, same board @mck1117 has.

**Comment by racer-coder** [comment]
Why do we need more RAM?  It won't help older hardware, the F429 has 256k, some F7 have 512, and H743 has 1M.  Now that it's looking like even the 192k is plenty, what's the driver for this?

Downside - more variants to program, more boardspace, more complexity.

**Comment by rusefillc** [comment]
No specific use-case, very long term plan.

But I can think of build-in bare bones oscilloscope and buffer transfer, crazy Lua, whatever self-tuning stuff with https://github.com/dpilger26/NumCpp and all other kinds of crackpipe dreams.

**Comment by rusefillc** [comment]
Thank you @dron0gus !

https://rusefi.com/forum/viewtopic.php?p=43998#p43998
