### ISSUE TITLE
F4 MCU says it's too cold

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2552]
hellen72 here running pretty fresh firmware on a bench with just USB power

2021-04-14_20_40_49_996: EngineState: CRITICAL error: Invalid CPU temperature measured -54.900878906 20210407@hellen72
2021-04-14_20_40_50_216: EngineState: CRITICAL error: Invalid CPU temperature measured -54.900878906 20210407@hellen72
2021-04-14_20_40_50_434: EngineState: CRITICAL error: Invalid CPU temperature measured -54.900878906 20210407@hellen72
2021-04-14_20_40_50_656: EngineState: CRITICAL error: Invalid CPU temperature measured -54.900878906 20210407@hellen72
2021-04-14_20_40_50_768: EngineState: CRITICAL error: Invalid CPU temperature measured -54.900878906 20210407@hellen72
2021-04-14_20_40_50_983: EngineState: CRITICAL error: Invalid CPU temperature measured -54.900878906 20210407@hellen72
2021-04-14_20_40_51_203: EngineState: CRITICAL error: Invalid CPU temperature measured -54.900878906 20210407@hellen72
2021-04-14_20_40_51_422: EngineState: CRITICAL error: Invalid CPU temperature measured -54.900878906 20210407@hellen72

**Comment by mck1117** [comment]
what PN is this MCU?

**Comment by rusefillc** [comment]
@mck1117 it's F429

**Comment by rusefillc** [comment]
I believe it was a random one time thing

same board was happy before on same pretty fresh firmware

I've updated to latest and got NB2 to run

**Comment by mck1117** [comment]
I think it was briefly broken maybe a month ago, all the F42x I have report temp correctly.

**Comment by rusefillc** [comment]
I am now experiencing same on real car definitely on latest firmware

battery might be not totally charged?

i am cranking for a bit and then

![image](https://user-images.githubusercontent.com/48498823/115606792-2a26db00-a2b2-11eb-848e-9df3eff5fec6.png)

**Comment by rusefillc** [comment]
We have user report with same error on Frankenso https://rusefi.com/forum/viewtopic.php?p=40719#p40719

**Comment by rusefillc** [comment]
HW CI says Hi
```
 [junit] Testcase: testMcuTemperature took 1,562 sec
    [junit]     FAILED
    [junit]
    [junit] junit.framework.AssertionFailedError:
    [junit]     at com.rusefi.common.MiscTest.testMcuTemperature(MiscTest.java:27)

**Comment by rusefillc** [comment]
```
    [junit] Testcase: testMcuTemperature took 0,015 sec
    [junit]     FAILED
    [junit] mcuTemp is NaN
    [junit] junit.framework.AssertionFailedError: mcuTemp is NaN
    [junit]     at com.rusefi.common.MiscTest.testMcuTemperature(MiscTest.java:29)
    [junit]
```

**Comment by rusefillc** [comment]
@mck1117 Build failed in Jenkins: integration_and_primary_bundle #10129

**Comment by rusefillc** [comment]
@mck1117 it happened again :(

```
    [junit] I 210803 221841.248 [Commands Queue] BinaryProtocol - Sending [enable test_mode]
    [junit] I 210803 221841.248 [main] IoUtil - Command [enable test_mode] executed in 0
    [junit] I 210803 221841.248 [Commands Queue] IoUtil - Got confirmation in 0ms
    [junit] ------------- ---------------- ---------------
    [junit]
    [junit] Testcase: testMcuTemperature took 8,719 sec
    [junit]     FAILED
    [junit] mcuTemp is NaN
    [junit] junit.framework.AssertionFailedError: mcuTemp is NaN
    [junit]     at com.rusefi.common.MiscTest.testMcuTemperature(MiscTest.java:29)
    [junit]
    [junit] Testcase: burn took 0,281 sec

BUILD FAILED
<http://127.0.0.1:8080/job/integration_and_primary_bundle/ws/java_console/build.xml>:196: Test com.rusefi.common.MiscTest failed

Total time: 16 seconds
I 210803 221841.357 [communication executor1] MessagesCentral - postMessage EngineState: [trigger_hw_input] disabled
I 210803 221841.357 [communication executor1] MessagesCentral - postMessage EngineState: confirmation_disable trigger_hw_input:24
I 210803 221841.357 [communication executor1] MessagesCentral - postMessage EngineState: [test_mode] enabled
```

**Comment by mck1117** [comment]
The ECU sends temperature to the PC as a scaled integer.  How does it end up NAN? Integers can't do NAN.

**Comment by mck1117** [comment]
Here's your NAN:

![image](https://user-images.githubusercontent.com/568254/128261471-c03a4a9b-3ee1-4ee2-a4ec-8488f1089175.png)

**Comment by rusefillc** [comment]
Thank you @mck1117 added some wait loop

**Comment by mck1117** [comment]
why not just wait 1 second before quering temperature?

**Comment by mi-hol** [comment]
the last comments sound like issue is solved, right?

**Comment by mck1117** [comment]
we haven't seen it in forever
