### ISSUE TITLE
is this SD card log valid or not?

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2554]
![image](https://user-images.githubusercontent.com/48498823/114802025-f0624b80-9d6a-11eb-9636-48e50addd6b6.png)

[re_16.zip](https://github.com/rusefi/rusefi/files/6314680/re_16.zip)

**Comment by stefanst** [comment]
Seems to be the same underlying issue as #2546 - duplication of field names.

**Comment by mck1117** [comment]
I don't think it's a dupe - there are some fields accidentally duplicated in the SD log
