### ISSUE TITLE
Catch up with Chibios 20.3

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2555]
Chibios has some H7 bugfixes it's time for us to catch up

**Comment by rusefillc** [comment]
I've refreshed https://github.com/rusefi/ChibiOS/tree/stable_20.3.x

next step rebase https://github.com/rusefi/ChibiOS/tree/stable_20.3.x.rusefi on https://github.com/rusefi/ChibiOS/tree/stable_20.3.x

**Comment by rusefillc** [comment]
@dron0gus can I interest you in this one?

**Comment by mck1117** [comment]
Are there actually h7 changes? Afaik the only H7-specific change recently would have been the CAN driver changes that I wrote and already cherry picked in to our repo.

**Comment by rusefillc** [comment]
http://forum.chibios.org/viewtopic.php?f=7&t=5430#p39428 does mention h7 and I assume it's just a healthy thing to catch up once in a while?

**Comment by mck1117** [comment]
Fair enough.  Though it seems the FDCAN changes actually haven't been merged yet.

**Comment by rusefillc** [comment]
https://forum.chibios.org/viewtopic.php?f=7&t=5430&p=40631#p40631 mentions H7 a couple more times

@mck1117 @dron0gus poke :)

**Comment by rusefillc** [comment]
See also #3794

**Comment by rusefillc** [comment]
Just refreshed https://github.com/rusefi/ChibiOS/tree/stable_20.3.x to match upstream

**Comment by rusefillc** [comment]
just merged https://github.com/rusefi/ChibiOS/tree/stable_20.3.x into https://github.com/rusefi/ChibiOS/tree/stable_20.3.x.rusefi there were five conflicts but neither seemed to be about actual RE changes

**Comment by rusefillc** [comment]
looks like a success!
