### ISSUE TITLE
Smarter pinout re-generation

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2564]
At the moment connector pinouts are generated nightly

Would be nice to have more quick response if we change activity, do we have any simple options?

**Comment by chuckwagoncomputing** [comment]
The simplest option would be to run it on changes matching the path "firmware/config/boards/*"
That will run a lot when it doesn't need to. It would be perfect if we could do "firmware/config/boards/*/connectors/*", but I'm guessing that doesn't work.

**Comment by rusefillc** [comment]
Can we have a button _somewhere_?

Can we simply write down the URL for GHA so that I can go there and click "rerun"? Even manual button would be a way for now.

**Comment by chuckwagoncomputing** [comment]
I don't think there is a way to manually trigger a workflow run. You can re-run a workflow that has already run, but it will run on the same commit, not the newest.

**Comment by chuckwagoncomputing** [comment]
Well now that I decided to not be too lazy to google, we have #2588

**Comment by chuckwagoncomputing** [comment]
Do you see the button to run the workflow now?
Here are the instructions:
https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow#running-a-workflow-on-github

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/116320839-fd2d6900-a786-11eb-988a-2b65347ddad2.png)

**Comment by rusefillc** [comment]
That's my chance to advertise IDEA

Note syntax highlighting difference between valid and invalid

![image](https://user-images.githubusercontent.com/48498823/116321068-68773b00-a787-11eb-9736-ecb1f42a7833.png)

![image](https://user-images.githubusercontent.com/48498823/116321027-572e2e80-a787-11eb-9f6d-a18e30af761e.png)

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi/actions/workflows/gen-pinouts.yaml

shows a button now!

![image](https://user-images.githubusercontent.com/48498823/116321162-8e9cdb00-a787-11eb-8f9a-f4c095aa85fe.png)

**Comment by rusefillc** [comment]
it's green!

No idea if anything was uploaded logging is a unclear?

![image](https://user-images.githubusercontent.com/48498823/116321781-bcceea80-a788-11eb-99e0-e78a54588b2d.png)

**Comment by rusefillc** [comment]
it works thank you!!!
