### ISSUE TITLE
hellen64 scripts and pinout

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2565]
We need scripts to generate hellen64 binaries https://github.com/rusefi/rusefi/tree/master/firmware/config/boards/hellen/hellen64_miataNA6_94

We also need to finish connector https://rusefi.com/docs/pinouts/hellen/hellen64_miataNA6_94/

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi/tree/master/firmware/config/boards/hellen/hellen72/connectors is a sample

**Comment by BeerMoneyMotorsports** [comment]
Hellen64 pinout in progress.  Working on having it ready this week so we can get going with the H64 as soon as they arrive.

**Comment by rusefillc** [comment]
@BeerMoneyMotorsports we need all the "id: GPIOxx" to be filled in like in h72 See https://github.com/rusefi/rusefi/blob/master/firmware/config/boards/hellen/hellen72/connectors/main.yaml

Can you trace Injector #1 in hellen72 into something called "PG7" probably? PG7 is stm32 pin name, and GPIOG_7 is how we represent that stm32 pin name in the yaml file
