### ISSUE TITLE
Get unofficial eLua demo to compile with ChibiOS 20

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2578]
http://www.eluaproject.net/ is very promising and our friends at https://github.com/autosportlabs/RaceCapture-Pro_firmware are enjoying it https://wiki.autosportlabs.com/RaceCapturePro_Lua_Scripting with FreeRTOS

https://github.com/rusefi/chibios_with_elua is a fork of https://github.com/linvinus/chibios_with_elua

https://github.com/linvinus/chibios_with_elua is inactive for the last 6 years and it was compiled against cibios 3.0

**Comment by rusefillc** [comment]
https://habr.com/ru/company/embox/blog/496146/ about lua not eLua

**Comment by mck1117** [comment]
RC is not using eLua, it looks like they use "normal" Lua

**Comment by mck1117** [comment]
lua works, closing
