### ISSUE TITLE
MRE48 - specific board blips

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2580]
@BeerMoneyMotorsports reports that a specific MRE48 miata adapter board blips randomly once in a while on a custom vehicle

replacement board would not blip the same, customer is not happy with the replacement board

**Comment by rusefillc** [comment]
Next step: convert problematic board to be used on @BeerMoneyMotorsports own NA6

**Comment by BeerMoneyMotorsports** [comment]
This will be on the backburner a little bit while working on Hellen tasks.
