### ISSUE TITLE
No Heater + on Hellen 72

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/rusefi#2584]
no H+ marking on the Hellen72 board.  See attached pic.  possible misprint? 
![Hellen72 H+](https://user-images.githubusercontent.com/82395131/116017327-4ce82500-a60d-11eb-96a7-b0e4c5e3ad4f.jpg)

**Comment by rusefillc** [comment]
I wonder if H+ is supposed not to touch H72 due to the way OEM harness is done?

@andreika-git we need this documented on hellen72 public wiki please

**Comment by BeerMoneyMotorsports** [comment]
are we meant to use oem wiring then?  current discussions have pointed to it being a new harness from the Hellen to the sensor.  not involving the oem wiring?  Im not seeing that detail in the schematic for H72.

**Comment by andreika-git** [comment]
![module-wbo-lsu-pinouts](https://user-images.githubusercontent.com/15104768/116080216-72267300-a6a1-11eb-9c2f-49186bb12a07.jpg)

**Comment by BeerMoneyMotorsports** [comment]
@andreika-git thank you for that illustration and the conversation last night to explain it.
