### ISSUE TITLE
dev console: table editor improvements

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#259]
1) clicking on a value should copy cell value into 'set' field
2) hitting '=' key should open a small dialog for 'set' value
3) DONE borders around table groups to show which control goes with which button
4) DONE fix 'burn to controller' text to 'send to controller'
5) auto-send of some sort would be nice
6) DONE the status window should re-appear
7) DONE status window should have Burn button
8) DONE tooltip panel needs a Burn button as well
9) log 'writeconfg' into status window somehow?

Reported by: rusefi

**Comment by rusefillc** [comment]
We do not plan to replace TS with rusEFI console
