### ISSUE TITLE
too many users are getting confused by injector compensation mode

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#2597]
Lots of people should be setting "none", but are setting "fixed rail pressure"

**Comment by blundar** [comment]
This seems like a descriptive problem?

No compensation = return style regulator
Fixed rail pressure = mechanical returnless fixed pressure
rail pressure sensor, MAP = physical sensor measuring rail pressure, physical sensor measuring manifold pressure
differential sensor = physical sensor connected to both rail and manifold (Ford/Bosch style) measuring differential pressure directly

**Comment by mck1117** [comment]
We should put that text in the tool tip

**Comment by rusefillc** [comment]
@BeerMoneyMotorsports @blundar @OrchardPerformance this came up again. If we do not work smart we would have to work hard.

![image](https://user-images.githubusercontent.com/48498823/148129300-4b7b09d9-91ee-4039-86eb-111a88be2121.png)

**Comment by BeerMoneyMotorsports** [comment]
This was my mistake as i failed to read the tool tip.  @OrchardPerformance has already done his part and this ticket should be closed.  

<img width="273" alt="image" src="https://user-images.githubusercontent.com/82395131/148130534-e4010057-85c4-4a2f-9b47-3edf1cf7b5b1.png">
