### ISSUE TITLE
dev console auto-update

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#260]
most trivial console auto-update would be a huge usability improvement

Reported by: rusefi

**Comment by rusefi** [comment]
Currently users download http://rusefi.com/build_server/rusefi_bundle.zip manually, console has functionality of reading http://rusefi.com/console/versions.txt file and showing a dialog if console is outdated

A proposal would be to have a small downloader which would download latest bundle, unzip it and launch console from there.

file structure inside http://rusefi.com/build_server/rusefi_bundle.zip would probably need to be changes so that we downloader on top, and 'current' folder with a snapshot. If downloader downloads new version it renames 'current' to older version and creates new 'current.

**Comment by chuckwagoncomputing** [comment]
The autoupdater does this if I'm not mistaken. Close?
