### ISSUE TITLE
Minor scripts refactoring: reduce most obvious parameters duplications

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2607]
We have many .sh files with same
"-firing_order controllers/algo/firing_order.h"
and same "-ts_destination tunerstudio"

can we have most duplicated content into new script shared gen_common_variables.sh and have all custom scripts source the variable from there?

**Comment by chuckwagoncomputing** [comment]
How is this different from #2451?

**Comment by mck1117** [comment]
dupe dupe dupe dupe dupe

**Comment by rusefillc** [comment]
this one is a more specific suggestion not just a problem statement :) can we move all duplicated parameters into one variable?

**Comment by chuckwagoncomputing** [comment]
This should have been closed with #2451
