### ISSUE TITLE
Do we believe in onOffAlternatorLogic?

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2624]
Do we believe in bit bang mode of alternator control? Is anyone using it? Shall we refactor or kill?

**Comment by stefanst** [comment]
I'm pretty sure there's several cars where the ECU controls alternator on/off. I'm thinking Doges/Chryslers from the 90s for example. I may be wrong. My guess is that the whole point is to have it turned off during cranking.
I have 0 personal experience with this.
