### ISSUE TITLE
IAT input is being totally ignored by Frankenso

### ISSUE THREAD

**Issue by VasiliyKh** [rusefi/rusefi#2632]
Frankenso ignores an IAT sensor...
When I attached my IAT to INP1, the "raw IAT" gauge always whows 0 volts..., but in the real life, the voltage on the PC1 changes when I heat or cold the sensor.. Then I attached the sensor to INP8 and "raw IAT" is still the same but the voltage on PA3 changes every time I heat or cold the sensor. If I vice versa versa temperature sensors pins in the TS (the Frankenso takes data from the IAT and thinks that it is CLT, the same with IAT input). I can heat and cool the IAT and the CLT gauge reacts so good and fast, but the CLT (Frankenso thought it was IAT) is ignored.
Look like this is the software bug...

Can we solve it somehow?
Thank you

**Comment by rusefillc** [comment]
please paste 'tempinfo' and 'analoginfo' console commands output

**Comment by VasiliyKh** [comment]
Do you mean open the console, put "tempinfo" and send what it'll show me, right?

**Comment by rusefillc** [comment]
yes, and 'analoginfo'

**Comment by VasiliyKh** [comment]
What debug mode is better to use? 
Now I have CAN-bus in debug mode

**Comment by rusefillc** [comment]
debug mode and weather on Mars are not relevant for 'tempinfo' and 'analoginfo' console commands output

**Comment by VasiliyKh** [comment]
Thank you for information

This is for tempinfo
![image](https://user-images.githubusercontent.com/38183813/117374614-2b711e00-aed6-11eb-81b9-34dbc30beb2b.png)

This is for analoginfo
![image](https://user-images.githubusercontent.com/38183813/117374646-34fa8600-aed6-11eb-9c2d-ae51956af89e.png)


Don't look at TPSs (all throttles are disconnected now)

**Comment by rusefillc** [comment]
@mck1117 do we expect ThermistorFunc or anyone to print A, B and C?

we have one command showing zero IAT voltage while another shows non-zero voltage. is that some error handling being vague?

**Comment by rusefillc** [comment]
@VasiliyKh a link to tune would be nice

**Comment by mck1117** [comment]
Yes, please link a tune. I would like to repro on my hardware.

**Comment by VasiliyKh** [comment]
No problem, here it is
https://rusefi.com/online/view.php?msq=515

I have to admit, if I put that this is a CLT sensor (not an IAT) in the TS, but don't change anything in the hardware, the Frankenso works good with values from the sensor.  So, when it thinks that values from the IAT are values from the CLT, everything is great
It means that the problem is in the software only.. (according to my logic)

**Comment by rusefillc** [comment]
@mck1117 says "Matthew Kennedy  1:05 AM
@Kavabanga found your problem with IAT.  Congrats, you are the WORLD RECORD HOLDER for "most number of analog inputs used on rusefi"

this reminds me of the external ADC dreams

FYI @andreika-git
