### ISSUE TITLE
check MCU flash size at runtime

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#2648]
we should probably fatal error if you try to use rusEFI on a 512k device

**Comment by mck1117** [comment]
not quite complete, some MCUs require a different amount of flash, and I don't expect that to work on non-stm32

**Comment by mck1117** [comment]
For example, H7 requires 2MB because it's implemented to use dual bank.

**Comment by rusefillc** [comment]
so minor massage of the define is needed?

**Comment by mck1117** [comment]
the more complicated part is that on F7, we have to put the config in a different spot based on which device it is, and whether dual bank mode is enabled (option byte), see #2659
