### ISSUE TITLE
NA6 ini is not uploaded

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2649]
Automation does not upload NA6 .ini file

![image](https://user-images.githubusercontent.com/48498823/117516971-a256f700-af68-11eb-9225-bade6e7c2913.png)

![image](https://user-images.githubusercontent.com/48498823/117516982-ab47c880-af68-11eb-8b20-2e01c318f0fb.png)

bash regexp bug?

**Comment by mck1117** [comment]
it doesn't accept signatures with uppercase
needs to be `([a-zA-Z0-9_]+)`
