### ISSUE TITLE
does 1mb f7 work yet

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2675]
flash banks? are we covered? some magic option bit? how to validate? how to set?

**Comment by mck1117** [comment]
> flash banks?

Some STM32, including the STM32F7, have two independent flash banks.

> some magic option bit?

This feature is enabled or disabled with a bit in the option bytes, called `nDBANK`.

> how to validate?

In theory, the firmware now validates that the combination of `nDBANK` and device flash size are compatible.  A little bit more validation is required, though.

> how to set?

I do it in the "option bytes" page of STM32CubeProgrammer.

**Comment by mck1117** [comment]
See ST AN4826: https://www.st.com/resource/en/application_note/dm00266999-stm32f7-series-flash-memory-dual-bank-mode-stmicroelectronics.pdf

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/117702927-268ec180-b197-11eb-9618-49709e3f1b70.png)

not good
![image](https://user-images.githubusercontent.com/48498823/117702879-18d93c00-b197-11eb-85eb-8dfc44ea60ff.png)

**Comment by mck1117** [comment]
![image](https://user-images.githubusercontent.com/568254/117704741-0ef80e80-b180-11eb-8b2b-0091c7eac280.png)

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/117735621-d24e0680-b1c3-11eb-834e-cb41ac606f62.png)
