### ISSUE TITLE
printf format error in erase error

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2711]
Looks like erase error is trying to communicate address?

![image](https://user-images.githubusercontent.com/48498823/118412440-f5673300-b667-11eb-96e4-a8cf52446bf4.png)

**Comment by rusefillc** [comment]
@mck1117 poke error message error also error itself

**Comment by rusefillc** [comment]
#2719 does not cover this one does it @mck1117 ?

**Comment by mck1117** [comment]
@dron0gus fixed this one
