### ISSUE TITLE
Something seems wrong with H121 vag pinout

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2721]
We had a recent change in 121 yaml and no nothing gets added into the table

I assume something is not great with the yaml? Can we please fail with a more explicit error message if that's the case?

https://github.com/rusefi/rusefi/tree/master/firmware/config/boards/hellen/hellen121vag/connectors
https://rusefi.com/docs/pinouts/hellen/hellen121vag/

**Comment by chuckwagoncomputing** [comment]
I see the problem. I should have time to fix it this afternoon.

**Comment by chuckwagoncomputing** [comment]
Also @BeerMoneyMotorsports there is a tiny problem with the yaml. A pin is listed as "1a" but the coordinates are for "1A".

**Comment by BeerMoneyMotorsports** [comment]
@chuckwagoncomputing i havent gotten as far as the coordinates yet.  i will make sure those are consistent with each other whenever i get to that point.

**Comment by rusefillc** [comment]
fixed thank you!
