### ISSUE TITLE
cranking timing not costant

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2733]
![image](https://user-images.githubusercontent.com/48498823/119266701-ceee4e00-bbb9-11eb-9ef2-0b27409304fc.png)

**Comment by rusefillc** [comment]
tune https://rusefi.com/online/view.php?msq=531
log https://rusefi.com/online/view.php?log=235

**Comment by rusefillc** [comment]
i do not like minCrankingRpm static variable without a reset etc

**Comment by rusefillc** [comment]
@andreika-git do we need a check box to disable taper between cranking threshold and current RPM?

this advanced logic works really bad if all your angles are very very wrong, there should be a way to run "simplest" configuration on demand

**Comment by mck1117** [comment]
setting running mode to "fixed" will also give predictable results

**Comment by andreika-git** [comment]
> do we need a check box to disable taper between cranking threshold and current RPM?

We already have a way to disable taper if we really need to - "Use separate Advance Table for cranking". Not the best way possible but it allows to set the fixed value for cranking (if the table if filled with a constant value)...

**Comment by rusefillc** [comment]
Problem is that _no one_ knows about the taper. There is no way to know to use table if plain value is needed.

**Comment by rusefillc** [comment]
Well, maybe this could be improved by improving only the TS file not changing firmware

See also #2735

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/119272104-665f9b00-bbd2-11eb-926a-68bb7714a899.png)

![image](https://user-images.githubusercontent.com/48498823/119272108-6a8bb880-bbd2-11eb-87da-cb797f4b50ae.png)
