### ISSUE TITLE
Support dual fans

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#2739]
Two fan outputs, each should support (independent):
- on/off tempersture for hysteresis
- Enable this fan with AC

**Comment by dron0gus** [comment]
Some old JDM cars have two two-speed fans. Controlled through two signals and some relay magic. :)
![XoTsmjI](https://user-images.githubusercontent.com/28624689/119487395-fe3fbf00-bd61-11eb-8bd7-0c5c5674766e.png)

**Comment by mck1117** [comment]
Yep - similar on the C5 corvette. One signal turns on both fans in series (half voltage), and the other switches some relay magic to put them in parallel instead.

**Comment by BeerMoneyMotorsports** [comment]
i like this for miata specifically.  main cooling fan for normal function.  second cooling fan activated if temps get higher OR AC is on.  Hmm, maybe even have both fans on with AC.

**Comment by stefanst** [comment]
You don't really need the big fan if the engine is cool-ish and the AC is running. Once things get a little hotter, the big fan kicks in anyway.

**Comment by mck1117** [comment]
yeah, not as necessary on the miata, but some cars do have two fans next to each other, and run them in a high/low speed arrangement
