### ISSUE TITLE
Merch: ship out legacy T-shirt in exchange for a vague promise of a photo in that T-Shirt

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2743]
@chuckwagoncomputing has not exactly promised a photo but goes on top of the list

**Comment by rusefillc** [comment]
@BeerMoneyMotorsports second?

**Comment by BeerMoneyMotorsports** [comment]
i promise to post a pic ONLY in the shirt.

**Comment by mck1117** [comment]
I will even wear it at a race

**Comment by chuckwagoncomputing** [comment]
Please send @BeerMoneyMotorsports a XXXXL shirt.

**Comment by rusefillc** [comment]
@BeerMoneyMotorsports Done :)
