### ISSUE TITLE
Burn on VE table stops engine

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2744]
@Abricosvw reports that burn on VE table while engine is running causes engine to stall

**Comment by rusefillc** [comment]
@Abricosvw please paste youtube link

**Comment by Abricosvw** [comment]
https://youtu.be/0Jh2iLBG-J4

**Comment by mck1117** [comment]
More detail please.

- does ecu still connect?
- LEDs?
- Did it actually save the settings?
- Which ecu?

**Comment by mck1117** [comment]
@Abricosvw ?

**Comment by Abricosvw** [comment]
@rusefillc @andreika-git @dron0gus @mck1117 
https://youtu.be/bggwrzeQhsE

**Comment by mck1117** [comment]
dupe of #2839
