### ISSUE TITLE
plain ON/OFF alternator control

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#277]
there is an opinion that something much simpler than PID should control alternator just fine

See http://rusefi.com/forum/viewtopic.php?f=5&t=525&p=17744#p17739

Status update: I think the code is there and seems to be working-ish, open question is the 10ms delay is really 10ms

Reported by: rusefi

**Comment by OrchardPerformance** [comment]
This exists and works in current firmware. Suggest we close this. 

![image](https://user-images.githubusercontent.com/49926376/135775152-42a12832-6d2a-44fe-b392-ed749f856def.png)
