### ISSUE TITLE
Fuel Source for cranking triggers "please power cycle" warning

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2770]
that's unexpected

**Comment by mck1117** [comment]
ctrl-f of that string yields nothing, what is the string in the warning?

**Comment by mck1117** [comment]
poke?

**Comment by rusefillc** [comment]
discovery with a week old firmware, week old project
change "fuel source for cranking"
got
![image](https://user-images.githubusercontent.com/48498823/120431714-db577100-c346-11eb-82e1-a7aecc9f3bba.png)

**Comment by mck1117** [comment]
No cranking settings are marked with `requiresPowerCycle`, so I'm not sure what you saw.

**Comment by rusefillc** [comment]
I know! Yet @dron0gus and myself say it at the garage and the image above is me reproducing this with a discovery in 10 seconds

**Comment by mck1117** [comment]
no way it repros for me too connected to simulator

**Comment by rusefillc** [comment]
Welcome to IT, or probably more like welcome to TS

**Comment by mck1117** [comment]
moved to ts-issues repo

**Comment by LT401vette** [comment]
Power cycle required is monitored at the defined data type level, in this case a U32, not bit level.  useRunningMathForCranking is a bit field sharing that U32 with etb_use_two_wires which is set to requiresPowerCycle.
I will evaluate the impacts of monitoring at the bit level.

**Comment by LT401vette** [comment]
Making this byte level should not be difficult, Taking it to the bit level would require changes to the framework. That would have greater impacts. Certainly not something to be done in a patch release.

**Comment by LT401vette** [comment]
After a thought, I came up with another way to track the bit fields. Implemented for next beta.
