### ISSUE TITLE
rusefi.ini usability issues

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#279]
In general: 
- I would have all pins default to "NONE" instead of PA0. (Andrey: looks like that's only if you do not read initial state from ECU, that's because zero value is PA0 and not NONE)
- In many cases the name of the menu point differs from the name displayed on the window. This confuses me... (fixed)

-  Fuel correction coefficients: There are a plethora of fuel correction coefficients. But how do they modify fuel? Are they a multiplier for pulsewidth (100% means unmodified PW), or are the additive (0% means unmodified PW)?

1.3. Injection settings
- Injector Open Time (msec). I assume this is "Dead Time". I suggest to rename to Dead Time since that's also used in the table on the right
- phase offset: what's that?
- Injector Dead Time Battery Correction: value appears to be ms/V. So if my Dead Time at 13.6V is 1.36ms (which happens to be the case for my injectors) it would be 0.10ms/V at 13.6V? If so, why do we need "Open Time" at all? Or is this an adder/multiplier for "Open Time"?

1.4. Ignition settings
- My car definition is set to 4 cylinder, wasted spark. But in ignition settings I get to fill out 4 of the 6 ignition pins. What are they? I'm only using two pins with WS.

(as an aside here, the pinout table https://docs.google.com/spreadsheets/d/1G8olOoZOSNjRBk2r0EeqKDDZw9X7n2TUZjAuxP7xtkA/edit#gid=0 shows 3 ignition/spark output pins and 5 injectors. Somebody must have built one weird-as-hell engine!)

1.6. MAF Sensor
- I'm not running MAF, so don't care personally, but there's no way to select a pin.... Never mind, found it further down the line under "Other Inputs" - could use a relocation.

1.7. Battery and Alternator Settings
- Battery Input Divider Coefficient(coef). Did you have a German name that one? And what does it do- is it a multiplier?
- PID control: dTime. Is that how often the loop runs?

1.9. Tach Output
- What is "Rise at trigger Index"?

1.10. Other Inputs
- TPS. How do I calibrate this? 
- Baro ADC: Same: How do I calibrate?
- The two coefficients are presumably for calculating baro correction- correct?

2. Tuning
2.1. General
- Difference between MAP and Speed-Density?
- I can select a "Sensor Chart", but don't know, what they are, or where they are to be entered

2.2. Cranking duration correction
- Looks like this should be some sort of taper? Maybe from 100% at 0 events down to 50% or so at 100 events?

2.3. Warmup AFR correction
- Are we correcting target AFR here? Or PW?

2.4. Warmup AFR auto correction
- A PID doing exactly what? (I'm not really currently interested in this. Manual correction is fairly trivial except for accel enrichment under warmup conditions)

2.5. Coolant based target AFR
- Doesn't really make sense, since we have a 3D target AFR table. We'd need a coolant-temp based table modifier....

2.6. Target AFR table
- Is this actually used in the fueling calculation? I.E. If I change target AFR during my tuning from 10 to 9, does the ECU automatically know to inject 10% more fuel?

Reported by: rusefi

**Comment by rusefillc** [comment]
Great news most was really addressed in the last six years
