### ISSUE TITLE
We have just doubled bundle file size from 14M to 28M

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2797]
rusefi_simulator output settings change has increased simulator binary size from 1M to 30M, that has doubled rusefi_bundle download size

Do we care or are we happy to keep as is?

**Comment by mck1117** [comment]
Oops, that's pretty bad.  Let's not do that.

**Comment by rusefillc** [comment]
We are back to 17M

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/120969575-500c2000-c738-11eb-9a3f-682df04eac0a.png)
