### ISSUE TITLE
inhibit starting without oil pressure

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#2799]
I may or may not have started an engine this weekend without any oil in it.  We have software, let's prevent that!

**Comment by rusefillc** [comment]
I like it

**Comment by mck1117** [comment]
I think the right thing to do is have two parameters:
"minimum starting oil pressure"
and
"minimum running oil pressure"
There are a few corners at The Ridge Motorsports Park that we can hit very low oil pressure (<10 psi where there should be 50) for about a second (low load, going over a big crest in a hard left hand corner) where we don't want the engine to cut out, but it's perfectly reasonable to inhibit start without oil pressure.

**Comment by rusefillc** [comment]
I think preventing from cranking is legit while we probably never want to completely shut engine off?

**Comment by mck1117** [comment]
Looking at some logs of oil pressure during startup it might need to be a little smarter.  Something like "if oil pressure doesn't go above X within Y seconds of start, kill engine".  Simply waiting for oil pressure before firing could significantly increase start time, especially on a really cold engine that's been sitting for days (draining oil out of places, so you have to displace air first).

**Comment by mmatousek89** [comment]
lets do it other way, start engine, and if there is no "given pressure" within "given delay" then fuelcut for "given shutdown time"

**Comment by mck1117** [comment]
@mmatousek89, that's exactly what #2800 does.
