### ISSUE TITLE
h121 pps1 pin conflict

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2801]
in hellen121vag yaml looks like same EFI_ADC_3 was used twice: PPF1 and IN_RES2

1) short term need a fix in hellen121 yaml
2) long term open question if pinout generator should be failing faster in case of similar pin conflict?

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/121179944-42d15d00-c82e-11eb-9752-2347b6a4f8ca.png)


@andreika-git does ADC channel 3 support two different pins while we do not support this in FW? if not what's your take on this pinout use case, is that related to the missing ADC flexibility?

**Comment by andreika-git** [comment]
1) First of all, PF10 is not EFI_ADC_3, it's EFI_ADC_8.
2) BUT. That EFI_ADC_8 is for ADC3, not ADC1/2. So as long as we don't support ADC3 for slow analog inputs (yet), it's better to remove it from IN_RES2 for now.
That is, some pins may share the same ADC channels, but on different ADCs: one on ADC1 or 2 and another on ADC3. So this is only related to ADC3 drama.

**Comment by rusefillc** [comment]
perfect, we've clarify h121 specific

goes to @chuckwagoncomputing to have generator fail in case of duplications not just use latest override

**Comment by chuckwagoncomputing** [comment]
So this is the way yamls are parsed:
```
for every yaml file
    for every pin
        add pin to array which matches the class
for every class array
    add all pins to relevant registry
```
So how do we solve this issue?
If we don't care about pins that are duplicated between different yams, we can do this:
```
for every yaml file
    for every pin
        for every pin
            skip this pin if it isn't this pin, but still has a matching ID
        add pin to array which matches the class
for every class array
    add all pins to relevant registry
```

Is this good enough, or do we need to cross files too?

**Comment by rusefillc** [comment]
for every pin
   throw error if already used

**Comment by chuckwagoncomputing** [comment]
You misunderstood my question. If already used in this yaml file, or in any yaml file for this build?

**Comment by rusefillc** [comment]
any yaml i guess since total registry is what mappers?

**Comment by chuckwagoncomputing** [comment]
OK so I guess we need something like this:
```
for every yaml file
    for every pin
        add pin to array which matches the class
for every class array
    for every pin in array
        for every class array (starting at this one, so we never compare the same two pins twice)
            for every pin in array (starting at this one, so we never compare the same two pins twice)
                throw error if pin isn't this pin, but still has a matching ID
    add all pins to relevant registry
```

**Comment by rusefillc** [comment]
could set/map/dictionary be more appropriate here?

for every yaml file
    for every pin
        check if already in set/map/dictionary
            throw error if yes
        add pin to set/map/dictionary which matches the class
