### ISSUE TITLE
ETB: do not disable control pins in two wire mode

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2802]
we should not disable control pin in two wire mode

**Comment by mck1117** [comment]
I don't think we do disable it?

Remember, "control pin" = enable pin (high when ETB allowed, low when ETB stop)

![image](https://user-images.githubusercontent.com/568254/121234050-27734b80-c848-11eb-8622-f63588595ea7.png)

My reading of the code is that in two wire mode, it pins the enable pin high.

**Comment by rusefillc** [comment]
I was vague this was about TS project settings see commit
