### ISSUE TITLE
Strange options names for "Clutch input inverted"

### ISSUE THREAD

**Issue by dron0gus** [rusefi/rusefi#2808]
"DEFAULT", "PULLUP", "PULLDOWN".
Suppose it should be "true" and "false".
![Screenshot from 2021-06-11 00-21-48](https://user-images.githubusercontent.com/28624689/121599087-41c94700-ca4b-11eb-875e-b60f185bb9c9.png)

**Comment by mck1117** [comment]
we also can't really change the pullup/pulldown behavior of hardware pins, except with some smart gpio that @dron0gus has on his board

**Comment by dron0gus** [comment]
```
bool LaunchControlBase::isInsideSwitchCondition() const {
....
	case CLUTCH_INPUT_LAUNCH:
		if (isBrainPinValid(CONFIG(clutchDownPin))) {
			engine->clutchDownState = efiReadPin(CONFIG(clutchDownPin));
			
			if (CONFIG(clutchDownPinMode) == PI_PULLDOWN)
			{
				return !engine->clutchDownState;
			} else {
				return engine->clutchDownState;
			}
```

But also

```
	if (isBrainPinValid(CONFIG(clutchDownPin))) {
		efiSetPadMode("clutch down switch", CONFIG(clutchDownPin),
				getInputMode(CONFIG(clutchDownPinMode)));
	}
```
I think this should be two separate options: one to set PULL mode another one to set inverted.

**Comment by mck1117** [comment]
yes - I like that better.  
I think it should be:
- pullup mode: pulldown, pullup, floating (hide on boards without capability)
- polarity: active high vs. active low (#2613!)
