### ISSUE TITLE
inhibit closed loop idle until after the cranking -> running taper

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#2813]
Let the cranking->running idle taper happen without closed loop trying to mess with it.

**Comment by stefanst** [comment]
Any progress on this? I just slammed into a problem with IAC valve dropping right after cranking.

**Comment by rusefillc** [comment]
my start is now weird i wonder if my start is weird for same reason. will post logs today

**Comment by rusefillc** [comment]
is https://rusefi.com/forum/viewtopic.php?p=41684#p41684 relared to this issue?

**Comment by mck1117** [comment]
I think this is properly fixed now after #3051.
