### ISSUE TITLE
Alex and Abricos are complaining about fuel

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2828]
New

Alex Miculescu  10:14 AM
@Matthew Kennedy did we changed something drastical in fuel algo?
10:15
image.png 
image.png

10:15
i have <50 VE in the table, but ecu is using > 50
10:15
car runs like crap
:+1:
1

10:15
started autotune today to make it home at least
10:16
it's like VE would not be extracted from the table at all
10:17
i have a trace with VE 7 in the table in the fuel:ve shows 64....
10:17
engine is hot, multipliers are all at 1.0
10:20
https://i.imgur.com/4fWBmMy.png

(200 kB)
https://i.imgur.com/4fWBmMy.png

10:20
looks like i cannot upload the log
10:20
the current tune is uploaded

Matthew Kennedy  1:23 PM
Do you have idle ve table enabled?

abricosvw  4:06 PM
Something really not good
4:06
I have same ve problem

Matthew Kennedy  4:18 PM
my engine runs fine
4:18
idk

Matthew Kennedy  4:30 PM
@Alex Miculescu check "engine load accel enrichment"
4:34
wow autotune has made a real mess of your VE map

Alex Miculescu  4:45 PM
it is a real mess with autotune
4:45
but it looks like it would not react to ve table
4:45
i do not have idle ve table enabled

Matthew Kennedy  4:45 PM
can you try turning off the load AE

Alex Miculescu  4:45 PM
i did auto update (dfu mode, console did not connected to the board, so i used the ST tool to connect to the board and flash)
4:46
i will try tomorrow the debugger reflash
4:46
AE is multiplier 0
4:46
taper all 1.0
4:46
i have only TPS enrichment
4:46
https://i.imgur.com/JDhkRmm.png

(33 kB)
https://i.imgur.com/JDhkRmm.png

4:46
ups
4:46
it is not off
4:46
it was off at one point
4:46
and the same issue
4:47
in the morning when i left, i was lean as f**
4:47
then started auto tune
4:47
it was "fine" for a while, and after 10km it got rich
4:47
and could not control it any more
4:47
it looks like VE is not modified, like it would run on an old ve, that i do not have access to
4:47
did EEPROM layout changed?

stefanst  4:48 PM
link to tune?

Alex Miculescu  4:48 PM
i had the last release and my car was fine, then sarted with two updates (10 jun and 16jun) nightly and non worked ok with the VE

Matthew Kennedy  4:48 PM
https://rusefi.com/online/view.php?msq=559

rusefi.comrusefi.com
rusEFI online
rusEFI tune file sharing site
4:48
layout hasn't changed

Alex Miculescu  4:49 PM
How did you reflashed you're car?
4:49
debugger our usb update?

Matthew Kennedy  4:49 PM
shouldn't matter
4:49
signature matches between TS and fw?

Alex Miculescu  4:49 PM
with debugger i noticed full erase, with ST usb i noticed, that my tune was still on the stm
4:50
signature is ok
4:50
TS did not throw any errors

Matthew Kennedy  4:50 PM
debugger doesn't necessarily do full erase

Alex Miculescu  4:50 PM
this is the only think i know it is different, dfu would keep old config, debugger i erase all
4:50
i always did a full erase with debugger :slightly_smiling_face:

Matthew Kennedy  4:50 PM
ok

Alex Miculescu  4:51 PM
i will try in the morning, to get to the ecu and see if there is a difference
4:51
worst case i fall back to last release
4:51
since i need the car

Matthew Kennedy  4:51 PM
alex I mean the "Engine Load (alpha version)" section

Alex Miculescu  4:51 PM
BTW i am preparing for a new test mule (a4 b5 1.8T ) :smile:

Matthew Kennedy  4:51 PM
oooh
4:52
set both multiplier to 0

Alex Miculescu  4:52 PM
angine load Alpha was off, when i left from work, then i stoped at the kindergarded and fall back to the morning tune, but the same issue

Matthew Kennedy  4:52 PM
but it's not off in your tune

Alex Miculescu  4:52 PM
at crancking the VE is ok, but after engine started i notice the delta

Matthew Kennedy  4:52 PM
it's enabled

Alex Miculescu  4:53 PM
it is not off in the tune

Matthew Kennedy  4:53 PM
"Accel multiplier" and "Decel multiplier" should be 0

Alex Miculescu  4:53 PM
https://i.imgur.com/2mk0Zen.png

(217 kB)
https://i.imgur.com/2mk0Zen.png

4:54
anyhow it should not change VE difference
4:54
since load is a multipilier
4:54
that is applied later in the pipeline

Matthew Kennedy  4:54 PM
not quite
4:54
that section modifies the map value to predict what the map will be in a moment
4:54
but it should still select a value that is in the VE table
4:55
I see no 72 in that column of the VE
4:55
so something weird is going on

Alex Miculescu  4:55 PM
yes, and @abricosvw noticed the same issue
4:55
what fw are you running on you're car?

Matthew Kennedy  4:55 PM
let me flash master

Alex Miculescu  4:56 PM
get latest nightly it should be the same

Matthew Kennedy  4:56 PM
nightly == master

Alex Miculescu  4:56 PM
and do a dfu update

stefanst  4:56 PM
Was that DURING autotune? I think you have to tell autotune to use the new values and not the old ones.

Alex Miculescu  4:56 PM
yes (but when you say master -> i am thinking you just hit build, not download :slightly_smiling_face:
4:57
no
4:57
it can be reproduced, with autotune off
4:58
so engine off, i see the correct VE reported (that initial ve is really constant ) and after crancking, while idle-ing i can see it is different
4:58
and even if i change VE thabel
4:58
table, i would expect that log would report new VE

stefanst  4:58 PM
Agreed.

Alex Miculescu  4:58 PM
but no, it looks like it is something old, but i do not get burn errors, or something
4:59
i was absent for a few months and i do not know all the changes, so i do not have any hints what could do this
4:59
i only know that last rel was ok, and 10 and 16th of june nightly was not ok

Matthew Kennedy  5:01 PM
release from may was OK?

Alex Miculescu  5:02 PM
yes

Matthew Kennedy  5:10 PM
Image from iOS 
Image from iOS

5:12
running on latest, looks ok
5:12
now I will DFU over the top the last release

Alex Miculescu  5:14 PM
@abricosvw what stm are you running? is it f7?

18 replies
Last reply 19 hours agoView thread

Matthew Kennedy  5:15 PM
I am on f7 btw
5:15
and h7
5:17
old FW works fine with identical binary tune contents on mcu flash

Alex Miculescu  5:21 PM
i did a reflash with st link on my spare ecu, and it looks ve is read correctly, i will try tomorrow to reflash the ecu from the car with stlink, to see if that would do the trick
5:21
something is fishy

Matthew Kennedy  5:27 PM
alex do you have a 2MB f7 configured in dual bank mode?

Alex Miculescu  5:28 PM
i have the old mre 0.3

Matthew Kennedy  5:28 PM
I think factory default is for single bank
5:28
so it is probably 2MB then

Alex Miculescu  5:28 PM
i think it is single banck

Matthew Kennedy  5:28 PM
F76xVIT?
5:28
I think default is for nDBANK=1, aka single bank

Alex Miculescu  5:29 PM
VIT
5:29
32f767VIT6

Matthew Kennedy  5:29 PM
ok
5:29
I only have F7 ZGT to hook up to a running car
5:30
and f4 of course
5:30
and H7 :slightly_smiling_face:

Alex Miculescu  5:30 PM
but f4 fails for @abricosvw so .... i think we need to focus on what is the same?

Matthew Kennedy  5:33 PM
and last release doesn't stop engine when you push burn?

Alex Miculescu  5:37 PM
It stopped

Matthew Kennedy  5:38 PM
oh it does?

Alex Miculescu  5:38 PM
So they are not related

Matthew Kennedy  5:38 PM
I mean that's still a bug, it didn't used to do that

Alex Miculescu  5:38 PM
Ve issue is fresh for me
5:39
I can test in the morning release candidate
5:39
I cannot do it now, need to wake up in 5h

Matthew Kennedy  5:39 PM
oof
5:40
@abricosvw hey

Alex Miculescu  5:52 PM
Btw, i could not upload tune because no load info, could this be connected?

abricosvw  6:00 PM
It stop

Matthew Kennedy  6:02 PM
any config parameter change, then burn?
6:02
only ve table?

abricosvw  6:18 PM
Not only VE... air ,coolant , timing (edited) 

Matthew Kennedy  6:18 PM
what do ECU LEDs do?

abricosvw  6:18 PM
I don't know:pensive:

Matthew Kennedy  6:19 PM
I wonder if yours is hard faulting
6:19
or fatal erroring

abricosvw  6:19 PM
I forget to check led all the time
6:19
My ecu under hood

Matthew Kennedy  6:27 PM
@abricosvw did you post tune?

abricosvw  6:29 PM
I upload old bundle in ecu ...
I have old tune  ...
5sec I upload

abricosvw  6:36 PM
IMG_20210617_183557.jpg 
IMG_20210617_183557.jpg

6:36
Not work
6:36
:pensive:
6:37
New TS
6:37
Update

Matthew Kennedy  11:00 PM
@Dave B. any bright ideas about how to build the configuration for injector comp such that everybody is happy
11:00
I think I can figure out a performant way to actually do it

Dave B.  11:00 PM
"everyone is happy" - eat shit

Matthew Kennedy  11:00 PM
but my question is around the shape of the configuration
11:00
lol
11:00
ok, make a few people happy

Dave B.  11:00 PM
do it so it works well?  sure

Matthew Kennedy  11:00 PM
and make most aftermarket/oem injectors (for which we have data) easy enough to configure

Dave B.  11:01 PM
the two most elegant models IMHO are 05-10 Ford with pressure compensation and 08-14 GM with pressure compensation
11:01
I think that closely copying an OEM model is a very, very, very good idea

Matthew Kennedy  11:01 PM
yes, I'm inclined to agree
11:01
is one easier to convert to the other?

Dave B.  11:02 PM
why? because it will make injector data provided by manufacturers who care accessible
11:02
ford is better suited to floating point / math
11:02
gm is better suited to fixed point
11:02
IMHO

Matthew Kennedy  11:02 PM
meh don't care
11:02
converting to floating point is cheaper

Matthew Kennedy  11:03 PM
plus I think whatever it is we can linearize around the current operating point to compute the "last chance" adjustment

3 replies
Last reply 13 hours agoView thread

Matthew Kennedy  11:03 PM
for transients

Dave B.  11:06 PM
you know who has really good explanations?
11:06
injector dynamics.
11:09
http://injectordynamics.com/articles/ford-injector-characterization/

Injector DynamicsInjector Dynamics
Ford Injector Characterization - Injector Dynamics
Ever wonder what all those values mean? Or why they are needed? Here's a quick explanation. If we get enough requests, we may expand this article with further detail.
Dec 1st, 2013 (557 kB)
http://injectordynamics.com/articles/ford-injector-characterization/

11:09
http://injectordynamics.com/articles/gm-injector-characterization/

Injector DynamicsInjector Dynamics
GM Injector Characterization - Injector Dynamics
Ever wonder what all those tables mean? Or why they are needed? Read this in preparation for your next keyboard racing event.
Dec 1st, 2013 (19 kB)
http://injectordynamics.com/articles/gm-injector-characterization/

11:10
temporarily hold your nose at the sales pitch

Matthew Kennedy  11:11 PM
Image from iOS 
Image from iOS

Dave B.  11:12 PM
I can get much more in depth explanations of both

Matthew Kennedy  11:12 PM
in the non-time-critical part, we can use the estimated pulse width to figure out where we'll be on the curve

Dave B.  11:12 PM
look at the ford explanation
11:13
they divide the injector operation into a linear region (high slope) and the result of the non-linear region (low slope)
11:13
with a latency that is applied
11:14
pulsewidth = latency + (time1 * low slope) + (time2 * high slope)
11:14
but it's not quite that simple because breakpoint is a quantitty of fuel not a time

Matthew Kennedy  11:14 PM
yeah I know
11:14
I mean in case we want to support the table as well

Dave B.  11:15 PM
huh?
11:15
have you seen OEM ford injector data?

Matthew Kennedy  11:15 PM
GM uses an adder table

Dave B.  11:15 PM
maybe the thing to do is code both?
11:16
option A: battery vs. offset + type flow rate here
11:16
option B: proper Ford injector model
11:16
Option C: proper GM injector model
11:17
once you get into the ways they handle compensation, you'll find it's virtually impossible to swap just one piece
11:17
pressure compensation is handled VERY differently
11:20
this stuff is hard to get right but I've literally had to do < 2% fueling changes on a 600+whp car when swapping injectors and good injector data on both
11:20
it's exceedingly painful, actually.

Matthew Kennedy  11:24 PM
so looking at a random gm tune
11:24
2011 6 liter PPV

Dave B.  11:25 PM
probably 42#ish injectors if flex
11:25
32#ish if not
11:26
keep in mind that you're not going to get the whole GM model unless you're dealing with a vehicle which was equipped with a FPCM

Matthew Kennedy  11:26 PM
a what?

Dave B.  11:26 PM
only the FPCM equipped stuff got all the compensations
11:26
FSCM?
11:26
the PWM fuel pump computer
11:27
sits on CAN bus

Matthew Kennedy  11:27 PM
ok so it has a flow vs. pressure table - and it's exactly X * sqrt(pressure)

Dave B.  11:27 PM
controls pump to manage fuel pressure
11:27
the issue is how compensations come into play
11:27
Ford is much more complete IMHO.

Matthew Kennedy  11:28 PM
then a giant [pressure, voltage] -> offset table

BeerMoneyMotorsports  11:33 PM
I love these brainstorms
11:33
I learn so much

Dave B.  11:37 PM
read the injector dynamics articles
11:38
and then I can try to find much more in depth explanations

Matthew Kennedy  11:39 PM
dave what's a year/model to look at the ford model
11:39
early coyote maybe?

BeerMoneyMotorsports  11:41 PM
Where do you find this info

5 replies
Last reply 13 hours agoView thread

Matthew Kennedy  11:41 PM
hptuners tune cabinet

Dave B.  11:42 PM
07 gt500
11:42
05 mustang gt
11:43
Coyote got funky.  No MAP sensor, no differential pressure sensor.  They use a speed density model to INFER (i.e. calculate) the manifold pressure and then use that calculated value as an input into the injector model
11:43
heresy
11:44
GM measures manifold pressure, measures (or infers) fuel pressure, calculates differential pressure
11:44
05-10 Ford have differential fuel pressure sensors on the rail, directly measure pressure drop across injector
11:44
Dodge do like GM
11:45
but fail

Matthew Kennedy  11:45 PM
because dodge

Dave B.  11:47 PM
https://www.fordracingparts.com/parts/ics/m-9593-g302.pdf
11:47
that's the Ford data for 07-10 GT500 injectors
11:47
EV14 bosch
11:48
they scale offset for pressure

Matthew Kennedy  11:48 PM
lol that doesn't match the gt500 tune I pulled

Dave B.  11:48 PM
they scale low slope (non-linear) for pressure
11:48
they scale high slope (linear) for pressure
11:49
they scale breakpoint (when to switch from low->high) for pressure
11:49
the units are probably different

Matthew Kennedy  11:49 PM
nope
11:49
the high slope matches

Dave B.  11:49 PM
and the FRPP cals are done by different than Ford OEM

Matthew Kennedy  11:49 PM
and the pressure tables match
11:50
low slope is different

Dave B.  11:50 PM
you realize there are 3 revs of gt500 tune
11:50
"GT500" in database (07-08) and XSH1 (09-10) and then 11-12 with tricore/copperhead

Matthew Kennedy  11:50 PM
this is a 2008

Dave B.  11:51 PM
that data will probably match XSH1
11:51
it's a quite minor difference

Matthew Kennedy  11:53 PM
it mostly matches the ford racing data

Message dev_fuel_algorithms

**Comment by shadowm60** [comment]
working rel:
tune: https://rusefi.com/online/view.php?msq=560
log: https://rusefi.com/online/view.php?log=262

failed nightly:
tune: https://rusefi.com/online/view.php?msq=559
log: https://rusefi.com/online/view.php?log=263

**Comment by mck1117** [comment]
I can reproduce using Alex's tune:
![image](https://user-images.githubusercontent.com/568254/123522023-50307900-d66f-11eb-9cc1-698d632bd728.png)

**Comment by mck1117** [comment]
`m_veTable->getValue(rpm, load)` returns 76

**Comment by mck1117** [comment]
Here's the problem:

![image](https://user-images.githubusercontent.com/568254/123522168-891d1d80-d670-11eb-9f25-dc683fdd965a.png)

**Comment by rusefillc** [comment]
thats a swert one! lets halt and catch fire?

**Comment by mck1117** [comment]
yes

**Comment by mck1117** [comment]
This is a user config error, will be detected by #2866, closing
