### ISSUE TITLE
TS Burned All Data engine stop

### ISSUE THREAD

**Issue by Abricosvw** [rusefi/rusefi#2839]
when TS burn itself, then the engine stops ... 
i checked 3 latest firmware releases ...
![New Bitmap Image (2) (1)](https://user-images.githubusercontent.com/35018246/122683660-a9f7f580-d1ce-11eb-865c-e0e22cd5aa36.jpg)

**Comment by rusefillc** [comment]
I am able to reproduce this with a discovery

1) step 1: full chip erase and flash rusefi_bundle Garbage Man Day.zip
2) connect with TS
3) enable internal stimulator
4) go make any change, hit "Save"

actual result: I get blue LED freee and write
expected result: no blue LED freeze, "unsaved changes" indicator in TS

**Comment by rusefillc** [comment]
I assume we've broken it while making logic smarter defect which chips have two banks and allow hot write?

**Comment by mck1117** [comment]
This is expected behavior - we're supposed to burn while self stimulating

**Comment by rusefillc** [comment]
Ok, now with external stim

1) I set trigger to "one tooth"
2) I have one wire from PD1 to PC6
3) I play with "displacement" field and "save" button

Sometimes things are great. Sometimes sync is lost and RPM goes to zero. At least once I got 3k or 4k for a moment instead of 1200.

**Comment by rusefillc** [comment]
Relevant console commands

"ext_stimulation"
"burnconfig"

**Comment by dron0gus** [comment]
Looks like scheduling issue. Something is blocking CPU for a while.
Self stimulation. Subaru SVX trigger. First trigger is 12 pulses per rotation. With equal gaps.
![Screenshot from 2021-06-21 14-11-57](https://user-images.githubusercontent.com/28624689/122753472-fd377a00-d29a-11eb-9bf7-fcd1794c9cf9.png)

**Comment by dron0gus** [comment]
1. enable self stimulation
2. go to High Speed Logger, start
3. open Ignition->Ignition cylinder trim
4. Adjust any value in this dialog
5. observe trigger errors.
Somehow TS calls flash write on any change on these values.

**Comment by rusefillc** [comment]
self stimulation is a special case

to reproduce real issue you have to use a wire and external stimulation if on discovery 

```
	if (ENGINE(directSelfStimulation) || engine->rpmCalculator.isStopped()) {
		/**
		 * rusEfi usually runs on hardware which halts execution while writing to internal flash, so we
		 * postpone writes to until engine is stopped. Writes in case of self-stimulation are fine.
		 *
		 * todo: allow writing if 2nd bank of flash is used
		 */
#if EFI_INTERNAL_FLASH
		writeToFlashIfPending();
#endif /* EFI_INTERNAL_FLASH */
	}
```

**Comment by dron0gus** [comment]
```
void writeToFlashIfPending() {
	// with a flash write thread, the schedule happens directly from
	// setNeedToWriteConfiguration, so there's nothing to do here
	if (**allowFlashWhileRunning()** || !getNeedToWriteConfiguration()) {
		return;
	}

	writeToFlashNow();
}
```
So this path does not leads to `writeToFlashNow()`

**Comment by Abricosvw** [comment]
it seems that the settings are always save ...
in 50 minutes, there were no settings that were never saved ...
the engine has never stopped while burn settings (any) ...

and ( unsaved changes ) are always ON and     one time ( failed CRC ) ...

![New Bitmap Image (4)](https://user-images.githubusercontent.com/35018246/122831825-72657800-d2b8-11eb-85b1-1d35610f8be4.jpg)
![New Bitmap Image (3)](https://user-images.githubusercontent.com/35018246/122831832-7396a500-d2b8-11eb-9243-3ae8d2d082c0.jpg)
