### ISSUE TITLE
Random discovery has RED led and no USB connectivity with rusefi_bundle Garbage Man Day.zip

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2840]
step 1: random discovery from pile

step 2: auto DFU to rusefi_bundle Garbage Man Day.zip

step 3: red LED, no USB comms

**Comment by rusefillc** [comment]
[red_discovery.zip](https://github.com/rusefi/rusefi/files/6683665/red_discovery.zip)

**Comment by rusefillc** [comment]
@mck1117 any chance you have a discovery to flash attached image?

**Comment by mck1117** [comment]
will check today

**Comment by mck1117** [comment]
CJ125 is trying to initialize using SPI2.

SPI2 TX uses DMA controller 1, stream 3

However, C1S3 is already used by USART3 TX

**Comment by rusefillc** [comment]
why does USB not USB?

**Comment by mck1117** [comment]
because it hits an `osalDbgAssert` which disables interrupts, then `while (1) { }`

**Comment by rusefillc** [comment]
Do we have an opportunity to implement a smarter osalDbgAssert ?
