### ISSUE TITLE
Proteus HW CI sporadic failures

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2845]
Is it time to improve or disable?

![image](https://user-images.githubusercontent.com/48498823/122772510-74f2ae00-d275-11eb-8898-0616c4085142.png)

**Comment by mck1117** [comment]
I will make a hardware change to the HW CI setup that should fix this.

**Comment by mck1117** [comment]
I think this is fixed, haven't seen it in ages.
