### ISSUE TITLE
Ant invocation in "java_console" should build java console

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2857]
cd java_console
ant

expected behavior: java console is compiled
actual behavior: error: package com.rusefi.generated does not exist

it should take one ant invocation not two to build java console in a freshly checked out folder

whatever dependency on antlr has to be handled automatically

As of right now, first we have to invoke 'ant' from configuration_definition to get antlr generated

and then as second step we invoke ant to build rusEFI console

**Comment by rusefillc** [comment]
related to https://github.com/rusefi/rusefi/commit/c0aeb39301a9248a5d043083befc553dba0c4cd1

**Comment by mck1117** [comment]
I think the real question is: why does the console depend on configuration_definition at all? Can you move any stuff actually needed by both to some `shared/` project to remove the dependency completely?

**Comment by rusefillc** [comment]
java_console does not have binary dependency on configuration_definition it builds same source code. I do not follow the argument.

**Comment by mck1117** [comment]
Why does the console build all of the code in `configuration_definition/`? Surely the console doesn't need _all_ of the code in `configuration_definition/`.

**Comment by rusefillc** [comment]
Because we balance costs with benefits. While we have a zillion of things to improve it might make most sense to approach those zillion things in the order of subjective priority.

**Comment by rusefillc** [comment]
@dron0gus says Hi

**Comment by rusefillc** [comment]
@mck1117 every time we change grammar I have to do boring stuff to work around locally :(

Yes proper fix is gradle migration

**Comment by rusefillc** [comment]
@alxrMironovHome here is the work around;

cd java_tools
cd configuration_definition
ant


once you invoke 'ant' in configuration_definition you should be able to invoke 'ant' in java_console

**Comment by rusefillc** [comment]
"Not cool when we introduce extra manual labor with no attempt to undo. That's not progress." would be my passive-aggressive take on https://github.com/rusefi/rusefi/pull/4365#issue-1313607538

**Comment by rusefillc** [comment]
Anyway #4371
