### ISSUE TITLE
VW warnings on cranking part #1

### ISSUE THREAD

**Issue by Abricosvw** [rusefi/rusefi#2861]
9002 

CUSTOM_SYNC_COUNT_MISMATCH = 9002

**Comment by Abricosvw** [comment]
https://rusefi.com/online/view.php?log=270

**Comment by Abricosvw** [comment]
[2021-06-25_19.58.35.zip](https://github.com/rusefi/rusefi/files/6719293/2021-06-25_19.58.35.zip)

**Comment by mck1117** [comment]
It's seeing an early sync point here:

![image](https://user-images.githubusercontent.com/568254/123531616-e3db6700-d6ba-11eb-8973-ccb53c8ccde7.png)

**Comment by mck1117** [comment]
Then a real one here:
![image](https://user-images.githubusercontent.com/568254/123531621-ed64cf00-d6ba-11eb-9039-ef6da21f500e.png)

**Comment by mck1117** [comment]
@Abricosvw was this log made with a MAX992x chip on Frankenso?

If so, swap your wires:

![image](https://user-images.githubusercontent.com/568254/123531698-a88d6800-d6bb-11eb-8614-379f5c2a4efb.png)

**Comment by mck1117** [comment]
https://github.com/rusefi/rusefi/wiki/Trigger-Configuration-Guide

**Comment by rusefillc** [comment]
@mck1117 you are right about the early sync point but making gap expectation smarter does not improve things

```
	s->setTriggerSynchronizationGap2(1.6, 4);
	s->setSecondTriggerSynchronizationGap(1); // redundant gap ratio to fight start-up noise
	s->setThirdTriggerSynchronizationGap(1);
```

the warning is about constant 
```
sync point: isDecodingError=1
count: cur=116 exp=58
count: cur=0 exp=0
count: cur=0 exp=0
```
which I believe is related to a bug in expected tooth calculaton

**Comment by mck1117** [comment]
That warning is a product of the broken csv replay logic :)

**Comment by rusefillc** [comment]
@mck1117 any specific patched you would want to contribute? :)

**Comment by mck1117** [comment]
crafting a PR now!

**Comment by mck1117** [comment]
with #2874, tracking two extra gaps /does/ prevent the warning!
```
s->setTriggerSynchronizationGap2(1.6, 4);
s->setSecondTriggerSynchronizationGap(1); // redundant gap ratio to fight start-up noise
s->setThirdTriggerSynchronizationGap(1);
```

**Comment by Abricosvw** [comment]
Yes I have MAX chip on Frankenso ...
This my trigger (pic from internet)
![60-2_005](https://user-images.githubusercontent.com/35018246/123548654-acf56780-d733-11eb-848b-99c606b74643.jpg)
![60-2_004](https://user-images.githubusercontent.com/35018246/123548655-acf56780-d733-11eb-85ba-a1bce204d73a.jpg)

**Comment by rusefillc** [comment]
Trigger decoder improved for 60/2 VW (only that version for now)

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/124369878-a3419780-dc3e-11eb-964c-884149afdb81.png)

![image](https://user-images.githubusercontent.com/48498823/124369880-a9377880-dc3e-11eb-9bf4-a841d3f002ea.png)

**Comment by rusefillc** [comment]
TODO: download log files check what other warning codes are there

i believe there is CAM configured without actual signal?

**Comment by rusefillc** [comment]
by the way #2898

**Comment by Abricosvw** [comment]
when i swap VR pin

[trigger 36.1 salea.zip](https://github.com/rusefi/rusefi/files/6760060/trigger.36.1.salea.zip)

**Comment by rusefillc** [comment]
closing this one just to reduce confusion

**Comment by mck1117** [comment]
I think we've fixed this, closing.
