### ISSUE TITLE
HTML title for pinout pages

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2882]
Shall we add a nice <title> for https://rusefi.com/docs/pinouts/hellen/hellen121nissan/ and siblings?

**Comment by chuckwagoncomputing** [comment]
Now do we leave this open until yaml fields have been added, or close it now that the capability is present? I closed #3012 before I thought about that.

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/129198283-a19f8541-dd70-4c88-906d-8a686bb13aaa.png)

do not follow. do you mean we need to add actual values into actual yaml files? at the moment HTML content does not have TITLE tag, is there a way to get HTML HEAD TITLE by specifying some yaml field? can you please specify that at least for one yaml file as example?

i wonder if there is some confusion here?

**Comment by rusefillc** [comment]
I will take care of those, thank you!!!
