### ISSUE TITLE
Nissan VVT trigger decoder

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2887]
official trigger shape that's so nice

![image](https://user-images.githubusercontent.com/48498823/124064845-9be27a00-da03-11eb-9fa1-fd399db7bf78.png)

**Comment by mck1117** [comment]
hey look, more symmetrical crank patterns!

**Comment by rusefillc** [comment]
Channel name is a hack but progress!

![image](https://user-images.githubusercontent.com/48498823/124337980-76747e00-db73-11eb-8f34-f652984ede7f.png)

**Comment by rusefillc** [comment]
Quite related to #2243
