### ISSUE TITLE
v12 m73 either start or does not

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2893]
m73 with default m73 proteus tune
only rusefi car with starter button

1/3 of times starter engages for a moment and silenve
2/3 of times engine starts

**Comment by rusefillc** [comment]
maybe related to #2886 ? maybe not?

**Comment by mck1117** [comment]
what condition do we wait for to disable the starter?

**Comment by rusefillc** [comment]
RPM > config(crankingRpm) hopefully?

**Comment by mck1117** [comment]
```
	if (engine->rpmCalculator.isRunning()) {
		// turn starter off once engine is running
		bool wasStarterEngaged = enginePins.starterControl.getAndSet(0);
		if (wasStarterEngaged) {
			efiPrintf("Engine runs we can disengage the starter");
			engine->startStopStateLastPushTime = 0;
		}
	}

	if (getTimeNowNt() - engine->startStopStateLastPushTime > NT_PER_SECOND * CONFIG(startCrankingDuration)) {
		bool wasStarterEngaged = enginePins.starterControl.getAndSet(0);
		if (wasStarterEngaged) {
			efiPrintf("Cranking timeout %d seconds", CONFIG(startCrankingDuration));
			engine->startStopStateLastPushTime = 0;
		}
	}
```

**Comment by mck1117** [comment]
do you see either of these messages?

**Comment by rusefillc** [comment]
I was not looking :(

Next step is getting 1+ Proteus in case from @stefanst to do more testing. Overall that's a low priority for me just needed a record of the issue - ideally I would wait until I have x5 working Proteus to test on v12 :)

**Comment by mck1117** [comment]
was this fixed by new spark plugs?

**Comment by rusefillc** [comment]
yes it was fixed by 6 spark plugs

**Comment by rusefillc** [comment]
this is also begging for "your spark plugs are wet" diagnostics message which is #3771
