### ISSUE TITLE
Matt has CUSTOM_ERR_VVT_OUT_OF_RANGE warning

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2921]
See https://rusefi.com/forum/viewtopic.php?p=41486#p41486

**Comment by mck1117** [comment]
I don't understand where these values are coming from. It's bouncing between ~1309 and ~0.3.

~0 I understand: the rising/falling edge is just about exactly at TDC on my engine, modulo timing chain slop (no tensioner, pushrod engine).
Where did ~1309 come from? 1309 modulo 360 is 229.  Nothing about my engine is 229 degrees.  Where did that number come from?

**Comment by mck1117** [comment]
Will try to reproduce on the bench tonight using single tooth crank, single tooth cam (both of which I can generate with an arbitrary waveform generator, and adjust the phase between them)

**Comment by rusefillc** [comment]
I still have Nissan VVT jumping
and do not have time to test on NB2 :( overall I know this area is messy :)

**Comment by mck1117** [comment]
well, we now know it reproduces on single tooth cam - so it's nothing special about the trigger decoder itself.  I'll test tonight and see what I find.

**Comment by rusefillc** [comment]
Do we need three more tickets for the three other warnings?...
