### ISSUE TITLE
pinouts process is broken but also green

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2942]
quick improvement: 

make it fail at least

```
processing ./firmware/config/boards/proteus/connectors/black35.yaml
DIR pinouts/proteus/
NAME black35
sed: -e expression #1, char 29: unknown command: `"'
pinouts/proteus//index.html: very short file (no magic)
IMG black35.jpg
black35.jpg
```

**Comment by rusefillc** [comment]
@chuckwagoncomputing 

that's 2nd time yq changes on us. that means they will change on us again

can we dump specific yq source code or binary into https://github.com/rusefi/rusefi_external_utils/ so that we know for sure what version of yq we use at any moment?

**Comment by chuckwagoncomputing** [comment]
I'd much rather have the workflow fetch a specific release on GH.

**Comment by rusefillc** [comment]
works for me, as long as it's a bit more repeatable.

**Comment by rusefillc** [comment]
@OrchardPerformance @BeerMoneyMotorsports we now have a manual one time backup at https://github.com/rusefi/rusefi_documentation/tree/master/pinouts-backup

**Comment by OrchardPerformance** [comment]
I keep local, off line copies of some things incase of outage as well

**Comment by chuckwagoncomputing** [comment]
Regarding keeping freezing software versions: the OS images that GH runs on update on a regular basis, with new versions of software. As far as I know, the only way to avoid this would be to self-host.

**Comment by rusefillc** [comment]
but yq is not part of image is it?

we control where and how we get yq and yq specifically is the huge source of drama, not sed not java

**Comment by rusefillc** [comment]
@chuckwagoncomputing close or do we have more plans here?

**Comment by chuckwagoncomputing** [comment]
As far as I know we're done with this
