### ISSUE TITLE
icon paths are broken when invoking via rusefi_autoupdate

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2944]
S2R:
download artifacts from https://rusefi.com/build_server/rusefi_bundle.zip or build locally

expected behavior:

``java -jar rusefi_console.jar ``
![image](https://user-images.githubusercontent.com/48498823/125169778-b4783000-e179-11eb-9ebf-33483494980b.png)

broken behavior, should be same as above
``java -jar rusefi_autoupdate.jar``
![image](https://user-images.githubusercontent.com/48498823/125169801-d4a7ef00-e179-11eb-8e87-c6112fb750ba.png)

**Comment by Come1LLF00** [comment]
Okay, I came up with the idea to add every URL of loaded jars including rusefi_console.jar to the system classloader when getClassLoaderByJar is invoked in AutoupdateUtil. The current solution looks like this:
`private static void addURLToSystemClassLoader( URL url ) throws IntrospectionException {
    URLClassLoader systemClassLoader = (URLClassLoader) ClassLoader.getSystemClassLoader();
    Class<URLClassLoader> classLoaderClass = URLClassLoader.class;

    try {
        Method method = classLoaderClass.getDeclaredMethod("addURL", URL.class );
        method.setAccessible(true);
        method.invoke(systemClassLoader, url );
    } catch ( Throwable t ) {
        t.printStackTrace();
        throw new IntrospectionException("Error when adding url to system ClassLoader ");
    }
}

@NotNull
public static URLClassLoader getClassLoaderByJar(String jar) throws MalformedURLException, IntrospectionException {
    final URL newURL = new File(jar).toURI().toURL();
    addURLToSystemClassLoader( newURL );
    return new URLClassLoader(
            new URL[]{ newURL },
            AutoupdateUtil.class.getClassLoader()
    );
}`

**Comment by rusefillc** [comment]
@Come1LLF00 yes this looks fixed now!
