### ISSUE TITLE
WBO is setting itself to CAN

### ISSUE THREAD

**Issue by CrazyStriker** [rusefi/rusefi#2945]
CAN WBO seem to set itself to true.
Pushed the settings from TS a few times, resseting ECU in between and it's stuck to CAN input, hence no WBO input for me anymore.09/07/21 
Nightly build on H72

**Comment by rusefillc** [comment]
that's pretty odd

Q1: just to confirm does your firmware match 100% match your project version?

Q2: just to reduce chance of misunderstanding please upload your very fresh tune?

Q3: just to reduce chance of misunderstanding please provide a URL for the exact dialog on the tune where you are trying to change the setting?

**Comment by CrazyStriker** [comment]
- Project .ini is 2021/07/09
- https://rusefi.com/online/view.php?msq=579
- https://rusefi.com/online/view.php?msq=579&dialog=egoSettings

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi/issues/2944 is not a great example but can we please spell out 6 steps to reproduce, and spell out expected vs actual result?

**Comment by CrazyStriker** [comment]
Issue timeline for me :
- Car was running on 2021/04/26 FW
- Downloaded nightly build on 07/10
- Updated .ini to 2021/07/09
- Set the board to DFU mode using TS
- Flashed the FW using .hex from 2021/07/09 nightly
- Reset the board

- Started TS on the right project. Showed a few errors regarding idle advance. Solved issue and reset board
- TS reads board configuration and generates difference report. 
Difference report shows this in local tune : 
![image](https://user-images.githubusercontent.com/38209146/125172447-1789b700-e1ba-11eb-908b-bdecb316b065.png)
And this in board tune : 
![image](https://user-images.githubusercontent.com/38209146/125172456-23757900-e1ba-11eb-80ab-cb389623098a.png)

- I choose to push local tune tu set my WBO to analog
- Reset the board, and connected to TS. Goes back to difference report with same exact difference.
- While car is running, lambda shows 0

**Comment by CrazyStriker** [comment]
![IMG_20210710_184631](https://user-images.githubusercontent.com/38209146/125197196-004fd580-e25d-11eb-8dd5-88b41d8823ea.jpg)
