### ISSUE TITLE
dash pic example

### ISSUE THREAD

**Issue by duhafnusa4** [rusefi/rusefi#2948]
![dash](https://user-images.githubusercontent.com/5051341/125208727-ee206800-e259-11eb-9600-6cf742fba5a6.jpg)
Thank you for taking the time to report an issue!

To make our work easier, please provide as many details as you can:
* [ ] What hardware did you use while experiencing the issue?

**Comment by rusefillc** [comment]
@duhafnusa4 I am a bit lost here

what is the desire here on this ticket?

**Comment by duhafnusa4** [comment]
This was made to host the pic so I could use it in the dash wiki

**Comment by rusefillc** [comment]
@duhafnusa4 please close this ticket

@duhafnusa4 please consider discovering a less weird way to upload images :)

**Comment by duhafnusa4** [comment]
Please provide me with non weird way and I will gladly :)

**Comment by rusefillc** [comment]
This was discussed in slack
