### ISSUE TITLE
datalog points cleanup

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#295]
Following data points should be avaialble in TS and native logs:

rpm, map, tps, accelpedal if dbw, MAF if present, inj pw, fuel pressure, idle valve position/duty
vehicle speed
if logging both, driven / non-driven (i.e. front/rear) wheel speed
ignition timing
any calculated torque value
open/closed loop status
knock, knock retard status
ST fuel trims, LT fueltrims, ST spark/knockl, LT spark/learned knock
ST idle airflow trims, LT/learned idle airflow trims
idle target, idle actual, spark correction due to idle
air temp, downstream/IAT2, engine coolant temp, cylinder head temp/ECT2
estimated air temp 
target AFR/target lamda/eq

Reported by: rusefi

**Comment by mck1117** [comment]
does this still exist? datalog seems fine.

**Comment by rusefi** [comment]
At least name reuse between three log implementations & better entry names still seem to be needed, for instance ```		reportSensorF(log, "f: tps delta",``` is not right.

**Comment by mck1117** [comment]
this is done, internal log and TS log are very very close at this point
