### ISSUE TITLE
Do we need to change handling of very invalid MAP sensor and zero fuel

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2979]
naked hellen72-d bench powered by +12v
curious think about self-stim is that we calculate zero fuel based on invalid MAP=4kPa

open question if that should be enough to shut down spark once we start to command zero fuel?

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/126046082-15978df2-9c81-48fb-a398-21d558f4a04e.png)

**Comment by mck1117** [comment]
no - even in cases of zero fuel (for example, decel fuel cut) you don't want to cut ignition.  It's still possible for the wall wetting fuel to be running the engine for a moment, and if you cut ignition when zero fuel, it'll burn on its way out the exhaust.
