### ISSUE TITLE
NB2 trigger shape does not seem to match JimStim

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#2980]
JimStim does not approve of rusEFI trigger shape definition? note errors in coil scheduling

depending on RPM we either have one coil event not even or just totally not present

![image](https://user-images.githubusercontent.com/48498823/126046908-a6c3e28d-e845-41a9-bca4-ee201c310814.png)

![image](https://user-images.githubusercontent.com/48498823/126046936-df1218e3-b7cb-4775-9811-2cc76167bd56.png)

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/126047083-27f536c7-fb64-4913-8036-19ad82796b95.png)

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/126047239-eb7cb544-70c3-430c-b47d-000448bf0f42.png)

**Comment by rusefillc** [comment]
and now self-stim also show uneven sparking, so the problem is NOT trigger definition?!

![image](https://user-images.githubusercontent.com/48498823/126047794-88549db8-bfc5-4fa3-be57-dfad1f1b0d7e.png)

**Comment by rusefillc** [comment]
new debug gauge in the "instance RPM" family confirms problem

this log is with external jimstim

![image](https://user-images.githubusercontent.com/48498823/126048885-46682a3a-ff6e-47e9-9460-26bbf92c1789.png)

**Comment by mck1117** [comment]
trigger is correct, prepareEventAngles is broken
