### ISSUE TITLE
Boost by gear

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3007]
Not for Martin because boost by gear is a form of traction control and not wanted/not allowed in some specific racing series

**Comment by rusefillc** [comment]
martin does "AX autocross"

**Comment by mmatousek89** [comment]
https://www.fia.com/events/european-autocross-championship/season-2021/european-autocross-championship

**Comment by rusefillc** [comment]
Depends on #3159 for protection portion of the logic

**Comment by rusefillc** [comment]
Dup of #2404 or not a dup?
