### ISSUE TITLE
GHA reliability: retry FTP upload

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3011]
We definitely have FTP upload reliability problem which affects less important TS plugin but also more important pinout generator and else

are there any cost efficient ways to improve this area? Does linux offer a build-in or popular retry tool? https://serverfault.com/questions/80862/bash-script-repeat-command-if-it-returns-an-error has a link to something on GH

**Comment by chuckwagoncomputing** [comment]
Why is FTP failing?

**Comment by rusefillc** [comment]
I believe that FTP is failing sporadically because my hosting company is not perfect in terms of FTP reliability

**Comment by mck1117** [comment]
can you link an example failure build on gha?

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi/runs/3119536573?check_suite_focus=true

![image](https://user-images.githubusercontent.com/48498823/126573292-41d2939e-66dc-4695-aee3-aa1d8f7a8796.png)

**Comment by rusefillc** [comment]
oh did not realize there are retries! not sure if there is a delay between those

**Comment by chuckwagoncomputing** [comment]
I think the delay is pretty short, like <5 seconds.

**Comment by rusefillc** [comment]
Related to https://github.com/rusefi/rusefi_documentation/issues/164

**Comment by rusefillc** [comment]
this drama could be related to the increase in build configurations number

if GHA runs too many actions in parallel 1and1 could be considering this a bit of a DoS attach and limiting us.

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/136645449-09f3f4e1-2198-42bc-aca5-4afffec584c2.png)

**Comment by rusefillc** [comment]
Maybe progress?

![image](https://user-images.githubusercontent.com/48498823/136664474-c6b0df04-884b-4d5f-b98b-a5fa68ece5d7.png)

I will keep an eye on this since I get email notifications on failed runs

**Comment by rusefillc** [comment]
hold one where are my 999 retries? :(

![image](https://user-images.githubusercontent.com/48498823/136674122-bcd8e59c-1d94-495e-852e-14d121044c80.png)

**Comment by chuckwagoncomputing** [comment]
You appear to be using an account without full SSH, only SFTP.

**Comment by rusefillc** [comment]
So they are pushing us into bigger change. Please add path variable and lets go with universal account secret name


Primary account has full ssh

**Comment by rusefillc** [comment]
RUSEFI_DOXYGEN_FTP_USER not removed yet
RUSEFI_DOXYGEN_SSH_PASS not removed yet

RUSEFI_SSH_USER added
RUSEFI_SSH_PASS added

**Comment by rusefillc** [comment]
@chuckwagoncomputing looks like we've addresses all of these?
