### ISSUE TITLE
"prettyClose": some strange code inside idle controller?

### ISSUE THREAD

**Issue by andreika-git** [rusefi/rusefi#3030]
1) We have IdleController::update() where we call:
```
float position = getIdlePosition();
applyIACposition(position PASS_ENGINE_PARAMETER_SUFFIX);
```

2) Inside IdleController::getIdlePosition() we set:
```
engine->engineState.idle.currentIdlePosition = iacPosition;
return iacPosition;

```

3) Inside applyIACposition() we check:
```
bool prettyClose = absF(position - engine->engineState.idle.currentIdlePosition) < idlePositionSensitivityThreshold;
if (prettyClose) {
	return;
}
```

Does it really work? 'prettyClose' equals true all the time, right? I cannot get past it on the bench.

**Comment by mck1117** [comment]
I've always used `idlePositionSensitivityThreshold` = 0, so I've never hit this.  What is the purpose of idlePositionSensitivityThreshold?

**Comment by andreika-git** [comment]
For stepper motors, it equals to 1 step to avoid excessive micro-movement.

**Comment by rusefillc** [comment]
```
idlePositionSensitivityThreshold = 1.0f / engineConfiguration->idleStepperTotalSteps;
```
how does it equal "1"?

stepper is already mention around there, I've made it mentioned twice

**Comment by mck1117** [comment]
it's not equal to 1, it's equal to one stepper step worth

**Comment by mck1117** [comment]
wait - I'm not sure we need `idlePositionSensitivityThreshold` at all - the stepper driver truncates to the nearest step, so sub-step moves don't trigger a move anyway.  With `idlePositionSensitivityThreshold` set to 1/stepCount, it will just prevent sub-step moves twice.

**Comment by andreika-git** [comment]
`"the stepper driver truncates to the nearest step, so sub-step moves don't trigger a move anyway"`

If a value is right in the middle between two steps, then the stepper still moves! For example, it's 10.99, and then becomes 11.01. The small 0.02 increment will trigger stepper to move 1 step because of truncating to nearest (the same would be with rounding too).

This 'idlePositionSensitivityThreshold' appeared not in an abstract world, it was caused by a real car experience with a low-step-count stepper, and was tested well enough to see that the IAC works **better** with it.

The current implementation has two issues:
1) position == currentIdlePosition is always true, and the stepper just doesn't work
2) position is in percentage, and idlePositionSensitivityThreshold is ratio

**Comment by mck1117** [comment]
Ah, that makes some more sense then.
