### ISSUE TITLE
Hellen Nissan had blinking blue + solid red and no USB

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3034]
step 1: flash Hellen Nissan

step 2: set sensors

![image](https://user-images.githubusercontent.com/48498823/126727544-c2d18784-cd84-4a48-97ef-cba3d1cc812e.png)

TBD

**Comment by mck1117** [comment]
dump of mcu is easiest

**Comment by rusefillc** [comment]
Win7 would not connect to that USB

while Win10 another device works fine
