### ISSUE TITLE
2 byte table axis

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3045]
at the moment we are flexible with TS table cell size - it could be 1 byte or 4 byte

but each axis cell still always take 4 bytes. for 8x8x1 table we have 8x2x4 bytes for axis would be nice to have an option of axis taking less memory than data in the table

step 1 extra flexibility for 3D interpolation template?
step 2 something else?

**Comment by rusefillc** [comment]
should it actually be 1 byte for RPM?

how do we want to pack load axis into two bytes?

**Comment by mck1117** [comment]
> how do we want to pack load axis into two bytes?

we already do it in a few places, scaled by (iirc) 50 or 100

**Comment by rusefillc** [comment]
@alxrMironovHome can you help?

**Comment by rusefillc** [comment]
Relates to #3707

**Comment by rusefillc** [comment]
@mck1117 shall we close?
