### ISSUE TITLE
Proteus build down

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3049]
https://github.com/rusefi/rusefi/runs/3150886153

![image](https://user-images.githubusercontent.com/48498823/126872131-c4fec5c4-71c9-4758-9bd8-65f6971388d1.png)

**Comment by rusefillc** [comment]
@mck1117 https://github.com/rusefi/rusefi/runs/3151847781?check_suite_focus=true

**Comment by mck1117** [comment]
after an unplug+replug, this flashed ok: https://github.com/rusefi/rusefi/runs/3151879384
