### ISSUE TITLE
Red test mule cranking to idling is weird

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3050]
See https://rusefi.com/forum/viewtopic.php?p=41684#p41684

**Comment by rusefillc** [comment]
two changes:
improved TPS calibration
wider threshold (but with REO creating it now)

now idle does not fall that much down but still oscillation

https://rusefi.com/online/view.php?log=301

**Comment by rusefillc** [comment]
https://github.com/rusefi/web_backend/issues/127 reported

**Comment by mck1117** [comment]
related to #2813

**Comment by rusefillc** [comment]
looks great! https://rusefi.com/online/view.php?log=303
