### ISSUE TITLE
Fuel pump priming on battery voltage

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3058]
A Human connects RE to laptop
An hour later human turns ignition key

current result: RE primes fuel pump on ECU start

expected result: human could be right to expect fuel pump priming once he turns key ON i.e. ECU gets +12 not laptop power on

**Comment by mck1117** [comment]
yes, there are a handful of things that should happen on rising edge of 12v, instead of upon power-on

**Comment by mmatousek89** [comment]
ecu definetelly should not act like "key on" when you connect power from laptop usb, thats unexpected behaviour

**Comment by mck1117** [comment]
Done! We do all this stuff at key-on now instead of power up.
