### ISSUE TITLE
show friendly pin names in error messages - looking for yaml to generate board_meta.cpp

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#3072]
right now we show "pin PA3 already used by xyz"

we could show "analog volt 3 already used by xyz"

**Comment by rusefillc** [comment]
at the moment firmware does not know yaml pin names :(

**Comment by mck1117** [comment]
that's exactly what this issue is about 🙂

**Comment by rusefillc** [comment]
looks like we are looking for board_meta.cpp method generated from yaml with "getBoardPinName" method?

**Comment by rusefillc** [comment]
Not same but kind of related to #3298

**Comment by rusefillc** [comment]
We now have getBoardSpecificPinName
