### ISSUE TITLE
Refactor vss towards flex fuel sensor

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3106]
Vss sensor should get much closer to flex fuel sensor 

A part of the change in s migration to Sensor framework see flex as example

**Comment by mck1117** [comment]
As an intermediate change we can use functionPointerSensor to get it in the sensor model without full implementation, see init_lambda.cpp

**Comment by mck1117** [comment]
depends on #3107

**Comment by mck1117** [comment]
This is done!
