### ISSUE TITLE
Console to show device signature in window title also we have a problem with default bundle?!

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3115]
Abricos says that console should display actual device signature in window title

**Comment by rusefillc** [comment]
@mck1117 what the best way to undo 
![image](https://user-images.githubusercontent.com/48498823/128608360-89a7bdef-2462-40f2-8d49-79b8e2af774a.png)

**Comment by mck1117** [comment]
What's the best way to undo? Why not just edit that line to put it back. I think it was an over eager `git add .`

**Comment by rusefillc** [comment]
@Abricosvw thank you once again great defect report! fixed now.
