### ISSUE TITLE
analog output for crank angle

### ISSUE THREAD

**Issue by mmatousek89** [rusefi/rusefi#3122]
fast DAC providing 0-5V coresponding to 
0-720deg crank angle

probably special hardware?

can we update every crank degree or it will owerload processor?

this can be handy for osciloscope in X/Y mode or fast datalloger to have synchronisation with crankshaft without dificulty of triggerpattern decoding

**Comment by rusefillc** [comment]
https://xyproblem.info/ what problem are solving

**Comment by mmatousek89** [comment]
thts not problem, thats feature to improove workflow, you can put it under "nice to have" label

**Comment by mck1117** [comment]
but why? why not just sync the scope to an ignition output or something?

We don't have the hardware to be able to do this.  We can't reasonably do this without crazy CPU load.
