### ISSUE TITLE
Ford Focus II 2004-2008 CAN PPS

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3123]
There is an opinion that ECU on said Focus receives pedal position via CAN not via analog signal from pedal

**Comment by rusefillc** [comment]
1.8 EUDM

**Comment by mck1117** [comment]
![image](https://user-images.githubusercontent.com/568254/128939975-876ff0fc-079f-4262-aadd-73578a6ab71e.png)

A5/A75 = instrument cluster
B138 = throttle pedal
thing at the bottom = ECU

So yes, it's CAN pedal.

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/128975658-15eaa9e0-67f8-4148-99e1-4ef00d3b795c.png)

**Comment by mck1117** [comment]
This will work today with Lua, in fact it was in the cool demo on YouTube.
