### ISSUE TITLE
miata 36-1 trigger basemap

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/rusefi#3126]
Please add an alternate preset for NB using 36-1 trigger wheel.  Very cheap and easy upgrade to improve our startup.

**Comment by rusefillc** [comment]
36/1 button added
![image](https://user-images.githubusercontent.com/48498823/128865283-f81430c3-543c-4b4d-b86b-53949d99f1c2.png)

maybe not best possible usability but "default" means "OEM" base map while 36/1 means not OEM

**Comment by BeerMoneyMotorsports** [comment]
@rusefillc this will also need to be implemented for NB1 map.

**Comment by BeerMoneyMotorsports** [comment]
@rusefillc reminder to add 36-1 option for NB1.
