### ISSUE TITLE
comms halts after trying to set VSS pin to PA2

### ISSUE THREAD

**Issue by thirstyone** [rusefi/rusefi#3129]
Bare discovery board, connect to rusefi console, set 'minimal' in preset section, close rusefi console. open TS, set VSS to pa2, hit 'Burn' - blue led stops blinking and becomes solid.

**Comment by mck1117** [comment]
cool, it hard faults when you pick PA2

**Comment by mck1117** [comment]
yeaaaaaah we dereference a null pointer
