### ISSUE TITLE
12v TPS in error message? that's weird

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3137]
During Nissan tests

![image](https://user-images.githubusercontent.com/48498823/129110419-df3922d9-461d-411c-8111-e7ef08e2d564.png)

**Comment by mck1117** [comment]
you think 12v is weird? try 167!

![image](https://user-images.githubusercontent.com/568254/129467775-cc9b7337-1dee-43bd-98ab-0e01ab874bef.png)
