### ISSUE TITLE
faster cranking with battery-backed RAM

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#314]
stm has battery-backed RAM, it should be possible to save the state of trigger for faster cranking

as is we need two full cycles in order to sync trigger. With battery-backed RAM we hope to remember trigger position of previous engine run which would allow to speed up trigger syncronization

see http://stackoverflow.com/questions/20667754/how-to-use-backup-sram-as-eeprom-in-stm32f4

Reported by: rusefi

**Comment by rusefi** [comment]
Why do we need two cycles?

1) we need to find sync point to start anything
2) we need a cycle so that we know RPM and we can start scheduling angles based on RPM

**Comment by rusefi** [comment]
it's hard to say how difficult it would be to achieve, no clear roadmap for this improvement at the moment

**Comment by mck1117** [comment]
maybe close? none of the sensors we're using provide accurate data near zero engine speed, so there isn't much hope of this working

**Comment by mck1117** [comment]
super far out of scope, requires special hardware
