### ISSUE TITLE
prevent invalid sensors for the moment after burn

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#3145]
1. sensors update
2. flash erase/burn happens (blocking CPU)
3. sensors are briefly invalid
4. sensors update, things are happy

let's avoid #3 happening, it means sometimes the fan relay will click on briefly after a burn

**Comment by rusefillc** [comment]
What hard evidence do we have to support this theory?

**Comment by mck1117** [comment]
The fan on my car clicks on after burn. I've seen exactly this happen.
