### ISSUE TITLE
console  & TS to complaint about a non-compatible firmware

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#315]
console and TS should produce very visible error if firmware version does not match console expected version,

implementation idea: I wonder if that's time to start playing with
signature    = "MShift v0.01"

**Comment by chuckwagoncomputing** [comment]
TS definitely complains if the .ini version doesn't match. I wasn't sure about console, but I just checked and it complained about it.
![image](https://user-images.githubusercontent.com/1531127/215364463-3c81288b-1ab1-4fef-956f-9a79d73154ce.png)
