### ISSUE TITLE
TPS/TPS enrichment to be a multiplier

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3167]
We have converted starting fuel from ms to gramms

Should we do same for TPS / TPS table?

![image](https://user-images.githubusercontent.com/48498823/129648510-0c86417d-2197-4f7b-8149-59997f834e20.png)

**Comment by OrchardPerformance** [comment]
Should probably be a multiplier and just 1.00 = 100% (no change) 1.2=120%.
Reason is this adds onto the running fuel so should probably be proportional to the running fuel. 

If it is proportional then we are more likely to be able to set a good default basemap.

**Comment by highspeed427** [comment]
Can we revisit this? I am running into major issues with this being ms. i agree with @OrchardPerformance on this matter. it needs to be a multiplier. Ive recently been building tunes for multiple difference size injectors and keep having to completely remap the accel fuel. 

thanks
