### ISSUE TITLE
Add NB2 boost sensor as hard-coded MAP sensor

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3184]
Subj

**Comment by CrazyStriker** [comment]
[NB2 OEM MAP curve.xlsx](https://github.com/rusefi/rusefi/files/7025253/NB2.OEM.MAP.curve.xlsx)
![image](https://user-images.githubusercontent.com/38209146/130317624-8e0b8293-ff56-45cd-b2aa-d743419cfd5e.png)
Gathered data using dubious 3bars GM copy.
Seem decent enough to be used as is; at least it's linear.

**Comment by rusefillc** [comment]
We already had it, now with improved calibration
