### ISSUE TITLE
unclear SPI start error

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3186]
![image](https://user-images.githubusercontent.com/48498823/130430463-ddee1f37-dff5-4552-bba0-1d0d6f8776c0.png)

https://rusefi.com/online/view.php?msq=629

Denis says he is using nucleo144 stm32f429

**Comment by rusefillc** [comment]
Trying to find if custom or not custom binary

Maybe specific SPI is not enabled on compile time?

**Comment by rusefillc** [comment]
That's using https://rusefi.com/build_server/rusefi_bundle.zip

**Comment by mck1117** [comment]
woohoo, that's our first error caught in the real world that would've caused an ECU lockup!

**Comment by mck1117** [comment]
I suspect it's a DMA collision

**Comment by mck1117** [comment]
We don't have the ability to change that string, as it comes directly from ChibiOS, not us.

**Comment by rusefillc** [comment]
technically we can patch ChibiOS

**Comment by mck1117** [comment]
I think that's the best we can realistically do in that scenario, it's essentially impossible that users hit this on any non-bare-stm32, so those messages are really for devs.
