### ISSUE TITLE
94/95 miata presets

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/rusefi#3191]
Please adjust defaults below in 94/95 tune.

- injector size = 254cc
- engine displacement = 1.8

**Comment by rusefillc** [comment]
I believe that we already have this
please clarify if that's not how the firmware acts

![image](https://user-images.githubusercontent.com/48498823/130675284-48100a7f-9b3e-43a4-aefb-3dfee3569212.png)

**Comment by BeerMoneyMotorsports** [comment]
This is not how it functions for me.  
1- loaded latest nightly
2- Apply NA8 defaults
3- disconnect ECU 
4- Restart Tech Tool
5- Connect ECU

Below are screenshots of what i am seeing after applying the NA8 defaults.  Also defaults to Batch fire

![image](https://user-images.githubusercontent.com/82395131/130680305-48c76365-3502-4418-bef3-8dec7d2a4958.png)
![image](https://user-images.githubusercontent.com/82395131/130680585-bc9a6ed7-83d5-4793-974c-5d2091d6705d.png)

**Comment by rusefillc** [comment]
@BeerMoneyMotorsports I found at least one defect

let's try again in 20 minutes :)

**Comment by rusefillc** [comment]
@BeerMoneyMotorsports I assume this was fixed
