### ISSUE TITLE
Stop engine button killed coil?

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3196]
Alex wonders if stop engine button killed his coil

**Comment by rusefillc** [comment]
See #3180

**Comment by rusefillc** [comment]
@mck1117 is this fixed now? can I CHANGELOG this?

**Comment by rusefillc** [comment]
@mck1117 is this fixed by #3194?

**Comment by rusefillc** [comment]
@mck1117 was this fixed by #3194?

**Comment by rusefillc** [comment]
Related to #3071

**Comment by rusefillc** [comment]
Actually we need #3071 which is currently https://github.com/rusefi/rusefi/pull/3220

**Comment by mck1117** [comment]
This is probably fixed - it should now be impossible to overdwell a coil under any normal circumstance.

Let's go for changelog-worthy!

**Comment by rusefillc** [comment]
Already changelog-ed https://github.com/rusefi/rusefi/commit/b2446a6ddb87e59e270a43283d19b59d32053626
