### ISSUE TITLE
can vehicle speed broken

### ISSUE THREAD

**Issue by shadowm60** [rusefi/rusefi#3211]
since vehicle speed was updated, can vehicle speed not working any more

**Comment by rusefillc** [comment]
Sounds like we need unit test to protect this functionality

**Comment by shadowm60** [comment]
It was added as sensor, and the new implementation is not checking if there is can vss configured

**Comment by OrchardPerformance** [comment]
Should probably solve this one as it breaks functionality for some users and prevents rx8 and e46 working right.

**Comment by mck1117** [comment]
@shadowm60, when you get a chance, can you check if this is fixed?

**Comment by shadowm60** [comment]
@mck1117  tested today finally, issue can be closed!
