### ISSUE TITLE
hysteresis for GPPWM

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3222]
How do we control fan relay with GPPWM in terms of hysteresis? I am hearing some crazy clicking on Abricos's vehicle

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/132137194-6b1f049b-e891-48f5-95df-196ae760f701.png)

**Comment by mck1117** [comment]
that's what the "on above duty" and "off below duty" are for

you can't have "off below" greater than "on above"

set those to 40 and 10 or something

**Comment by rusefillc** [comment]
@mck1117 tooltip improved, you can't have "off below" greater than "on above" validation added
