### ISSUE TITLE
Complete fuel cut, maybe by wall wetting? Warning on decel (?) CUSTOM_OBD_SKIPPED_FUEL = 9010

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3225]
![image](https://user-images.githubusercontent.com/48498823/132138521-6775735a-cf43-4602-9b71-1124c195192a.png)

**Comment by mck1117** [comment]
happens in this log on my car, under the same conditions:

https://rusefi.com/online/view.php?log=341

looks like it happens 1-3 times per big lift-off the throttle

**Comment by rusefillc** [comment]
is that wall wetting cutting fuel for Nick for 0.4 seconds?

![image](https://user-images.githubusercontent.com/48498823/134982902-43a338e3-7b2d-42e1-bee1-b3848003d077.png)

**Comment by rusefillc** [comment]
Looks like fuel cut is a normal condition here, just removing this warning
