### ISSUE TITLE
cranking is sensitive to WBO warm-up

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3268]
Visiting Nick today

first cranking attempt:
insert key, start cranking right away while external WBO controller gauge shows 14 which maybe probably means "heating"
result: car was very unhappy and did not start

second cranking attempt:
insert key, turn into ON position, give it 10 seconds for WBO to change from 14 to 21, car starts much better

question: is this about Nick's tune depending on closed loop fuel adjustment for cranking/running?
is this about Nick's battery being unhappy during sensor heating?
is this about anything else?

**Comment by mck1117** [comment]
Is closed loop fuel enabled?

**Comment by rusefillc** [comment]
@mck1117 i believe it's disabled for now https://rusefi.com/online/view.php?msq=654

**Comment by mck1117** [comment]
we certainly don't listen to WBO while cranking
