### ISSUE TITLE
Dave is asking for a one line clarification on force induction VE

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3277]
Dave says that this help area should state one of two things

option 1
```
VE incorporates pressure ratio as measured by MAP sensor in boost (no VE ever above 105%ish)
```

option 2
```
VE values reference amount of air required to fill cylinder at sea level (with forced induction perfect cylinder filling 100% times pressure ration)
```

![image](https://user-images.githubusercontent.com/48498823/134844563-794cbe4b-ddaa-4b7d-ada2-153c5644333f.png)

**Comment by rusefillc** [comment]
@mck1117 @OrchardPerformance so which way is RE? option 1 or option 2?

**Comment by OrchardPerformance** [comment]
Option 1 is correct.
