### ISSUE TITLE
BUG? main relay vs coils initialization sequence

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#328]
need to confirm that main relay is turned on only after coil pins are turned on, hopefully that would be a software work around
117) RESOLVED IN R0.5 Add pull down and series resistors to hi/low mosfet driver
for older boards https://svn.code.sf.net/p/rusefi/code/trunk/hardware/frankenso/known_issues.txt

Reported by: rusefi

**Comment by mck1117** [comment]
this is fixed in hardware and software
