### ISSUE TITLE
I have a discovery board which does not switch to DFU

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3280]
Is "software switch to DFU" broken or do I have an F407 discovery board which would not reboot into DFU?

**Comment by rusefillc** [comment]
I do not think that we have DFU command acknowledged in the protocol at the moment, TODO revisit

**Comment by mck1117** [comment]
Can you connect STM32CubeProgrammer via the stlink, and check whether the boot addresses are correct?

**Comment by rusefillc** [comment]
lost that board but will do that next time
