### ISSUE TITLE
individual cylinder fuel trims

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3284]
@blundar need more details on this feature

would it be in % extra, positive or negative, with "0" meaning no trim? or anything else?

**Comment by rusefillc** [comment]
@mck1117 says something like "give #7 5% more gas"

**Comment by blundar** [comment]
I don't think it really matters as long as it is clear.

I think I personally prefer 1.0 = no change, 0.9 = 10% reduction, 1.1 = 10%
increase
0 = no change +10 = 10% increase, -10 = 10% decrease would be ok

**Comment by rusefillc** [comment]
fancy boys have 8x12 tables for each cylinder

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/135382552-7c1d48f6-c91e-46c5-9b64-10c1b8e0eadf.png)

**Comment by rusefillc** [comment]
Status: configuration maybe is ready, TS view maybe ready, no code.

**Comment by mck1117** [comment]
@blundar says

> if you can set your axes points, 4x4 is plenty
> 4x4 lets you exclude idle, exclude cruise/off boost
> that's 110% functional.
