### ISSUE TITLE
MPXH6400 CALIBRATION

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/rusefi#3288]
We need to offer a calibration for MPXH6400 by default.  I will be testing on the lemon and adding to Hellen as needed.

**Comment by rusefillc** [comment]
@BeerMoneyMotorsports can you please help with actual calibration? like 0v and 5v values or something?

**Comment by BeerMoneyMotorsports** [comment]
Pressure Sensor 2.9PSI ~ 58.02PSI (20kPa ~ 400kPa)  0.2 V ~ 4.8 V

**Comment by rusefillc** [comment]
@BeerMoneyMotorsports how about
```
mpxh6400(1 /*volts*/, 90 /*kPa*/, 3 /*volts*/, 250 /*kPa*/)
```
