### ISSUE TITLE
better RPM calculation logic

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#329]
current RPM is calculated only once per 720 degrees, based on the duration of these 720 degrees - so RPM could be ~700 degrees late.

A precision improvement here would be to calculate RPM 
a) based on a sliding 720, not 720 cycle
or b) based on few last teeth, not full 720 cycle 

Reported by: rusefi

**Comment by smonette-jive** [comment]
I'm not sure if the micro-controller has enough processing power to calculate the RPM at each crank trigger base on the time spent between the triggers. You will also need to modify the way you calculate ignition. From what I remember, the code calculates the ignition timers at the beginning of each cycle. You can fix this issue by calculating the ignition timers (modify future timers) at each crank trigger interrupt. This would also make the ignition a lot more accurate on acceleration and would also produce more power too.

**Comment by OrchardPerformance** [comment]
Closing because instant RPM appears to be functional after merge #2180
