### ISSUE TITLE
 flash_reboot_dfu.bat feedback

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3300]
@andreika-git says

calls the console, which reboots the ECU, but then does not complete and freezes in anticipation of something, without closing the port - and no further dfu firmware update occurs

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/135771549-3cba8f1e-180c-49da-9369-8941182f8208.png)

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/135771558-2d5f62b1-9b28-4423-b608-fb4887c38cfd.png)

**Comment by rusefillc** [comment]
@andreika-git unable to reproduce, looks like expected in master with discovery

![image](https://user-images.githubusercontent.com/48498823/135771580-9f8b0ea5-cc78-4cb9-be53-d35ac53b0095.png)

**Comment by andreika-git** [comment]
Maybe it's somehow related to multiple COM ports?
![image](https://user-images.githubusercontent.com/15104768/135801254-3bb4caea-d331-4690-8a5b-a5e2095dbf42.png)

**Comment by rusefillc** [comment]
I've added some logging can you please try again with latest console in 20+ minutes from now?

**Comment by rusefillc** [comment]
also your console is 0523 who knows what else has changed worth trying latest just to be sure

DFU reboot protocol should be totally the same

**Comment by andreika-git** [comment]
![image](https://user-images.githubusercontent.com/15104768/135978251-95796288-c961-456b-9ea0-327bd42438ab.png)

**Comment by andreika-git** [comment]
![image](https://user-images.githubusercontent.com/15104768/136234821-311f8da3-0b2b-492c-9d41-79ae9c9b625b.png)

**Comment by andreika-git** [comment]
It kinda works... It resets DFU and after ~8 seconds of delay it exits.
