### ISSUE TITLE
rusefi_Console: Too long re-connection time

### ISSUE THREAD

**Issue by andreika-git** [rusefi/rusefi#3305]
TunerStudio is able to restore the connection in a few seconds after the USB cable is connected again.
But the Console has a too long reconnection timeout (>10 seconds?). It would be perfect if we could match the TS timings.

**Comment by mck1117** [comment]
>  But the Console has a too long reconnection timeout (>10 seconds?). It would be perfect if we could match the TS timings.

That is, if it works at all. Usually the console just crashes for me upon reconnect attempt.

**Comment by rusefillc** [comment]
Q: what is this about?
A: @andreika-git often need to reset ECU while bench testing stuff like stepper etc so we want a lighter ECU reset workflow

**Comment by rusefillc** [comment]
@alxrMironovHome can you help?

**Comment by rusefillc** [comment]
@andreika-git how does it look with the change?

**Comment by rusefillc** [comment]
@alxrMironovHome discovered that drama was about poking driver with port number which was not yet valid at that point. that was hanging-ish the driver.

now with the fix we wait for port to become officially available again and things seem to have improved!

**Comment by mck1117** [comment]
Fixed by #3936
