### ISSUE TITLE
why does averagedMapRunningBuffer use min() instead of avg()

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#3309]
Why does `averagedMapRunningBuffer` use `min(...)` instead of `avg(...)`?

I think I understand what the feature is for, to average the sampled MAP across multiple sample events (ie, cylinders) to get a smoother reading.  But why would it select the minimum of all samples, instead of the average of all samples?

**Comment by andreika-git** [comment]
That's because it is used mostly for ITBs. Each ITB has its own vacuum tube, but they are interconnected into one common MAP input. And only one cylinder has valid MAP readings at a time - one ITB draws-in air (intake stroke), but others can push out air because of resonant effects in the manifold (the inlet valve closes and the air wave moves backward). In other words, the MAP sensor value can be greater than the real cylinder vacuum - and it means that the bigger value is wrong. And at the same time MAP readings cannot be less than the real vacuum - it means we can take the smallest one as the "true" one!
Here's the example of a smooth ITB MAP data:
https://rusefi.com/forum/download/file.php?id=3154
It was a major breakthrough for me back in 2017 :)

**Comment by mck1117** [comment]
Do you have any data to support that different values of `mapMinBufferLength` actually provide a difference in the measured value or smoothness?

**Comment by mck1117** [comment]
Also, remember that especially for ITBs, the goal is not *correct*, but instead *repeatable*, and average may be a more *repeatable* measure that will also give better transient response (the whole point of ITBs!).

**Comment by andreika-git** [comment]
> Do you have any data to support that different values of `mapMinBufferLength` actually provide a difference in the measured value or smoothness?

I use only mapMinBufferLength = numberOfCylinders (meaning the last N cylinders, N=4 in my case).
I've also tested values less than numberOfCylinders and it didn't work well for me. And of course = 0 (or =1) just disables the feature. 
All other larger values like 2*N etc. make no sense to me (= slower response).

**Comment by mck1117** [comment]
Yes, I certainly agree that the only valid values are probably 1 or N=cylNum.  Do you have back to back comparisons of N=1 and N=4 on your engine?

**Comment by andreika-git** [comment]
It was just unusable with N=1:
![image](https://user-images.githubusercontent.com/15104768/135805142-c71f6eba-4dcd-4478-b4b8-9d27e10c014e.png)
![image](https://user-images.githubusercontent.com/15104768/135805238-528abdea-1c84-4815-ad19-6fbe8c2fe1b2.png)

**Comment by mck1117** [comment]
Wait, but that looks like a MAP sensor on only a single cylinder.

![image](https://user-images.githubusercontent.com/568254/135805392-2b4412e0-7f2d-4d17-afdd-6ada19672826.png)

Once the engine is running the aliasing is pretty bad (TS update rate vs. MAP update rate), so it's hard to tell if it's really that noisy, or just measuring on a single cylinder.  If it's really that much variation in MAP between cylinders, I have to wonder about cylinder-to-cylinder balance (mechanical) and plumbing balance for the MAP sensor.

Anyway, if it was a small to moderate variation, average would work fine too.  Sort of hard to tell from that log how bad it really is.

**Comment by andreika-git** [comment]
It's definitely not only 1 cylinder :)
There are 2 pairs of 4 hoses connected to common junctions:
![image](https://user-images.githubusercontent.com/15104768/135806303-e98813cd-3370-4dca-bae2-d4cd82a7ba6c.png)
![image](https://user-images.githubusercontent.com/15104768/135806244-539eca62-37ff-40f3-8e53-378a2f4f35a6.png)
One quadruple is for MAP sensor, another is for vacuum brake booster.
And the engine is idling rather nasty with N=1, trust me.

**Comment by mck1117** [comment]
My question is not whether `N=1` is correct for your engine - my question is whether *average* instead of *minimum* would provide equivalent results.  A log at sufficient update rate with N=1 would provide enough information to make that determination.

**Comment by mck1117** [comment]
PS: are those motorcycle throttles?

**Comment by andreika-git** [comment]
> My question is not whether `N=1` is correct for your engine - my question is whether _average_ instead of _minimum_ would provide equivalent or superior results. A log at sufficient update rate with N=1 would provide enough information to make that determination.

I cannot find logs with the "avg" version, sorry. It was 4 years ago, and the "min" version appeared after I tried the "avg" first. Also I remember that current "min of the window-averaged samples" version was better than "min of all samples during the cycle".

> PS: are those motorcycle throttles?

yes, and they were balanced:
![image](https://user-images.githubusercontent.com/15104768/135807034-59a19734-8cb0-4f72-9022-c3d310864e69.png)

**Comment by andreika-git** [comment]
Min. MAP value is a common practice for ITBs. The ideal solution is to use 4 separate MAP sensors and choose the min value. For example, @jharvey has a hardware solution for combining MAPs: https://github.com/jharvey/MultiMAP

Also people use back-flow valves as a mechanical substitute...

**Comment by mck1117** [comment]
well, anyway, current behavior is preserved in #3292
