### ISSUE TITLE
MAP estimate table axis is not numerically ascending on Frankenso upgrade 

### ISSUE THREAD

**Issue by OrchardPerformance** [rusefi/rusefi#3312]
Morgan upgraded his frankanso ( from snapshot_20210516_143957_stm32f407_rusefi -> to snapshot_20210909_074135_stm32f407_rusefi) 

This caused a table axis error on the MAP estimate table. 

Do we need to set a new default for that table? 

![image](https://user-images.githubusercontent.com/49926376/135773710-071a78d8-55fe-450a-b96b-99bf2d16145a.png)

![image](https://user-images.githubusercontent.com/49926376/135774159-87778cd9-2c8b-4b33-9617-42103c78f4ca.png)

**Comment by rusefillc** [comment]
at the moment the "official" migration procedure (not nice) is via TS - I believe this was NOT done here

at the moment just setting both axis to zero would do the trick of killing the error

we do not have partial incremental defaults, it's either reset everything to default or not
