### ISSUE TITLE
FEATURE REQ: aux temperature inputs

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#332]
We need a two more AUX temperature inputs in addition to existing CLT and IAT

Reported by: rusefi

**Comment by rusefi** [comment]
Someone else is asking same thing https://rusefi.com/forum/viewtopic.php?f=5&t=1565

**Comment by rusefi** [comment]
https://rusefi.com/s/debugmode  = "Aux Temperature" added

aux1 is debugFloat1 and aux2 i debugFlost2, in celcius

**Comment by OrchardPerformance** [comment]
This is in the firmware and appears to be working? 
Close?

**Comment by ByteVenom** [comment]
This is partially implemented. This needs to have a more obvious channel in the RusEFI to be used, other than DebugFloatx. Is there any reason why it can’t be renamed to AuxTempx and be put in as a available sensor channel?

**Comment by rusefi** [comment]
Another related thing is auxVoltage which does not seem to be implemented completely

**Comment by mck1117** [comment]
aux sensors work
