### ISSUE TITLE
IAT and CLT presets

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/rusefi#3321]
Please add drop down for Coolant temp and Intake air temp known calibrations.  See below for NA and NB calibrations in that order. So we should have NA miata, NB miata, GM IAT, and any other applicable sensor cal.  

![image](https://user-images.githubusercontent.com/82395131/136228038-aad9c5be-4323-4bb3-ab1e-ff4f63b4e434.png)

![image](https://user-images.githubusercontent.com/82395131/136227984-949db25a-8fd5-4bbe-bd41-6f300fdb45dc.png)

**Comment by rusefillc** [comment]
#3054
