### ISSUE TITLE
rusEfi_Console exits (crashes?) after ~2mins of disconnected inactivity

### ISSUE THREAD

**Issue by andreika-git** [rusefi/rusefi#3324]
Steps to reproduce:
1) Connect the ECU via USB
2) Start the Console (status: connected)
3) Disconnect the USB cable
4) Wait ~2 minutes
5) The Console exits unexpectedly

The error log is attached:

[err.log](https://github.com/rusefi/rusefi/files/7295754/err.log)

**Comment by mck1117** [comment]
this does not repro any more
