### ISSUE TITLE
external muxes for internal ADC

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3350]
Ethernet pin conflict raised the issue of ADC shortage

At least on STM32H7 we can use external muxes to multiply number of channels by N

@mck1117 says

the plan on atlas is to use external muxes to multiply number of channels by N
sample group A
flip mux
sample group B
flip mux
sample group A

**Comment by mck1117** [comment]
The H7's ADC is fast enough to do that flip/sample/flip/sample *for the fast ADC*.

**Comment by mck1117** [comment]
Do we need to on F4? What's wrong with the setup today on F4?

**Comment by rusefillc** [comment]
Ethernet on f4 seems to be asking

**Comment by rusefillc** [comment]
8chan as first board with mux?

https://github.com/rusefi/alphax-8chan/issues/3

**Comment by rusefillc** [comment]
Ugly limited implementation works

linked tune & log uses muxed analog inputs for pedal, and non-muxed input mux

https://rusefi.com/online/view.php?msq=1356
https://rusefi.com/online/view.php?log=1136

**Comment by dron0gus** [comment]
Some fixes https://github.com/rusefi/rusefi/pull/6732
