### ISSUE TITLE
REO NB1 ecu not recognized

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/rusefi#3351]
NB1 tunes are not being recognized when attempting to load to REO.  

![image](https://user-images.githubusercontent.com/82395131/137221116-f0812f19-9a81-44a3-9b86-04e2e405fd3d.png)

**Comment by rusefillc** [comment]
@andreika-git this is about dash in signature/bundle name

@andreika-git do you remember if there are reasons why we do not allow dashes in signature/bundle names?

**Comment by rusefillc** [comment]
@BeerMoneyMotorsports latest bundle should work - latest .ini file was added into the catalog
