### ISSUE TITLE
firmware update via CAN

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3362]
stm32 seems to have CAN support in bootloader

how can we update rusEFI firmware via CAN?

**Comment by rusefillc** [comment]
Why?

My preference is to update hardware but not deal wigh custom code due to support costs forever

**Comment by rusefillc** [comment]
https://github.com/andreika-git/hellen-one/issues/108 created

**Comment by dron0gus** [comment]
Maybe OpenBLT https://www.feaser.com/openblt/doku.php?id=homepage ? PC tools/libs are also available in this project.

**Comment by dron0gus** [comment]
Cando https://www.cananalyser.co.uk/cando.html is GD32E103 (STM32F103 clone https://www.codetd.com/en/article/12803421 ) adapter. Is it possible to run https://github.com/moonglow/pcan_cantact on it?

**Comment by rusefillc** [comment]
it works!
