### ISSUE TITLE
pinout documentation: proteus links not in browser address bar on Proteus black 23

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3365]
all in Chrome:

step 1: open https://rusefi.com/docs/pinouts/microrusefi/
step 2: click on pin 5

result: browser URL has exact URL of pin 5, great https://rusefi.com/docs/pinouts/microrusefi/?connector=main&pin=5

![image](https://user-images.githubusercontent.com/48498823/137826022-0f11c41f-2d62-4114-aa80-68637ba187fb.png)

step 3: open https://rusefi.com/docs/pinouts/proteus/
step 4: click on pin 5

result: no change in browser URL
expected result: explicit URL of pin 5

![image](https://user-images.githubusercontent.com/48498823/137826074-25c666ec-6a60-4566-b7fe-920560193662.png)

**Comment by chuckwagoncomputing** [comment]
Proteus does not have the necessary information in the yaml for this feature to work.

**Comment by rusefillc** [comment]
Progress, thank you for your patience.

So https://github.com/rusefi/rusefi/commit/7f5b4b7953d143d71b917a62c9fb455ba315dc8f

Let's make those fields mandatory? it looks like current flexibility is just too confusing - at the moment there is no way for a human to guess what fields missing or present cause what effects.

If we simply make those mandatory we would be in a much simpler to comprehend situation

I am happy to adjust all files once generator starts to fail

**Comment by rusefillc** [comment]
@chuckwagoncomputing we have a problem. Should I revert https://github.com/rusefi/rusefi/pull/3950?

![image](https://user-images.githubusercontent.com/48498823/154824006-1b08e87a-7edd-4936-939f-e5a25e43f898.png)

I believe those pins in question cannot really have ID?

```
  - pin: 23
    function: Crank Pos/Trigger #1 +

  - pin: 24
    function: Crank Neg/Trigger #1 -

  - pin: 25
    function: Cam Pos/Trigger #2 +
```

is the root cause that "id" should not be _primary key_ but "pin" should?

**Comment by chuckwagoncomputing** [comment]
Maybe the error message isn't clear enough. The `id` field goes in the info section; it's not something that each pin has, but rather a single id for the whole connector.
Example:  https://github.com/rusefi/rusefi/blob/45c5082b885c1b1e33a1a0eb3171a6185db0e145/firmware/config/boards/proteus/connectors/black23.yaml#L155

Frankenso doesn't even have the info section, and until now the pinout generation has just failed silently. I haven't looked, but I'm sure it's not the only board that doesn't have it.
Maybe we should just print an error message and not fail the whole workflow? i.e. revert the change to misc/jenkins/generate_pinouts/gen_upload_pinouts.sh

**Comment by rusefillc** [comment]
Oh gotcha

I've just pushed _something_ and poke the action again

**Comment by rusefillc** [comment]
it's green again!
