### ISSUE TITLE
flatshift

### ISSUE THREAD

**Issue by proracing1** [rusefi/rusefi#3380]
Hello everybody,
I am very into race cars and have installed 4 ecus. The result is great and I am very happy. 
I really miss the flat foot shifting feature though. 
Is it feasible to have and active low input trigger an ignition retard for the time that the input is driven low?
Best case scenario is to have trigger conditions such as rpm, tps % etc
Best regards!

**Comment by OrchardPerformance** [comment]
Achieving this is similar to the clutch activated version, it just triggers off a microswitch on the shifter instead, microswitch triggers a heavy ignition retard or cut before the ecu allows the auto to shift or a detent is released on the sequential box to allow the shift to be completed. 

Detect microswitch signal > cut or retard ignition > trigger output for gear release > wait some time to reenable ignition. 

The logic here would be similar to that needed for ignition retard while an auto transmission shifts.

**Comment by rusefillc** [comment]
see Lua draft https://github.com/rusefi/rusefi/blob/master/firmware/controllers/lua/examples/quickshift.txt

**Comment by rusefillc** [comment]
see more complex script https://rusefi.com/forum/viewtopic.php?f=5&t=2670

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi/issues/5608
