### ISSUE TITLE
lua CAN rx notes

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#3404]
- add one handler per bus (onCan1Rx)
- add a parameter to the handler for bus
- add a parameter to the listener config to only listen to that ID on some bus(es)

Kirby  1:35 AM
I think a handler per bus makes the most sense
Matthew Kennedy  1:35 AM
option 3 could also coexist with 1/2

Kirby
also, thinking about it more, ListenCan(BUS,ID,MASK,[DLC])
id take a mask argument too, to process ranges

Matthew Kennedy  1:40 AM
`if (eid & MASK == ID)` ?
1:40
anyway that's easy enough to add later
Kirby  1:41 AM
yep

**Comment by rusefillc** [comment]
We have it see https://www.rusefi.com/forum/viewtopic.php?f=5&t=2062
