### ISSUE TITLE
BUG corrupted configuration if power loss during write

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#341]
tomiata has reproduced corrupted flash configuration by turning power off while burning config

we need to keep two copies of configuration in flash so that at least one is OK

See http://rusefi.com/forum/viewtopic.php?f=5&t=1145&p=22145&hilit=reliability#p22137

Reported by: rusefi

**Comment by rusefi** [comment]
Stefan reports wiped out configuration on tuning engine off after auto-tune with a laptop

See http://rusefi.com/forum/viewtopic.php?f=3&t=1076&p=24889#p24889

**Comment by mck1117** [comment]
this was fixed in #1123
