### ISSUE TITLE
Digital speed divider board

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3412]
We need a small board just to divide high/low signal frequency by 8 or by 16

See https://github.com/rusefi/rusefi/issues/2935

Please have power LED, rounded edges, silk and a couple of random mounting holes

**Comment by rusefillc** [comment]
for audi couple 1+135 trigger decoding i might need reset feature. For existing board I was thinking to power off/power on to reset

Q1: what is power consumption of this board? can I feed it from TC4427?

Q2: what is start-up time? I have 30 us :)

**Comment by mck1117** [comment]
Q1: power consumption is effectively zero.  Something like 50 microamperes.
Q2: start up time is also effectively zero, as soon as it has power, it works (no software, just hardware)
