### ISSUE TITLE
Steve says: fuel fuel trim

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3422]
Cells not necessary, more clarification is needed

@BeerMoneyMotorsports please help

**Comment by mck1117** [comment]
> Cells not necessary

what does that mean?

**Comment by rusefillc** [comment]
@mck1117 I assume
![image](https://user-images.githubusercontent.com/48498823/139491805-b63d3a6d-c329-46ae-8116-faf8c4602448.png)

**Comment by mck1117** [comment]
Those have tooltips now. Closing.
