### ISSUE TITLE
proportional spark cut

### ISSUE THREAD

**Issue by mmatousek89** [rusefi/rusefi#3427]
lets cut sparks in controlled way , cut exactly needed percent of sparks without risk of overheating one cylinder and fouling plug with unburnt fuel on other cylinder. and on top of that preferably adjust percent of cut from LUA

 ideal is ign+fuel cut ( whole event cut ) but thats dificult to do properly due to fuel pudling in intake and other challenges related to fuel cut and fuel. restore in proper way.... its much easier on gdi...

you can allso RANDOMISE by registering number of cut on every single cylinder and aply cut on cylinder with lowest number of previuous cuts 

bigger question for me is how to aply 30%cut properly, you have to choose some time window to have period of "pwm" controll but in same time you want to distribute cutted events as evenly as possible

when just counting loud:

4cyl 6000rpm
100revs per sec
200events per sec
at least 10hz spark cut pwm freq
20events to calculate PWM
thats 5% resolution of "SparkCut" variable.
or we can calculate over series of 5 pwm periods and do one more or less cut  in one period to obtain more precise resolution.

but we still need to evenly distribute cuts over one period, cuting 10 consequent events and leaving 10consequent events for 50% cut doesnt seem to me like good idea,
it will be beter to cut one, leave one, cut one and so on to obtain smooth engine run even when cutting 50% of sparks

**Comment by OrchardPerformance** [comment]
Can you be specific about the operating condition you would want to trigger this controlled cut under?

**Comment by rusefillc** [comment]
this is all about launch control

**Comment by mmatousek89** [comment]
allso gear cur, soft rev limiter, pit limiter, maybee traction controll and allso antilag and torque correction

**Comment by rusefillc** [comment]
#3385

**Comment by rusefillc** [comment]
```
setSparkSkipRatio(0.3)

function onTick()
end
```

![image](https://user-images.githubusercontent.com/48498823/142170817-0f68f7ed-47c6-48f0-acc2-deeb0a51597c.png)

![image](https://user-images.githubusercontent.com/48498823/142170839-214ca391-36e2-4df9-bfe4-0dcafc94e19d.png)

![image](https://user-images.githubusercontent.com/48498823/142170859-94a1dace-810a-41e6-8af4-c10c7d662d04.png)
