### ISSUE TITLE
Do we need double PID in closed loop DC wastegate

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3429]
Do we have first PID to come up with "DC motor target" and then second PID from DC target into duty cycle?

Should it be one PID from pressure into DC motor duty cycle?

**Comment by rusefillc** [comment]
first PID + open loop generates "boost position"

second PID moves thingy to hit "boost position"

**Comment by mmatousek89** [comment]
thats definetelly what i want!

**Comment by rusefillc** [comment]
Martin says "in my opinion 2x pid is definitely what i want for EWG."
