### ISSUE TITLE
instant shaft acceleration

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#343]
https://m.cyberleninka.ru/article/v/diagnostirovanie-dvs-po-pokazatelyam-uglovoy-skorosti-kolenchatogo-vala is another reason to imrove instant shaft acceleration calculation

See
	SC_RPM_ACCEL = 3,
	SC_DETAILED_RPM = 4,

Reported by: rusefi

**Comment by mck1117** [comment]
we now calculate and log RPM rate of change in rpm/s
