### ISSUE TITLE
remove background from "program" icon or replace icon

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3435]
at the moment ugly white background on icon

![image](https://user-images.githubusercontent.com/48498823/139594469-c28635c5-6f57-4e6a-877b-6c40e8845199.png)

need a better icon at least without ugly background

**Comment by rusefillc** [comment]
and kind of broader question of all easily visible icons

**Comment by rusefillc** [comment]
Maybe use $$$ toward design improvements

**Comment by rusefillc** [comment]
@ksmola what shall we do about 

![image](https://user-images.githubusercontent.com/48498823/139608817-278c0829-1745-4ec6-b36e-8db9b50e0673.png)

background and all?

**Comment by ksmola** [comment]
see latest PR

**Comment by rusefillc** [comment]
Thank you @ksmola

That's one amazing leap total total domination!
