### ISSUE TITLE
do not control VVT during cranking

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3443]
during cranking at least on Honda K we get very weird VVT angles, also we do not have oil pressure anyway

I guess we should not bother with VVT PID during cranking?

**Comment by mck1117** [comment]
random OEM tune has a minimum VVT operation RPM

![image](https://user-images.githubusercontent.com/568254/140197466-4bf5cb3d-2ec4-42ca-a32a-2579118002f4.png)

**Comment by blundar** [comment]
It is very common in OEM land for there to be a delay between startup and
VCT control.  I think there is a lot of concern about getting oil pressure
to stabilize before diverting oil pressure to do additional things.

**Comment by mck1117** [comment]
> I think there is a lot of concern about getting oil pressure to stabilize before diverting oil pressure to do additional things.

also, preventing integrator windup during a period of no oil pressure, then oil pressure arrives, and it bonks the cam in to the stop

**Comment by mck1117** [comment]
so I see a need for two things then:
1. minimum VVT control rpm, if below RPM, reset pid controller and output 0 duty
2. minimum VVT engine run time, if engine not running long enough, reset PID and output 0 duty

**Comment by rusefillc** [comment]
Yes, but maybe reuse cranking RPM for 1.?

**Comment by mck1117** [comment]
Yeah, that's probably fine for now unless we come up with a good reason that doesn't work. #2 mostly covers it "engine just started and is at low RPM" anyway.
