### ISSUE TITLE
On Proteus Main relay control

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3447]
We have ``EFI_MAIN_RELAY_CONTROL`` which control is we simply do "1" or vbatt conditional logic for main relay control

most hellens for instance have 
```
DDEFS += -DEFI_MAIN_RELAY_CONTROL=TRUE
```

it looks like Proteus is NOT using this feature and has less smart MR control

is this a feature or a bug?

**Comment by rusefillc** [comment]
looks to me like at least current Proteus is good for MR control based on VBatt

![image](https://user-images.githubusercontent.com/48498823/140150942-5704f4ae-bae1-4817-a4de-b1084b7ca915.png)

**Comment by rusefillc** [comment]
Same on 0.2

![image](https://user-images.githubusercontent.com/48498823/140152360-851eb87c-ed4e-43c4-b0ec-ae324d621fa3.png)

**Comment by mck1117** [comment]
yes, I think that would be fine to do.  I seem to remember the EFI_MAIN_RELAY logic was maybe super complicated, but that's a separate issue.

**Comment by rusefillc** [comment]
@mck1117 you recall correctly - at least at some point EFI_MAIN_RELAY extremely complicated. I believe it was simplified a few months back and one day we shall re-implement the advanced behaviors in a much cleaner way.
