### ISSUE TITLE
Limit ETB to < 100% 

### ISSUE THREAD

**Issue by duhafnusa4** [rusefi/rusefi#3457]
@mck1117 and I through testing on my car found problems with ETB when value is 100% or greater. 

We need to limit the ETB to less than 100%. @mck1117 feel free to comment

**Comment by rusefillc** [comment]
@mck1117 can you please elaborate? is this about TS UI limitation? is this about defaults? is this about software changes?

**Comment by OrchardPerformance** [comment]
This is to prevent the ETB driving past 90 degrees, this is possibly a software change to allow a user settable limit to prevent this situation. 

See image below with the ETB at 100% but sitting about 5-10 degrees past fully open (90deg). 
![image](https://user-images.githubusercontent.com/49926376/140531293-3b20c2eb-67a9-48dd-adcd-e0ac86510e62.png)

**Comment by rusefillc** [comment]
So is this a chance for auto-calibration to calibrate 100% point as NOT the full open but magic percentage of full open?

**Comment by duhafnusa4** [comment]
I recognize that thumb, and the photo i took doesnt do it justic, Id say its closer to 10% past 100%
