### ISSUE TITLE
Nissan MR18DE trigger

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#3461]
Do we support this trigger pattern?

![image](https://user-images.githubusercontent.com/568254/140406262-d56dd3ba-78be-41c6-bc69-5a44b8099970.png)

**Comment by rusefillc** [comment]
Does not looks like we support https://github.com/rusefi/rusefi/wiki/All-Supported-Triggers#nissan :(

What's the evil plan?

2004–2012 Nissan Tiida/Versa

**Comment by mck1117** [comment]
I want a VVT test mule

2004-2012 Nissan Tiida/Versa has VVT

There is a 2004-2012 Nissan Tiida/Versa in my driveway 😈

**Comment by rusefillc** [comment]
@mck1117 https://github.com/rusefi/kicad-libraries/commit/eb70637ed6f87a6ff3a6fb60054b460edcd2e4e6 see https://rusefi.com/forum/viewtopic.php?f=4&t=2195

**Comment by mck1117** [comment]
it looks like a close relative of the VQ cam pattern but 1-3-4-2 instead of 1-4-5-2-3-6

![image](https://user-images.githubusercontent.com/568254/140422535-0361aa2b-d6e0-43ff-a00c-158b36acdee6.png)

**Comment by mck1117** [comment]
crank on MR18DE is 16 teeth, then two teeth of skip, aka it's 36-2-2

**Comment by mck1117** [comment]
we can close for now, will revisit when I can log exact trigger from the car.
