### ISSUE TITLE
+ symbol required to make TS tips show

### ISSUE THREAD

**Issue by OrchardPerformance** [rusefi/rusefi#3463]
![image](https://user-images.githubusercontent.com/49926376/140527080-5ab8f407-df1d-4b58-a905-9ae0f1522bf4.png)

Image above shows a case where there is a TS tip but it is not displaying due to a lack of +

I have not checked _every_ case but it looks like it is true for all the tips without + symbols at the start.

**Comment by OrchardPerformance** [comment]
Shows up as lines 382 and 383 in VS code 
![image](https://user-images.githubusercontent.com/49926376/140527474-064a48a2-c381-449c-b09b-cc8e9b044d35.png)

**Comment by rusefillc** [comment]
@OrchardPerformance weird. Unless we somehow speak about different fields? See image

![image](https://user-images.githubusercontent.com/48498823/140571841-2a5d8c2f-b52d-4300-bdaa-8766b1ee7a9d.png)

**Comment by rusefillc** [comment]
@OrchardPerformance ?

**Comment by OrchardPerformance** [comment]
It looks like I picked a terrible example, actually possibly the worst available. 
I pulled that out while busy at work, agree there is a double comment there, it was one to correct from the PR. 

Checking better see below:
![image](https://user-images.githubusercontent.com/49926376/141042431-34a9314b-28a9-492f-93b1-c83f7f174b99.png)
![image](https://user-images.githubusercontent.com/49926376/141042458-beb66620-5ac5-4b60-92fb-7eeb1f5fdd1a.png)
![image](https://user-images.githubusercontent.com/49926376/141042484-e08330ef-88df-40e1-8559-c370c8550e34.png)


![image](https://user-images.githubusercontent.com/49926376/141043392-9f78f474-fac4-4926-b039-e8713fb40ece.png)
![image](https://user-images.githubusercontent.com/49926376/141043417-101149e1-c671-4c7e-86ea-2a0604c29d08.png)
![image](https://user-images.githubusercontent.com/49926376/141043448-71cfb289-8cba-44d9-b48d-63b26ae8b81b.png)

**Comment by rusefillc** [comment]
I've pulled latest .ini and I seem to have both tooltips?

![image](https://user-images.githubusercontent.com/48498823/141194270-e81f70e2-78d3-45bb-96c0-05b1f7b51519.png)

![image](https://user-images.githubusercontent.com/48498823/141194333-c63f4c4f-0e5c-4468-8036-757f548edf2d.png)

**Comment by OrchardPerformance** [comment]
OK that is weird. 
It was a late October bundle I took those screen shots of, will check the exact date but I think it's the perogi day release. 

Let me check a couple of releases and update in an hour or so.

**Comment by rusefillc** [comment]
I do not follow. Why do we look at releases at all? I believe we only care about how SNAPSHOT works.

I am failing to convince you that I've changed this in SNAPSHOT :( Any release is simply irrelevant here is not it?

I can get you exact date of when this was changed but my concern stands: we only care about snapshot nothing else.

**Comment by OrchardPerformance** [comment]
So when I asked: 
![image](https://user-images.githubusercontent.com/49926376/141200944-67b0ba98-b6d1-4885-aad7-5faf8386a3fb.png)
The correct answer was "this has been changed in the last few weeks so it is no longer needed" 

8 days ago when the PR was submitted and neither Matt nor myself knew why + symbols were missing the key information was really "This was changed recently enough that the current release is obsolete and the workflow has changed in the last couple of weeks" 

When I raised this ticket wondering why neither I not USERS could see these tips the vital information was "I have changed this since the release" 

It is not about convincing me of anything, simply letting me know that a change has happened so recently that it is only in snapshot and I might see different results if I am not using the snapshot. 

I am referring to the release as I need to be able to see what users see and why they are asking questions that could be answered in tool tips. 
Obviously when there is no tip in the release and I see one with a missing + in the current git version I am going to think there is a problem with missing + because no one said things changed since the version the users are looking at.

**Comment by rusefillc** [comment]
in my opinion releases are not relevant for development and this was all about development

knowing exact user version is helpful for troubleshooting - some users use some releases some users use some snapshots for reasons. "latest release" does not hold a very special place in my opinion.

overall all my life is in snapshot. latest release was a month ago, that's about 8 times longer than my attention span.

Note how I was pointing at "master" which is maybe where I should have be more clear since "master" is git specific talk to "snapshot"

![image](https://user-images.githubusercontent.com/48498823/141205275-dc7a788e-080d-427d-8b79-a1aa34870406.png)

**Comment by OrchardPerformance** [comment]
This is why we need some stability
