### ISSUE TITLE
TS project is not happy

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3481]
![image](https://user-images.githubusercontent.com/48498823/140618859-ef9c8818-5646-4556-932e-557141773767.png)

@racer-coder to be honest I do not know what is wrong exactly but it's next to hpfp changes from yday

**Comment by racer-coder** [comment]
It's a capitalization bug, but I'm trying to figure out why I can't reproduce it

**Comment by rusefillc** [comment]
i had old project
I went to update .ini for existing project and got bug

capitalization between what and what? I am blind on top of everything

**Comment by racer-coder** [comment]
How did you get that window to pop up?  I had to dig into TunerStudioAppDebug.txt to find that message.

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/140619542-89dba2ac-3907-4912-9111-0092f6f99d6a.png)
