### ISSUE TITLE
unit tests build time: Address sanitizer

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3485]
Can we please NOT run Address sanitizer in "default' makefile unit_tests build but only on github actions?

I am looking to get myself a quicker local build :)

**Comment by rusefillc** [comment]
@mck1117 can you help?

@racer-coder FYI

**Comment by racer-coder** [comment]
Normally i'd recommend clang for faster compile times but it was even slower than gcc.  It might be related to coverage compilation too.

**Comment by mck1117** [comment]
Code coverage is much more expensive than asan. I tested it and asan made almost no difference.

**Comment by racer-coder** [comment]
I also got a big improvement removing -Wa alms blah blah

**Comment by mck1117** [comment]
> I also got a big improvement removing -Wa alms blah blah

good call, that saves ~20% for me

**Comment by mck1117** [comment]
Also, you do really want asan enabled for development.  That's when you're going to be making leaks/overruns, so you want it always there.
