### ISSUE TITLE
Remove Miata MX5 NB1 trigger

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3488]
NB1 trigger is same as NB2 VVT configuration

in order to simplify life we shall remove NB1 trigger and use NB2 on NB1

**Comment by mck1117** [comment]
@BeerMoneyMotorsports presumably you could test this at some point, set an NB1 board to NB2 vvt trigger settings, and see what happens?

**Comment by BeerMoneyMotorsports** [comment]
Yes. Nb vvt should be renamed to NB amd other nb deleted

**Comment by rusefillc** [comment]
@BeerMoneyMotorsports this has happened!

**Comment by rusefillc** [comment]
@BeerMoneyMotorsports 

@BeerMoneyMotorsports NB1 trigger is gone, people with old NB1 trigger will get fatal error





10:18
on hellen NB1 boards we technically can make stuff hard-coded (edited) 
10:18
so that new firmware would change it's own settings
10:19
nope we cannot :disappointed:
10:20
if we go 'board override' it would be impossible to go 36/1
10:20
i assume you want 36/2 as option
10:20
so all we can 'override' is VVT
10:20
and trigger pins
10:20
@BeerMoneyMotorsports let me know
