### ISSUE TITLE
TS Bench test problem - Coil 1 test error

### ISSUE THREAD

**Issue by OrchardPerformance** [rusefi/rusefi#3490]
I tried to bench test coil 1 and received the following error

![image](https://user-images.githubusercontent.com/49926376/140628455-5c5f4ee8-20f7-49f4-b60a-1fe02d207858.png)

Edit to add - Test button for coils 1,2 and 3 cause this error. 
Coil 4,5,6 seem to fire ok
Coils 7 + 8 seem to do nothing as not in config yet?

**Comment by rusefillc** [comment]
@OrchardPerformance please try again with .ini file from latest bundle

**Comment by rusefillc** [comment]
@OrchardPerformance in the meantime rusEFI console bench commands were not broken, the issue only affects TS buttons
