### ISSUE TITLE
Another bench test error - Injector 3 test

### ISSUE THREAD

**Issue by OrchardPerformance** [rusefi/rusefi#3491]
Similar to the coil test error #3490 , pressing test on injector 3 (H88 board) causes the error below:

![image](https://user-images.githubusercontent.com/49926376/140628809-559d823e-3fb1-4873-87f3-05803a79da43.png)

All other injectors seem to not fire when tested.

**Comment by rusefillc** [comment]
Dup of #3490 - this one I've noticed while fixing spark
