### ISSUE TITLE
XY idle ve table

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/rusefi#3496]
Idle ve is currently rpm only. It should be rpm  vs load with minimum of 6x6. 

Issue- load changes enough to cause a 3 point afr change at same rpm.  Lights, fan, window switches, etc.

**Comment by BeerMoneyMotorsports** [comment]
@mck1117 do you have time soon to assist me with this?  Hopefully i can educate myself some.

**Comment by mck1117** [comment]
this is done
