### ISSUE TITLE
Latest firmware causes an error (2021 11 07 build) 

### ISSUE THREAD

**Issue by OrchardPerformance** [rusefi/rusefi#3500]
No settings changed, board was DFU updated and plugged in, fresh TS project using the .ini in the ECU. 

![image](https://user-images.githubusercontent.com/49926376/140659833-1afe1b1e-0504-4b2b-9ba1-6bec103ea5d5.png)

I am going to try a fill erase and then flash the firmware incase it is a leftover setting.

**Comment by rusefillc** [comment]
I am offline for couple of hours, console could be a workaround for bench test

**Comment by OrchardPerformance** [comment]
I will just proceed with hardware tests on the previous (06112021) bundle.

**Comment by rusefillc** [comment]
@OrchardPerformance please test in about 14 minutes from now or later?
