### ISSUE TITLE
Main and Pump pins default set wrong

### ISSUE THREAD

**Issue by OrchardPerformance** [rusefi/rusefi#3501]
Default settings loaded with the firmware has the main relay and fuel pump relay pins incorrectly set. 
![image](https://user-images.githubusercontent.com/49926376/140661268-f6dbc855-1e8a-4edc-afa4-551230368114.png)

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/140677849-c883f868-37cd-41fa-ac20-2e18f0410b44.png)
