### ISSUE TITLE
Just to confirm - do we still need two buffers?

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3509]
@mck1117 you've added something fancy with buffers pool or else which has potentially really changed loggingcentral.cpp data workflow?

Do we still need
```
// Two buffers:
//  - we copy line buffers to writeBuffer in LoggingBufferFlusher
//  - and read from readBuffer via TunerStudio protocol commands
using LB = LogBuffer<DL_OUTPUT_BUFFER>;
LB buffers[2];
LB* writeBuffer = &buffers[0];
LB* readBuffer = &buffers[1];
```
or am I confusing this with some other potentially unused buffer?

**Comment by mck1117** [comment]
yes, we need both of those.
