### ISSUE TITLE
gcc_map_reader should scan ram4 section too

### ISSUE THREAD

**Issue by racer-coder** [rusefi/rusefi#3516]
STM32F407 and probably others have a goofy CPU-only memory.  gcc_map_reader ignores it, which is bad since it hides more opportunities to fix memory bloat.

I tried to change it myself but couldn't compile - gradle was unhappy and I'm not a Java developer... and then it left a background process running on my box?  Why on earth?

**Comment by mck1117** [comment]
pretty much all of them have multiple memories, some of them on their own bus from the CPU (like ram4 on the f407)

**Comment by rusefillc** [comment]
https://docs.gradle.org/current/userguide/gradle_daemon.html

**Comment by rusefillc** [comment]
@racer-coder can you PR broken stuff and I will attempt to fix?

**Comment by rusefillc** [comment]
#3518
