### ISSUE TITLE
more specific lua error handling

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3532]
can we know location closer to error instead of just saying "this script is broken somewhere"?

```
2021-11-11_17_22_59_408: EngineState: LUA error [string "startPwm(0
2021-11-11_17_22_59_516: EngineState: LUA error [string "startPwm(0
2021-11-11_17_22_59_625: EngineState: LUA error [string "startPwm(0
2021-11-11_17_22_59_737: EngineState: LUA error [string "startPwm(0
2021-11-11_17_22_59_846: EngineState: LUA error [string "startPwm(0
```

```
startPwm(0, 800, 0.3)
-- direction
startPwm(1, 80, 1.0)
-- disable
startPwm(2, 80, 0.0)

pid = Pid.new()
pid:setP(2)

function onTick()
  targetVoltage = getAuxAnalog(0)
  
  target = interpolate(1, 0, 3.5, 100, targetVoltage)
-- clamp 0 to 100
  target = math.max(0, target)
  target = math.min(100, target)

  pid:setTarget(target)
  duty = pid:get(analog1)
  
  print('Target ' .. targetVoltage .. ' ' .. target)
  
  
end
```

**Comment by mck1117** [comment]
you're trying to print a comma, because that's the delimeter between log messages

**Comment by rusefillc** [comment]
@mck1117 you comment is legit but my concern is different/wider?

**Comment by mck1117** [comment]
I mean that it clipped off 90% of the error message, there is a more useful message that it didn't fully print

**Comment by rusefillc** [comment]
oh so your proposal is to address clipping and revisit

**Comment by mck1117** [comment]
to unblock you for now:

`0LUA ERROR loading script: [string \"(startPwm(0, 800, 0.3)...\"]:3: ')' expected (to close '(' at line 1) near 'startPwm'`

**Comment by rusefillc** [comment]
not blocked, know where errors are just suggesting we improve one day
