### ISSUE TITLE
I bet device manager has command line interface

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3547]
Would life get better for Jimmy if rusEFI console invokes some command line device manager and yells at Jimmy based on specific hard data as reported by said command line?

**Comment by duhafnusa4** [comment]
yes it would

**Comment by rusefillc** [comment]
@duhafnusa4 please report how does it look with fresh bundle with my changes

**Comment by duhafnusa4** [comment]
yes daddy

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/142032683-2b0b8315-e005-4666-9135-79eced4058ac.png)
