### ISSUE TITLE
FEATURE REQ/DOCUMENTATION: NA6 official tune and wiring

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#357]
We have three NA6 ECUs - tomiata, hunchback and Jeff-93 - we need to unify wiring

We also need base tune to batch that unified wiring (tomiata's tune is the one to go)

Reported by: rusefi

**Comment by OrchardPerformance** [comment]
Is this ticket made obsolete by PNP and recent additions to the wiki?

**Comment by rusefi** [comment]
not yet - we do not have an official tune yet, and we kind of need it now :)

@stefanst

**Comment by mck1117** [comment]
Hellen fixes all problems - we have defaults now
