### ISSUE TITLE
BUG: TPS in console, TPS adc mode

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#358]
two problems with TPS

1) TPS seems to work in TS but not work in rusEfi console, why?

2) TPS code seems to mention fast mode in some places and slow in other places, how does it even work?!

calcFastAdcIndexes
		tpsSampleIndex = fastAdc.internalAdcIndexByHardwareIndex[engineConfiguration->tpsAdcChannel];

addChannel("TPS", engineConfiguration->tpsAdcChannel, ADC_SLOW)

Reported by: rusefi

**Comment by mck1117** [comment]
we can close this

**Comment by mck1117** [comment]
we can close this
