### ISSUE TITLE
SDcard log over ignition ON / OFF / ON with USB plugged

### ISSUE THREAD

**Issue by mmatousek89** [rusefi/rusefi#3593]
when im in car with laptop, and turn key off, there is no logging to sd card when i turn key back on, because ECU connected via usb go to MSD mode and key on does not cancel MSD mode

**Comment by rusefillc** [comment]
@mmatousek89 please use "current behavour" and "expected behaviour" to make it a bit less confusing

In your description there

**Comment by mmatousek89** [comment]
mine does not need reboot, as soon as i connect computer it goes to MSD mode

**Comment by mck1117** [comment]
correct:
- boot with USB connected -> immediate MSD
- boot without USB connected -> no MSD, write log to SD

**Comment by mmatousek89** [comment]
haa 2disk drives are showing up....

my bad that i named my sd card RUSEFI when formated  :-D

because now booth drives are RUSEFI ... 

one is SDcard

and one is  rusefi internal....

**Comment by mmatousek89** [comment]
ok sorry on this one,  its totaly my bad  i need to be more concentrated
