### ISSUE TITLE
DFU drama on one Proteus has killed DFU on second Proteus

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3597]
We took Proteus 0.6 and rebooted into DFU programmatically
We have installed STM32 BOOTLOADER driver
We saw message about readout protection

![image](https://user-images.githubusercontent.com/48498823/142941313-6637e7c3-43ba-47cb-90c0-65a1d79b490a.png)

we invoked relevant command -rdu

this has killed everything - this proteus no longer responds to HW reset button nor to HW DFU button, and windows shows:

![image](https://user-images.githubusercontent.com/48498823/142941277-e6459485-c97f-4526-975b-eca6bdd12c28.png)

we tool another unit. Proteus 0.6 runs OK but if we enter HW DFU we still see broken USB message?!

huh.

**Comment by NMSTEC** [comment]
Resolved. tldr, incorrectly configured MCU. 

1. After bricking, connected to st-link. Found memory wiped. 
2. Rewrote flash. Normal mode works, DFU did not. Reset would operate properly.
3. Checked with Matt, and compared to his ECU. Found incorrect Boot addresses, as well as nDBANK option bit
4. Set nDBANK to 0, changed BOOT_ADD0 from 0xffff to 0x80 & BOOT_ADD1 from 0xffff to 0x40.
5. Mass Erase and rewrite. Problem fully resolved, DFU and normal mode operate as expected.

**Comment by NMSTEC** [comment]
![image](https://user-images.githubusercontent.com/45252464/142970413-2e3d8de7-553e-4d36-979d-be2a6e18ebc7.png)
