### ISSUE TITLE
clutch input via CAN

### ISSUE THREAD

**Issue by NMSTEC** [rusefi/rusefi#3605]
On Harley's clutch switch info is sent from the forks via CAN, and would like it to be set in ECU from that.

**Comment by rusefillc** [comment]
@mck1117 shall we make clutch a Sensor?

**Comment by NMSTEC** [comment]
I'd rather have option for CAN inputs. For example on a different model of harley starter IS controlled by ECU, and starter switch is CAN based.

**Comment by rusefillc** [comment]
@NMSTEC do you want to create extra work and get results later, or do you prefer to stay focused and get results sooner?

**Comment by NMSTEC** [comment]
Ya gotta stop thinking everything im suggesting is 100% needed right now. 
This is for future, but will be needed. To run the bike, dont even need clutch switch as we speak anyway.

**Comment by rusefillc** [comment]
@NMSTEC 
https://github.com/rusefi/rusefi/wiki/Lua-Scripting#getoutputname
https://github.com/rusefi/rusefi/wiki/Lua-Scripting#setclutchupstatevalue
https://github.com/rusefi/rusefi/wiki/Lua-Scripting#getcalibrationname
