### ISSUE TITLE
Mark hit timer watchdog "no events since"

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3608]
@NMSTEC reports timer watchdog fatal error

![IMG_20211124_172802](https://user-images.githubusercontent.com/48498823/143345385-068a03ad-1091-4006-967e-698eb75b974b.jpg)

**Comment by mck1117** [comment]
happened again:

![image](https://user-images.githubusercontent.com/568254/144541591-d4e03735-b2e8-4f74-982f-f1ac69bb9694.png)

**Comment by rusefillc** [comment]
@mck1117 this sounds important and also it has been a while since anyone has reported. What shall we do?

**Comment by mck1117** [comment]
I guess we can close for now, reopen if we see it again?
