### ISSUE TITLE
skipspark script kills ECU

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3611]
martin says

```
setSparkSkipRatio(0.3)
```

![image](https://user-images.githubusercontent.com/48498823/143469398-11135385-3da9-4d2c-b7fd-b57b0f5bf70b.png)

**Comment by rusefillc** [comment]
I am able to reproduce the issue with MRE

I get all LEDs light up and not blink until reset

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/143520987-0e22f8e7-b7eb-451e-8722-4128bf8d18b9.png)

**Comment by rusefillc** [comment]
rand() wants to do malloc and that does not go well

![image](https://user-images.githubusercontent.com/48498823/143521570-43535908-5298-4b27-bf4f-cabdf262be6c.png)

**Comment by rusefillc** [comment]
We now use fancy https://github.com/MersenneTwister-Lab/TinyMT

**Comment by mck1117** [comment]
> malloc and that does not go well

we....actually still have a reference to `malloc` in the firmware

it's called by `strtof` within lua: https://stackoverflow.com/questions/66145835/why-do-strtod-and-strtof-of-the-newlib-c-standard-library-implementation-use
