### ISSUE TITLE
can we please have a runner for proteus-F7 to speed up that specific bundle

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3618]
At the moment proteus-F7 is the most important bundle

build queue costs us a lot of human time while active troubleshooting how can we make one build much quicker?

**Comment by mck1117** [comment]
#3622 speeds up our firmware builds significantly, as it doesn't need to download any dependencies or do a full clone first.

**Comment by NMSTEC** [comment]
I see it as a feature, I have enough time to go out for a smoke and think about where I screwed up in the project.

**Comment by chuckwagoncomputing** [comment]
Additional discovery: according to https://github.com/orgs/community/discussions/20019#discussioncomment-4722254 if you label your runners the same as the Github-hosted runners, e.g. `ubuntu-latest`, Github will run jobs on them until they're all full, then run the rest on the Github-hosted runners. This solves the main problem with #3622.

**Comment by chuckwagoncomputing** [comment]
I can confirm that this Just Works

**Comment by mck1117** [comment]
> Github will run jobs on them until they're all full

that's a good finding!

**Comment by chuckwagoncomputing** [comment]
Disregarding self-hosting, and back to the issue at hand:
Moving it to its own workflow would not help matters, as there is no way, as far as I can tell, to give a particular workflow priority in the queue. I will close this issue, and if we want to discuss self-hosting, that can be done elsewhere.
