### ISSUE TITLE
Need engine kill switch accessible in Lua

### ISSUE THREAD

**Issue by NMSTEC** [rusefi/rusefi#3620]
Injector only maaaaaay cause a lean pop, but we may as well try it first. Recommend ETB slam shut, while injector off. Use compression & vac to stop engine fast.

Prefer implementation be simple without "Shutdown till RPM 0" Long story, but prefer raw flag/switch/bool.

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi/wiki/Lua-Scripting#stopengine
