### ISSUE TITLE
output_channels.txt commit to trigger full .ini generation

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3633]
At the moment change of output_channels.txt like https://github.com/rusefi/rusefi/commit/bd48f83b7397aabee297faa878421785011fda34 does not cause full blown rusefi.ini generation - only intermediate .ini files are regenerated by gen_outputs*.sh

we might need just one line of bash change to add output_channels.txt as dependency? or else

**Comment by rusefillc** [comment]
@mck1117 can you please help?

**Comment by rusefillc** [comment]
not sure if it works see latest commits

**Comment by mck1117** [comment]
fixed?
