### ISSUE TITLE
MAP lost in Datalogging after latest snapshot 20121129@28919

### ISSUE THREAD

**Issue by NMSTEC** [rusefi/rusefi#3637]
Working on previous firmware from 3 days ago all logging was fine. All channels are logged. Gauges show MAP properly, and bike runs fine.

Logs show 0 MAP at all times
[DataLogs.zip](https://github.com/rusefi/rusefi/files/7621439/DataLogs.zip)
![image](https://user-images.githubusercontent.com/45252464/143950575-90324605-8ea8-4bf1-a767-45f6028c4c95.png)
![image](https://user-images.githubusercontent.com/45252464/143950624-bc255ba1-76cb-4608-b4cf-c3b3e03f7b09.png)

**Comment by rusefillc** [comment]
@NMSTEC great find, looks like mix-up between MAP and instant MAP

**Comment by mck1117** [comment]
This is still not right

![image](https://user-images.githubusercontent.com/568254/144131458-837f1222-fb0e-4305-a2aa-e57e5d2b469a.png)

**Comment by NMSTEC** [comment]
Could use this fixed for tomorrow with the new Cylinder pressure testing thing.

**Comment by rusefillc** [comment]
please try now - there was a chance yesterday

**Comment by NMSTEC** [comment]
Confirmed fixed.
