### ISSUE TITLE
Requesting LUA Torque intervention

### ISSUE THREAD

**Issue by NMSTEC** [rusefi/rusefi#3638]
Harleys have traction control, it requests power reduction, can be as simple as % of ETB reduction request as long as its called, and return back to stock after request has stopped.

**Comment by rusefillc** [comment]
@NMSTEC edited - one issue for one ask

**Comment by rusefillc** [comment]
We already have two relevant Lua functions open question which is the best overall logic

https://github.com/rusefi/rusefi/wiki/Lua-Scripting#settimingaddangle
allows to dial down timing, use with timer

https://github.com/rusefi/rusefi/wiki/Lua-Scripting#setsparkskipratio
allows to skip some sparks, same story use with timer

**Comment by NMSTEC** [comment]
Would prefer to have ETB request modifiable, as that would allow for more control with smoothness. Basically driver request TPP to be overridden via lua during request.

**Comment by rusefillc** [comment]
@NMSTEC please try https://github.com/rusefi/rusefi/wiki/Lua-Scripting#setetbaddextraetb
