### ISSUE TITLE
MAP Problem - unsure what it is

### ISSUE THREAD

**Issue by NMSTEC** [rusefi/rusefi#3649]
After yesterdays update MAP is all over the place... Instant map only works on low speed crank, and MAP only works while running but its jumping up and down massively.

Todays injection of crank log: https://rusefi.com/online/view.php?log=465
Yesterdays running log: https://rusefi.com/online/view.php?log=463

**Comment by NMSTEC** [comment]
Note: yesterday MORNINGS update.

**Comment by rusefillc** [comment]
Yesterdays running log: https://rusefi.com/online/view.php?log=463
![image](https://user-images.githubusercontent.com/48498823/144653455-e0b6d179-a56d-42df-95b3-f94f95f0c7e0.png)

**Comment by NMSTEC** [comment]
This is not a problem. Ignore.
