### ISSUE TITLE
Dumb CAN wake-up

### ISSUE THREAD

**Issue by NMSTEC** [rusefi/rusefi#3660]
1. rusEFI gets message "please go to sleep"
1. rusEFI turns off can TX
1. wait XXX seconds, where XXX is time for everyone to go to sleep
1. rusEFI goes in to low power wake-on-can mode

Just to clarify Harley graceful power off/power on is done via CAN not by controlling main relay

For much smarter implementation see #1731

**Comment by rusefillc** [comment]
Oh shit :( Worst case we would have to implement a dedicated microcontroller just for CAN and wake up.

**Comment by mck1117** [comment]
Can you enumerate the full list of what happens when you go from walking up to a parked bike, thru running engine?

**Comment by rusefillc** [comment]
probably relevant https://www.st.com/resource/en/application_note/dm00096220-using-stm32f4-mcu-power-modes-with-best-dynamic-efficiency-stmicroelectronics.pdf

**Comment by mck1117** [comment]
That's why I wanted clarity on what we need.  If we need to wake up for ANY packet, that's pretty easy.  If we need to only wake up for a particular packet, that's harder.

**Comment by rusefillc** [comment]
step one: bike is parked for a week, things are whatever
step two: rider sits on the bike with RFID in his pocket, rider does not touch any buttons
step three: ass sensing sensor sends a CAN message to start waking up modules
if ECU does not wake up and announce itself within unknown time, dash would persist an error code with error light. 3 minute of manual fuckery to wipe out code


there are only two wires with +12 ever:
pin 67 has constant +12
pin 5 has +12 when physical switch is in IGNITION position

BCM expects CAN from ECU while no power on pin 5. Conclusion: MCU in ECU is supposed to feed itself on constant power pin 67.

@NMSTEC please correct me if any of this is not right
@NMSTEC please elaborate of shutdown procedure in terms of what CAN activity happens when

**Comment by NMSTEC** [comment]
We need any packet whatsoever to wake up. As the rest of the vehicle does the same. 

Scenario 1. Walking to up to bike, nothing occurs. Turn IGN to on, and BCM wakes everyone up as well as turn "ign 12v" on. Wakes all up just by simply transmitting any packet. In this case 0x502 - 0x01(or 10? I cant recall, not at work)

Scenario 2. Sit down on bike, with everything off. BCM wakes up (Motion sensor) everyone with a 0x502 message, but keeps ign voltage off. At this point all modules are awake and broadcasting, and it WILL check for ECM message. If no ECM at this point, all modules set u0100 code.

Scenario 3. Without touching rest of bike, press any button anywhere on bike (Hazards, turn signal, cluster button, whatever) That module wakes up, transmits appropriate info that its awake and that it wants to say this button is pressed. At this point BCM decides to power up ign voltage, and everyone transmits data as normal until nothing else occurs, and BCM tells everyone to go to sleep. This is usually a 5 second delay.

The shutdown procedure again, can be easily implemented in LUA with some form of access to a FW switch. Wake up is allowed on absolutely any CAN message on bus, and is expected to wake up.

This can be proven with the easy fact of when I update proteus with any data, or unplug and plug it back in, my lua code transmission wakes up everyone, and BCM supplies 12v ign.

**Comment by rusefillc** [comment]
@mck1117 @NMSTEC  do I read it right that we would need a CAN shutoff to work together with CAN wake-up? i.e. we need to make sure that we wake up during overall shutdown procedure, i.e. once we decide to suspend ECU we would need to stay alive for some time while making sure that we are CAN silent?

**Comment by mck1117** [comment]
> The shutdown procedure again, can be easily implemented in LUA with some form of access to a FW switch. Wake up is allowed on absolutely any CAN message on bus, and is expected to wake up.

This makes it pretty easy to implement.

**Comment by mck1117** [comment]
Please confirm:
- BCM always commands turn-off
- Presence of a single CAN frame indicate wake-up

yes?

**Comment by NMSTEC** [comment]
Yes to both. Hence why in the other ticket proteus transmitting that packets angers the BCM.

**Comment by NMSTEC** [comment]
> @mck1117 @NMSTEC do I read it right that we would need a CAN shutoff to work together with CAN wake-up? i.e. we need to make sure that we wake up during overall shutdown procedure, i.e. once we decide to suspend ECU we would need to stay alive for some time while making sure that we are CAN silent?

Prefer to handle that in LUA, depending on whatever new un-reverse engineered scenario I discover. 
Let LUA control shutdown, and FW wake up on any packet.

**Comment by mck1117** [comment]
Yeah, so all we need is:
- Lua engine stop (already have this)
- Lua ECU-sleep-mode
- Hardware (probably no software) to wake ECU from CAN traffic

**Comment by NMSTEC** [comment]
It doesn't have to go into the deepest of sleeps either, 15-25ma is an acceptable power draw.

**Comment by NMSTEC** [comment]
Bike overall in sleep state draws 60ma. Majority of it being the BCM and the IMU (Motion sensor). Quite normal for cars too. Mazda/fords of the early 2005-2012s ate about 130ma. That being a defect though, the BCM consumed all of that basically.

Lower current is always better, however I am talking about just in case scenarios.

**Comment by rusefillc** [comment]
@mck1117 says "just use RX pin as a wakeup pin" - that would mean at least wiring wakeup pin somewhere, @NMSTEC would have to solder a hair wire @NMSTEC can you solder a hair wire on your proteus once we have more details? :)

Still open question what SW change to park stm32 how

**Comment by mck1117** [comment]
No - you don't need an extra wire.  AFAIK you can configure the STM32 to wake up on an EXTI line, so you configure the CAN RX pin as EXTI so it wakes the STM32 when traffic happens.

**Comment by mck1117** [comment]
@NMSTEC can you set a "target" and "absolute maximum" power draw?

**Comment by NMSTEC** [comment]
> @mck1117 says "just use RX pin as a wakeup pin" - that would mean at least wiring wakeup pin somewhere, @NMSTEC would have to solder a hair wire @NMSTEC can you solder a hair wire on your proteus once we have more details? :)
> 
> Still open question what SW change to park stm32 how

Generally speaking databus input pins are exclusively all interrupt pins. All that's required is setting that pin as an interrupt in FW. 



> @NMSTEC can you set a "target" and "absolute maximum" power draw?

Target sub 5mA, Max 25mA.

**Comment by mck1117** [comment]
![image](https://user-images.githubusercontent.com/568254/144784477-39afc8af-938f-4528-bb07-c2a639552d05.png)

Standby mode draws very little:

![image](https://user-images.githubusercontent.com/568254/144784577-65d72561-48b6-44f3-80e2-3b40dab25d4f.png)

**Comment by mck1117** [comment]
So standby mode does indeed need the WKUP pin wired - but we can test on a nucleo/discovery board.  They have jumpers you can remove to measure supply current on the CPU supply rail.

**Comment by mck1117** [comment]
![image](https://user-images.githubusercontent.com/568254/144824636-7cb8bc1c-eded-4d29-97f7-fbd67bc0a7c1.png)

**Comment by rusefillc** [comment]
@NMSTEC @mck1117 what's the plan? @NMSTEC says he has to cut a trace used by PPS2 on his Proteus for real test? what about MAX9924 how is that relevant how do we want to address it? I guess vr_descrete anyway

which LED is mentioned why and how?

why is CAN mentioned on the report? what is the CAN plan?

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi/wiki/Lua-Scripting#mcu_stop added

**Comment by rusefillc** [comment]
@mck1117 @NMSTEC do you guys have a plan on what to cut on Proteus how?

**Comment by rusefillc** [comment]
E65 BMW and #1731 are both saying 'hi'

**Comment by rusefillc** [comment]
#3720 created

**Comment by rusefillc** [comment]
https://github.com/andreika-git/hellen-one/issues/125 created

**Comment by rusefillc** [comment]
Alex mentions TJA1054

**Comment by rusefillc** [comment]
MC33742PEPR2
https://www.rocelec.com/part/FREMC33742PEPR2
![image](https://user-images.githubusercontent.com/48498823/147802368-6f08edb5-febd-4dc9-80c8-9a0ab59ec421.png)

**Comment by rusefillc** [comment]
also there is the whole https://www.mouser.com/new/nxp-semiconductors/freescale-mc3490x-power-management/

**Comment by rusefillc** [comment]
https://www.can-cia.org/fileadmin/resources/documents/proceedings/2017_hell.pdf

![image](https://user-images.githubusercontent.com/48498823/147855643-1932f0af-01df-4c37-83b8-a83de5c1c044.png)

**Comment by rusefillc** [comment]
Alphax 2chan has van wake up working
