### ISSUE TITLE
proteus Official well known idle stepper via H-bridges configuration

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3661]
As means to document stepper via H-bridges configuration in my opinion we shall add canned tune for that.

Maybe a new approach: a button to reset only relevant configuration, not full configuration like engine type does?

**Comment by Krakert** [comment]
@mck1117 Did you manage to look into this? I tried multiple things but with no success so far.
[forum post](https://rusefi.com/forum/viewtopic.php?f=18&t=2234l)

**Comment by rusefillc** [comment]
gm_sbc.cpp has this
