### ISSUE TITLE
Pause CAN broadcast on engine stop

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3665]
Mark says that rusEFI CAN broadcast which is probably related to WBO control is keeping vehicle alive on engine stop

We need some way to stop WBO broadcast

Is 501 a relevant message?

**Comment by NMSTEC** [comment]
Transmission of any data on Vehicle bus, wakes up BCM, and forces it to send GO SLEEP signal constantly with address 0x501 Packet 0x00.
In this specific case, 0ef50000 is the address in question. 

My recommendation is some sort of switch in FW that I can trip in LUA to enable and disable native can broadcast. I have already implemented a sort of graceful shutdown in LUA.

**Comment by mck1117** [comment]
I don't think you want it on engine stop - you want it when the ignition is off.

**Comment by rusefillc** [comment]
@mck1117 it sounds like we just need _some_ mechanism and lua hook to begin with?

Shall I simply add enableBroadcast() lua hook?

**Comment by mck1117** [comment]
I would prefer `enableCanTx(bool)` that enables/disables _all_ CAN transmission

**Comment by NMSTEC** [comment]
I'd request just all proteus side can to stop talking, lua controlled. I'd
like to keep full can control somewhere where I can easily access it

**Comment by rusefillc** [comment]
@NMSTEC I am not sure what you are calling. Also we will absolutely not implement proteus-specific logic. For firmware issues it's all rusEFI.

**Comment by NMSTEC** [comment]
Sorry, typing on phone while doing renovations. No, I am asking for a
switch that is accessed by lua to turn off and on rusefi broadcast, via
lua.

**Comment by rusefillc** [comment]
@NMSTEC please elaborate why do you ask not the same what @mck1117 is asking

github comments are not slack. Please consider not using it while distracted while on the phone unless it's worth poking all subscribers via email?

**Comment by mck1117** [comment]
he's asking for the same thing I did

**Comment by rusefillc** [comment]
``enableCanTx(isEnabled)`` added
enabled by default

use enableCanTx(false) to supress CAN TX
