### ISSUE TITLE
FSIO: need to hide RPN under the hook

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#369]
https://en.wikipedia.org/wiki/Reverse_Polish_notation is just the implementation, humans need to be working with human-readable expressions

eval & set_fsio_expression commands should take human-readable infix expressions

**Comment by rusefi** [comment]
See also http://rusefi.com/wiki/index.php?title=Manual:Flexible_Logic

**Comment by rusefi** [comment]
See also http://rusefi.com/forum/viewtopic.php?f=15&t=1233&p=26398#p26398 for some great ideas in Russian

**Comment by mck1117** [comment]
goodbye fsio
