### ISSUE TITLE
V-Twin - Per bank Timing table

### ISSUE THREAD

**Issue by NMSTEC** [rusefi/rusefi#3702]
V-Twin engine is not symmetrical with front and rear engines having very different cooling. Because of that we would need front and rear banks to run completely independent timing maps.

We can keep the same axis points.

I want additional Timing table for second bank in addition to current timing table. 

Blah blah blah:
Vtwins. Rear cyl runs way hotter than front. Needs separate tables for Front and Rear cyls. This will also to apply to V4 bikes (Aprillia).

**Comment by rusefillc** [comment]
it looks like @NMSTEC prefers completely independent separate timing maps but at the moment @mck1117 suggest that we go with 6x6 per-bank or per-cylinder trimming/adjustment map

**Comment by NMSTEC** [comment]
After much deliberation we have agreed trim would be enough for our specific case.

**Comment by mck1117** [comment]
this is fixed with cylinder ignition trim
