### ISSUE TITLE
V-Twin - Additional VE map 

### ISSUE THREAD

**Issue by NMSTEC** [rusefi/rusefi#3703]
V-Twin engine is not symmetrical with front and rear engines having very different cooling. Because of that we would need front and rear banks to run completely independent fuel maps.

We can use the same Axis Values between both maps

Blah blah: As mentioned on #3702 rear cylinders run on different fuel level/VE from the front due to temp differences.

**Comment by mck1117** [comment]
like #3702 we don't need per-cylinder maps, we can use a cylinder trim table per cylinder

**Comment by mck1117** [comment]
possible dupe #3284

**Comment by mck1117** [comment]
this is fixed with per-cylinder trim tables, as in #3284
