### ISSUE TITLE
Map3D needs some changes to allow autoscale RPM bin

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3707]
See https://github.com/rusefi/rusefi/commit/76088f686fa9df26ac69da103275a211c15de506

looks like Map3D is not ready for one of axis being autoscaled? what about just table being autoscaled and not axis?

to clarify - I am less excited about one-byte RPM at the moment and mostly focused on having the actual table autoscaled, either way it looks like Map3D is not fully compatible with mult+div autoscale?

**Comment by rusefillc** [comment]
@racer-coder any chance you could help?

**Comment by mck1117** [comment]
it doesn't support axis being scaled with a divisor other than 1

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi/commit/6b91bacd594e3725b5ab32b89abb7b136cb2ea13 @mck1117 @racer-coder do we still need to take care of that one?

**Comment by mck1117** [comment]
I can do that, yes.
