### ISSUE TITLE
Miata triggers review

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/rusefi#3717]
Problem- Miatas suck to crank up and no level of tuning seems to really help.  Ive personally spent days trying to get cars to crank reliably.  

Miata triggers seem to struggle during cranking.  I personally see a trigger error every time i go to start. @zhoob2004 also sees this issue.  This is something i see from both NA CAS and NB stock crank/cam triggers.  Below is a link to a log from @zhoob2004 on the 96 with proteus.  I will be updating with logs from nb1 in the coming days.  

To note, by changing from stock NB triggers to 36-1 crank trigger, the problem is resolved.  My thoughts are we are missing something on the triggers OR the 36-1 hides terrible cranking tuning.  

https://rusefi.com/online/view.php?log=515

**Comment by mck1117** [comment]
@zhoob2004 or @BeerMoneyMotorsports - can you try with these gap override settings?  These are derived from data in Zach's log (515).

![image](https://user-images.githubusercontent.com/568254/147287147-939f0b6c-553e-4cfb-a924-2288acd05f9d.png)

**Comment by BeerMoneyMotorsports** [comment]
@mck1117 nb1 recording.  4 starts.  3rd was no start while 4th fired right up.  they were sequential attempts. no time between.

https://rusefi.com/online/view.php?log=517

**Comment by rusefillc** [comment]
@BeerMoneyMotorsports do you have  logic analyzer?

**Comment by mck1117** [comment]
We've been chatting on slack, probably don't need a logic analyzer with the recently improved log fields

**Comment by BeerMoneyMotorsports** [comment]
@rusefillc i do, i can implement it however directed.

**Comment by mck1117** [comment]
Let's use this issue for NA, and #3721 for NB

**Comment by mck1117** [comment]
@Zhoob2004 and @BeerMoneyMotorsports will report back here once they've tried those adjusted sync settings for NA

**Comment by BeerMoneyMotorsports** [comment]
lemon with latest snapshot and no modification to tune.  76f ambient cold start.

https://rusefi.com/online/view.php?log=529

**Comment by BeerMoneyMotorsports** [comment]
log with trigger gap override settings

https://rusefi.com/online/view.php?log=530

![image](https://user-images.githubusercontent.com/82395131/147859519-85c06697-dfe0-4423-8178-ca8b8c936034.png)

**Comment by BeerMoneyMotorsports** [comment]
These settings work fantastic.  Solid improvement. Consistent and fast startup.

**Please keep ticket open for further cold weather tests**

![image](https://user-images.githubusercontent.com/82395131/147862237-570f3dd7-94b1-4945-a5c6-15b935443db8.png)

**Comment by BeerMoneyMotorsports** [comment]
near freezing start.  did not catch first try

https://rusefi.com/online/view.php?log=542

**Comment by BeerMoneyMotorsports** [comment]
@mck1117 the new settings seem to have done great.  i think this ticket can be closed now?

**Comment by mck1117** [comment]
Sure, if we're happy with NA sync, I'm happy to close.
