### ISSUE TITLE
stm32_stop just reboots stm32f4discovery

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3720]
stm32f407 discovery see also https://github.com/rusefi/rusefi/wiki/Dev-Quick-Start

need to fix/implement MCU stop with wake-up on pin PA0 or any other pin of your choice. Method will be
invoked via existing USB serial port connectivity, frontend application to send commands already exists.

current non working "stm32_stop" method at https://github.com/rusefi/rusefi/blob/master/firmware/hw_layer/ports/stm32/stm32f4/mpu_util.cpp

work would need to be summitted as github pull request

bin/send_command "stm32_stop"

stm32f4discovery with fresh firmware
PA0 jumper wire to GND, no other wires
mini USB, micro USB

send stm32_stop via console

expected: some sort of stop
actual result: firmware reboots

**Comment by rusefillc** [comment]
@NMSTEC do you have an stm32f407 discovery board?

**Comment by NMSTEC** [comment]
I do not. Will order from the link you sent, and will fuck with proteus upon my return.

**Comment by rusefillc** [comment]
@NMSTEC report same or similar on Proteus F7 with some hw mod

**Comment by NMSTEC** [comment]
STM32F7 on proteus. Cut PA0 trace, soldered on jumper to RX pin of CAN. Can is not active at this time, and running on bench from USB only. stm32_stop forces reboot. Cut jumper, leaving PA0 hanging in the air, problem remains.

**Comment by rusefillc** [comment]
maybe relevant:
```
The important part is to always clear the wakeup flag (via PWR_CR_CWUF_Msk) in the PWR->CR register. Otherwise the device will immediately wake up after attempting to enter the stop mode.
```

**Comment by NMSTEC** [comment]
Resolved: https://github.com/rusefi/rusefi/pull/3783

**Comment by mck1117** [comment]
dddddone!
