### ISSUE TITLE
NB1/NB2 triggers review

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#3721]
Breaking off NB1/2 as its own issue, as it's a different decoder to NA.  #3717 

@BeerMoneyMotorsports says nb1 recording. 4 starts. 3rd was no start while 4th fired right up. they were sequential attempts. no time between.

https://rusefi.com/online/view.php?log=517

**Comment by mck1117** [comment]
In that log:

- Crank looks great.  We sync it no problem.
- VVT makes a bunch of garbage right at the start of cranking, what's up with that?

![image](https://user-images.githubusercontent.com/568254/147441990-25cca91b-bfb4-48a3-9213-3fd870ceccec.png)

That mess of a blob was a total of 33 VVT edges in 0.32 second.

**Comment by mck1117** [comment]
Third attempt in that log is an even worse disaster:

![image](https://user-images.githubusercontent.com/568254/147444392-a46d0e8b-fcb7-4d22-94ef-a6e46be68a2d.png)

**Comment by mck1117** [comment]
And the 4th attempt is perfect!?

![image](https://user-images.githubusercontent.com/568254/147444432-37939e4f-b21e-4573-a481-57764fc1a0a6.png)

**Comment by BeerMoneyMotorsports** [comment]
log of second NB1.  had some oddities of rpm spike.

https://rusefi.com/online/view.php?log=518

**Comment by rusefillc** [comment]
so you need three points to connect logic analyzer

GND - we usually have it on proto area
for CAM/CRANK the simplest option could be to solder little wire stubs at the back side of the PCB right to relevant ECU connector pins

0.5M is good enough rate for our purposes while saving logic analyzer trace. Please IM if I can help with logic analyzer UI.

**Comment by BeerMoneyMotorsports** [comment]
Second NB1 updated firmware.  
![image](https://user-images.githubusercontent.com/82395131/147510995-6a7973e9-a4f7-4788-9033-e1cb5a7d21bc.png)

https://rusefi.com/online/view.php?log=519

**Comment by BeerMoneyMotorsports** [comment]
> so you need three points to connect logic analyzer
> 
> GND - we usually have it on proto area for CAM/CRANK the simplest option could be to solder little wire stubs at the back side of the PCB right to relevant ECU connector pins
> 
> 0.5M is good enough rate for our purposes while saving logic analyzer trace. Please IM if I can help with logic analyzer UI.

i will rig one up for testing tomorrow.  thank you.  i have used it previously on an mre but it has been a while

**Comment by BeerMoneyMotorsports** [comment]
1st NB1 updated log.  no start on first few attempts.  only started on last attempt.

https://rusefi.com/online/view.php?log=520

**Comment by mck1117** [comment]
520 has the same mess as previous logs above, maybe a bad sensor??

**Comment by BeerMoneyMotorsports** [comment]
logs

1st NB(orange car)
517 & 520

2nd NB(silver car)
518 & 519

**Comment by BeerMoneyMotorsports** [comment]
Lets ignore 1st NB logs for this ticket as it has problems.  Use only 2nd NB logs

**Comment by BeerMoneyMotorsports** [comment]
nb triggers have been much improved.  this is ok to close.
