### ISSUE TITLE
HellenNA8_96 config folder

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/rusefi#3724]
@rusefillc could you assist me by creating the files needed for the HellenNA8_96?  Then i can get started writing the yaml.  

https://github.com/rusefi/rusefi/tree/master/firmware/config/boards/hellen

**Comment by rusefillc** [comment]
@BeerMoneyMotorsports I've just added empty main.yaml file

**Comment by rusefillc** [comment]
@andreika-git what shall we do about other firmware files? which board is closes I can at least copy-paste files from another folder?

**Comment by BeerMoneyMotorsports** [comment]
@rusefillc this board is basically the same exact thing as the NB1.  same chip and modules.  main difference is pinout changes.

**Comment by BeerMoneyMotorsports** [comment]
> @BeerMoneyMotorsports I've just added empty main.yaml file

thank you!

**Comment by BeerMoneyMotorsports** [comment]
Closing, files created and firmware tested successfully.
