### ISSUE TITLE
MRE hangs up on start

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3738]
Passat MRE is a fragile state: it would hang on start (meaning no blue LED blinking and no USB connectivity)

only with GDI board connected and only when started with +12v

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/148000998-c125a256-574a-4537-9a8a-afd0ab4df89a.png)

**Comment by mck1117** [comment]
Surely that doesn't lock up the ecu. A pin conflict doesn't explain why it locks up ONLY under those conditions.

**Comment by rusefillc** [comment]
actual pin content makes me thing that I have a bad binary mixing discovery and MRE configurations, closing issue

worked once I took official build server binaries
