### ISSUE TITLE
GHA execution throttling

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3739]
In order to cut the pipeline let's execute some jobs less often than always

**Comment by rusefillc** [comment]
@chuckwagoncomputing I've failed to implement this :( Any chance you would be interest in this approach to GHA performance?

**Comment by chuckwagoncomputing** [comment]
This issue isn't actionable as-is. Please clarify how it should be determined whether a job should be run. Coin toss? Phase of the moon? Only on Tuesdays? The color of the Queen's hat?

**Comment by rusefillc** [comment]
@chuckwagoncomputing my bad

see https://github.com/rusefi/rusefi/commit/0c22c9ffb3aee4494a9221537b984bc3419f320e which is part of master now. it shows skip-rate values and execution-throttle.sh tool which is currently unused in master.

**Comment by rusefillc** [comment]
@chuckwagoncomputing does it look like we currently skip at all?

**Comment by chuckwagoncomputing** [comment]
Looks like it's working to me. Here is an example: https://github.com/rusefi/rusefi/runs/5998787781?check_suite_focus=true

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/163583609-0560adf0-fbcd-414a-8801-6b4148fc30e1.png)
