### ISSUE TITLE
Solenoid Clicking after data burn

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/rusefi#3763]
While working on NB1, i have noticed the EGR boost solenoid starts clicking after doing a Burn.  This is very audible but does not see to cause performance issues.  It is output for INJ 6 per the schematics.  It controls ecu pins 4C and 3T.  

4D/3T are tied together as either can be used to control a boost controller.  Boost control isnt turned on in this tune, however the pin is selected in the menu.  

The solenoid will remain clicking until a full power cycle is done(ign and usb).  

Tune is https://rusefi.com/online/view.php?msq=813
Signature: rusEFI 2021.12.31.hellen-nb1.45104247

**Comment by BeerMoneyMotorsports** [comment]
log https://rusefi.com/online/view.php?log=563

**Comment by mck1117** [comment]
What kind of frequency?

Is this the pin set to boost control, but boost control is disabled?

**Comment by BeerMoneyMotorsports** [comment]
i dont know exact frequency.  It clicks relatively fast.  

Correct, pin is set to boost control but it is not enabled.

**Comment by mck1117** [comment]
not necessary, I know what's happening

**Comment by mck1117** [comment]
@BeerMoneyMotorsports did this get fixed?

**Comment by BeerMoneyMotorsports** [comment]
I have confirmed that i no longer have clicking with latest firmware

**Comment by mck1117** [comment]
Great, will close then!
