### ISSUE TITLE
F7 ST bug work-around

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3775]
We can workaround #3566 on our end

**Comment by mck1117** [comment]
I think adding an erase of sector 12 prior to the normal flash operation should work.

**Comment by rusefillc** [comment]
``STM32_Programmer_CLI.exe -c port=usb1 -e 12``
sector 12 message does not look right but maybe it's just the message
![image](https://user-images.githubusercontent.com/48498823/149699767-b32dab7f-f282-4dad-aa5a-bbf5652857bd.png)

``STM32_Programmer_CLI.exe -c port=usb1 -e 8``
sector 8 looks message looks nice but we know it's not getting the job done
![image](https://user-images.githubusercontent.com/48498823/149699845-9c90712b-f326-49ad-9b39-f5ab5598207e.png)

**Comment by rusefillc** [comment]
still verification error with both sectors 8 and 12 erased

![image](https://user-images.githubusercontent.com/48498823/149700384-03359dbd-f131-4b4a-a3fb-a8794f940ccd.png)

**Comment by rusefillc** [comment]
@mck1117 it look to me like I am unable to erase the sector we need to erase. See screenshots.

**Comment by mck1117** [comment]
If I run `.\STM32_Programmer_CLI\bin\STM32_Programmer_CLI.exe -c port=usb1 -e [0 19]`, it says:

```
USB speed   : Full Speed (12MBit/s)
Manuf. ID   : STMicroelectronics
Product ID  : STM32  BOOTLOADER
SN          : 3057365D3438
FW version  : 0x011a
Board       : --
Device ID   : 0x0451
Device name : STM32F76x/STM32F77x
Flash size  : 2 MBytes (default)
Device type : MCU
Revision ID : --
Device CPU  : Cortex-M7

Erase sector(s) ...

erasing sector 0000 @: 0x08000000 done
erasing sector 0001 @: 0x08004000 done
erasing sector 0002 @: 0x08008000 done
erasing sector 0003 @: 0x0800c000 done
erasing sector 0004 @: 0x08010000 done
erasing sector 0005 @: 0x08020000 done
erasing sector 0006 @: 0x08040000 done
erasing sector 0007 @: 0x08060000 done
erasing sector 0008 @: 0x08080000 done
erasing sector 0009 @: 0x08084000 done
erasing sector 0010 @: 0x08088000 done
erasing sector 0011 @: 0x0808c000 done
erasing sector 0012 @: 0x08090000 done
erasing sector 0013 @: 0x080a0000 done
erasing sector 0014 @: 0x080c0000 done
erasing sector 0015 @: 0x080e0000 done
sector 0016 does not exist
sector 0017 does not exist
sector 0018 does not exist
sector 0019 does not exist
Flash page/sector erase command correctly executed.
Note: if flash sector is protected, it will not be erased.
```

But it has still not erased the content at 0x08080000!

(I filled the flash with 0xAA so I can see what's erased)

![image](https://user-images.githubusercontent.com/568254/150873162-0b5db1c6-312a-4588-8516-fdab954b3a93.png)

**Comment by mck1117** [comment]
sure

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/182998390-74b24170-12e7-4646-bded-9b3a5b4fa73d.png)

but 0x08080000 still not erased

![image](https://user-images.githubusercontent.com/48498823/182998555-7105362b-3fd7-4888-9536-e05ea37c1ae8.png)

**Comment by rusefillc** [comment]
@mck1117 @nmschulte I wonder if a special custom version of https://github.com/rusefi/rusefi/blob/master/misc/install/STM32_Programmer_CLI/Data_Base/STM32_Prog_DB_0x451.xml would convince the tool of proper sector location

**Comment by nmschulte** [comment]
I think that might work well actually, but I don't use these tools.
