### ISSUE TITLE
Flex Fuel epic

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#3776]
Tracking sub-issues for flex fuel stuff.

**Comment by mck1117** [comment]
Cranking fuel #3777

**Comment by mck1117** [comment]
Separate E timing table #3778

**Comment by BeerMoneyMotorsports** [comment]
Boost tables per ethanol level?  Maybe that is more select-a-tune request?

**Comment by BeerMoneyMotorsports** [comment]
[alan_500hp.zip](https://github.com/rusefi/rusefi/files/7851546/alan_500hp.zip)
here is the 495whp flex ms3 tune

**Comment by mck1117** [comment]
> Boost tables per ethanol level? Maybe that is more select-a-tune request?

seems like more general select-a-tune need, not a flex need

**Comment by BeerMoneyMotorsports** [comment]
it is more general and not flex only.  HOWEVER, i think flex is not complete without it.
