### ISSUE TITLE
Gear detection based on RPM to VSS ratio

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3779]
For stuff like #3007 do we need to figure out current gear based on RPM and VSS?

**Comment by rusefillc** [comment]
@BeerMoneyMotorsports @blundar how are other ECUs detecting gear? any examples of relevant user facing settings?

**Comment by BeerMoneyMotorsports** [comment]
I have 94-05 that “should “ have a vss input from cluster. I am in a position to confirm that signal in the next few days. I will log it and provide confirmation on my end.

**Comment by mck1117** [comment]
I can wire a VSS from a front wheel on my Volvo if that helps (eventually)

**Comment by NMSTEC** [comment]
Drive car at constant RPM in each gear, write down VSS.

RPM/VSS = Ratio ±5% error margin

For VSS calculation, XLS sheet attached.
[gearRatioCalc_DD.xls](https://github.com/rusefi/rusefi/files/7853418/gearRatioCalc_DD.xls)

**Comment by BeerMoneyMotorsports** [comment]
screenshot of another ecu that uses TS for general information.

![image](https://user-images.githubusercontent.com/82395131/149155373-484da507-33dc-4f93-84d6-dff5960a0e91.png)

**Comment by rusefillc** [comment]
@BeerMoneyMotorsports please help me see gear detection setting example, not boost control which uses detected gear

At the moment we are trying to have working gear gauge

**Comment by BeerMoneyMotorsports** [comment]
here you go
![image](https://user-images.githubusercontent.com/82395131/149156425-56e5ba92-2e1b-4dd7-bdda-3ec848d65506.png)

**Comment by rusefillc** [comment]
@BeerMoneyMotorsports what other options do they offer?

![image](https://user-images.githubusercontent.com/48498823/149439879-3df9455d-1b84-4427-822c-21b8c85df00e.png)

**Comment by mck1117** [comment]
it may be for analog/digital sensors that detect the shifter position

**Comment by BeerMoneyMotorsports** [comment]
<img width="230" alt="image" src="https://user-images.githubusercontent.com/82395131/149442087-3eb39107-9638-4d7e-b54f-85ceb2ec8d80.png">

**Comment by rusefillc** [comment]
@BeerMoneyMotorsports @NMSTEC I can use help here so that I do not have to think. Need the formula to connect vehicle speed and gear ration


kilometers per hour * 1000  / 60 gives us meters per minute

meters per minute we divide by (2 * Pi * wheel diameter) to get wheel revolutions per minute

wheel revolutions per minute we divide or multiply by final drive ratio to get drivershaft revolutions per minute?

once we have  drivershaft revolutions per minute do we divide by engine PRM to get current transmission gear ratio?

**Comment by NMSTEC** [comment]
Engine to WS: https://x-engineer.org/calculate-wheel-vehicle-speed-engine-speed/

In short
WS= (Circumference of tire *Eng RPM) / (Gear ratio * Final drive ratio)

**Comment by mck1117** [comment]
driveshaft = wheel RPM * axle ratio (driveshaft spins faster than axle)
gearbox ratio = engine / driveshaft (engine spins faster than driveshaft)

**Comment by rusefillc** [comment]
@BeerMoneyMotorsports  please test latest firmware

We are looking at "gearbox ratio"

you would need to configure two new settings at "Speed sensor config" dialog - finalGearRatio and wheelDiameter

**Comment by NMSTEC** [comment]
Fun story, if harley going on dyno monday, I too can test it. This model has physical gearbox VSS, & I can try using RPMs as well.

**Comment by BeerMoneyMotorsports** [comment]
First up is that final gear ratio will not accept the input ratio.  should be 4.3 but it reverts to 4.  

To note, final gear ratio is technically repetitive and was covered under speed sensor gear ratio.  

Is parameter for wheel diameter needed if we know revolutions per kilometer already?

FYI- I tested the old configuration yesterday and confirmed functionality on NB1.  

![image](https://user-images.githubusercontent.com/82395131/149635407-e19f8f36-7380-4b6c-9bff-aa03dd59091b.png)

**Comment by BeerMoneyMotorsports** [comment]
amending my last update, both final gear ratio and wheel diameter only want to accept whole numbers.

tune-  https://rusefi.com/online/view.php?msq=825
log- [vss.zip](https://github.com/rusefi/rusefi/files/7875990/vss.zip)

**Comment by rusefillc** [comment]
@BeerMoneyMotorsports just made the following fixes
1)  final gear ratio and wheel diameter should now accept two digits after period
2) log entry name changed from s2rpm to Gauge Ratio

At the moment your vss.zip has something very weird in s2rpm maybe due to bad tune, let's try again once we have less crazy numbers un tune once we can enter those via TS

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi/issues/3792 created to track one potential setting duplicate

**Comment by rusefillc** [comment]
#3793 created to track another potential setting duplicate

**Comment by BeerMoneyMotorsports** [comment]
Ill attempt to test tomorrow but there is supposed to be snow

**Comment by BeerMoneyMotorsports** [comment]
snow/ice delays

**Comment by NMSTEC** [comment]
Harley going on Dyno today. Will be doing the VSS fuckery today. Forgot to figure out the VSS CAN byte.

**Comment by rusefillc** [comment]
https://rusefi.com/online/view.php?log=603

![image](https://user-images.githubusercontent.com/48498823/151095863-8e14e5d7-ea5c-431e-97e3-0ccd19e18a1c.png)

**Comment by rusefillc** [comment]
huh?

![image](https://user-images.githubusercontent.com/48498823/151095925-bf963bbe-9b39-4b16-85e6-bde7ddf3713d.png)

**Comment by mck1117** [comment]
That's a downshift on the dyno, look at VSS at the same time, there's some jerky noise there. Potentially noise, potentially also actual jerk from the dyno.

Look how fuzzy VSS is in general:

![image](https://user-images.githubusercontent.com/568254/151096278-071ef632-3eaf-43ad-bd5e-cd3261293a02.png)

**Comment by BeerMoneyMotorsports** [comment]
quick run through a couple gears.  https://rusefi.com/online/view.php?log=615 
little longer drive with lots of gear changes.  https://rusefi.com/online/view.php?log=614

**Comment by rusefillc** [comment]
just merged #3839 we would need to try it again once #3839 builds sorry my bad should have merged earlier

**Comment by BeerMoneyMotorsports** [comment]
https://rusefi.com/online/view.php?log=626

**Comment by rusefillc** [comment]
@mck1117 do we need different filtering parameters or else?

![image](https://user-images.githubusercontent.com/48498823/151723497-3e25fdc8-3282-40d5-9e64-c54c4ba922ae.png)

**Comment by mck1117** [comment]
Huh? That log looks like clutch slip to me.

**Comment by rusefillc** [comment]
@ElDominio can you please help with logs of gear detection which we apparantly have?

**Comment by ElDominio** [comment]
Will test on tuesday using Lancer

**Comment by rusefillc** [comment]
@ElDominio Tuesday?

**Comment by ElDominio** [comment]
Tuesday from hell, the lancer is collecting dust, this should be easy but i am very lazy, I will eat a raw pinch of salt if I don't test this week

**Comment by ElDominio** [comment]
> Tuesday from hell, the lancer is collecting dust, this should be easy but i am very lazy, I will eat a raw pinch of salt if I don't test this week

Today I tried to test on Raymond car, but I am trying to interpret VSS to feed to Gear logic. This is another comment to remind myself since it won't be finished today

**Comment by ElDominio** [comment]
I got a log, it's gigantic.

[2022-12-06_19.56.42.mlg.zip](https://github.com/rusefi/rusefi/files/10171691/2022-12-06_19.56.42.mlg.zip)

The gear detection algorithm is confusing at least.

In basically everything I have used, all you do is make sure VSS reads correctly (calibrate VSS input to match speedo), then use VSS/RPM to determine gear (ECU saves how many revs are needed per mile for each gear, example: in first you can do 5mph/1000RPM, second 10mph/1000rpm... continues in picture)

![image](https://user-images.githubusercontent.com/5685108/206058586-144d7c21-2da7-486f-a21b-d05dc4a013e0.png)

**Comment by mi-hol** [comment]
Just an example how other app handles this
![image](https://user-images.githubusercontent.com/22799428/218723867-6d8afb5a-1fcf-40e3-852a-74988489728a.png)

**Comment by rusefillc** [comment]
@ElDominio you are talking about improvements meaning you want to give me more work.

@ElDominio can we try a different approach? Would it be possible to get the current approach working first or is it totally unuseable?

**Comment by ElDominio** [comment]
If we need to make this work, it needs to bw quite thoroughly explained. Understanding RPM/VSS is much easier

**Comment by rusefillc** [comment]
@ElDominio please clarify

Do _you_ understand it enough to test or do _you_ need clarification?

@nmschulte @mck1117 @chuckwagoncomputing any volunteers?

**Comment by mck1117** [comment]
@rusefillc you mentioned on fb some testing was needed.  I see perfectly functional gear detection both in unit tests and in real logs. What specific gap do you see?

**Comment by rusefillc** [comment]
I have no resources to evaluate the data we have. If you declare gear detection working next step is documentation/case study/making it useable by @ElDominio ?

**Comment by ElDominio** [comment]
![image](https://user-images.githubusercontent.com/5685108/225448322-a13db20c-b3d5-4c7d-adaa-45ce6b3b5773.png)

Making it RPM vs VSS means we can use two pieces of data we already have, and assign a gear ratio to a gear.
I have prepared a spreadsheet explaining how it works. Please give it a look and feel free to comment
https://docs.google.com/spreadsheets/d/1x_v_taJ1OlW-1g6ioTMzR4uZp7twSlSOJcYXJrD6n4k/edit?usp=sharing

**Comment by mck1117** [comment]
> I have prepared a spreadsheet explaining how it works.

Yeah, I know how it would work.

We do it that way because we need tire diameter/sensor params/gear ratio to make the regular VSS work. All of rusEFI tries to base the configuration on "real" numbers from first principles, not on magic fudge factors that you set with trial-by-error.  The real numbers are gear ratios and tire size.

**Comment by rusefillc** [comment]
Both sides have a point

What if we set final drive ratio to 1 and wheel revolutions to 1000 would it allow the fudging approach via proper UI?

**Comment by rusefillc** [comment]
@ElDominio does https://github.com/rusefi/rusefi/commit/6f7523fbef404e4eb404a71d0e6746a5acdafff9 help?

**Comment by ElDominio** [comment]
> > I have prepared a spreadsheet explaining how it works.
> 
> Yeah, I know how it would work.
> 
> We do it that way because we need tire diameter/sensor params/gear ratio to make the regular VSS work. All of rusEFI tries to base the configuration on "real" numbers from first principles, not on magic fudge factors that you set with trial-by-error. The real numbers are gear ratios and tire size.

My deal here is, knowing gear ratios depends on Google in basically all cases. Tire diameter is extremely inconsistent in an island where every single car has different wheel/tire combos and I can't have measuring tape to measure each individual car.  
This is the method I have used in both LinkECU and Haltech, which I know doesn't make it the correct one, but it seems to work well enough for pretty much every car I have come accross with.

The other question is, if I am required to use the current method, who explains how it works except telling me "get the numbers from the service manual)
___________________________________
Is setting ignition timing not trial-by error? Why can't VSS be like this?

**Comment by mck1117** [comment]
@ElDominio you can set the final drive ratio to 1.0 or something, then look at this gauge (transmission section) to determine what the ratio should be in each gear

![image](https://user-images.githubusercontent.com/568254/225521763-30168cb7-4ebd-44c2-87f1-6b5ef1e4adde.png)

**Comment by nmschulte** [comment]
I can't comment beyond that, naively, for my setup, I have determined the correct ratios and metrics for my purposes.  Here is a spreadsheet I use to compare my options, in case it helps anyone:
https://docs.google.com/spreadsheets/d/19XC9ctJKfD9I_oPKq4FVoLHUMUo3B_5aS0BMMmkeBjE/edit#gid=0

I think I can sympathize with @ElDominio's situation, though I've never been in it.  If nothing else, it might be helpful if rusEFI can aid to determine the ratio, such as @mck1117 suggests.  Personally, knowing the actual ratios is important to me, but perhaps not so much for others.

**Comment by mck1117** [comment]
> Personally, knowing the actual ratios is important to me, but perhaps not so much for others.

it also helps with changing the mechanical parts out: if I change from a 4.10 to 3.73 rear end, I can change exactly one value that maps to that physical part of the car, and not have to re-tune my gear detection.

**Comment by ElDominio** [comment]
Since my use case is mostly street cars, most people don't change out their ratios basically ever.

So, setting the final drive to 1 will spit out useable gear ratios for each gear?

I get wanting to do it with hard data but I get a gamut of cars in the shop, usually not dedicated race cars so changing the ratio is very uncommon. I get why you guys do it this way so if doing the final drive = 1 thing can get the gear detection working, that's a good enough fix for me

**Comment by nmschulte** [comment]
I haven't messed with this part of the system yet, but for my application, there's a lot of assumption about the VSS (mainly, tire size and final drive ratio).  Anyway, assuming you have a trustworthy VSS speed, it seems like rusEFI could add command(s) to the firmware and buttons to Tuner Studio interface to compute the/a gear ratio for a given gear.  Possibly with some cleverness, it could automatically detect them all by shifting deterministically through all of the gears through a suitable range of RPM, when a certain mode is enabled.  This last idea would be more work than individual buttons, and both would be more work than what seems to already function (setting a "fake"/"guessed" final drive ratio and reading the computed gear ratio; see next para.).

@ElDominio, I gather you can use any value for the final drive to "spit out usable gear ratios," but using 1.0 seems sensible if you don't know the actual value.

**Comment by mck1117** [comment]
> @ElDominio, I gather you can use any value for the final drive to "spit out usable gear ratios," but using 1.0 seems sensible if you don't know the actual value.

Yep, you can use whatever values you want for tire circumference and final drive.

This means your workflow stays the same.  For each gear, drive at some constant speed, and record the indicated `Gearbox Ratio` in the field for that gear.

**Comment by rusefillc** [comment]
looks to be working
