### ISSUE TITLE
't' in terminal does not print seconds properly

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3780]
connect to rusEFI unit via terminal
hit 't' button a few times
expected behavior: testCommandCounter increases, seconds show number of seconds since ECU start

actual behavior:
![image](https://user-images.githubusercontent.com/48498823/149061960-69a1a54e-1f7c-48d9-8e72-d92df8f64917.png)

**Comment by rusefillc** [comment]
At first I've suspected that ``getTimeNowSeconds`` is not returning expected int value but TS seems not to be affected

![image](https://user-images.githubusercontent.com/48498823/149062269-fdde889f-030a-468d-a247-6c0288a7cb10.png)

is that some %d issue with 64 value on stack not 32 bit value? sometime else?

**Comment by rusefillc** [comment]
@racer-coder any chance you could look into this random bugreport?

**Comment by mck1117** [comment]
%d can't print a 64-bit
