### ISSUE TITLE
replace speed sensor gear ratio

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3793]
there are many different implementations of vehicle speed sensor - some are CAN, some are tooth on drivestaft side, some are tooth on wheel.

sometimes we need more natural final drive ratio

overall open question which settings are most suited when and what kind of duplication do we have if any

![image](https://user-images.githubusercontent.com/48498823/149639781-124ed340-1ae5-4adf-b78f-6fdd8a917dba.png)

**Comment by mck1117** [comment]
Speed sensor gear ratio may not always be axle ratio: for example, using ABS sensor for speed sense or diff-mounted speed sensor would have speed sensor ratio of 1.0. My setup will have 48t, 1.0 ratio for speed sense, but 3.73 from axle to gearbox output

**Comment by rusefillc** [comment]
Should we replace these two
![image](https://user-images.githubusercontent.com/48498823/149639876-87848a2d-5dae-4b34-ad99-bf563f16dd19.png)

with one "sensos tooth to wheel revolution ratio" and use it along wide wheel diameter?

**Comment by mck1117** [comment]
I much prefer quantities that users can actually measure or inspect without math. I can count my sensor teeth and gear ratio, and type those in and there is zero opportunity for wrong math. It's a great opportunity for us to differentiate ourselves with an easier user experience.

**Comment by rusefillc** [comment]
I like "actually measure or inspect without math"
