### ISSUE TITLE
better solution for board files

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#380]
ST_STM32F4_DISCOVERY board files were modified under https://sourceforge.net/p/rusefi/tickets/293/

We should probably move our custom board files out of chibios folder

**Comment by rusefi** [comment]
![image](https://cloud.githubusercontent.com/assets/7377949/24218844/2f40c8dc-0f1b-11e7-96bb-4cf259522720.png)

@fpoussin FIY :(

**Comment by rusefi** [comment]
http://stackoverflow.com/questions/1405030/using-git-how-can-i-selectively-pull-merge-changes-from-anothers-fork

git remote add fpoussin https://github.com/fpoussin/rusefi.git
git fetch fpoussin
git log fpoussin/chibios-update
git cherry-pick -n 51e9e9dd9f67004e0a5c1ad6ae25ac6106473ef6

**Comment by fpoussin** [comment]
Looks good :) 
I know, git can be rough sometimes...
