### ISSUE TITLE
Better handling of RPM during stop of cranking

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3803]
At the moment failed attempts to start engine produce really confusing noisy log files

There must be a few low hanging fruits to make logs of stop of cranking less confusing

B6 Passat for instance. Note 2 second of 430 RPM logged at the end of cranking attempt

![image](https://user-images.githubusercontent.com/48498823/149855404-455c8aeb-de67-4768-919d-2f27e8602a44.png)

**Comment by rusefillc** [comment]
Relevant magic constants:
NO_RPM_EVENTS_TIMEOUT_SECS

**Comment by mck1117** [comment]
Worst case engine has 1 tooth per crank rev (let's assume we don't care about 1 tooth per cam rev engines, if those exist?).

That means at 100 rpm, that tooth arrives every 0.6 second.  So we can probably reduce `NO_RPM_EVENTS_TIMEOUT_SECS` from 2 to 1, at least.

**Comment by racer-coder** [comment]
Make it trigger dependent?  People with 60-2 shouldn't suffer a poor experience just because others have a crappy trigger setup.

**Comment by rusefillc** [comment]
great minds thinks alike

![image](https://user-images.githubusercontent.com/48498823/149857577-73bf7554-e828-4464-91cd-eb99cce4b04d.png)

**Comment by mck1117** [comment]
> Make it trigger dependent? People with 60-2 shouldn't suffer a poor experience just because others have a crappy trigger setup.

You don't necessarily want it _too_ low, lest it rapidly cycle something on/off at the start/end of cranking

**Comment by rusefillc** [comment]
progress was made!
