### ISSUE TITLE
gcov coverage seems stale

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3805]
https://rusefi.com/docs/ points at https://rusefi.com/docs/unit_tests_coverage/ which says

Date: | 2021-12-04 07:39:23

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi/blob/master/.github/workflows/build-unit-tests.yaml is the job

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/149945555-caee3cc0-cf50-4c36-a2ad-875d305ac13d.png)

**Comment by rusefillc** [comment]
@chuckwagoncomputing I've made at least one fix but docs/unit_tests_coverage does not seem better :( can you please help?

![image](https://user-images.githubusercontent.com/48498823/149952020-fef1db4f-db65-4489-950f-ea015e86fbd4.png)

**Comment by chuckwagoncomputing** [comment]
Doesn't seem like this is fixed yet...

**Comment by rusefillc** [comment]
@chuckwagoncomputing date looks better for me

![image](https://user-images.githubusercontent.com/48498823/150436545-daf450be-28fe-4ed9-bc02-fd92de58dd13.png)

**Comment by rusefillc** [comment]
I vote to close? @chuckwagoncomputing maybe caching issue on your end?

**Comment by chuckwagoncomputing** [comment]
That date/time is just now. Not sure what happened exactly. I _thought_ I reloaded the page on my end.
