### ISSUE TITLE
sporadic HighRevTest testV12

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3806]
GHA has one failure and then recovered

Jenkins had about six failures so far and recovered

BAD
https://github.com/rusefi/rusefi/tree/20220119.daily_tag
https://github.com/rusefi/rusefi/actions/runs/1737600759

BAD
https://github.com/rusefi/rusefi/tree/20220117.2143
https://github.com/rusefi/rusefi/actions/runs/1737678645

looks good
https://github.com/rusefi/rusefi/tree/20220117.2118

GOOD 
https://github.com/rusefi/rusefi/tree/20220118.daily_tag

![image](https://user-images.githubusercontent.com/48498823/149951171-7041b74c-4c5c-4af8-9c20-bb00bcd2e6a7.png)

**Comment by rusefillc** [comment]
before big RPM change

![image](https://user-images.githubusercontent.com/48498823/150475437-15c9e1bc-7f8f-41c6-a2d5-8b79b130214a.png)

**Comment by rusefillc** [comment]
@mck1117 any chance you could have a look?

**Comment by rusefillc** [comment]
Acceptance criteria: 30 consecutive successful builds on Jenkins (at 11 minutes per job on Jenkins that's 7 hours of testing unfortunatelly)

I've disabled master job and will start binary search. Will keep this ticket updated.

**Comment by rusefillc** [comment]
looks like https://github.com/rusefi/rusefi/commit/9f5188bf305a2327f957548759e9606f9b3cccfa is the cause

plan to cache this calculation

**Comment by rusefillc** [comment]
@mck1117 still an issue :( https://github.com/rusefi/rusefi/actions/runs/1743220941

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/151004611-51e748bd-81d5-49b1-93d9-af2395e485d4.png)

**Comment by rusefillc** [comment]
that commit which returns math back to 1 second has helped jenkins

![image](https://user-images.githubusercontent.com/48498823/151068041-ccae3c12-549d-404a-9091-352d6c3ca691.png)

**Comment by mck1117** [comment]
#3838 says we are probably OK
