### ISSUE TITLE
datalog entries naming mess

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#382]
Currently rusEfi produces three types of logs

Each type of logs has it's own name for same field, that's a mess and that would be improved

See https://github.com/rusefi/rusefi/tree/master/firmware/tunerstudio
See https://github.com/rusefi/rusefi/blob/master/java_console/models/src/com/rusefi/core/Sensor.java
See https://github.com/rusefi/rusefi/blob/master/firmware/console/status_loop.cpp

HOWTO:
step1: add new string contant into rusefi_config.txt
for example
#define GAUGE_COIL_DWELL_TIME "dwell: coil charge time"

Step2: use new constant in rusefi.input TS project template
for example
entry = sparkDwellValue,	@@GAUGE_COIL_DWELL_TIME@@, float,"%.3f"
(quotes note needed since string contant comes with quotes)

step3:
generate code using gen_config.bat

step4:
use new contant in firmware source code, for example change line to
	reportSensorF(log, fileFormat, GAUGE_COIL_DWELL_TIME, "ms", ENGINE(engineState.sparkDwell), 2);

step5:
use new contant in java console code, for example change line to
    DWELL(Fields.GAUGE_COIL_DWELL_TIME, SensorCategory.OPERATIONS, FieldType.FLOAT, 60, BackgroundColor.MUD, 1, 10),

End result example: https://github.com/rusefi/rusefi/commit/94ed4f25b8e0dc5ebeec899d71230bb5edb0f3e7

**Comment by fpoussin** [comment]
I suggest we use Python + Jinja2 (template engine) + PyYaml for these.

**Comment by rusefi** [comment]
Do not know anything about these tools unfortunatelly :(

I assume some code would be needed to calculate offsets - i doubt the tools would be flexible enough to generate TunerStudio .ini files structure, would they? Assuming some custom code would still be needed it's not too far from having everything in our own tools.

Anyway at this point all the tools are ready and the remaining part of the ticket is just to extract the constants and reference those on all three places - no infrastructure work left, only the actual content management.

**Comment by rusefi** [comment]
things are good enough now
