### ISSUE TITLE
Stop blocking DFU in console if version wrong.

### ISSUE THREAD

**Issue by NMSTEC** [rusefi/rusefi#3834]
<img width="639" alt="image" src="https://user-images.githubusercontent.com/45252464/150884614-dae1df7d-357b-42a5-873c-97a8f9d35fcf.png">

Should either warn and allow, or ignore altogether if manually DFUing.

**Comment by rusefillc** [comment]
That's by design, should stay

**Comment by rusefillc** [comment]
I am not aware of a legit use case where it should be possible to proceed

**Comment by mck1117** [comment]
We can at least ask the user what they think the right thing to do is, with an appropriate warning about proceeding.
