### ISSUE TITLE
microRusEFI -  pinout - can we merge sections

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3837]
@chuckwagoncomputing would it be OK for me to merge these two sections with three classes for pin: 36?

that's microRusEFI pin reuse, we have similar duplication for four pins

```
  - pin: 36
    id: [GPIOB_0, EFI_ADC_8]
    class: [switch_inputs, analog_inputs]
    color: orange left    
    ts_name: 36 - AN volt 8, Aux Reuse
    type: av

  - id: GPIOB_0
    class: outputs
    ts_name: AUX AV8 reuse

```

**Comment by chuckwagoncomputing** [comment]
As far as the pinouts are concerned, yes that's fine. Won't it break the configs of people who are using AUX AV8 reuse though?

**Comment by rusefillc** [comment]
@chuckwagoncomputing true

it's a trade-off for sure but it is important to emphasize same wire under same name instead of same wire under different names
