### ISSUE TITLE
1MHz software timer into F103 project

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3840]
Let's copy-paste single_timer_executor/microsecond_timer into sample F1 project

Let's have PB6 run at 30% duty cycle at 400Hz as a test of this code in F1 sample project

**Comment by rusefillc** [comment]
@NMSTEC can you help?

**Comment by mck1117** [comment]
Why? What needs soft pwm?

**Comment by rusefillc** [comment]
Dual WBO with dual analogue outputs would be a use-case for hybrid timer

**Comment by mck1117** [comment]
Dual WBO would warrant an F405, not run by a single F103.  The F103 doesn't have the ADC bandwidth for it.

**Comment by rusefillc** [comment]
Reeaaaaaaaaaaaaaly? F103 is so bad in ADC department or WBO demands so much?!
