### ISSUE TITLE
Add SPI code into stm32f1_test_project

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3842]
We have https://github.com/rusefi/rusefi/tree/master/misc/stm32f1_test_project

stm32f1_test_project already starts UART port and CAN port
we need to add SPI code 

for first test let's have SPI read code which would print something into UART or CAN your choice

for test source of SPI i suggest rusEFI firmware with GDI MC33816 settings enabled

flash any board with rusEFI
configure rusEFI to send SPI message via https://github.com/rusefi/rusefi/blob/master/firmware/hw_layer/mc33816.cpp

this ticket is asking for F103 code to read that SPI message

**Comment by NMSTEC** [comment]
yes will do today

**Comment by rusefillc** [comment]
Gdi4 has spi now

**Comment by rusefillc** [comment]
Gdi4 has spi now
