### ISSUE TITLE
narrow band to wide band conversion table

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#385]
If wide-band is not availble narrow-band allows at least some level of tune-ability, but a 8-point conversion table is needed. this table would be used to convert narrow-band signal in simulated wide-band signal

http://rusefi.com/forum/viewtopic.php?f=10&t=1205&p=24657#p24655

**Comment by rusefi** [comment]
See also ES_NarrowBand

**Comment by rusefillc** [comment]
Status update: this hack was removed some time ago
