### ISSUE TITLE
Console: Main "Pause" button not working?

### ISSUE THREAD

**Issue by andreika-git** [rusefi/rusefi#3854]
It seems that the "Pause/Resume" button stopped working.
Expected: When the main "Pause" is pressed, the console messages stop updating.
Actual: new messages are added...
![image](https://user-images.githubusercontent.com/15104768/151667603-dca9138a-4bea-4898-a121-2aa722d592e2.png)

The additional pause button above the messages still works.

P.S. The console is compiled from the current master.

**Comment by mck1117** [comment]
works for me?

**Comment by rusefillc** [comment]
@mck1117 does not work for me - note that there are two "pause" buttons on the same screen, it's the left-top which is does not work

**Comment by rusefillc** [comment]
it's not a great UI :( top-left button pauses gauges while the other button pauses text messages

I've renamed the top-left button to reduce the confusion a bit. thank you @andreika-git
