### ISSUE TITLE
Technical debt: ENUM_32_BITS

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3874]
ENUM_32_BITS which is used to force 4 byte enum size is a hack which should be removed

ENUM_32_BITS helps java code generator match C/C++ behavior:
looks like C/C++ enum size or alignment is more complex than what java code generator is currently capable of

step 1 of the fix would be to reproduce this issue with a unit test :)

**Comment by rusefillc** [comment]
See comments at #3785  and #3784

**Comment by mck1117** [comment]
we need  #3786 first
