### ISSUE TITLE
Good starting point to learn firmware

### ISSUE THREAD

**Issue by LmTinyToon** [rusefi/rusefi#3889]
Hello. I came across on rusefi project and it excited me. I want to learn its internals in free time. What is good point to start learning of firmware? I have good foundation in math/computer sciense ( c++/c knowledge in desktop development and some rusty background in firmware - AVR programming with atmega328p) and have basic understanding of internal combustion engines. But details of working engine is too vague to me. I have no idea of creation/injections of flammable mixture. I guess that  understanding of these details will help me to understand firmware. Here is my question:

Maybe there is good resources/books which were used during development? It's not scary if some math/physics formulas will be presented. I am primarly interested in books which will cover details of ecu and internal combustion engine. Less important for me is stm32 books, but I will appreciate them too.

**Comment by mck1117** [comment]
Come on over to our Slack: https://rusefi.com/forum/viewtopic.php?f=13&t=1198
