### ISSUE TITLE
console reconnection deadlock

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#3935]
![image](https://user-images.githubusercontent.com/568254/153778095-f0cd9a20-813a-40b0-98d7-84eda309c1c6.png)

Timer calls `LinkManager.restart()`, calls `connect()`, which calls `startAndConnect` etc which queues a function on the executor which will do the connection.

Then it calls `await` on a `CountDownLatch`, blocking the thread. But we're running on the executor thread! This blocks the executor from running the task that will complete, deadlocking the app.

**Comment by mck1117** [comment]
Looks fixed to me, @rusefillc does the console survive if you push/release reset button 10 times?

**Comment by rusefillc** [comment]
@mck1117 looks great!!!

@andreika-git FYI i know you were interested in that overall area
