### ISSUE TITLE
Extra Idle Air if Throttle is Pressed behavior

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#3940]
I think this function should be slightly improved so it can better be used as a sort of dashpot.

Suggestions:
1) Make it engage when the ECU goes out of "idle" state, not when throttle is pressed
2)  Implement a check for RPM/s that when under a RPM/s threshold, the value is slowly (maybe the rate at which idle returns to normal can also be configured?) returned to normal idle values.

Example:
User pressed throttle, engine RPMs increase significantly
Once the RPMs start falling, check rate of change of RPM to make sure we aren't dropping like a stone and possibly shutting off (or still falling into steady idle)
Once RPM/s is relatively low, the additional idle air subtracts slowly, to be able to return to idle without an undershoot

![image](https://user-images.githubusercontent.com/5685108/154221785-4679a6fd-abf1-4c83-b88c-a4283f55c539.png)

**Comment by rusefillc** [comment]
@andreika-git any interest?

**Comment by mck1117** [comment]
@ElDominio do you have a log that demonstrates the behavior you want this change to avoid? That would be helpful at least for us to test against, and maybe to offer alternatives that are already possible today.

**Comment by rusefillc** [comment]
and tune obviously

at the moment we are affected by https://github.com/rusefi/web_backend/issues/158 :(

**Comment by ElDominio** [comment]
The behavior this would try to avoid, especially in Open Loop operation, is a dip of RPM as RPM comes down from not-idle. 

This post https://forums.linkecu.com/topic/13259-dash-pot-settings/?do=findComment&comment=85016 explains it quite well, and even some OEM's (basically all USDM) use this even in closed loop mode. You crack the idle valve open to a certain % as RPMs are dropping from above idle, wait for them to stabilize (for .5s-2s, depends on how hard said engine decelerates), then slowly return idle % to the base table. It allows for a much more mellow return to idle, and much more consistent in my experience.

**Comment by mck1117** [comment]
Here's an example return to idle on rusEFI (5.3 LS, medium-ish cam, 228/230 duration):

![image](https://user-images.githubusercontent.com/568254/161491765-020d3f9d-c4c9-4208-90e5-44d3f0587044.png)

My idle timing control settings are probably more aggressive than they need to be, but you get the idea.

BTW, you can emulate this behavior by setting your open loop idle position to be a little bit (50-100 RPM) higher than target, then let the closed loop control pull it down once you're close.

I'd still love to see a rusEFI log so we can compare apples-to-apples.

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/161676082-fdf0e960-aafb-4350-8f2d-f927bb331777.png)

LinkECU's "lock out" of idle control when going outside of idle parameters. It arms once the car goes out of idle control method (adds additional idle air %), then enters dashpot function once idle conditions have been met again, and does the behavior explained in the last image

![image](https://user-images.githubusercontent.com/48498823/161676143-312dcd57-7fd4-4d59-b7de-6bd6626cf874.png)

additional idle % is held for x time, then removed over y amount of time to return to base idle value

**Comment by rusefillc** [comment]
@ElDominio at the moment my plan is to catch up with @andreika-git tomorrow

but please consider sharing a relevant tune & log - we really need to know _what_ we are addressing not just _how_ we are addressing it.

**Comment by ElDominio** [comment]
I want to share one, but I won't be near a RusEFI install in the next two weeks. I might be able to try one remotely, I'll let you guys know

**Comment by ElDominio** [comment]
https://rusefi.com/online/view.php?log=750

This log shows the behavior

![image](https://user-images.githubusercontent.com/5685108/164113784-f39ba2f7-facd-4031-9a89-4da79829b168.png)



Blue circles are the problem (RPM dips below when coming to idle), and the green line I added would be a ROUGH estiamte of what i'd expect idle valve to do

**Comment by rusefillc** [comment]
tune and log those come together as baskin and robbins

**Comment by ElDominio** [comment]
It's linked in the post heh

**Comment by rusefillc** [comment]
@ElDominio I must be blind :(

I do see https://rusefi.com/online/view.php?log=750 which is a log
I do not see tune link :(

**Comment by mck1117** [comment]
![image](https://user-images.githubusercontent.com/568254/164317253-6eebed1d-6aff-4225-bd12-eed7a84021e8.png)

**Comment by mck1117** [comment]
@ElDominio have a look at lambda - it's suuuper lean on decel, which is causing the dip.  Stable idle is ~1000 rpm, ~33kPa, and it's only a few kPa low while on the decel, but the lambda sensor is indicating off scale lean (>1.35, which isn't much range).

![image](https://user-images.githubusercontent.com/568254/164318418-b7fc1e31-4de1-4d8e-ab96-593fa88ba729.png)

**Comment by rusefillc** [comment]
@mck1117 i do not trust that "auto-link tune" feature think I believe it's showing weird too often at least that's my experience maybe I am not nice to it :(

**Comment by mck1117** [comment]
the linked one *is* the correct tune, though

**Comment by mck1117** [comment]
> @mck1117 i do not trust that "auto-link tune" feature think I believe it's showing weird too often at least that's my experience maybe I am not nice to it :(

create ticket?

**Comment by ElDominio** [comment]
Is it wrong to decel with no fuel? Shouldn't fueling be correct once the VE table goes round the idle areas?

**Comment by rusefillc** [comment]
https://github.com/rusefi/web_backend/issues/169

**Comment by mck1117** [comment]
> Is it wrong to decel with no fuel? Shouldn't fueling be correct once the VE table goes round the idle areas?

wall wetting means this isn't necessarily true

**Comment by ElDominio** [comment]
While we could banter on and on about this.... Could it still be added? All I know is that I really like this function even if it's superflous/unnecessary, and it helps me a lot with customer cars.

**Comment by rusefillc** [comment]
I am aware of three developers who could added
@mck1117 what do you say?
@andreika-git I suspect not sooner than a month from now
myself more or less same at least a month from now

**Comment by ElDominio** [comment]
another explanation of what i'm looking for 
![image](https://user-images.githubusercontent.com/5685108/199066256-3de732b1-d3ba-45b7-ae92-465960fed055.png)

![image](https://user-images.githubusercontent.com/5685108/199066334-4b47ea65-0382-4b8e-b40a-8ea68d148809.png)

**Comment by ElDominio** [comment]
gonna make new thread
