### ISSUE TITLE
Onboard SD Card Datalogging Doesn't Record TPS

### ISSUE THREAD

**Issue by droneperson42** [rusefi/rusefi#3943]
After discovering the magic of SD card logs recently I found that it does not record "Throttle pedal position" or "TPS" parameters (TPS is the parameter used on my Hellen NB1 ECU). The TPS gauge in TS works fine and it appears in datalogs taken through TS with a laptop or shadowdash MS on my phone via BT. See the SD log [here](https://rusefi.com/online/view.php?log=656). Currently running December 29 2021 FW version

**Comment by rusefillc** [comment]
code says that PPS is logged both under TPS and PPS names

```
	{engine->outputChannels.throttlePedalPosition, GAUGE_NAME_TPS, "%", 2},
	{engine->outputChannels.TPS2Value, GAUGE_NAME_TPS2, "%", 2},
	{engine->outputChannels.throttlePedalPosition, GAUGE_NAME_THROTTLE_PEDAL, "%", 2},
```

even your sample file shows TPS and PPS fields both at zero so on the one hand we have a defect but on the other hand it's not exactly correct to say that both TPS and PPS are not recorded. It looks like what's happening is PPS is recorded as TPS.

Do you have PPS on your vehicle? Please provide TS log along your next SD card log.

Now pushing fix to log TPS as TPS, firmware snapshot would have it in about 20 minutes

**Comment by rusefillc** [comment]
@droneperson42 we definitely had at least one defect which is fixed now please test again when you have a chance

**Comment by droneperson42** [comment]
I'll try it now. He's correct standard MX5 NB1 throttle cable and TPS

**Comment by rusefillc** [comment]
``now`` would be too early. please give it another 11 minutes

**Comment by droneperson42** [comment]
Yep, it fully works now! TPS values are displayed in the log. I've also noticed that the "date created" on the SD log files is also correct wheras before they all showed created in 2017. Cheers!
