### ISSUE TITLE
CPU usage stats with IRQ usage

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#396]
ChibiOS has some means of tracking thread CPU usage but not much for IRQ ticks (?)

A lot of rusEfi logic is witin IRQ, we need some monitoring

**Comment by rusefi** [comment]
@fpoussin  points at https://github.com/fpoussin/MotoLink/blob/master/code/app/main.c#L407

**Comment by fpoussin** [comment]
You can probably close this one

**Comment by rusefi** [comment]
Speaking of which, what is the ChibiOS way to access 168'000'000 value, i.e. CPU frequency?

// todo: access some existing configuration field
#define CORE_CLOCK 168000000

Yep, we now have this - see https://rusefi.com/forum/viewtopic.php?f=5&t=373&start=360#p30895

**Comment by fpoussin** [comment]
I think they use HSI/HSE and PLL mult/div values from mcuconf.h

**Comment by rusefi** [comment]
@fpoussin can you help with this?
