### ISSUE TITLE
Mark is asking for VIN number field

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3967]
I assume @NMSTEC is looking to have logic decoding options from VIN

17 symbols in VIN he says

**Comment by rusefillc** [comment]
please RTFM. RTFM starts on top of https://github.com/rusefi/rusefi/blob/master/firmware/tunerstudio/generated/rusefi_proteus_f4.ini

once you are done RTFMing feel free to ask questions :)

**Comment by NMSTEC** [comment]
Fine let's ignore that, Yes need VIN field. Needs to be LUA accessible as its required for Harley Security.
