### ISSUE TITLE
revisit romraider usage

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3971]
on the one hand RomRaider has made some amazing progress recently https://github.com/RomRaider/RomRaider/pull/130

on the other hand I think they are still officially 1.6 only and 32 bits only? that bother me a bit

For March 2022 we should remove RR under #319

Maybe one day we would add it again with proper upstream merge of all our integration hacks on top of 2021 refactoring progress

**Comment by rusefillc** [comment]
FYI @racer-coder since you have interest in frontend side of things

**Comment by mck1117** [comment]
looks like no romraider left in the repo?

![image](https://user-images.githubusercontent.com/568254/213823955-239af93d-c043-48e5-8069-f95af3a4e3fb.png)
