### ISSUE TITLE
Firmware Update via UART and/or USB

### ISSUE THREAD

**Issue by andreika-git** [rusefi/rusefi#398]
rusEFI should be able to update firmware using UART (done as of Dec 2018, see https://github.com/rusefi/rusefi/tree/master/firmware/bootloader see http://www.st.com/en/development-tools/flasher-stm32.html)

rusEFI should be able to update firmware using USB serial in a similar way

Add support for firmware uploading in rusEFI console - i.e. reimplement http://www.st.com/en/development-tools/flasher-stm32.html in java

**Comment by rusefi** [comment]
See also #147

**Comment by andreika-git** [comment]
This might help...

**Comment by fpoussin** [comment]
See https://github.com/fpoussin/MotoLink/tree/master/code/bootloader
It uses USB but it's exactly the same if using CDC.

Bootloader is updated via USB DFU (tactile button on boot0 pin)
This can also be a solution as it does not involve any firmware changes.

**Comment by rusefi** [comment]
http://dfu-util.sourceforge.net/ to provide reset after DFU upload

**Comment by fpoussin** [comment]
Looks like the libusb driver is not installed

**Comment by rusefi** [comment]
no idea how to install it, is there a command i can use?

**Comment by rusefi** [comment]
ps: it detects the HW ID so it must be communicating?

**Comment by fpoussin** [comment]
Did you read the documentation?

**Comment by rusefi** [comment]
Obviously not, anyone ever does that?!

**Comment by fpoussin** [comment]
Use https://zadig.akeo.ie to install the WinUsb driver and try again.

**Comment by rusefi** [comment]
@ksmola any interest?

**Comment by rusefi** [comment]
On the other hand we have https://github.com/NordicSemiconductor/Android-DFU-Library

Which could be potentially converted into non-Android JAVA DFU uploader

FYI @andreika-git

**Comment by rusefi** [comment]
See also https://github.com/rusefi/dfu_java

**Comment by rusefillc** [comment]
Sounds like OpenBLT also "via CAN" is the fanciest option and we now have it.
