### ISSUE TITLE
ECU prints unknown command for all commands

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#3980]
ECU prints unknown command even when it's a known command

![image](https://user-images.githubusercontent.com/568254/156882122-bc2d3396-f075-454f-a153-cf6f151ffde5.png)

**Comment by rusefillc** [comment]
@dron0gus could this be related to some of your recent changes?

**Comment by dron0gus** [comment]
Yes. This is my fault. Nothing bad happens, only return code is incorrectly interpreted and error message emitted.
Will fix it on weekend.

**Comment by mck1117** [comment]
Yep, that's why I assigned to you :)

No big deal, just created an issue so we didn't forget about it.

**Comment by mck1117** [comment]
also let's not do this:

![image](https://user-images.githubusercontent.com/568254/156906916-4d40f135-a4a6-42c5-95a6-50968868f1f9.png)

**Comment by dron0gus** [comment]
https://github.com/rusefi/rusefi/pull/3987
