### ISSUE TITLE
random order in generated_ts_name_by_pin

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#3989]
generated_ts_name_by_pin switch code generator uses a hash thus results are sometimes changing order randomly which is producing noise in git history

expected: always same generated code until there is a change

**Comment by mck1117** [comment]
> uses a hash thus results are sometimes changing order randomly

why would they change randomly? what is being hashed?

**Comment by rusefillc** [comment]
```
    private final Map</*id*/String, /*tsName*/String> tsNameById = new HashMap<>();
```

**Comment by mck1117** [comment]
do you have an example commit that caused an order change that shouldn't have?

**Comment by rusefillc** [comment]
Yes the one by @opelpanfan ?
