### ISSUE TITLE
TPS AE engages during crank

### ISSUE THREAD

**Issue by NMSTEC** [rusefi/rusefi#3996]
Expected result: TPS vs TPS to not be active until engine is running.
Actual result: During cranking TPS will move to crank position, which may trip AE.

Conditions: ETB is disabled while engine not spinning.

I am unsure if cranking RPM is overriden by TPS acceleration or it stays static until out of crank condition however due to my engine type, we have long enrichment times, so it may roll over into normal VE table.

![image](https://user-images.githubusercontent.com/45252464/158085338-3ec4567d-8d75-45c1-9d82-34a09b6408e1.png)
https://rusefi.com/online/view.php?log=694

**Comment by rusefillc** [comment]
@NMSTEC see arguing at https://github.com/rusefi/rusefi/pull/3997

**Comment by NMSTEC** [comment]
Argument continuing in Slack before transferring main talking points here.

**Comment by NMSTEC** [comment]
Considering conversation did not continue, I say, TPS vs TPS AE should NOT be used during cranking or no spinning. If there needs to be enrichment by TPS during cranking, then either tune is bad, or you have a carb making EFI pointless here, or your engine is scrap.
