### ISSUE TITLE
Mitsubishi 3A92 Support - 3 cylinder

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4011]
I have a 3 cylinder Mitsubishi Mirage project car with a 3A92 engine, with this trigger wheel combo in the following pictures.

Needs to be full sequential as this is a 3 cylinder lol
The trigger seems to be a 36-2-1-1, where the -2 indicates the arrival of piston at one of its TDC's, while the cam wheel seems to be a 4+1, the the double tooth indicates that cylinder 1 is next at the true TDC.
![image](https://user-images.githubusercontent.com/5685108/159127807-ed9543b3-34c8-47cb-be47-8fb21f78ad3a.png)
![image](https://user-images.githubusercontent.com/5685108/159127813-be240a65-9eb4-4933-9912-c25e4211239a.png)
![image](https://user-images.githubusercontent.com/5685108/159127823-875bdf50-eca2-46b3-abe3-d6641563fa7f.png)

6G75 also uses this trigger, but is a V6 instead of I3
#4014

**Comment by rusefillc** [comment]
@ElDominio what years use this? is this ever VVT or always fixed position?

**Comment by ElDominio** [comment]
This is always single VVT on exhaust, which is the wheel in the picture

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/159144566-7f844911-356e-4e2f-ba2b-219531cc678e.png)

**Comment by rusefillc** [comment]
@ElDominio https://github.com/rusefi/rusefi/wiki/All-Supported-Triggers#mitsubishi

**Comment by rusefillc** [comment]
@ElDominio please test with Sunday firmware
