### ISSUE TITLE
Don't use "/" and "-" interchangeably in  trigger names

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4012]
I think all "minus" triggers should be clarified, like 60-2 should be "60-2" not "60/2"  since the slash notation is what Megasquirt used (uses?) to refer to cam teeth. 36/2 in some ECUs would usually mean 36 on crank 2 on cam.

Also, there is a trigger called "Mitsubishi", but Mitsubishi uses a ton of pretty much custom trigger patters. 4G63 uses one pattern (well known, probably this is what "Mitsubishi" trigger is for), 6G71-4 use another pattern, 6G75 uses another pattern, 3A92 uses another pattern, 4B11 uses another pattern

**Comment by ElDominio** [comment]
![image](https://user-images.githubusercontent.com/5685108/207369140-c463d7be-e873-4317-a15f-573a26b11651.png)

This is what I meant. Would help a lot to avoid confusion

**Comment by ElDominio** [comment]
Still relevant,
there's 36/2, but then 36_2_2_2, then also 18-2-2-2

Why is it so incosistent? Why are slashes being used when no one uses slashes?

**Comment by rusefillc** [comment]
Dup of #6258
