### ISSUE TITLE
Mitsubishi 4B11 support

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4013]
Add support for the 4B11 crank trigger, 36-2-1 , camshaft is half moon.
![image](https://user-images.githubusercontent.com/5685108/159129310-c4865aa9-add8-4bad-ae00-b87750e74d7b.png)
![image](https://user-images.githubusercontent.com/5685108/159129318-f4a04d37-3d3b-40ae-9ce0-9357aa5ea46c.png)

**Comment by ElDominio** [comment]
Dual VVT on this engine, both cams are half moon type

**Comment by mck1117** [comment]
VVT config should be simple once we support that crank, just use single tooth first half/second half

**Comment by rusefillc** [comment]
@ElDominio please validate
