### ISSUE TITLE
Mitsubishi 6G75 Support

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4014]
![image](https://user-images.githubusercontent.com/5685108/159130117-37e06097-686f-44e9-972a-03c52cfe65ca.png)

Crank is a 36-2-1-1
Cam is that weird thing in the picture

**Comment by rusefillc** [comment]
@ElDominio what years are those? does this ever have VVT or is this always fixed cam position?

**Comment by ElDominio** [comment]
This has VVT, but it is only switched (like old VTEC)

**Comment by rusefillc** [comment]
@ElDominio any chance of a straight image of the VVT trigger wheel?

**Comment by ElDominio** [comment]
I can grab a scope off the oscilloscope but a picture of the cam itself.... let me try

**Comment by rusefillc** [comment]
@ElDominio do we still care? if we do please provide more info :)

**Comment by ElDominio** [comment]
This is a very common swap in PR, but as far as I can tell it's exactly 3A92. I haven't had one come in, but as soon as I do I will pester lol

**Comment by rusefillc** [comment]
Let's reopen if we have anything to do
