### ISSUE TITLE
trigger images have misplaced TDC

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4015]
looks like TDC line is always offset by some magic number

![trigger_TT_FORD_ASPIRE](https://user-images.githubusercontent.com/48498823/159143159-1293aa93-a845-4d97-838c-70f2dd9bc2e4.png)

![trigger_TT_FIAT_IAW_P8](https://user-images.githubusercontent.com/48498823/159143160-e43be4ff-0b90-44cf-b94c-bbdb047fc8e9.png)

**Comment by rusefillc** [comment]
@mck1117 could this be caused by #3905?

**Comment by mck1117** [comment]
I can check, what's the process for generating those from intellij?

**Comment by rusefillc** [comment]
"TriggerImage" IDEA configuration

fix incoming

**Comment by rusefillc** [comment]
@mck1117 

![image](https://user-images.githubusercontent.com/48498823/159143563-7b010789-7077-4c2e-8ade-82ef691efa81.png)
