### ISSUE TITLE
 toothed previous time

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4019]
@eldominio reports a FATAL error

![image](https://user-images.githubusercontent.com/48498823/159378973-7a5b50e2-2193-45a9-8bd1-f2c65275afdf.png)

**Comment by mck1117** [comment]
I have a hunch about what this is. We queue trigger input events in fast interrupts, then hand off to another interrupt to process them. That second interrupt processes them in pin number order, not chronological order, so it may be possible to get out of order events.

**Comment by rusefillc** [comment]
if that's the case would that mean that ICU is totally broken?

**Comment by mck1117** [comment]
No, these boards don't use ICU. This is probably a bug in `digital_input_exti.cpp`

**Comment by rusefillc** [comment]
@mck1117 this sounds important?

**Comment by mck1117** [comment]
we haven't seen it in a while.....so maybe fixed?
