### ISSUE TITLE
Proper cam speed labels in triggers

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4021]
![image](https://user-images.githubusercontent.com/5685108/159617347-a0a0a58d-0a1a-4b91-9d19-96e395591352.png)

I think "4 stroke with cam sensor" should be called "4 Stroke - Primary at Cam Speed/Crank Speed" or something like that. It doesn't really make sense to use "4 stroke without cam sensor" when the car in fact does have a cam sensor.

Or have a separate Primary Trigger Location dropdown menu, to choose Cam/Crank speed

**Comment by rusefillc** [comment]
Some progress was done - confusing drop-down replaced by two less confusing simpler drop-downs with conditional activation

![image](https://user-images.githubusercontent.com/48498823/161451579-53f33547-587c-4ab6-8989-75596b11dab6.png)
