### ISSUE TITLE
Trigger setup in TS is highly confusing: hide operation mode from users?

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4031]
We already only use "operation mode" for skipped wheel triggers

Question: do we even need it for skipped wheel triggers? shall we just declare that all skipped wheel triggers are always crank-based?

**Comment by rusefillc** [comment]
@mck1117 @OrchardPerformance @ElDominio?

**Comment by ElDominio** [comment]
No, I do a lot of Toyota skipped tooth on cam by grinding a tooth off the 24 tooth trtigger, it's usually the best choice even thought it has a +1. 

Also, the Aprilia 500cc engine is 48-2 on cam from the factory.

**Comment by rusefillc** [comment]
What users see now is called
``
engineConfiguration->ambiguousOperationMode
``

which is passed into ``initializeTriggerWaveform`` method - note how limited usages are already

**Comment by ElDominio** [comment]
Operation mode means where the trigger is located? Can't they have an option like say, 

Primary trigger location: Crank/Cam 

Secondary is always cam so that's that, but the primary trigger location should be selctable
