### ISSUE TITLE
technical debt: global trigger default is weird

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4032]
default trigger is 60/2 on CAM?!

```
	engineConfiguration->trigger.type = TT_TOOTHED_WHEEL_60_2;
	// huh WAT? our default is skipped on CAM?! and *many* our tests are relying on that?!
	setCamOperationMode();
```

**Comment by mck1117** [comment]
If we comment `setCamOperationMode();` we get:
![image](https://user-images.githubusercontent.com/568254/161416080-c6983c74-d17f-44c6-a498-91371548a404.png)
