### ISSUE TITLE
why CUSTOM_ERR_ZERO_CRANKING_FUEL?

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#4041]
![image](https://user-images.githubusercontent.com/568254/161449709-8b8b5376-d2c4-4c12-8ebc-45f2396b280d.png)

no start at the beginning of this log:
[no idle.zip](https://github.com/rusefi/rusefi/files/8405553/no.idle.zip)

using this tune:
https://rusefi.com/online/view.php?msq=935

**Comment by mck1117** [comment]
Looks like zeroes in the E100 table aren't helping.

![image](https://user-images.githubusercontent.com/568254/161453225-46f652cb-e5ab-45e4-9541-070b5608c1be.png)

**Comment by rusefillc** [comment]
#3791

**Comment by rusefillc** [comment]
@mck1117 please add default crankingFuelCoefE100 curve

**Comment by rusefillc** [comment]
this log is now https://rusefi.com/online/view.php?log=732
