### ISSUE TITLE
junk yard dreams: 121 pigtails

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4049]
GDI4 uses 121 pin https://rusefi.com/forum/download/file.php?id=9387 like 
99/2005 VAG
2010ish Nissan
some Hyundai

**Comment by duhafnusa4** [comment]
Thanks

**Comment by rusefillc** [comment]
@duhafnusa4 please assign to yourself since you are a secret member

**Comment by duhafnusa4** [comment]
going to the junkyard saturday

**Comment by NMSTEC** [comment]
Oh I have these

**Comment by duhafnusa4** [comment]
I have aqcuired 2 sets from nissans (pathfinders passenger side engine bay) and will be shipping today.
