### ISSUE TITLE
Pin 84 (O2 Signal) should be to an analog voltage

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4051]
Connecting this pin to an analog voltage input on the ECU would allow the use of this wire as an O2 input for people running widebands. Connect pin 84 to an analog input on the processor? With proper conditioning for 0-5v?

**Comment by mck1117** [comment]
what ECU is this for? Is there a better repo for this issue?

**Comment by ElDominio** [comment]
I thought I had made this in Hellen154, I'll copy it there.
