### ISSUE TITLE
Why do we need clean_env_variables.sh again?

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4060]
We use 'export key=value' and just 'key=value' in firmware build scripts

we also have a very weird clean_env_variables.sh

```

DEFAULT_ENGINE_TYPE=-DDEFAULT_ENGINE_TYPE=FRANKENSO_MIATA_NA6_VAF
FW_ID_ENV=frankensoNA6

export EXTRA_PARAMS="-DDUMMY \
 -DSHORT_BOARD_NAME=frankenso_na6 \
```

in the end we need all? most? variables to be consumed by common_make.sh which is always 'downstream' from the script where we set variables

Can we wipe out all 'export ' and wipe out clean_env_variables.sh as a consequence?

**Comment by chuckwagoncomputing** [comment]
Variables aren't handed down to scripts that are called unless they are defined with `export`.

On the other hand, I don't know why clean_env_variables.sh exists. Every firmware build is virtually on a separate machine. Maybe it's something for/from the Jenkins workflow?

**Comment by rusefillc** [comment]
So we do not expect ``FW_ID_ENV=frankensoNA6`` to work?

clean_env_variables.sh helps with consecutive executions which yes could be jenkins or even our local devices?
