### ISSUE TITLE
Flag more cases of suspicious configurations

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4065]
between https://rusefi.com/online/view.php?msq=946&dialog=ignitionSettings and another user having a bit worse case of similar issue today we need better messaging:

for wasted trigger and sequential fuel we shall say flag with "TBD tricky fuel settings"

for wasted trigger and individual ignition we shall flag a red warning "THIS WOULD PROBABY NOT WORK RIGHT"

**Comment by mck1117** [comment]
huh? the linked tune is fine

**Comment by rusefillc** [comment]
Linked tune has semi-random fueling which is acceptable but worth a message in TS

**Comment by mck1117** [comment]
This is kind of fixed by #4152, which doesn't let you run sequential without full sync (ie, something running at cam speed).
