### ISSUE TITLE
Set sensible default for dwell by voltage multiplier table

### ISSUE THREAD

**Issue by OrchardPerformance** [rusefi/rusefi#4067]
Just spoke to Lloyds over a non-spark issue, turns out it may have been "working as intended" and there was no output on the ignition coils as there was no dwell being commanded due to the default multiplier of zero. 

Suggest we set the default table to 8 -> 16v and a default value of 1 in all multipliers to protect us idiots from ourselves. 

![image](https://user-images.githubusercontent.com/49926376/163251703-d2e7146f-9e84-465e-8c3e-84c3c8a807a4.png)

Suggest 
![image](https://user-images.githubusercontent.com/49926376/163251793-cebb4708-e073-4758-b208-c038322b3c1c.png)

**Comment by rusefillc** [comment]
yes we need default

no, you are not facing this issue because

```
		// for compat (table full of zeroes)
		if (voltageMult < 0.1f) {
			voltageMult = 1;
		}
```

**Comment by OrchardPerformance** [comment]
hmm. Let me fire up an MRE and check what is going on then.

**Comment by rusefillc** [comment]
@mck1117 I've made a change which is progress but wrong

my change is wrong due to dwellVoltageCorrVoltBins not being autoscaler by 10. @mck1117 please PR autoscaling of dwellVoltageCorrVoltBins if you have a chance

**Comment by OrchardPerformance** [comment]
Ok, correct-andrey-battery-staple. 

It's not causing a no spark, so just a question of adding defaults. 

Not sure why they are reporting nospark, will personally investigate but it is tangential to defaults.

**Comment by rusefillc** [comment]
@OrchardPerformance see 
![image](https://user-images.githubusercontent.com/48498823/163257101-d01734f2-a9c6-4f74-a648-c2343fb897ce.png)
