### ISSUE TITLE
Help with Eclipse Rusefi C project

### ISSUE THREAD

**Issue by filipk5** [rusefi/rusefi#408]
I am trying to get this project going in Eclipse environment. I can not get it to run due to an error 127. Thanks for the help.
![eclipse rusefi compile project error](https://cloud.githubusercontent.com/assets/28354095/25667204/d36a6e2c-2ff0-11e7-9e0c-b7cedb0045ab.JPG)

**Comment by rusefi** [comment]
http://rusefi.com/forum/viewtopic.php?f=5&t=9 would be the most relevant forum thread

First troubleshooting step from there is
arm-none-eabi-gcc -v
in command prompt, what does it show?

I believe your Eclipse does not see arm-none-eabi-gcc installed

**Comment by filipk5** [comment]
Thanks 

I posted it it somewhere else in github but it looks like it does not need ti be there.

Help with Eclipse Rusefi C project · Issue #408 · rusefi/rusefi

  
|  
|   
|   
|   |    |

   |

  |
|  
|    |  
Help with Eclipse Rusefi C project · Issue #408 · rusefi/rusefi
 I am trying to get this project going in Eclipse environment. I can not get it to run due to an error 127. Thank...  |   |

  |

  |

 

Filip
