### ISSUE TITLE
Table rpm values non linear

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/rusefi#4091]
While reviewing a tune, it was found that th rpm values in the table were not linear.  This gave no errors to the user. 

https://rusefi.com/online/view.php?msq=963

![E8EA6A01-8394-4BEB-B871-67A2524C208F](https://user-images.githubusercontent.com/82395131/164774120-bfe19201-984b-4e80-a6c3-5953cfe93292.jpeg)

**Comment by rusefillc** [comment]
@BeerMoneyMotorsports any chance that you mean "ascending"?

**Comment by rusefillc** [comment]
We are invoking
```
		ensureArrayIsAscending("Ignition load", config->ignitionLoadBins);
		ensureArrayIsAscending("Ignition RPM", config->ignitionRpmBins);
```
on boot not every time properties were changed.

@BeerMoneyMotorsports please confirm that ECU was power cycled with those settings

**Comment by rusefillc** [comment]
@BeerMoneyMotorsports is this a tune from someone or can you reproduce this locally? meaning to be 100% sure on sequence of events?

**Comment by mck1117** [comment]
I loaded this tune on random recent firmware and it errored

**Comment by rusefillc** [comment]
@BeerMoneyMotorsports do you know steps to reproduce?

**Comment by rusefillc** [comment]
no response from OP
