### ISSUE TITLE
efiPrint NaN handling

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4115]
should say NaN but is saying 0.00000?

**Comment by rusefillc** [comment]
@chuckwagoncomputing i vaguely remember having some kind of test coverage for printf of floats

maybe in simulator? i will make a branch with broken printf of floats and we shall see what fails

but not today

**Comment by mck1117** [comment]
We just call chibios's snprintf function. We have -ffast-math set, so there's no guarantee that NaNs will be detectable.

**Comment by rusefillc** [comment]
So we have
```
static void runChprintfTest() {
```

**Comment by rusefillc** [comment]
@mck1117 https://github.com/rusefi/ChibiOS/pull/21
