### ISSUE TITLE
ISS does not work on two different TCUs due to max99xx 85ms timeout

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4117]
See https://rusefi.com/forum/viewtopic.php?p=45136#p45136

**Comment by rusefillc** [comment]
Is it time to ditch the biquad yet?

**Comment by mck1117** [comment]
> Is it time to ditch the biquad yet?

I don't understand why you jump from "the signal is noisy" to "let's delete the filter system"

**Comment by rusefillc** [comment]
I believe we decode RPM without filter system. Why do we need filtering to decode VSS? Why do we need filtering to decode ISS?

**Comment by rusefillc** [comment]
if we have cases where we need filtering it looks like we should have VSS_RAW and VSS_FILTERED as separate entities. encapsulation and etc.

**Comment by rusefillc** [comment]
@mck1117 @chuckwagoncomputing @dron0gus @Qwerty-OFF I would like to revisit this one. What is root cause of noisy? How can I help in moving filtering test from real hw into unit test area?

**Comment by chuckwagoncomputing** [comment]
Is there any way to capture a series of inputs and replay them in a unit tests?
e.g. capture a real-life input into a file with a series of timestamps, then replay that in a unit test

I can add code to output timestamps to debug console. I don't know if that's fast enough to keep up. I seem to remember some messages being cut off when I tried that earlier.

**Comment by rusefillc** [comment]
yes in about a week I can capture conditioned VR signal with logic analyzer similar to https://github.com/rusefi/rusefi/tree/master/unit_tests/tests/trigger/resources

**Comment by chuckwagoncomputing** [comment]
It seems like the biquad does not like any noise. Here's what happen's when you get an unexpected short gap:
```
40.909592
100.956970
105.647354
96.894814
4151.113770
6044.447754
564.367615
-766.487549
512.756165
-29.386383
125.853348
99.721848
97.454361
```
[test.c.txt](https://github.com/rusefi/rusefi/files/14951009/test.c.txt)

**Comment by mck1117** [comment]
This is very reasonable behavior for an IIR filter. The impulse response is naturally going to have some ringing.

![image](https://github.com/rusefi/rusefi/assets/568254/7d4d9783-62b6-4f39-98f2-a0d102391be3)

The impulse response of an [IIR](https://en.wikipedia.org/wiki/Infinite_impulse_response) is always going to be related to [sinc](https://en.wikipedia.org/wiki/Sinc_function).

**Comment by mck1117** [comment]
> I believe we decode RPM without filter system. Why do we need filtering to decode VSS? Why do we need filtering to decode ISS?

You actually do decode RPM with a filter, and that filter is that you average RPM over N teeth for one engine revolution, or for some number of degrees for instant RPM.

> See https://rusefi.com/forum/viewtopic.php?p=45136#p45136

I see a very clean analog signal here. Why does the very clean analog signal not arrive as very clean digital signal to the ECU?

**Comment by chuckwagoncomputing** [comment]
Is anyone using VSS without issue? I suspect my problems stem mostly from bad/noisy input signal.
See scope traces at https://rusefi.com/forum/viewtopic.php?p=49456#p49456

**Comment by rusefillc** [comment]
@ElDominio do you have positive experience with VSS sensor?

@chuckwagoncomputing i think canam VSS was pretty happy, it's a hall

**Comment by chuckwagoncomputing** [comment]
I would sooner expect hall VSS to work than VR. I don't know how the VR processing circuit works, but it seems to me that the low amplitude of a VR sensor at low speeds would be a lot more vulnerable to noise than either a hall sensor or a VR sensor at high speeds.

**Comment by chuckwagoncomputing** [comment]
https://rusefi.com/forum/viewtopic.php?p=49461#p49461

**Comment by rusefillc** [comment]
@chuckwagoncomputing @mck1117 would a cyclic_buffer of 16 last events help as a way to average?

**Comment by mck1117** [comment]
> Is anyone using VSS without issue? I suspect my problems stem mostly from bad/noisy input signal.

Yep, afaik Miatas have no problem.

**Comment by rusefillc** [comment]
> Yep, afaik Miatas have no problem.

Hall.

**Comment by mck1117** [comment]
> Hall.

Sure, but there's no convincing reason that any of the VR scope shots I've seen couldn't be decoded cleanly.

**Comment by chuckwagoncomputing** [comment]
> Sure, but there's no convincing reason that any of the VR scope shots I've seen couldn't be decoded cleanly.

With Proteus' VR input, or do you think more filtering pre-Proteus is in order?

I think the data I have collected shows that it is not being processed cleanly as is.
Oh I guess I should mention that there is a 10K resistor in series with VR+, and the scope measurements were taken after it, backprobing the Proteus connector.

**Comment by chuckwagoncomputing** [comment]
> would a cyclic_buffer of 16 last events help as a way to average?

Here's what that looks like - 1st column is input, 2nd is biquad, 3rd is average:
```
0	0	0
347	142	22
48	228	25
336	183	46
49	194	49
41667	17101	2653
2	24991	2653
71	1995	2658
4	-3605	2658
347	1885	2679
183	-267	2691
57	261	2694
5	12	2695
535	212	2728
15	331	2729
111111	45488	9673
8	66677	9674
6	5240	9653
591	-9486	9687
7	4991	9666
7	-1418	9663
7	246	7060
8	29	7060
8	-29	7056
7	25	7056
8	2	7035
8	9	7024
8	8	7021
8	8	7021
8	9	6988
8	8	6988
```

**Comment by mck1117** [comment]
yeah, moving average is still wrong, just different wrong.

![image](https://github.com/rusefi/rusefi/assets/568254/dd4ba56e-32f7-4499-92d4-bdb257687279)

Biquad is an IIR filter with prescribed corner frequency and Q factor, moving average is an IIR filter with N evenly spaced taps.

**Comment by mck1117** [comment]
> I think the data I have collected shows that it is not being processed cleanly as is.

vss.png, vss8.png, vss9.png: these look great and I would expect good results from a max9924

vss4.png, vss5.png: exactly how slow were you going?

**Comment by chuckwagoncomputing** [comment]
I think I was just coming to a stop on those. It's only while moving slowly that I have problems.

**Comment by mck1117** [comment]
OH, the timescale on those suggests that you're bumping up against the 85ms timeout limit on the MAX992x. If you get the 85ms timeout, it resets the threshold to the minimum possible (15mV or something tiny) instead of using 1/3 of the previous peak's voltage.

Might be worth wiring up a discrete VR board with a sufficient threshold to avoid that noise at near-zero speed.

**Comment by chuckwagoncomputing** [comment]
I think this is the magic answer. I don't math so good, but I think this puts the minimum at about 3.4 MPH, which I would say seems about right.

**Comment by mck1117** [comment]
you could also bootleg together a plain comparator with a little hysteresis from an opamp, doesn't even have to be "symmetric" and flip at zero crossings, just has to reject some more noise

**Comment by chuckwagoncomputing** [comment]
Both the VSS and the one-wire OSS on my Grand Marquis work nicely with the vr-discrete on the uaEFI.

**Comment by rusefillc** [comment]
not a SW issue but HW issue

thank you @mck1117 

closing, nothing to fix here.
