### ISSUE TITLE
temporary disable Acceleration enrichment logic for a few seconds After rpm Hard Limit event

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#413]
If we hit a hard RPM limit we should disable Acceleration enrichment logic for a few seconds just to reduce the firmware confusion in case of RPM hard limit jerking

**Comment by rusefi** [comment]
engineConfiguration->noAccelAfterHardLimitPeriodSecs

**Comment by mck1117** [comment]
this is a dupe of #187
