### ISSUE TITLE
Corolla 1ZZ 2003 trigger improvements

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4132]
[2022-05-02_14.12.19.zip](https://github.com/rusefi/rusefi/files/8605596/2022-05-02_14.12.19.zip)

![image](https://user-images.githubusercontent.com/48498823/166313087-59df90f0-a080-4b3c-afc3-4861cffdea33.png)

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/166313199-25defbcb-798e-4eee-9039-775ff806d8ec.png)

should be 

![image](https://user-images.githubusercontent.com/48498823/166313327-8a8ef3d0-6a16-469d-a270-4f4a657d78c9.png)

**Comment by rusefillc** [comment]
@eldominio please confirm that ^^^ setting have helped

Shall we implement this as new official hard-coded trigger?

**Comment by mck1117** [comment]
I don't think we need it as an official hardcoded trigger, I think we can just hand tune the ratios for all 36-2 triggers. Those overrides shouldn't hurt anybody else using a 36-1 on any engine.

**Comment by rusefillc** [comment]
@mck1117 so you say do not ADD new 36-2 but change current 36-2?

**Comment by ElDominio** [comment]
I would say just call it Toyota 36-2, since 1ZZ, 2ZZ, 2AR, 2ZR and pretty much all 36-2 4cylinder Toyotas use it at even the same angle. BTW Trigger Angle is -140.

And please rename triggers with "/" to + or - pleeeease

**Comment by mck1117** [comment]
> @mck1117 so you say do not ADD new 36-2 but change current 36-2?

correct

**Comment by rusefillc** [comment]
Usability follow up https://github.com/rusefi/rusefi/issues/4172
