### ISSUE TITLE
MRE wasted spark config error 

### ISSUE THREAD

**Issue by OrchardPerformance** [rusefi/rusefi#4134]
Looks like the TS config for the MRE is highlighting the wrong box. 
Confirmed on previous release (20220126) but not had a chance to check the newer releases yet. 

I don't think it is causing a running issue by setting Ignition 7 as output 4 but trying to confirm this currently.

![image](https://user-images.githubusercontent.com/49926376/166446734-481b8abb-4648-4374-9c24-496a462a653c.png)

**Comment by OrchardPerformance** [comment]
Extra context on the firing order 
![image](https://user-images.githubusercontent.com/49926376/166447696-d032e47e-e6c3-4f61-94fe-80a3cd0e25a5.png)

**Comment by OrchardPerformance** [comment]
Tune here for completeness. 

https://rusefi.com/online/view.php?msq=989

**Comment by OrchardPerformance** [comment]
Further investigation shows we actually highlight only the first 4 cylinders of the firing order. 
This is consistent behavior for all V8 firing orders available on MRE but is it the best/right way to do this? 
![image](https://user-images.githubusercontent.com/49926376/166585618-0169c8c8-118a-41cd-9fd4-26ca2f2e3c81.png)
![image](https://user-images.githubusercontent.com/49926376/166585640-ae35aeb2-d92a-4f22-95ff-d9c78f89139b.png)

**Comment by rusefillc** [comment]
@OrchardPerformance this was not touched for a few years

yes always first half, why does this look wrong to you?

**Comment by OrchardPerformance** [comment]
It's not wrong, just different, possibly quite clever but not currently well explained to tuners familiar with other systems). 

Closing this one off as there is no software problem, maybe just a documentation one.
