### ISSUE TITLE
chVTSetAny VS uart priority issue

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#414]
@andreika-git reports that periodicFastCallback and periodicSlowCallback callbacks within virtual timer are causing UART loss of bytes

Need to either ensure that virtual callbacks are taking less time or bump the UART priority which I'd rather not do considering coil control within virtual timer

**Comment by rusefi** [comment]
http://rusefi.com/forum/viewtopic.php?f=15&t=1233&p=25933#p25926

**Comment by rusefi** [comment]
Just noticed 
#define CH_CFG_ST_FREQUENCY                 1000

todo: check if same value was used before 3.0 migration?

**Comment by rusefi** [comment]
http://www.chibios.com/forum/viewtopic.php?f=3&t=1899&p=29454#p29452

**Comment by mck1117** [comment]
this was fixed by the buffered UART driver
