### ISSUE TITLE
User was unable to find Ford Mustang firing order 1-5-4-2-6-3-7-8 in the list

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4150]
1-5-4-2-6-3-7-8 seems to be the firing order for Ford Mustang?

**Comment by rusefillc** [comment]
Well, signal seems to be that we shall re-order firing orders (that would be an incompatible change) in order to make the drop down simpler

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/167293735-3dd9b047-fe3b-4ac3-a445-43f7902443a2.png)

**Comment by ElDominio** [comment]
i think this was solved

**Comment by rusefillc** [comment]
@ElDominio I've added human-readable suffixes for Mustang and HO
