### ISSUE TITLE
reduce flash footprint by smarter code generation

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4163]
OpenBLT does not fit inside 512K flash on F7 with work-around this points us at ``value_lookup_generated.cpp``

![image](https://user-images.githubusercontent.com/48498823/167801891-5185cf38-7475-430a-9d68-75fc98a50748.png)

**Comment by rusefillc** [comment]
base line
```
/home/runner/work/rusefi/rusefi/gcc-arm-none-eabi-9-2020-q2-update/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld: build/rusefi.elf section `.rodata' will not fit in region `flash0'
/home/runner/work/rusefi/rusefi/gcc-arm-none-eabi-9-2020-q2-update/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld: region `flash0' overflowed by 16680 bytes
collect2: error: ld returned 1 exit status
make: *** [ChibiOS/os/common/startup/ARMCMx/compilers/GCC/mk/rules.mk:217: build/rusefi.elf] Error 1
ERROR invoking compile_proteus_f7.sh
Error: Process completed with exit code 1
```

**Comment by rusefillc** [comment]
@mck1117 at least string literals are gone, is it good enough?

**Comment by mck1117** [comment]
I wish we'd done this in a branch so we could actually measure the impact 😢

**Comment by rusefillc** [comment]
@mck1117 we have the RC binaries from few days ago

**Comment by mck1117** [comment]
well, backporting current jar to the last commit before this latest batch of changes:

old lookup: 639054
new lookup: 636846
delta: 2208 bytes saved

So, did slightly save space! However I think there's a much bigger performance improvement, since its now comparing integers instead of the full string on every line.
