### ISSUE TITLE
Custom Toothed Wheel position should be able to be selected

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4178]
![image](https://user-images.githubusercontent.com/5685108/168506066-d87f3e4f-2de3-41fc-bf2f-a7313b2781b2.png)

We frequently run into 24-1 modified Toyota triggers on cam, or 4 teeth without missing. New update doesn't let us do this since the option is grayed out

**Comment by mck1117** [comment]
As a temporary workaround, you can select 60-2, set "on camshaft", then put it back to the correct trigger. The ECU is looking at those settings even though you can't change them in TS.

**Comment by rusefillc** [comment]
Looks like this fixed at some point - I did not do anything and it's selectable for me now

![image](https://user-images.githubusercontent.com/48498823/188488054-726887e5-853c-4d4d-854a-4d9260ea8468.png)
