### ISSUE TITLE
USB TS update rate

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4200]
At the moment my MRE via mini USB shows 249 which is too close to 250 and is not 999 as I recall on some record setting picture. Do we expect more than 249?

![image](https://user-images.githubusercontent.com/48498823/170396164-7a93ecae-ef78-4f42-8107-b3fe4b926619.png)

![image](https://user-images.githubusercontent.com/48498823/170396095-e30c8a1c-6ea1-4afb-8e16-2a37f7101504.png)

**Comment by rusefillc** [comment]
@mck1117 says

```
output channels are ~4x blocking factor
some limitation (not us, I don't think, maybe windows, maybe usb?) limits to ~1000 USB transactions/second
```

**Comment by rusefillc** [comment]
We clearly saw 999 which was clearly not random

![image](https://user-images.githubusercontent.com/48498823/171502801-4ec52a26-a8bd-45c8-ad55-ac4550195fc0.png)

**Comment by rusefillc** [comment]
@mck1117 i believe there was an update recently? can we link?

**Comment by mck1117** [comment]
yes, blocking factor was increased which got us back to ~500hz over USB #4703
