### ISSUE TITLE
remove handleGetStructContent

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#4205]
Remove TS_GET_STRUCT, handleGetStructContent, etc. Does the console even call these any more now that it uses the "flat" output channel based system?

#4075 related

**Comment by rusefillc** [comment]
dup

**Comment by mck1117** [comment]
do we still use TS opcode `TS_GET_STRUCT`?

**Comment by rusefillc** [comment]
i guess no? https://github.com/rusefi/rusefi/commit/5a2b4301838694cb1e81971e915a9acb89084781
