### ISSUE TITLE
Fatal error if TPS or pedal primary/secondary are too similar

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#4229]
We're trying to prevent people circumventing the redundancy requirement by running a wire to two inputs.

**Comment by duhafnusa4** [comment]
leave a way for it to work. just have a pop up that says "youre gonna die" or #jimmymode

**Comment by mck1117** [comment]
> leave a way for it to work. just have a pop up that says "youre gonna die" or #jimmymode

nah

**Comment by duhafnusa4** [comment]
:(

**Comment by mck1117** [comment]
done!
