### ISSUE TITLE
Send SENT MAF

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4240]
Please ship MAF not MAP

**Comment by NMSTEC** [comment]
Shipped.

**Comment by rusefillc** [comment]
next step is desiding which wires are GND, 5v and signal

**Comment by NMSTEC** [comment]
[Tahoe-Sent-MAF.pdf](https://github.com/rusefi/rusefi/files/8873161/Tahoe-Sent-MAF.pdf)

**Comment by rusefillc** [comment]
need more info see https://rusefi.com/forum/viewtopic.php?p=45542#p45542

**Comment by rusefillc** [comment]
@NMSTEC says
pin 5 +12
pin 6
pin 7
