### ISSUE TITLE
[SECURITY] Cheap password protection against tune modification

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4243]
TL,DR: make tune modification a bit harder
not goal: hide tune
not goal: assertion of tune authenticity

I have many requests of tuners to allow the use of password protection. It doesn't matter to me if the maps themselves are encrypted or not (would complicate things much more)

Only be able to disallow reading/writing through serial until the password is entered, preferably in a submenu under controllers, at which point the ECU correctly responds to read/write requests from Tunerstudio.

Once the correct password is entered, the  ECU entered an "unlocked mode", where the tune can be read/written until the lock is reapplied. Could be done with a dialog box with a password entry and a checkbox, once the box is unchecked, the ECU throws an error to ask the user to reconnect for map access.

**Comment by rusefillc** [comment]
good solution is not needed, we will start with a lame solution:

1) new flag which would disable write commands
2) padlock buttons to unlock
3) TBD mechanism for password entry and persistance

**Comment by NMSTEC** [comment]
I like this solution.

**Comment by ElDominio** [comment]
I was asked to ping two weeks after the ticket was opened so here id a ping a month afterwards

**Comment by rusefillc** [comment]
Sounds like https://rusefi.com/forum/viewtopic.php?p=34942#p34942 is the way to go here :(

I might have a cadidate for paid development assignments but I do not see myself personally coding this feature in the coming months.

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/181931824-246119ff-e00a-49d9-9b22-7717aa416a03.png)

**Comment by ElDominio** [comment]
Question: to unlock, can i just blast "unlock [password]" through serial? 

I want to make a neat unlock app so people can use password without consome

**Comment by rusefillc** [comment]
@ElDominio no, you would wrap the command into a packet with tunerstudio protocol header and footer including CRC

**Comment by ElDominio** [comment]
> [@ElDominio](https://github.com/ElDominio) no, you would wrap the command into a packet with tunerstudio protocol header and footer including CRC

Even for unlocking? Not locking?
