### ISSUE TITLE
GDI PT2001 Sense resisters for injectors should be 15mOhm, or settings altered

### ISSUE THREAD

**Issue by NOx-z** [rusefi/rusefi#4251]
all of these sense resistors for Rev A are 10mOhm whereas all of our previous versions are 15mohm (except for 10mOhm used on the boost converter sense, sense number 4). This has implications of incorrectly setting the expected peak-hold currents with our current settings.

solutions:
A) change settings for 10mOhm
b) swap resistors to 15mOhm

in real life we have smaller R0.3 - DO WE HAVE BOM?

R0.3.2 was a major change - at least a much larger board, BOM 
https://github.com/rusefi/rusefi/blob/48ff33c792e62359566485e4b9f6af0f8009c4be/hardware/Common_Rail_MC33816/gerbers/Common_Rail_MC33816_R0.3.2/Common_Rail_MC33816_R0.3.2_JLC_BOM.csv#L32

https://rusefi.com/docs/ibom/Common_Rail_MC33816_0.3.2.html

**Comment by rusefillc** [comment]
I will fix my legacy board, who else has what legacy boards? @NOx-z @mck1117 do you have any legacy? safer to update those all

**Comment by rusefillc** [comment]
Does this sound like https://github.com/rusefi/rusefi-hardware/issues/92 reason or contributing factor?

**Comment by rusefillc** [comment]
is this related to https://github.com/rusefi/rusefi-hardware/issues/96 at all?

**Comment by mck1117** [comment]
@rusefillc can you confirm what resistors are on the board you started the car on previously? There are references in code to them being 10mOhm, but we thought they were maybe 15.

**Comment by rusefillc** [comment]
Flight delayed by 40 minutes, ETA touch down 11pm EST

**Comment by rusefillc** [comment]
So "R22,R12,R26,R21"?

https://rusefi.com/docs/ibom/Common_Rail_MC33816_0.3.2.html ?

i think https://rusefi.com/forum/viewtopic.php?p=37790#p37790 is the picture of my actual board

at least  R010 matches 

![image](https://user-images.githubusercontent.com/48498823/174385984-0d320c01-f0af-405a-bad3-3810b331a9df.png)

**Comment by mck1117** [comment]
OK, in that case we're all set here, no change to make.
