### ISSUE TITLE
verbose trigger sync should reuse engineSnifferRpmThreshold

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4259]
we cannot afford verbose trigger at high RPM same as we cannot afford engine sniffer at high RPM

we shall apply same engineSnifferRpmThreshold logic and setting into verbose trigger sync

**Comment by mck1117** [comment]
Do we even need verbose trigger print out? We log the same sync data to TS log at ~500hz already...

**Comment by rusefillc** [comment]
We definitely do not log _all_ the info from console verbose lines. For instance #4172
