### ISSUE TITLE
Time delay before DFCO

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4292]
I remember some technical reason for this behavior but I don't remember it. The real  reason i would like this is so cars with pops can have, for example, 2-3 seconds of pops then go into DFCO. 

I think the technical reason is to control the amount of engine braking available but I'm not going to lie lol

**Comment by ElDominio** [comment]
Any progress on this?

**Comment by 10AE0739** [comment]
I was also looking for this feature in settings.

**Comment by rusefillc** [comment]
@mck1117 shall we close this ticket?

**Comment by mck1117** [comment]
@ElDominio want to give it a try?

**Comment by ElDominio** [comment]
Of course, I'll try to get it tested before sunday

**Comment by 10AE0739** [comment]
I'm running the 8/30 snapshot on my Hellen NB1. This works well. Thank you.

**Comment by mck1117** [comment]
Reports of it working, looks like we're done here!

**Comment by rusefillc** [comment]
We have this one and #4500 I wonder what else can use a time delay
