### ISSUE TITLE
Be able to use CAN RPM/TPS/MAP/VSS as operating inputs (replace actual sensors)

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4293]
I have been wondering if this is possible, as this could be useful to use 2Chan as aux fuel/boost control/additional I/O for cars that need this (not necessarily running rusEFI)

In my case I have a Hyundai Kona 1.6T in which 2Chan could be controlling aux fuel (only need injection time to be correct, since these are not the main injectors), boost control, and probably with flex fuel input.

**Comment by mck1117** [comment]
You can already set sensors from Lua (and receive CAN, of course).  That works for everything other than RPM, but you could do it by just PWMing the injectors without "running" the engine.

**Comment by ElDominio** [comment]
but, boost control is RPM dependent too, no? And for additional I/O conditions, most of those I/O would be RPM dependent

**Comment by rusefillc** [comment]
use Lua with one of lua general purposes tables not boost control table?

**Comment by rusefillc** [comment]
> you could do it by just PWMing the injectors without "running" the engine.

i do not get this part

**Comment by rusefillc** [comment]
@mck1117 ^^^

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi/wiki/Lua-Scripting#set-sensor-value has an example

**Comment by ElDominio** [comment]
Can it set RPM? and get treated as trigger? (Could be an evently spaced pulse at x frequency divided by number of cylinders?)

**Comment by rusefillc** [comment]
@ElDominio nope, RPM would be a very, very separate story

**Comment by ElDominio** [comment]
I think this works now right?

**Comment by rusefillc** [comment]
Yes possible with lua
