### ISSUE TITLE
usability confustion: ediatble fields with board overrides

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4295]
We have hard-coded board overrides and for instance in case of VBAT we have field editable

We shall make this less confusing, I assume TS has options for read-only values?

**Comment by rusefillc** [comment]
https://user-images.githubusercontent.com/48498823/175981287-2c19d393-b4e5-49ff-b6b5-85cf66367312.mp4

**Comment by mck1117** [comment]
just hide them on boards we know override it

**Comment by mck1117** [comment]
aka, the user doesn't ever have to think about battery sense on a proteus/mre/hellen/whatever, so why even show the UI?

**Comment by rusefillc** [comment]
where do we draw the line?

the value of showign read-only value would be sharing technical details while also sending the message that it's hard coded

like for instance CLT pull-up should it be hidden like I am about to push?
