### ISSUE TITLE
Ignition timing drift correction

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4311]
Tommy says that on some vehicles you need a configurable by rpm time offset if timing to get say 10  degrees fixed timing on the whole RPM range

Something something cam only sensors, belt stretch etc

**Comment by mck1117** [comment]
I'd love to add it when shown a video of a car set to "fixed timing" mode and a timing light that shows drift

**Comment by rusefillc** [comment]
Sounds like a plan. Closing for now, search would remember.

**Comment by rusefillc** [comment]
@eldomonio @blundar opinions?

**Comment by ElDominio** [comment]
I mean, as I usually say, most other ECU's have this. I have never really tested this happening and when you do the tune on the dyno, you usually end up compensating for this in the ignition map anyways.

But it is usually an option on pretty much every other ECU.
![image](https://user-images.githubusercontent.com/5685108/177007286-d376e4e0-43c5-4183-82bb-43c22623f00a.png)
