### ISSUE TITLE
re drivers not installing

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/rusefi#4313]
Hardware- Hellen Miata all
Firmware- current Release and Snapshot.  This has been an issue for a little while however i do not know the full scope.  Sometimes "install drivers works fine, other times it doesn't.

For new users that need to update firmware, they are following the instructions to
- Download correct firmware
- Connect ECU to laptop
- Open Console
- click "Install Drivers"
- restart laptop
- open console and hit Auto DFU
- "ERROR- DEVICE NOT INSTALLED"
- In device manager you see STM32 Bootloader with the caution triangle

The fix- 
- open device manager while ecu still in DFU
- update driver
- point it to the file folder ''Drivers" in the firmware.  must point it to the entire folder and not the individual driver
- install
- cycle ecu power and open console
- auto DFU now works.

**Comment by BeerMoneyMotorsports** [comment]
![image](https://user-images.githubusercontent.com/82395131/177016735-ac55c189-94bc-478a-b372-ed41df364738.png)

**Comment by rusefillc** [comment]
Got another complaint

We need to test if driver installer works for STM32 bootloader

Minor progress proposal #4475

As an idea shall we display any sort of helpful URL?

![image](https://user-images.githubusercontent.com/48498823/186255931-5e38a4a4-ca8c-4736-9dd2-df0a6db40880.png)

**Comment by rusefillc** [comment]
See also #4476

**Comment by rusefillc** [comment]
Do we fail to close one of the windows or something else with one of the windows?

![image](https://user-images.githubusercontent.com/48498823/187085590-26f5a287-3cb9-4a03-a334-206662ad500a.png)
