### ISSUE TITLE
Do not leave repo just to robots

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4323]
two automatic date in a row look weird

![image](https://user-images.githubusercontent.com/48498823/177673785-779a43c9-50e6-48bc-84ef-af41e4c82953.png)

@mck1117 @chuckwagoncomputing do we have elegant ideas? is this another case of #4302 and shall we leverage makefile instead?

**Comment by mck1117** [comment]
why not?

**Comment by chuckwagoncomputing** [comment]
I suppose that action could do a check to see if the most recent commit message was "Update date", and not run if so.
