### ISSUE TITLE
debug is set to idle mode, but none of the debug fields show anything

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4335]
https://rusefi.com/online/view.php?msq=1109

debug is set to idle mode, but none of the debug fields show anything.

https://rusefi.com/online/view.php?log=924)

**Comment by rusefillc** [comment]
related to https://github.com/rusefi/rusefi/issues/3614

@stefanst please try new fancy "live data" in console

as for logs, please see relevant "view" dialog - all fields of all "view" are logged

there is a chance that usability of all NAMES should be improved but at least "view" diallogs in TS show those names

**Comment by stefanst** [comment]
I believe this is the "live data"
![image](https://user-images.githubusercontent.com/709317/177908131-dd4fbff6-ac0b-4de3-9120-5e7372ede257.png)
It does not appear to contain any information about PID state.

**Comment by rusefillc** [comment]
it sounds like @stefanst is not hunting for "anything" but specificaly PID state?

**Comment by stefanst** [comment]
Correct. I was trying to tune idle PID. It is tricky without seeing what the PID is doing.

**Comment by stefanst** [comment]
AS to improvements in console: I will not use console for things that should be done in TS. Only if it's not possible to make TS do what is needed will I consider using a second tool.

**Comment by rusefillc** [comment]
"view" in TS is different from "live data" in console - maybe there is a confusion with terminology

"view" in TS shows only a list of variables with values

"live source code" in console shows actual source code with code flow branching

**Comment by rusefillc** [comment]
in the mean time renaming "idle" debug to "stepper idle" since that's all debug does now

**Comment by rusefillc** [comment]
@stefanst great news: your log file has PID info for a few of PID unconditionally regarless of debug mode

![image](https://user-images.githubusercontent.com/48498823/177916001-87949255-8e98-42e3-9537-d99dc48e21b9.png)


@stefanst please clarify if you are all set or what is still desired to be clarified or improved
