### ISSUE TITLE
fix Subaru EZ30 trigger gaps

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4344]
We shall hard code https://rusefi.com/forum/viewtopic.php?p=45853#p45853 magic

**Comment by rusefillc** [comment]
@mck1117 how did you come up with better numbers?

**Comment by rusefillc** [comment]
@mck1117 poke

**Comment by mck1117** [comment]
https://rusefi.com/forum/viewtopic.php?p=45971#p45971
