### ISSUE TITLE
Launch control bug? "range" thing is confusing

### ISSUE THREAD

**Issue by elmepro** [rusefi/rusefi#4348]
If launch control is set to 2000rpm, then in real world i got 4000rpm looks like its two times more rpm than set to TunerStudio.
(separate request edited out by @rusefillc )

Car bmw m50b25 tigger wheel 60/2
Board: Proteus
FW:  20220702

If something needed let me known.

**Comment by shadowm60** [comment]
Can you share tune?

**Comment by rusefillc** [comment]
please share log of launch attempt as well

**Comment by rusefillc** [comment]
@elmepro I have to request that one github issue coveres only well, one subject

**Comment by elmepro** [comment]
Im sorry for late response a had 2 day drifting training. (absolutely love rusefi)

Tune is same as uploaded  here are log file
[launch control log.zip](https://github.com/rusefi/rusefi/files/9128263/launch.control.log.zip)

**Comment by rusefillc** [comment]
@elmepro you say driftning on rusEFI and no photos/no videos? do you want to break my heart?

**Comment by elmepro** [comment]
> @elmepro you say driftning on rusEFI and no photos/no videos? do you want to break my heart?

Ouh don't worry I'm all in to Rusefi need small touches to car wiring and i will add videos and review

**Comment by rusefillc** [comment]
@elmepro it's a usability problem not a bug here

See https://rusefi.com/forum/viewtopic.php?p=45889#p45889

**Comment by rusefillc** [comment]
will replace "range" with "adder" on the dialog labels
