### ISSUE TITLE
PID logic: min/max handling

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#435]
open question if current PID implementation is right in terms of limiting iTerm into the minValue/maxValue range

https://github.com/rusefi/rusefi/blob/master/firmware/controllers/math/pid.cpp

**Comment by rusefi** [comment]
http://brettbeauregard.com/blog/2011/04/improving-the-beginner%E2%80%99s-pid-reset-windup/

**Comment by rusefi** [comment]
See also https://sourceforge.net/p/rusefi/tickets/353/

**Comment by rusefillc** [comment]
Too much was improved in this area since 2017
