### ISSUE TITLE
scaling of microRusEFI ADC gauges

### ISSUE THREAD

**Issue by mmatousek89** [rusefi/rusefi#4356]
when i remove rezistors and use AN8 as analog input, asign it to "advanced->aux inputs ADC#1" , scaling is wrong, i see only 2.9V when i aply 5v to AV8 pin, when i asign to "sensors-> oil pressure" reading is correct

**Comment by rusefillc** [comment]
:( @mmatousek89 i am upset by what I persive as low quality of this ticket. Specifically I am hurt by the fact that it does not seem to mention "microRusEFI"

**Comment by mmatousek89** [comment]
> :( @mmatousek89 i am upset by what I persive as low quality of this ticket. Specifically I am hurt by the fact that it does not seem to mention "microRusEFI"

i does mention "micro" in title ;)

**Comment by mmatousek89** [comment]
> @mmatousek89 please clarify what is source of signal with MRE test? is it just floating wire measuring pulled-up voltage?

source of voltage is 10k potentiometer and pushbutton to gnd with 4k7 pullup to 5V

**Comment by rusefillc** [comment]
@mmatousek89 i guess I am just overall tired and unhappy with HW drama

**Comment by mmatousek89** [comment]
> @mmatousek89 i guess I am just overall tired and unhappy with HW drama

i dont know how HW can be related if in other part of software (setted up as oil pressure) input work correctly

**Comment by mmatousek89** [comment]
when i asign
"advanced->aux input->ADC#1=AV5"
problem is still same,
gauge "sensors-raw->raw aux1 rawanaloginput1gauge" show 0-2,960V when potentiometer aply 0-5.000V to input AV5

**Comment by mmatousek89** [comment]
in console i can see right value as "input" 

Aux analog ADC14 ADC_SLOW PC3 adc=2.96/input=4.97V/divider=1.67

so i assume that gauge is by mistake linked to "adc" instead of "input"
