### ISSUE TITLE
What about "catch all CAN" via Lua

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4373]
Do we have the API to CAN RX any message not just the speciifc list?

for instance vaguely related to crazy MS 29 bits https://github.com/rusefi/rusefi/blob/master/firmware/controllers/lua/examples/ms29bit.txt or just cases when we need to relay 100s of different messages from bus one to bus two while fildering our very few IDs or just changing baud rate

**Comment by rusefillc** [comment]
@NMSTEC FYI

**Comment by kjngineering** [comment]
Proposal from https://github.com/rusefi/rusefi/issues/4374

could work like:

canRxAdd(0x20000000,0xFFFFFFFF,*callback)

which would be a capture all for all addressses.

**Comment by mck1117** [comment]
> canRxAdd(0x1FFFFFFF,0x1FFFFFFF,*callback)
> 
> which would be a capture all for all addresses in standard + extended.

or canRxAdd(0, 0, callback)
