### ISSUE TITLE
Martin reports that latest snapshot bricks his MRE

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4382]
Martin reports that latest snapshot gives him FATAL without USB

**Comment by rusefillc** [comment]
https://rusefi.com/online/view.php?msq=1131

**Comment by rusefillc** [comment]
0715 works
latest fatal

would be nice to isolate date of issue

See https://github.com/rusefi/rusefi/actions/workflows/build-firmware.yaml?query=branch%3Amaster


each link like https://github.com/rusefi/rusefi/actions/runs/2720877025 has artifacts - use MRE files from artifact

**Comment by rusefillc** [comment]
from experience lack of USB means ChibiOS halt like #3186

**Comment by rusefillc** [comment]
well we have #2859 and yet it did not help

**Comment by mck1117** [comment]
I'll have a look tonight with a debugger attached

**Comment by rusefillc** [comment]
so far I am unable to reproduce

```
[4:23 PM, 7/26/2022] ecu martin honda: hmmm... not so happy because i cant see, ohh shit
[4:23 PM, 7/26/2022] ecu martin honda: i unsoldered board with sd card
[4:23 PM, 7/26/2022] ecu martin honda: can this kill usb?
```
it's the unofficial MRE board

![image](https://user-images.githubusercontent.com/48498823/181109596-c4b789d2-5ca5-42d0-bc59-470d82de6fd3.png)

**Comment by mck1117** [comment]
no repro, close?
