### ISSUE TITLE
Additional CAN messages

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/rusefi#4401]
I have noticed we are missing a few CAN messages on the Bus.  There are probably more that i have not noticed.  

1- Low Fuel Pressure
2- High Fuel Pressure
3- Flex %

**Comment by rusefillc** [comment]
Do we need to update https://github.com/rusefi/rusefi/blob/master/firmware/controllers/can/rusEFI_CAN_verbose.dbc @mck1117 ?

**Comment by 10AE0739** [comment]
I'll add to this. I'd like to see target AFR CAN messages so that it can be displayed on CAN Gauges.

**Comment by mck1117** [comment]
this isn't done, the dbc needs updating
