### ISSUE TITLE
Hellen NA6 Warning 354

### ISSUE THREAD

**Issue by Keith-N** [rusefi/rusefi#4418]
ECU : Hellen NA6 Rev b
Using snapshot 20220806

When the ignition is on, a warning code 354 constantly occurs. Connecting via USB only does not cause this to occur. The car can still be started and idle without issue. 

A log was taken while cycling the key and starting/stopping the engine.

Log can be found here [https://rusefi.com/online/view.php?log=945](url)

**Comment by mck1117** [comment]
Probably a bug in my recent PR adding those warnings. I'll have a look!

**Comment by rusefillc** [comment]
@Keith-N please re-test

**Comment by Keith-N** [comment]
I tested again after the referenced commit was merged and no longer see the constant warning 354

**Comment by Keith-N** [comment]
Issue
