### ISSUE TITLE
some ignition events skipped 

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#4421]
Some cylinders seem to not fire even though sync looks OK.

Sequential mode:

- Ignition 2/4 missing, but those cylinders get fuel.

![image](https://user-images.githubusercontent.com/568254/183264425-b52db069-ba54-44a0-b781-2e781ea1ec46.png)

Wasted spark:

- All looks normal, engine runs well

![image](https://user-images.githubusercontent.com/568254/183264796-48ed95bc-0571-4f09-84e9-c9eb68ad6d9b.png)

Log: https://rusefi.com/online/view.php?log=946
Tune: https://rusefi.com/online/view.php?msq=1137

**Comment by mmatousek89** [comment]
seems like you are locked in 0-360degree of engine cycle and 360-720 is ignored .

**Comment by rusefillc** [comment]
@mck1117 how shall we proceed in your opinion? what data do we have or need to reproduce this issue?

**Comment by mck1117** [comment]
I can have a look at this to try and reproduce with the provided info, I think it's enough to at least try.

**Comment by mck1117** [comment]
I think this is *probably* fixed. We saw a few people with similar issues, and updating to latest seemed to fix the issue.

**Comment by mck1117** [comment]
I think it's fixed, but we can reopen if we see it again.
