### ISSUE TITLE
VVT target to allow negative values

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4424]
4B11 VVT issues: positive duty makes Exhaust VVT go negative

As title says, that happens, but VVT angle cannot be negative. Need to target negative angle since this is expected operation

**Comment by rusefillc** [comment]
duty? angle? I am very confused

tune URL is best

**Comment by ElDominio** [comment]
https://rusefi.com/online/index.php?vehicleName=Lancer+NotEvo+fifrst&user_id=675&sorts[uploadedMsq]=-1&sorts[uploadedLog]=-1

Increasing exhaust VVT duty makes the VVT angle go into negative numbers (when idling at 0 degrees)

**Comment by rusefillc** [comment]
@ElDominio what is "actual behaviour" and what is "expected behaviour"

I am starting to wonder if that's about VVT target table not allowing negative values

Are you asking for VVT target to start accepting negative values?

![image](https://user-images.githubusercontent.com/48498823/183550831-dd765a0a-f496-45e0-99e9-30f69851a9ce.png)

**Comment by ElDominio** [comment]
Correct, that would be best

**Comment by rusefillc** [comment]
just a reminer that you would need to lower PID min value to include your negative range

**Comment by mck1117** [comment]
there's a other step, the control is reversed for his exhaust cam

**Comment by rusefillc** [comment]
For reversed control do we simply use negative P?

**Comment by mck1117** [comment]
> For reversed control do we simply use negative P?

It's much more user friendly to not do that.

**Comment by mck1117** [comment]
> just a reminer that you would need to lower PID min value to include your negative range

PID min is the min output - not the min target

**Comment by rusefillc** [comment]
https://github.com/rusefi/ts-issues/issues/52

**Comment by ElDominio** [comment]
https://rusefi.com/online/view.php?log=967

VVT exhaust angle target is negative, PID max and min are 90 and -90 respectively. No change in VVT angle, VVT direction for exhaust is set to "retard"

https://rusefi.com/online/view.php?log=968

This log has VVT direction set to "advance", and once the target is changed to a positive value(at about 30s), actual VVT goes rapidly towards -40 (max VVT angle on exhaust), I assume because the PID is seeing it get farther and farther away from +10 (the target) .

**Comment by ElDominio** [comment]
👀
