### ISSUE TITLE
Unable to tune low idle

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4437]
@ElDominio reports challenges with idle tune

Desired idle around 750 RPM, other ECUs seem able to achieve but not RE

**Comment by ElDominio** [comment]
@rusefillc  if anyone wants to try to tune it they are welcome. 

Both cars idle fine at 750 after the VVT position update. Only when cranking they sometimes jump from +350 degrees to -350ish degrees. After some time it has a chance of landing on 0 and starting.

**Comment by rusefillc** [comment]
@ElDominio you are the Chief Tuner remember?

#4438 created
