### ISSUE TITLE
Something with cranking and engine phase detection

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4438]
@ElDominio please provide unhappy tune and logs

**Comment by ElDominio** [comment]
Will do as soon as possible

**Comment by ElDominio** [comment]
https://rusefi.com/online/view.php?log=964

At exactly 5.8 seconds, exhaust VVT jumps from 0 to 360

https://rusefi.com/online/view.php?log=965

At exactly2.4 seconds, you can see VVT go from 0 to -360, then at 3 second, from -360 to +360. Is this affecting sync phase or should not matter?

**Comment by rusefillc** [comment]
Engine phase is driven only by vvt intake at the moment

bulb could be #669 which is still unresolved

overall let me go over those logs :)

**Comment by ElDominio** [comment]
https://rusefi.com/online/view.php?log=966

On this log, at 6.4 seconds exhaust VVT jumps to 360, at 6.5 seconds it comes back down to zero, and at exactly that point the car seems quite happy and cranks over, working perfectly after that.

**Comment by rusefillc** [comment]
exhaust VVT jumps could be consequese of camResyncCounter going up. camResyncCounter might be the real deal

![image](https://user-images.githubusercontent.com/48498823/184545041-d55f5fc4-9267-4cdf-9050-d68aaed6f1d2.png)

**Comment by rusefillc** [comment]
We had fixes. Are able to reproduce this issue now?

@mck1117 what's your take?

**Comment by mck1117** [comment]
I think this is probably fixed, or at least wasn't duped when we did fix it

**Comment by rusefillc** [comment]
@ElDominio any objections to me closing?

**Comment by ElDominio** [comment]
Close
