### ISSUE TITLE
Hellen NB1 1999 Miata no tach output 

### ISSUE THREAD

**Issue by green21135** [rusefi/rusefi#4439]
Rusefi Hellen NB1 ecu is fully functional except no tech output to the gauge. Tach works in tuner studio properly but no signal to the dash. Tried setting different output pins in TS, does anyone know what pin/settings I’d need? Or is this a hardware issue

**Comment by BeerMoneyMotorsports** [comment]
Tach output is fully functional. 

![40EA6475-C8E5-42DB-B90C-99E99BD9EE84](https://user-images.githubusercontent.com/82395131/184538488-b647349c-76b9-4a88-8886-f09afb09725b.png)

**Comment by green21135** [comment]
> Tach output is fully functional.
> 
> ![40EA6475-C8E5-42DB-B90C-99E99BD9EE84](https://user-images.githubusercontent.com/82395131/184538488-b647349c-76b9-4a88-8886-f09afb09725b.png)

I am getting this list of pins available, what do I need to do for it to list that pin?
![90B249C1-D1CC-4078-A1C3-C0B94B2D5241](https://user-images.githubusercontent.com/29759237/184539642-cc0d0cea-f841-4ef0-9e53-5ecc884e1f20.jpeg)

**Comment by rusefillc** [comment]
@green21135 how did you get fgis unit when?

Please update the firmware toblatest release

**Comment by rusefillc** [comment]
Closing since no response
