### ISSUE TITLE
invalid ini

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#4451]
![image](https://user-images.githubusercontent.com/568254/185014429-59190c48-935e-41db-ac8d-1da4639e88cc.png)

**Comment by rusefillc** [comment]
please elaborate

what version of TS? new issue? old issue? any context?

**Comment by mck1117** [comment]
ini from current master, latest non-beta TS

**Comment by mck1117** [comment]
broken by this commit: https://github.com/rusefi/rusefi/commit/afc376bf8c31bae118cf429fa2b4b576c45374e1

because when you said

![image](https://user-images.githubusercontent.com/568254/185015262-3a65e79a-19ba-46fd-ba19-b975dbfa9a88.png)

that was in fact not quite true, because the legacy parser doesn't work either

**Comment by mck1117** [comment]
This issue and the discussed `vvtStatus` "array of struct iterate" are both fixed by #4287.

**Comment by rusefillc** [comment]
@mck1117 please clarify your test process for #4385

did you open TS after you broke .ini under ##4385?
