### ISSUE TITLE
.ini files should be uploaded prior to snapshot upload

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4454]
At the moment build-firmware.yaml uploads snapshot potentially before corresponding .ini file is uploaded

We should move .ini file upload into firmware job

![image](https://user-images.githubusercontent.com/48498823/185023266-759b3711-40ce-4ef6-96ac-9d0332f09fc1.png)

**Comment by rusefillc** [comment]
Another benefit of moving .ini files to firmware job would be not uploading .ini file if we "skip-rate" firmware build. That's important since current REO host does limit total number of files.

**Comment by mck1117** [comment]
> Another benefit of moving .ini files to firmware job would be not uploading .ini file if we "skip-rate" firmware build. That's important since current REO host does limit total number of files.

that's a good point! what's that file number limit?

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/185023919-d7e2a77a-3e7b-4d5e-a22a-d1251bb3aaef.png)

**Comment by mck1117** [comment]
it also looks like we might be uploading every ini file for every build, even if they're duplicates

**Comment by mck1117** [comment]
for example this build uploaded ini files with no ini change: https://github.com/rusefi/rusefi/runs/7829688078?check_suite_focus=true

**Comment by rusefillc** [comment]
@mck1117 two issues

1) FullServerTest relies on default .ini file to be available in the internet
2) we upload custom builds but not the default .ini see https://rusefi.com/online/ini/rusefi/2022/08/

**Comment by rusefillc** [comment]
@mck1117 

![image](https://user-images.githubusercontent.com/48498823/185275942-bf23e43c-7dea-4e88-8206-073773d92882.png)
