### ISSUE TITLE
Hyundai154 not showing model in firmware, is this ok?

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4466]
![image](https://user-images.githubusercontent.com/5685108/185824935-92638d3c-e60c-4375-af5b-d79b12b10b50.png)

Used console to update, and now it seems to be running generic firmware. ECU works fine, but just a heads up

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/185826080-b98aeaf7-9232-4bf6-bfa8-7fd40b44c25e.png)
 looks good

do you expect to see hyuindai somewhere else?

i.e. that's a big screenshot, what part of the screenshot looks wrong or what _exactly_ is not working as intended?

**Comment by ElDominio** [comment]
That is the one it is expecting if i'm not wrong, the one found being 
![image](https://user-images.githubusercontent.com/5685108/185831466-47b1aaa5-31bd-4fa5-938a-b776b537ed75.png)

**Comment by rusefillc** [comment]
@ElDominio it looks like it was always like that (console title never showed board name) and nothing is "broken" but it's overall "confusing"

```
	char versionBuffer[32];
	chsnprintf(versionBuffer, sizeof(versionBuffer), "rusEFI v%d@%s", getRusEfiVersion(), VCS_VERSION);
	tsChannel->sendResponse(TS_CRC, (const uint8_t *) versionBuffer, strlen(versionBuffer) + 1);

```

**Comment by mck1117** [comment]
this looks fine....does the "yes" button work?

**Comment by rusefillc** [comment]
Yes but also legit usability improvement suggestion or at least signal, it's fair to be confused by current inconsistency

**Comment by ElDominio** [comment]
something was changed about naming on firmware and whatever is the current state is fine
