### ISSUE TITLE
Set a complete fuel cut when BattV = 0v

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4474]
This would make cars with main relay control shut off the moment key is shut off, then turn off the main relay after 1sec as usual. Clients keep asking why their car stays on after they key off

**Comment by rusefillc** [comment]
Let's unpack if multiple action items here:

1) is this happening with USB power or without or both
2) why 1 second for main relay what is it about

**Comment by mck1117** [comment]
besides, we should already be cutting the main relay when the ignition voltage goes low

**Comment by ElDominio** [comment]
1) happening on both
2) some cars get angry if it all shuts down at once? idk lol but if we want to keep MR alive for any reason, cutting fuel should still be done even if MR is on

**Comment by shadowm60** [comment]
On motorcycles there is an issue sometimes that voltage regulator dies, this would make voltage to jump over 18v, maybe this issue could be broken down that main relay/injectors are fired if the voltage is in a preconfigured voltage range?

**Comment by rusefillc** [comment]
So, overall: we have no idea what's going on and we have a lot of ideas :)

let's start the game of elimintation: @BeerMoneyMotorsports @stefanst did you experience anything relevant on Miata NB2?

**Comment by BeerMoneyMotorsports** [comment]
No issues with my NB2 or any  reported by my customers..

**Comment by rusefillc** [comment]
@ElDominio it sounds like this issue is only specific to specific vehicles.

Question1: are you aware of vehicles where we do NOT have the issue?
Question2: any model/year where we DO have the issue? Wiring diagrams etc?

**Comment by ElDominio** [comment]
Hellen154hyundai

69 mustang with a 4chan controlling main relay

**Comment by mck1117** [comment]
@ElDominio can you draw a rough diagram of:

- ignition wire from key to ECU (and anything else relevant)
- main relay wiring to/from ECU
- main relay wiring to other engine hardware

**Comment by rusefillc** [comment]
@mck1117 see edit - looks like Hellen154hyundai  is the one to explore? https://github.com/rusefi/rusefi_documentation/tree/master/OEM-Docs/Hyundai

**Comment by mck1117** [comment]
does the behavior still happen with USB connected? ie, can you log it?

**Comment by rusefillc** [comment]
@mck1117 what shall we do in your opinion? close or ask a question?

**Comment by ElDominio** [comment]
Remind me and I'll get a video of it happening

**Comment by mck1117** [comment]
After changing some wiring on my race car specifically in the name of increased safety during faults (if you crash, fuel pump should stop!), I think it's worthwhile doing this anyway. What if the car is wired wrong and the engine stays on? What if the main relay welds itself shut? We should kill the engine!

**Comment by rusefillc** [comment]
@ElDominio has provided https://youtu.be/qjGH8XD5hUM

**Comment by mck1117** [comment]
If the laptop is connected in that vid, can we get a TS log of that happening? I'm really curious what is going on there.

**Comment by ElDominio** [comment]
Car keeps 12v input at 12v for a second because thanks Mitsu

It still behaves strangely on hellen154 but, not like the video.

**Comment by mck1117** [comment]
If the ignition pin keeps voltage on it, how would we know that it's turned off?

**Comment by ElDominio** [comment]
That's why I didn't upload a log of it, on that car we don't have much of a choice. Once a Mustang I have at the shop I'll see if I can replicate what I mean, but on the Evo we can't do diddly squat, maybe I have to sniff key state from CAN (probably)

**Comment by ElDominio** [comment]
Close
