### ISSUE TITLE
windows 7 test log

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4476]
i have a win 7 laptop, just hooked MRE and no connectivity

![image](https://user-images.githubusercontent.com/48498823/186270166-9406d0b7-0197-4b7b-8a6a-c105caf6b608.png)

**Comment by rusefillc** [comment]
I've installed drivers using console button and got port working

![image](https://user-images.githubusercontent.com/48498823/186270495-06af21d1-b9e8-4b9a-bd8f-00a824809cc6.png)

**Comment by rusefillc** [comment]
switched to DFU using console but unable to DFU update

![image](https://user-images.githubusercontent.com/48498823/186270740-2fe7d94e-eeed-48f4-bb71-1aef71489a95.png)

**Comment by mck1117** [comment]
do we care about w7?

**Comment by rusefillc** [comment]
I have zero attachement to win7.

#4475 would at least give us a chance to know what our users are using

In my specific case win7 is the device I can just grab and test with zero effort upfront. With device drivers I assume that we would need real HW test, I am not aware of any fancy virtualization to help us here? Looks like _someone_ would have to use a bunch of hard drives for different Windows versions?

**Comment by rusefillc** [comment]
```
::echo off

@echo off
setlocal
for /f "tokens=4-5 delims=. " %%i in ('ver') do set VERSION=%%i.%%j

if "%version%" == "6.1" (
if exist "%windir%\sysnative\pnputil.exe" (
    start "STM32 USB DFU DRIVER" %windir%\sysnative\pnputil.exe -i -a  %0\..\DriverNotSigned\DFU_in_HS_Mode.inf
) else (
    start "STM32 USB DFU DRIVER" pnputil -i -a  %0\..\DriverNotSigned\DFU_in_HS_Mode.inf
)
) else (
if exist "%windir%\sysnative\pnputil.exe" (
    start "STM32 USB DFU DRIVER" %windir%\sysnative\pnputil.exe -i -a  %0\..\Driver\STM32Bootloader.inf
) else (
    start "STM32 USB DFU DRIVER" pnputil -i -a  %0\..\Driver\STM32Bootloader.inf
)
)
endlocal
```

**Comment by rusefillc** [comment]
https://stackoverflow.com/questions/7044985/how-can-i-auto-elevate-my-batch-file-so-that-it-requests-from-uac-administrator
