### ISSUE TITLE
ECU does not fire inj/ign correctly after swapping settings 3A92

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4477]
I use one 4chan ECU for:
1) Honda B20 (running a modified 24-1 modified trigger)
2) Mitsubishi 3A92 3 cylinder

When I moved the ECU from 3A92 to B20, injector 4 did not fire until i updated firmware (dk what this has to do with it)

Then, I swapped back to 3A92,  and now coil 3 does not fire (shows on RusEFI console that Coil3 is not being commanded to fire)

Logs and tune at
https://rusefi.com/online/view.php?log=996

**Comment by mck1117** [comment]
snip of rusefi console?

please include all the information you can about an issue

**Comment by ElDominio** [comment]
![image](https://user-images.githubusercontent.com/5685108/186282121-a6ef778b-7e8c-47d7-8775-c32415e5ea07.png)

**Comment by mck1117** [comment]
I don't understand your trigger configuration

![image](https://user-images.githubusercontent.com/568254/186282610-d30670eb-8669-4f03-83a6-3666430fd0e2.png)

![image](https://user-images.githubusercontent.com/568254/186282640-2fe8ef58-91ef-43e4-a925-8befbbfc5db6.png)

Does this engine have vvt? Even if not, the "first" cam must always be in the spot labeled "intake cam". But you have no cam inputs configured at all?

**Comment by mck1117** [comment]
There is a real bug here though, we're trying to do wasted spark on an odd-cylinder engine which doesn't really work properly right now.

**Comment by mck1117** [comment]
For now you should set "Require cam/VVT sync for ignition" to `true`

**Comment by ElDominio** [comment]
It does have VVT, and it is only on the exhaust cam, and only has that cam sensor. Intake has no sensor.

It did run correctly before with these settings, quite well in fact https://youtu.be/XcJ1Yui71R4 haha

I'll swap those settings and report back once I can (just stored the car)

**Comment by mck1117** [comment]
Ok, well, the cam input set as secondary is never correct for this setup.

**Comment by mck1117** [comment]
see also #4195

**Comment by ElDominio** [comment]
Will try to test this on Thursday

**Comment by ElDominio** [comment]
Not working, now it doesn't start since both coils 1 and 3 fire at the same time

log and tune: https://rusefi.com/online/view.php?log=1019

console snip: 
![image](https://user-images.githubusercontent.com/5685108/188017483-4e2f0dce-3783-439e-86ff-aed73b98f998.png)

**Comment by ElDominio** [comment]
![image](https://user-images.githubusercontent.com/5685108/188017997-20229a2e-57ef-41fe-b67b-f01f071fa9e1.png)


Set to sequential ignition

**Comment by ElDominio** [comment]
![image](https://user-images.githubusercontent.com/5685108/188019952-2df3c9de-645a-4512-abf7-a28558180bdf.png)


Injection enabled

**Comment by mck1117** [comment]
This one looks kind of similar: #4421

**Comment by rusefillc** [comment]
Related to #4532 - need to a recording of that vehicle

We did not change anything relevant for a while, this must be a tune issue. Worst case try a couple of previous releases.

https://rusefi.com/online/view.php?msq=1201&dialog=triggerConfiguration_IO uses proper cam option


Why wasted spark on https://rusefi.com/online/view.php?msq=1201&dialog=ignitionSettings ? you have CAM please use it for sequential?

**Comment by rusefillc** [comment]
Actually #4533 was changed 12 days ago so maybe do try Aug release just to confirm

but wasted does not right here, you have CAM please use it to reduce complexity

**Comment by ElDominio** [comment]
https://github.com/rusefi/rusefi/issues/4477#issuecomment-1234811305

This was done with sequential ignition/injection.

**Comment by rusefillc** [comment]
I would love to be effective
@ElDominio please join me in my desire to be effective

If we mix and jump between tunes need full tunes.

I suspect that the signal here is "tools such please implement better tools". It sounds like console should compare latest online tune to current tune and offer convinience, or maybe I need to fix TS plugin.

**Comment by ElDominio** [comment]
but the full tune is in online, is it not?

**Comment by rusefillc** [comment]
@ElDominio a tune not explicitly linked pretty much does not exist

@ElDominio a tune not explicitly linked means "please find me and good luck hopefully you would find the right tune but maybe not"

@ElDominio please link the tune you are referring to

**Comment by ElDominio** [comment]
https://rusefi.com/online/view.php?log=1029

**Comment by ElDominio** [comment]
Andrey says ignition cut reason = 12 which is "no engine phase"

**Comment by mck1117** [comment]
![image](https://user-images.githubusercontent.com/568254/188746770-dfcb76b1-2ee6-41a1-b7c7-08684ee38032.png)

**Comment by rusefillc** [comment]
expected https://github.com/rusefi/rusefi/wiki/Images/triggers/trigger_TT_VVT_MITSUBISHI_3A92.png

**Comment by mck1117** [comment]
12 = engine phase (cam didn't sync yet

2 = fuel (aka the "enable fuel" bit is disabled on the injection config page)

**Comment by mck1117** [comment]
> expected https://github.com/rusefi/rusefi/wiki/Images/triggers/trigger_TT_VVT_MITSUBISHI_3A92.png

trigger looks great IMO, look at nice instant RPM (except for the blip that we already know about #4463)

**Comment by ElDominio** [comment]
![image](https://user-images.githubusercontent.com/5685108/188747469-17005bb4-4b26-406c-b6a7-84a634122204.png)


https://rusefi.com/online/view.php?log=1033

**Comment by mck1117** [comment]
Your tune loaded in simulator looks completely normal:

![image](https://user-images.githubusercontent.com/568254/188748964-60b886ed-580f-4259-a4de-480bb555a62b.png)

**Comment by rusefillc** [comment]
Huh? Is not simulator supposed to NOT work sice not VVT sync?

**Comment by mck1117** [comment]
I have cheated a little bit and tricked the sim in to having vvt sync

**Comment by ElDominio** [comment]
[rusEFI_trigger_log_2022-09-06_18_10_08_099.zip](https://github.com/rusefi/rusefi/files/9501180/rusEFI_trigger_log_2022-09-06_18_10_08_099.zip)

**Comment by ElDominio** [comment]
![2022-09-06_18_10_30_812rpm_0_maf_0 0](https://user-images.githubusercontent.com/5685108/188749494-423819e1-c8fd-4ba4-96e0-3977b025e9a4.png)

**Comment by mck1117** [comment]
yooo what did you change?

**Comment by rusefillc** [comment]
@mck1117 just edited with more info
