### ISSUE TITLE
Hyundai Genesis Coupe crank/cams logic analyzer recoding

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4485]
We need to add some files into https://github.com/rusefi/rusefi/tree/master/unit_tests/tests/trigger/resources

just for consistency older .logicdata is best, just for simplicity please have crank as channel and and cams and 2 and 3

See also https://github.com/rusefi/hellen154hyundai/issues/58 for test point location

**Comment by ElDominio** [comment]
Can be closed?
