### ISSUE TITLE
12-3 trigger losing sync, ECU disables ignition and injection

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4524]
We installed a 2chan on a CRF250F (one cylinder, 12-3 crank trigger, using MAP to sync), and are having some strange sync issues. If the thing runs perfectly all the time, it'll never have any issues, but if there's a misfire or a sudden change in engine speed it seems to lose sync and disable injection/ignition, which is terrible since it's a bike (injection and ignition are disabled until RPMs are zero, even though it is reading RPM just fine). 

Logging the issue is a bit hard since on the dyno, it's fine (everything is under control)  Still, here is tune and some logs: https://rusefi.com/online/index.php?vehicleName=CRF&user_id=675&sorts[uploadedMsq]=-1&sorts[uploadedLog]=-1

**Comment by rusefillc** [comment]
Do we have any log of an incident?

**Comment by ElDominio** [comment]
Very difficult to grab, behavior is a bit erratic. On dyno it barely happens, i'll have it back in the shop tuesday to try to reproduce

**Comment by mck1117** [comment]
💀💀💀💀💀

![image](https://user-images.githubusercontent.com/568254/188513318-bbaf5c44-2f01-4479-bb65-6c83463f338e.png)

**Comment by rusefillc** [comment]
Lol 2022.03

**Comment by ElDominio** [comment]
I always hit autoupdate and update firmware, wtf? 
Anywho it'll be at the shop tomorrow and I'll make sure it's on latest

**Comment by ElDominio** [comment]
https://rusefi.com/online/view.php?log=1039

Updated today and it still reports as 2022.03.23, wtf?

**Comment by ElDominio** [comment]
![image](https://user-images.githubusercontent.com/5685108/189551219-8b7bd4bd-5a1d-41e8-8bfa-f6acb5afe016.png)


on latest snapshot

**Comment by ElDominio** [comment]
![image](https://user-images.githubusercontent.com/5685108/189551431-07124df4-ac96-4516-b67d-653d6126790a.png)

**Comment by ElDominio** [comment]
Fixed by using console commands for read out removal

https://rusefi.com/online/view.php?log=1040  <- primary inverted

https://rusefi.com/online/view.php?log=1041 <- primary not inverted

**Comment by rusefillc** [comment]
@ElDominio please call I would like to empower you

![image](https://user-images.githubusercontent.com/48498823/190461099-2e17d110-e980-47e1-aacf-399972c7a85f.png)

https://rusefi.com/online/view.php?msq=1221&dialog=triggerConfiguration_gap

**Comment by ElDominio** [comment]
![image](https://user-images.githubusercontent.com/5685108/190483115-8c2ae37d-ae22-4cb0-ae37-cf3aa3fa29db.png)

**Comment by rusefillc** [comment]
Damn I wish I knew we are tring the VTwin mode :)


Red line looks to be the same every 360 degrees right?

**Comment by ElDominio** [comment]
![image](https://user-images.githubusercontent.com/5685108/190484492-101d08dd-c8eb-48d8-b6b1-b1a817c140c8.png)


No instant MAP!

**Comment by ElDominio** [comment]
https://youtube.com/shorts/TsgtuGhcpm8?feature=share
https://rusefi.com/online/view.php?log=1044

Video and log of problem

problem not being a problem for reasons uknown
https://youtube.com/shorts/wiGEJNaRO6g?feature=share

**Comment by rusefillc** [comment]
Data Rate: ~ 100
@ElDominio why are you so cruel to me?

Unfortunatelly even at 1KHz we do not have enough bandwidth to catch individual gap ratios. We would need to use external logic ananlyzer once you get latest 2chan in your hands with crank hookup point.

until we have logic ananlyzer pic i suggest starting randomly widening trigger gaps
try changing 4.7 to 5.7

try changing 0.800 to 0.7
try changing 1.340

![image](https://user-images.githubusercontent.com/48498823/190644293-f5b095b4-c0f1-4123-8108-606300b613c7.png)

**Comment by rusefillc** [comment]
@ElDominio how is this going?

@mck1117 "reliabity was a confurn" I recall, changes changlogs issue tracking etc?

**Comment by ElDominio** [comment]
Need logic analyzer? with new 2chan i should be able to

**Comment by rusefillc** [comment]
4chan but yes. weird that it has just stopped to even start without any clear reason :(

**Comment by ElDominio** [comment]
This 12-3 is on a 2Chan mounted on a CRF250, do the newer 2chan have pads?

**Comment by mck1117** [comment]
time for logic analyzer, without that we can't do much here

**Comment by ElDominio** [comment]
I think i can do this using a 4chan, will try asap

**Comment by ElDominio** [comment]
[12minus3logclog.zip](https://github.com/rusefi/rusefi/files/9740272/12minus3logclog.zip)

Ran for a sec then hit the weird engine off condition

**Comment by mck1117** [comment]
Your crank sensor lost a tooth.

![image](https://user-images.githubusercontent.com/568254/194802547-14521b72-04fd-4922-9d1b-fbdb9d5d0967.png)

**Comment by mck1117** [comment]
and it did it again 5 revolutions later:

![image](https://user-images.githubusercontent.com/568254/194802625-c7636690-40c4-4838-892a-0dc8920b5547.png)

**Comment by mck1117** [comment]
And just before it lost two teeth in the same rev:

![image](https://user-images.githubusercontent.com/568254/194802688-e7343791-c95b-495a-8e98-f56240850f20.png)

**Comment by mck1117** [comment]
Update: the VR threshold table was set too hot, reducing it up at those rpm should fix it.

**Comment by mck1117** [comment]
User reports that it's fixed with adjusted VR threshold.

**Comment by rusefillc** [comment]
https://github.com/rusefi/hellen88bmw-issues/issues/52
