### ISSUE TITLE
Sensor.java should be auto-generated at least partially

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4525]
Sensor.java having magic offsets is a shame

One day we shall generate complete Sensor.java (shall we?) but at the moment we are pretty far. For right now we desperately need to auto-generate at least the offisets.

**Comment by rusefillc** [comment]
@mck1117 are you interested or shall I? Want to make sure that we are not working on this concurrently.

**Comment by mck1117** [comment]
go for it

**Comment by rusefillc** [comment]
Good for now
