### ISSUE TITLE
A picture of Norman holding a logic analyzer

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4532]
ebay.com
"logic analyzer"
$10ish works magic

**Comment by ElDominio** [comment]
![IMG_20220910_213919.jpg](https://user-images.githubusercontent.com/5685108/189508036-2be73b3f-f67a-46e6-8bb9-503ce40519cf.jpg)

**Comment by rusefillc** [comment]
@eldomino next step https://support.saleae.com/logic-software/legacy-software/older-software-releases
