### ISSUE TITLE
Injection Offset for skipped wheel triggers

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4536]
Looks like fuel injection angle is wrapping angle using wrong operation mode method potentially causing unindended injection angle for skipped wheel configurations

**Comment by mck1117** [comment]
do we have a test that catches this wrong behavior?

**Comment by mck1117** [comment]
oh, I guess this was actually more trivial than I thought it was. Perhaps `getWheelOperationMode` should be more private?

**Comment by mck1117** [comment]
and I think this only ever actually caused an issue if you were running a 2 stroke since `getEngineCycle` return 360 if 2 stroke, 720 otherwise
