### ISSUE TITLE
VVT Cam position issues using half moon trigger: Random jumps due to wrong CAM edge

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4539]
Lancer 4B11 has similar issues to Genesis (their cam setups are identical, half moon)

At random times, the cam reading jumps by an impossible value and then back to zero, at which point the car misfires for a split second

Log and tune: https://rusefi.com/online/view.php?log=1030

How it looks:
![image](https://user-images.githubusercontent.com/5685108/188509514-b86f1015-b31d-4bad-9df4-4cec55e373de.png)

**Comment by mck1117** [comment]
If you invert the vvt input (and adjust vvt offset to zero it out again), does that change the behavior? It's possible that one of the edges on the hall sensor is "lazy" and the other is "sharp".  We want the "sharp" one, not the "lazy" one.

**Comment by ElDominio** [comment]
You are correct, switched the cam edge and now it works perfectly. Thanks @mck1117 !

**Comment by ElDominio** [comment]
BTW, it fixed it for 4B11, NOT for Genesis! Genesis at cranking RPM is still unreliable sometimes

@rusefillc  automatic detection would be great, is it doable?
Maybe check for the variation in degrees in a certain amount of time, and pick the one with the least error? That's better than any other ECU out there

**Comment by mck1117** [comment]
Not sure fully automatic is a very viable strategy. That's a great way to find some marginal condition (new combination of temperature/engine speed/whatever) that picks wrong and then your engine won't start/run properly.

> NOT for Genesis! Genesis at cranking RPM is still unreliable sometimes

log?

**Comment by ElDominio** [comment]
https://rusefi.com/online/view.php?log=986 seen at 2s

https://rusefi.com/online/view.php?log=985

https://rusefi.com/online/view.php?log=964

Maybe have independent rising/falling for each sensor? idk why it still happens on genesis, and notice all logs show only exhaust cam

**Comment by mck1117** [comment]
Those are all old firmware - log again with new snapshot on the genesis and see if behavior changed.

964 shows the crank losing sync

985 shows good vvt position, but shows #4463, which should now be fixed-ish. This log looks OK to me.

986 same as 985

These all look like different issues, some of which are fixed.

**Comment by ElDominio** [comment]
https://rusefi.com/online/view.php?log=1035
Exhaust vvt on newest firmware

**Comment by mck1117** [comment]
> https://rusefi.com/online/view.php?log=1035 Exhaust vvt on newest firmware

What happens when not cranking? We don't use that cam for any engine sync purpose, just vvt measurement.

**Comment by mck1117** [comment]
OK, I now understand what's going on with exhaust vvt. Will create a new issue.

**Comment by mck1117** [comment]
@ElDominio do a bunch of cranks back to back again on genesis, see how it looks now

**Comment by ElDominio** [comment]
Forgot to update: VVT angles always look perfect, at least in this case! Need to test on 4B11 but G4KF is perfect!

**Comment by ElDominio** [comment]
This can be closed as it is the same as 4b11 double rpm ticket
