### ISSUE TITLE
publish continues integration artifacts online

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#454]
@andreika-git  would love to see full jenkins error report

@fpoussin what would you suggest? at the moment I have my jenkins instance with real stm32 hardware in my apparment and I would rather not expose my IP address for paranoia reasons, is there anything to publish jenkins state on the web? I can upload to the rusefi for example

**Comment by fpoussin** [comment]
You can store releases on Amazon S3 free, there are tons of APIs to make this automatic.

https://wiki.jenkins.io/display/JENKINS/S3+Plugin

**Comment by fpoussin** [comment]
Sure, PM me on slack.

**Comment by fpoussin** [comment]
https://developer.github.com/v3/repos/releases/#upload-a-release-asset

**Comment by rusefi** [comment]
This is still needed and I still do not have brain cycles to implement, I do not even understand the scope of work - is this a 3 minute project or a 30 minutes project?

@fpoussin @dron0gus @mck1117 @andreika-git as a simpler workaround I can simply add your emails into CI report destination list. Please respond if you are interested

**Comment by rusefi** [comment]
Closing this since we seem to be moving towards GH Actions
