### ISSUE TITLE
Request: Boost assist and different boost table axes

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4540]
Changing Y axis into load helps making Open Loop function "like" a closed loop, but without PID, I have used it a lot with good results. Example:
![image](https://user-images.githubusercontent.com/5685108/188511459-3d78cae1-c800-4cc2-a158-7073e934c99f.png)

Also, a spool assist function would help, described in this pic:
![image](https://user-images.githubusercontent.com/5685108/188511494-e80606c1-44bd-4026-98a9-dd4cbb7df4bd.png)

**Comment by mck1117** [comment]
"spool assist" covered by  #4316

**Comment by ElDominio** [comment]
can i have switchable Y axis on boost table yet

**Comment by ElDominio** [comment]
this pretty much is how it works
