### ISSUE TITLE
VVT minimum RPM

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4545]
VVT should have a minimum activation RPM, since at lower rpms (idle), targetting 0 could still result in the ECU slowly going crazy trying to control VVT position and outputting some duty when none is desired (Some car have a target of 0, slowly start misfiring, I set maximum duty to 0 and the misfire goes away).

**Comment by ElDominio** [comment]
Issue with this: 
![image](https://user-images.githubusercontent.com/5685108/194589225-f432ae45-284f-4578-b8e2-734dff9a8c01.png)

Max should be near 3k or so

**Comment by rusefillc** [comment]
@ElDominio please claridy

original description focuces on idle " minimum activation RPM, since at lower rpms (idle)"

3000 rpm seems quite high for idle, is this a separate use case or else?

**Comment by ElDominio** [comment]
Error says I can't set over 100rpm in picture

**Comment by rusefillc** [comment]
@ElDominio is there anything you want to share

![image](https://user-images.githubusercontent.com/48498823/194591981-da687d5f-d9b0-4f9c-adc8-a84fb8944709.png)

**Comment by ElDominio** [comment]
I have a dealer in China

**Comment by rusefillc** [comment]
fixed it's 3000 now
