### ISSUE TITLE
"Blip" with trigger error on several boards

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/rusefi#4552]
I have 3 reports of a "Blip" while driving.  The report is that the engine and tach die, then come back on if the car is in motion(restarts itself) but will die if not in motion.  This issue is started under NA6 due to the first one reporting the issue.  

Current reports-
NA6 firmware-- [rusEFI 2022.06.29.hellenNA6.1831869224]
NA8 96 firmware-- [rusEFI 2022.06.29.hellenNA8_96.4107948449]
NB1 firmware-- [rusEFI 2022.07.01.hellen-nb1.3773366088]

logs-
NA6- https://rusefi.com/online/view.php?log=952
96- https://rusefi.com/online/view.php?log=1004
nb1- incoming

![image](https://user-images.githubusercontent.com/82395131/187037403-0a9993e2-13b2-499a-acfc-3638262cfa6a.png)
![image](https://user-images.githubusercontent.com/82395131/187037430-9f8f8c68-83d7-4e98-9eea-aaa954539885.png)
![image](https://user-images.githubusercontent.com/82395131/187037442-7bc6ef62-f637-445b-9a5f-e3f7d743a8b9.png)
![image](https://user-images.githubusercontent.com/82395131/187037458-b70fa414-40bc-4846-8ad8-ee09e792955b.png)

**Comment by rusefillc** [comment]
Vaguely related to https://github.com/rusefi/rusefi/issues/4553

**Comment by BeerMoneyMotorsports** [comment]
i could not upload this file to REO but i think i had the issue at the end of this log.  ive been driving and logging all day.  it was at idle and just decided to shut off.  Not peter out and die, just cut off.  https://drive.google.com/file/d/1LgBXt_V72_rVc6iSb9b8lJ7vOliuQ3Fm/view?usp=sharing

**Comment by rusefillc** [comment]
@BeerMoneyMotorsports please clarify which of four kinds of log files is there

@BeerMoneyMotorsports would you be available to paste a screenshot focusing on the relevant portion of the log here showing RPM and trigger error counter? that kind of raw data processng / more clear description of what you have would help.

**Comment by rusefillc** [comment]
@mck1117 check this out we have a loss of second in time at the moment of trigger error

https://www.rusefi.com/online/view.php?log=1025 - note blue value jump from 662.6 to 663.6
![image](https://user-images.githubusercontent.com/48498823/189446642-2e68ce3a-fa51-47f3-a476-26fa08b3a217.png)

![image](https://user-images.githubusercontent.com/48498823/189446702-cf17e7ea-1dca-40b2-ad8d-7b6d46425b71.png)

**Comment by rusefillc** [comment]
Same in 1022

This is highly suspecious :)

**Comment by rusefillc** [comment]
Reminds us of #4554

**Comment by BeerMoneyMotorsports** [comment]
It is a Tuner Studio log.  I have been logging all day in an attempt to catch it.  On my car, both occurrences show no trigger error. They were both around idle and then the engine cuts off.  

<img width="749" alt="image" src="https://user-images.githubusercontent.com/82395131/189457364-f89064cb-ddf5-456b-b9f5-cbe0e8136de5.png">
 
another occurrence https://rusefi.com/online/view.php?log=1038

<img width="768" alt="image" src="https://user-images.githubusercontent.com/82395131/189457505-116b244c-2f96-48e0-adf5-8f3ce3cd80d5.png">

**Comment by BeerMoneyMotorsports** [comment]
@rusefillc both of mine have 1 second loss as well.

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi/issues/4557

**Comment by BeerMoneyMotorsports** [comment]
@rusefillc i had several instances tonight on a date with the wife.  below is one of them and they all show 1 second missing.  These were all with SD logging at 3ms.

<img width="774" alt="image" src="https://user-images.githubusercontent.com/82395131/189464144-fff6bf15-c3c0-42c5-ab7f-e1fc7725b441.png">

**Comment by rusefillc** [comment]
The whole 1s jump is exciting progress. Now that I was able to reproduce this on a bench twice we are getting closer to resolution. https://github.com/rusefi/rusefi/issues/4557

**Comment by BeerMoneyMotorsports** [comment]
@rusefillc i changed from 50ms to 3 ms on sd logging earlier. The issue happened far more frequently after that change.

**Comment by rusefillc** [comment]
See also https://github.com/rusefi/rusefi/issues/4560
