### ISSUE TITLE
randomly hanging for a complete second

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4557]
master has seconds watchdog behind special tempBooleanForVerySpecialLogic setting https://github.com/rusefi/rusefi/commit/8d770daca8fd628984a3a3c1c0a8ddb4ea3db8fe

I have F7 proteus with SD card hooked to power supply fatal im under 15 minutes
I have MRE without SD card survive 20 minutes

![image](https://user-images.githubusercontent.com/48498823/189460598-02db1125-e30a-4576-a418-6bd97b534618.png)

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/189462877-c02c815a-8236-4a66-9c92-cd94ea5cef6b.png)

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/189490620-1d229120-e0cd-47af-af3a-e6085bf8b6b9.png)

**Comment by rusefillc** [comment]
@mck1117 @dron0gus fun fact - MRE without SD card has survived the night

let me check with lower SD card period

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/189491531-17a4ee1d-bd7f-48f7-80fc-f5aac25ba815.png)

**Comment by rusefillc** [comment]
@racer-coder this _might_ be related to

```
struct WrapAround62 {
	uint64_t update(uint32_t source) {
		// Shift cannot be 31, as we wouldn't be able to tell if time is moving forward or
		// backward relative to m_upper.  We do need to handle both directions as our
		// "thread" can be racing with other "threads" in sampling stamp and updating
		// m_upper.
		constexpr unsigned shift = 30;

		uint32_t upper = m_upper;
		uint32_t relative_unsigned = source - (upper << shift);
		upper += int32_t(relative_unsigned) >> shift;
		m_upper = upper;

		// Yes we could just do upper<<shift, but then the result would span both halves of
		// the 64-bit result.  Doing it this way means we only operate on one half at a
		// time.  Source will supply those bits anyways, so we don't need them from
		// upper...
		return (efitick_t(upper >> (32 - shift)) << 32) | source;
	}
```

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/189491940-1fe0557a-0079-4be5-a4a0-db8aec8ebd4e.png)

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/189492298-a21c8bb7-1c1b-4337-a8bd-4a0b11a7293f.png)

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/189492468-f00477a0-f98d-4824-8cd5-4269426122d2.png)

**Comment by racer-coder** [comment]
Well that's interesting since I thought your tick clock was around 4MHz?

**Comment by dron0gus** [comment]
tempBooleanForVerySpecialLogic code do uint32_t (efitimems_t) to float conversion.
It can cause precision lose when crossing 24 bit boundary
https://stackoverflow.com/questions/68690961/why-does-converting-int-to-float-lose-precision-in-c-programming-language
Can we remove this conversion and re-run test? 
https://github.com/rusefi/rusefi/pull/4562

**Comment by rusefillc** [comment]
@dron0gus first time not 1100ms

![image](https://user-images.githubusercontent.com/48498823/189561998-02dd2485-6e25-4890-b70c-30518626e744.png)

**Comment by dron0gus** [comment]
Half night of running with https://github.com/rusefi/rusefi/pull/4567 on my HW.
![Screenshot from 2022-09-12 05-49-15](https://user-images.githubusercontent.com/28624689/189565130-b8444dcd-e7ab-4bf2-a790-c0a2eb316676.png)

**Comment by rusefillc** [comment]
2 out of (4 proteus and 1 mre) got affected in 8 hours

![image](https://user-images.githubusercontent.com/48498823/189643869-dd56733f-81bb-48ed-9275-54f21ba10384.png)

![image](https://user-images.githubusercontent.com/48498823/189644033-8a1460a2-f287-4aee-bece-755af8c47fa8.png)

**Comment by dron0gus** [comment]
@mck1117 
![Screenshot from 2022-09-13 22-31-31](https://user-images.githubusercontent.com/28624689/189992834-2363ac21-31a3-4443-bb2c-23fe9d89c887.png)
[2022-09-13_22.18.17.zip](https://github.com/rusefi/rusefi/files/9560247/2022-09-13_22.18.17.zip)

**Comment by mck1117** [comment]
Man 40ms is a long lock.

**Comment by rusefillc** [comment]
Last long lock I remember was engine sniffer or text output memory buffer copy

**Comment by rusefillc** [comment]
Also 40ms is more for #4570 but really not for 1125ms problem?

**Comment by mck1117** [comment]
That field can only store 65.535ms, so it could very well be 1125ms problem.

**Comment by rusefillc** [comment]
Fun fact: I have three units not fatal with tempBooleanForVerySpecialLogic for 24 hours

I reset those and all three get fatal within 3 hours

**Comment by mck1117** [comment]
Here are two logs that might be of interest. 

[blip.zip](https://github.com/rusefi/rusefi/files/9562672/blip.zip)

`re_31 scott.mlg` it from rusEFI proteus
`rc_15 scott.log` is from a racecapture connected over CAN

Have a look at 2007.52 seconds in the racecapture log. ECU data freezes for ~1.1 seconds.

In the rusEFI log, the same instant is 2010.97 seconds, where the log skips 1.148 seconds.

The ECU didn't blip (and time skip forward), the ECU hung for 1.1 seconds, then "snapped out of it" and went back to normal. The engine continued running for another hour without an issue.

**Comment by mck1117** [comment]
WE GOT ONEEEEEEEE

![image](https://user-images.githubusercontent.com/568254/190074902-64f38836-0497-429f-a2fd-f5f909a45b8f.png)

![image](https://user-images.githubusercontent.com/568254/190074581-e101b7e6-e6bd-4022-8050-af7e9c59e72e.png)

4580649 / 4e6 = 1.145 seconds

**Comment by mck1117** [comment]
Two while loops here without a timeout

![image](https://user-images.githubusercontent.com/568254/190076025-53fcc6ee-4676-472d-8a7e-b18f2d332bb5.png)

**Comment by mck1117** [comment]
Caught another one with some counters added to detect stuck loops.

Second loop (`STM32_RTC_HAS_SUBSECONDS`) takes 2 million iterations to complete.

![image](https://user-images.githubusercontent.com/568254/190077268-2ba42f34-b8ff-4941-986b-456c5e39c78a.png)

**Comment by mck1117** [comment]
@dron0gus what's your take? It looks like they're trying to exactly synchronize to a change of the subsecond counter. I don't understand why they're doing it under lock. That seems like a huge mistake in a real time system. Why do they not lock a mutex, synchronize clock, then unlock mutex?

**Comment by dron0gus** [comment]
@mck1117 I think there is logic problem.
`oldssr` should be update on each iteration. It should be inside `do {} while` loop.
We are good with `tr`, `dr`, `cr` reading if `oldssr` (that we sampled right before reading `tr`) is the same as after finishing reading this batch of registers.
Otherwise if `ssr` ticked while we were reading other register code will stuck until `ssr` makes wrap around.

**Comment by dron0gus** [comment]
Actually there are two modes of reading these RTC registers. Direct and shadowed. Shadow mode is used if `BYPSHAD != 1`.
By default `BYPSHAD` seems is cleared.
So there is no need do multiple reads and compare values.
![Screenshot from 2022-09-14 11-49-50](https://user-images.githubusercontent.com/28624689/190107961-341aa41b-6778-42b8-96e0-bb81a62672bb.png)
But this code seems implements all checks for both BYPSHAD = 0 and BYPSHAD = 1 mode.

**Comment by dron0gus** [comment]
Funny thing. This code was added as "fix" of some other bug.
https://sourceforge.net/p/chibios/bugs/1231/

```
commit 1a8ae11322a6ae870bc2299e80d410a8ba0dbe1e
Author: Giovanni Di Sirio <gdisirio@gmail.com>
Date:   Sat Apr 9 07:54:26 2022 +0000

    Fixed bug #1231.
    
    git-svn-id: svn://svn.code.sf.net/p/chibios/svn/branches/stable_20.3.x@15576 27425a3e-05d8-49a3-a47f-9c15f0e5edd8

diff --git a/os/hal/ports/STM32/LLD/RTCv2/hal_rtc_lld.c b/os/hal/ports/STM32/LLD/RTCv2/hal_rtc_lld.c
index 3c0632ce2..ebd10ddbe 100644
--- a/os/hal/ports/STM32/LLD/RTCv2/hal_rtc_lld.c
+++ b/os/hal/ports/STM32/LLD/RTCv2/hal_rtc_lld.c
@@ -637,7 +637,7 @@ void rtc_lld_get_time(RTCDriver *rtcp, RTCDateTime *timespec) {
   uint32_t dr, tr, cr;
   uint32_t subs;
 #if STM32_RTC_HAS_SUBSECONDS
-  uint32_t ssr;
+  uint32_t oldssr, ssr;^M
 #endif /* STM32_RTC_HAS_SUBSECONDS */
   syssts_t sts;
 
@@ -649,11 +649,17 @@ void rtc_lld_get_time(RTCDriver *rtcp, RTCDateTime *timespec) {
   while ((rtcp->rtc->ISR & RTC_ISR_RSF) == 0)
     ;
 #if STM32_RTC_HAS_SUBSECONDS
-  ssr = rtcp->rtc->SSR;
+  oldssr = rtcp->rtc->SSR;^M
+  do^M
+#endif /* STM32_RTC_HAS_SUBSECONDS */^M
+  {^M
+    tr  = rtcp->rtc->TR;^M
+    dr  = rtcp->rtc->DR;^M
+    cr  = rtcp->rtc->CR;^M
+  }^M
+#if STM32_RTC_HAS_SUBSECONDS^M
+  while (oldssr != (ssr = rtcp->rtc->SSR));^M
 #endif /* STM32_RTC_HAS_SUBSECONDS */
-  tr  = rtcp->rtc->TR;
-  dr  = rtcp->rtc->DR;
-  cr  = rtcp->rtc->CR;
   rtcp->rtc->ISR &= ~RTC_ISR_RSF;
 
   /* Leaving a reentrant critical zone.*/

```

**Comment by dron0gus** [comment]
While code initially suggested by user in https://forum.chibios.org/viewtopic.php?f=35&t=5949 thread is correct and ssr is readed inside the loop.

**Comment by dron0gus** [comment]
And yes, I see not reason to lock this code.

**Comment by rusefillc** [comment]
I've reported https://sourceforge.net/p/chibios/bugs/1234/

**Comment by rusefillc** [comment]
So we are affected since https://github.com/rusefi/ChibiOS/commit/eed346d57f80efd78bd4130c7088066a1169d495#diff-477173e15cc7667e590339b9db05629c3cce0aa7956b5baaecb2bff2adcdd155

**Comment by rusefillc** [comment]
@dron0gus @mck1117 see https://forum.chibios.org/viewtopic.php?f=35&t=5949&e=1&view=unread#p41462
