### ISSUE TITLE
Dron says self-stim errors are kind of same issue

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4570]
it's amazing to have smart people on board with rusEFI

@dron0gus says that 1200 RPM has a few trigger errors every hour and those trigger errors show shorter than #4557 time gaps

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi/commit/ac33561801fff26002d2cff76a6653ef35cc22b0 is hopefully relevant

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/189833233-605dcc27-bac0-424c-8c15-8d4020691ee1.png)

**Comment by mck1117** [comment]
@dron0gus how did you repro this? post exact tune?

**Comment by mck1117** [comment]
@dron0gus can you test again with #4578?

**Comment by rusefillc** [comment]
@dron0gus poke :)

**Comment by dron0gus** [comment]
8 hours with no trigger error. RPM = 6500.

**Comment by dron0gus** [comment]
After RTC read fix.
