### ISSUE TITLE
applyNonPersistentConfiguration twice

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#458]
andreika is asking about 

runRusEfi()
    --> readConfiguration()
        --> applyNonPersistentConfiguration()
            --> applyFsioConfiguration()
    --> initHardware()
        --> readFromFlash()
            --> readConfiguration()
                --> applyNonPersistentConfiguration()
                    --> applyFsioConfiguration()
    --> initEngineContoller()
        --> commonInitEngineController()
            --> initFsioImpl()

need to fix or to document :)

**Comment by mck1117** [comment]
I remember fixing this
