### ISSUE TITLE
bluetooth_jdy without BT hangs ECU

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4583]
invoke in console
```
bluetooth_jdy 115200 alphax 1234
```

actual result: blue LED stops blinking after BT init process

**Comment by rusefillc** [comment]
See #4588

TODO @rusefillc validate

**Comment by rusefillc** [comment]
@dron0gus i can still reproduce some issue

* take discovery definitely without BT
* in console launch ``bluetooth_jdy 115200 alphax 1234``
* after it goes through attempts blue LED stops blinking :(

**Comment by dron0gus** [comment]
Fixed? Close?
