### ISSUE TITLE
"angle range findAngle#a6" critical error

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4593]
error in screenshot

![Screenshot from 2022-09-19 17-34-41](https://user-images.githubusercontent.com/5685108/191123901-df63b107-7512-4e64-8a91-12b390e67de4.png)

**Comment by rusefillc** [comment]
a6 means "dwell" that's all I know so far :(

**Comment by mck1117** [comment]
-2147483647 is an interesting number

**Comment by rusefillc** [comment]
Warnings were improved, closing until this happens again with new warnings. Not actionable as is :(
