### ISSUE TITLE
K47 is Wasteagte, not K48

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4616]
![image](https://user-images.githubusercontent.com/5685108/191339832-bf4466fa-b048-4d9a-8bb9-e59cc978a62b.png)

K48 is blow off valve control, K47 is wastegate according to pinout

**Comment by ElDominio** [comment]
But can't I use K47 as an output?

**Comment by rusefillc** [comment]
@ElDominio just pushed K48 LS1
