### ISSUE TITLE
Firmware Update Error

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/rusefi#4626]
Unable to update firmware for Miata.  See errors below from NB1 and NA6.  I have deleted and reinstalled drivers with no success.  

**Console version 20220926
Windows 10.0
Bundle rusefi_bundle_hellen-nb1
Using selected COM10

Reboot command [reboot_dfu] sent into serial=COM10!

Giving time for USB enumeration...
Executing wmic path win32_pnpentity where "Caption like 'STM32 Bootloader'" get Caption,ConfigManagerErrorCode /format:list
No Instance(s) Available.

Done!

No Instance(s) Available.
*** DRIVER ERROR? *** Did you have a chance to try 'Install Drivers' button on top of rusEFI console start screen?**

<img width="554" alt="image" src="https://user-images.githubusercontent.com/82395131/192663462-ff5cb84e-71dd-4c8f-81bb-91b5b1555543.png">

**Comment by mck1117** [comment]
snip of device manager?

**Comment by BeerMoneyMotorsports** [comment]
<img width="254" alt="image" src="https://user-images.githubusercontent.com/82395131/192664083-ea87480d-aa62-4c0e-85aa-5ecb5b246fe6.png">

<img width="181" alt="image" src="https://user-images.githubusercontent.com/82395131/192664142-a8099bed-35b0-4695-b98f-cd978c92601c.png">

**Comment by BeerMoneyMotorsports** [comment]
Confirmed same issue on release for Hellen 121 Nissan.  STM cube programmer will connect while in DFU

<img width="890" alt="image" src="https://user-images.githubusercontent.com/82395131/192666074-967b3313-1dea-4d83-ba1d-d49ab59c3998.png">

**Comment by rusefillc** [comment]
I've only tested #4625 on Win7 so far

Could be that they request elevation now?

I will have access to hardware in 25 hours from now.

**Comment by BeerMoneyMotorsports** [comment]
Do you need any more data from my end?

**Comment by rusefillc** [comment]
No

Wow, on win11 they have two spaces not one.

![image](https://user-images.githubusercontent.com/48498823/193110930-3fd9220f-d18f-4c4a-a0b7-95c927f7286a.png)

**Comment by rusefillc** [comment]
Looks good with the fix

![image](https://user-images.githubusercontent.com/48498823/193127495-0c59a25e-2005-4149-a71c-83f77a73aad1.png)
