### ISSUE TITLE
Extremely noisy external MAP

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4644]
https://rusefi.com/online/view.php?log=1068

You can see MAP being VERY noisy in upper RPMs/MAPs, it is connected to the board directly, will follow up thread with pics

**Comment by rusefillc** [comment]
https://rusefi.com/online/view.php?msq=1251&dialog=mapCurves shows an only 5 degrees sampling window?

**Comment by ElDominio** [comment]
I tried from 5 to 100 and no change

**Comment by mck1117** [comment]
can you put an oscilloscope on the MAP sensor wire?

**Comment by ElDominio** [comment]
Will try to get that done, but just in case this happens under boost, normal dilly dally is pretty useable

**Comment by ElDominio** [comment]
Again idk probably went alphaN
