### ISSUE TITLE
MRE rev limit max 12500rpm 

### ISSUE THREAD

**Issue by OrchardPerformance** [rusefi/rusefi#4649]
Was bench testing something earlier and found the max "rpm hard limit" possible to set on an MRE is ~12500. 
Setting it to more has unpredictable results with the numbers in the box shortening to 4 digits (i.e. 1200 not 14000) 

Going to test some more but this may be a limit across all RE. 

Relevance here is motorcycle could be 14k to 15k rpm.

**Comment by OrchardPerformance** [comment]
Update - Tried MRE, Proteus and Frankenso and this exists on all of them. 
12000 is ok 
![image](https://user-images.githubusercontent.com/49926376/194779685-f9f762d0-bdfa-4e3c-b111-c22d30e412d2.png)

13000 changes to "200" 
![image](https://user-images.githubusercontent.com/49926376/194779695-32dfa523-8fd3-41bb-80a9-9712935b7cda.png)

14000 changes to "1200" 
![image](https://user-images.githubusercontent.com/49926376/194779707-9a57758c-daf1-4141-b8d0-cad65961975b.png)

Could this be a TS problem?

**Comment by OrchardPerformance** [comment]
Looks like 12799 is the highest the box takes. 
12800 turns into zero. 

Seems like 128 x10 is the highest the number goes before overflow? 
12799 = 12799
12800 = 0
12801 = 1
14000 = 1200

**Comment by rusefillc** [comment]
I see zero tune URLs

i see firmware version not being mentioned

I see https://github.com/rusefi/rusefi/pull/4300 being very relevant

**Comment by rusefillc** [comment]
I also see 19000 locally

overall I tend to blame operator not TS

![image](https://user-images.githubusercontent.com/48498823/194780315-6de68b70-5db7-493c-9cc1-066e745faff3.png)

**Comment by OrchardPerformance** [comment]
Version does not matter, I tried at least 7 versions going back as far as 2019. 

The problem exists on all versions where the RPM limit moved to the "limits and fallbacks" page. 

Tune totally irrelevant, see above. 

You can type any number you like, but soon as you press enter 19000 will change to 6200.

**Comment by mck1117** [comment]
@rusefillc read the issue please. He didn't say you can't type in 19000, he said that values above 12800 behave like x-12800, not that they can't be typed in. Smells like the config field is an int8_t and we're running out.

**Comment by rusefillc** [comment]
@mck1117 I appreciate your loyalty but in my opinion it's misplaced. Clearly emotional baggage is dragging us all down here but in this specific case I am still thinking that I am paying attention while you guys do not.

https://rusefi.com/online/view.php?msq=1256&dialog=limitsAndFallback

![image](https://user-images.githubusercontent.com/48498823/194781347-1b76b5c0-0f18-4bd3-a23e-d61a96778bb3.png)

**Comment by mck1117** [comment]
Then why didn't we start with the `git blame`? Looks like maybe old firmware here.

**Comment by OrchardPerformance** [comment]
Ok, so it's fixed but the issue DID exist. 

I will inform any users of exiting units with firmware that may not be the latest that this bug exists and can be fixed by updating. 

This ticket at least now exists to catalogue what was a bug and can be found by anyone that also encounters it.

**Comment by rusefillc** [comment]
Just a reminder that I've literally referenced #4300 fix

I am hoping for @OrchardPerformance to see signal here. Screenshots bad urls good maybe?

**Comment by mck1117** [comment]
there was even already an issue: #4298
