### ISSUE TITLE
LSB/MSB/offset/shift?

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4660]
```
BO_ 515 BASE3: 8 Vector__XXX
 SG_ MAP : 7|16@0+ (0.03,0) [0|0] "kPa" Vector__XXX
```

do we have a defect? start at 7 with size 16? Does is really describe data[0] and data[1]?

PS: Can we maybe add human-readable three line hint on how to read DBC? Just to educate me can you please help me understand 7,16 here?

**Comment by mck1117** [comment]
no humans should be trying to read a dbc, they're intended to be read by software

**Comment by rusefillc** [comment]
@mck1117 just updated description to separate defect report from readability suggestion

I do not agree on no humans reading DBC file. Least we can do is point to some (Free?) software which opens the file

**Comment by mck1117** [comment]
that looks like software, what is that software?

**Comment by rusefillc** [comment]
that is https://www.vector.com/us/en/products/products-a-z/software/candb/ which is the most official software assuming DBC is in fact owner by Vector? http://mcu.so/Microcontroller/Automotive/DBC_File_Format_Documentation.pdf

I am failing to change Startbit using that questionable software
