### ISSUE TITLE
We've lost Proteus HW CI

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4668]
proteus HW CI is broken

**Comment by rusefillc** [comment]
@mck1117 I've disabled for now https://github.com/rusefi/rusefi/commit/8fbe224f4004bdf29fdd60cecadd197ca94ebe10

**Comment by rusefillc** [comment]
@mck1117 poke

**Comment by mck1117** [comment]
actual supply voltage is 12.14 volts
measured voltage at vbatt sense pin is 1.32 volts (ratio 9.2, 1.32*9.2 = 12.144) so divider works OK

**Comment by mck1117** [comment]
oh it's #4628
