### ISSUE TITLE
Timing IAT Correction broken?

### ISSUE THREAD

**Issue by andreika-git** [rusefi/rusefi#467]
![iat_corr_log](https://user-images.githubusercontent.com/15104768/28967311-3f0144dc-7923-11e7-9e65-683e691098d3.PNG)
[2017-08-02_09.09.13.msl.zip](https://github.com/rusefi/rusefi/files/1200223/2017-08-02_09.09.13.msl.zip)
(Starting from 719 sec)

typedef Map3D<IGN_RPM_COUNT, IGN_LOAD_COUNT, float> ign_Map3D_t;
static ign_Map3D_t iatAdvanceCorrectionMap("iat corr");

iatAdvanceCorrectionMap.init(config->ignitionIatCorrTable, config->ignitionIatCorrLoadBins,
   config->ignitionIatCorrRpmBins);
iatCorrection = iatAdvanceCorrectionMap.getValue((float) rpm, engine->sensors.iat);

**Comment by mck1117** [comment]
I think this got fixed with #945

**Comment by mck1117** [comment]
this is fixed, we can close
