### ISSUE TITLE
configuration override in case of reading error

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#469]
Historically rusEfi would override configuration with defaults if configuration was not read successfully.

It's a very open question if that's the smartest reaction to a failed config read. What if failed config read was caused by low voltage or some EMI spike?

It's very unclear what's going on, but it's probably better strategy would be not to override the configuration with the defaults since these are not really useful for any real user

Open question: how to handle brand new stm32 chip? Should we assume that whole configuration is all zeros, and reset configuration only if all zeros?

**Comment by rusefi** [comment]
See also #341

**Comment by stefanst** [comment]
Agreed that overriding the whole configuration is not helpful. 
Is there sufficient memory to store two configs? If so, we could switch to backup-config.

**Comment by mck1117** [comment]
Backup config storage didn't actually work, but was fixed long ago.  Closing.
