### ISSUE TITLE
RPM not reading, test units 4chan and hellen154

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4706]
last known good FW was 20221018, recent updates have broken RPM reading on test cars with 4B11 and Hyundai Theta 60-2. Downgrading back to 20221018 fixes RPM reading. RusEFI console can see all teeth without problem but RPM never shows up on Tunerstudio/car doesn't run

**Comment by mck1117** [comment]
logs?

**Comment by mck1117** [comment]
![image](https://user-images.githubusercontent.com/568254/198411089-6023a0d7-fc88-4c3d-a5fc-3ba2f4db28ec.png)

**Comment by rusefillc** [comment]
It's past sunset here unfortunatelly and testing happens outside. No logs today unfortunatelly.

@mck1117 is it easy for you to update any vehicles in your visinity to latest?

**Comment by mck1117** [comment]
My car runs and drives on FW from 10/21, I can update the other one to snapshot and see what happens.

**Comment by mck1117** [comment]
no start on latest snapshot

**Comment by mck1117** [comment]
what's up with those zeroish dwell spark events?

![image](https://user-images.githubusercontent.com/568254/198418074-d4b7e6f8-bfc3-4366-b7c1-5073fe17ca1f.png)

**Comment by mck1117** [comment]
Trigger input DEBUG pins? What?

![image](https://user-images.githubusercontent.com/568254/198418741-7102921c-aac7-48e9-af4a-7440793c4399.png)

**Comment by rusefillc** [comment]
Introduced by #4691

thank you @mck1117 for finding root cause!
