### ISSUE TITLE
UI Suggestions for Tunerstudio

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4722]
Need separate ticket since need way more details ~~Create a "Tuning" or "Popular" tab with the basics like VE, main ignition, main AFR, accel enrich and idle~~

done?
~~Idle% adder for A/C should also be under "Air conditioning"
Fan adders should be under Fans
remove extra idle air and taper until they do something documented
Idle position is under "Sensors - Extra 1" instead of an "Idle" section, even though there's an IDLE PID section with everything but the actual output (for gauges)~~

I'm going to post a critique of each section individually so my brain doesn't fry

**Comment by ElDominio** [comment]
![image](https://user-images.githubusercontent.com/5685108/198941050-fb29b977-6bcb-42e2-8c9a-92bbc3aafb6c.png)


Order should be from most important to least, with folders always at the bottom for visual cohesion
Ignition settings
________________
Ignition Advance
Ign CLT correction
Ign IAT correction (important to indicate IGN even though this is the tab because human brains short circuit)
________________
Dwell
Ignition Blend tables (what is an adder bias?)
Per Cylinder Trims

**Comment by ElDominio** [comment]
Put Trigger Gap Override as a part of Advanced Trigger, it is literally an advanced trigger option
Why is CLT based RPM limit in its own section? imo make it a menu that enables if chosen in the limits category

All the small additional outputs should be clumped together in one or two "Outputs" section, no reason to have two clicks to set each output (more if you count burns every time)

**Comment by ElDominio** [comment]
![image](https://user-images.githubusercontent.com/5685108/198942120-e0b43635-d494-4206-b2a9-a52fe01943c5.png)


This one is a bit more involved, but I'd replace "Sensors" with "General I/O" and clump together inputs and puts (seperate with a horizontal lines for inputs and outputs) and keep Advanced for actual advanced functions, like traction control, launch control, flex fuel blending etc

![image](https://user-images.githubusercontent.com/5685108/198942531-e4bc154f-6a2b-4915-947c-46e1f73bba69.png)


Move I/O configuration to that tab, then tables that use that configuration (like VVT) live inside Advanced.

**Comment by dron0gus** [comment]
https://github.com/rusefi/rusefi/pull/4723

**Comment by ElDominio** [comment]
Another suggestion: remove deadzone on Closed Loop Ignition timing

**Comment by rusefillc** [comment]
@ElDominio @dron0gus are we 100% done or less than 100% done here? how do we track what else needs to be changed?

@ElDominio do you have time and motivation to create a new one for remaining stuff? any other approach?

**Comment by dron0gus** [comment]
@rusefillc suggestion from only two first messages are done.

**Comment by ElDominio** [comment]
I have thought a bit more, I think Advanced should eb changed to "Outputs"  and take out
-cylinder offsets (group under base engine)
-gear detection (should be under Sensors - Vehicle speed since it's directly dependant on this)
-Lua Analog Inputs (Should be under Sensors, since it's literally a sensor)
--or, yank out all Lua stuff from "Advanced" and put it under a folder in Controller called "LUA", since this is quite related to the controller itself and a very not-begginer-level capability.

-make View the last button or next to last button, the things here are used almost exclusively for debugging. In fact, this sould be a folder under Controller since the views there are all debug functions.

![image](https://user-images.githubusercontent.com/5685108/201544391-bf560216-be91-4ffd-aa9b-515266c8d56a.png)
o means output, i means input. Alternator and Battery should not be tied together.
Start Button should be renamed to Starter Control.

**Comment by rusefillc** [comment]
@ElDominio "how do we track what else needs to be changed?" was me trying to say "please stop piling all small separate changes into one ticket it's already impossible to figure out what was done and what still needs to be done"

It would be amazing to separate all things which would be separated while all things relevant together :) "starter control" and "CLT warm-up curve" would be examples of things which seem SEPARATE to me.

**Comment by rusefillc** [comment]
progress?

![image](https://user-images.githubusercontent.com/48498823/201549507-2021d8e0-b408-45c4-985b-80dbfbf0b18a.png)

![image](https://user-images.githubusercontent.com/48498823/201549515-cf577f25-3bc1-4028-8ac3-228b7fe12608.png)
