### ISSUE TITLE
target lambda & afr log fields broken - TS part

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#4727]
these fields are always 0 in both SD and TS logs

**Comment by mck1117** [comment]
We allow duplicate fields in output channels !?!?!?!?

![image](https://user-images.githubusercontent.com/568254/199569739-8f00cbba-a638-44d1-85b5-a2e5050fd893.png)

**Comment by dron0gus** [comment]
Similar to https://github.com/rusefi/rusefi/issues/4720

**Comment by rusefillc** [comment]
@mck1117 I've disallowed duplicate fields in output channels, I hope that would fix target lambda in TS logs

@mck1117 can you help with SD card logs? specifically my problem is around current requirement to generate very static reference

**Comment by BeerMoneyMotorsports** [comment]
related? https://github.com/rusefi/rusefi/issues/4826

**Comment by mck1117** [comment]
No, it's not SD, it's everywhere. It looks like now everything in `fuel_computer_s` is stuck at 0.

**Comment by rusefillc** [comment]
@BeerMoneyMotorsports yes does look pretty related

Just updated ticket title - the hope is that TS logs are working OK now but that was not really validated.

**Comment by rusefillc** [comment]
@mck1117 sounds like closing this one as well
