### ISSUE TITLE
Another suggestion: remove deadzone on Closed Loop Ignition timing

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4729]
Another suggestion: remove deadzone on Closed Loop Ignition timing

_Originally posted by @ElDominio in https://github.com/rusefi/rusefi/issues/4722#issuecomment-1301533797_

**Comment by rusefillc** [comment]
@ElDominio that's probably a separate enough issue if I understand you right that you want to completely remove a feature, not just _rearrange_ UI?

**Comment by ElDominio** [comment]
As you said, remove the thing completely, it is basically unnecessary

**Comment by rusefillc** [comment]
@ElDominio @mck1117 close this one?
