### ISSUE TITLE
Both fronts error? What?

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4743]
![image](https://user-images.githubusercontent.com/5685108/200186344-5b406b81-21b5-4303-a71b-08465e051e2d.png)

wut

**Comment by ElDominio** [comment]
BOTH EDGES is much more descriptive than both FRONTS

It was because i was using a trigger that requires BOTH EDGES while setting to only use Rising Edge, why is that option even possible

**Comment by mck1117** [comment]
this will go away with #4621
