### ISSUE TITLE
duty cycle preference for tachometer signal output

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#476]
Nikita needs a 50% duty cycle for his tachometer, we need to implement 'tachPulseDurationAsDutyCycle' setting

**Comment by OrchardPerformance** [comment]
Closing as this is in the current firmware and works (I use it) 

![image](https://user-images.githubusercontent.com/49926376/135775348-8b5be216-593b-4b5e-b64c-29744a421764.png)
