### ISSUE TITLE
RPM correction/multiplier for Accel Enrich

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4760]
add a 2D RPM correction table to transient enrich, to be able to lower the amount of enrich applied at upper RPMs (since engines in motion usually need much less enrichment). 

A table like this
![image](https://user-images.githubusercontent.com/5685108/200680532-52bacac1-8184-4040-bb16-5884351e7ad7.png)

maybe even with 4 cells is enough. 1.0 at 1000RPM, .9 at 3000rpm, .5 at 5000RPM, 0 at 7000RPM.

**Comment by mck1117** [comment]
how much time do you spend at 7k rpm while below 30c coolant?

**Comment by ElDominio** [comment]
no coolant just showed that to show what a 2D table looks like. Coolant would be replaced by RPM

**Comment by mck1117** [comment]
yes I understand the request - I'm asking why you think it's necessary

**Comment by ElDominio** [comment]
dding 3ms on a transient at 5.500rpm usually just makes an engine lug

**Comment by mck1117** [comment]
oh duh the snip of a random table confused me

**Comment by ElDominio** [comment]
![image](https://user-images.githubusercontent.com/5685108/200682229-971bfc52-5e52-4b8b-858a-3e2b62926a6e.png)

**Comment by ElDominio** [comment]
Also, a CLT-based correction on enrich (more enrich added when colder)  would also be good. Some ecus have a "Cold/Hot" temp, where the Hot temp is the normal, and the cold temp uses a multiplier.

Example:
Cold = 100F ; Multiplier = 1.3
Hot = 150F

(up to 100F, it uses 1.3 as a multiplier, then interpolates between 100F and 150F to become 1x multiplier.)

**Comment by ElDominio** [comment]
@mck1117 @rusefillc  any progress?

**Comment by rusefillc** [comment]
Some progress

![image](https://user-images.githubusercontent.com/48498823/207443969-9ad9da8b-bb99-4c1b-a18c-728d9ffe6c6c.png)
