### ISSUE TITLE
Add fuel adder to launch

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4777]
![image](https://user-images.githubusercontent.com/5685108/201544052-388c84c7-51a6-4a0b-bf08-b8c59b05b03b.png)

Usually fuel is added to cool exhaust charge when on launch control. A simple % should do

**Comment by rusefillc** [comment]
@ElDominio please give it a try when you have a chance

**Comment by TurboMarian** [comment]
@rusefillc For some reason it doesn't add any fuel when launch control is active

**Comment by mck1117** [comment]
@TurboMarian log and tune link?
