### ISSUE TITLE
Allow MAP as Open Loop Boost vertical axis

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4778]
I think boost control should have a few changes implemented.
First, open lood should have selcteable Y axis between TPS and MAP. Using MAP allows to do pseudo closed loop boost ( I KNOW IT IS NOT TRUE CLOSED LOOP) but allows for quick somewhat reliable results.

**Comment by ElDominio** [comment]
This is mee still wanting MAP as y axis

**Comment by rusefillc** [comment]
current state
![image](https://github.com/rusefi/rusefi/assets/48498823/62bf1591-f39b-42d1-b47c-955eb1de9ace)

**Comment by rusefillc** [comment]
boostControlOpenLookYAxis

@ElDominio would it be OK for us to make it much more flexibility not just TPS vs MAP?

![image](https://github.com/rusefi/rusefi/assets/48498823/d9c29931-98a6-42cb-a302-fd3b9c77a853)

**Comment by rusefillc** [comment]
kind of related to https://github.com/rusefi/rusefi/pull/6480

**Comment by ElDominio** [comment]
Sure

**Comment by kifir23917** [comment]
```
	expected<float> xAxisValue = readGppwmChannel(m_config->rpmAxis);
	expected<float> yAxisValue = readGppwmChannel(m_config->loadAxis);
```

**Comment by kifir23917** [comment]
- Zero
- TPS -> % 
- MAP KPa
- CLT C
- IAT C
- Fuel Load ?
- Ignition Load ?
- Aux Temp 1 C

**Comment by kifir23917** [comment]
![Screenshot - Boost control open loop](https://github.com/rusefi/rusefi/assets/159958110/28c94fa3-4bbc-4bb0-a32e-64fa4dd750ba)

Am I correct that we do not want to update numbers on Y axis depending on the value selected in Y Axis drop-down list?

**Comment by rusefillc** [comment]
> Am I correct that we do not want to update numbers on Y axis depending on the value selected in `Y Axis` drop-down list?

correct, touching the axis values is out of scope.

**Comment by mck1117** [comment]
JFYI if you put MAP on the Y axis, it turns it in to a second closed loop table. It's by definition not open loop if you do that.

**Comment by ElDominio** [comment]
I know; it's not PID but it does work oaky for most quarter mile applications, and definitely easier to explain to people. True closed loop is better but it's sometimes not what I need in the moment

**Comment by rusefillc** [comment]
see also #5027
