### ISSUE TITLE
Organize Lua front end stuff in seperate folder

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4781]
yank out all Lua stuff from "Advanced" and put it under a folder in Controller called "LUA", since this is quite related to the controller itself and a very not-begginer-level capability.

![image](https://user-images.githubusercontent.com/5685108/201559154-fee4ab1a-760e-45b2-a855-df315045b5a4.png)

**Comment by rusefillc** [comment]
@ElDominio good enough?

![image](https://user-images.githubusercontent.com/48498823/202889768-68d6cb3a-d8f2-4c8d-af88-bb7e2d400d20.png)

**Comment by ElDominio** [comment]
Yeah close this much neater now
