### ISSUE TITLE
Gear Detection menu option move

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4783]
![image](https://user-images.githubusercontent.com/5685108/201559482-43362562-5d42-42c7-ac7a-a3c6e239be0c.png)

![image](https://user-images.githubusercontent.com/5685108/201559467-6d082634-79c5-4013-a841-05c2b79cd9ea.png)

less clicks for related stuff

**Comment by rusefillc** [comment]
I think I've attempted doing that under https://github.com/rusefi/rusefi/commit/9588c36d59ffd71748892cf1d771c018664b0d4f already let me double-check tomorrow

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/202887080-62bff830-6176-4480-867a-f3ed43f09ebb.png)
