### ISSUE TITLE
Error in can_dash.cpp

### ISSUE THREAD

**Issue by chaoschris** [rusefi/rusefi#4786]
can_dash.cpp Line 721

tmp =  (uint16_t)(Sensor::getOrZero(SensorType::Lambda1)) * 1000;

should be:

tmp =  (uint16_t)(Sensor::getOrZero(SensorType::Lambda1)) * 1000);

**Comment by rusefillc** [comment]
@chaoschris are you http://www.bylund-automotive.com/?

Is where a build thread for this setup anywhere or on the rusEFI forum?

**Comment by chaoschris** [comment]
@rusefillc nope, i am one of the guys behind https://github.com/oelprinz-org/
