### ISSUE TITLE
simulator does not compile on latest ubuntu

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4791]
Did GHA just upgrade GCC? No? What's going on? why is build red?

https://github.com/rusefi/rusefi/actions/runs/3493929725/attempts/1
![image](https://user-images.githubusercontent.com/48498823/202613841-218a1f11-29ee-4c3f-9ff0-43a7e3f215ea.png)

previous build

![image](https://user-images.githubusercontent.com/48498823/202613634-1a5165a9-b455-4133-a541-a3bb92fbed58.png)

![image](https://user-images.githubusercontent.com/48498823/202613697-83244136-646c-47a7-b695-06b70512cbc5.png)

**Comment by nmschulte** [comment]
FYI, `master` (717a51095c67964b99fdc828c650c7e463cd162b) fails to build w/ GCC 12:
```
Compiling hal_can_lld.cpp
simulator/can/hal_can_lld.cpp: In function ‘void can_lld_stop(CANDriver*)’:
simulator/can/hal_can_lld.cpp:143:14: error: ‘remove’ is not a member of ‘std’; did you mean ‘move’?
  143 |         std::remove(instances.begin(), instances.end(), canp);
      |              ^~~~~~
      |              move
make: *** [../firmware/ChibiOS/os/common/startup/SIMIA32/compilers/GCC/rules.mk:130: build/obj/hal_can_lld.o] Error 1
Simulator compilation failed
```

**Comment by rusefillc** [comment]
@nmschulte that's separate from current github action, right?

**Comment by nmschulte** [comment]
Yep, just trying to reproduce locally to diagnose -- working through GCC 9 and 11 now.

**Comment by nmschulte** [comment]
I am able to build successfully with GCC 9, GCC 10, and GCC 11, and GCC 12 fails due to a different issue (`std::remove` is removed w/ the `-std=c++2a` option, I guess; maybe this can be more specific value if so).

However, I had to alter the Makefile to do so on my system, as it expects `gcc` and `g++` to be the correct binaries, ignoring any specified `CC`/`CXX`/`CPP`/`LD`, which I suppose is bad form.  No idea what's changed about the build env. except that `ubuntu-latest` must have changed which GCC is "default."

**Comment by rusefillc** [comment]
@chuckwagoncomputing any idea where would GHA announce planned changes/changelog? At the moment we have no idea what's going on, bug or feature :(

**Comment by nmschulte** [comment]
Note that the failing build is firmware, not simulator.

**Comment by rusefillc** [comment]
@nmschulte huh? on github it says simulator fails?

![image](https://user-images.githubusercontent.com/48498823/202639165-16a56e00-2748-4518-b02b-3839f76cba04.png)

**Comment by mck1117** [comment]
In GHA do we specify explicit ubuntu version, or latest? we can try specifying previous version for now

**Comment by nmschulte** [comment]
`ubuntu-latest` is specified, and between the two simulator runs it seems to have changed from `20.04` to `22.04`; I'll put up a PR about this after testing.

**Comment by nmschulte** [comment]
https://github.blog/changelog/2022-11-09-github-actions-ubuntu-latest-workflows-will-use-ubuntu-22-04/

**Comment by rusefillc** [comment]
@nmschulte so https://github.com/rusefi/rusefi/pull/4793 would be a work-around right?

Do we know root cause, what's special about latest ubuntu?

**Comment by nmschulte** [comment]
Yes, #4793 should resolve the problem from what I've gathered and tested.

I still don't understand exactly what's off, but it seems the GHA `ubuntu-latest` change that seems to have landed; the only notable difference so far is that 22.04 has GCC 11 installed.  My tests w/ Docker and this version of Ubuntu haven't yet turned up anything useful.

**Comment by nmschulte** [comment]
Alright, I was able to reproduce this issue finally.  The key is that the _Firmware at GHA_ workflow builds simulator with `OS="Windows_NT"`: MinGW.  This succeeds on Ubuntu 20.04, but not Ubuntu 22.04.  Building with GCC on Linux seems to not suffer at all.

**Comment by chuckwagoncomputing** [comment]
That's so a binary is created that people can run on Windows.

**Comment by rusefillc** [comment]
So OS="Windows_NT" is a functional requirement

and the second fun fact: more than once we saw Windows GCC settings being different from unix gcc behavior

**Comment by nmschulte** [comment]
Yep; I was able to recreate the issue w/ the MinGW GCC 11 (triggered by that env var); I didn't test the changes at all though, just that the build succeeded.  It's interesting that only MinGW exposed the linker issues, though: not sure what's different about the incantation / configuration of MinGW vs regular GCC, or what changed between MinGW GCC 9 vs MinGW GCC 11.

rusEFI could use more unit and integration tests -- maybe good to throw a fuzzer and [memory] safety analyzer at it too (e.g. Valgrind)

**Comment by rusefillc** [comment]
@nmschulte https://github.com/rusefi/rusefi/blob/a14345aaac72304c9f7068173a5e470fd4704f30/.github/workflows/build-unit-tests.yaml#L70

**Comment by mck1117** [comment]
we also run unit tests & simulator with asan enabled - it's detected plenty of real bugs
