### ISSUE TITLE
Boost is it actually "open+closed"?

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4803]
https://rusefi.com/forum/viewtopic.php?p=45745#p45745 makes me wonder if we have an issue with option name

boost control mode does not say "open + closed"

![image](https://user-images.githubusercontent.com/48498823/202886303-eca4dddb-8a74-4e8b-a332-3b46f15b9515.png)

like for instance idle control says

![image](https://user-images.githubusercontent.com/48498823/202886312-146b4e92-1ef1-41b6-996c-b0bde82a32ed.png)

So is the forum wrong or is the mode name wrong?

**Comment by mck1117** [comment]
Agree, boost should be "open + closed" like idle

**Comment by rusefillc** [comment]
@ElDominio FYI

no logic change here, only UI mode name correction

**Comment by ElDominio** [comment]
Just saw, open loop boost duty is used as base then PID is applied on top? That's perfect.

Now, the base duty table should use target KPA on the Y axis 

a.k.a. for 150kpa you need 20% duty
for 180 kpa you need 27% duty
etc

**Comment by mck1117** [comment]
> Now, the base duty table should use target KPA on the Y axis

Ehhhh. That also depends on throttle position. My car will make 200 kpa at both 60% throttle or 100% throttle, but it needs much more gate duty at 60%, so there isn't a clear mapping between gate duty and resulting MAP.

**Comment by ElDominio** [comment]
I'm just saying because this is pretty much standard practice on most aftermarket ECU's i've worked with

![image](https://user-images.githubusercontent.com/5685108/202912890-85ddf6ab-687d-4c7b-aecc-959a65388ada.png)
![image](https://user-images.githubusercontent.com/5685108/202912935-2c5b7368-9e45-45b3-9b64-d82abd73f523.png)
