### ISSUE TITLE
Proteus and 4chan fail to auto-calibrate specific VAG ETB

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4816]
4chan rev D with JLC assembled TLE9201
start with default tune - ETB is oscillating trying to shut down or something? PCB lights are cycling, looks like some sort of shutdown of either 6A questionable wall power supply or TLE9201 protection? Same questionable wall power supply is happy to drive a much larger Ford SENT ETB - log of oscillation https://rusefi.com/online/view.php?log=1101

Now pressing "auto calibrate" getting un unhappy TPS calibration https://rusefi.com/online/view.php?msq=1310 log https://rusefi.com/online/view.php?log=1102

![image](https://user-images.githubusercontent.com/48498823/203099642-c0eb763f-5fc8-4146-8597-4268dfc3f7be.png)

![image](https://user-images.githubusercontent.com/48498823/203098337-d5af29cb-e2d8-4bed-b010-5f153d759f20.png)

**Comment by rusefillc** [comment]
Oh and ETB does open completely during auto-calibration

also I have at least two units of same kind, here's another piece

![image](https://user-images.githubusercontent.com/48498823/203100800-e5ab8d39-7317-4174-8dfc-260bf3dc9d39.png)

**Comment by mck1117** [comment]
I think video would be handy here

**Comment by rusefillc** [comment]
@mck1117 https://youtu.be/Pwmy6Y5feR4

**Comment by rusefillc** [comment]
Same exact behavior with Proteus

**Comment by mck1117** [comment]
Do you have a TS log? We should be logging the raw voltage.

**Comment by mck1117** [comment]
> weird not inverted TPS calibration here? with a 4 wire TPS it's not like I could wire things in a wring way?

“not inverted” is pretty normal, lots of throttles have both signals with the same sign but different slope magnitude and offset.

**Comment by rusefillc** [comment]
> Do you have a TS log? We should be logging the raw voltage.

Two 4chan logs linked all the way on top, do you mean Proteus logs? I sure can grab those but behavior is 200% the same exact.

**Comment by rusefillc** [comment]
This issue here is a combination of #4832 and shitty power supply where power supply was shutting down before TLE9201 would overload.
![ps-bad](https://user-images.githubusercontent.com/48498823/204117293-f563df9c-4ad8-4af0-bc4a-a471970653f4.jpeg)

![ps-seems-ok](https://user-images.githubusercontent.com/48498823/204117294-f25826b8-d125-4a5d-b571-9a1e158b2164.jpeg)

@mck1117 feel free to close unless you have ideas for improvements?

**Comment by mck1117** [comment]
One suggestion for the humans (not the code) is to bench test things like this with a small lead acid battery in parallel with your PSU while testing. For example set PSU to 13v, max current limit, with lead acid in parallel. The PSU will keep the battery fully charged, and the battery will supply the big current peaks necessary for ETB stuff when the PSU can't keep up/supply enough. I think I used one of the alarm/UPS style batteries like this: https://www.amazon.com/ExpertPower-EXP1270-Rechargeable-Lead-Battery/dp/B003S1RQ2S

**Comment by rusefillc** [comment]
> One suggestion for the humans (not the code) is to bench test things like this with a small lead acid battery 

thank you, ordered!
