### ISSUE TITLE
Launch control UI suggestions

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4819]
First off, why is Launch Control not in Advanced, and it is in Controller? I think it's much more welcome inside Advanced

![image](https://user-images.githubusercontent.com/5685108/203372336-dd20edab-5da6-414f-80e1-4a6c74fd8400.png)

Other doubts/issues here
![image](https://user-images.githubusercontent.com/5685108/203374215-9032d343-968d-4325-8aa9-537c4fc49d61.png)

**Comment by rusefillc** [comment]
"Adder" word is there for a reason - without "Adder" we had users use 3800 and 3800 in both fields instead of 3800 and 0
