### ISSUE TITLE
Nissan: probably hardware issue but maybe we need firmware progress as well

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4821]
rawPPS primary and secondary show different level of noise

q: do we want software to respond in any different way or just should address relevant RC filter?

![image](https://user-images.githubusercontent.com/48498823/203453357-f1133a70-9f2f-442c-991a-18dcfa3c4978.png)

relevant log https://rusefi.com/forum/viewtopic.php?p=46624#p46624

**Comment by Qwerty-OFF** [comment]
Not same
![image](https://user-images.githubusercontent.com/4116383/203491233-5a66d4a3-052a-4f1b-a63a-b57e17bd52ee.png)

**Comment by mck1117** [comment]
> want software to respond in any different way

https://en.wikipedia.org/wiki/Nyquist%E2%80%93Shannon_sampling_theorem Says software cannot help us, and we MUST fix the hardware.

**Comment by rusefillc** [comment]
many 350z are happy, closing
