### ISSUE TITLE
VE Blend tables is an ignition adder?

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4823]
![image](https://user-images.githubusercontent.com/5685108/203498341-b9f0ab75-852e-46a6-ac3c-01c2ecb232e7.png)

Can I add VE or Ignition here? If it is ignition, why is it under VE?
If it's VE, why can i write negative numbers?

![image](https://user-images.githubusercontent.com/5685108/203498598-3c00e1db-81ae-4467-aa7b-8a6c00272e50.png)

I  suppose "bias" is voltage and "param" is how much the blend table is blended to main table? if so, "voltage" and "blend factor" is a better name to use

**Comment by mck1117** [comment]
First bit is probably a typo if it in fact opens a dialog that then says VE. 

You can put negative values in the table because maybe whatever you’re doing makes the engine less efficient: suppose it’s VVT, so in part of the operating range it removes VE, and part it adds.

**Comment by ElDominio** [comment]
I'm an idiot lol
