### ISSUE TITLE
Toyota 36-2 with 4-1 cam trigger problems

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4825]
Car runs fine semi-sequentially, but once cam is activated RPM's go crazy.

![image](https://user-images.githubusercontent.com/5685108/204018339-e82cf38e-c3ab-4e9f-8794-393ae6e711ad.png)

Sorry for low speed logging the car is in the other side of the island and i'm waiting for my shop, once I have it i'll try to get the car in person

https://rusefi.com/online/view.php?log=1110

**Comment by mck1117** [comment]
will take a look once back in the country, if you can grab a logic analyzer trace once the car is nearby that would be super helpful

**Comment by ElDominio** [comment]
i'll try to get a scope as soon as i get the new shop

**Comment by rusefillc** [comment]
> the new shop

Shall we all it "Maserati shop"?

**Comment by ElDominio** [comment]
[displaylogictrue 36minus2.zip](https://github.com/rusefi/rusefi/files/10377190/displaylogictrue.36minus2.zip)

crank to run
36-2, crank not inverted, cam inverted

setting crank to inverted causes issues while starting, but there seems to be an extra tooth in trigger logger. setting to crank invert to TRUE after start gets rid of the extra tooth

VVT position going crazy

**Comment by ElDominio** [comment]
Connected jumper cable between sensor ground and VR-

Signal is significantly cleaner, but not very reliable.
Scopes of this at 
[bridgeoscope.zip](https://github.com/rusefi/rusefi/files/10414013/bridgeoscope.zip)

We will remove this bridge and run a seperate CMP+/- wire tor esolve issues, but I think VVT errors were due to sharing the VR

Also, noticed I duplicated this issue #4930

**Comment by ElDominio** [comment]
definitely not RusEFI's fault. i hate VR sensors sometimes
