### ISSUE TITLE
ETB duty cycle jitter: only monitoring within this ticket

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4833]
I assume that ETB Duty cycle jitter above certain threshold is an indicator of an error

Open question when exactly can we reliably detect it how, maybe at least StdDev for X of last updates at least while engine is not running?

~~Open question how to respond to such condition - response is out of scope~~

**Comment by rusefillc** [comment]
Kind of related to #1336 @mck1117 ?

**Comment by mck1117** [comment]
Possibly related yes - I have some controls systems friends to ask for ideas here, a simple threshold isn’t going to work.

**Comment by rusefillc** [comment]
Status update: plan to add a couple of ExpAverages and call it a day
