### ISSUE TITLE
Working disconnect button in Console

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4862]
Put a disconnect/connect button in Console so we can switch between Tunerstudio and Console without having to reopen console every time.

**Comment by mck1117** [comment]
why not close it

**Comment by ElDominio** [comment]
Closing it means having to open, connect every time (about 15 seconds)

A disconnect button keeps the program open and ready to just connect, we save one click and a few alt tabs of having to go to Explorer to click it

**Comment by rusefillc** [comment]
#220 is technically kind of close
also "about 15 seconds" was recently improved a bit

Not saying that "disconnect" is not an option - just saying that it's a pile of small improvements and root cause is the fucking "switch between console and TS back and forth" :(

**Comment by ElDominio** [comment]
please; switching between console and TS for writing Lua scripts is very aggravating

**Comment by ElDominio** [comment]
please this is so bad when writing stuff
