### ISSUE TITLE
Get ETB target position in Lua

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4864]
Can there be a sensor type for this? Basically add TagetTPS (before lua adders) to this https://github.com/rusefi/rusefi/blob/master/firmware/controllers/sensors/sensor_type.h

So i can do throttle manipulation based on the target throttle position from the table itself

**Comment by mck1117** [comment]
do you want the unadjusted number, or the number after lua adjustment?

**Comment by ElDominio** [comment]
before, so it doesn't cause weird feedback loops lol (lua adds, then grab modified, adds again, keeps adding forever)

**Comment by mck1117** [comment]
> before, so it doesn't cause weird feedback loops

That's what I thought, but I figured I'd ask anyway 🙂

**Comment by rusefillc** [comment]
@ElDominio thank you for your interest in advanced rusEFI Lua

Here is what I think is the best way to do it: https://github.com/rusefi/rusefi/wiki/Lua-Scripting#getoutputname

Step 1: make sure that you see a live data point matching your desire, create a ticket to add a live data point

Step 2: we need https://github.com/rusefi/rusefi/issues/4867 and https://github.com/rusefi/rusefi/issues/4866

Step 3: @ElDominio make a video explaining all this magic Live Data including! https://github.com/rusefi/rusefi_documentation/issues/258

Bonus point: https://github.com/rusefi/rusefi/issues/4868

**Comment by ElDominio** [comment]
idk i probably figured out a way to do what i wanted without this
