### ISSUE TITLE
URGENT: mono-injection support

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#487]
At the moment rusEfi assumes that each cylinder has it's individual injector

we need to add support for single injector ASAP

**Comment by rusefi** [comment]
IM_SINGLE_POINT

**Comment by rusefi** [comment]
A problem is that historically some calculations were done on a per-cylinder basis. A proper change would be to convert everything to per-engine basis and only divide amounts by the number of cylinders if needed

**Comment by mck1117** [comment]
A temporary hack that works is to set the displacement wrong so that the math is done for each cylinder having the displacement of the whole engine.  For example, a 2 liter with a single 800cc injector would be entered as an 8 liter with 800cc injectors, then only plug in a single injector channel.
