### ISSUE TITLE
2JZ 12+1 Trigger issues while higher RPM

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4874]
https://rusefi.com/online/view.php?log=1114

In this log, you can see syncgapratio is very erratic while starting, while it is close to 1 when running (no missing tooth)

What is this due to? this makes the car very hard to start.

https://rusefi.com/online/view.php?log=1115

In this log, it never started and the RPM was always reading incorrectly.

**Comment by ElDominio** [comment]
https://rusefi.com/online/view.php?log=1118 sync loss at upper RPM

**Comment by mck1117** [comment]
why is the VR threshold so high?

![image](https://user-images.githubusercontent.com/568254/205995044-cb04ce44-8046-469f-80c2-17786dafe641.png)

**Comment by ElDominio** [comment]
I set it to 1 and it still has problems, I scoped it and the voltage was easily over 1.5v in idle;

Can voltage go DOWN with RPM?

**Comment by mck1117** [comment]
There is an analog filter that will reduce amplitude somewhat with RPM, but it shouldn't do a whole lot.

I'd try setting it to 0.3v or something (or slightly more than the minimum required to avoid trigger errors at idle) and see what happens.

**Comment by rusefillc** [comment]
@mck1117 do we need a ticket to actually implement the ADC3 analog_input logic?

**Comment by mck1117** [comment]
> @mck1117 do we need a ticket to actually implement the ADC3 analog_input logic?

#4876

**Comment by mck1117** [comment]
analog trigger pattern looks very good

![image](https://user-images.githubusercontent.com/568254/206797583-d3b2c156-c613-44db-b1d7-ed26c64595c5.png)

**Comment by mck1117** [comment]
@ElDominio is going to try and get digital logic analyzer of cam+crank inputs to ECU when back home

**Comment by mck1117** [comment]
onboard trigger scope says both crank+cam should be set "invert = true"

![image](https://user-images.githubusercontent.com/568254/207466963-be29c486-f47a-41e0-958b-ef6fc7b5f34a.png)

**Comment by rusefillc** [comment]
@ElDominio did https://github.com/rusefi/alphax-4chan/issues/85 help? Can we test with improved hardware?

**Comment by ElDominio** [comment]
god I hate VR part 3. Probably fixed with better conditioning
