### ISSUE TITLE
2-Chan BT Name has changed

### ISSUE THREAD

**Issue by Timbelom** [rusefi/rusefi#4875]
I have updated 2 chan board with fresh bundle.
I have executed same command as before.

``bluetooth_jdy 115200 alphax 1234``

previously endpoint name was "alphax", currently "alphax-BLE"

**Comment by dron0gus** [comment]
This is feature
https://github.com/rusefi/rusefi/blob/master/firmware/console/binary/bluetooth.cpp#L209
Current FW will set 'alphax' name for SSP and 'alphax-BLE' for BLE mode for JDY33.
I suspect lower passthrough in BLE mode, so I'd like to see wich mode is used.
![Screenshot from 2022-12-07 13-03-47](https://user-images.githubusercontent.com/28624689/206149129-912b92d0-a349-45b0-b615-1713e09e63db.png)
