### ISSUE TITLE
Toyota ETCS-i APS (ETB APP) [and TPS]

### ISSUE THREAD

**Issue by nmschulte** [rusefi/rusefi#4896]
_First, according to the documentation and references, this [APS] situation isn't intended in normal/stock operation, so this issue serves at the moment to simply document the situation: manual actuation on the bench, beyond the designed/intended [APS] ranges.  **However, intended/typical TPS suffers similarly!**  Notes about ETCS-i magnetic clutch included for completion._

Toyota's ETCS-i (ETB) APS (APP) outputs behave similarly to some (e.g. certain Ford; https://github.com/rusefi/rusefi/blob/master/firmware/controllers/sensors/redundant_ford_tps.cpp) TPS outputs: one signal reaches max before the other when actuated across the entire range.  In this [bench] situation, the VPA2 (redundant/secondary APP) signal reaches max (~5V) before VPA (primary APP).  This causes rusEFI to signal an error (again, when using the full mapping/range, on the bench).

Additionally, the ETCS-i's TPS output (VTA1 and VTA2) behaves similarly, though this is a typical situation.  This would be ideal to support via rusEFI.

![image](https://user-images.githubusercontent.com/8540239/207802265-06c93316-4f59-44e2-962d-2d186f1285c7.png)
_(image via https://alflash.com.ua/ETCS.htm)_

I will check soon (<24hr hopefully) the APS output ranges in-vehicle, though the documentation notes the typical/allowable range.  Ideally rusEFI would like to support this situation as well.

----
_APS (from Lexus IS300 FSM, DI-297, DI-299)_
![image](https://user-images.githubusercontent.com/8540239/207802852-12c407a7-631f-497d-b85c-71148ee69bad.png)
![image](https://user-images.githubusercontent.com/8540239/207805255-e53e23ae-b589-46ef-876b-9a2a4acf5b15.png)

_TPS (from Lexus IS300 FSM, DI-96, DI-99)_
![image](https://user-images.githubusercontent.com/8540239/207803056-f681875e-e120-4c8e-8879-cc6f2d25f844.png)
![image](https://user-images.githubusercontent.com/8540239/207805009-4bb80a6e-1f55-4dfc-b1a4-0917c139256b.png)

----

Finally, relatedly, ETCS-i has also a magnetic clutch [dis]engaging the control motor, operated via the ECM.  The ECM pulses the circuit to avoid excess power consumption, affording ~0.9 A (from main/12V it seems).

_Magnetic Clutch Circuit (from Lexus IS300 FSM, DI-280, DI-284)_
![image](https://user-images.githubusercontent.com/8540239/207806454-75ab97ea-5682-4f0c-8861-a4810d1446be.png)
![image](https://user-images.githubusercontent.com/8540239/207806567-0f773a43-7502-4ec3-8649-75e591b1b419.png)

----

_Proteus 0.6 - rusEFI 2022.12.08.proteus_f7.snap_1513_

**Comment by mck1117** [comment]
Here's a log with raw voltages of "actuated via "hand pedal" until stop, then opened the plate by hand, fluttered it a bit, released back to stop, and then released "hand pedal" to closed"

[2022-12-15_02.11.02.mlg.zip](https://github.com/rusefi/rusefi/files/10240017/2022-12-15_02.11.02.mlg.zip)

**Comment by mck1117** [comment]
I believe @nmschulte is going to try and reproduce that log with a real throttle cable/pedal/car soon, as that log was taken on the bench, possibly actuating the PPS further than is possible in the real car.

**Comment by mck1117** [comment]
![image](https://user-images.githubusercontent.com/568254/208296361-b4cfd3a6-5510-473c-837d-57c2d5378cce.png)
