### ISSUE TITLE
Aux per-cycle output

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#490]
We need two auxilary digital on/off outputs which would open once per each 360 degrees of engine crank revolution

The valve open angle position should be defined by a 16-point curve by TPS, close valve angle position should be defined by another 16-point curve by TPS

See https://github.com/rusefi/rusefi/blob/master/firmware/controllers/trigger/aux_valves.cpp

**Comment by mck1117** [comment]
What's this for?

**Comment by rusefi** [comment]
@mck1117 have a sponsor for this feature, not sure what is the exact purpose

**Comment by rusefi** [comment]
AUX_DIGITAL_VALVE_COUNT

**Comment by rusefi** [comment]
depends on #495

**Comment by rusefi** [comment]
set mock_tps_voltage 1

**Comment by rusefi** [comment]
Looks good ![image](https://user-images.githubusercontent.com/7377949/33300113-ac1705a4-d3bc-11e7-8a45-2985fb99781e.png)
