### ISSUE TITLE
1NZ Trigger problems (36-2/4-1)

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4901]
https://rusefi.com/online/view.php?log=1126

when Cam sync is enabled, VVT1 angle goes crazy. Soon will have SD card trigger logs

**Comment by mck1117** [comment]
is this hall sensors or VR sensors?

**Comment by ElDominio** [comment]
VR since Toyota

**Comment by mck1117** [comment]
duplicate of #4930?

**Comment by ElDominio** [comment]
Correct but all data is here mistakenly, why are both closed now?
