### ISSUE TITLE
virtual MSD with .ini in fork

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4915]
@TurboMarian is wondering how to get MSD with .ini working on https://github.com/TurboMarian/rusefi custom boards

**Comment by mck1117** [comment]
just generate config and it works?

**Comment by rusefillc** [comment]
Let's see how https://github.com/rusefi/rusefi/commit/dd6b3de294fd3ef065e1b90cd2f0b99580c9d972 goes

**Comment by rusefillc** [comment]
@TurboMarian note how https://github.com/rusefi/rusefi/commit/20e0f6c3468e069b82383e6a4e1a104c240f4427 adds .ini files based on https://github.com/rusefi/rusefi/commit/dd6b3de294fd3ef065e1b90cd2f0b99580c9d972 I believe that's what you are missing on your branch

**Comment by TurboMarian** [comment]
Thank you guys. I done that but still virtual drive is blank (disk 2). Disk 3 is SDCARD in ECU.

<img src="https://user-images.githubusercontent.com/73337486/209594329-ac6db4c8-81fb-4e4b-981b-90f0a96fd801.png" width=50% height=50%>

**Comment by mck1117** [comment]
Did you run the gen_config script for your board before building the firmware?

**Comment by mck1117** [comment]
If the drive is there but blank, it means you didn’t run the script.

**Comment by rusefillc** [comment]
@TurboMarian please push into https://github.com/TurboMarian/rusefi for us to be less blind

**Comment by mck1117** [comment]
Like this, you should see content added to ramdisk_image.h

![image](https://user-images.githubusercontent.com/568254/209599939-4ed9b7a0-9e65-485e-bf77-c311dcbd5670.png)

**Comment by TurboMarian** [comment]
Thank you guys!
<img src="https://user-images.githubusercontent.com/73337486/209698073-0e2cd2ab-1664-4121-a07b-105f2689d81a.png" width=50% height=50%>
