### ISSUE TITLE
Sometimes while editing Lua we get "Fuel pressure compensation is set to use a pressure sensor, but none is configured. 20221226@proteus" on Passat config

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4916]
No tune link but trust me it has fuel pressure sensor configured

Once in a while Lua "Send to ECU" button would cause "Fuel pressure compensation is set to use a pressure sensor, but none is configured. 20221226@proteus"

**Comment by rusefillc** [comment]
Does "Send to ECU" cause full configuration change action? Do we have a race condition between sensor de-init/re-init and fuel model thread?

**Comment by mck1117** [comment]
Yeah, that doesn't fix the issue.  Let me take a real look at it.

**Comment by mck1117** [comment]
fixed by #4947
