### ISSUE TITLE
Mitsubishi 4G93 Trigger issues

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4918]
What kind of trigger pattern is expected when you choose this?

https://github.com/rusefi/rusefi/wiki/All-Supported-Triggers#mitsubishi

**Comment by rusefillc** [comment]
@ElDominio what do you think about removing that trigger and renaming Miata NA to mention that it's same as Mitsu?

```
	// todo: this really looks to be same as Miata_NA shall we remove?
	TT_MITSUBISHI = 11,

```

https://github.com/rusefi/rusefi/wiki/All-Supported-Triggers#mazda-miata-na

**Comment by ElDominio** [comment]
Maybe call it Miata NA/4G63

**Comment by ElDominio** [comment]
4G18 is not an engine; why was the title changed to that?

Difference between Miata NA/4G63 and 4G93 is that 4G93 is separate Cam/Crank sensors, Miata NA is a CAS unit. I think this is enough reason to keep them separate @rusefillc

**Comment by rusefillc** [comment]
Google knows 4g13 and for whatever reason we have a reference to 4g18 in the source code I cannot explain that and it's not the most important issue

I see that https://github.com/rusefi/rusefi_documentation/blob/master/Images/triggers/trigger_TT_MITSUBISHI.png image is wrong - circles do not match linear shape


compare to https://github.com/rusefi/rusefi/wiki/All-Supported-Triggers#mazda-miata-na

**Comment by ElDominio** [comment]
https://rusefi.com/online/view.php?log=1135 -> log of what's happening, it runs for a split second and has trigger error. Changing to 4G69 trigger has perfect syncgapratio but RPM = 0

[4g93start.zip](https://github.com/rusefi/rusefi/files/10333658/4g93start.zip) -> logaic analyzer log

[osclog.csv](https://github.com/rusefi/rusefi/files/10333660/osclog.csv) -> ts oscope

**Comment by rusefillc** [comment]
@ElDominio 

![image](https://user-images.githubusercontent.com/48498823/210295675-ff657c19-8fa6-497a-a4e0-f61d8a1651ed.png)

does the file open for you? using what version of what app?

**Comment by ElDominio** [comment]
![image](https://user-images.githubusercontent.com/5685108/210296236-ae6ced71-b7c9-490a-b38a-bc3209ecffd3.png)

**Comment by rusefillc** [comment]
yes works with 1.2.40!

**Comment by rusefillc** [comment]
@ElDominio this is now two separate tickets mixed together

glad to see logic analyzer!

you seem to describe two separate cranking attempts with different settings but only one log?

https://rusefi.com/online/view.php?msq=1352 shows crank as primary input and cam as seconday

![image](https://user-images.githubusercontent.com/48498823/210370621-14a9d28a-2e90-4f25-a3f4-dea9f84f5fdf.png)


please clarify if physical wires are flipped (c3-crank goes to cam or crank? c7-cam goes to cam or crank on actual vehicle?) since cam has to be primary input

**Comment by ElDominio** [comment]
Pretty sure we wired crank to crank+(c3) and cam to c7 and i flipped it in settings

**Comment by rusefillc** [comment]
I am confused. Please confirm what tune matches what log. Is this a case of tune not matching log?

**Comment by ElDominio** [comment]
I don't really remember but I do know flipping it didn't work. 

The only setting that has at least tried to fire up is Miata NA, both inverted, with Primary set to C7 and Secondary set to C3. But it loses sync quickly and shuts off (which is the behavior seen in the most recent log)

**Comment by rusefillc** [comment]
trigger documentation now show gaps in light grey for instance "gap 1.90"

![image](https://user-images.githubusercontent.com/48498823/210444907-a755904f-628f-41e1-9827-7a17f78892ea.png)

![image](https://user-images.githubusercontent.com/48498823/210445006-565c80ff-05a1-4eff-8531-889566c0c2fc.png)

note that one is waiting for only one gap and the other waits for two. note the gap sequence


please post links to four logs
mitsu trigger, cam not inverted
mitsu trigger, cam inverted
miata NA trigger, cam not inverted
miata NA trigger, cam inverted

secondary channel inverted or not would be a separate story, for now let's focus on top cam wheel since that's the one where we see gaps nicely

I guess for secondary inverted or not we will be troubleshooting instant RPM @mck1117 ?

**Comment by rusefillc** [comment]
PS: look at logs 
![image](https://user-images.githubusercontent.com/48498823/210445958-9d38d10c-c02b-4922-9803-2be1c8c6e535.png)

**Comment by ElDominio** [comment]
using mitsu trigger
[2022-12-29_14.04.55.mlg.zip](https://github.com/rusefi/rusefi/files/10339982/2022-12-29_14.04.55.mlg.zip)

syncgapratio is content but no RPM

**Comment by mck1117** [comment]
> syncgapratio is content but no RPM

syncgapratio is NOT content - look at the sync parameters on the image

![image](https://user-images.githubusercontent.com/568254/210447653-d0f8572b-c3ed-4dd1-b8bb-cca468a3d6e5.png)

@ElDominio try these parameters in trigger gap override, if the engine starts, please record SD trigger log of cranking+start+run so we can hardcode better trigger shape

![image](https://user-images.githubusercontent.com/568254/210447875-69bbef0c-c0f9-4c1f-86f8-92f550fdc5b1.png)

**Comment by rusefillc** [comment]
@mck1117 you seem to be suggesting miata gaps but note the difference between images - mitsu has gaps painted only on falls
```
void initializeMitsubishi4g18(TriggerWaveform *s) {
	s->initialize(FOUR_STROKE_CAM_SENSOR, SyncEdge::Fall);
```

vs

```
void initializeMazdaMiataNaShape(TriggerWaveform *s) {
	s->initialize(FOUR_STROKE_CAM_SENSOR, SyncEdge::Both);
```

**Comment by mck1117** [comment]
Whatever the gaps are, look at the log - they don't match the number in the image, but WILL sync with the miata numbers (should mitsu also be rising edge??)

**Comment by rusefillc** [comment]
miata numbers are "BOTH" numbers. miata "BOTH" numbers would not work for mitsu "Fall" would they?

**Comment by mck1117** [comment]
https://rusefi.com/online/view.php?log=1135 shows some gap ratios, are those not the real gap ratios measured on the real engine?

**Comment by ElDominio** [comment]
That log was made on real engine yes

**Comment by ElDominio** [comment]
Engine does not turn on with those settings, it seems to try but the moment it does it loses sync and never runs

**Comment by rusefillc** [comment]
I am glad to be right!

Now that you've executed @mck1117's suggestion please consider my request for data as mentioned above

**Comment by mck1117** [comment]
> it seems to try but the moment it does it loses sync and never runs

grab a log of that?

**Comment by rusefillc** [comment]
Related to #4935

**Comment by ElDominio** [comment]
> > it seems to try but the moment it does it loses sync and never runs
> 
> grab a log of that?

It's  in the "miatanainverted.mlg" but it only shows 204RPM (which it did go over)

**Comment by rusefillc** [comment]
these two look like winners to me

![image](https://user-images.githubusercontent.com/48498823/210678218-7ea6a3f7-dfb2-4b00-a592-dce62e2932b0.png)

![image](https://user-images.githubusercontent.com/48498823/210678228-b1eb186d-4ae8-4471-badc-1223c5e5e1de.png)

note how one is inverted another is not. either we have magic or trigger definitions are inverted.

@ElDominio please confirm that timing light was used to confirm TDC location. I wonder if bad TDC was causing engine to kick

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/210678406-765723ad-b481-4b76-a810-baa789f7bc33.png)

![image](https://user-images.githubusercontent.com/48498823/210678413-aaaf9aea-d588-4972-9ab6-9b77b6bcc11f.png)

look like loosers?

**Comment by ElDominio** [comment]
> these two look like winners to me
> 
> ![image](https://user-images.githubusercontent.com/48498823/210678218-7ea6a3f7-dfb2-4b00-a592-dce62e2932b0.png)
> 
> ![image](https://user-images.githubusercontent.com/48498823/210678228-b1eb186d-4ae8-4471-badc-1223c5e5e1de.png)
> 
> note how one is inverted another is not. either we have magic or trigger definitions are inverted.
> 
> @ElDominio please confirm that timing light was used to confirm TDC location. I wonder if bad TDC was causing engine to kick
> 

Timing only confirmed on miata NA/INVERTED

**Comment by mck1117** [comment]
@rusefillc you can look at `triggerToothAngleError` to see if teeth are arriving at the correct time

**Comment by ElDominio** [comment]
@mck1117  @rusefillc  anything else I need to get?

**Comment by rusefillc** [comment]
@ElDominio what's the current problem statement? does the car start/run/happy?

**Comment by ElDominio** [comment]
start yes
run no
happy definitely no

i have no more requests for logs so idk what else to do

**Comment by rusefillc** [comment]
plz call?

why does it not run in your opinion? do you have a log where it cranks and starts? why does it not start/run in the logs which look happy in terms of trigger sync?

For your information without tunes I was assuming that ignition/injection was off or something. As is the process is pretty frustrating :( Let's brainstorm how can we make this less spread out in time. Just the logs are not giving at least me the full enough picture, please consider posting to youtube more often. No, pixelated whatsapp videos would not be same :(

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/211168897-fdda2b8d-44ce-4b38-b403-2784c8e1fe1e.png)

![image](https://user-images.githubusercontent.com/48498823/211168929-06647fdc-f10b-4cbe-9afa-f6059e43fbf2.png)

**Comment by ElDominio** [comment]
[4g93startnosparkplugs.zip](https://github.com/rusefi/rusefi/files/10367134/4g93startnosparkplugs.zip)

**Comment by ElDominio** [comment]
Runs on 4G93 only cam

Issues on 4G93 both fronts

log with crank inverted
[4g63 both front only crank invert.zip](https://github.com/rusefi/rusefi/files/10367297/4g63.both.front.only.crank.invert.zip)

log with crank not inverted
[4g63 both front no invert.zip](https://github.com/rusefi/rusefi/files/10367298/4g63.both.front.no.invert.zip)

log with crank not inverted, with injectors enabled
[4g93bothfront none inverted.zip](https://github.com/rusefi/rusefi/files/10367299/4g93bothfront.none.inverted.zip)

**Comment by ElDominio** [comment]
fun fact:

this only works for revE 4chan, not any previous one

**Comment by rusefillc** [comment]
https://rusefi.com/online/view.php?log=1143

i see crazy gap ratio I suspect noise. open question is 4chan hardware is problem or not, unfortunately unable to get in touch with @mck1117 on #4656 

![image](https://user-images.githubusercontent.com/48498823/211641289-25a1293d-2a46-49e1-8773-eddb9189e8be.png)

my plan:
* I ship more connector parts to @ElDominio asking to make Proteus and 8chan (!!!) harnesses to isolate HW issues
* I will see if I can revive #4656

**Comment by rusefillc** [comment]
Let me recap
* Still a major concern for @ElDominio 
* We have since merged https://github.com/rusefi/rusefi/pull/4656 @ElDominio did we test with that firmware fix/hack?
* We suspect HW digital input specific to hall (which probably technically also affects 2chan? but maybe progress in 8chan), we have two vectors of progress here
* Either make a Proteus or 8chan harness
* or try https://github.com/rusefi/alphax-4chan/issues/72 capacitor mods


@mck1117 FYI

**Comment by rusefillc** [comment]
I think we have changes so much it's time for a new ticket with only current status
