### ISSUE TITLE
Cam showing on console but not TS trigger logger

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4919]
![IMG_20221229_140346.jpg](https://user-images.githubusercontent.com/5685108/209993723-3fb981ad-f9ea-44c0-b7d1-a15bf88191b4.jpg)

![IMG_20221229_142209.jpg](https://user-images.githubusercontent.com/5685108/209993734-a39b00ab-dc34-439e-bdc3-5891e96e1089.jpg)

![IMG_20221229_142330.jpg](https://user-images.githubusercontent.com/5685108/209993820-8d483913-38ba-4005-bb91-619553c1429f.jpg)

Have tried on E6 and same issue

**Comment by ElDominio** [comment]
Problem solved, triggers inverted

My confusion arises from the idea of crank being primary no matter the trigger. I would suggest a fix but it would involve writing instructions and no one including me reads them

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/209994492-7d162af0-c124-4e27-97a8-833fdd9d41f9.png)

![image](https://user-images.githubusercontent.com/48498823/209994493-ff694f1e-4db0-4b7b-808b-3c77f907f2c6.png)

![image](https://user-images.githubusercontent.com/48498823/209994494-4b3e13aa-0754-446a-aa3a-543beb145329.png)

![image](https://user-images.githubusercontent.com/48498823/209994495-6fa6156f-759a-43db-b5e7-fced00c8d3d4.png)

![image](https://user-images.githubusercontent.com/48498823/209994496-71c9cb21-fd39-4055-9497-c6901c785800.png)

![image](https://user-images.githubusercontent.com/48498823/209994498-ad1cbc90-7097-4ea6-9622-bbab5534ad9a.png)

![image](https://user-images.githubusercontent.com/48498823/209994499-c017ce17-8cde-46bf-95a1-9ed4f27dde7e.png)

![image](https://user-images.githubusercontent.com/48498823/209994500-2a87f7f2-e61a-414e-93a7-a3a29efd1109.png)
