### ISSUE TITLE
Madza 36-1 and ST107 cam (Madza3)

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4922]
You can see it happen at about 0s and 1.8s and 7s, cam position goes crazy and so does RPM.

https://rusefi.com/online/view.php?log=1133

**Comment by mck1117** [comment]
SD trigger log please

**Comment by ElDominio** [comment]
[re_12.zip](https://github.com/rusefi/rusefi/files/10333637/re_12.zip)

trigger log uplaoded

**Comment by mck1117** [comment]
possibly same VR weirdness as #4874

**Comment by ElDominio** [comment]
Any possible fix? Could it be related to https://github.com/rusefi/alphax-4chan/issues/84 ?

**Comment by rusefillc** [comment]
@ElDominio did https://github.com/rusefi/alphax-4chan/issues/85 help? Can we test with improved hardware?

**Comment by ElDominio** [comment]
I have used a mazda3 and it worked fine? so i'll close this and make a new one if needed
