### ISSUE TITLE
Toyota 1NZ-FE trigger (36-2CKP, 4-1CMP) issues

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4930]
The car runs well in semi sequential, but activating the cam input makes RPMs go insane and the car shut off.

https://rusefi.com/online/view.php?log=1134 -> Log shows this happening

[re_11.zip](https://github.com/rusefi/rusefi/files/10333643/re_11.zip) -> tooth log

**Comment by ElDominio** [comment]
RPMs no longer go crazy, but cam position is jumpy

[OsciLogandNormalLogwithcapsRevE.zip](https://github.com/rusefi/rusefi/files/10368954/OsciLogandNormalLogwithcapsRevE.zip)
tunerstudio oscope and log



[re_15.zip](https://github.com/rusefi/rusefi/files/10368955/re_15.zip)
SD card tooth log

**Comment by rusefillc** [comment]
Looks like https://rusefi.com/online/view.php?msq=1349&dialog=triggerConfiguration is the tune

**Comment by mck1117** [comment]
invert the cam

**Comment by rusefillc** [comment]
Ideal gap should be 3 on 36/2

https://github.com/rusefi/rusefi/wiki/All-Supported-Triggers#362

We get a very clear gap of 2 that gives us a 15% spile in instant RPM which #4954 would be reporting "one day"

Something is not right @ElDominio 

![image](https://user-images.githubusercontent.com/48498823/211659854-fa8bfc5e-aa9f-4ac0-a6e0-1a85e1e1af20.png)

**Comment by mck1117** [comment]
It is more obvious to look at `triggerToothAngleError`, there is clear +10 then -10, which means one tooth is in the wrong spot.

![image](https://user-images.githubusercontent.com/568254/211662080-6cc957dd-10e8-4210-8d22-c6417a8fc555.png)

Looking at the tooth log, you have the correct trigger type selected, but you need to __invert the primary trigger__.

**Comment by mck1117** [comment]
![image](https://user-images.githubusercontent.com/568254/211663951-ea6777e7-836e-423e-9614-c423f40a8574.png)

**Comment by ElDominio** [comment]
https://rusefi.com/online/view.php?msq=1364

Current tune on car

I will be with the car on Thursday

**Comment by rusefillc** [comment]
crank seems happy now https://rusefi.com/online/view.php?log=1146

**Comment by rusefillc** [comment]
@ElDominio says VVT is issue now so let's look at vvtSyncRatio

![image](https://user-images.githubusercontent.com/48498823/212187959-89a09eb0-c23f-4906-a974-067732c46ca9.png)

**Comment by mck1117** [comment]
Something bad/weird is going on with the cam.

Top: crank (good)
Bottom: cam (wtf)

![image](https://user-images.githubusercontent.com/568254/212188268-00c34ed3-238f-477a-b635-f4a7a0eb542c.png)

(by the way, it works great to open a trigger scope log from TS in megalogviewer!)

**Comment by mck1117** [comment]
How is the cam wired? there's no connection between the cam and crank sensors, is there?

**Comment by ElDominio** [comment]
Yes, there is, factory Toyota wiring shares the negative side of VR

I mentioned this on slack but aha slack is not GH lol

**Comment by rusefillc** [comment]
@mck1117 I would love to learn new skills

@mck1117 at the moment I need simpler instructions to learn new skills sorry, as is I have no idea what new skills I can gain

**Comment by mck1117** [comment]
> factory Toyota wiring shares the negative side of VR

Yeah, this isn't gonna work with the VR circuitry . Not sure what to do there. Any way you can run independent VR- wires for each?

**Comment by mck1117** [comment]
> @mck1117 I would love to learn new skills
> 
> @mck1117 at the moment I need simpler instructions to learn new skills sorry, as is I have no idea what new skills I can gain

huh?

**Comment by rusefillc** [comment]
"(by the way, it works great to open a trigger scope log from TS in megalogviewer!)"

this sounded like you were suggesting something but I have no idea what you are suggesting

**Comment by ElDominio** [comment]
![image](https://user-images.githubusercontent.com/5685108/212190644-b91adeea-4ac7-4d5b-b284-f766c6492800.png)

**Comment by mck1117** [comment]
> "(by the way, it works great to open a trigger scope log from TS in megalogviewer!)"
> 
> this sounded like you were suggesting something but I have no idea what you are suggesting

nope, I've just learned this too! I opened it by accident with MLV and it worked great.

**Comment by ElDominio** [comment]
Solution for VVT position has been established


Final problem: cranking RPM with inverted set to TRUE on primary trigger is not useable. I get it running by setting it to false, starting the engine, then switching to TRUE.

[2023-01-12_17.36.37.mlg.zip](https://github.com/rusefi/rusefi/files/10406421/2023-01-12_17.36.37.mlg.zip)

**Comment by mck1117** [comment]
@ElDominio try grounding that wire while also connected to both cam/crank VR- inputs - just add a ground jumper between the VR- wire and sensor ground

**Comment by ElDominio** [comment]
Connected jumper cable between sensor ground and VR-

Signal is significantly cleaner, but not very reliable.
Scopes of this at 
[bridgeoscope.zip](https://github.com/rusefi/rusefi/files/10414013/bridgeoscope.zip)

We will remove this bridge and run a seperate CMP+/- wire tor esolve issues, but I think VVT errors were due to sharing the VR

Also, noticed I duplicated this issue #4825

**Comment by ElDominio** [comment]
I am commenting to document

It is recommended to add a 10nf cap across pins 4 and 5, and pins 2 and 4 to TLV3202AIDR for VR purposes

Pending testing
