### ISSUE TITLE
findTriggerZeroEventIndex() failed

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4935]
![IMG_20230104_125819.jpg](https://user-images.githubusercontent.com/5685108/210608917-f8b91b8a-8609-4120-8049-96bb7bd02e57.jpg)

Latest firmware snapshot
On 4g93 car

**Comment by ElDominio** [comment]
<img width="438" alt="2023-01-04 12_50_16-Error!" src="https://user-images.githubusercontent.com/5685108/210614326-7e3d22c6-466b-410e-b34d-e26957a816a6.png">

**Comment by rusefillc** [comment]
@ElDominio is that with custom or default gaps?

**Comment by ElDominio** [comment]
Custom gaps
