### ISSUE TITLE
"12 tooth crank" on firmware is not in Supported Triggers

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4942]
"12 tooth crank" seems to be the proper choice for the first generation of 2JZ, where it is dual VR 12 on crank +1 on cam.

There is nothing about this in https://github.com/rusefi/rusefi/wiki/All-Supported-Triggers but it exists in firmware

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi/wiki/All-Supported-Triggers#toyota-2jz 1/24 added

**Comment by rusefillc** [comment]
Depends on #4956
