### ISSUE TITLE
12 tooth crank issues

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4943]
I have a 2JZ with this trigger setup using internal VR for both.

[suprare_12.zip](https://github.com/rusefi/rusefi/files/10357425/suprare_12.zip)

here is a cranking log with inverted trigger
[crankinglogenenero2023inverttrue.zip](https://github.com/rusefi/rusefi/files/10357431/crankinglogenenero2023inverttrue.zip)

adjacent tune
[crankingtoothlogsuprainvertedtrye.zip](https://github.com/rusefi/rusefi/files/10357436/crankingtoothlogsuprainvertedtrye.zip)

Changing to custom toothed wheel allowed it to sync and run, but sometime syncs on the wrong tooth (30 degrees out of timing) (there are no logs of this, can be produced if helpful)

**Comment by rusefillc** [comment]
#4179

**Comment by rusefillc** [comment]
https://rusefi.com/online/view.php?msq=1298 looks correct

**Comment by rusefillc** [comment]
i see two issues on the log

1) vvt counter is not increasing. This setup absolutely depends on single tooth cam being alive

2) what's up with trigger gap? on the evenly spaces 12/0 crank I would expect 1, 1, 1, 1, 1ish equal gaps but that's totally not what the log shows? Some sort of electrical/VR issue? Which reminds me about build-on oscilloscope have you tried that?

![image](https://user-images.githubusercontent.com/48498823/211238187-1b667144-694c-4b02-888b-7fe37a660a12.png)

**Comment by ElDominio** [comment]
![image](https://user-images.githubusercontent.com/5685108/211398025-8c53fc2b-3120-46bc-803d-e6af54f56ae0.png)

we can see cam+1 is extremely close to one of the crank teeth

Trigger scope pic with 
custom tooth wheel 12 0 missing
both sensors VR, boards has 10nF caps soldered on

[logsoncustom12toothnomissing.zip](https://github.com/rusefi/rusefi/files/10376518/logsoncustom12toothnomissing.zip)

customtrigger12minus0yessttart.csv <- started with custom tooth wheel 12 0 missing, oscope log, other log is the same but i had injection disabled


[12toothcrank scranking scope.zip](https://github.com/rusefi/rusefi/files/10376526/12toothcrank.scranking.scope.zip)

only a scope of cranking since this trigger does not start

**Comment by ElDominio** [comment]
Using these tooth gaps
![image](https://user-images.githubusercontent.com/5685108/211401121-b52ae356-c1e5-4e4c-b9bd-52d295ca525c.png)

Fired right up, will check for possible sync problems
[running12toothwithcustomgaps.zip](https://github.com/rusefi/rusefi/files/10376628/running12toothwithcustomgaps.zip)

**Comment by rusefillc** [comment]
@ElDominio says "Toyota wheel is unusual it gives gap numbers during cranking"

![WhatsApp Image 2023-01-09 at 14 58 57](https://user-images.githubusercontent.com/48498823/211404187-afb8dcf4-5af9-411e-9a9c-40eb47aba3a8.jpg)

**Comment by rusefillc** [comment]
2JZ would be global trigger offset 65 but same wheel could be Honda, not hard coding for now

![WhatsApp Image 2023-01-09 at 15 30 52](https://user-images.githubusercontent.com/48498823/211404697-609dff31-8c5f-4d5e-a1bd-e1aafc2efbc4.jpg)
