### ISSUE TITLE
sensorinfo does not contain physical pin info

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4949]
analoginfo used to mention HW channel
```
2021-04-01_17_14_38_244: EngineState: CLT ADC13 ADC_SLOW PC2 adc=0.82/input=1.65v/divider=2.00
2021-04-01_17_14_38_244: EngineState: IAT ADC14 ADC_SLOW PC3 adc=0.98/input=1.97v/divider=2.00
```

see #2517

It looks like #4646 has wiped that info out

**Comment by mck1117** [comment]
This?

![image](https://user-images.githubusercontent.com/568254/211128471-64d24e7b-554a-4607-b5d0-70e1437a697a.png)

**Comment by rusefillc** [comment]
No, that

![image](https://user-images.githubusercontent.com/48498823/211128511-fd8e59fe-6b95-4954-b1ef-fd9e91f8ebfe.png)

**Comment by rusefillc** [comment]
also this @mck1117 

![image](https://user-images.githubusercontent.com/48498823/211128528-ce91c06a-944a-4f51-9f20-328d2f36f29f.png)

**Comment by mck1117** [comment]
eh? the command `sensorinfo` first shows all ADC channels in use, then shows all sensors configured

**Comment by rusefillc** [comment]
Ohh sorry
