### ISSUE TITLE
change of only trigger offset changes fire order?!

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4952]
@ElDominio is struggling to start hist 4g93 right now

same 4g93 settings same fuel OFF, three logs are different only with offset yet they somehow produce different firing order?!

![image](https://user-images.githubusercontent.com/48498823/211167532-aee22638-49fe-45fd-85a4-64139e8fed3f.png)

![image](https://user-images.githubusercontent.com/48498823/211167545-4692d6d3-bd67-4523-81fe-754a30563a83.png)

**Comment by mck1117** [comment]
it's just skipping cylinder 3 in the first screenshot because it gets a trigger error before cyl 3 fires
