### ISSUE TITLE
Ignition IAT corr IAT error what

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4953]
![image](https://user-images.githubusercontent.com/5685108/211172600-a6f824b2-0d4d-42a2-ace6-4d630223793b.png)

**Comment by ElDominio** [comment]
![image](https://user-images.githubusercontent.com/5685108/211172652-1596d3b7-c546-43e7-9e2d-5aad06877de6.png)

**Comment by rusefillc** [comment]
@ElDominio did you full erase on firmware update and restored settings from TS?

looks like you did not full erase so new table was using random left-over bytes?

**Comment by ElDominio** [comment]
Problem is/was? IAT values in the lower two rows were negative. Although negative air temp is not possible in Puerto Rico, it might be somewhere else?
![image](https://user-images.githubusercontent.com/5685108/211172932-b71d9930-22db-4b2e-a0bf-c92d77620837.png)

**Comment by rusefillc** [comment]
@mck1117 it's a typo
```
		ensureArrayIsAscending("Ignition IAT corr IAT", config->ignitionIatCorrLoadBins);
		ensureArrayIsAscending("Ignition IAT corr Load", config->ignitionIatCorrLoadBins);
```

ignitionIatCorrTempBins not validated while ignitionIatCorrLoadBins is validated twice.

**Comment by rusefillc** [comment]
@ElDominio reminder to use more words. I see nothing broken, I see you not wiping chip blank and @mck1117 not adding CHANGELOG about the incompatible configuration change

please manually fix vertical axis
