### ISSUE TITLE
totalFuel and totalIgnition correction gauges in Tunerstudio

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4955]
Having a "totalX" gauge for corrections ccan help catch corrections that might be driving a tuner crazy.

Also, a view like this would help but I don't know about the difficulty of making this
![image](https://user-images.githubusercontent.com/5685108/211210571-fb29d904-7aac-4019-b86e-ff00f409f3bb.png)

Shows each correction individually and then the total, which helps catching tuning mistakes. Every correction should ideally have a gauge

**Comment by rusefillc** [comment]
@ElDominio more of fuel and timing data points were extracted into corresponding "view" section - see fuel and ignition state in "view"

Also any "view" entry could now be a gauge with little effort of my end. See new subcategories for gauges, let me know if we are on the right track.

Any additional "view" metric to expose as a gauge please let me know.

**Comment by ElDominio** [comment]
Thank you very much, will test soon
