### ISSUE TITLE
IAC PID Multiplier Table Rounding Issue

### ISSUE THREAD

**Issue by OSprey65** [rusefi/rusefi#4963]
In the idle settings menu, it says to use values between 0-1 for the IAC PID multiplier table. When entering any value over 0.5, the table rounds the displayed values to the nearest integer but hovering over the cell shows that the correct value is retained.
![image](https://user-images.githubusercontent.com/24773729/211736926-a8457052-f2d9-4694-bb43-71b8947f42f7.png)

**Comment by rusefillc** [comment]
interesting, that tells me that no one has used it so far?

**Comment by mck1117** [comment]
scale 20? I think you want a scale of more like 0.05, min 0, max 10

**Comment by OSprey65** [comment]
Looks like I'm one of the first to try it then. It's useful for correcting the idle droop
