### ISSUE TITLE
Optimize Build - cut down on build time passing by skipping actions not required?

### ISSUE THREAD

**Issue by mi-hol** [rusefi/rusefi#4970]
@chuckwagoncomputing I wanted to add just connector pinout and was adding 2 files via PR "WIP: add Benelli Walbro connector pinout" #4969 and was surprised  by the number of unnecessary actions that are performed.

"Time is money" would it make sense to cut down on build time passing by skipping actions not required?

**Comment by rusefillc** [comment]
You are suggesting something for which cost does not justify benefit
