### ISSUE TITLE
Cam-as-primary is vague

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4975]
Why are some triggers designed to use cam as primary? config should always be crank as primary to eliminate vaugeness

Right now 4G63 uses Cam as primary, but 95 Dodge Neon doesn't or does? If it doesn't, why not? Cam is part of trigger shape  @rusefillc

**Comment by ElDominio** [comment]
![IMG-20230117-WA0027.jpg](https://user-images.githubusercontent.com/5685108/212971008-dd111c55-683b-44bb-b62f-84ec99d21c51.jpg)

In one example, cam is primary

In other example, cam is not even considered.

@rusefillc says "please follow images" which implies to follow order on images from left to right

Sentence is not in "all supported triggers" page

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi/wiki/All-Supported-Triggers#norman-note

**Comment by ElDominio** [comment]
Note helps significantly

New users don't know who Norman is though
