### ISSUE TITLE
Dodge 1995 trigger reading double RPM

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#4976]
log and tune at https://rusefi.com/online/view.php?log=1147

![image](https://user-images.githubusercontent.com/5685108/212964800-56915e79-2da4-4c97-ad16-d330b64946e0.png)

**Comment by rusefillc** [comment]
@ElDominio please help me understand what's going on

Do you see the blue warning note?

![image](https://user-images.githubusercontent.com/48498823/212965848-fabc0c07-8497-4645-9516-0769353ae6eb.png)

How does blue warning correspond to your selection?

![image](https://user-images.githubusercontent.com/48498823/212965975-eb5c2cef-e122-4d41-b874-bf238538d6a2.png)

**Comment by rusefillc** [comment]
@ElDominio i am _really_ worried overall

https://github.com/rusefi/rusefi/wiki/All-Supported-Triggers#dodge-neon-1995

**Comment by ElDominio** [comment]
https://rusefi.com/online/view.php?log=1148

settings as in trigger page now with log

**Comment by mck1117** [comment]
should this not get converted to a symmetrical crank trigger? is the "crank" pattern actually on the crank, or are they all on the cam "CAS-style"?

**Comment by ElDominio** [comment]
crank is actually on crank

**Comment by mck1117** [comment]
> crank is actually on crank

OK, in that case, it must get converted. Right now you'll get timing inaccuracy since some teeth are on cam, and some are on crank, but we treat them as phase locked (which they aren't, if the belt stretches then some of your events move around)

**Comment by ElDominio** [comment]
This is a log from the guy who is running the car

Apparently, started it with timing retarded (he changes trigger angle from 140 (which is actual zero) to 170 and the car starts, he then changes back to 142 and it runs well.


[LogCranking170triggerFixed0cranking#2.zip](https://github.com/rusefi/rusefi/files/10471587/LogCranking170triggerFixed0cranking.2.zip)


This is a log at 135 trigger angle, doesn't start. Might be something that stating while severly undertimed makes it start correctly?
[LogCranking135trigger-30cranking.zip](https://github.com/rusefi/rusefi/files/10471589/LogCranking135trigger-30cranking.zip)

**Comment by mck1117** [comment]
OK, this requires a tooth log of some form to proceed. Logic analyzer, SD card, whatever, but something is *VERY* wrong with the trigger pattern and it's not worth our effort to try and diagnose this over 3 hops of the game of telephone. Get a tooth log of the same thing as the "135 trigger 30 cranking" log and then we can make progress.

**Comment by ElDominio** [comment]
![image](https://user-images.githubusercontent.com/5685108/214153475-f14cc289-3ae1-4649-9c00-49f534bd7409.png)

Did a tooth log to check how and when it loses sync to try to understand why

**Comment by mck1117** [comment]
> when it loses sync to try to understand why'

this is of no use, we need to change how this trigger mode works in code first

**Comment by mck1117** [comment]
apparently the engine has blown up, but:

our trigger pattern was totally wrong. It's close, but the teeth weren't actually spaced right.

![image](https://user-images.githubusercontent.com/568254/214192379-566321a5-d6ce-4ff1-bb1a-8f3fa1053217.png)

with #5003 the pattern is now within a degree or so of correct.

**Comment by rusefillc** [comment]
Have we blown up the engine?

**Comment by mck1117** [comment]
> Have we blown up the engine?

@ElDominio initial assessment was no

**Comment by ElDominio** [comment]
Today they tore it open, oil pump failure lol

**Comment by mck1117** [comment]
> oil pump failure

ouch
