### ISSUE TITLE
improvements around RPM_LOW_THRESHOLD 

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#498]
We have RPM_LOW_THRESHOLD hard-coded at 240 while logs show lower RPM during cranking.

Do we need to lower the hard-coded value? Make things configurable? Improve documentation?

**Comment by rusefi** [comment]
// note that we are ignoring the number of tooth here - we
// check for duration between tooth as if we only have one tooth per revolution which is not the case
#define REVOLUTION_TIME_HIGH_THRESHOLD (60 * 1000000LL / RPM_LOW_THRESHOLD)

**Comment by mck1117** [comment]
this is now set to 25, and we haven't seen a problem with that.
