### ISSUE TITLE
LTS: folder inside bundle and self identifition

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4992]
At the moment all .zip bundles have files within "snapshot_timestamp" folder. While we need a way to say what bundle we look at, current approach is broken

Timestamp in folder makes no sense in ligh of bundle autoupdate, looks like we shall remove timestamp

For lts branches shall we use branch name as folder name?

Open question if we need some metainfo.txt file with original bundle timestamp, and maybe separate entry somewhere with latest auto update timestamp.

**Comment by rusefillc** [comment]
@chuckwagoncomputing any interest?

**Comment by mck1117** [comment]
should the folder name just be the signature?

right now it's like `snapshot_20230111_174746_proteus_f4_rusefi`

it could be like `rusEFI master.2023.01.22.proteus_f4.2951145916`

**Comment by rusefillc** [comment]
With autoupdate workglow original bundle timestamp should we much less visible imho

**Comment by chuckwagoncomputing** [comment]
So something like `rusEFI master.proteus_f4`?

**Comment by rusefillc** [comment]
Yes

Minor detail let's call main/master "snapshot" looks like that's the client facing term we use
