### ISSUE TITLE
LTS: bundle autoupdate to use proper branch source

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4993]
We have java autoupdate logic, it needs to embrace branches

**Comment by chuckwagoncomputing** [comment]
Could you give an example?

**Comment by rusefillc** [comment]
Download bundle from build server lts folder 
Wait a week
Hit "autoupdate"

Expected: nothing
Actual result: I assume it would override content with master stuff?

**Comment by chuckwagoncomputing** [comment]
Thanks, I understand now. It seems to me that #4992 is a prerequisite to this.

**Comment by rusefillc** [comment]
Yes absolutely!

**Comment by chuckwagoncomputing** [comment]
Could we safely assume that if the branch name (stored in the file name or otherwise) is not master, then we should find the files at `rusefi.com/build_server/lts/<branch name>`?

**Comment by rusefillc** [comment]
yes, since we own the convention?
