### ISSUE TITLE
Refactoring: less confusion macro names around serial/uart/etc in connectivity

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#4999]
Current terminology could be improved

**Comment by rusefillc** [comment]
First order of business
We have "serial" and "uart" what is the proper term for "serial or uart"?

**Comment by mck1117** [comment]
For context, which defines?

**Comment by rusefillc** [comment]
```
HAS_PRIMARY
HAS_SECONDARY
```

**Comment by nmschulte** [comment]
The console filenames say 'serial', but UART seems less ambiguous in the bigger scope: but this is limited to the console§TS IO where serial isn't really ambiguous.

**Comment by dron0gus** [comment]
ChibiOS has both Serial and UART drivers for same IP block in STM32. Drivers provide different functionality. So serial != uart. At least in ChibiOS therms.

**Comment by rusefillc** [comment]
Serial is uSart, I am thinking to use UxART as umbrella term unless there are better ideas

**Comment by mck1117** [comment]
> Serial is uSart, I am thinking to use UxART as umbrella term unless there are better ideas

what is the problem we are trying to solve?

**Comment by rusefillc** [comment]
Has_primary is a shitty variable name

**Comment by mck1117** [comment]
BTW those particular defines are _not_ defined in any config file, they're defined as a function of others in tunerstudio_io.h

![image](https://user-images.githubusercontent.com/568254/213998503-5ef4be7f-bc09-4a86-b79b-8ac3e1c6d42d.png)

**Comment by mck1117** [comment]
#3578 already improved this by not having separate serial vs. uart defines, and just deciding based on the type of whatever thing listed there

**Comment by rusefillc** [comment]
Here we will only rename, nothing else.
