### ISSUE TITLE
PID: idle valve position after deccel

### ISSUE THREAD

**Issue by darxfame** [rusefi/rusefi#501]
Today if we turn on the PID idle valve, we have an idle valve position = PID Min after decceleration, but it's not right.
We must save the last idle position before acceleration or TPS position more PID TPS Deactivation and move idle valve to the saved last position.

**Comment by rusefi** [comment]
this is about idlePidDeactivationTpsThreshold but looks like it's the current logic already?

	if (getTPS(PASS_ENGINE_PARAMETER_SIGNATURE) > boardConfiguration->idlePidDeactivationTpsThreshold) {
		// just leave IAC position as is
		return currentIdlePosition;
	}

**Comment by rusefi** [comment]
@metra52  please attach a log showing a drop in idlePosition

**Comment by stefanst** [comment]
Last idle valve position held is not always the correct one to fall back to. Engine conditions may have changed in the meantime. Idle Valve should not return to last known position, but to an "initial values" table. Initial values should be based on coolant temp and desired idle RPM. A modifier for manifold air temp would also be useful if the value is available.

**Comment by metra52** [comment]
![image](https://user-images.githubusercontent.com/1126563/33400480-53279efc-d567-11e7-8ee6-cbb2ef1e19c4.png)

the first push on the gas (green color,) the regulator drops from 20 percent to 5 (red line) and the RPM fall down (yellow line) then I throttle pressed so that the machine does not stoped

**Comment by metra52** [comment]
@stefanst in the rusefi firmware not table with initial values for idle valve. in this case we hav only manual position and CLT multiplier

**Comment by metra52** [comment]
on image we saw that idle valve position after decceleration TPS change to more less than before acceleration

**Comment by metra52** [comment]
View from 898sec. This is log file
[cold start.zip](https://github.com/rusefi/rusefi/files/1515785/cold.start.zip)

**Comment by metra52** [comment]
CurrentTune
[CurrentTune.zip](https://github.com/rusefi/rusefi/files/1515796/CurrentTune.zip)

**Comment by andreika-git** [comment]
#589

**Comment by mck1117** [comment]
this was fixed long ago
