### ISSUE TITLE
LTS: firmware matcher needs to learn to migrate

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#5015]
rusEFI console autoupdate feature has protection against accidental update of for instance MREF4 binary into proteusF7

At the moment that logic does not handle old vs new bundle name, also how would it handle branch switch?

![image](https://user-images.githubusercontent.com/48498823/215484989-638b3a16-7999-4318-8286-8847cbde25c7.png)

**Comment by rusefillc** [comment]
@chuckwagoncomputing you said you java now? :)

**Comment by rusefillc** [comment]
``proteus_f7`` comes as bundle part of ``#define TS_SIGNATURE "rusEFI master.2023.01.30.proteus_f7.3726161684"``

We need a new terminology I guess ``proteus_f7`` is bundle TYPE and ``rusefi.snapshot.proteus_f7`` is FULL bundle name?

**Comment by chuckwagoncomputing** [comment]
Re: Terminology
I suggest `proteus_f7` is "bundle target"

**Comment by rusefillc** [comment]
Separate issue #5016

I am making progress on this one here hope to push soon.
