### ISSUE TITLE
No load over 250kpa on Generic PWM

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#5026]
![image](https://user-images.githubusercontent.com/5685108/216408107-ec9335a6-f7ee-4040-bb9d-0db740f59ecb.png)

Can I have more than 250 load? It's ok if it's  in multiples of 2

**Comment by rusefillc** [comment]
@ElDominio how far would you like to go?

**Comment by ElDominio** [comment]
We need negative numbers, so maybe multiples of 5?

-635 to 635 ?

**Comment by rusefillc** [comment]
So either way it's an incompatible change.

We can expand this field to be two bytes not just play with scale

@mck1117 what do you think?
