### ISSUE TITLE
Allow MAP as Y axis on boost control

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#5027]
Have something like "override boost table load axis" with MAP or any other variable, to be used in open loop boost

**Comment by rusefillc** [comment]
@ElDominio please help by following https://xyproblem.info/

I definitely know that my preference is to be in the loop and understand what is done _why_. As is this ticket commands without providing context.

**Comment by rusefillc** [comment]
thank you @ElDominio I get it now!

**Comment by ElDominio** [comment]
Hi i'm MAP as Y axis in open loop boost table again

**Comment by ElDominio** [comment]
This was done
