### ISSUE TITLE
Selectable CanBus channel for WBO inputs

### ISSUE THREAD

**Issue by NMSTEC** [rusefi/rusefi#5028]
Need to transfer WBO to Can2. 
Unable to find option in TS regarding this. 

I presume will need added switch for rusefi broadcast on channel 1 or 2, or 1 & 2.

**Comment by mck1117** [comment]
> I presume will need added switch for rusefi broadcast on channel 1 or 2, or 1 & 2.

You can already pick which bus gets the broadcast:

![image](https://user-images.githubusercontent.com/568254/220051166-7fe35b71-3588-422a-8ff9-9df288ca0f8b.png)
