### ISSUE TITLE
Antilag switch pin mode was ignored

### ISSUE THREAD

**Issue by Benjamin-neo** [rusefi/rusefi#5036]
Antilag
Antilag activation by pin state always on no. (test on different pin, pullup, pulldown)
LaunchControl have same fonctionnality and work.

**Comment by rusefillc** [comment]
@Benjamin-neo is this tested on bench or real car? Any content you can share build thread pictures logs videos?

**Comment by Benjamin-neo** [comment]
tested on car, and on bench to tested on different pin to known if problem is hadrware or firmware. have look to compare with lauch same fonction, bug is in only on antilag ALSactivate pin state doesn't change .I dont tell antilag doesnt work , I report bug only in antilag activation by switch pin, all work expect ALSactivationPinstate

**Comment by rusefillc** [comment]
@Benjamin-neo glad to hear tested on car, looking to see more info on the forum

**Comment by rusefillc** [comment]
@Benjamin-neo will look into your bug report

**Comment by Benjamin-neo** [comment]
@rusefillc yes will post more on forum when project will ready.
For the bug, I have look at more, the problem is in activation mode ( switch Input/ always active). it seem to be simple inverted. maybe just need correct .ini
I let you see, I hope this info will help you

**Comment by rusefillc** [comment]
@TurboMarian looks like ALSActivatePinMode field was never used?

**Comment by rusefillc** [comment]
@Benjamin-neo I've made a change please try https://rusefi.com/build_server/ no sooner than 20 minutes from now :)

**Comment by Benjamin-neo** [comment]
@rusefillc 
I have look at and test Turbomarian , here is solution for switch antilag
![soluce](https://user-images.githubusercontent.com/85869292/217358514-18b58c03-8f1d-4905-8848-eccf0a39e87d.png)

**Comment by Benjamin-neo** [comment]
Have test f407 from bundle, doesnt work.
test with previous version and just != instead of == . and work perfectly

**Comment by rusefillc** [comment]
Well I do not get it

ALSActivatePinMode was not used I assume it's wrong for ALSActivatePinMode to be not used?

Also the != or == please someone explain in human words

**Comment by Benjamin-neo** [comment]
yes it's wrong for ALSActivatePinMode.
In file [firmware/controllers/algo/antilag_system.cpp]
turbomarian has only made on change == to !=

isALSSwitchActivated = engineConfiguration->antiLagActivationMode != SWITCH_INPUT_ANTILAG;

Just this edit solve the problem, als can be use with switch activation, pin is correctly selected, pullup pulldown , invert.. all this thing work . test on bench on multiple pin.
Als fonction is better on switch instead of always. als it's not safer for turbo and exhaust

**Comment by rusefillc** [comment]
@TurboMarian i have a feeling that "!=" random change was not addressing root cause of the issue. Clearly the code was intended to have "=="

```
typedef enum __attribute__ ((__packed__)) {
	SWITCH_INPUT_ANTILAG = 0,
	ALWAYS_ON_ANTILAG = 1,
} antiLagActivationMode_e;
```

```
    #define antiLagActivationMode_e_enum "Always Active", "Switch Input"
```

root cause: .ini file texts do not match enum values (always value "1" in enum versus value "0" in ini)

@TurboMarian please please please get to root causes not lucky hacks

**Comment by rusefillc** [comment]
@Benjamin-neo please update firmware and update TS project to load fixed .ini file

**Comment by Benjamin-neo** [comment]
Hi, just test it. switch mode like it do. just a last little bug , you can see on screen, while switch is select we can set pin , pull mode, invert, we can setting while select active always. test on last bundle f407 and .ini dowload with bundle. you can see sw on screenshot
![little bug](https://user-images.githubusercontent.com/85869292/217541196-4d708b8c-f4be-4d69-881a-c6ff587309ef.png)

**Comment by rusefillc** [comment]
@Benjamin-neo plz try latest .ini file (required latest firmware just to get latest signature)
