### ISSUE TITLE
cltIdleCorr mess

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#504]
At the moment cltIdleCorr is used as IAC duty cycle/position correction in manual mode, and as target RPM multiplier in automatic idle mode.

RPM multiplier is not super convinient, also we have a mess between cranking and auto mode. we need to reduce confusion

**Comment by darxfame** [comment]
Мы вот это разве уже не решили? сделав отдельную табличку для ПИДа и оставив мануал мультиплаер для ручного режима

**Comment by mck1117** [comment]
this is no longer true, they have their own tables
