### ISSUE TITLE
Is cranking Fuel CLT multiplier not working correctly?

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#5045]
![image](https://user-images.githubusercontent.com/5685108/217297965-27cbac67-a2f4-446c-9055-97c0bc4cd1bc.png)

Doesn't show as part of the total fuel multiplication?

**Comment by rusefillc** [comment]
cranking and running fuel is calculated totally differently. please raise your cranking limit, please look at cranking gauges which we probably do not have let me look :)

**Comment by ElDominio** [comment]
Cranking limit is 400RPM

**Comment by rusefillc** [comment]
@ElDominio I now suspect that we have crap in crap out situation, specifically I have no idea which correction you are talking about since stuff is truncated. based on bad info and bad brain I produce bad answers

**Comment by ElDominio** [comment]
![image](https://user-images.githubusercontent.com/5685108/217302990-70a21f18-63d9-44bb-9891-4038e10365aa.png)
This is the table is shown in the screenshot

![image](https://user-images.githubusercontent.com/5685108/217303308-5c45c15b-3f59-4f10-aafe-d2b865a59018.png)
Current cranking settings

**Comment by rusefillc** [comment]
@ElDominio please help by mentioning CLT in ticket title

**Comment by ElDominio** [comment]
Done

**Comment by ElDominio** [comment]
says done right there so i'm going to believe past me
