### ISSUE TITLE
auto-calibrated ETB overheats TLE9201 on 4chan

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#5060]
same issue on 4chan rev C and latest 4chan rev F
EXP-1270 small battery maybe it's discharged note VBatt going doing

https://rusefi.com/online/view.php?msq=1393

[ETB-overheat.zip](https://github.com/rusefi/rusefi/files/10718099/ETB-overheat.zip)

![image](https://user-images.githubusercontent.com/48498823/218356989-e372e699-ac78-4b50-a3d6-fffcc88fedc7.png)

**Comment by rusefillc** [comment]
added regulated power supply to the battery
swapped this VAG ETB for same VAG ETB

same result - 4chan rev F is overheating

same

**Comment by rusefillc** [comment]
happy Proteus F7 setup

https://rusefi.com/online/view.php?msq=1394

log https://rusefi.com/online/view.php?log=1165


![image](https://user-images.githubusercontent.com/48498823/218371404-fcc3f642-6cf5-4c11-886d-e04ce051c4ca.png)

**Comment by rusefillc** [comment]
Hold on, the happy log and perfect ETB above is with DEFAULT PID settings https://rusefi.com/online/view.php?msq=1394&dialog=etbDialog

I've hit ETB auto-tune and only gave it a second to run. BOOM! I got lame PID settings which have me insane ETB duty rate of change and I got Proteus h-bridge shut down on me.

Next I run ETB auto-tune again this time longer say 10 seconds. And now Proteus has legit healthy PID settings.

**Comment by rusefillc** [comment]
Ok let's retrace steps

4chan, manually reverting PID settings to default.

https://rusefi.com/online/view.php?msq=1395

same (?) PID settings behave way worse on 4chan comparing with Proteus - that is hopefully nicely documented now

[2023-02-12_23.45.44.mlg.zip](https://github.com/rusefi/rusefi/files/10718868/2023-02-12_23.45.44.mlg.zip)

Allow me not to document but it looks like 4chan is unable to get nice ETB pid regardless how long I run auto tune.

**Comment by rusefillc** [comment]
Ohh @ElDominio confirms stuff https://github.com/rusefi/alphax-4chan/issues/100

**Comment by mck1117** [comment]
Why is vbatt changing so much? this suggests that you have a power supply problem.
