### ISSUE TITLE
ETB auto-calibrate usability: both buttons should not be enabled at the same time

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#5061]
At the moment both "start ETB pin autotune" and "stop ETB pin autotune" buttons are always or often enabled at the same time.

Would be nice for buttons to know current state of the process. If we are NOT tuning - start should be enabled, stop should be disabled

while we are tuning start should be DISABLED and stop should be ENABLED

![image](https://user-images.githubusercontent.com/48498823/218373860-1771032f-f25b-41d4-bb24-31e86d398e89.png)

**Comment by rusefillc** [comment]
@nmschulte is this by any chance something you could help with?

**Comment by nmschulte** [comment]
On it; free to assign to me.

**Comment by rusefillc** [comment]
@nmschulte you would need to expose "isAutoTuneRunning" bit output for UI to use it for conditional logic

see into existing .txt files maybe we even have the bit already. maybe only UI change is needed

**Comment by nmschulte** [comment]
Cool.  While researching, I found this, semi-related ...
https://github.com/rusefi/rusefi/blob/master/firmware/controllers/actuators/electronic_throttle.cpp#L1036

which lead to this (ex. `isFanOn`) ... is this file still deprecated; what's the alternative?
https://github.com/rusefi/rusefi/blob/master/firmware/console/binary/output_channels.txt#L4

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi/commit/ce3cfc89c19286b16b1e9790d6ac30f457b8a678

**Comment by rusefillc** [comment]
DC vs ETB is a much much bigger fish to fry :(

**Comment by nmschulte** [comment]
It looks like `calibrationMode` already outputs the status, so that's a win.

"DC" means "deprecated" or ?

**Comment by rusefillc** [comment]
DC as https://en.wikipedia.org/wiki/DC_motor


like DC motor wastegate code flow should probably NOT go through electronic_throttle.cpp right?
