### ISSUE TITLE
build-firmware (f429-discovery) fails to compile "LSE frequency not defined"

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#5065]
To reproduce on local branch remove all skip-rate I assume there is a chance to see other configurations failing as well

https://github.com/rusefi/rusefi/actions/runs/4160565754/jobs/7197659625

**Comment by rusefillc** [comment]
@nmschulte please help

**Comment by nmschulte** [comment]
This can be corrected in two ways:
1) define non-zero `STM32_LSECLK` value and allow the enablement to timeout
2) disable the STM32 LSE (and enablement timeout flow) on this board

I performed #1 here, let me know if I should do #2 instead.

**Comment by nmschulte** [comment]
So, looking closer, this diverges from ChibiOS setup; to stay consistent we should do #2 instead:
https://github.com/rusefi/ChibiOS/blob/6b154adfaa56afe7570a19bbce552d2e7ea9b891/os/hal/boards/ST_STM32F4_DISCOVERY/board.h#L44

I'm happy to switch if we want to remain consistent, but I suspect this board config in ChibiOS would fail too ...

**Comment by mck1117** [comment]
we don't need to stay consistent with chibi's board.h - that's the whole point of the LSE detection you implemented.

we have the logic to detect missing LSE, let's use it

**Comment by rusefillc** [comment]
@nmschulte it looks like f429-discovery compiles just fine on my end - I've poked github action which has build it just fine

**Comment by nmschulte** [comment]
Great.  It's also building for me: I had a stale docker build image w/ outdated build context.
