### ISSUE TITLE
2chan rev E SD card config

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#5067]
We shall confirm that 2chan rev E has SD configured and enabled

**Comment by andreika-git** [comment]
rev-E uses SPI1 for SD card and also uses SPI2 pins as CAN2 (available on the external connector on board). BUT we also have rev-D which uses SPI1 pins for CAN2.
I can enable SPI1 for SD card for all 2chan revisions for now, but I see a potential conflict here...

**Comment by rusefillc** [comment]
Hellen has that amazing board ID feature would it help?

**Comment by rusefillc** [comment]
like Hyundai has dynamic pinout between rev B and rec C

if dynamic is not possible, screw rev D and SD card on rev E has priority. CAN2 is an easter egg not official feature.
