### ISSUE TITLE
No rusefi*.ini file 

### ISSUE THREAD

**Issue by kdi11080** [rusefi/rusefi#5078]
rusefi_default_bundle don't have rusefi*. ini file

**Comment by rusefillc** [comment]
Related to https://github.com/rusefi/rusefi/issues/5016

Just removed rusefi_default_bundle from https://rusefi.com/build_server/ please use rusefi_bundle_f407-discovery.zip

@chuckwagoncomputing FYI

**Comment by rusefillc** [comment]
@kdi11080 do you have a build thread on the rusEFI forum? Please share some cool info about you project :)
