### ISSUE TITLE
Document rusEfi changes to Chibios & attach a patch

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#509]
In light of yet another ChibiOS migration we need to document all areas of changes rusEfi is making to ChibiOS and produce the current version of a patch file

rusefi_chibios_16.patch between https://github.com/rusefi/ChibiOS/tree/stable_16.1.x and https://github.com/rusefi/ChibiOS/tree/stable_rusefi

Вначале сделал две папки ChibiOS-stable_16.1.x и ChibiOS-stable_rusefi
А потом:
diff -uwr ChibiOS-stable_rusefi ChibiOS-stable_16.1.x > rusefi_chibios_16.patch

**Comment by rusefi** [comment]
See also #463

**Comment by rusefi** [comment]
@andreika-git any chance you can contribute the rusefi_chibios_16.patch file?

**Comment by andreika-git** [comment]
I'll try my best

**Comment by andreika-git** [comment]
Here we are:
[rusefi_custom_chibios.txt](https://github.com/rusefi/rusefi/files/1527661/rusefi_custom_chibios.txt)

[rusefi_chibios_16.patch.zip](https://github.com/rusefi/rusefi/files/1527664/rusefi_chibios_16.patch.zip)

**Comment by rusefi** [comment]
See also https://github.com/rusefi/rusefi/issues/65

**Comment by rusefi** [comment]
We had a good grip in this in firmware/docs folder
