### ISSUE TITLE
rusefi online does not have .ini for f407 discovery previously known as all or default

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#5091]
TS unable to download from https://rusefi.com/online/ini/? Looks because we have not uploaded anything?

![image](https://user-images.githubusercontent.com/48498823/219511015-8c410cdd-b17c-4578-b40d-0c012ccb5cae.png)

![image](https://user-images.githubusercontent.com/48498823/219511024-59231cc8-2b62-4177-b07c-5821d7f05d58.png)

![image](https://user-images.githubusercontent.com/48498823/219511049-c0019762-d1f4-4e50-82ca-aa22796394e7.png)

![image](https://user-images.githubusercontent.com/48498823/219511104-0a8fbbb9-d7f2-42b0-94f5-3fbd17868017.png)

**Comment by rusefillc** [comment]
@chuckwagoncomputing can you help?

**Comment by chuckwagoncomputing** [comment]
I apologize for the oversight. I thought https://github.com/rusefi/rusefi/blob/4d52a48efee6c984a3db9bceff1eb909a984ef94/firmware/gen_config_board.sh#L20-L24 check meant INI parameter wasn't needed. I'll look into it when I get a chance.

**Comment by chuckwagoncomputing** [comment]
Oh I see, ini-file is used in another step.
