### ISSUE TITLE
proteus F7 shows zero MSD in Windows 10

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#5097]
Proteus F7
* does not show virtual "help" disk is this bug or feature for F7 specifically?
* does not show SD card MSD

**Comment by rusefillc** [comment]
@nmschulte @mck1117 can you please test on your end? is this something with my desktops or boards, or is this a firmware issue?

**Comment by nmschulte** [comment]
I'll try and test this evening or tomorrow morning.

**Comment by mck1117** [comment]
SD card should work. It worked for me yesterday. Please check what you see in device manager? Old st driver instead of built in windows driver?

MSD should NOT work, see comment in efi features disabling it because 512k F7

**Comment by rusefillc** [comment]
* one Proteus F4 running snapshot shows SD card on Windows 11 upstairs

**Comment by mck1117** [comment]
On MM, what do SD indicators in TS show?

**Comment by rusefillc** [comment]
@mck1117 see https://github.com/rusefi/alphax-2chan/issues/84
