### ISSUE TITLE
Duplicated pin names 

### ISSUE THREAD

**Issue by chuckwagoncomputing** [rusefi/rusefi#5106]
Duplicated pin names in board mappings now result in a failed interactive pinout generation workflow.
There are currently 5 boards with this issue.

|yaml|pins|
|--------|-------|
|hellen/hellen-gm-e67/connectors/main.yaml|J4_4|
|hellen/hellen121nissan/connectors/main.yaml|51a, 77a|
|hellen/hellen154hyundai/connectors/main.yaml|K65|
|hellen/hellen64_miataNA6_94/connectors/main.yaml|1G, 3I|
|hellen/hellen72/connectors/main.yaml|4I|

**Comment by rusefillc** [comment]
@chuckwagoncomputing somehow I was not able to located miata duplicates but just pushed top three files at least

**Comment by chuckwagoncomputing** [comment]
I manually confirmed the last 2, the duplicates are right above each other.

**Comment by rusefillc** [comment]
@chuckwagoncomputing my bad, sorry
