### ISSUE TITLE
Feb20: 3rd ticket for 4g9x mess

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#5111]
@ElDominio says snapshot does not start 4g9x while Jan 9th was starting 4g9x 

Sibling of #5000 and #5092

**Comment by ElDominio** [comment]
![image](https://user-images.githubusercontent.com/5685108/220199018-c2d6a9aa-3650-4235-aa58-eceb63da9967.png)


car runs, not sure if timing on EVERY cylinder is ok, but on #1, it does run


[Uploading 2023-02-20_17.10.01.mlg.zip…]()

**Comment by ElDominio** [comment]
![image](https://user-images.githubusercontent.com/5685108/220200313-0ccedbe6-3c74-4827-81a6-8e761d17e94f.png)

[4g93 version 11 log.zip](https://github.com/rusefi/rusefi/files/10787839/4g93.version.11.log.zip)


coils look crazy, did not attempt to start

**Comment by ElDominio** [comment]
![image](https://user-images.githubusercontent.com/5685108/220201851-ae6cd4e9-57d7-4384-a824-bba3ac474a60.png)

[4g93 version 29.zip](https://github.com/rusefi/rusefi/files/10787924/4g93.version.29.zip)

also starts and runs; doesn't seem too different from mess 4

**Comment by ElDominio** [comment]
![image](https://user-images.githubusercontent.com/5685108/220202241-9eb1a206-06b1-4697-a9c2-8e4c7186d4a3.png)

[4g93 version 34.zip](https://github.com/rusefi/rusefi/files/10787934/4g93.version.34.zip)

also doesn't seem to different from mess 4 and 29, all have cylinder 1 at the same angle with timing light

**Comment by rusefillc** [comment]
trigger 11 gives us "CUSTOM_PRIMARY_TOO_MANY_TEETH = 9002" warning

**Comment by rusefillc** [comment]
trigger 11 coil schedule does not look healthy, instant RPM is insane

![image](https://user-images.githubusercontent.com/48498823/220204081-ca4628b4-d375-46e8-a1ed-684cfdbd9cb9.png)

**Comment by ElDominio** [comment]
[4g93 v11 logs.zip](https://github.com/rusefi/rusefi/files/10788073/4g93.v11.logs.zip)


logs in different modes in v11; 
cmp f means SECONDARY is FALSE, cmp t means SECONDARY is TRUE
ckp f means PRIMARY is FALSE, ckp t means PRIMARY is TRUE

**Comment by ElDominio** [comment]
![image](https://user-images.githubusercontent.com/5685108/220207721-c280a5c2-9d02-49a9-afd2-731e55397f76.png)

[custom tooth with vvt cam inverted cam true.zip](https://github.com/rusefi/rusefi/files/10788146/custom.tooth.with.vvt.cam.inverted.cam.true.zip)


VVT seems to change, angle so does ignition angle until VVT angle stops jumping around

**Comment by ElDominio** [comment]
![image](https://user-images.githubusercontent.com/5685108/220207766-554825bd-4c1c-4e41-9b4d-ed4fd46772ec.png)

[custom tooth with vvt cam inverted cam flse.zip](https://github.com/rusefi/rusefi/files/10788150/custom.tooth.with.vvt.cam.inverted.cam.flse.zip)


same deal

**Comment by rusefillc** [comment]
> [custom tooth with vvt cam inverted cam true.zip](https://github.com/rusefi/rusefi/files/10788146/custom.tooth.with.vvt.cam.inverted.cam.true.zip)
> 
> VVT seems to change, angle so does ignition angle until VVT angle stops jumping around

not amazing with weird start and double RPM

![image](https://user-images.githubusercontent.com/48498823/220210652-0eca34ee-ebc9-45d1-93ea-2cf12de57afd.png)

**Comment by rusefillc** [comment]
two cam true I would expect primary rise/fall to behave same and trigger gap pattern to be same

![image](https://user-images.githubusercontent.com/48498823/220213358-8ce09244-a963-4d04-b2e9-da4d150912b8.png)

![image](https://user-images.githubusercontent.com/48498823/220213363-d2c16fff-0cbf-412f-b783-db2a72f24f0b.png)

**Comment by ElDominio** [comment]
[redone v11 logs with power cycle between changes.zip](https://github.com/rusefi/rusefi/files/10788401/redone.v11.logs.with.power.cycle.between.changes.zip)

**Comment by rusefillc** [comment]
@mck1117 see two "cam=false" https://github.com/rusefi/rusefi/issues/5111#issuecomment-1437674127 logs above

I am at the end of my rope so I am wondering if magic constant 90 degrees in instantRpm calculator is messing with us here. Let's see if 135 would better https://github.com/rusefi/rusefi/commit/61eefa205b2034598f2bd31ef28f7934bcaffac5

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/220256024-217ddaed-222e-4aa7-858a-60c6b2256718.png)

new feature - trigger shape into regular  @ElDominio please make a new cranking log at highest data rate TS setting

![image](https://user-images.githubusercontent.com/48498823/220259748-304dbd6b-f366-489e-961c-a621f4ff6e56.png)

**Comment by ElDominio** [comment]
[4g93 v11 on feb21 with triggerChannels view.zip](https://github.com/rusefi/rusefi/files/10796417/4g93.v11.on.feb21.with.triggerChannels.view.zip)

log with newest snapshot in cranking

**Comment by ElDominio** [comment]
![image](https://user-images.githubusercontent.com/5685108/220439964-a6900c27-e902-40cc-beb9-103318ff39e2.png)

Overlay of https://github.com/rusefi/rusefi/issues/5111#issuecomment-1438907081 and this self stim log 

[selfstim.zip](https://github.com/rusefi/rusefi/files/10796871/selfstim.zip)

Green circles indicate places where stim vs reality align perfectly. The expected one vs reality seems spot on, why is ignition schedule crazy?

**Comment by ElDominio** [comment]
[trg75 cranking log both CRANK and CAM false C7 CAM set to primary.zip](https://github.com/rusefi/rusefi/files/10798742/trg75.cranking.log.both.CRANK.and.CAM.false.C7.CAM.set.to.primary.zip)


using trg75

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/220486494-b97b0cd3-3d7e-4d2a-8d34-4f88f4239924.png)

**Comment by rusefillc** [comment]
@ElDominio see how we have have vvtSyncGapRatio and then we do not have it @mck1117 any ideas why would we not have vvtSyncGapRatio any longer?

![image](https://user-images.githubusercontent.com/48498823/220492813-358adc23-daea-4fe6-a432-8a678f538681.png)

**Comment by rusefillc** [comment]
i think it's time to start moving vvt position, i think we break engine phase when crank happens unexpectedly

![image](https://user-images.githubusercontent.com/48498823/220493685-0d99439f-82ad-47e5-8441-aea07deeb395.png)

**Comment by ElDominio** [comment]
[vvt angle logs plus minus 60.zip](https://github.com/rusefi/rusefi/files/10799086/vvt.angle.logs.plus.minus.60.zip)

**Comment by ElDominio** [comment]
[ignition enabled vvt trigger.zip](https://github.com/rusefi/rusefi/files/10799123/ignition.enabled.vvt.trigger.zip)


using custom tooth 2 no missing, vvt mode 4g93

**Comment by rusefillc** [comment]
> [vvt angle logs plus minus 60.zip](https://github.com/rusefi/rusefi/files/10799086/vvt.angle.logs.plus.minus.60.zip)

WOW both show happy engine phase PROGRESS???

minus 60

![image](https://user-images.githubusercontent.com/48498823/220496439-2f8d40cf-adfe-4046-95e9-70a19e0d9071.png)

plus 60

![image](https://user-images.githubusercontent.com/48498823/220496473-07e3f50a-ff61-4932-9292-d51531a901b4.png)

**Comment by rusefillc** [comment]
> [ignition enabled vvt trigger.zip](https://github.com/rusefi/rusefi/files/10799123/ignition.enabled.vvt.trigger.zip)

again we are back crazy engine phase. is it just random? :(

![image](https://user-images.githubusercontent.com/48498823/220496587-0d54450e-14e8-4223-b288-1998156d696b.png)

**Comment by ElDominio** [comment]
[vvt logs plus minus 60 vvt mode 4g93.zip](https://github.com/rusefi/rusefi/files/10799170/vvt.logs.plus.minus.60.vvt.mode.4g93.zip)

**Comment by mck1117** [comment]
there's an extra tooth here that threw off sync until just after the cursor

![image](https://user-images.githubusercontent.com/568254/220497360-d0ada537-29ac-4ab1-811a-f9dfd36f47d0.png)

**Comment by rusefillc** [comment]
Yes, that's a smoking gun.

**Comment by mck1117** [comment]
extra blip is perfectly aligned with coil 1 firing, smells like hardware to me

![image](https://user-images.githubusercontent.com/568254/220498615-d6f83f90-1fcd-4e2b-b181-ec5b20b909e9.png)

**Comment by mck1117** [comment]
and once it re-syncs after that blip, firing order looks correct:

![image](https://user-images.githubusercontent.com/568254/220499147-e1b5da5e-5c24-4a2d-89bb-215849b838cd.png)

**Comment by rusefillc** [comment]
https://github.com/rusefi/alphax-4chan/issues/87 would be simplest option of alternative hardware

**Comment by ElDominio** [comment]
I know I'll get pushback for this but here I go

Can't we do something like, confirm CAM angle is consistent for 3 cycles then lock the VVT angle? That would work even if there's noise on startup (since it seems the noise only happens the first few cycles)

**Comment by ElDominio** [comment]
I just did a log to check

I can see the VVT angle is either -20, or -200, sometimes it moves by 180 degrees.

Attached are said log and its matching tune

[5 starts with different angles.zip](https://github.com/rusefi/rusefi/files/10832450/5.starts.with.different.angles.zip)

**Comment by rusefillc** [comment]
Technically yes, it looks like it's the spark noise specifically which causes noise thus technically some smarter software in fact might mitigate the issue.

But that's hella expensive in terms of software, testing and forever support. While we still have a hope for HW progress I would prefer to give that hardware approach a try. I hope to ship you a board with hacks tomorrow https://github.com/rusefi/alphax-4chan/issues/102

**Comment by ElDominio** [comment]
https://rusefi.com/online/view.php?log=1178

Log with new HW mod 
tune is wadjacent to log on rusefi online

**Comment by ElDominio** [comment]
second log, ignition on https://rusefi.com/online/view.php?log=1179

**Comment by rusefillc** [comment]
might be OK

![image](https://user-images.githubusercontent.com/48498823/222577855-eeec252e-bd3c-4d0e-b930-d7471ac74be3.png)

**Comment by mck1117** [comment]
crank looks clean, still maybe some vvt channel noise

![image](https://user-images.githubusercontent.com/568254/222579264-6bb906fc-62c0-41a6-b378-adacd9fb1505.png)

**Comment by ElDominio** [comment]
[changing angle incorrect orders.zip](https://github.com/rusefi/rusefi/files/10876546/changing.angle.incorrect.orders.zip)

sometimes, changing the trigger angle by 5 degrees makes the timing mark completley vanish

there seems to be a magic point in trigger angle where it goes completley out of line
titles of logs are descriptive

**Comment by ElDominio** [comment]
CAR TURNED ON

Log with matching tune: https://rusefi.com/online/view.php?log=1180

Still problems during cranking
https://rusefi.com/online/view.php?log=1181

**Comment by rusefillc** [comment]
first I suspected bad cam signal on top but then I say battery dips?

![image](https://user-images.githubusercontent.com/48498823/222925313-1853f021-125f-4829-af80-ce90eec6420f.png)

**Comment by ElDominio** [comment]
i think battery dips are when the engine backfires because of incorrect ignition timing while starting; since the engine gets "stuck" and the starter is in pain

**Comment by ElDominio** [comment]
I expected jan9th to run on cam only, not both wheels. Would like to see if what I tested was real or just my imagination. Very close to grinding one tooth off and running as 2+1 trigger.

**Comment by rusefillc** [comment]
@ElDominio i do not get the plan but here are the binaries

https://rusefi.com/temp/jan09-strange-approach/

**Comment by ElDominio** [comment]
https://rusefi.com/online/view.php?log=1189

Log with most recent snapshot

https://rusefi.com/online/view.php?log=1190

also log with most recent snapshot

**Comment by ElDominio** [comment]
So i have confirmed this cam wheel is same as late gen 4g63, which means i have another car to test on; the different trigger is 4G94 (so, 4G63 and 4G93 use the SAME trigger)

The pattern on 4G63/4G93 SHOULD be the same as Miata NA, but divided in Cam/Crank (phyiscally apart)

We ground off one tooth to use Single Tooth, but it still has sync issues.

https://rusefi.com/online/view.php?log=1191

**Comment by ElDominio** [comment]
![image](https://user-images.githubusercontent.com/5685108/223562743-f7dee78a-37dc-486d-bd0f-6505a95495c1.png)

**Comment by ElDominio** [comment]
![image](https://user-images.githubusercontent.com/5685108/223563204-1dc3937b-94f0-44b2-9999-5c21badec855.png)

**Comment by ElDominio** [comment]
![image](https://user-images.githubusercontent.com/5685108/223564924-f3c5ffad-c2d3-4a72-9e4a-0e82001fcac8.png)

**Comment by ElDominio** [comment]
![image](https://user-images.githubusercontent.com/5685108/223565930-382d10b4-8e42-4941-a854-7190ba3d0c3f.png)
 
Camcounter increased even if there is no cam signal in that point?

**Comment by rusefillc** [comment]
@ElDominio was it C3+C7 previously? Is it still C3+C7 or has something changed? Any additional info on pinout situation?

**Comment by rusefillc** [comment]
It's very hard for me. Looks like problem statement is slowly shifting and I am very very lost.

At this point it seems reasonable to assume hardware issues. Let's make an adapter for Proteus to be directly in place of 4chan using 4chan harness.

Reminder that @ElDominio has three sets of 8chan and three sets of Proteus plugs exactly for this purpose.

**Comment by ElDominio** [comment]
new logs with modified 4chan
[DataLogs.zip](https://github.com/rusefi/rusefi/files/11067184/DataLogs.zip)

**Comment by rusefillc** [comment]
@ElDominio need executive summary please. Same? Good? Bad?

**Comment by rusefillc** [comment]
@ElDominio https://github.com/rusefi/alphax-4chan/issues/104

![image](https://user-images.githubusercontent.com/48498823/227661771-8875db08-05e3-4b02-bdad-f5f7cd75e11a.png)

**Comment by ElDominio** [comment]
Behavior on one of the modified ecus is the same as unmodified

I have noticed that it changes by 540 degrees (180*3)
![image](https://user-images.githubusercontent.com/5685108/227745787-2d4ca3b1-d92a-46a1-ab7c-01ce5d4ba41a.png)

![image](https://user-images.githubusercontent.com/5685108/227745834-0097c29e-4902-4faa-8287-0434c7c50212.png)

![image](https://user-images.githubusercontent.com/5685108/227745903-24a437b4-4a10-4530-a275-265d208c515c.png)

**Comment by rusefillc** [comment]
@ElDominio is it easy to test with the other board?

bad news this one says C200 on the sticker i.e. this one is the "more" modified board :(

**Comment by ElDominio** [comment]
I'll try to get the ecu tomorrow to test

**Comment by ElDominio** [comment]
Got ecu, will test tomorrow

**Comment by ElDominio** [comment]
Other modded ECU (already tested one version of mod)
4 starts in log, final start has same angle problem as previous ECU (540 degrees apart)

![image](https://user-images.githubusercontent.com/5685108/228635812-a69e46dc-ae9f-4b45-9553-10a0d66a4392.png)
Since I am getting this error, here is the current tune in a zip file
[CurrentTune.zip](https://github.com/rusefi/rusefi/files/11104369/CurrentTune.zip)

And here is log of current ECU
[othermoddedecucrankinglog.zip](https://github.com/rusefi/rusefi/files/11104373/othermoddedecucrankinglog.zip)

**Comment by rusefillc** [comment]
and unmodified we have somewhere?

**Comment by ElDominio** [comment]
![IMG_20230329_144050.jpg](https://user-images.githubusercontent.com/5685108/228636509-e36144b2-1175-4615-aa0b-f49a5265f057.jpg)

Current ecu being tested

**Comment by ElDominio** [comment]
all data before you shipped modified ECU's is unmodified

**Comment by ElDominio** [comment]
Unsolicited test:

Using Miata NA, car cranks fine, once it almost starts, there is a trigger error
[usingMiataNAalmoststartsbuttriggererror.zip](https://github.com/rusefi/rusefi/files/11116851/usingMiataNAalmoststartsbuttriggererror.zip)

**Comment by rusefillc** [comment]
#5210 created for separate minor issue

**Comment by rusefillc** [comment]
![WhatsApp Image 2023-03-30 at 22 01 51](https://user-images.githubusercontent.com/48498823/229006040-36945356-031c-4bee-99ac-65aa5c091c1e.jpg)


not helping since we had at least two minor improvement

* https://github.com/rusefi/rusefi/issues/5193
* https://github.com/rusefi/rusefi/issues/5152
