### ISSUE TITLE
setEtbAdd explanation not very good

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#5118]
says "percent: e.g. 10 for 10%"

so for example, if i have 5% current TPS and i write "setEtbAdd(5)", do I get 5.5 (5% more TPS than before) or do I get 5+5 = 10% TPS (this is what it actually does and it should stay this way)

Documentation is not clear if one or the other, an example helps
"Adds the % inside the parenthesis to the current TPS, 
ex:
current TPS: 5%
setEtbAdd = 5

actual TPS = 10%

**Comment by rusefillc** [comment]
@ElDominio does https://github.com/rusefi/rusefi_documentation/pull/424/commits/63b1783a4f465529603a6a61f1269b5bd20e9725 help?
