### ISSUE TITLE
Custom trigger dialog? What adjustments do we like most?

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#5119]
pic from https://www.facebook.com/groups/rusEfi

![image](https://user-images.githubusercontent.com/48498823/220480354-1af89a07-6a26-4061-ae7b-a5bea7b0780a.png)

**Comment by mck1117** [comment]
that's a completely different ini (and looks like it's pretty old?), we've never had a menu called "E-Throttle"

**Comment by mck1117** [comment]
hello friend 
![image](https://user-images.githubusercontent.com/568254/220482234-cc376872-c28c-4c6f-b43e-f251aebfd950.png)

**Comment by rusefillc** [comment]
Hello @960

**Comment by mck1117** [comment]
this is basically what I did in #5077

**Comment by rusefillc** [comment]
@ElDominio opinions?

**Comment by ElDominio** [comment]
Uuuh the current iteration i like very much, is more change necessary?

**Comment by mck1117** [comment]
> Uuuh the current iteration i like very much, is more change necessary?

Good answer!
