### ISSUE TITLE
weird: happy running car shows repetitive pattern of unrealistic vvtSyncGapRatio

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#5152]
gap ratio 2000 all the time on running engine? is that some scaling issue or what?

see https://github.com/rusefi/rusefi/issues/5111#issuecomment-1454034075

![image](https://user-images.githubusercontent.com/48498823/222920631-b35b418d-b7a6-4654-9edd-7cc92e754179.png)

**Comment by rusefillc** [comment]
@ElDominio I believe that in terms of cost/benefit this is the most important issue

Please provide a log with snapshot software I am looking for data from new debug field

**Comment by rusefillc** [comment]
#5193

**Comment by andreika-git** [comment]
Unrealistic vvtSyncGapRatio means we have very low toothDuration sometimes, like only 8-22 ticks! This means that a reentrant protection for hwHandleVvtCamSignal() might help...

**Comment by rusefillc** [comment]
> Unrealistic vvtSyncGapRatio means we have very low toothDuration sometimes, like only 8-22 ticks! This means that a reentrant protection for hwHandleVvtCamSignal() might help...

but in https://rusefi.com/online/view.php?log=1181 it's not _sometimes_ it's _always_ in a very repetitive way. The clear nice pattern and car running makes me think that the screenshot about is totally NOT about the noise

**Comment by mck1117** [comment]
this is absolutely hardware noise:

![image](https://user-images.githubusercontent.com/568254/226750925-5816a4c3-fb34-48e2-b75d-9f750da6edca.png)

there are 3 falling edges here when there should be exactly 1

**Comment by mck1117** [comment]
last row red/green are number of rise/fall events that happened since the last sample, scaled so that 0 and 1 (expected values) are hidden, all spikes are duplicate edges

![image](https://user-images.githubusercontent.com/568254/226752496-3ca74f54-557a-4195-81d0-4143421b5d21.png)

**Comment by rusefillc** [comment]
Wow, sounds like more error validation is needed for insane vvt ratio

**Comment by rusefillc** [comment]
damn I am blind :( there is an area of reasonable ratios from 0.2 to 4

![image](https://user-images.githubusercontent.com/48498823/226766401-1c8277b4-f71b-4778-b31a-46220c74ac15.png)

**Comment by mck1117** [comment]
I don't think you meant to close

**Comment by rusefillc** [comment]
I did mean to close. Better error detection was implemented here, smarter noise processing out of scope, hw issues would be be hardware-specific tickets.
