### ISSUE TITLE
"different user levels in TS" idea "expert mode" "pnp mode" "hide hardware" uiMode

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#5154]
https://rusefi.com/forum/viewtopic.php?p=47291#p47291

```
Also not sure it is possible but having a way to have different user levels in TS would be awesome. A basic tuning only setting would be nice. Or a drop down that has the core tuning things. As once you have dialed starting, and basic things in most are spending their time tuning only a handful of tables.
Tuning:
--FUEL VE
--IGNITION ADVANCE
--IDLE TUNING
--TEMP MODIFIERS
--ETC

These are just ideas and far from needed. I look very much at the end user. Some users want to play with the ecu/etc but many just want to tune their car. The former will be on these forums and groups the later is a much bigger market and the experience/UI needs to be dead simple and easy for them. I do think that is where others....speeduino in particular really shine. It's easy. Similar to the iPhone vs Android debate. While you can DO more with the android the iPhone just works to do the thing.
```

**Comment by rusefillc** [comment]
We have at least two options I can think of:
* cheaper option: a drop down "Simple/Full" or even "Setup/Tuning/Full" which would allow us to hide individual fields/panels/menues based on selected category. Pretty much "full" is current layout and we can subtract from it based on user drop down.
* expensive option: multiple completely parallel .ini files. Probably unrealistic too much effort

@ElDominio what do you think?

**Comment by classicdaily** [comment]
I like the cheaper option.   Yes FULL would be how it is now.  Even Just Tuning/Full might be enough  I will think on that too.

**Comment by dron0gus** [comment]
1. Installer mode - output/input assignment, triggers, etc.
2. Tuner mode - tables, curves, ets
3. Full mode.

**Comment by ElDominio** [comment]
I also like the cheaper option, or what @dron0gus said

Many people's brains melt when seeing things like PID's and having those options available to most of them creates confusion.

Would the menus be completely hidden or just grayed out?

**Comment by rusefillc** [comment]
could work together with https://github.com/rusefi/rusefi/issues/4420
