### ISSUE TITLE
Even 'only' build should produce proper bundle/autoupdate/upload .ini

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#5169]
The amazing 'only:xxx' feature should behave closer to normal build, just only for one matrix entry

**Comment by chuckwagoncomputing** [comment]
I'm confused about what you're trying to achieve here.
As far as I can tell, what you've done is enabled artifact upload for all pushes to master. Is that right?

**Comment by rusefillc** [comment]
Before change "only honda" would create not complete autoupdate of only honda

I want "only honda" to create full autoupdate of only honda

**Comment by chuckwagoncomputing** [comment]
Did your change fix it?
If so, can you explain how?

**Comment by chuckwagoncomputing** [comment]
Also, can you link a run that did not work correctly?

**Comment by rusefillc** [comment]
> before: https://github.com/rusefi/rusefi/actions/runs/4379928313/jobs/7666409230

problem statement: there was firmware build but autoupdate bundle was not uploaded, also .ini was not uploaded

![image](https://user-images.githubusercontent.com/48498823/224326909-a0a27d22-a5ae-4126-93d4-8b4fd45ce454.png)

after the change https://github.com/rusefi/rusefi/actions/runs/4380160678/jobs/7666920589 looks like it works as desired - there is both firmware and autoupdate bundle upload

**Comment by chuckwagoncomputing** [comment]
That run didn't upload bundles because it wasn't a push to master, it was a push to [2023-03-10](https://github.com/rusefi/rusefi/tree/2023-03-10)

**Comment by rusefillc** [comment]
We need a phone call :(

**Comment by rusefillc** [comment]
Something https://github.com/rusefi/rusefi/commit/b385756ce5bb9742887d8d4d0ddd734604d7885d

**Comment by rusefillc** [comment]
So funny thing https://github.com/rusefi/rusefi/commit/b385756ce5bb9742887d8d4d0ddd734604d7885d is a commit related to nightly tag and this has something to do with my problem.

**Comment by rusefillc** [comment]
I was watching github action job and it looks like I was watching the wrong output?

Q1: Do I just revert my change?
Q2: Do you want to report this to GH?

**Comment by chuckwagoncomputing** [comment]
Yep, I think that's what happened.

Yes, and yes.

**Comment by rusefillc** [comment]
Reverted by https://github.com/rusefi/rusefi/commit/336250469946624e05720c3ea8adf967b7b512c3

**Comment by chuckwagoncomputing** [comment]
Github has responded, and says this is "by design".
Good job, Microsoft.
