### ISSUE TITLE
Mar 9 4g results

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#5170]
@ElDominio has news

**Comment by ElDominio** [comment]
Test 1:
4chan with only one mod, which will be shipped back tomorrow, disconnected ignition coils. Signal still noisy, get double RPM sometimes

[no coils connected modded 4chan.zip](https://github.com/rusefi/rusefi/files/10937493/no.coils.connected.modded.4chan.zip)


Currently wiring test 2, 8chan. Will report back

**Comment by ElDominio** [comment]
Test 2:
8chan
seems to have no noise, have started more than 10 times without noise, still have coils disconnected,

[goodcrankinglog.zip](https://github.com/rusefi/rusefi/files/10937662/goodcrankinglog.zip)


 connecting coils to test
 connected
 testing
 log:
 
[connectedcoilsccranking.zip](https://github.com/rusefi/rusefi/files/10937670/connectedcoilsccranking.zip)


going to try to turn on car

**Comment by rusefillc** [comment]
Wow!

**Comment by ElDominio** [comment]
> Test 2: 8chan seems to have no noise, have started more than 10 times without noise, still have coils disconnected,
> 
> [goodcrankinglog.zip](https://github.com/rusefi/rusefi/files/10937662/goodcrankinglog.zip)
> 
> connecting coils to test connected testing log:
> 
> [connectedcoilsccranking.zip](https://github.com/rusefi/rusefi/files/10937670/connectedcoilsccranking.zip)
> 
> going to try to turn on car

noticed it was running semi-sequential when i have a one tooth cam
turned on "Require Cam/VVT sync for ignition" and I never have ignition.
I can see LED pulsing correcetly

tune: https://rusefi.com/online/index.php?vehicleName=TecoTest+8chan&user_id=675&sorts[uploadedMsq]=-1&sorts[uploadedLog]=-1

log: 
[interesting no crank sync.zip](https://github.com/rusefi/rusefi/files/10938381/interesting.no.crank.sync.zip)


*a new error has been found could not upload log to rusefi online; new ticket at 8chaan https://github.com/rusefi/alphax-8chan/issues/72

**Comment by rusefillc** [comment]
drama https://github.com/rusefi/alphax-8chan/issues/81 :(

**Comment by rusefillc** [comment]
@ElDominio for now please move to 5C hall 4 (with latest firmware)

https://github.com/rusefi/alphax-8chan/issues/77#issuecomment-1465427208

**Comment by ElDominio** [comment]
Noted, will update asap

**Comment by ElDominio** [comment]
https://rusefi.com/online/view.php?log=1199

https://rusefi.com/online/index.php?vehicleName=8chan+convert&user_id=675&sorts[uploadedMsq]=-1&sorts[uploadedLog]=-1

**Comment by ElDominio** [comment]
The timing light shows a different angle on starts where the VVT angle is not the same as last

**Comment by rusefillc** [comment]
Too many tickets closing this one @ElDominio
