### ISSUE TITLE
Not able to upload log to RusEFI online trg_err missing

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#5174]
![image](https://user-images.githubusercontent.com/5685108/224220703-a76ab157-e5cc-4504-8c1c-7af545e74cb4.png)

Only happened on an 8chan which I updated to today's snapshot

**Comment by rusefillc** [comment]
new occurrence of https://github.com/rusefi/web_backend/issues/158

**Comment by rusefillc** [comment]
long term fix https://github.com/rusefi/web_backend/issues/194

fixing by reverting for now
