### ISSUE TITLE
Some pins label on interactive pinout are screwed

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#5175]
![image](https://user-images.githubusercontent.com/5685108/224513455-62ce1757-818f-44cd-84ba-a0cf1274e1ed.png)

**Comment by rusefillc** [comment]
@ElDominio thank you! fixed

![image](https://user-images.githubusercontent.com/48498823/224524652-38138ae3-50c9-41fa-b067-2a06973e6d98.png)
