### ISSUE TITLE
Antilag input causes fatal on consecutive calibration changes

### ISSUE THREAD

**Issue by Fera31** [rusefi/rusefi#5180]
Proteus F7  Rev 0.7.0
conflict in als button sw
i try analog and digital . but is the same error
![image](https://user-images.githubusercontent.com/66860635/225017312-ed2dfcc2-d4c8-41d3-9e89-e28ef0409255.png)

**Comment by rusefillc** [comment]
@Fera31 I've just pushed the fix

please give automation 35 minutes and "rusefI_autoupdate" in 34 minutes from now, and update firmware on your unit.
