### ISSUE TITLE
provide_gcc to overwrite link

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#5190]
from facebook
i guess we should remove symlink before creating new one?

![image](https://user-images.githubusercontent.com/48498823/226232295-e265b0d5-bbf0-4803-b7db-48b12aa1a98a.png)

**Comment by rusefillc** [comment]
@chuckwagoncomputing just realized that I am not sure what does
``ln -s "${TMP_DIR}"/* "${COLLOQUIAL}"``
do exactly? does it create a BUNCH of symlinks?

**Comment by rusefillc** [comment]
Wow today I've learned!

**Comment by chuckwagoncomputing** [comment]
I had to test it, because I wasn't sure.
Re: this issue:
Adding the `-f` flag to ln would overwrite any existing file.

**Comment by rusefillc** [comment]
@chuckwagoncomputing do you approve https://github.com/rusefi/rusefi/commit/72682b587da3f94e262530509916f6f3c59fe2f8?
