### ISSUE TITLE
Poor timer explanation on Lua Wiki

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#5192]
what does
(variablename):reset(); 
do?

No explanation as to what Timer is (as self evident as this is), or how any of the ancillary functions work.
Are there more than getElapsedSeconds and reset()?

**Comment by rusefillc** [comment]
@ElDominio does https://github.com/rusefi/rusefi/wiki/Lua-Scripting#timer help?

there are no other methods

**Comment by ElDominio** [comment]
I think that's good enough
