### ISSUE TITLE
8chan Official well known idle stepper configuration

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#5197]
let's use stepper IAC on 8chan

**Comment by rusefillc** [comment]
See also https://github.com/rusefi/rusefi/issues/3661

**Comment by rusefillc** [comment]
17123852 Throttle Position Sensor + Idle Air Control Valve 17113598 For Chevy GM

![image](https://user-images.githubusercontent.com/48498823/227731041-d65290bc-b234-4d76-b26e-febad2b88e7e.png)

**Comment by andreika-git** [comment]
We don't have enough settings to configure the h-bridge stepper with two 9201s:

![image](https://user-images.githubusercontent.com/15104768/227767063-af221c18-8ebd-4cf2-b730-1b71c0096603.png)

We need an option to set useTwoWires = false. We already have it for ETB (etb_use_two_wires), and now we need it for the stepper. Maybe stepper_dc_use_two_wires?

**Comment by rusefillc** [comment]
@andreika-git can you please add code comment with human readable comment which pins are A which pins are B?

how do I figure out where to connect "high A" where do I connect "low A" i.e. what about A/B direction?

**Comment by rusefillc** [comment]
https://youtu.be/-DePdZhZXYU

https://rusefi.com/online/view.php?msq=1434
