### ISSUE TITLE
Pavel Mad Rat is touching FWD VQ engine

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#5201]
https://rusefi.com/online/view.php?msq=1433

https://rusefi.com/online/view.php?log=1206
https://rusefi.com/online/view.php?log=1207

**Comment by rusefillc** [comment]
https://en.wikipedia.org/wiki/Marussia_B-Series

**Comment by rusefillc** [comment]
trigger: engine phase pretty mad

![image](https://user-images.githubusercontent.com/48498823/227784991-df690961-e5b3-4e02-808e-004ecc6586f9.png)

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/227785196-9a3bc799-d947-4369-b793-c6b8f74e561c.png)

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/227786179-6492900d-652a-4928-aa77-5f3a3e0c2455.png)

**Comment by rusefillc** [comment]
See also https://github.com/rusefi/hellen121nissan-issues/issues/26

**Comment by rusefillc** [comment]
See https://github.com/rusefi/rusefi/issues/5202

**Comment by rusefillc** [comment]
https://rusefi.com/online/view.php?log=1208 much better with inverted CAM

![image](https://user-images.githubusercontent.com/48498823/227786836-dc930f4d-abf2-40e3-ab91-47fcf655c363.png)

**Comment by omidgheitani** [comment]
On Mar 26, 2023 7:36 PM, rusefillc ***@***.***> wrote:
https://rusefi.com/online/view.php?msq=1433
https://rusefi.com/online/view.php?log=1206
https://rusefi.com/online/view.php?log=1207
