### ISSUE TITLE
4g is symmetrical crank not just four stroke crank

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#5211]
![image](https://user-images.githubusercontent.com/48498823/229008115-bc895ffe-5daf-49ad-ab65-fb71415a6838.png)

![WhatsApp Image 2023-03-30 at 22 30 58](https://user-images.githubusercontent.com/48498823/229008133-ad82cf88-2e5c-458a-838a-0e1f188760f2.jpg)

VVT sync needs to know if crank has single (60/2) or double (miata NB) or tipple (vg35) or else symmetrical crank

at the moment 2/0 custom toothed wheel is not smart enough to declare itself FOUR_STROKE_SYMMETRICAL_CRANK_SENSOR

is this what upsets @ElDominio ?

**Comment by rusefillc** [comment]
New episode of #5111

@ElDominio please update all three boards to same latest snapshot

please use new "Mitsu 4G63 Crank" trigger

**Comment by ElDominio** [comment]
[new trigger log car turned on.zip](https://github.com/rusefi/rusefi/files/11128548/new.trigger.log.car.turned.on.zip)

Cranked 4 times, engine started twice in the log.
Might be due to tuning, will test on April 1

**Comment by ElDominio** [comment]
revB using new trigger:
[nonmodifiednewtrigger.zip](https://github.com/rusefi/rusefi/files/11130351/nonmodifiednewtrigger.zip)

revF with modified crank trigger
[modified ecu idle log.zip](https://github.com/rusefi/rusefi/files/11130352/modified.ecu.idle.log.zip)

**Comment by rusefillc** [comment]
@ElDominio which of two modified revF? do we need cap mod or not?

**Comment by ElDominio** [comment]
![IMG_20230329_144050.jpg](https://user-images.githubusercontent.com/5685108/229310989-defccae0-b7ab-41b8-88ec-7f1eabb77428.jpg)

This one is working
