### ISSUE TITLE
RPM Limit should have hysteresis 

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#5224]
(x) = hysterisis
(Y) = RPM limit (hard limit where spark/fuel is cut)

if (y) is 7200rpm, and (x) is 200rpm, 
when the ECU sees 7200rpm, fuel/ign will cut, and stay cut until 7200-200=7000rpm is reached

**Comment by rusefillc** [comment]
Part of #4529

**Comment by rusefillc** [comment]
@ElDominio i believe we can reduce confusion with the following cheap proposal:

As you know on rusEFI online you can link to specific dialog like https://rusefi.com/online/view.php?msq=1438&dialog=cltFuelCorrCurve

i suggest we mention similar URLs of relevant existing settings and spell out existing setting name and maybe even suggest how many new parameters with what suggested name should be added?

**Comment by ElDominio** [comment]
![image](https://user-images.githubusercontent.com/5685108/230664258-72aeeb55-ca8b-4ab8-94d9-32d13bae83a7.png)

Nothing specific opens for me?

**Comment by rusefillc** [comment]
Damn you are right some of these specific URLs are broken :( bug report https://github.com/rusefi/web_backend/issues/205

Try https://rusefi.com/online/view.php?msq=1438&dialog=ignitionSettings

**Comment by ElDominio** [comment]
![image](https://user-images.githubusercontent.com/5685108/230741567-b01002cf-0593-4007-9cb9-6c125a84bc0d.png)

something like this

https://rusefi.com/online/view.php?msq=1438&dialog=limitsAndFallback

in here
![image](https://user-images.githubusercontent.com/5685108/230741630-eb59142e-ada6-44b4-8d26-ef883dad606c.png)

**Comment by rusefillc** [comment]
@ElDominio please test we have https://github.com/rusefi/rusefi/pull/5228

**Comment by ElDominio** [comment]
![image](https://user-images.githubusercontent.com/5685108/231308212-5c43319e-2d7c-47af-8521-90c940fd2a8b.png)

This settings works
_________________________________

![image](https://user-images.githubusercontent.com/5685108/231308254-8b1ae94a-ac87-44a1-ad6c-90bbbd737b1e.png)

This has no rev limit

**Comment by rusefillc** [comment]
Closed with defect

**Comment by andreika-git** [comment]
> This log shows not working rev limit at start, then change to NOT clt related and it worked fine with hysteresis

1) In the settings screen I see hard limit 7200, but in the log I see 3050 RPM max. How can rev limit work when not clt related?

2) Can you explain the inconsistency between the current value on the graph (>7000) and table (2500) on your screenshot?

![image](https://user-images.githubusercontent.com/15104768/232131091-1eb7f455-ec93-4dc1-86ff-bf2ab8d32325.png)

**Comment by ElDominio** [comment]
1) I switched the setting while logging

2) I have absolutely no idea? I didn't edit the screenshot or anything
