### ISSUE TITLE
wow we have two separate per-cylinder trims?!

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#5237]
we have per-cylinder table
```
angle_t getCylinderIgnitionTrim(size_t cylinderNumber, int rpm, float ignitionLoad) {
	return interpolate3d(
		config->ignTrims[cylinderNumber].table,
		config->ignTrimLoadBins, ignitionLoad,
		config->ignTrimRpmBins, rpm
	);
}
```

and we have
```
	// Plus or minus any adjustment if this is an odd-fire engine
	auto adjustment = engineConfiguration->timing_offset_cylinder[cylinderNumber];
```

**Comment by rusefillc** [comment]
@mck1117 @ElDominio is this a feature or a bug?

**Comment by mck1117** [comment]
Feature! The cylinder offset is for your crankshaft (odd fire engines, etc) and the per cylinder tables are for tuning.

**Comment by ElDominio** [comment]
I used it for 180* angle 2 cylinder, can confirm

**Comment by mck1117** [comment]
Mark uses it for Harley too. The timing mark is actually not lined up any cylinder, one is 22.5 ahead and the other 22.5 behind.
