### ISSUE TITLE
VVL activation

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#5249]
The current way to activate VVL is using a Generic PWM table which is not very cool. 
This way makes the the VVL switch on and off when it activates and (maybe) falls a bit in RPM.

A simple option like this
![image](https://user-images.githubusercontent.com/5685108/233576431-721c781b-33ca-49ba-a506-0ba239ee327b.png)

Works, and add a TPS condition to not get it activating under a certain TPS or boost

**Comment by rusefillc** [comment]
@ElDominio what is VVL? :) variable valve lift? on what cars?

**Comment by ElDominio** [comment]
Yes, variable valve lift.

Toyota 2ZZ engine

**Comment by ElDominio** [comment]
Also applies to K series.

Client had no idea how to use GP PWM table, this would greatly benefit them

**Comment by Zazins** [comment]
This is basicly the same as I was thinking at #5407.
This is great way to do that as most ecu in market do it and for most of people easy to understand.

**Comment by ElDominio** [comment]
Still relevant

**Comment by ElDominio** [comment]
this should be tagged project-k

**Comment by ElDominio** [comment]
this is also a clone, i will close and focus on #5704
