### ISSUE TITLE
Negative timing is not displayed correctly

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#5250]
Relevant log https://rusefi.com/online/view.php?log=1220

At 1.6s you can see -595 degrees of timing. Only happens when negative values of timing are chosen (putting 0 degrees shows zero degrees, less than that shows crazy values) 
are these even real?

**Comment by rusefillc** [comment]
We have https://github.com/rusefi/rusefi/commit/b35902ce35a760ee58ca81b3ea92286e528d1ad9 but not sure if related

**Comment by ElDominio** [comment]
still relevant

**Comment by rusefillc** [comment]
![image](https://github.com/rusefi/rusefi/assets/48498823/180ce1de-6c50-46ca-b39c-469a2efe4616)
