### ISSUE TITLE
Ford Coyote VVT Decoder

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#5275]
Here is an oscope log
[newerckplog.zip](https://github.com/rusefi/rusefi/files/11469970/newerckplog.zip)

Here is a picture of an oscope with a LinkECU
https://user-images.githubusercontent.com/5685108/237802589-19142f27-6f60-4c18-838a-408e6f7845d8.jpg

**Comment by rusefillc** [comment]
![image](https://github.com/rusefi/rusefi/assets/48498823/ce832d10-6f10-4de9-9535-6453f37ac150)
![image](https://github.com/rusefi/rusefi/assets/48498823/af5e35d9-df58-4c25-9cb7-ac88933af114)

two of them have two wires, two of them have three
![WhatsApp Image 2023-05-13 at 11 24 44](https://github.com/rusefi/rusefi/assets/48498823/51230d6b-8de4-4529-b0ff-c99e51ed635b)
![WhatsApp Image 2023-05-13 at 11 25 54](https://github.com/rusefi/rusefi/assets/48498823/747437a6-a019-4c38-83b6-471215de9a54)

**Comment by rusefillc** [comment]
So we see lazy hall?

![image](https://github.com/rusefi/rusefi/assets/48498823/f2f7429d-883e-404f-83eb-87a80c4c7dec)

**Comment by rusefillc** [comment]
> So we see lazy hall?
>

Our hw is different could be falling or rising or inverted in RE, we just have to try all combos and compare vvt gap ratio log with expected sequence

**Comment by rusefillc** [comment]
Expected gap sequence see https://github.com/rusefi/rusefi/wiki/All-Supported-Triggers#ford-coyote-vvt

**Comment by ElDominio** [comment]
No VVT reading, I'm going to see if I have wired Hall cam and not VR cam and to what pin with oscope.

Log: https://rusefi.com/online/view.php?log=1234

**Comment by ElDominio** [comment]
Changed cable to hall input 3 and scoped![IMG_20230515_141209.jpg](https://github.com/rusefi/rusefi/assets/5685108/7f55db5b-e5f0-476a-9c27-c319be8101ca)



No input on rusefi console trigger counters are 0

**Comment by rusefillc** [comment]
@ElDominio @andreika-git I vaguely remember 8chan fab or BOM drama around hall pull-ups

was it https://github.com/rusefi/alphax-8chan/issues/41?

**Comment by ElDominio** [comment]
So, i turned it on and it read fine, but after a while it does not read again. I think it might have vibrated off R125

**Comment by ElDominio** [comment]
Tried new modified 8chan"

i could only see 31A producing anything useable, but still no reading
relevant tune: 
[CurrentTune.zip](https://github.com/rusefi/rusefi/files/11913334/CurrentTune.zip)

relevant log
[novvtsadface.zip](https://github.com/rusefi/rusefi/files/11913347/novvtsadface.zip)

I see VVT syncgapratio going up, maybe i needed to flip edge? Did not try that

**Comment by ElDominio** [comment]
Intake VVT reads! Only missing exhaust VVT test

**Comment by ElDominio** [comment]
I am pretty sure I provided exhaust VVT logic logs, i am commenting to bump

**Comment by rusefillc** [comment]
@ElDominio what's the status? shall we close?

**Comment by ElDominio** [comment]
Position is decoded correctly, VVT on Gen2 works weirdly because of factory way of working. New ticket about strange VVT operation?

**Comment by rusefillc** [comment]
>  strange VVT operation?

yes please
