### ISSUE TITLE
Boost control by gear first step: open loop MVP 1x8 table

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#5276]
we have open loop table
we have ``Sensor::getOrZero(SensorType::DetectedGear)``

let's add a 1x8 table of gear-based open loop adder

![image](https://github.com/rusefi/rusefi/assets/48498823/bab864ae-8cf7-4dbb-987b-f7f471d11d44)

**Comment by andreika-git** [comment]
The initial implementation is ready, now we need to test it somehow?

**Comment by rusefillc** [comment]
@ElDominio closing since no feedback for too long
