### ISSUE TITLE
openblt: OscillatorType inconsistency

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#5280]
MRE says HSE
https://github.com/rusefi/rusefi/blob/519ee8d50f840faed0f88bf634eacd93bb53d2c8/firmware/config/boards/microrusefi/openblt/main_external_osc.c#L120

subaru says HSE
https://github.com/rusefi/rusefi/blob/519ee8d50f840faed0f88bf634eacd93bb53d2c8/firmware/config/boards/subaru_eg33/openblt/main_external_osc.c#L108

"default" file used by proteus says HSI

https://github.com/rusefi/rusefi/blob/aecd997d4b42a6258c2a95d7b10e3da74e8f744f/firmware/hw_layer/openblt/main_internal_osc.c#L130

we shall either document reasons for inconsistency or reduce that inconsistency?

**Comment by dron0gus** [comment]
Because Proteus can have different HSE oscillators. OpenBLT has no way to detect HSE frequency in runtime.
