### ISSUE TITLE
test_trigger_input_adc progress

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#5283]
We need more scenarios to be covered in test_trigger_input_adc

**Comment by andreika-git** [comment]
Currently the following datasets are tested:

- trigger_adc_1.csv 
- trigger_adc_750.csv 
- trigger_adc_1000.csv 

Remaining are "decr/incr" and "real*"

**Comment by rusefillc** [comment]
We now have a unit test with RPM! Progress was made.
