### ISSUE TITLE
TunerStudio warnings in bundle 2023.05.28

### ISSUE THREAD

**Issue by Gorfest-n** [rusefi/rusefi#5291]
TunerStudio warnings in bundle 2023.05.28 alphax-2/8/8chan
[warnings .txt](https://github.com/rusefi/rusefi/files/11593724/warnings.txt)

![изображение_2023-05-29_220135](https://github.com/rusefi/rusefi/assets/50032177/3d99cd9f-6c9d-496b-a9d0-7cc12be17cd4)

**Comment by rusefillc** [comment]
```
1 Errors:
Error: Error: CurveGraph yBin not a valid Constant., Problem at:
[mainController.ini]:[Line:3642]: 		yBins = gearBasedOpenLoopBoostAdder
```

**Comment by rusefillc** [comment]
Three or four errors in .ini file fixed thank you for the report!

Current release TunerStudio 3.1.08 shows close to a hundred of similar warnings
``Warning: bit Constant ignBlends2_blendParameter, contains fewer options (26) that expected(32), padding remaining with "INVALID"``

but current beta version TunerStudio 3.1.08.16 already does not consider this an issue, let's just live as is and one TS has a release those warnings would be gone
