### ISSUE TITLE
Error codes should have a table what each one means on wiki

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#5293]
On rusEFI logs there is spark cut code, fuel cut code, and etb error code. All of these produce a number that one is supposed to "know" what it means since there is no documentation of this anywhere

Will attach a log with an etberrorcode soon

**Comment by ElDominio** [comment]
[30.zip](https://github.com/rusefi/rusefi/files/11615685/30.zip)

![image](https://github.com/rusefi/rusefi/assets/5685108/4e34ba57-10ac-436f-b433-6dacd0ce80f4)

**Comment by rusefillc** [comment]
A pretty-horrible but at-least-something solution at https://github.com/rusefi/rusefi/wiki/Error-Codes
