### ISSUE TITLE
ADC vRef voltage error 

### ISSUE THREAD

**Issue by Gorfest-n** [rusefi/rusefi#5306]
Error when editing the value of the ADC vRef voltage
![877](https://github.com/rusefi/rusefi/assets/50032177/8efc7dc6-374e-4dfd-81ed-8c1fc86abfb9)
.
signature= rusEFI master.2023.05.31.alphax-4chan.60984480

**Comment by rusefillc** [comment]
Similar to #5290 some boards have this value hard-coded thus not allowing to edit

hiding settings same as #5290 hid the other one
