### ISSUE TITLE
Lua ->(to)-> Tunerstudio inputs and outputs

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#5307]
Inputs processed in Lua (like AC request or Launch trigger) should be useable in TunerStudio, and Outputs (like AC Output) should too.

Use case example: on a car with fully CANBUS A/C, input is recieved through CAN, and output approval (meaning, the ECU tells the AC panel it's fine to turn on compressor) is done through CAN. There should be a "Lua Input" in the drop down for AC request input, and a Lua Output for AC clutch output. Maybe there could be 5 additional Lua I/Os on these kinds of inputs/outputs

<img width="325" alt="image" src="https://github.com/rusefi/rusefi/assets/5685108/3364fcc2-6e2a-4df7-ab75-98b0f972e0ec">
<img width="466" alt="image" src="https://github.com/rusefi/rusefi/assets/5685108/38d5d1a6-c0d4-4d9e-a435-2cc404b89c56">

This would allow for things like CAN A/C control, or more-complciated activation schemes from Lua inputs (share an input but using different conditions)

**Comment by rusefillc** [comment]
@andreika-git @ElDominio next step to check how is this related to https://github.com/rusefi/rusefi/issues/4861
