### ISSUE TITLE
Console "Install Drivers" is broken, keeps opening cmd windows

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#5308]
After installing the drivers, console keeps opening CMD windows showing "requesting administrative privileges" and closing them, this keeps happening until console is killed in Task Manager

**Comment by mi-hol** [comment]
@ElDominio is this the same issue as described in https://github.com/rusefi/rusefi/issues/5162 ?
In case it is, please close this issue as duplicate

**Comment by ElDominio** [comment]
I don't think so, install is successful but it keeps opening windows without error

**Comment by ElDominio** [comment]
@rusefillc  @rusefillc  @rusefillc

**Comment by rusefillc** [comment]
> This was fixed when more people started exploding

I am not aware of anyone fixing it unless Microsoft has changed something? weird.

**Comment by ElDominio** [comment]
I saw a thread on Facebook about it, then the probalem stopped about a week afterwards
