### ISSUE TITLE
Kia/Hyundai CAN 

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#5328]
These are the CAN messages from another aftermarket ECU compared to the car with no ECU
<img width="224" alt="image" src="https://github.com/rusefi/rusefi/assets/5685108/89aae0ca-6776-4395-ad0d-c119fd485b21">

Here are three logs
[hyundaikia_CAN_stuff.zip](https://github.com/rusefi/rusefi/files/11759848/hyundaikia_CAN_stuff.zip)
* boostloggenesis.log - stock ECU driving on street and making boost
* genesisnoecu.log - Hyundai Genesis with no ECU
* haltechturnon.log - turning on engine on a Kia Forte with aftermarket ECU

on 0x329 of haltechturnon.log we can see this
<img width="602" alt="image" src="https://github.com/rusefi/rusefi/assets/5685108/95da7b03-56c2-4c98-bdf0-6e18212c03fc">

blue line is what I suspect is causing it to not work on kia, byte0

On all others you either have a flat value or something which is known (a/c request, RPM, CLT)
I suspect Kia cluster not working is due to 0x329 or I am missing some flat value on some packet

**Comment by rusefillc** [comment]
```
(1663615431.829629) can0 329#0C96800E112F0014
(1663615432.209514) can0 329#4F96800E112F0014
```
