### ISSUE TITLE
Each bank of cam inputs should have individual edge selection

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#5333]
Say case:
Car has 2x VR cam but ECU only has enough inputs for one; one will need to be conditioned externally, meaning the edge might be different on each cam

Or even, 2x VR cam and 2x hall cam, they might need different edges on each

Maybe stick it in Advanced trigger, and have an option for "Individual Edge Selection"

**Comment by rusefillc** [comment]
At the moment we have one setting
![image](https://github.com/rusefi/rusefi/assets/48498823/d2533b05-3fee-4d1b-a694-7436b16ea7a0)

Let's rename existing setting to "invert intake cams" and add one new setting "invert exhaust cams"

I.e. let's NOT have four per-cam setting, both intake and/or both exhaust would still have to use same setting

**Comment by rusefillc** [comment]
@ElDominio please test

**Comment by ElDominio** [comment]
Confirmed working, log at https://rusefi.com/online/view.php?log=1381
