### ISSUE TITLE
single-wire batch injection does not use firing order

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#5353]
individual ignition + individual injection: both spark and fuel are in firing order AS EXTECTED
![image](https://github.com/rusefi/rusefi/assets/48498823/6dd6d449-778b-4f5d-bef5-e170c3c74a78)

batch/wasted ignition + individual injection
coils are firing in 1-8-4-3 order AS EXTECTED
which is
(1+6) (8+5) (4+7) (3+2)

![image](https://github.com/rusefi/rusefi/assets/48498823/bd31387e-edb5-4492-8235-38ae0be5e5fd)

individual ignition + two wire batch injection
![image](https://github.com/rusefi/rusefi/assets/48498823/81d4de86-7484-48bb-b88c-de12720fcb2c)

individual ignition + batch injection
note two things:
* it's injectors 1-2-3-4 which are fired, not 1-8-4-3 - so we have a difference of approach here - that alone could have been OK
* 

![image](https://github.com/rusefi/rusefi/assets/48498823/a7f363f3-7610-4cc1-9e6a-744afeb78e49)

**Comment by rusefillc** [comment]
@ElDominio says

![WhatsApp Image 2023-06-24 at 22 59 14](https://github.com/rusefi/rusefi/assets/48498823/652a34ab-6330-4923-952a-15f7d786f615)

**Comment by ElDominio** [comment]
![image](https://github.com/rusefi/rusefi/assets/5685108/b86f10f9-afc1-454c-a422-73bf19865685)

![image](https://github.com/rusefi/rusefi/assets/5685108/a6d87529-def5-412d-a00a-2ecf3467bca3)

**Comment by mck1117** [comment]
lol that's neat

![image](https://github.com/rusefi/rusefi/assets/568254/96aaab17-7d8f-4683-bde0-f6b1fe58ad4e)
