### ISSUE TITLE
Updater needs JRE11, JRE only exists up to 8?

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#5385]
<img width="265" alt="image" src="https://github.com/rusefi/rusefi/assets/5685108/b52c4c26-5a8f-4791-9a8c-f02f156dee56">

But

https://www.java.com/en/download/manual.jsp

<img width="711" alt="image" src="https://github.com/rusefi/rusefi/assets/5685108/2b8b0123-81e2-405f-aeb8-24ad93fc8019">

**Comment by rusefillc** [comment]
yeeeee, that's going to be a bit confusing :(

https://www.oracle.com/java/technologies/javase/jdk11-archive-downloads.html

**Comment by ElDominio** [comment]
That download is enormous and people usually have garbage internet, even in the mainland. 

Could the updater be split off from console then? Have a dedicated updating application that runs on potatoes?

**Comment by rusefillc** [comment]
try https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.19%2B7/OpenJDK11U-jre_x64_windows_hotspot_11.0.19_7.msi

**Comment by rusefillc** [comment]
https://rusefi.com/s/j
