### ISSUE TITLE
serial-over-USB reconnection after reset issue

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#54]
If you reset rusEfi while serial-over-USB is connected, you cannot connect it again till you reset rusEfi one more time.

Looks like this issue is reproducible with just ChibiOS demo code - so it's not our issue http://forum.chibios.org/phpbb/viewtopic.php?f=16&t=1727

Reported by: rusefi

**Comment by mck1117** [comment]
I've never seen this happen

**Comment by rusefillc** [comment]
@mck1117 I believe this is all about pre-Win 10 driver? I guess time to close since pre-Win 10 exists less and less?

**Comment by mck1117** [comment]
oh, that's what this was

yeah I guess a reasonable thing for us to say "please use w10" if somebody has a problem
