### ISSUE TITLE
flex fuel sensor

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#540]
first step towards e85 EFI would be integrating with GM flex fuel sensor

**Comment by OrchardPerformance** [comment]
@rusefillc @mck1117  - Has Gwendal driving around on this already? Do we feel this one is done?

**Comment by CrazyStriker** [comment]
I'm driving using set stoich value of 10. need to install sensor still but I can start working on it ASAP

**Comment by OrchardPerformance** [comment]
Thirsty. Would be cool to give this one a push as I don't think it will take much to get it over the line.

**Comment by mck1117** [comment]
Automatic stoich compensation should work, but a real world test of it would be cool.
