### ISSUE TITLE
GDI4 overlap factor

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#5416]
GDI4 box cannot do more than 50% duty cycle

firmware should be aware of that and handle things in a less confusing way

**Comment by mck1117** [comment]
the actual engine has more restrictive conditions than 50% duty cycle that you have to respect which will implictly respect the duty limits of the driver chipset

**Comment by rusefillc** [comment]
> the actual engine has more restrictive conditions than 50% duty cycle that you have to respect which will implictly respect the duty limits of the driver chipset

yes, if actual engine is part of the picture
right now I am helping GDI test bench use-case.

**Comment by rusefillc** [comment]
Awesome s   '
