### ISSUE TITLE
Remove injector drive options

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#5422]
I know of no injectors that are driven when ground is disconnected. Why does this option exist?

**Comment by mck1117** [comment]
because some injector driver chips are inverted input

**Comment by rusefillc** [comment]
@mck1117 what would be an example of such a chip? Who uses it on what board?

**Comment by ElDominio** [comment]
I think it then should be disabled in prebuilt boards, since they are always built with a known chip. Only leave if for generic firmwares

**Comment by mck1117** [comment]
> what would be an example of such a chip? Who uses it on what board?

tle9104
