### ISSUE TITLE
Tach output critical error

### ISSUE THREAD

**Issue by Gorfest-n** [rusefi/rusefi#5431]
rusEFI master.2023.07.22.alphax-4chan.3805642889

If the tachometer output is set to "A4 - Tachometer", then we get a critical error. 
Previous builds don't have this error.
![изображение_2023-07-22_215942](https://github.com/rusefi/rusefi/assets/50032177/b9d5bb26-d7e9-49f2-a359-302574a1e900)

**Comment by rusefillc** [comment]
See https://github.com/rusefi/alphax-4chan/issues/146

Володя, а поменялся ли у нас a-EN?

**Comment by rusefillc** [comment]
@Gorfest-n у нас там распиновка новых плат немного поменялась :( Сейчас видимо сломанны и старые, и новые платы. Сейчас попробую починить немного :)

**Comment by rusefillc** [comment]
```
void boardInitHardware() {
	alphaEn.initPin("a-EN", H144_OUT_IO3);
	alphaEn.setValue(1);
```

**Comment by Qwerty-OFF** [comment]
Видимо для тахометра выбрана не правильная нога. @rusefillc когда-то будет пора что то сделать с группами пинов OUT_IOx и IOx чтобы они не путались? H144_OUT_IO3 в rev.h это тестовая точка P19.
![image](https://github.com/rusefi/rusefi/assets/4116383/ab5a9c8c-9434-45f5-977a-3e465930eb21)
