### ISSUE TITLE
Conditional compilation of getOutputValueByName getConfigValueByName

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#5434]
See auto-generated "getOutputValueByName" method
See auto-generated "getConfigValueByName" method

those generated methods take a LOT of flash and we need a way to compile firmware WITH lua but without EFI_LUA_LOOKUP see https://github.com/rusefi/rusefi/commit/a89ee66fb6537ef1ecfc3eb8da83c1ed8c4db1c2

**Comment by rusefillc** [comment]
@mck1117 any chance you would be available to finish implementation? I've made just the first step https://github.com/rusefi/rusefi/commit/a89ee66fb6537ef1ecfc3eb8da83c1ed8c4db1c2

**Comment by andreika-git** [comment]
The size of rusefi.bin for VW121 config:
1) Before PR #5439: 524260 bytes
2) After PR #5439: 473956 bytes
= 50304 bytes less!
