### ISSUE TITLE
CAN bench test: broadcast event counters

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#5436]
Every 100ms we should send out six bytes on BENCH_TEST_EVENT_COUNTERS extended CAN ID: 
* primary trigger rise + fall
* secondary trigger rise + fall
* four VVT rise + fall event counters

**Comment by rusefillc** [comment]
@andreika-git other rusEFI usages see https://github.com/rusefi/rusefi/wiki/CAN

**Comment by andreika-git** [comment]
https://github.com/rusefi/rusefi/commit/f2736e5f91edd259abbee7a341ba0c584ecb8971
Now with broadcast mechanism.
