### ISSUE TITLE
Custom Trigger Tooth with 1+0 causes endless loop

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#5471]
**Describe the bug**
As stated in the title, when you set trigger settings to
custom toothed wheel
1 tooth
0 missing

and apply 12v, th ECU hangs until reset

**Hardware**
 - revD 2chan
 - Bike engine

**To Reproduce**
Apply settings as stated in first section
reset ECU
power up with USB
apply 12v to main 12v pin

**Expected behavior**
ECU works as normal

**Comment by rusefillc** [comment]
interesting, unable to reproduce on a Proteus

![image](https://github.com/rusefi/rusefi/assets/48498823/8e82f44f-878b-4766-8c2c-a5c7c7effe08)

**Comment by rusefillc** [comment]
@ElDominio please provide two tunes "tune right before change" and "tune with change"

**Comment by ElDominio** [comment]
Four cylinder ECU used in parallel to control injection
