### ISSUE TITLE
proteus shows crazy RPM on Honda Generator

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#5492]
https://rusefi.com/online/view.php?msq=1526

https://rusefi.com/online/view.php?log=1266

![image](https://github.com/rusefi/rusefi/assets/48498823/c2a2a844-425a-413e-94ba-90258b118aae)

**Comment by rusefillc** [comment]
@ElDominio says shunt resistor

http://www.useasydocs.com/theory/vr.htm

**Comment by rusefillc** [comment]
![image](https://github.com/rusefi/rusefi/assets/48498823/53264f9c-f889-495e-96bc-8278fd44334b)

**Comment by rusefillc** [comment]
VR has one side ground on this "Vehicle"

VR and injector

![WhatsApp Image 2023-08-06 at 01 59 29](https://github.com/rusefi/rusefi/assets/48498823/e3a8b2e3-0ede-4c39-9ba6-761622026cc8)

**Comment by rusefillc** [comment]
MRE "crank" and raw VR, with 10K pull-down

![WhatsApp Image 2023-08-06 at 01 59 30](https://github.com/rusefi/rusefi/assets/48498823/dfb0855b-b535-43ac-afce-e0a70a2cf82d)

**Comment by Qwerty-OFF** [comment]
Try 1k - 4.7k R1207, 10n C1209

More correctly, it seems to need to change MAX9924 operating mode, see Figure 1 and Table 1 in MAX9924 datasheet.

**Comment by rusefillc** [comment]
@Qwerty-OFF do we have similar trick for tle8888?

**Comment by rusefillc** [comment]
Aborting since no plans to test further :(
