### ISSUE TITLE
Startpwm is broken

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#5502]
![IMG_20230808_200234.jpg](https://github.com/rusefi/rusefi/assets/5685108/e81f35a8-6512-47ba-8def-31b2d67d3f83)

This was working on previous firmware

Line 3 is

startPwm(0, 2.5, 0)

**Comment by ElDominio** [comment]
Downgraded to 4 days ago (08042023) problem is gone

**Comment by rusefillc** [comment]
must be related to #5497
