### ISSUE TITLE
"rpmAcceleration" in TS doesn't go lower than 0

### ISSUE THREAD

**Issue by tmbryhn** [rusefi/rusefi#5504]
"rpmAcceleration" variable in TunerStudio does not give negative values on deceleration.

 - Board: custom hardware running Proteus_F4 FW
 - Trigger setup: 36-1. No cam input

 - Define a gauge to "rpm delta"
 - Have RPM decrease (deceleration)
 - Observe gauge "rpm delta"

**Expected behavior**
 - Value on "rpm delta" should be negative

**Comment by rusefillc** [comment]
@tmbryhn please help me understand your choice of not linking tune and log.

**Comment by rusefillc** [comment]
random log confirms the issue

![image](https://github.com/rusefi/rusefi/assets/48498823/47985506-6f1e-4172-88d5-e9128a6e8f5c)
