### ISSUE TITLE
EPIC: we need to test fresh boards

### ISSUE THREAD

**Issue by andreika-git** [rusefi/rusefi#5511]
Test use-case:
- all analog sensors for hellen125honda board  
  * Stim hardware already has 8 (or 10?) different voltages suitable for testing analog sensor inputs.
We need an instruction on pin connection map: which pin of stim connects with which pin of honda board.
- all hall sensors
  * Currently we don't have a board with broken hall inputs
  * We have 8 generic outputs on STIM, now we need a firmware modification to use them
- all actuators (lowside)
  * test used IO first, then figure out how to test unused IO
  * We have a special Proteus config which blinks all outputs, but this is a bad way, we need better.  
  * Stim firmware already has console, and it knows how to test outputs.

We assume that the tested board already has the default firmware with default settings.

We also have:
- hellen154hyundai with MAP sensor malfunction
- 4chan with COIL1 malfunction

TODO (future versions):
- wbo controller (we can test if it's alive via CAN)

**Comment by andreika-git** [comment]
Related issues:
~~https://github.com/rusefi/rusefi/issues/5436~~
https://github.com/rusefi/rusefi/issues/5437
https://github.com/rusefi/rusefi-hardware/issues/222

**Comment by rusefillc** [comment]
See also https://github.com/rusefi/rusefi/issues/5514

**Comment by rusefillc** [comment]
Actual board profiles https://github.com/rusefi/rusefi-hardware/issues/228

**Comment by andreika-git** [comment]
Now we have https://github.com/rusefi/rusefi-hardware/commit/72c7d06cec56a038330b7406647478b9ae76a516
We can perform the first test of CAN communication...

**Comment by rusefillc** [comment]
rusEFI gets CAN from stim
rusEFI might be not sending data correctly https://github.com/rusefi/rusefi/issues/5525

**Comment by rusefillc** [comment]
#4630

**Comment by andreika-git** [comment]
https://github.com/rusefi/rusefi-hardware/commit/32495af8984dca49b91e472f044ff7822e0a965e

@rusefillc Can you please test the raw_analog_values packet processing?

**Comment by rusefillc** [comment]
> @rusefillc Can you please test the raw_analog_values packet processing?

rusEFI side was broken - we were relying on outputChannels which are not populated if USB is not connected. this is now fixed https://github.com/rusefi/rusefi/commit/9adc323fec207f9e49fc2725dd4ce8826075c42f

**Comment by rusefillc** [comment]
> 
> @rusefillc Can you please test the raw_analog_values packet processing?

https://github.com/rusefi/rusefi-hardware/issues/228#issuecomment-1687371773

**Comment by rusefillc** [comment]
```
Processing BENCH_TEST_BUTTON_COUNTERS ID=770004/l=8 19 0 0 0 0 0 0 0
Processing BENCH_TEST_EVENT_COUNTERS ID=770000/l=8 3E 22 22 1F 0 0 8C 0
```

pretty expected result for the following configuration (things are wires in the most reasonable way)

```
void proteusStimQc() {
    engineConfiguration->trigger.type = trigger_type_e::TT_ONE_PLUS_ONE;

   	engineConfiguration->triggerInputPins[0] = PROTEUS_DIGITAL_1;
   	engineConfiguration->triggerInputPins[1] = PROTEUS_DIGITAL_2;
   	engineConfiguration->camInputs[0] = PROTEUS_DIGITAL_3;
   	engineConfiguration->camInputs[1] = PROTEUS_DIGITAL_4;
   	engineConfiguration->vehicleSpeedSensorInputPin = PROTEUS_DIGITAL_5;
   	engineConfiguration->brakePedalPin = PROTEUS_DIGITAL_6;
}
```

**Comment by rusefillc** [comment]
Good enough, done!
