### ISSUE TITLE
broadcast button toggle counter

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#5514]
we shall broadcast brake pedal input, clutch pedal input, A/C request button toggle counters

this would help us test https://rusefi.com/docs/pinouts/hellen/hellen154hyundai/ boards

**Comment by andreika-git** [comment]
brakePedalPin --> brakePedalState  --> brakePedalToggleCounter
clutchUpPin --> clutchUpState --> clutchUpToggleCounter
acSwitch --> acButtonState --> acButtonToggleCounter
