### ISSUE TITLE
broadcast board ID and uptime

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#5515]
every 250ms we should broadcast on BENCH_TEST_BOARD_STATUS EID
* board unique ID 2 bytes
* number of seconds since ECU reboot 2 or 3 or 4 bytes TBD

**Comment by andreika-git** [comment]
https://github.com/rusefi/rusefi/pull/5518

**Comment by andreika-git** [comment]
https://github.com/rusefi/rusefi-hardware/commit/72c7d06cec56a038330b7406647478b9ae76a516
