### ISSUE TITLE
4G69 Cam pattern

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#5541]
**Is your feature request related to a problem? Please describe.**
We have no support for this cam, seems to be 4+1+1
4 teeth at 90 degrees, two of them have two teeth.

**Would we need new configuration fields?**
Nope, only dropdown choice for 4g69 cam

**Describe the solution you'd like**
Add support for 4G69 cam

**Describe alternatives you've considered**
grinding teeth but that's ugly

**Additional context**
![Untitled](https://github.com/rusefi/rusefi/assets/5685108/759dd052-cc56-4079-8323-719a0d5e21fe)

**Comment by rusefillc** [comment]
![image](https://github.com/rusefi/rusefi/assets/48498823/2af114ce-25dc-4f67-98eb-e2e10a60a141)

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi/wiki/All-Supported-Triggers#4g69-vvt
