### ISSUE TITLE
Injector duty reading half of reality

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#5542]
**Describe the bug**
Injector duty is half of real, was hitting Fuel Cut Code 10 (duty) and injector duty was at 50%

**Hardware**
4chan revH

**To Reproduce**
rev to a place where you ask for more than 96% duty
check reported duty

**Expected behavior**
read 100% instead of 50%

[test trigeer.zip](https://github.com/rusefi/rusefi/files/12435070/test.trigeer.zip)

Log shows fuel cut code and current duty being 50%

**Comment by rusefillc** [comment]
@ElDominio without tune I do not know if you are in GDI mode

with GDI mode setting we are limited to 50% duty cycle

**Comment by ElDominio** [comment]
Can guarantee not GDi, but cannot guarantee not GDi mode; i wish this persons internet was not absolutely horrifying

**Comment by andreika-git** [comment]
Let him check the "Number of lobes" setting (should be 0) in the Controller->"HPFP Cam Configuration" dialog.

**Comment by rusefillc** [comment]
Seems to be caused by #5416

Default tune has three lobes and too many users are now affected. Changing check to look at output pin not lobes.

**Comment by rusefillc** [comment]
@ElDominio a work-around would be to set Controller->"HPFP Cam Configuration" -> "Number of lobes" to zero

**Comment by ElDominio** [comment]
Was set to 3, the seller FINALLY gave me the tune

**Comment by rusefillc** [comment]
@ElDominio that's rusEFI issue we had bad default and deciding GDI mode because of it. Gdi mode logic changed now.
