### ISSUE TITLE
Honda-K pinout mapping seems wrong around VVT

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#5547]
![image](https://github.com/rusefi/rusefi/assets/48498823/d9d645ef-18d7-4f4d-9a80-5d13203bd315)

does not match

```
  - pin: B21
    meta: H144_OUT_PWM5
    class: outputs
    type: ls
    ts_name: ___ - EVAP
    function: EVAP

  - pin: B23
    meta: H144_OUT_PWM4
    class: outputs
    ts_name: ___ VTC VVT
    function: VTC VVT
```

**Comment by rusefillc** [comment]
![image](https://github.com/rusefi/rusefi/assets/48498823/b07ca905-d85e-4759-9f6e-7d4474886717)

**Comment by rusefillc** [comment]
@ElDominio remember we were suspecting soldering issue? I now think that VVT output pin was never properly configured

Are you 200% curtain that we had VVT working on second unit on the dyno?

**Comment by ElDominio** [comment]
About 197% sure.

VVT did not follow target in one ECU (didn't even move), yes in the other. Same tune was loaded with no firmware ini change
