### ISSUE TITLE
2chan revF not showing additional I/O pins

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#5564]
Internal I/O not showing on most recent FW![Screenshot_20230914-190653.jpg](https://github.com/rusefi/alphax-2chan/assets/5685108/089fe691-00f7-473e-b7e3-48b3c57b56ef)

**Comment by rusefillc** [comment]
@ElDominio some progress was made stay tuned for more

**Comment by ElDominio** [comment]
they are all there
