### ISSUE TITLE
Fan not be able to be set because in use at VR PWM

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#5565]
<img width="504" alt="image" src="https://github.com/rusefi/alphax-2chan/assets/5685108/fa1359df-1b9f-41e1-ae1e-484dde85a2c3">

what's VR PWM?

**Comment by ElDominio** [comment]
![image](https://github.com/rusefi/rusefi/assets/5685108/443af528-7333-43f7-b9a8-dde4a0fc548f)

https://rusefi.com/online/view.php?msq=1541

**Comment by rusefillc** [comment]
* sounds like 2chan never had two discrete VRs so we shall ignore the second threshold setting and hide the second channel control?
* sounds like 2chan before rev G should have hard-coded OUT_PWM6: VR threshold and not even expose the setting?
* sounds like 2chan rev G no longer needs VR threshold settings we should hide for that specific revision?

@ElDominio please confirm

**Comment by ElDominio** [comment]
I have more dumb revision ideas for rev-after-G so I think they shouldn't be hidden

Having no second channel seems fine though

**Comment by rusefillc** [comment]
> I have more dumb revision ideas for rev-after-G so I think they shouldn't be hidden

we will deal with latest once we are in the future :)

**Comment by ElDominio** [comment]
I disabled PC8 and got the same error btw

**Comment by rusefillc** [comment]
@ElDominio please update firmware to get more detailed message

![image](https://github.com/rusefi/rusefi/assets/48498823/b7444843-6f6f-4810-b143-80bf7ef2ba34)

**Comment by rusefillc** [comment]
@ElDominio also VR pin controls are now hidden for 2chan and 4chan with, and 2chan values are hard-coded

![image](https://github.com/rusefi/rusefi/assets/48498823/96e21f7e-d102-43aa-a231-b9626e1958f4)

**Comment by ElDominio** [comment]
Problem is fixed now? Updated to 20230818 and all worked
