### ISSUE TITLE
ETB activates radiator fan

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#5569]
https://rusefi.com/online/view.php?msq=1543

4chan, kia adapter, brand new patch cord

sitting in parked vehicle

* radiator fan bench test works, TS indicator goes green while bench test
* with "disable ETB if engine is stopped" FAN is not spinning, no TS gauge
* i chance "disable ETB if engine is stopped" to "false" to test ETB and I get fan spinning while TS indicator is not active

**Comment by rusefillc** [comment]
second example of 4chan does same so probably not a fab defect

@ElDominio have you ever noticed anything similar?

**Comment by ElDominio** [comment]
Maybe happens on new revision? I always leave ETB active with engine off and have never seen this behavior

**Comment by rusefillc** [comment]
patchcord issue main relay wires was not hooked up properly
