### ISSUE TITLE
Hyundai-PB: There are TWO possible pins for Fuel Pump

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#5590]
**Describe the bug**
2012 Hyundai Accent PR Market does not fire Fuel Pump

**Hardware**
4chan
PB Adapter

**To Reproduce**
Turn on fuel pump anywhere for any reason

**Expected behavior**
Fuel pump turns on

**Actual behavior**
no fuel pump activation

**Screenshots**
<img width="646" alt="image" src="https://github.com/rusefi/rusefi/assets/5685108/a4ac7dea-86cf-4d1c-b963-9e025d6dee05">

**Additional context**
Car turned on with fuel pump jumped manually. It was discovered that pins might changed, will later confirm if this is the case.

**Comment by rusefillc** [comment]
@ElDominio we seem to have some relevant R1 and R2 on https://github.com/rusefi/rusefi-hardware/blob/main/breakout-boards/Breakout_154_kia_pb/hellen-hyundai-pb-154-adapter-0.1.pdf

anyway let me add better silk on next iteration of the board!
