### ISSUE TITLE
6G72 Trigger Pattern

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#5593]
**Is your feature request related to a problem? Please describe.**
I want the Mitsubishi 6G72 trigger pattern to be supported

**Would we need new configuration fields?**
An option under Trigger for Mitsubishi 6G72

**Describe the solution you'd like**
Add support for the pattern

![image](https://github.com/rusefi/rusefi/assets/5685108/c0b26789-ed6c-4f29-8160-003342444064)
factory trigger pattern analysis

![image](https://github.com/rusefi/rusefi/assets/5685108/4181cc0c-5f13-461b-b2c7-a1c33b58317e)
bottom is crank (3 windows)  top is cam (4 windows)

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi/wiki/All-Supported-Triggers#6g72-cam

**Comment by ElDominio** [comment]
https://rusefi.com/online/view.php?log=1324

VVT reads, but no sync

**Comment by ElDominio** [comment]
[6g72crankinglogsWOT.zip](https://github.com/rusefi/rusefi/files/13518421/6g72crankinglogsWOT.zip)

**Comment by rusefillc** [comment]
![image](https://github.com/rusefi/rusefi/assets/48498823/908f3a5b-dd85-4ac7-9636-2766b4e4eca2)

**Comment by rusefillc** [comment]
looks great

![image](https://github.com/rusefi/rusefi/assets/48498823/b6ed3e2f-cd83-438b-b029-2813dfc392b7)

**Comment by ElDominio** [comment]
This works! Why was it not closed?
