### ISSUE TITLE
Problem with downloading simulator

### ISSUE THREAD

**Issue by krisyovchevv** [rusefi/rusefi#5595]
Hello, I tried to download the simulator for TunerStudio, but after clicking on the link to download the zip file, I get a tab that shows an error and gives me two buttons:
1- Main page
2- New wiki
Is there a way to download the simulator or not?
![Screenshot 2023-10-05 185640](https://github.com/rusefi/rusefi/assets/105774870/32c32ebc-cfc8-4c8b-b10f-4f2d012de263)

**Comment by rusefillc** [comment]
@krisyovchevv please elaborate on how exactly are you trying to download the simulator? As is I have no idea what are you clicking where meaning I would not be able to fix.

**Comment by krisyovchevv** [comment]
I go to the github page for the guide on how to download and use the simulator: https://github.com/rusefi/rusefi/wiki/Virtual-simulator
and click on the "here" button, where the zip file with the files for the simulator should be downloaded:
![Screenshot 2023-10-05 191344](https://github.com/rusefi/rusefi/assets/105774870/dcb7748e-ab4a-4c11-a9ad-24a9e6e23cb6)

Whereupon after pressing the "here" button, I get a page saying "Not found", and below two options:
![Screenshot 2023-10-05 185640](https://github.com/rusefi/rusefi/assets/105774870/02b4f50a-5a6a-4c74-9f3f-851cf92ba59d)

**Comment by rusefillc** [comment]
Fixed link at https://github.com/rusefi/rusefi/wiki/Virtual-simulator

**Comment by krisyovchevv** [comment]
Thank you <333
