### ISSUE TITLE
document why do we care about detectHellenMcuType

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#5615]
detectHellenMcuType seems to distinguish between 144 and 176

Do we still care? I see console output but do we use the result anywhere?

**Comment by andreika-git** [comment]
AFAIR detectHellenMcuType() was intended to be used for old Miata boards (eg. hellen72 revA-revD) without BoardID to detect mcu144 vs mcu (176)

**Comment by rusefillc** [comment]
@andreika-git do you mean it is in fact totally unused as if today?
