### ISSUE TITLE
Remove Injector Test from "Controller"

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#5616]
**Describe the bug**
Why do we have "Injector Test" when we can test injector in Bench Test with the same parameters?

**Hardware**
 - Board: [e.g. microRusEFI]
 - Engine info [e.g. m111 NA]

**To Reproduce**
1. Go to 'Controller'
2. Click on 'Injector Test'

**Expected behavior**
Only have one option, either in Bench Test or Injector Test (I like bench test better)

**Screenshots**
<img width="345" alt="image" src="https://github.com/rusefi/rusefi/assets/5685108/712e2d68-1dd7-4aac-ad4c-d315c761289f">

**Comment by mck1117** [comment]
Did you actually look at each? The injector test page has stuff to facilitate both testing injectors and characterizing injectors.

**Comment by ElDominio** [comment]
Yes, and I didn't understand what additional data from what I have on the main dashboard/panel and how is it useful (I can look at battery in the gauges and what are test iterations)

If it's that important for such an edge case, it should be in a folder that whoever uses that specific function can find it; most end users end up asking "which test mode do I use?" even if they're are to test specifically coils.

**Comment by ElDominio** [comment]
Apparently not a good idea so closing
