### ISSUE TITLE
Volvo 240 60-2 trigger with holes instead of teeth

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#5655]
**Describe the bug**
Tooth time looks as if it was a 60-1, but it looks like a 60-2 and we counted 58 teeth (holes), similar to picture but instead of having a 2x air gap it is 2x solid.

Log of gap is at: https://rusefi.com/online/view.php?log=1313

**Hardware**
-paralela
-max9924 vr to hall
-volvo 240 turbo '89

**To Reproduce**
start engine
rpm reading not consistent

**Expected behavior**
engine fires? the wiring is garbage but i'm just making a record

**Screenshots**
![image](https://github.com/rusefi/rusefi/assets/5685108/a90368c3-e84f-4d5f-a6c4-468858765d92)

**Additional context**
this is just to log it, but not critical, the wiring is extremely poor in this car

**Comment by mck1117** [comment]
I ran a volvo 240 for a long time with the stock trigger setup with no issue, on a proteus with max9924. Swap your VR wires.

**Comment by ElDominio** [comment]
I didn't try that one lol, thanks @mck1117 i'll try it monday

the wiring on it is horrifying so i don't rule out noise either, and the flywheel is warped (you can physically see it wobble up and down while cranking, and it reflects on the oscope) so i told him to get a new one

**Comment by ElDominio** [comment]
@mck1117 it worked, thanks!

also had to use custom toothed wheel instead of 60/2 but w/e it ran jsut fine even with shit wiring
