### ISSUE TITLE
Flex fuel problem 

### ISSUE THREAD

**Issue by Benjamin-neo** [rusefi/rusefi#5702]
Board custom with custom firmware
I use f407 with minimal pins. I only add my board, source code is untouch at the moment.

I have already compile other version, car work with older version.
But I want to update to have the new feature "afterstart map", very good idea.

all seems to be good but ...
when I select a pin for flex fuel and burn. the next change with a burn do a critical error. "Same action twice (flexinfo)."

I have try with other pin, same problem.
Only thing to doesn"t have the critical error is leave flexsensor : none......

**Comment by rusefillc** [comment]
i think I know what it is about let me address it under https://github.com/rusefi/rusefi/issues/5703

**Comment by Benjamin-neo** [comment]
problems are solves
