### ISSUE TITLE
F407-Discovery status LED conflicts for GPIO

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#5705]
**Describe the bug**
Conflict for LEDs PD12/PD13, nowhere it is stated that they are status LEDs, and they need configurability to be able to be used

**Hardware**
Paralela Brainboard

**To Reproduce**
Use an output at the indicated pins

**Expected behavior**
The outputs are controlled correctly, right now they confict with ED pin assignments

**Screenshots**
<img width="523" alt="image" src="https://github.com/rusefi/rusefi/assets/5685108/da0d54ea-8e51-4731-bae6-7bf821f6eaeb">

<img width="488" alt="image" src="https://github.com/rusefi/rusefi/assets/5685108/e73023aa-13ef-4912-a761-83acc686f0ae">

**Comment by rusefillc** [comment]
> Can PD14 be liberated?

No, that would hurt F407-Discovery firmware.

proper solution here is for Paralela Brainboard to use it's own firmware probably within https://github.com/rusefi/fw-Paralela repo
