### ISSUE TITLE
odd fire engines do not appreciate wasted mode on spinning

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#5715]
cylinder offset is for real it should be accounted on fixed timing ignition mode

**Comment by mck1117** [comment]
I believe cylinder offset and trim are always applied even when in fixed mode

**Comment by rusefillc** [comment]
```
	// Allow correction only if set to dynamic
	// AND we're either not cranking OR allowed to correct in cranking
	bool allowCorrections = engineConfiguration->timingMode == TM_DYNAMIC
		&& (!isCranking || engineConfiguration->useAdvanceCorrectionsForCranking);

	if (allowCorrections) {
		angle_t correction = getAdvanceCorrections(engineLoad);
		if (!cisnan(correction)) { // correction could be NaN during settings update
			angle += correction;
		}
	}
```

**Comment by mck1117** [comment]
And cylinder offset isn't related to that function:

```c++
static angle_t getAdvanceCorrections(float engineLoad) {

	.....

	return engine->ignitionState.timingIatCorrection
		+ engine->ignitionState.cltTimingCorrection
		+ engine->ignitionState.timingPidCorrection;
}
```

**Comment by rusefillc** [comment]
@mck1117 what I with timing light see seems worse - looks like first two revolutions there is no offset on second cylinder and then it appears. that's in fixed timing mode, very repetitive.

**Comment by rusefillc** [comment]
![image](https://github.com/rusefi/rusefi/assets/48498823/6af3e651-7418-4b6a-a88a-3cfe51cdc2c4)

**Comment by rusefillc** [comment]
https://rusefi.com/online/view.php?log=1320

**Comment by rusefillc** [comment]
![image](https://github.com/rusefi/rusefi/assets/48498823/7757ddcf-bcf4-4d4b-941f-42f6e86e92ba)

**Comment by mck1117** [comment]
Note uneven spacing of both fuel and spark while in fixed mode.

![image](https://github.com/rusefi/rusefi/assets/568254/03303764-bcf2-456d-b154-905362c2678e)

Probably has to do with this part: `at least on FOME they are`
