### ISSUE TITLE
Add test commands to force "fatal error" and "hard fault"

### ISSUE THREAD

**Issue by andreika-git** [rusefi/rusefi#5722]
We need to test the firmware behavior when a fatal error or hard fault (bus fault? usage fault?) occurs.
Let's choose command names.
"fatal_error"?
"hard_fault"?

**Comment by rusefillc** [comment]
two years ago we had
```
	addConsoleAction("error", myerror);
static void myerror(void) {
	firmwareError(CUSTOM_ERR_TEST_ERROR, "firmwareError: %d", getRusEfiVersion());
}
```

**Comment by andreika-git** [comment]
https://github.com/rusefi/rusefi/pull/5725
