### ISSUE TITLE
Lua: setAcDisabled is broken, only disabled, never re-enables

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#5742]
**Describe the bug**
Calling setAcDisabled disables AC, doesn't matter the value passed (either 0 or 1)

**Hardware**
hyundai154

**To Reproduce**
Write setAcDisabled(0) in lua
ac output never activates if this function is called

**Expected behavior**
setAcDisabled(0) allows normal activation of AC, 1 disables AC oupurt

**Comment by rusefillc** [comment]
I am able to reproduce the problem I know what it could be about

![image](https://github.com/rusefi/rusefi/assets/48498823/5fc1871f-5d3e-4e51-91f9-4bf89e0940db)

![image](https://github.com/rusefi/rusefi/assets/48498823/592eea31-ee1a-493c-a244-2957022c8628)

**Comment by rusefillc** [comment]
@ElDominio Lua is fucked about about number to boolean conversion

1 is true and 0 is true :(

only ``nil`` is false.

![image](https://github.com/rusefi/rusefi/assets/48498823/10c18ee2-87c9-4d92-b96e-5699267bfe89)

**Comment by ElDominio** [comment]
So use nil instead of 0?

**Comment by rusefillc** [comment]
> So use nil instead of 0?

yes, at least for now. we kind of _can_ handle boolean in a not-so-Lua way but that's a can of warms to open

**Comment by ElDominio** [comment]
I'm fine with using nil, not that hard to remember

**Comment by ElDominio** [comment]
The problem was that i did not use (nil) and expected (0) to enabe AC. This can be closed
