### ISSUE TITLE
bench test 33810 module

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#5745]
https://github.com/rusefi/rusefi-hardware/tree/main/MC33810-breakout has arrived how do I bench test? Would be great to see injector missing / coil missing diag working!

**Comment by dron0gus** [comment]
"gpio" command should show you errors on injector outputs.
Diagnostic for ING outputs is implemented, but not enabled because currently driver switches these pin to alternative mode to drive external ignitor on my Subaru. This should be configuration option.
