### ISSUE TITLE
Lua VSS broken for no apparent reson?

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#5759]
**Describe the bug**
2023-11-28_18_19_01_632: EngineState: LUA ERROR loading script: [string "..."]:7: Tried to create a Lua sensor of type VehicleSpeed, but one was already registered.

It was working fine, after a write it started throwing this error

Lua code here:
https://gist.github.com/ElDominio/1b2c2329c52d7a68924c65014bd46bd2

**Hardware**
 - 4chan
 - 3a91

**To Reproduce**
Write Lua code with vss call, sometimes is broken/?

**Expected behavior**
I changed nothing in the code and after a burn Lua complained about bad vss

**Screenshots**
<img width="649" alt="image" src="https://github.com/rusefi/rusefi/assets/5685108/ca6cf3db-1e9c-4afe-acc3-e308020265fc">

**Comment by ElDominio** [comment]
Rebooting ECU reverted the problem?
Same error again on Nov19 firmware

**Comment by rusefillc** [comment]
@ElDominio here is minimal script and it works for me

```

speedSensor = Sensor.new("VehicleSpeed")
speedSensor : set(123)

print("Speed is " ..getSensor("VehicleSpeed"))

function onTick()
end


```


@ElDominio please report output of this minimal script on your end

**Comment by ElDominio** [comment]
2023-11-28_19_04_44_609: EngineState: LUA ERROR loading script: [string "speedSensor = Sensor.new("VehicleSpeed")..."]:1: Tried to create a Lua sensor of type VehicleSpeed, but one was already registered.

**Comment by ElDominio** [comment]
changed firmware to latest official release, added Lua and ECU is happy

**Comment by rusefillc** [comment]
@ElDominio looks like the whole "can vss: lua" is totally unneeded?

**Comment by ElDominio** [comment]
CAN VSS should be under the CAN settings, built into cars with CANs that we have decoded

But what is someone hss physical VSS, and they inject through Lua too, will Lua console notice and scream?

**Comment by ElDominio** [comment]
I dunno if you want this thread, but somution is to disabled CAN LUA VSS in TS and inject it anyways
