### ISSUE TITLE
Remove cells from MAF transfer curve

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#5778]
**Is your feature request related to a problem? Please describe.**
This table is way too big for no good reason, i'm sure this can  be 20 cellls and that is more than enough definition to allow any MAF users to properly define their sensors

**Would we need new configuration fields?**
Nope, just make the MAF transfer function smaller

**Describe the solution you'd like**
Make the MAF transfer function smaller

**Comment by rusefillc** [comment]
reduced to 32 values
