### ISSUE TITLE
ignion timing in case of sudden RPM change

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#58]
currently ignition timing is set once per shaft revolution, I wonder to what extend this is an issue considering sudden RPM change.

Reported by: rusefi

See getRpmAcceleration()

see https://www.youtube.com/watch?v=GPp1bWtMHO8

**Comment by rusefi** [comment]
See SC_RPM_ACCEL

**Comment by mck1117** [comment]
ignition timing is now updated at 200hz, no need for faster than that
