### ISSUE TITLE
all three accelerations should be near zero while not accelerating

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#5809]
note vertical reporting 1g while unit is not moving in relation to bench which does not move in relation to plater Earth

![image](https://github.com/rusefi/rusefi/assets/48498823/004bbffa-707f-47a9-8ba1-1e4c2114d41e)

**Comment by mck1117** [comment]
> vertical reporting 1g

The standard is to report the true force on all 3 axes, and that means vertical=1g at rest. If you tip the car over on its side, you want lat=1g, vert=0g, right?

**Comment by rusefillc** [comment]
Thank you @mck1117 so "Won't fix"?
