### ISSUE TITLE
VE Blend Table 1 uses config from table 2 (video inside!!!!1!)

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#5833]
**Describe the bug**
VE Blend table 1 uses the configuration values from table 2.

**Hardware**
 - Board: Hellen154
 - Engine info Theta2

**To Reproduce**
Set  Blend parameter in VE table 1
Nothing happens
Set Blend Parameter in VE Table 2
config settings apply for both 1 and 2

**Expected behavior**
They are actually individual configs

**Screenshots**
A VIDEO!
https://youtu.be/gTW5IfZWf6k

**Comment by rusefillc** [comment]
@ElDominio please tune and log
