### ISSUE TITLE
Change name from "invert "input": true/false" to "trigger edge: rising/falling"

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#5847]
**Is your feature request related to a problem? Please describe.**
Current nomenclature is unclear, what is the current trigger mode? For people that are going to touch this setting, they will either invert it anyways (since they don't know what it does, just that it might work), or they might fully understand this and choose the correct edge (rising/falling) 

**Would we need new configuration fields?**
<img width="565" alt="image" src="https://github.com/rusefi/rusefi/assets/5685108/828de753-52f5-4855-9660-99624d4aea86">

**Describe the solution you'd like**
Same as picture

**Describe alternatives you've considered**
If we are told "default edge is rising" then inverting it would logically be falling. Having text that says this would be useful

**Comment by rusefillc** [comment]
![image](https://github.com/rusefi/rusefi/assets/48498823/33d5835e-f556-4b90-8cf4-a81908ca28a9)

**Comment by mck1117** [comment]
that's a breaking change for all tunes. Proceed with caution.
