### ISSUE TITLE
Detected gear is not current gear?

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#5850]
**Describe the bug**
I am detecting gear succesfully but Current Gear  = 0; why?

**Hardware**
 - Board: hellen154
 - Engine info hyundai theta2

**To Reproduce**
1. Go to Sensors -> Speed Sensor
2. Foward gear count = 6
3. Input gear ratios
4. Correct detection but not assigned to current gear?

**Expected behavior**
Current gear = detected gear

**Screenshots**
<img width="456" alt="image" src="https://github.com/rusefi/rusefi/assets/5685108/4102b07d-244f-4f4f-bb63-99e2760b23cb">

**Tune and log**
https://rusefi.com/online/view.php?log=1330

**Comment by rusefillc** [comment]
@ElDominio @chuckwagoncomputing this confusion was about TCU current gear variable. I've moved TCU into it's own 'view' page and disabled TCU for most of the board while it's still work in progress.
