### ISSUE TITLE
usability issue: Boost blend logic does not happen while not controlling boost

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#5864]
**Describe the bug**
LuaGauge1 changes in TunerStudio, but axis doesn't seem to be followed by gauge.

**Hardware**
 - Board: hellen154

**To Reproduce**
Set blend parameter as Lua Gauge 1
Axis doesn't change when it is changing in the gauge itself.

**Expected behavior**
Axis is properly followed

**Screenshots**
https://youtu.be/NALTO9jd92A

**logs**
https://rusefi.com/online/view.php?log=1331

**Comment by rusefillc** [comment]
@ElDominio boost logic is not running while RPM is zero, there are other conditions turning boost control off

I've added an indicator right on the blend dialog

![image](https://github.com/rusefi/rusefi/assets/48498823/37a5486d-334e-41aa-b395-ce6a0b67c560)
