### ISSUE TITLE
Disable fans after VSS > x

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#5875]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when fans stay on at speed despite there being no reason to

**Would we need new configuration fields?**
VSS threshold for fans = after this VS, fans are disabled (since airspeed is higher than what fan motor can do anyways)

**Describe the solution you'd like**
An option as described above to disable the fans after a certain VSS

**Describe alternatives you've considered**
writing it in lua

**Comment by rusefillc** [comment]
> I'm always frustrated when fans stay on at speed despite there being no reason to

Why do you care? :)

**Comment by ElDominio** [comment]
<img width="306" alt="image" src="https://github.com/rusefi/rusefi/assets/5685108/7bc4ad65-e3f0-4e15-8be1-dcdbbc6d1a9b">

> Why do you care? :)

Because we are wasting power driving them/motors die from overuse
