### ISSUE TITLE
Lamborghini Diablo 1995 CKP Pattern

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#5876]
Odd crank pattern, uses VR sensors on both crank and cam. Will try to get logic analyzer but i do need to wire up a VR converter to be able to analyze from what i think?

Ckp:
![IMG-20240110-WA0028.jpg](https://github.com/rusefi/rusefi/assets/5685108/3e4f6cd2-2620-4e85-9686-0b53f166929f)

Cmp:
![IMG-20240110-WA0027.jpg](https://github.com/rusefi/rusefi/assets/5685108/3df3d318-aab7-4da7-bef8-65eccecabde7)

**Comment by rusefillc** [comment]
@ElDominio from common sense I would assume google to have at least one photo of that weirdness?

See https://www.ebay.com/itm/325732593310 which at least show the six dowels matching the drawing

**Comment by ElDominio** [comment]
Crank is 6/0 symmetrical VR
Cam uses two VR sensors for one tooth, since it uses two IDENTICAL ecus, one for each bank.

The two cam sensors change the phase of each bank. You can literally swap the ECUs and the car still runs
