### ISSUE TITLE
LUA code and EGT makes ECU to hang

### ISSUE THREAD

**Issue by zed65** [rusefi/rusefi#5889]
**Describe the bug**
Processor hangs with specific LUA code and SPI EGT turned on.

**Hardware**
F407VGT6 Blackboard

**To Reproduce**
see:
https://rusefi.com/forum/viewtopic.php?f=17&t=2688

**Comment by mck1117** [comment]
@rusefillc go look at the call to getMax31855EgtValue in status_loop.cpp and see if the things done in getMax31855EgtValue are a good idea to call from an arbitrary lua call stack

**Comment by rusefillc** [comment]
Things got worse #5893
