### ISSUE TITLE
Possible bug around _OpenBLT_Shared_Params on F7?

### ISSUE THREAD

**Issue by andreika-git** [rusefi/rusefi#5905]
In STM32F4.ld we have:
```
    shared  : org = 0x20000000, len = _OpenBLT_Shared_Params_Size
    ram0    : org = 0x20000000 + _OpenBLT_Shared_Params_Size, len = 128k + RAM3_SIZE - _OpenBLT_Shared_Params_Size /* SRAM1 + SRAM2 + SRAM3 (optionally) */
    ram1    : org = 0x20000000 + _OpenBLT_Shared_Params_Size, len = 112k - _OpenBLT_Shared_Params_Size      /* SRAM1 */
```
The 'shared' region is located just before ram0/ram1 starts...

But in STM32F7.ld we have:
```
    shared      : org = 0x20000000, len = _OpenBLT_Shared_Params_Size
    ram0   (wx) : org = 0x20020000 + _OpenBLT_Shared_Params_Size, len = 384k - _OpenBLT_Shared_Params_Size      /* SRAM1 + SRAM2 */
    ram1   (wx) : org = 0x20020000 + _OpenBLT_Shared_Params_Size, len = 368k - _OpenBLT_Shared_Params_Size      /* SRAM1 */
```
The 'shared' line seems to be just copy-pasted from F4, but actually ram0/1 starts from other address on F7.

Is it a bug?

Do we need a fix like this?
![image](https://github.com/rusefi/rusefi/assets/15104768/6b8809b1-7137-4ac9-b251-47f5d81bc2cf)

**Comment by dron0gus** [comment]
@andreika-git yes, this looks like copy-paste bug. My fault. Please fix this if you working with this code.
