### ISSUE TITLE
Expand daihatsu 3+1 3cyl trigger to 4+1 as well

### ISSUE THREAD

**Issue by runesmdk** [rusefi/rusefi#5925]
Daihatsu uses the n+1 across both 3 and 4 cyl. 
The wiki describes daihatsu trigger as only 3+1 now. 

Their 4+1 works exactly at the same +1 timing as the 3+1, its 4 pulses every 720° crank, and then a single extra pulse at 30° crank.

**Comment by rusefillc** [comment]
@runesmdk see https://github.com/rusefi/rusefi/wiki/All-Supported-Triggers#daihatsu

**Comment by runesmdk** [comment]
> @runesmdk see https://github.com/rusefi/rusefi/wiki/All-Supported-Triggers#daihatsu

That went fast! 

The +1 signal you are referring to isnt tdc however, the tdc is the one before the +1. So the signals fall 0, 30, 180, 360, 540 (atleast according to speeduino wikipedia).
I dont know if that means anything for the rusefi or it just tracks crank degrees. 

Also, the rusefi wiki about triggers dont mention it being coded as a cam-speed signal, i just assume it is?

**Comment by runesmdk** [comment]
"Syncedge rise only", if i use a hall sensor, the signal falls when the sensor signal goes low.

**Comment by rusefillc** [comment]
@runesmdk updated https://github.com/rusefi/rusefi/wiki/All-Supported-Triggers#daihatsu

**Comment by runesmdk** [comment]
> @runesmdk updated https://github.com/rusefi/rusefi/wiki/All-Supported-Triggers#daihatsu

Bang on. What about my previous message about rising only?

**Comment by rusefillc** [comment]
> What about my previous message about rising only?

let's think about it once your engine is idling with current firmware and we see any problems

**Comment by runesmdk** [comment]
> > What about my previous message about rising only?
> 
> let's think about it once your engine is idling with current firmware and we see any problems

The windows on the shutter plate for the hall sensor only fits with falling as the 180° signal shutters arent equal length on the rising, especially not on the +1

**Comment by rusefillc** [comment]
reminder that edge is configurable

![image](https://github.com/rusefi/rusefi/assets/48498823/68b011e5-630e-47c3-9b15-279b742a1e3b)

**Comment by runesmdk** [comment]
> reminder that edge is configurable
> 
> ![image](https://private-user-images.githubusercontent.com/48498823/303452776-68b011e5-630e-47c3-9b15-279b742a1e3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0MTkyMzYsIm5iZiI6MTcwNzQxODkzNiwicGF0aCI6Ii80ODQ5ODgyMy8zMDM0NTI3NzYtNjhiMDExZTUtNjMwZS00N2MzLTliMTUtMjc5Yjc0MmExZTNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDE5MDIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4ZDVjZTI3ODAyODdkMGJmZDczY2I4YzZmNWI1OTQ1YjQyNWU5ZGRjZDRkOGEwNmMxYmM0ZDFjMjRhNGU1OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xoI0cJx2ExIK3v8RLRLx1P8xdbgeucvwdbOB6cIXwpw)

![Screenshot_20240208-200604](https://github.com/rusefi/rusefi/assets/10236408/eaff2d6d-fdd4-4fbb-884e-a18dd591480c)
![Screenshot_20240208-200814](https://github.com/rusefi/rusefi/assets/10236408/50851586-2c2f-477b-8cc2-3e4967fb01e8)

Okay thats great. I was only asking because i saw that
