### ISSUE TITLE
proteus HW0.7v dont have suppressor diode on ETB Power input 

### ISSUE THREAD

**Issue by WOOL929** [rusefi/rusefi#5926]
On the Proteus v0.7 board, the tle9201 power input does not have a suppressor Diode.

![eeschema_GaeTwWb6uo](https://github.com/rusefi/rusefi/assets/113139906/5f67f957-df37-4238-b867-7d85e243dd84)

It seems that if the top pair of arms fails, then the reverse current from the throttle return could become a problem for the nodes on the 12v_MR bus?!

![ApplicationFrameHost_jkQ9t4yFzT](https://github.com/rusefi/rusefi/assets/113139906/f531b557-4f63-4127-9642-46cb3d13f868)

The datasheet has it.
![chrome_dVCn5W3nXH](https://github.com/rusefi/rusefi/assets/113139906/e68bf1e0-4f8b-455f-a156-11e5101465c4)

Maybe it's not even a problem? I'm trying myself as a bug reporter

**Comment by rusefillc** [comment]
@WOOL929 please create same exact issue at https://github.com/mck1117/proteus
