### ISSUE TITLE
build scripts monoliht

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#5935]
* openblt compilation wipes out incremental main firmware state due to pch coupling. in order to have incremental compilation we shall decouple
* autoupdate bundle and full bundle are weirdly coupled
* it's unclear what are the key inputs for any given board configuration: is it folder name or shortBoardId or else?

**Comment by chuckwagoncomputing** [comment]
Please be aware of my current effort to move all build scripts to Make, which I believe will solve this issue.

**Comment by rusefillc** [comment]
> Please be aware of my current effort to move all build scripts to Make, which I believe will solve this issue.

@andreika-git @chuckwagoncomputing how to coordinate this better? @chuckwagoncomputing can you focus for instance on incremental build with openblt and deal with gen_live_data later, or is all that not easily divisible?

**Comment by chuckwagoncomputing** [comment]
OK I'll try to get a PR-able state that fixes incremental builds.
Current state of the project: https://github.com/rusefi/rusefi/compare/master...chuckwagoncomputing:rusefi:makeover?expand=1

**Comment by chuckwagoncomputing** [comment]
Part 0 https://github.com/rusefi/rusefi/pull/5936

**Comment by rusefillc** [comment]
@chuckwagoncomputing what's your proposal for meta info discovery? i.e. what's the unique key and how is everything else resolved from it?

corner cases are mre_f4 and mre_f7 while 4chan and 4chan_f7

**Comment by chuckwagoncomputing** [comment]
Two keys:
- board directory
- build target

Everything else is contained at <board directory>/compile_<build target>.sh

**Comment by rusefillc** [comment]
PS: @chuckwagoncomputing another use-case is https://github.com/rusefi/rusefi/wiki/Custom-Firmware

specifically desire is to have "paralela" mentioned only once within the whole 'https://github.com/rusefi/fw-custom-paralela' repo. Test criteria is "how many entities need renaming/editing once https://github.com/rusefi/fw-custom-example is forked"

since technically at the moment we have one key in compile_XXX.sh file name but there is also compile_proteus_f4_debug.sh which is proteus_f4 but with debug

**Comment by rusefillc** [comment]
PPS @chuckwagoncomputing https://github.com/rusefi/fw-custom-paralela/blob/master/.github/workflows/build-firmware.yaml is an interesting case of meta info consumption

**Comment by chuckwagoncomputing** [comment]
Yes I'm working on that before making https://github.com/rusefi/rusefi/pull/5938 not a draft. I didn't know about the desire to have the name mentioned only once though; that's a wrench in the gears.

**Comment by rusefillc** [comment]
>  I didn't know about the desire to have the name mentioned only once though; that's a wrench in the gears.

I mean nothing is set in stone but just to make it less error-prone and hopefully common sense says that if we fork https://github.com/rusefi/fw-custom-example we produce _one_ entity which ideally should have _one_ key mentioned _once_?

**Comment by chuckwagoncomputing** [comment]
Interesting note regarding keys:
We are now using board directory and bundle name as keys, and then resolving them to a meta-info file. We could use only the meta-info file.
- Get BUNDLE_NAME from the meta-info file name
- Assume BOARD_DIR is the directory the file is in

**Comment by chuckwagoncomputing** [comment]
That's correct. And the BOARD_DIR for all those files is the directory they are in.

I didn't think of it before, but getting BUNDLE_NAME from the meta-info file will require renaming all of the default 'meta-info.env' files to include the bundle name. Or we could just default to using SHORT_BOARD_NAME if the file is meta-info.env.

**Comment by chuckwagoncomputing** [comment]
Actually [common_script_read_meta_info.inc](https://github.com/rusefi/rusefi/blob/master/firmware/config/boards/common_script_read_meta_env.inc) already sets BOARD_DIR to the directory the meta-info file is in.

**Comment by chuckwagoncomputing** [comment]
I'm going to call this completed.
