### ISSUE TITLE
ETB traction control drop is affected by not-highlighted cell

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#5952]
**Describe the bug**
If current slip state is 1.00 and i have two cells in Y column, 1.02 and 1.03., if I write values in 1.03 ETB drops anyways

**Hardware**
 - hellen154hyundai

**To Reproduce**
1. Go to Controller ->Traction Control ETB Drop
2. write vlues in a non-highlighted cell
3. ETB drops

**Expected behavior**
Does not drop ETB in cells not close to the ETB drop

**Screenshots**
https://youtu.be/WwZlngGoSQc

**Comment by zed65** [comment]
Related to:??
![slipBins](https://github.com/rusefi/rusefi/assets/23425941/3cdce2e2-c82e-4259-ac8d-4b01ddbbf2dc)

**Comment by rusefillc** [comment]
Could be consequence of https://github.com/rusefi/rusefi/issues/6139
