### ISSUE TITLE
BUG: firmware error 6550

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#598]
fatal error while enabling self_stimulation after increasing number of cylinders

**Comment by rusefi** [comment]
maybe fixed now?

**Comment by rusefi** [comment]
https://rusefi.com/forum/viewtopic.php?f=15&t=1031&e=1&view=unread#p29655 

CUSTOM_ERR_6591 was reported

also sounds like EMI noise was triggering input pins

**Comment by rusefi** [comment]
looks better now!!!

**Comment by rusefi** [comment]
This bug really needs a unit test - reopening ticket

**Comment by Subrus** [comment]
![image](https://user-images.githubusercontent.com/39065352/43359124-fa3df65e-92a5-11e8-822a-eb88c9096cfe.png)

**Comment by Subrus** [comment]
![image](https://user-images.githubusercontent.com/39065352/43359367-d97f5a30-92a9-11e8-917a-28203f73db28.png)

**Comment by rusefi** [comment]
So the issue is about ownIndex field containing ununitialized value while we are adding additional cylinder while engine is running.

**Comment by rusefi** [comment]
CUSTOM_ERR_6687 reported :(

**Comment by mck1117** [comment]
this is fixed, right?
