### ISSUE TITLE
revive ptrace

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#5983]
we have https://github.com/rusefi/rusefi/wiki/Developer-Performance-Tracing

on master on Proteus F7 I am failing to get any data in the json file. Need to either improve documentation or revive the feature or else

See https://github.com/rusefi/rusefi/commit/0c8785d7d3518f27349d858670de337676981589

**Comment by rusefillc** [comment]
@mck1117 stuff seems to be broken between perf_trace.cpp and BigBuffer

**Comment by andreika-git** [comment]
The BigBuffer is occupied with ToothLogger.
