### ISSUE TITLE
Where did VR threshold config go?

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#5989]
**Describe the bug**
VR Threshold settings vanished? Need to configure low rpm threshold 

**Hardware**
 - Board: 4chan
 - Engine info: not real engine

**To Reproduce**
1. Look for VR Threshold
2. Cannot find

**Expected behavior**
why was this configurability removed?

**Comment by rusefillc** [comment]
"look" sounds like something a human would do? Proper robotic way is to use "search" feature of TS

Screen shot shows snapshot version and search results. I do not see an issue please clarify @ElDominio 

![image](https://github.com/rusefi/rusefi/assets/48498823/fab74864-3c80-4cee-9931-86558fa10174)

**Comment by ElDominio** [comment]
![IMG_20240218_135400.jpg](https://github.com/rusefi/rusefi/assets/5685108/e0ccea11-b733-419c-aeba-444c7ba2cb62)

Fw v20240120

**Comment by ElDominio** [comment]
Was removed at some point apparently but I updated and it's back
