### ISSUE TITLE
Looks like hard-coded idlePositionSensitivityThreshold is not helping

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#599]
We have a hard-coded value of "1" for idlePositionSensitivityThreshold which no one can explain why we have?

		// The threshold is dependent on IAC type (see initIdleHardware())
		if (absF(iacPosition - currentIdlePosition) < idlePositionSensitivityThreshold) {
			idleState = PWM_PRETTY_CLOSE;
			continue; // value is pretty close, let's leave the poor valve alone
		}

**Comment by rusefi** [comment]
I suspect this is root cause of https://rusefi.com/forum/viewtopic.php?f=3&t=1400&p=29704#p29643 problems

**Comment by mck1117** [comment]
open loop vs. closed loop idle transition works great now
