### ISSUE TITLE
HARDWARE VALIDATION FAILED error on multiple units

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#6008]
**Describe the bug**
An odd critical error has been affecting several units, not letting them run

**Hardware**
 - Board:8chan revC, F407 paralela
 - Engine infoford coyote, 4G93

**To Reproduce**
1. Connect usb without 12v
2. See HARDWARE VALIDATION FAILED error

**Expected behavior**
This error does not exist? The error is quite cryptic

**Screenshots**
<img width="560" alt="image" src="https://github.com/rusefi/rusefi/assets/5685108/8e2cfe52-39c3-43a1-bc4c-0550bb0785da">

**Additional context**

**Comment by ElDominio** [comment]
But this was on F407, not 8chan?

**Comment by rusefillc** [comment]
@ElDominio ops. I've missed that part. Just reverted 8chan change

@ElDominio please consider making such important details more obvious by placing into the ticket title instead of vague "multiple units".

**Comment by rusefillc** [comment]
> But this was on F407, not 8chan?

C'mon. Please do much better than "F407".

I refuse to understand "F407" as a reference to any board.

**Comment by rusefillc** [comment]
@ElDominio https://github.com/rusefi/fw-custom-paralela/commit/450b5312bb8bd1019ef3178faaea2992f0b5feff
