### ISSUE TITLE
cygwin or mingw runners?

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#6024]
having really hard time picking gcc versions for unit_tests github actions

https://community.chocolatey.org/packages/mingw#versionhistory

8.5 silent compilation error? https://github.com/rusefi/rusefi/pull/6018
9.4 silent compilation error? https://github.com/rusefi/rusefi/pull/6017
10.2 failure to setup? https://github.com/rusefi/rusefi/pull/6020

https://github.com/marketplace/actions/install-cygwin

**Comment by rusefillc** [comment]
required for https://github.com/rusefi/rusefi/issues/6013

**Comment by chuckwagoncomputing** [comment]
PR to switch to Cygwin: https://github.com/rusefi/rusefi/pull/6055
