### ISSUE TITLE
green PR has broken USE_OPENBLT builds

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#6026]
openblt builds are broken

is it https://github.com/rusefi/rusefi/pull/6023 or unrelated broken dependency?

**Comment by chuckwagoncomputing** [comment]
https://github.com/rusefi/rusefi/pull/6028

**Comment by rusefillc** [comment]
how original PR was green but red master?!

**Comment by chuckwagoncomputing** [comment]
I really don't know. The red was caused by a race condition between two different make instances trying to build the bootloader. Maybe it was just luck?
Anyhow, I think this is fixed.
