### ISSUE TITLE
Hard fault with CJ125 and HIP9011 enabled

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#603]
Repro steps:
1) Enable both CJ125 and HIP9011 on the same SPI port.
2) Save to flash/reboot
3) Crash somewhere in SPI code

**Comment by mck1117** [comment]
I can share a stack trace once I get home.

**Comment by darxfame** [comment]
i've got a hard crash too in the past and then i erased firmware settings from STM and then it worked

**Comment by mck1117** [comment]
I tried that and that didn't fix it.  It was a totally clean config debugging on a spare MCU on the bench with debugger attached, so it's not something weird from the tune on my car.  I'm going to be doing more work on the cj125 controller soon, so looking at this will be involved there.

**Comment by darxfame** [comment]
it is more important!
