### ISSUE TITLE
Document and/or fix LTS upload paths

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#6069]
I hit "Run Workflow with LTS master" and I see files appearing at folders like https://rusefi.com/build_server/lts/alphax-8chan/ with "master" anywhere on path

I see older (?) https://rusefi.com/build_server/lts/lts-2023.01/ and https://rusefi.com/build_server/lts/master/ folders which seem to use different approach

Specifically right now I am looking to make a release candidate. To make a release candidate I need a set of freshly fully build bundles ideally all in order folder not subfolders.

https://github.com/rusefi/rusefi/wiki/Dev-LTS-project seems to be the page to update?

![image](https://github.com/rusefi/rusefi/assets/48498823/9a769028-acd9-4b66-95c3-acc4d630f129)

**Comment by rusefillc** [comment]
@chuckwagoncomputing can you help?

**Comment by chuckwagoncomputing** [comment]
I broke this!
