### ISSUE TITLE
fw-custom-paralela does not upload bundle to build_server

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#6074]
https://github.com/rusefi/fw-custom-paralela/ has the six secrets, three for .ini and three for bundle upload

https://github.com/rusefi/fw-custom-paralela/actions/runs/8073628209/job/22057621020 is just silent about upload status

**Comment by rusefillc** [comment]
@chuckwagoncomputing I've attempted see my two commits. I am missing something please help?

**Comment by chuckwagoncomputing** [comment]
2nd commit is not what you want, `all` only builds firmware, not the bundle.
upload_bundle.sh is meant to be run from the artifacts directory.
https://github.com/rusefi/rusefi/blob/b2fce5aa1d0155f40f41c9d665b5bf1e0371eb07/.github/workflows/build-firmware.yaml#L524-L527
