### ISSUE TITLE
bad fix of sensors reinit has caused a forever CAN listener loop

### ISSUE THREAD

**Issue by runesmdk** [rusefi/rusefi#6079]
Board looses comms (fail to burn page) if set to daihatsu 4cyl trigger using c5 cam1/hall1 input. 

root cause https://github.com/rusefi/rusefi/commit/ee20cbd33b114dd05782faf02728f1966216ae9b
fix https://github.com/rusefi/rusefi/pull/6119
follow up https://github.com/rusefi/rusefi/issues/6120

**Comment by runesmdk** [comment]
> Yes, I am able to reproduce the issue, thank you for the report!
> 
> @runesmdk please use https://github.com/rusefi/rusefi/releases/tag/2024-02-18 as a workaround that one seems to work

I downloaded the fresh snapshot today. This link is to nightly's thats 2 weeks old?

**Comment by rusefillc** [comment]
> This link is to nightly's thats 2 weeks old?

yes

https://github.com/rusefi/rusefi/releases/tag/2024-02-22 does not have burn issue but has 5VP issue

actually https://github.com/rusefi/rusefi/releases/tag/2024-02-27 seems to be OK as well so whatever defect we have introduced seems really recent?

**Comment by runesmdk** [comment]
> > This link is to nightly's thats 2 weeks old?
> 
> yes
> 
> https://github.com/rusefi/rusefi/releases/tag/2024-02-22 does not have burn issue but has 5VP issue
> 
> actually https://github.com/rusefi/rusefi/releases/tag/2024-02-27 seems to be OK as well so whatever defect we have introduced seems really recent?

Will try later, thanks

**Comment by runesmdk** [comment]
> > > This link is to nightly's thats 2 weeks old?
> > 
> > 
> > yes
> > https://github.com/rusefi/rusefi/releases/tag/2024-02-22 does not have burn issue but has 5VP issue
> > actually https://github.com/rusefi/rusefi/releases/tag/2024-02-27 seems to be OK as well so whatever defect we have introduced seems really recent?
> 
> Will try later, thanks

Updated to 2024-02-27. Kept getting "Data write failed for 2 attempts, local data will be refreshed from controller" and "Controller error: Burn page failed crc check" while using "slow comms (wireless)" on usb cable. Switched to "fast comms" and worked. Dont know if i its just because you cant use slow on usb? But daihatsu trigger is now set atleast.

**Comment by rusefillc** [comment]
Does not reproduce with f407 discovery or proteus F7 firmware.

I can reproduce ONLY with uaefi firmware :(

On any TS burn a disconnect happens but uaEFI keeps blinking blue LED. Even rusEFI console is no longer to connect to unit until power cycle. 

So, happy rusEFI console. TS burn breaks comms. Unhappy rusEFI console.

**Comment by rusefillc** [comment]
Does NOT happen with uaEFI firmware on stm32f407 discovery hardware

**Comment by rusefillc** [comment]
DOES happen on uaEFI even after full chip erase.
