### ISSUE TITLE
project issue if tunebymaf selected

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#608]
if tunebymaf is selected TS is showing a warning

Initial error:
1 Errors:
Error: Error in section [VeAnalyzeMaps], unable to parse ini row., Problem at:
[mainController.ini]:[Line:950]: veAnalyzeMap = fuelTableTbl, afrTableTbl, AFRValue, egoCorrection, { 1 }

**Comment by OrchardPerformance** [comment]
I think recent MAF changes have resolved this problem, (specifically a move to VE map) tested and error does not appear for me anymore. 
Can be closed.
