### ISSUE TITLE
local unit tests end up with slightly wrong headers around trigger logic

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#6089]
go make unit_tests
go check local changes

unexpected:
![image](https://github.com/rusefi/rusefi/assets/48498823/12b31ff1-454c-4f12-a18e-e724afd5f3e9)

**Comment by rusefillc** [comment]
@chuckwagoncomputing TriggerWheelTSLogic.java is producing those values we've lost locally

**Comment by rusefillc** [comment]
PS: not sure about steps to reproduce now. maybe it's ./gen_live_documentation.sh not make unit_tests?

**Comment by chuckwagoncomputing** [comment]
I haven't been able to reproduce this. Have you?

**Comment by rusefillc** [comment]
unable to reproduce
