### ISSUE TITLE
Console builds not including .jar files, builds went from 27ish mb to 17ish mb

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#6104]
**Describe the bug**
Console builds from snapshot and nightlies are not including .jar files, making the program not run

**To Reproduce**
1. Download latest snapshot
2. Try to run rusefi_console.exe
3. does not run because no .jar file
4. be sad

**Expected behavior**
console runs

**Comment by rusefillc** [comment]
@chuckwagoncomputing https://rusefi.com/build_server/rusefi_bundle_alphax-4chan.zip is in fact missing both jar files
