### ISSUE TITLE
make clean does not clean firmware/deliver folder

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#6105]
"make clean" might have never cleaned firmware/deliver

**Comment by rusefillc** [comment]
@chuckwagoncomputing do we still use that "deliver" folder at all?

**Comment by chuckwagoncomputing** [comment]
We do use deliver because some actions upload artifacts from it.

**Comment by rusefillc** [comment]
@chuckwagoncomputing low priority ask: can we add a feature of "make clean" cleaning that folder?

**Comment by chuckwagoncomputing** [comment]
Yes, I will add it.
