### ISSUE TITLE
UAEFI Burn page 0 failed from full flash erase and changing reasonable settings

### ISSUE THREAD

**Issue by ggurov** [rusefi/rusefi#6116]
**Describe the bug**
From a full chip erase and fresh firmware flash, unsetting intake/exhaust cam sensor pins causes a TS error

**Hardware**
 - Board: UAEFI
 - Bench

**To Reproduce**
1. Fully erase UAEFI
2. Flash latest firmware (2024-03-02)
3. Open trigger setup menu
4. change cam sensor bank 1 intake/cam sensor bank 1 exhaust to "NONE"
5. click Burn
6. See error

**Expected behavior**
No error is produced, and settings are updated.

**Screenshots**

![image](https://github.com/rusefi/rusefi/assets/2112173/6f98a076-5e42-4c16-849d-c2165439494c)

![image](https://github.com/rusefi/rusefi/assets/2112173/99cd2315-e909-48b3-9102-8b4c990b1589)

![image](https://github.com/rusefi/rusefi/assets/2112173/733fef1c-75f3-4ce6-bea5-175fbf3d3943)

**Additional context**
Controller keeps flashing BLUE

closing TS shows:

![image](https://github.com/rusefi/rusefi/assets/2112173/236e032e-1747-47ba-b0b6-3194abe69e79)

restarting TS - controller cannot reconnect

after controller reset, TS connects, and settings are not updated:

![image](https://github.com/rusefi/rusefi/assets/2112173/38f12397-f747-4159-98b9-f57c1770c7aa)

**Comment by rusefillc** [comment]
Great report! Looks like a dup of #6079

**Comment by rusefillc** [comment]
@ggurov please test with revent commit
