### ISSUE TITLE
Proteus F4 Loss of Comms

### ISSUE THREAD

**Issue by viper128** [rusefi/rusefi#6121]
Describe the bug
Any burn form TS causes Page burn Failed and loss of comms with both TS and rusEFI Console

Hardware:
Board: Proteus F4 0.7

Update firmware to release_20240227 via rusEFI Console
Load tune from TS
Power cycle Proteus
any additional writes cause Page burn failed errors and loss of comms

Vehicle continues to run after loss of comms

**Comment by rusefillc** [comment]
dup of #6079 which was just fixed!
