### ISSUE TITLE
Community insists on configurable comms LED

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#6146]
grrrrr

**Comment by mck1117** [comment]
you know, you don't have to support _every_ board for zero integrator effort, right?

**Comment by rusefillc** [comment]
> you know, you don't have to support _every_ board for zero integrator effort, right?

let the record show that you are available to comment on this issue while having no capacity to respond to https://github.com/rusefi/rusefi/commit/23dfe924ddacc2f349a46abca8ddf34ba8a12e5c

**Comment by rusefillc** [comment]
Use snapshot not release https://rusefi.com/build_server/rusefi_bundle_f407-discovery.zip
