### ISSUE TITLE
Base tune for 154hyundai

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#6158]
Should get most key start Hyundai Genesis Coupe started

If push button start or immobiilized, need to add +360 to trigger angle

https://rusefi.com/online/view.php?msq=1498

**Comment by rusefillc** [comment]
@ElDominio closing because provided tunes have too many random and inconsistency - different cannedpedalToTpsTable different vvtTable1, overall look like two random tunes.

Confused about problem statement, I guess there is no more such thing as "base tune".
