### ISSUE TITLE
CJ125 unit-tests coverage

### ISSUE THREAD

**Issue by andreika-git** [rusefi/rusefi#617]
The CJ125 controller code is potentially dangerous. It controls a powerful MOSFET and high-current WBO heater circuit. If any of this PID control logic fails, it may cause severe damage of WBO sensor or CJ125 hardware. 
Besides, the CJ125 chip is not that protected as it seems...
![image](https://user-images.githubusercontent.com/15104768/47615620-b11be380-dab9-11e8-9bde-e9c5f508bffa.png)

We're already started using our CJ125 code not only in the 'lab' conditions, but on the real cars. That's why we need to take some extra precautions when making any change to existing implementation...

**Comment by mck1117** [comment]
FYI, I'm using the cj125 on my daily driver.  I've put ~1500 miles on it and it works great.

**Comment by mck1117** [comment]
it looks like we have cj125 tests now?
