### ISSUE TITLE
MISRA-C & MISRA-C++ validation

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#62]
We should look into MISRA-C & MISRA-C++

Reported by: rusefi

**Comment by rusefi** [comment]
@dron0gus says "If someday we decide to follow MISRA rules if (!parameters) will break MISRA rule 11.4."

**Comment by mi-hol** [comment]
@rusefillc due to the findings in https://en.wikipedia.org/wiki/MISRA_C#Criticism it would seem to make sense closing this issue.
What is your view?
