### ISSUE TITLE
PR was green but master was not around prepend.txt usage

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#6206]
https://github.com/rusefi/rusefi/pull/6203 which has added new constant into .txt files was mostly green

once pushed into master it was pretty red https://github.com/rusefi/rusefi/commit/ae94f76163bcfe7d4127e682b1f137f0cd125a42 until  https://github.com/rusefi/rusefi/commit/981160698f60cd17483b0391cddfec6bbe80df78#diff-770ceef6672e1e53b6bc353503eed19b1226d4781c487f7ed19044add25359cc has generated proper headers. Next build was happy as expected from the first one

**Comment by rusefillc** [comment]
@chuckwagoncomputing let me create a test PR

**Comment by chuckwagoncomputing** [comment]
Still have problems... I'm working on it.
