### ISSUE TITLE
custom board simulator does not account prepend.txt

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#6225]
https://github.com/rusefi/fw-custom-paralela/commit/d093ae70b25d4974b969a53f17b241ec65f8e654 is red because simulator seems to be creating binary tune snapshot using default value not custom ``LUA_SCRIPT_SIZE`` value which increases calibration image size

**Comment by chuckwagoncomputing** [comment]
It seems like the value set by prepend.txt is being overwritten by the value from rusefi_config.txt which is read later. Has overriding rusefi_config.txt values with prepend.txt been known to work?

**Comment by rusefillc** [comment]
> It seems like the value set by prepend.txt is being overwritten by the value from rusefi_config.txt which is read later. 

100%

proteus https://github.com/rusefi/rusefi/blob/master/firmware/config/boards/proteus/prepend.txt has size override which 500% make it into firmware and java console
