### ISSUE TITLE
trigger definition better validation

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#624]
It should be impossible to do

	s->setTriggerSynchronizationGap(0.9);  
        s->setSecondTriggerSynchronizationGap(1.1);

since gap ranges "0.67 to 1.12" and "0.83 to 1.38" would overlap

it would be nice to add code to detect such invalid sync gaps parameters to reduce confusion for people implementing new triggers

**Comment by alexander-n8hgeg5e** [comment]
maybe for some triggers it's ok to have these overlaps.
For instance as i had  wrongly noted my signal shape i had this trigger:                           
      Signal were:      70,      70,      100,     70
	                  110,     110,     110,      80,
Without the sync anomaly the trigger would be 0.64 , 1.57 and so on ...
this one seems most uniq event : 2. is high, and 3. low while 0 is only 0.80 what is far away from 1.57

        0:      0.80  ->  0.2  - 1.2   not high
        1:	0.91  ->  0.6  - 2     not really important, not low
        2:	1.57  ->  1.1  - 2     high
        3:	0.64  ->  0.2  - 1.1   low
	
(could be described as if not after 1.57 0.64 then sync)
 
the line with "1:" ,... its not not important so, it can overlap...
Is this right? I don't really know.

Maybe some manual like comments in the Trigger structure header file.... or somewhere
and a reference to there from a readme file in the trigger/decoder folder or so..?

**Comment by mck1117** [comment]
Yeah - almost any sequence of gap ratios is valid. Not worth trying to check whether the parameters are valid.
