### ISSUE TITLE
"Switch to OpenBLT" command doesn't work on Proteus-F7

### ISSUE THREAD

**Issue by andreika-git** [rusefi/rusefi#6247]
The "reboot_openblt" command reboots the ECU, but OpenBLT doesn't switch to "backdoor" mode on Proteus-F7...
Something around SharedParamsReadByIndex(0, &value): the value != 1 (but the function returns BLT_TRUE)
The same build works on 2chan (recompiled locally or from bundle).

**Comment by mck1117** [comment]
flush the cache before reboot

**Comment by rusefillc** [comment]
> flush the cache before reboot

@mck1117 do you have a relevant FOME line? How does this work for you on F7?

**Comment by dron0gus** [comment]
https://github.com/rusefi/rusefi/pull/6291

**Comment by mck1117** [comment]
> @mck1117 do you have a relevant FOME line? How does this work for you on F7?

it works and I'm not sure why

**Comment by andreika-git** [comment]
Fixed by https://github.com/rusefi/rusefi/commit/4c7cd85f8bf7b8f6137af45f45c09b30b0dc51fe
