### ISSUE TITLE
wrong trigger naming for missing teeth

### ISSUE THREAD

**Issue by runesmdk** [rusefi/rusefi#6258]
For example, in trigger list exists;
36/1, 60/2 etc.

Other ecu write these as 36-1 and 60-2. The minus indicates missing teeth. The SLASH indicates cam triggerwheel. For instance 60-2/1 is a 60-2 crank with 1 tooth cam.

**Comment by rusefillc** [comment]
@ElDominio can you find your version of this ticket?
