### ISSUE TITLE
static_vector.h:29:17: error: writing 10 bytes into a region of size 0 [-Werror=stringop-overflow=]

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#6270]
new compilation error https://github.com/rusefi/fw-custom-paralela/actions/runs/8379085483/job/22945174108

Probably related to https://github.com/rusefi/rusefi/commit/87c624c61316152f1d2ab113bf84d91c273559f2

Q1: why is rusEFI repo is green? 
Q2: is this a real defect or compiler glitch?

**Comment by rusefillc** [comment]
cleaner report https://github.com/rusefi/fw-custom-paralela/actions/runs/8381981626/job/22954756795

**Comment by chuckwagoncomputing** [comment]
Seems like it's due to https://github.com/rusefi/rusefi/commit/87c624c61316152f1d2ab113bf84d91c273559f2
- The commit before doesn't fail
- That commit fails for a different reason
- The next commit, which fixes that reason, fails for this issue

I have no idea why it's not failing on the main repo, nor what specifically is making it fail.

**Comment by chuckwagoncomputing** [comment]
Compiles with -O0

**Comment by rusefillc** [comment]
@chuckwagoncomputing https://github.com/rusefi/fw-custom-paralela/issues/6?

**Comment by chuckwagoncomputing** [comment]
I can reproduce it locally.
`./bin/compile.sh config/boards/f407-discovery/meta-info.env ../simulator/build/rusefi_simulator`

Also it compiles fine with -01. -02 breaks something.

**Comment by rusefillc** [comment]
can you try

```
// not using 'location' here due to https://github.com/rusefi/rusefi/issues/6270 :(
m_storage[m_size] = value;
```

**Comment by rusefillc** [comment]
@chuckwagoncomputing do we somehow end up with different version of GCC between main repo simulator and custom fw simulator? i.e. back to "why is it green in main repo"?

**Comment by rusefillc** [comment]
my WSL is green

```
rusefi@DESKTOP-2017:~/rusefi/firmware$
rusefi@DESKTOP-2017:~/rusefi/firmware$
rusefi@DESKTOP-2017:~/rusefi/firmware$ ./bin/compile.sh config/boards/f407-discovery/meta-info.env ../simulator/build/rusefi_simulator
[META] Reading meta env from ./config/boards/f407-discovery/meta-info.env
[META] PROJECT_BOARD=
[META] PROJECT_CPU=ARCH_STM32F4
[META] POST_BUILD_SCRIPT=
[META] BOARD_DIR=./config/boards/f407-discovery
[META] USE_OPENBLT=
PROJECT_BOARD: f407-discovery
BOARD_DIR:     ././config/boards/f407-discovery
PROJECT_CPU:   ARCH_STM32F4
SHORT_BOARD_NAME: f407-discovery
CPU_HWLAYER:   ports/stm32/stm32f4
CONFDIR:       ./hw_layer/ports/stm32/stm32f4/cfg
LDSCRIPT:      ./hw_layer/ports/stm32/stm32f4/STM32F4.ld
bash ./gen_signature.sh f407-discovery
cd ./../java_tools && flock -o /tmp/java.lock ./gradlew :config_definition:shadowJar
if [ "$(cat .target-sentinel 2>/dev/null)" != f407-discovery ]; then \
echo f407-discovery >.target-sentinel; fi
cd ./../java_tools && flock -o /tmp/java.lock ./gradlew :config_definition_base:shadowJar
cd ./../java_tools && flock -o /tmp/java.lock ./gradlew :enum_to_string:shadowJar
Generating signature for f407-discovery

BUILD SUCCESSFUL in 968ms
17 actionable tasks: 17 up-to-date

BUILD SUCCESSFUL in 1s
12 actionable tasks: 12 up-to-date

BUILD SUCCESSFUL in 874ms
6 actionable tasks: 6 up-to-date
rusefi@DESKTOP-2017:~/rusefi/firmware$
rusefi@DESKTOP-2017:~/rusefi/firmware$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.4.0-1ubuntu1~20.04.2' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-9QDOt0/gcc-9-9.4.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.2)
```

**Comment by chuckwagoncomputing** [comment]
Nope, that didn't fix it.
It's different between the Build Simulator workflow and the Custom Board workflow because the Build Simulator workflow is building it with -O0.
When the firmware make instance calls it it passes an option to use -O2. This came from [the old build_simulator script](https://github.com/rusefi/rusefi/blob/1efa97101be103057f722f487fdb0c86a3fdc5db/misc/jenkins/build_simulator.sh).

**Comment by rusefillc** [comment]
@chuckwagoncomputing can you just make custom board use happy Olevel?

**Comment by chuckwagoncomputing** [comment]
https://github.com/rusefi/rusefi/pull/6276

**Comment by mck1117** [comment]
if you get an asan fault at a particular optimization level, you're probably relying on undefined behavior somewhere

**Comment by rusefillc** [comment]
* Until https://github.com/rusefi/rusefi/commit/55b6f257253ae93f7d899395f86527935bf8dd67 relatively recently -O2 was always used in this repo! With that commit intention was to use -O2 for bundles (smaller) while with debug for local compilation

* https://github.com/rusefi/rusefi/pull/6277 test PR just to show red within this repo

**Comment by rusefillc** [comment]
> Seems like it's due to [87c624c](https://github.com/rusefi/rusefi/commit/87c624c61316152f1d2ab113bf84d91c273559f2)
 
Apparently FOME has this for quite some time now? https://github.com/FOME-Tech/fome-fw/commit/eed689eb036e39be6426ef678740a4a0e9d160fc

**Comment by rusefillc** [comment]
> if you get an asan fault at a particular optimization level, you're probably relying on undefined behavior somewhere

Let's welcome FOME to the party! https://github.com/FOME-Tech/fome-fw/pull/399 https://github.com/FOME-Tech/fome-fw/issues/400

**Comment by nmschulte** [comment]
see fome-tech/fome-fw#400 (https://github.com/FOME-Tech/fome-fw/pull/399#issuecomment-2126623914)
