### ISSUE TITLE
VVT simulator on real hardware pin with invert option

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#6285]
We have VVT https://github.com/rusefi/rusefi/issues/5640 signal generation in simulator

Next step would be to produce VVT signal alongside crank signal on real hardware

Specifically it's desired to have 60/2 on crank PD0 and Bosch Quick Start on CAM/VVT on PD1 on discovery

**Comment by rusefillc** [comment]
configuration pin added https://github.com/rusefi/rusefi/commit/a309e9f3663008b769581d870f429ddd05366673

OutputPin wiring attempt https://github.com/rusefi/rusefi/commit/4d1b59d15780f529f685ca551f671ad5b308f644

but logic analyzer shows generated 60/2 crank but nothing on VVT generated

**Comment by andreika-git** [comment]
Well, it works for me (compiled from current master, no changes)...

![image](https://github.com/rusefi/rusefi/assets/15104768/79504321-06b0-4914-a0df-4236924ab4c0)

![image](https://github.com/rusefi/rusefi/assets/15104768/4973514f-85ad-4c3a-91a8-2afcaf7ca41b)
![image](https://github.com/rusefi/rusefi/assets/15104768/29e2ec9c-7fcf-492e-8253-eb19d8f8740b)

**Comment by rusefillc** [comment]
cam pin output mode added
