### ISSUE TITLE
uaefi stops firing ignition correcty after being powered on for over 4-5 days. 

### ISSUE THREAD

**Issue by ggurov** [rusefi/rusefi#6292]
**Describe the bug**
unit was on a bench, at 7000 rpm, after some time it was noticed that ignition status led were not blinking the right pattern
logic analyzer used to calture pattern

![image](https://github.com/rusefi/rusefi/assets/2112173/2ebe8162-7e5b-4b2d-8930-083d6bd6b8ae)

after reset (power down 12v and pull usb, just 12v power down did not fix it)

the pattern went back to proper 6 cyl 
![image](https://github.com/rusefi/rusefi/assets/2112173/3fc0a6c9-baaa-4694-b956-1d5bf0bc7baa)
pattern

**Hardware**
 - uaefi
 - bench with 36-2 + cam stim

**To Reproduce**
1. set 7000 rpm on stim
2. lock timing to 6 degrees btdc
3. wait a while ?
4. maybe see bad pattern ?

**Expected behavior**
ignition to continue expected pattern

**Additional context**
i don't think i'm crazy

**Comment by ggurov** [comment]
confirmed not crazy



unit uptime: 148000 seconds, 41 hours give or take. was fine at 35-36 hours

uaefi rusefi 20240312


tune: https://rusefi.com/online/view.php?msq=1629
short log: https://rusefi.com/online/view.php?log=1362


reproduce this again, almost 48 hours of unit being on ~10000 rpm
locked ignition timing,, not any particular value




1000 rpm logic analyzer capture:
console indicates 4ms dwell, there's at least 1 of those present in one of the ignition channels (D4-D9)
injection doesn't seem to be affected (D10-D15)


![image](https://github.com/rusefi/rusefi/assets/2112173/cf735b5e-8dc3-4800-876f-0d11adae4ec4)


this seems to still be going up:


![image](https://github.com/rusefi/rusefi/assets/2112173/7cbb86a6-0eed-4217-b3b0-588cf3e378a7)

console seems to throw an exception:

![image](https://github.com/rusefi/rusefi/assets/2112173/ccd81e2e-a989-4d60-8153-be9ffea1d58b)


![image](https://github.com/rusefi/rusefi/assets/2112173/27d820e1-9e37-4036-b1b9-a66a20d276b8)



the pattern changes with RPM 2700 wavey


![image](https://github.com/rusefi/rusefi/assets/2112173/4a350ab0-9087-4e05-aca1-9fdfc9bdce86)



2500 rpm,, clusters:

![image](https://github.com/rusefi/rusefi/assets/2112173/1d053ab3-ace1-46af-958c-169e180b5370)


sometimes there's signals absent in channels completely:

![image](https://github.com/rusefi/rusefi/assets/2112173/2e9f7ba3-f8fa-448b-a7f8-528728655640)


console engine sniffer shows weird coil durations:

![image](https://github.com/rusefi/rusefi/assets/2112173/798b246f-fe34-4a8b-aa31-8a35c0e0abc8)


longer chart

![image](https://github.com/rusefi/rusefi/assets/2112173/49986b08-5921-4ccd-9552-3883e996aab7)


2024-03-26_06_44_11_977: EngineState: WARNING: C9009: looks like skipped spark event 11952948 Coil 3
2024-03-26_06_44_11_978: EngineState: WARNING: C9011: re-adding element into event_queue


2024-03-26_06_48_05_120: EngineState: WARNING: C9009: looks like skipped spark event 11956691 Coil 5
2024-03-26_06_48_05_123: EngineState: WARNING: C9011: re-adding element into event_queue


![image](https://github.com/rusefi/rusefi/assets/2112173/cc5fdf94-3129-44c0-a816-695394601db3)



these warnings seem to be accumulating quite rapidly

	CUSTOM_OUT_OF_ORDER_COIL = 9012,


after fiddling with nothing much really, pattern changed to this:

half the ignition channels at like 1/10th dwell, for a few seconds, then switch to the other 3 channels with the same- 2500 rpm


![image](https://github.com/rusefi/rusefi/assets/2112173/6428b951-80e1-4708-a1de-f4aa93cdd577)


around 7500 rpm, dwell starts out from 0, increases to indicated 4ms, then disappears:

![image](https://github.com/rusefi/rusefi/assets/2112173/3ddd4d30-febe-4e9d-9c6c-98f104981fc7)


sometimes channels seem to fire together: 2 5 on the left, and 3-4 on the right

![image](https://github.com/rusefi/rusefi/assets/2112173/caa1200c-f8bc-42ce-a7fd-caf15f331634)


3600 rpm:

no signal at all on ign1 or ign6, which after a few seconds flips to other channels being empty.


![image](https://github.com/rusefi/rusefi/assets/2112173/69411349-b5d6-4282-abf0-b3fe60dea046)

**Comment by rusefillc** [comment]
Thank you @ggurov this is valuable data! Let me add some tools to reproduce this first.

**Comment by ggurov** [comment]
https://rusefi.com/online/view.php?log=1363 better log file, previous log file has time jumping by quarter of a second while garbage collection runs, this one is clean.

**Comment by rusefillc** [comment]
@ggurov any chance you can attempt reproducing same with self-stimulation?

@ggurov any chance you could attempt same with lower tooth trigger count?

@ggurov any chance you could attempt this with three times slower RPM?

**Comment by mck1117** [comment]
48 hours at 10k rpm on a 36-1 is almost exactly 2^30 teeth

**Comment by mck1117** [comment]
I think the tl;dr might be "don't run for that long"

**Comment by rusefillc** [comment]
> what about generators ? they run longer

+1

**Comment by rusefillc** [comment]
@kifir23917 
* what's the smart way to approach this issue?
* would a unit test with very quick time movement help us here?

**Comment by rusefillc** [comment]
Wonder if this ticket here is a variation of #6451? Need to reproduce with current firmware.

**Comment by rusefillc** [comment]
Closing under the assumption of dup of https://github.com/rusefi/rusefi/issues/6451
