### ISSUE TITLE
Jeep XJ 4 Cyl not on "All Supported Triggers"  page

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#6324]
**Describe the bug**
There is no description of "Jeep XJ 4cyl"  on https://github.com/rusefi/rusefi/wiki/All-Supported-Triggers#jeep page

**Hardware**
 - Board: 2chan 
 - Engine info Jeep 2.5L engine

**Expected behavior**
There is some sort of visualization of what this trigger expects to see, like the following screenshot:

**Screenshots**
![Untitled](https://github.com/rusefi/rusefi/assets/5685108/058c1237-3dbf-4afc-9ca8-0d5038d09f4e)

Is it the upper one that is expected on Jeep XJ 4 cyl?

**Comment by ElDominio** [comment]
![image](https://github.com/rusefi/rusefi/assets/5685108/974b9f1a-ad74-407e-8bef-6e663a3ad674)


I'm working on a setup with this trigger, but I see it wants primary/secondary channel even though they are split from the factory? Shouldn't this do crank decoding seperate from cam decoding, and shouldn't it just use single tooth cam?

**Comment by rusefillc** [comment]
@ElDominio https://github.com/rusefi/rusefi/wiki/All-Supported-Triggers#jeep-4-cyl added

**Comment by rusefillc** [comment]
> Shouldn't this do crank decoding separate from cam decoding, and shouldn't it just use single tooth cam?

yes it should
