### ISSUE TITLE
six generated files not pushed into git

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#6333]
i would expect these files to be auto-generated by actions and not be modified locally, i believe that was the case at some point?

![image](https://github.com/rusefi/rusefi/assets/48498823/318637e8-eebc-42c8-bcdc-1a242595e82b)

**Comment by rusefillc** [comment]
master is red with
```
Run git config --local user.email "action@github.com"
fatal: pathspec 'console/binary/generated/*.ini' did not match any files
```

**Comment by chuckwagoncomputing** [comment]
I think it needs a leading firmware/ but I can't get to it until late tonight.

**Comment by rusefillc** [comment]
> I think it needs a leading firmware/ but I can't get to it until late tonight.

Done https://github.com/rusefi/rusefi/commit/2cea463027cc8797087ccaca35f99edac611794e thank you @chuckwagoncomputing
