### ISSUE TITLE
Lua: setBoostDutyAdd can target values under 0

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#6339]
**Describe the bug**
If the results of boost duty table + setBoostDutyAdd is a negative value, it is reported as such in tunerstudio. What is the final boost duty if the value shown is -100?

**Hardware**
 - Board: 4chan

**To Reproduce**
1. Write Lua function with a big, negative setBoostDutyAdd.
Watch boost duty be negative

**Expected behavior**
Boost duty is clamped to 0.

**Comment by rusefillc** [comment]
Actual boost duty is definitely clamped, looks like what you are focusing here is the gauge not matching actual physical world.

@ElDominio do we have similar issue on ETB output gauge and/or idle gauge?
