### ISSUE TITLE
alpha-n vs map estimation vs MAP sensor

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#6344]
rusEFI alpha-n works via VE table, VE table has MAP axis

in alpha-n we are assuming LACK of MAP sensor do we? in alpha-n we are _estimating_ MAP.

What if we have MAP sensor configured? Would that be a major usability issue?

**Comment by rusefillc** [comment]
See also https://github.com/rusefi/rusefi/issues/6346

**Comment by runesmdk** [comment]
Could alpha-n be pure alpha-n (tps) instead of map estimation? Or do we need to just select speed density and override y axis to tps to obtain that?

**Comment by ElDominio** [comment]
> > rusEFI alpha-n works via VE table, VE table has MAP axis
> > in alpha-n we are assuming LACK of MAP sensor do we? in alpha-n we are _estimating_ MAP.
> > What if we have MAP sensor configured? Would that be a major usability issue?
> 
> Could alpha-n be pure alpha-n (tps) instead of map estimation? Or do we need to just select speed density and override y axis to tps to obtain that?

If you choose AlphaN as the fueling strategy, MAP is not used for anything. @rusefillc means that the model of AlphaN is a way to represent air, but MAP estimation is a seperate table used as a fallback only in Speed Density mode, not used in AlphaN

**Comment by runesmdk** [comment]
> > > rusEFI alpha-n works via VE table, VE table has MAP axis
> > > in alpha-n we are assuming LACK of MAP sensor do we? in alpha-n we are _estimating_ MAP.
> > > What if we have MAP sensor configured? Would that be a major usability issue?
> > 
> > 
> > Could alpha-n be pure alpha-n (tps) instead of map estimation? Or do we need to just select speed density and override y axis to tps to obtain that?
> 
> If you choose AlphaN as the fueling strategy, MAP is not used for anything. @rusefillc means that the model of AlphaN is a way to represent air, but MAP estimation is a seperate table used as a fallback only in Speed Density mode, not used in AlphaN

So my Y lookup is tps then. I just took the statement about estimating map when in alpha-n as direct fact.

**Comment by rusefillc** [comment]
> I just took the statement about estimating map when in alpha-n as direct fact.

@runesmdk please make sure to read complete conversation on tickets
