### ISSUE TITLE
Overdwell at times around syncloss while cranking

### ISSUE THREAD

**Issue by ggurov** [rusefi/rusefi#6349]
**Describe the bug**
At times while cranking when sync loss happens, , there is long dwell periods, which could damage components

**Hardware**
 - Board: uaefi
 - Engine : bench

**To Reproduce**
1. set external trigger wheel to below cranking  rpm 
2. start logic analyzer capture
3. observe sync loss occur (if it does, for one reason or another)
4. examine signals

**Expected behavior**
Dwell not to exceed a safe-ish treshold

**Screenshots**
example of 150ms dwell

![image](https://github.com/rusefi/rusefi/assets/2112173/eea080ab-2c96-4d46-9245-7e377be55e2c)

example of 460ms dwell:

![image](https://github.com/rusefi/rusefi/assets/2112173/bf4886f1-7c97-4c59-877c-553e01295451)

**Comment by rusefillc** [comment]
@ggurov please provide recipient rusEFI tune

@ggurov any chance of rusEFI logs for when the issue happens?

@ggurov what do you use for external signal simulation? would you be able to reproduce with external rusEFI maybe on discovery?

**Comment by ggurov** [comment]
more info: sync loss while cranking came from noisy ADC that drove target RPM on a stim.

stim adjusted RPM between teeth while outputing signals:

![image](https://github.com/rusefi/rusefi/assets/2112173/91b16fd6-2cc0-4701-bc47-de1a4cbf962c)

so RPM changes rather wildly while virtual wheel is rotating, confusing decoder with long/short teeth.

this generated decent amount of sync loss. leading to the discovery of overdwell.

**Comment by ggurov** [comment]
reproduced to capture tune and log:

tune: https://rusefi.com/online/view.php?msq=1637
log: https://rusefi.com/online/view.php?log=1375

relevant: 
![image](https://github.com/rusefi/rusefi/assets/2112173/863382ba-c383-4516-baa7-d1dff5453ad1)


coilstate3 should not be long like that.

**Comment by rusefillc** [comment]
@ggurov just ordered https://www.amazon.com/gp/product/B0BC7FM7FD

**Comment by ggurov** [comment]
external trigger is done using an arduino uno ( https://www.amazon.com/WWZMDiB-ATmega328P-microcontroller-Development-Compatible/dp/B0BV9XFQ5T/ - has to be atmega328 based ) and an optoisolator board (https://www.amazon.com/gp/product/B0BC7FM7FD) that's driving a 12v signal from UNO's outputs

software is "Ardustim", slightly modified to not need the UI - attached here

[ardustim-for-overdwell.zip](https://github.com/rusefi/rusefi/files/14923290/ardustim-for-overdwell.zip)

this version boots up with 36-2 + 1 cam hardcoded, storage.ino:

```
void loadConfig()
{
  if(EEPROM.read(EEPROM_VERSION) == 255 || 1)
  //if(true)
  {
    //New arduino
    selected_wheel = THIRTY_SIX_MINUS_ONE_WITH_SECOND_TRIGGER; //36-1  <-----------
//    selected_wheel = SIXTY_MINUS_TWO_WITH_CAM; //36-1
    wanted_rpm = 200;
    mode = POT_RPM;
  }

```

pin 8 is crank
pin 9 is cam

  ```
pinMode(8, OUTPUT); /* Primary (crank usually) output */
  pinMode(9, OUTPUT); /* Secondary (cam1 usually) output */
```

A0 input gets a variable resistor to adjust RPM.

using the optoisolator board:

arduino pin 8 goes to in1
arduino pin 9 goes to in2
join the grounds
HVCC goes to 12v

OUT1 goes to crank in on ECU - hall ( may need 1k pullup to 12v)
OUT2 goes to cam in on ECU - hall ( may need 1k pullup to 12v)

this simulates a 12v hall effect sensor, inversion is taken care of, what goes into IN, comes out of OUT logically

**Comment by rusefillc** [comment]
@ggurov https://github.com/rusefi/Ardu-Stim/tree/30-to-300 with https://github.com/rusefi/Ardu-Stim/commit/8d08850ba7f3582188397a7a9dc6e79fc0dda2fe

**Comment by mck1117** [comment]
is overdwell protection somehow broken?

**Comment by ggurov** [comment]
there is no setting for overdwell

**Comment by mck1117** [comment]
> there is no setting for overdwell

correct, it's supposed to be always enabled at 1.5x normal dwell

**Comment by rusefillc** [comment]
> correct, it's supposed to be always enabled at 1.5x normal dwell

there is '!limitedSpark' check around there which I am not sure about

**Comment by rusefillc** [comment]
@ggurov shot into the darkness can you try artifact from https://github.com/rusefi/rusefi/pull/6351?

**Comment by rusefillc** [comment]
@ggurov master has some extra logging now https://github.com/rusefi/rusefi/commit/189539b51fb30bafc87f0c2c1005aa51f736bd72

**Comment by rusefillc** [comment]
@ggurov any chance you can add a couple of photos of the complete test setup?

For some reason I am tempted to simply solder some of the revenant things together.

**Comment by ggurov** [comment]
![image](https://github.com/rusefi/rusefi/assets/2112173/bcfa32a9-82af-447e-933f-c24be7b76815)
![image](https://github.com/rusefi/rusefi/assets/2112173/3c467e4a-2983-41e4-b175-7406fe899af1)

2024-04-10_11_45_41_840: EngineState: WARNING: C9003: primary trigger error: not enough teeth between sync points: expected 34/0 got 21/0
2024-04-10_11_45_43_935: EngineState: WARNING: C9012: out-of-order coil off Coil 3

![image](https://github.com/rusefi/rusefi/assets/2112173/5ff80d78-0df9-4faf-a6f8-777e0e4c7499)

**Comment by ggurov** [comment]
@rusefillc 
there's not much there, here's the picture.

it's a fairly basic engine simulator, iat/clt, tps/o2/map (unlabeled)

relevant parts are the boards on the right, blue board with atmega328 in a zif socket is my arduino uno that's running the code.

from that arduino uno, pin8 goes to crank input, pin9 goes to cam input on uaefi through the mess of wires on the left at the bottom of the board with variable resistors

the variable resistor labeled RPM is hooked up to 5v, A0, and ground on arduino uno to adjust RPM.

should be a pretty minimal set of wires

to uaefi: 
ground
12v
 arduino pin8 to crank (vr or hall ?)
arduino pin9 to cam (vr or hall ?)
arduino ground

usbc

on arduino variable resistor ground, a0, aref



![image](https://github.com/rusefi/rusefi/assets/2112173/c998be66-90f5-48fb-9557-04ffa72f70e8)

**Comment by ggurov** [comment]
the on time for that channel (D6) lasts pretty much a full rev... give or take a few ms. 

![image](https://github.com/rusefi/rusefi/assets/2112173/b22de45b-1831-4ce9-b29f-afdfc05f7443)

**Comment by rusefillc** [comment]
@ggurov fancy approach to investigate would be https://github.com/rusefi/rusefi/issues/6355

**Comment by mck1117** [comment]
@ggurov do you intend to have `Always use instant RPM` enabled on the experimental page?

**Comment by ggurov** [comment]
it makes the logs look nicer, if it’s better internally for running consistency to have that off, it wold be nice to have the logs be more smooth transition . i’ll give MLV’s smoothing a shot.


what’s the recommendation ? probably needs another thread so we don’t pollute this one.

**Comment by rusefillc** [comment]
@mck1117 thank you!

@ggurov we have a chance can you please test?

**Comment by ggurov** [comment]
i'll pull down artifacts from #6349 and try it out, but i just disabled instant RPM(reboot and powerdown and stuff proper), was able to get overdwell around cranking RPM with noisy trigger:

![image](https://github.com/rusefi/rusefi/assets/2112173/c079f75d-de5a-4632-a97c-cee1dff468c9)

**Comment by rusefillc** [comment]
> i just disabled instant RPM(reboot and powerdown and stuff proper), was able to get overdwell around cranking RPM with noisy trigger:

plz provide snapshots. First two are already in this repo just no decoding and no testing code so far https://github.com/rusefi/rusefi/commit/9c3385465371f3486492127e796a2c3a39dad4db

**Comment by ggurov** [comment]
[2ch-overdwell-no-instant-rpm.zip](https://github.com/rusefi/rusefi/files/14961511/2ch-overdwell-no-instant-rpm.zip)

**Comment by ggurov** [comment]
with https://github.com/rusefi/rusefi/commit/752db20ba2ff04c1f61906194d9011e3f8c1704a 

overdwell still reproduced with noisy trigger:

![image](https://github.com/rusefi/rusefi/assets/2112173/29437339-7c6a-48cb-87fd-84234d12148d)


[1ch-overdwell-with-752db20-master-65034.zip](https://github.com/rusefi/rusefi/files/14961555/1ch-overdwell-with-752db20-master-65034.zip)

tune: https://rusefi.com/online/view.php?msq=1639

**Comment by mck1117** [comment]
> with [752db20](https://github.com/rusefi/rusefi/commit/752db20ba2ff04c1f61906194d9011e3f8c1704a)
> 
> overdwell still reproduced with noisy trigger, instant rpm is off in the tune as well.

try it with instant RPM turned back on

**Comment by ggurov** [comment]
this is the longest one i've seen so far: ign ch 6 (D9), on for 8.6 seconds, instant RPM ON

![image](https://github.com/rusefi/rusefi/assets/2112173/b4bebf55-d6e0-4bb8-80bc-f0ce57370eb6)


[ign-ch6-on-for-8-seconds.zip](https://github.com/rusefi/rusefi/files/14961590/ign-ch6-on-for-8-seconds.zip)

**Comment by rusefillc** [comment]
@ggurov can you please test again in light of https://github.com/rusefi/rusefi/commit/4bc38d3543a8a9faf7416ecfeb7dff08a9dba86f?

**Comment by ggurov** [comment]
looks much better, cannot reproduce the condition anymore back to back previous firmware -> master 20240418 👍
