### ISSUE TITLE
Refactor Trigger System

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#635]
trigger system runs on a significant amount of magic and should be simplified

One of the most obvious issues is the coupling between TriggerShape and DECLARE_ENGINE_PARAMETER_SUFFIX. 

See also https://rusefi.com/forum/viewtopic.php?f=5&t=1439

**Comment by OrchardPerformance** [comment]
Is this a software task that can be finished and closed?

**Comment by rusefillc** [comment]
no clear scope at this point
