### ISSUE TITLE
logic analyzer binary or CSV to reproduce Overdwell defect without real hardware

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#6355]
See https://github.com/rusefi/rusefi/blob/master/unit_tests/tests/trigger/resources/readme.md

Would be great to have full logic analyzer recording of the incident which I would be able to convert into same or similar CSV format, and reproduce the issue without real hardware!

**Comment by mck1117** [comment]
doesn't saleae let you save as a csv?

**Comment by rusefillc** [comment]
> doesn't saleae let you save as a csv?

Yes if @ggurov uses a saleae we are golden. If @ggurov uses something else, that something else would need to provide same functionality. Ideally I need both a file working with UI (which for saleae means .logicdata) and CSV.

**Comment by mck1117** [comment]
his screenshots are of sigrok, which I guarantee can export as csv as well

**Comment by rusefillc** [comment]
> his screenshots are of sigrok, which I guarantee can export as csv as well

TIL https://sigrok.org/wiki/PulseView

**Comment by ggurov** [comment]
attached are sigrok session files that contain runs with overdwell. 

[overdwell-sigrok-sessions.zip](https://github.com/rusefi/rusefi/files/14948359/overdwell-sigrok-sessions.zip)

**Comment by rusefillc** [comment]
export takes FOREVER. it has moved from 0% but it plans to somehow spend a few MINUTES exporting?

also need help exporting only top (crank) channel


![pulseview_vNzoazXi1A](https://github.com/rusefi/rusefi/assets/48498823/805888e7-964b-434a-beb7-3874190a0e53)

**Comment by rusefillc** [comment]
> which I guarantee can export as csv as well

Does this warranty apply to "export only edges" @mck1117 ?

**Comment by rusefillc** [comment]
We have .csv and automated test

**Comment by rusefillc** [comment]
> his screenshots are of sigrok, which I guarantee can export as csv as well

https://github.com/rusefi/rusefi/issues/6403
