### ISSUE TITLE
tle9104 discovery test

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#6361]
We have https://github.com/rusefi/rusefi-hardware/tree/main/tle9104-breakout
We have https://github.com/rusefi/rusefi/blob/cd74860f371dca676dcaf8fead2ed591cfc4a454/firmware/hw_layer/drivers/gpio/tle9104.cpp

Next step would be to add some wires and test configuration

![image](https://github.com/rusefi/rusefi/assets/48498823/9ee1b6e8-d7d9-47a1-9cf0-9036120cee8b)

**Comment by dron0gus** [comment]
Done in https://github.com/rusefi/rusefi/pull/6648 ? @rusefillc close?
