### ISSUE TITLE
Knock retard does not pull timing unless bottom row of "Max Knock Retard" is populated

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#6370]
**Describe the bug**
If the "Max Knock Retard" is populated like this:
![image](https://github.com/rusefi/rusefi/assets/5685108/d0b07c52-0713-4763-9067-75426aeffbeb)

Timing will not be trimmed even if knock is detected.

Now populating the table like this
![image](https://github.com/rusefi/rusefi/assets/5685108/d1a8daf3-8fbe-484e-91d4-9f329ef9fe8c)

Timing is pulled as expected

**Hardware**
 - Board: custom paralela PNP
 - engine: 5EFE

**To Reproduce**
1. Enable knock
2. Do not populate the first row (from bottom up) of Max Knock Retard
3. Trigger a Knock event

**Expected behavior**
Timing is pulled correctly vs TPS, since at low TPS values we might not want to pull as much timing

**Screenshots**
![image](https://github.com/rusefi/rusefi/assets/5685108/bfdaa17c-7663-4c75-9699-ddb03192746c)

**Additional context**
[noknockifrow0.zip](https://github.com/rusefi/rusefi/files/15021685/noknockifrow0.zip)

**Comment by rusefillc** [comment]
#6139
