### ISSUE TITLE
PCF8575 vs PCA9555APW

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#6371]
we have
```
	// looks like we support PCF8575 i2c I/O expander
	m_i2c.read(/*address*/0x20, variant, sizeof(variant));
```

1) what is magic 0x20 where is it mentioned on https://www.ti.com/lit/ds/symlink/pcf8575.pdf?ts=1713412507841?
2) what about JLC C2652295 PCA9555APW is it compatible or how do we make it work?

**Comment by VFRenjoyer** [comment]
![image](https://github.com/rusefi/rusefi/assets/155034532/c1aa519f-bbea-4a2b-b279-d20230907f63)
Page 16 on the datasheet has this table defining the address. The default address is 0100000, and the last three bits can be set with pins A2,A1,A0

**Comment by rusefillc** [comment]
0100xxx0?

**Comment by rusefillc** [comment]
Ohh

![image](https://github.com/rusefi/rusefi/assets/48498823/2bdd7eb8-f70a-4ec7-aa22-008e904063a3)

See also https://forum.arduino.cc/t/pcf8574p-or-pca9555-creating-additional-do/89128/5

**Comment by dron0gus** [comment]
Done on https://github.com/rusefi/rusefi/pull/6714
