### ISSUE TITLE
ADC array out of bounds when using analog muxes

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#6376]
hellen on a bike: both TS and SD card logs report -32v on secondary TPS and secondary PPS

WAT?!

![image](https://github.com/rusefi/rusefi/assets/48498823/24757517-16cc-4d0e-b5e9-4378c9919280)

**Comment by rusefillc** [comment]
[re_13.zip](https://github.com/rusefi/rusefi/files/15046274/re_13.zip)

**Comment by rusefillc** [comment]
decoded TPS/PPS and error counter follow the broken voltage so it's more than just a logging glitch

**Comment by rusefillc** [comment]
Related to https://github.com/rusefi/rusefi/issues/6394

**Comment by rusefillc** [comment]
![image](https://github.com/rusefi/rusefi/assets/48498823/d7d4384c-a45e-4f4b-9808-900697151980)

**Comment by rusefillc** [comment]
hello Bi Quad filter? funny how we have seem similar (?) negative recently https://github.com/rusefi/rusefi/issues/4117#issuecomment-2050459260

**Comment by rusefillc** [comment]
rawPpsSecondary is with Bi Quad filter applied negative value tells us that at least one very noisy data point was received

200Hz sounds about right for this application

new data points in the logs: two rawRawPps fields which are completely unprocessed ADC values. Now we need a lucky log with those showing a problem

**Comment by rusefillc** [comment]
currently ``#define ADC_SAMPLING_FAST ADC_SAMPLE_28``


```
#define ADC_SAMPLE_3            0   /**< @brief 3 cycles sampling time.     */
#define ADC_SAMPLE_15           1   /**< @brief 15 cycles sampling time.    */
#define ADC_SAMPLE_28           2   /**< @brief 28 cycles sampling time.    */
#define ADC_SAMPLE_56           3   /**< @brief 56 cycles sampling time.    */
#define ADC_SAMPLE_84           4   /**< @brief 84 cycles sampling time.    */
#define ADC_SAMPLE_112          5   /**< @brief 112 cycles sampling time.   */
#define ADC_SAMPLE_144          6   /**< @brief 144 cycles sampling time.   */
#define ADC_SAMPLE_480          7   /**< @brief 480 cycles sampling time.   */
```

**Comment by rusefillc** [comment]
@dron0gus 

![javaw_9CPxqaWEJT](https://github.com/rusefi/rusefi/assets/48498823/35e2127f-4d5f-4546-bfa4-82d3053fd975)

**Comment by rusefillc** [comment]
![image](https://github.com/rusefi/rusefi/assets/48498823/edccf47b-21b6-4045-85a8-79e1b38ab681)

**Comment by andreika-git** [comment]
Maybe we should somehow check fastAdc.errorsCount which gets incremented on ADC conversion errors?

**Comment by andreika-git** [comment]
One of possible reasons - ADC buffer memory corruption?..

**Comment by rusefillc** [comment]
![WhatsApp Image 2024-04-22 at 12 14 46_43cfb896](https://github.com/rusefi/rusefi/assets/48498823/9334c0bf-b90e-44fc-9be8-9970c24293e3)

**Comment by dron0gus** [comment]
discovery f407. tps1 and tps2 set to PA0..PA3.
Just press enable self-stimulation, disable few times. Get +1 fastAdcErrorCounter.
Fast ADC is not in correct state when timer callback is executed. ADC is in ADC_ACTIVE state.
![Screenshot from 2024-04-23 00-37-31](https://github.com/rusefi/rusefi/assets/28624689/63b8f10d-61ec-4f06-a228-1d46409b1b5a)

**Comment by dron0gus** [comment]
https://github.com/rusefi/rusefi/blob/294040c22a407e389a6f10faea0d052d163a782a/firmware/hw_layer/adc/adc_inputs.cpp#L176 why this was commented out? Cause to much noise?

**Comment by rusefillc** [comment]
> why this was commented out? Cause to much noise?

Just created separate issue for that https://github.com/rusefi/rusefi/issues/6399 just in case

**Comment by rusefillc** [comment]
![image](https://github.com/rusefi/rusefi/assets/48498823/fd7c61ad-52b0-4a40-a553-6a92635ee0b9)

**Comment by rusefillc** [comment]
@dron0gus update: maaaaaaaaybe only happens while SD card logging

**Comment by rusefillc** [comment]
![image](https://github.com/rusefi/rusefi/assets/48498823/153b2349-218d-421c-8b0e-11ff59d065df)

**Comment by rusefillc** [comment]
![image](https://github.com/rusefi/rusefi/assets/48498823/3635f90f-c175-483d-8a02-3ae7b0de36e9)

![image](https://github.com/rusefi/rusefi/assets/48498823/4571b930-b53c-4ae5-94bd-95e6c9513ef1)

**Comment by ElDominio** [comment]
> @dron0gus update: maaaaaaaaybe only happens while SD card logging

Just in case i barely ever use sd logging

**Comment by dron0gus** [comment]
Looks like really related to SD/MMC access.
![Screenshot from 2024-07-13 12-39-11](https://github.com/user-attachments/assets/37fa29eb-c051-4fb8-9907-65b9ca142157)

**Comment by dron0gus** [comment]
Possible reason https://github.com/rusefi/rusefi/pull/6712
