### ISSUE TITLE
Ford Coyote Exhaust VVT position error

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#6402]
**Describe the bug**
Exhaust VVT position is resolved correctly up to 20 degrees; after that, there is an error and VVT angle jumps about.

**Hardware**
 - Board: 8chan revC
 - Engine info Ford Coyote

**To Reproduce**
1. Set VVT trigger type to Ford Coyote
2. Enable exhaust VR cams
3. rev engine and move VVT position using actuators

**Expected behavior**
VVT angle is linear in the retard direction

**Additional context**
Tune and log at:
https://rusefi.com/online/view.php?log=1379

**Comment by rusefillc** [comment]
![image](https://github.com/rusefi/rusefi/assets/48498823/a695808a-5200-44af-8296-c7a7c0d93fd5)

**Comment by rusefillc** [comment]
We see CAM sync errors

```
	CUSTOM_CAM_TOO_MANY_TEETH = 9004,
	CUSTOM_CAM_NOT_ENOUGH_TEETH = 9005,
```

let's have only one VVT input and output active and calibrate it to be vvt bank 1 intake even while in could be an exhaust, and grab a new log

**Comment by rusefillc** [comment]
Looks like you are waiting for https://github.com/rusefi/rusefi/issues/5333

**Comment by ElDominio** [comment]
Fix about #5333 worked, intake cams are working as expected; exhaust still crazy.

Log of ONLY bank 1 exhaust as bank 1 intake at 
https://rusefi.com/online/view.php?log=1380

**Comment by rusefillc** [comment]
vvt resync happens meanings false vvt sync

![image](https://github.com/rusefi/rusefi/assets/48498823/5b8ac0da-b94f-4768-84cf-8e4d0c9429e0)

**Comment by ElDominio** [comment]
[all waves coyote ch1 crank ch2 intake cam ch3 exh cam.zip](https://github.com/rusefi/rusefi/files/15173760/all.waves.coyote.ch1.crank.ch2.intake.cam.ch3.exh.cam.zip)

Channel 1 is 36-1 VR 9924
Channel 2 is Coyote Intake Cam
Channel 3 is VR2, going through discrete

**Comment by rusefillc** [comment]
@ElDominio note the differences in falls

![image](https://github.com/rusefi/rusefi/assets/48498823/c5126d3b-f0dd-4d27-a583-fccacd3106ca)

**Comment by ElDominio** [comment]
yes.......................................................................................?

**Comment by ElDominio** [comment]
Bumping this because i want to dyno the car again

**Comment by ElDominio** [comment]
This issue was caused because VR threshold was incorrecetly set up

![WhatsApp Image 2024-07-05 at 19 59 21_7649c2c2](https://github.com/rusefi/rusefi/assets/5685108/ef0a6a21-70ef-4ed1-a859-f94caad2bc45)

With these settings, exhaust VVT reads fine , tested up to -35
