### ISSUE TITLE
Launch control fuel addition does not work

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#6423]
**Describe the bug**
Fuel is not being added even though I requested 100% extra fuel on launch control

**Hardware**
 - Board: 4chan 
 - Engine info 13B Rotary

**To Reproduce**
1. Go to Advanced -> Launch Control
2. Enable it
3. add some fuel in "fuel added"
4. rev to launch control area
5. see no fuel is increased

**Expected behavior**
There is additional fuel added, base off current calculated fuel (take current fuel demand and add/remove whatever % is in "fuel added"

**Screenshots**
![image](https://github.com/rusefi/rusefi/assets/5685108/c5fb29b6-eb7b-4c34-94ed-1c58dc0b89dd)

log at https://rusefi.com/online/view.php?log=1382

**Additional context**
I think this is related to not having the "fuel cut" option set to true. This feels like the problem where if ignition cut was not set true, there would not be timing retard.

**Comment by zed65** [comment]
On my board with discovery firmware it works as expected (adds 100% fuel).

**Comment by ElDominio** [comment]
What are the settings for your launch control?

**Comment by zed65** [comment]
![LaunchSettings](https://github.com/rusefi/rusefi/assets/23425941/40f56567-ca9a-4241-9e0f-7a23e6ad04a1)
I tried both with and without fuel and ign cut, all worked.

**Comment by ElDominio** [comment]
tf, well I attached the log, and the pulse width basically changes tracking the VE table

**Comment by zed65** [comment]
I tried to load your tune on my board, launch worked.
Due to my stimulator I have to set my launch rpm to 2500
[launchTest.zip](https://github.com/rusefi/rusefi/files/15138073/launchTest.zip)

**Comment by ElDominio** [comment]
As far as I understand this was my mistake?
