### ISSUE TITLE
CLT/IAT boost duty/target compensation

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#6424]
**Is your feature request related to a problem? Please describe.**
Boost duty/target should have a 5x1 table to compensate for changes in temperatures (colder weather means air is more dense = same amount of DC get you more air; and vs CLT some people like to not have full power until operating temps are reached)

**Would we need new configuration fields?**
Two new tables to alter the duty (if in open loop boost mode) or target (if closed loop boost mode) to allow for higher/lower targets depending on temperature

**Describe the solution you'd like**
The said table to be added

**Describe alternatives you've considered**
I am currently using a blend table for this

**Comment by kifir23917** [comment]
@ElDominio, am I correct that we need to add couple of tables similar to the following, but these two tables should contain 5 values instead of 16?
![Warmup fuel manual Multiplier](https://github.com/user-attachments/assets/045e7bdf-c88e-4ffd-8182-381c5216c23d)
![Intake Iir temperature fuel Multiplier](https://github.com/user-attachments/assets/b0e4b55c-7637-4506-8b40-e6f140b7c828)

What should be names of these new tables that will be displaed on the top like `Intake air temperature fuel Multiplier` and `Warmup fuel manual Multiplier` on the tables above?

What should be default values in `Air Temp` and `Coolant` columns?

As I understand, in the one new table `Multiplier` column should be renamed to `Duty`, in the another new table `Multiplier` column should be renamed to `Target`, but I'm not sure which of these columns should be alongside with `Air Temp` and which of these columns should be alongside with `Coolant`. Could you please clarify it?

**Comment by ElDominio** [comment]
Intake Air Temperature Boost Multiplier
Coolant Temperature Boost Multiplier

Second columns of should BOTH still say Multiplier, since they are multipliers to the base duty and changing the name to duty will only result in confusion.
Both of these should be defaulted to 1.00, and they should work only with Boost Duty, and not touch target.

Default values should be
20 - 1.00
40 - 1.00
60 - 1.00
80 - 1.00
100 - 1.00

**Comment by rusefillc** [comment]
![image](https://github.com/user-attachments/assets/c9caf3d8-055a-4c97-a93f-7bdb21cc7e32)

**Comment by rusefillc** [comment]
@ElDominio in "open plus closed" which should we multiply? both open duty and closed target by same multiplier?

**Comment by kifir23917** [comment]
Current implementation uses the following formulas:
### closed loop target
(`BOOST_CONTROL_TARGET_COMPONENT` + `BLENDS_COMPONENT`) * `LUA_BOOST_TARGET_MULT` + `LUA_BOOST_TARGET_ADD`
where:
- `BOOST_CONTROL_TARGET_COMPONENT` is calculated from `Boost control target (kPa)` table
![image](https://github.com/user-attachments/assets/46f56b8f-caa1-46d1-bdf8-c33dac91494a)
- `BLENDS_COMPONENT` is calculated from blend tables
- `LUA_BOOST_TARGET_MULT` is configured with `setBoostTargetMult` Lua hook
- `LUA_BOOST_TARGET_ADD` is configured with `setBoostTargetAdd` Lua hook
### open loop duty
`LUA_BOOST_DUTY_ADD` + `BOOST_CONTROL_DUTY_CYCLE_COMPONENT` + `BLENDS_COMPONENT` + `GEAR_ADDER_COMPONENT`
where:
- `LUA_BOOST_DUTY_ADD`  is configured with `setBoostDutyAdd` Lua hook
- `BOOST_CONTROL_DUTY_CYCLE_COMPONENT` is calculated from `Boost control duty cycle (open loop)` table
![image](https://github.com/user-attachments/assets/64950a85-3d17-443f-b790-c71d1316b68f)
- `BLENDS_COMPONENT` is calculated from blend tables
- `GEAR_ADDER_COMPONENT` is calculated from `Boost control open loop gear adder`
![image](https://github.com/user-attachments/assets/4c65eba4-b2e5-4cd4-8bb5-cabad4d38740)



In the scope of this issue we're adding two new components:
- `CLT_BOOST_MULTIPLIER` is calculated from `Coolant Temperature Boost Multiplier` table
![image](https://github.com/user-attachments/assets/32e470cc-a7c9-45be-abd0-8bd06e7f72d8)
- `IAT_BOOST_MULTIPLIER` is calculated from `Intake Air Temperature Boost Multiplier` table
![image](https://github.com/user-attachments/assets/f3e79845-b8be-4f47-a99f-45840f752eb0)


Am I correct that new formulas should be the following?
### closed loop target
(`BOOST_CONTROL_TARGET_COMPONENT` * `CLT_BOOST_MULTIPLIER` * `IAT_BOOST_MULTIPLIER` + `BLENDS_COMPONENT`) * `LUA_BOOST_TARGET_MULT` + `LUA_BOOST_TARGET_ADD`
### open loop duty
`LUA_BOOST_DUTY_ADD` + (`BOOST_CONTROL_DUTY_CYCLE_COMPONENT` * `CLT_BOOST_MULTIPLIER` * `IAT_BOOST_MULTIPLIER`) + `BLENDS_COMPONENT` + `GEAR_ADDER_COMPONENT`

**Comment by ElDominio** [comment]
While the formulas look correct; Closed Loop TARGET should NOT be changed with the same tables as DUTY. They have to change independently (duty/target) in relation with CLT/IAT. This means we need one set of tables, another for duty. And anything that changes TARGET needs to be additive 

So
Duty = changes with multiplicative ratio, as shown in `LUA_BOOST_DUTY_ADD + (BOOST_CONTROL_DUTY_CYCLE_COMPONENT * CLT_BOOST_MULTIPLIER * IAT_BOOST_MULTIPLIER) + BLENDS_COMPONENT + GEAR_ADDER_COMPONENT`

Target = changes with additive, meaning `(BOOST_CONTROL_TARGET_COMPONENT  + BLENDS_COMPONENT) * LUA_BOOST_TARGET_MULT + LUA_BOOST_TARGET_ADD + CLT_BOOST_ADD + IAT_BOOST_ADD`

**Comment by kifir23917** [comment]
So actually we need four new tables. And by the moment we have titles only for two tables:
- `Intake Air Temperature Boost Multiplier`
- `Coolant Temperature Boost Multiplier`
What should be labels for another two tables? Something like the following?
- `Intake Air Temperature Boost Adder`
- `Coolant Temperature Boost Adder`

Do we need to clarify in the titles which tables are for open loop and which tables are for closed loop?

**Comment by rusefillc** [comment]
@ElDominio how confident are you that at least one human who is not you would use these four new curves? I wonder if our energy would be better spend working on custom curve usability and Lua integration?

**Comment by ElDominio** [comment]
The thing is, if we are tackling OEM-replacement ECUs, this would be pretty useful. I think having this allows a higher quality tier of tuner to produce reliable tunes

**Comment by kifir23917** [comment]
@ElDominio, I've supported the following curves in the scope of this issue:
### Open Loop
![image](https://github.com/user-attachments/assets/0a4de1a0-4720-4920-8458-41bb570e6348)
![image](https://github.com/user-attachments/assets/1b3129fa-b151-42e0-a76b-e310bbc1637d)
### Closed Loop
![image](https://github.com/user-attachments/assets/a23ca9ee-b47e-402f-9b50-81c9efc39e08)
![image](https://github.com/user-attachments/assets/31a1ca97-f6bf-4507-8927-03708a5fa492)

Is the naming of curves above good for you?

**Comment by ElDominio** [comment]
I think the open loop ones should say "Boost Duty Multiplier" and the closed loop ones should say "Boost Target Adder" for clarity's sake

**Comment by kifir23917** [comment]
@ElDominio, could you please check that all is OK with this functionality?

**Comment by ElDominio** [comment]
Can you make the target adders only enabled if mode Open + Closed Loop is active?

enabling closed loop causes this
![image](https://github.com/user-attachments/assets/b4d14145-a6f1-4b09-a61d-9224aac5882c)


multipliers do work, but closed loop is now broken; this only shows up when KEYED ON! if you try this with key off it will not throw the error

[testadders.zip](https://github.com/user-attachments/files/16646338/testadders.zip)

**Comment by kifir23917** [comment]
@ElDominio , I'm working on fixing `Access to uninitialized bins: clt (adder)` error. In case if i fix it, are you still sure that we really need to make the target adders enabled only if mode Open + Closed Loop is active?

**Comment by ElDominio** [comment]
> @ElDominio , I'm working on fixing `Access to uninitialized bins: clt (adder)` error. In case if i fix it, are you still sure that we really need to make the target adders enabled only if mode Open + Closed Loop is active?

Yes, since in Open Loop there are no targets to be modified

**Comment by kifir23917** [comment]
@ElDominio:
1. I hope that `Access to uninitialized bins: clt (adder)` error is fixed
2. Now target adders are only enabled only if mode `Open + Closed` Loop is active

Could you please test latest build?

**Comment by ElDominio** [comment]
Confirmed all working fine!

Please rename the multipliers so they say "boost duty duty multiplier" and and "boost target adder"

**Comment by kifir23917** [comment]
> Please rename the multipliers so they say "boost duty duty multiplier" and and "boost target adder"
1. I believe that you mean `boost duty multiplier`, not `boost duty duty multiplier`
2. Is my understanding correct that you want to rename column, marked on the screenshot below?
![image](https://github.com/user-attachments/assets/1a744b39-4097-42d2-a2a2-14c147fa0c03)

**Comment by ElDominio** [comment]
Only the menu dropdown, not the column

**Comment by kifir23917** [comment]
> Please rename the multipliers so they say "boost duty duty multiplier" and and "boost target adder"
> Only the menu dropdown, not the column

@ElDominio, I've renamed menu items:


![Image](https://github.com/user-attachments/assets/d7ef6ea8-335b-4aba-858e-91ad2a7065fc)
