### ISSUE TITLE
Oscilations in DWELL length after 40+ hours of uptime

### ISSUE THREAD

**Issue by ggurov** [rusefi/rusefi#6451]
EDIT:
new log field triggerElapsedUs
new log field sadDwellRatioCounter

EDIT2: current theory this defect is about int64+float loss of precision. I was only able to find one occurrence in overdwell protection, and a few places already have provisions of fix. 
* master now has one fix
* special branch master + 200K uptime https://github.com/rusefi/rusefi/pull/6496
* special branch before fix + 200K uptime https://github.com/rusefi/rusefi/pull/6495

EDIT3:
the defect was related to 
```
inline /*64bit*/ efitick_t sumTickAndFloat(/*64bit*/efitick_t ticks, /*32it*/float extra) {
  // we have a peculiar case of type compiler uses to evaluate expression vs precision here, for us it's the integer precision which is more important
```

in the code we were correctly handing four or five scenarios without articulating the commonality, and one occurrence of the same pattern - overdwell protection - was broken. So the defect was about bad overdwell scheduling killing ignition scheduling.

**Describe the bug**
It appears after some running, on the bench, dwell shows oscillations in duration consistent with a pattern:

commanded dwell: 3.5

3.5ms -> 3.2ms -> 3.0ms -> 2.7ms -> 2.4ms -> 2.1ms  -> 3.5ms

repeating on all channels. 

**Hardware**
 - Board: 407disco 
 - Engine info: 2jz-gte 6 cyl waste spark batch injection

**To Reproduce**
1. Tun board for 40+ hours on stim
2. Observe dwell duration on logic analyzer
3. `andrey_rusefi: WHAT THE HELL DWELL IS GOING NUTS`

**Expected behavior**
Dwell to not go nuts and stay consistent with commanded dwell.

**Screenshots**

![image](https://github.com/rusefi/rusefi/assets/2112173/dac2b4a1-7392-4b7e-8055-bfa1e42ee062)

![image](https://github.com/rusefi/rusefi/assets/2112173/7a4199f5-c058-4ee8-8d67-47bbeefb203e)

ch 3,4,5,6,7,8 are ignition channels, waste spark so 1+6, 2+5, 3+4 are paired 

saleae capture: 

[dwell_oscilations.zip](https://github.com/rusefi/rusefi/files/15189382/dwell_oscilations.zip)

ts log:

[2024-05-02_09.49.51.zip](https://github.com/rusefi/rusefi/files/15189374/2024-05-02_09.49.51.zip)

overdwell counter seems to be ticking up at the time

![image](https://github.com/rusefi/rusefi/assets/2112173/853583f8-3270-44ec-a7d2-6efff9d0c7b3)

https://youtu.be/rxIXa3DA6bA video of this happening

issue goes away after ECU power reset.

overdwell counter does not steadily increase after reset.

**Comment by rusefillc** [comment]
I guess https://github.com/rusefi/rusefi/issues/6450 is somewhat of a preparation to start looking into this issue

**Comment by rusefillc** [comment]
@kifir23917 https://www.youtube.com/watch?v=rxIXa3DA6bA

**Comment by rusefillc** [comment]
saleae "saleae logic 1" https://support.saleae.com/logic-software/legacy-software/older-software-releases#logic-1-x-download-links

@kifir23917 funny thing that only spark is broken that must be telling us something
* looks like signal generation is not broken
* interesting thing if bad dwell times are not broken?
* would a unit test with very quick time movement help us here?

**Comment by rusefillc** [comment]
@ggurov can you attempt reproducing with "one tooth" trigger instead of real 36-smth?

**Comment by ggurov** [comment]
![image](https://github.com/rusefi/rusefi/assets/2112173/97f796c0-e435-4add-bc4e-169fa19bf683)


running

**Comment by ggurov** [comment]
reproduced, similar thing: 

![image](https://github.com/rusefi/rusefi/assets/2112173/12687eeb-bcaa-4aea-b996-417a1028e700)


![image](https://github.com/rusefi/rusefi/assets/2112173/128f5946-2a8b-49dc-94d8-692556735aac)




https://www.youtube.com/watch?v=kIxebA81Nag


[reproduced_oscillations_3_0_trigger.zip](https://github.com/rusefi/rusefi/files/15213943/reproduced_oscillations_3_0_trigger.zip)


tune log and .sal file in the zip above. 

"time" variable in TS shows about 50 hours.

**Comment by rusefillc** [comment]
@ggurov @kifir23917 
* was it external signal generator? now that we use simple trigger shape can we attempt reproducing with self-stimulator?
* wonder if we can reproduce with self-stimulation on rusEFI simulator

**Comment by ggurov** [comment]
external generator off, internal one running

![image](https://github.com/rusefi/rusefi/assets/2112173/ff4983f7-dfd4-4558-8d67-e21f836e21da)

![image](https://github.com/rusefi/rusefi/assets/2112173/ca09728a-4bc4-4907-8943-a1858ad1c7c8)



running, output signals match what it was with external generator

**Comment by rusefillc** [comment]
![image](https://github.com/rusefi/rusefi/assets/48498823/413096a3-848e-40a5-ab5d-475c482d22e6)

**Comment by ggurov** [comment]
if that's my log, that's TS chugging at the start, check out SECL variable, it will do the same thing. maybe time does it too. it's an artifact of starting to log.

**Comment by rusefillc** [comment]
@ggurov please run with "debug mode" set to "dwell metric" (see bottom right corner of weird dialog)

(that's legacy extra logging)

![image](https://github.com/rusefi/rusefi/assets/48498823/081c832d-17e8-4bfc-b404-013861757e80)

**Comment by ggurov** [comment]
hmm, no secL variable ? there's gotta be something that ticks up from ecu monotonically...

**Comment by rusefillc** [comment]
@ggurov see uneven duration of second in bottom yellow "uptime" line, looks like a gap in the log?

![image](https://github.com/rusefi/rusefi/assets/48498823/8c2c36b4-3393-46af-b333-7c244a6e868b)

**Comment by ggurov** [comment]
reproduced with internal stim, will post artifacts in the morning

**Comment by ggurov** [comment]
INTERESTING THING TO NOTE:

once in this state, settings internal stim to 893 rpm = NO oscillations
894 = oscillations.

overdwell does not tick up @ 893, and starts going up at 894 rpm

this should be in the logs.



![image](https://github.com/rusefi/rusefi/assets/2112173/ff6e3e91-2341-4cc0-b438-8382908db24f)


https://www.youtube.com/watch?v=sJhYllzm8cI


[dwell_oscillations_internal_stim.zip](https://github.com/rusefi/rusefi/files/15247749/dwell_oscillations_internal_stim.zip)

**Comment by ggurov** [comment]
[2024-05-08_06.58.38-external-stim.zip](https://github.com/rusefi/rusefi/files/15247881/2024-05-08_06.58.38-external-stim.zip)

enabling external stim in that stage still produces the same results.

one thing to note, i've switched back to 36-2 for external stim, and consequentally internal stim.  and wave pattern seems consistent with the trigger pattern.

**Comment by rusefillc** [comment]
![image](https://github.com/rusefi/rusefi/assets/48498823/56694bd1-80ce-4e30-8ef0-d46807189607)
[reference-issue-6451.zip](https://github.com/rusefi/rusefi/files/15249468/reference-issue-6451.zip)

**Comment by ggurov** [comment]
https://rusefi.com/online/view.php?msq=1648 that was the tune with internal stim. it's also curtune.msq in the zip posted above with 893 vs 894 rpm separation

**Comment by rusefillc** [comment]
"good" orange from top screenshot

![image](https://github.com/rusefi/rusefi/assets/48498823/1879b739-af5f-4e9a-a2cd-aa42fed3d223)
pink 100 to 230, duration 130
orange from 330 to 480, duration 150

offset end of pink to end of orange 250

**Comment by rusefillc** [comment]
"bad" orange

![image](https://github.com/rusefi/rusefi/assets/48498823/14709630-1664-4ae2-a000-655669ad7f9d)

pink 100 to 250 duration 150
orange 340 to 450 duration 110

offset start of pink to start of orange 240
offset end of pink to end of orange 200

**Comment by ggurov** [comment]
reproduced with engint_type 93 on a bare discover board:

![image](https://github.com/rusefi/rusefi/assets/2112173/54a8d566-d6cd-4a3b-a341-8318e1d00b05)


[dwell_oscillations_discovery_engine_93.zip](https://github.com/rusefi/rusefi/files/15273869/dwell_oscillations_discovery_engine_93.zip)



logic analyzer log, tune, and log in the zip

ch2 and ch5 seem to be affected.

runtime of about 36 hours so..


issue happens above 3700 rpm

switching to internal trigger shows the same effect once ECU enters this state.

**Comment by ggurov** [comment]
[Session 1-increasing-partial-dwell.zip](https://github.com/rusefi/rusefi/files/15273961/Session.1-increasing-partial-dwell.zip)

above a certain RPM, (5500 or so)

there is an increasing dwell length of one of the pulses

![image](https://github.com/rusefi/rusefi/assets/2112173/bebec590-e1c7-4e6b-a46e-d45686ae71df)

**Comment by rusefillc** [comment]
sadDwellRatioCounter is alive. we've made progress!

![image](https://github.com/rusefi/rusefi/assets/48498823/1cad0c9a-aa0f-4344-a0f7-818e1017e387)

**Comment by rusefillc** [comment]
@ggurov why was RPM zero in the beginning?

what's going on with MAP sensor? I wonder if causation or correlation with sadDwellRatioCounter 

![image](https://github.com/rusefi/rusefi/assets/48498823/ca649c2d-9f34-4f52-a16a-ccd9397839b6)

**Comment by rusefillc** [comment]
Looks like issue depends on RPM

36-2 older tests, 893 rpm = NO oscillations, 894 = oscillations. 

TT_NARROW_SINGLE_TOOTH newer tests, threshold is around 3700

**Comment by rusefillc** [comment]
let's keep using engine 93 narrow tooth

let's try 12000RPM? 15K rpm?

I am hesitant but focus should probably be on internal stimulator


Looks like issue depends on RPM
36-2 older tests, 893 rpm = NO oscillations, 894 = oscillations. 
TT_NARROW_SINGLE_TOOTH newer tests, threshold is around 3700

**Comment by rusefillc** [comment]
WOW maybe smoking gun/maybe useful info?! why do we have overDwellCounter?!

let's try without

![image](https://github.com/rusefi/rusefi/assets/48498823/8651c5d4-f324-4ccc-88fc-0aee0e33958c)

**Comment by mck1117** [comment]
this is almost certainly a floating point loss of precision bug

**Comment by rusefillc** [comment]
> this is almost certainly a floating point loss of precision bug

I know but what are we accumulating?

**Comment by rusefillc** [comment]
@ggurov new smoke: 3700 threshold is when coil duty cycle crosses 25%

![javaw_vi0LJPTDbH](https://github.com/rusefi/rusefi/assets/48498823/b16e1b82-ffc9-4568-8ecb-f16dfdfddebb)

**Comment by rusefillc** [comment]
also CUSTOM_OUT_OF_ORDER_COIL = 9012

**Comment by rusefillc** [comment]
I've reproduced the issue

![image](https://github.com/rusefi/rusefi/assets/48498823/681046d7-77e4-41fd-b9ab-059bbf08eddc)

![image](https://github.com/rusefi/rusefi/assets/48498823/4d1a5e41-3078-4e86-8095-da90c118afcc)

**Comment by ggurov** [comment]
this is 767 12 cylinder @ 29000 rpm for approximately 19 hours

open up salea, look for this pattern:

ch 2 and ch3 are 40 seconds on, 40 seconds off, is at 14650 RPM precisely that should match up to the MLG

even going 10 rpm up from that causes a much more cyclical pattern

ch1 is cyl1, ch2 cyl2, ch3  cyl3, ch4 cyl4

1-2-3-4-5-6-7-8-9-10-11-12 firing pattern 12cyl



![image](https://github.com/rusefi/rusefi/assets/2112173/edbeece3-2d0d-44a6-a230-44a1d8ce7b24)





[767_26krpm_itnernal_single_tooth-14650-big-gaps.zip](https://github.com/rusefi/rusefi/files/15283266/767_26krpm_itnernal_single_tooth-14650-big-gaps.zip)

**Comment by ggurov** [comment]
same as above, but added a slower log rate shorter log sal mlg


![image](https://github.com/rusefi/rusefi/assets/2112173/549ebd85-9531-4d4e-9e2f-a88d2bb57e9d)
how linear uptime is depends on something secondary from RPM input.

as if it has to finish overflowing something, and then pace changes.



[767_26krpm_itnernal_single_tooth-aditional-slower-log-rate.zip](https://github.com/rusefi/rusefi/files/15283298/767_26krpm_itnernal_single_tooth-aditional-slower-log-rate.zip)

**Comment by rusefillc** [comment]
@ggurov see EDIT2 in ticket description

**Comment by mck1117** [comment]
https://github.com/FOME-Tech/fome-fw/pull/424 may be of interest

**Comment by rusefillc** [comment]
> [FOME-Tech/fome-fw#424](https://github.com/FOME-Tech/fome-fw/pull/424) may be of interest

appreciate it!

**Comment by rusefillc** [comment]
@ggurov there is a chance that this issue is now resolved. Are you available to test?
