### ISSUE TITLE
Looks like .hex files are not generated with gcc 8 2018 on windows

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#646]
![image](https://user-images.githubusercontent.com/7377949/50716728-f24be900-1050-11e9-894d-09cbb13a219e.png)

**Comment by rusefi** [comment]
full make output 
![image](https://user-images.githubusercontent.com/7377949/50717793-1d860680-1058-11e9-9ae0-6c4aa06f7857.png)

**Comment by rusefi** [comment]
https://bugs.launchpad.net/gcc-arm-embedded/+bug/1810274

**Comment by rusefi** [comment]
My version is gcc version 8.2.1 20181213 (release) [gcc-8-branch revision 267074] (GNU Tools for Arm Embedded Processors 8-2018-q4-major) 

@andreika-git  what is your version?

![image](https://user-images.githubusercontent.com/7377949/50718352-c898bf00-105c-11e9-9812-b8ef1dffca16.png)

**Comment by andreika-git** [comment]
Mine is 8.2.1-2018.11 (gcc-arm-8.2-2018.11-i686-mingw32-arm-eabi.tar.xz)

**Comment by andreika-git** [comment]
gcc -v output:
gcc version 8.2.1 20180802 (GNU Toolchain for the A-profile Architecture 8.2-2018.11 (arm-rel-8.26))

**Comment by rusefi** [comment]
We have fresh build at https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads

Version 8-2019-q3-update
Released: July 10, 2019

**Comment by rusefi** [comment]
gcc 8.3 from 2019 build is fine
