### ISSUE TITLE
Suzuki K6A (NON VVTI Trigger) 

### ISSUE THREAD

**Issue by EA11R** [rusefi/rusefi#6490]
I would like to have this trigger wheel added on RUSEFI UAEFI firmware

![2024-05-09_23_22_48_689rpm_0_maf_0 0](https://github.com/rusefi/rusefi/assets/82368250/7c731873-e874-4df5-a9c6-84e1688eb93e)
![IMG_4091](https://github.com/rusefi/rusefi/assets/82368250/2be696cd-cb27-4491-a2b0-31710ceb91cb)

Total tooth = 10  consisting of 3 pairs of tooth 3, 1 missing - 3 , 1 missing , 2 , 2 
it does read RPM as 12 - 2 

orientation of trigger in image is the way it mounts at cly #1 TDC 

areas free off tooth angle are around 70 deg for the largest gap

image of engine sniffer was taken of a hand rotated distributor 
I think I'm able to crank the engine with it tomorrow if it fits the F6A

**Comment by rusefillc** [comment]
![image](https://github.com/rusefi/rusefi/assets/48498823/7de3998b-1049-48d9-a82d-0ff7555aa61e)

**Comment by rusefillc** [comment]
![suzuki](https://github.com/rusefi/rusefi/assets/48498823/2ae02ef2-1021-4564-8351-ff67a023e8c1)

**Comment by rusefillc** [comment]
@EA11R I've made some progress no idea if it's right

https://github.com/rusefi/rusefi/wiki/All-Supported-Triggers#suzuki-k6a

**Comment by EA11R** [comment]
Yes, that's correct thank you very much 

the trigger is working correctly
