### ISSUE TITLE
use ChibiOS as is

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#65]
We should minimize the changes to ChibiOS source code, ideally we should eliminate these changes altogether.

See also #463

**Comment by rusefi** [comment]
@fpoussin that's the dream ticket to push all rusEfi chibi ideas into chibi master

**Comment by rusefi** [comment]
chprintf is now used as is

so it's getRemainingStack mostly?

See also https://github.com/rusefi/ChibiOS/tree/stable_rusefi

**Comment by fpoussin** [comment]
Maybe we can use hooks.

**Comment by rusefi** [comment]
With ChibiOS 17 we have very minimal changes.
