### ISSUE TITLE
console to show binary file date timestamp

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#6515]
left to "how to update FW" maybe?

**Comment by rusefillc** [comment]
At the moment we have a confusion in light of console having it's own version hard-coded manually

![image](https://github.com/rusefi/rusefi/assets/48498823/4e37733c-1aee-43be-9cb5-d847e3ee73e8)

**Comment by rusefillc** [comment]
Separate ask to automatically check that a newer snapshot exists

**Comment by highspeed427** [comment]
there will need to be multiple ways to handle this. alex and i will work on building the plan for all the ways we need to handle updates and entitlements as these processes will be partially married
