### ISSUE TITLE
Traction control timing adjustment not working

### ISSUE THREAD

**Issue by zed65** [rusefi/rusefi#6516]
Ignition timing drop do not work as intended.
See log at:
https://rusefi.com/online/view.php?log=1392

MLV and TS does not match (don't know if that's a problem but strange)
![tracMLV](https://github.com/rusefi/rusefi/assets/23425941/3acc006e-723d-4ab2-9e58-733ee7d4bd69)
![tracTS](https://github.com/rusefi/rusefi/assets/23425941/a44ac6e3-b0c1-4cad-be8b-ebc1244f2a51)

**Comment by rusefillc** [comment]
@ggurov do you say you got it to work and the confusion is about which direction the value is applied?

**Comment by ggurov** [comment]
no, i need to add two pwm values to drive the wheel sensors. i'll get around to it and test this

**Comment by ggurov** [comment]
https://github.com/rusefi/rusefi/issues/6520 maybe related

**Comment by rusefillc** [comment]
@zed65 what's the status?
