### ISSUE TITLE
unit_tests should compile and run both on linux and cygwin windows

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#652]
at the moment build server runs on cygwin windows and unit_tests compile and run there

@mck1117 reports that unit tests do not compile on unix, https://github.com/rusefi/rusefi/pull/651 was suggested

unfortunately while https://github.com/rusefi/rusefi/pull/651 fixes linux, it breaks cygwin :(

**Comment by rusefi** [comment]
@mck1117 @fpoussin here is how windows fails with suggested change. Revering #651 for now

![image](https://user-images.githubusercontent.com/7377949/50744565-5954d380-11f2-11e9-927d-6288770abad3.png)

**Comment by fpoussin** [comment]
![screenshot_20190107_112015](https://user-images.githubusercontent.com/1305966/50762810-5ac3e180-126e-11e9-8cbc-e107a56edcbf.png)
Small tip for next time you need to revert a PR, just use the button.

**Comment by fpoussin** [comment]
```
Compiling microsecond_timer.cpp
In file included from ../firmware/controllers/system/ThreadController.h:12:0,
                 from ../firmware/controllers/system/PeriodicController.h:10,
                 from ../firmware/hw_layer/microsecond_timer.cpp:18:
../firmware/ChibiOS4/os/rt/include/ch.h:70:10: fatal error: chtypes.h: No such file or directory
 #include "chtypes.h"
          ^~~~~~~~~~~
compilation terminated.
rules.mk:100: recipe for target 'build/obj/microsecond_timer.o' failed
make: *** [build/obj/microsecond_timer.o] Error 1
```
With gcc 7.3.0

**Comment by rusefi** [comment]
We have two defects on top of each other. At the moment things do not compile abywhere due to recent code change, but usually they do not compile on linux only

**Comment by fpoussin** [comment]
Ok, let me know when it's fixed.

**Comment by rusefi** [comment]
Things now compile on windows. How is linux?

**Comment by fpoussin** [comment]
Better, now there's only the pthread linker issue.

**Comment by fpoussin** [comment]
Which version of mingw are you using?

**Comment by rusefi** [comment]
Fresh cygwin gives me 7.3 or 7.4, for instance on this device 
![image](https://user-images.githubusercontent.com/7377949/50784392-813c4980-127b-11e9-97a6-51b9c316880e.png)
