### ISSUE TITLE
Alternator voltage target table

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#6523]
**Is your feature request related to a problem? 
I'm always frustrated when I want to lower voltage under different conditions but cannot because voltage target is one value

**Would we need new configuration fields?**
Chnge single voltage target value to a 4x4 table

**Describe the solution you'd like**
Chnge single voltage target value to a 4x4 table

**Describe alternatives you've considered**
Stay with a single target voltage which is. Abit sad

**Additional context**
Under high engine loads, it's good to lower target voltage to free up some torque, and in cruising conditions we can target slightly higher voltages for battery life

**Comment by rusefillc** [comment]
@ElDominio what are the axises? I can guess but you better spell out

![image](https://github.com/rusefi/rusefi/assets/48498823/e28b07a7-891c-4958-8433-24285fd6e309)

**Comment by ElDominio** [comment]
Axes are:

X i s RPM
Y is Load

**Comment by ElDominio** [comment]
X values are RPM, Y values are Load

**Comment by ElDominio** [comment]
Remove the written target voltage, and only use table

![image](https://github.com/user-attachments/assets/fb91a2f2-c6aa-4871-ada0-401edb3ee981)
