### ISSUE TITLE
luaSoftSparkSkip/luaHardSparkSkip probably bug

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#6528]
We may have a defect: In C++ binary "+" operator has higher priority higher then ternary "?:"
		 * operator. It means that below we check if (luaSoftSparkSkip + engineConfiguration->useHardSkipInTraction)
		 * expression (sum of float and bool values) is zero or not. It's pretty weird :(
		 
```
		engine->softSparkLimiter.setTargetSkipRatio(luaSoftSparkSkip + engineConfiguration->useHardSkipInTraction ? 0 : tractionControlSparkSkip);
		engine->hardSparkLimiter.setTargetSkipRatio(luaHardSparkSkip + engineConfiguration->useHardSkipInTraction ? tractionControlSparkSkip : 0);
```

**Comment by rusefillc** [comment]
@kifir23917 I am surprised that compiler has not thrown an error? are there any relevant flags?

**Comment by rusefillc** [comment]
@ggurov could this be relevant for current TC attempts?

**Comment by kifir23917** [comment]
> @kifir23917 I am surprised that compiler has not thrown an error? are there any relevant flags?

IMHO it's impossible to forbid implicit conversion from float to bool because people loves writing code like:
```
if (!floatValue) { /*...*/ }
if (floatValue) { /*...*/ }
```
