### ISSUE TITLE
unit tests code coverage (now need to find a Windows solution)

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#653]
maybe gcov?

1) first step building with modified Makefile => .gcno "gcov notes" files are now present in unit_tests\build\obj folder
2) executing binary with magic Makefile changes is supposed to generate .gcda files but I do not see this happening? 

Aug 26, 2019 status:
we have continues unit test coverage posted on https://rusefi.com/docs/unit_tests_coverage/
Nasty implementation since Windows 10 build server runs Virtual Box with separate jenkins just for gcov

TODO: would be nice to find a windows solution for gcov so that build server is window-only

**Comment by rusefi** [comment]
https://stackoverflow.com/questions/57643813/cannot-get-gcov-to-produce-any-coverage-data

**Comment by rusefi** [comment]
Pile of BS :(
With a HelloWorld.cpp application I've realized that x86_64-w64-mingw32-g++ and i686-w64-mingw32-g++.exe generated main.exe does not produce main.gcda

while plain g++ does produce main.gcda!

but plain g++ does not compile rusEfi because
```googletest/googletest/include/gtest/internal/gtest-port.h:2496:40: error: 'fileno' was not declared in this scope```

https://stackoverflow.com/questions/18784112/googletest-1-6-with-cygwin-1-7-compile-error-fileno-was-not-declared-in-this
helps to compile but now I am having linker issues
```
Linking build/rusefi_test
/usr/lib/gcc/x86_64-pc-cygwin/7.4.0/../../../../x86_64-pc-cygwin/bin/ld: symbol `__stack_chk_guard' missing from main hash table
/usr/lib/gcc/x86_64-pc-cygwin/7.4.0/../../../../x86_64-pc-cygwin/bin/ld: symbol `environ' missing from main hash table
```

**Comment by rusefi** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=854368 but they say closed?

**Comment by rusefi** [comment]
```
# mingw-w64 is a project which forked from mingw in 2007.
# It looks like cygwin build of mingwg-w64 has issues with gcov runtime :(
# In order to have coverage generated please download from https://mingw-w64.org/doku.php/download/mingw-builds
# Install using mingw-w64-install.exe instead of similar thing packaged with cygwin
```

**Comment by chuckwagoncomputing** [comment]
Is there any point to keeping this issue around? Are we not set on keeping mingw as a requirement?
