### ISSUE TITLE
4G93 sync problems

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#6544]
**Describe the bug**
Some 4G93 (equivalent trigger to 4G63) has issues when cranking, but everything seems fine

**Hardware**
 - Board: custom hardware paralela
 - Engine info 4G93

**To Reproduce**
1. Set up car 
2. try to crank
3. sometimes will not sync

**Expected behavior**
Good sync behavior? VVT syncgapratio seems reasonable yet no sync is achieved _sometimes_; when we can decode VVT position it starts right up

**Additional context**
Engine running happily:
https://rusefi.com/online/view.php?log=1403

Engine not running:
https://rusefi.com/online/view.php?log=1404

**Comment by rusefillc** [comment]
@ElDominio grrrr 100 data rate

note 0.824 while range is 0.2 to 0.8

please try custom VVG gaps like 2 to 5 and 0.2 to 0.9?

![image](https://github.com/rusefi/rusefi/assets/48498823/eb2d8336-4a66-49ef-9e20-bd9ede3c291e)


![image](https://github.com/rusefi/rusefi/assets/48498823/e4f19368-1fd2-4995-b82f-34fbe313924d)

**Comment by ElDominio** [comment]
we have succesfully started 10 times; override with custom gaps fixed the issue

**Comment by ElDominio** [comment]
So we tried on another car and it started up every time, easily started like 30 times.

We changed cam sensors on problematic car, same results, starts up easily.

My wonder is, how is this showing up on log? Why can we see cam sensor reading something reasonable yet have it be bad?
