### ISSUE TITLE
Latest console updates to a vesion from 3 days ago while reporting correct date

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#6557]
**Describe the bug**
Seems to me that the latest console build is reporting everything is from today when in reality the bubild is outdated

**Hardware**
 - Board: 4chan revB
 - Engine info 3A92

**To Reproduce**
1. Download latest console
2. update with firmware update button
3. see on TunerStudio that firmware is from 20240524 when today is 20240527

**Expected behavior**
TunerStudio reports 20240527 and firmware has latest updates

**Screenshots**
TunerStudio Reports:
![image](https://github.com/rusefi/rusefi/assets/5685108/b3017191-5853-43d8-949e-6eb1d1915be6)

ECU File says:
![image](https://github.com/rusefi/rusefi/assets/5685108/8e312a6a-9afa-4bc4-abcd-c0c56d7fd3d0)

But included ini is from
![image](https://github.com/rusefi/rusefi/assets/5685108/cc89c05d-2c95-4fe7-9946-00315a0f7bca)

**Additional context**
I tried forcing to use 0527 ini but tunerstudio refuses???? 
![image](https://github.com/rusefi/rusefi/assets/5685108/6ca20c5d-11e6-4a03-8528-d3cf5b392c91)

I think this is more tunerstudio issue

**Comment by ElDominio** [comment]
![image](https://github.com/rusefi/rusefi/assets/5685108/e239bafa-b2b7-45c8-963d-4f9f76f49299)

alas it was not a tunerstudio issue

**Comment by rusefillc** [comment]
Here in NJ I have the same issue

![image](https://github.com/rusefi/rusefi/assets/48498823/939e6935-d561-423b-9b2d-d9bc4d025ecb)

![image](https://github.com/rusefi/rusefi/assets/48498823/835cadb6-e1b6-4d21-ade6-1c5eb7a54ee6)

![image](https://github.com/rusefi/rusefi/assets/48498823/f87f05ca-7617-4b0a-9dc7-cfad59dfd474)

**Comment by rusefillc** [comment]
but current compile date

![image](https://github.com/rusefi/rusefi/assets/48498823/f35d5c25-ae25-45b6-b4df-ea23a57ceb2e)

**Comment by rusefillc** [comment]
![image](https://github.com/rusefi/rusefi/assets/48498823/9ab427fe-9b38-48ce-bbab-8968c1eb3b16)

**Comment by rusefillc** [comment]
I broke only that date around https://github.com/rusefi/rusefi/commit/748432a6598bc69bcc8bb5cc777d74010f4da3bc
