### ISSUE TITLE
The Big Refactoring of 2019: configuration version should not be a global variable

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#656]
http://wiki.c2.com/?GlobalVariablesAreBad is worse than https://en.wikipedia.org/wiki/God_object

**Comment by mck1117** [comment]
GlobalVarsIsBad vs. GodObject is a false dichotomy.  It's really GlobalVarsIsBad vs. GodObject vs. $OtherPatternsHere. (see discussion on slack)
