### ISSUE TITLE
Launch control should have a variable ignition cut BEFORE the main Hard cut

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#6566]
**Is your feature request related to a problem? Please describe.**
Current cut method is very harsh since we just get to the cut RPM and disable ignition, then re-enable once we drop below the cutRPM

**Would we need new configuration fields?**
Initial Ignition Cut % - % of ignition events cut when we get into the launch window
Final Ignition Cut % Before launch - % of ignition events cut once we get past Smooth Retard End RPM

**Describe the solution you'd like**
I'd like to be able to start a NOT FULLY ignition cut before we hit the main RPM cut to make transition into launch cut less rough.
I think Smooth Retard End RPM will need to be renamed since it now affects ignition cut. Maybe "Launch Corrections End RPM"

**Describe alternatives you've considered**
Even smarter launch logic for another time

**Comment by kifir23917** [comment]
@ElDominio, currently we have two ways to affect ignition skip ratio:
1. via Lua script (`setSparkSkipRatio` and `setSparkHardSkipRatio`)
2. via `Traction Ignition Skip` dialog:
![Screenshot - Traction Ignition Skip](https://github.com/rusefi/rusefi/assets/159958110/8a51ccbb-16ab-475c-8b64-0fdfbc2830c9)

To calculate target skip ratio current implementation sums skip ratio values from this two sources: `LUA_SKIP_RATIO` + `TRACTION_SKIP_RATIO`.

Now we are adding the third way to affect ignition skip ratio: via [`Initial Ignition Cut %`] and [`Final Ignition Cut % Before launch (%)`] settings on `Launch Control` dialog:
![Screenshot - Launch Control](https://github.com/rusefi/rusefi/assets/159958110/9c20f7f8-0433-45ff-a863-b9b5755781e9)

How should we calculate the target skip ratio from the three sources listed above? Should it be a simple sum: `LUA_SKIP_RATIO` + `TRACTION_SKIP_RATIO` + `PRELAUNCH_SKIP_RATIO`?

**Comment by ElDominio** [comment]
Yes, and `PRELAUNCH_SKIP_RATIO` should never be non-zero unless we are EXPLICITLY in the launch state

**Comment by kifir23917** [comment]
Does `we are EXPLICITLY in the launch state` mean that [`Enable Launch Control`] setting is `true`?

**Comment by ElDominio** [comment]
1) It only affects/uses the HardSkipLimiter, nothing about SoftSkip
2) correct, if we are in launch mode (meaning enable Launch = true, and all prerequisite conditions are also true), skip ratio should be 1 when LaunchRPM < real RPM
3) it should be "Final Ignition Cut% Before Launch"

**Comment by kifir23917** [comment]
> 3. it should be "Final Ignition Cut% Before Launch"

Shouldn't we add to "Final Ignition Cut% Before Launch" sum `LUA_SKIP_RATIO + TRACTION_SKIP_RATIO` as we do while rpm is between [`Launch Control Window(RPM)`] and  [Launch Corrections End RPM]?

**Comment by ElDominio** [comment]
When I mentioned
"Final Ignition Cut% Before Launch"
I meant the one in your supplied screenshot, where it is a user-enterable value. 



The final math should be 
`LUA_SKIP_RATIO + TRACTION_SKIP_RATIO + PRELAUNCH_SKIP_RATIO`

**Comment by ElDominio** [comment]
Only one issue is left;

when we finally go over Launch RPM(rpm), all hard cut methods should be disabled once we drop below Launch RPM(rpm).

here are the settings:
![image](https://github.com/rusefi/rusefi/assets/5685108/ce05d679-446b-4462-befe-02c0c8598774)

here is the log
[launchtest97perfectnt.zip](https://github.com/user-attachments/files/15828007/launchtest97perfectnt.zip)

![image](https://github.com/rusefi/rusefi/assets/5685108/950a4c0b-6cfa-4fb3-9326-9fc584c198f4)

We want ignition to reactivate at 2999rpm, with a 60% ignition cut at 0 degrees of timing, since we are over ((LaunchRPM-LaunchRPM Corrections End RPM) but under Launch RPM
a.k.a.
3000>*2999*>2940

We only want full hard cut OVER LaunchRPM

**Comment by kifir23917** [comment]
> We want ignition to reactivate at 2999rpm, with a 60% ignition cut at 0 degrees of timing, since we are over ((LaunchRPM-LaunchRPM Corrections End RPM) but under Launch RPM
> a.k.a.
> 3000>2999>2940

> We only want full hard cut OVER LaunchRPM

Doesn't this contradict to #5610? There is the following written:

> If I set my launch RPM to 4500rpm, and my RPM Hysteresis to 200rpm and my ignition cut to ON, my engine should disable ignition at 4500rpm, and then come back to life at 4300RPM.

**Comment by ElDominio** [comment]
> 
> Doesn't this contradict to #5610? There is the following written:
> 
> > If I set my launch RPM to 4500rpm, and my RPM Hysteresis to 200rpm and my ignition cut to ON, my engine should disable ignition at 4500rpm, and then come back to life at 4300RPM.

Yes but i'm pretty sure that was outdated, I had stated that this was a step, but the final behavior is as i jsut described

So yes, it contradicts that

**Comment by kifir23917** [comment]
> Yes but i'm pretty sure that was outdated, I had stated that this was a step, but the final behavior is as i jsut described

I've [rolled back](https://github.com/rusefi/rusefi/pull/6616) hysteresis functionality.
