### ISSUE TITLE
The Big Refactoring of 2019: DECLARE_ENGINE_PARAMETER_SUFFIX consistency and simplification

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#657]
DECLARE_ENGINE_PARAMETER_SUFFIX could be improved a bit easily

**Comment by mck1117** [comment]
I think before we jump in and rework the use of the ENGINE_PARAMETER_SUFFIX, we need to look at whether it's the right way to pass configuration and state around the workings of the ECU (hint, it isn't).  Let's not waste our limited time on something we're going to change later anyway.

**Comment by rusefi** [comment]
See also https://github.com/mck1117/efi-playground/blob/master/configurations/tester/main.cpp

See also https://github.com/mck1117/rusefi/tree/mck1117/cj125-pr-3/firmware/hw_layer/sensors

**Comment by rusefi** [comment]
https://gustedt.wordpress.com/2010/06/08/detect-empty-macro-arguments/
