### ISSUE TITLE
data write failed between older project and newer firmware

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#6595]
Looks like we are so used that we have stopped reporting  :(

reproducible with just a discovery board

[780rusEfi-min.zip](https://github.com/user-attachments/files/15829308/780rusEfi-min.zip)

![image](https://github.com/rusefi/rusefi/assets/48498823/19adb000-4feb-48ef-a598-db1e3357725b)

* grab fresh firmware, reset to default calibration
* open attachd 78-rusEfi-min project
* connect
* hit left button "send current TS settings"
* expected: happy
* actual result: "data write failed"

![image](https://github.com/rusefi/rusefi/assets/48498823/af2ced6c-8773-474a-b872-85e4fa8abe3b)

**Comment by rusefillc** [comment]
is this similar to https://github.com/rusefi/rusefi/issues/6116 or different story?

**Comment by zed65** [comment]
I erased my board with STM32Cube and flashed with fresh build, when I connect with TS it wanted to update firmware.ini, did that and then it starts to load tune to board and I got the same error.
![loss](https://github.com/rusefi/rusefi/assets/23425941/c408fd0c-9481-43aa-b4f5-b59e00bf5ff2)

**Comment by rusefillc** [comment]
@zed65 please attach your project folder - both main controller and current tune files

**Comment by zed65** [comment]
This is probably not related but I also got this error even though I got a fuelpress sensor configured. After a reboot of the board the error is gone.
![loss1](https://github.com/rusefi/rusefi/assets/23425941/55c91fa8-79ea-465f-8db2-24d57104acfd)

**Comment by zed65** [comment]
Here is my folder (if that was the one you wanted).
[780rusEfi.zip](https://github.com/user-attachments/files/15751890/780rusEfi.zip)

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi/releases/tag/release_20240304

**Comment by zed65** [comment]
If I do as you did (with hardware), everything is fine. Don't know what's going on :(

**Comment by rusefillc** [comment]
> If I do as you did (with hardware), everything is fine. Don't know what's going on :(

i assume that it is some specific setting in the older project which triggers the problem

@zed65 @ggurov since we know that sometimes it does NOT happen - looks like the next step is to compare affected tune to new tune defaults and then keep reducing difference report until problem stops happening?

it could also be about the total amount of changes not any specific setting

**Comment by zed65** [comment]
Strange, it only happens if I use the above specific project. I grabbed my newer project from my car and did the same test and I got no error.
[780rusEfiNew.zip](https://github.com/user-attachments/files/15753940/780rusEfiNew.zip)

**Comment by rusefillc** [comment]
> This is probably not related but I also got this error even though I got a fuelpress sensor configured. After a reboot of the board the error is gone. 

@zed65 should be better now https://github.com/rusefi/rusefi/commit/f1e21697d665737ecf57eeda9c468ac95922376e

**Comment by dron0gus** [comment]
Issue is still exist in master.

**Comment by dron0gus** [comment]
May be a ChibiOS CDC ACM implementation bug https://forum.chibios.org/viewtopic.php?f=35&t=6395

**Comment by dron0gus** [comment]
https://github.com/rusefi/ChibiOS/pull/48

**Comment by rusefillc** [comment]
@dron0gus what's the current status with https://github.com/rusefi/rusefi/pull/7031 change? Do we have a proper fix? Do we have a partial fix which significantly reduces the frequency of the issue? Else?

**Comment by dron0gus** [comment]
@rusefillc fixes issue in current scenario on my side. Was not able to reproduce any more.
