### ISSUE TITLE
Trigger: Usability: prohibit some invalid configurations

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#660]
In case of 36/1 and 60/2 trigger "4 stroke with cam sensor" mode of operation makes no sense since we only 60/2 as primary trigger input.

1) TS project should not allow such a configuration
2) rusefi should show a warning and indicate trigger definition error which should result in not being able to start the engine

**Comment by mck1117** [comment]
I disagree - 60/2 with "4 stroke with cam sensor" is a valid config, some people put a missing tooth wheel in place of the distributor or on the end of the cam in retrofit installs.

**Comment by rusefillc** [comment]
Nothing to change here
