### ISSUE TITLE
Verify usage of `Fuel Added %` setting on `Launch Control` dialog

### ISSUE THREAD

**Issue by kifir23917** [rusefi/rusefi#6607]
Current code  adds fuel according to `Fuel Added %` setting when:
1. `Enable Launch Control` is `true`
2. `Launch condition` is satisfied, i.e. **ALL** the following conditions are satisfied:
	(a) rpm reached `Launch RPM(rpm)`
	(b) Vechicle Speed is less than `Speed Threshold (kph)`
	(c) TPS is greater than `TPS Threshold`
	(d) "Switch condition" is satisfied, i.e. one of the following conditions is true:
	---- `Activation Mode` is `Speed Based`
	---- `Activation Mode` is `Break Pedal`
	---- `Activation Mode` is `Launch Button` and corresponding pin is in proper state
	---- `Activation Mode` is `Clutch Down Switch` and corresponding pin is in proper state
		
Condition 1.(a) above contradicts the [Lua script](https://www.rusefi.com/forum/viewtopic.php?p=49599#p49599) that applies `Fuel Added %` setting when:
- rpm is between `Launch RPM(rpm)` - `Launch Control Window(RPM)` and `Launch RPM(rpm)`

and doesn't apply it when:
- rpm is greater than `Launch RPM(rpm)`.

@ElDominio, should we fix `Fuel Added %` setting usage?

**Comment by ElDominio** [comment]
I think current implementation is fine. ok to keep as is
