### ISSUE TITLE
Pass start request from Lua

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#6619]
**Is your feature request related to a problem? Please describe.**
I want to be able to request starter engagement to firmware from Lua, so I can do all the monitoring for this from Lua (start request is on CAN, ECU has physical starter control)

**Would we need new configuration fields?**
No, just add new option here
![image](https://github.com/rusefi/rusefi/assets/5685108/b900971d-3d31-4399-9f6f-7f0dbe0c02a9)

that says "Lua"

**Describe the solution you'd like**
Add an option to send from Lua

**Comment by rusefillc** [comment]
``startCrankingEngine()``
