### ISSUE TITLE
Custom firmware builds as .zip.zip.zip from May 25

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#6644]
**Describe the bug**
Build commands make a file with the date 0525 and zipped three times over

**To Reproduce**
1. Build a custom firmware
2. look at what gets built

**Expected behavior**
I get a build based off latest firmware, and only zipped once

**Screenshots**
![image](https://github.com/rusefi/rusefi/assets/5685108/f601663e-8c63-4b2e-b6dd-39371073b192)

**EDIT**
seems to be latest firmware but odd file naming errors

**Comment by rusefillc** [comment]
github thing we do not have control over :(
