### ISSUE TITLE
single cylinder, 4 stroke wasted spark

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#6662]
https://rusefi.com/forum/viewtopic.php?f=17&t=2768 states that single cylinder, 4 stroke does not operate in wasted spark mode

**Comment by rusefillc** [comment]
@ElDominio do you know if we have wasted one cylinder?

**Comment by ElDominio** [comment]
On chumas i run "single coil" without sync, so something works somehow

**Comment by rusefillc** [comment]
related to #6868?

**Comment by rusefillc** [comment]
Dup of #4195
