### ISSUE TITLE
BUG: FATAL in firmware with DEBUG mode on F469 MCU

### ISSUE THREAD

**Issue by darxfame** [rusefi/rusefi#667]
I compile current firmware with flag `set DEBUG_LEVEL_OPT="-O2"` and firmware starts normally,
But if i compile it without this flag, i've got a `WARNING: HW timer state 1` message and FATAL firmware status. red and blue LED is always ON

Log file from rusefi console
[MAIN_rfi_report_2019-01-11_22_00_37.zip](https://github.com/rusefi/rusefi/files/2751039/MAIN_rfi_report_2019-01-11_22_00_37.zip)

**Comment by darxfame** [comment]
`cd rusefi/firmware
set PROJECT_BOARD=Prometheus
set EXTRA_PARAMS="-DDUMMY -DSTM32F469xx -DEFI_ENABLE_ASSERTS=FALSE -DCH_DBG_ENABLE_CHECKS=FALSE -DCH_DBG_ENABLE_TRACE=FALSE -DCH_DBG_ENABLE_ASSERTS=FALSE -DCH_DBG_ENABLE_STACK_CHECK=FALSE -DCH_DBG_FILL_THREADS=FALSE -DCH_DBG_THREADS_PROFILING=FALSE"
set DEBUG_LEVEL_OPT="-O2"
set USE_BOOTLOADER=yes
call compile_and_program.bat -r -j4
`

**Comment by rusefi** [comment]
This command does not work :( I suspect that's not a real command? It could not be just one huge line

maybe you need to use
```
three tilde syntax - start with three tilde and end with three tilde
```
 

I believe it should be possible to produce a real command - maybe take compile_and_program.bat for start? Maybe ";" are missing?



![image](https://user-images.githubusercontent.com/7377949/51062481-08175c00-15c5-11e9-9b8c-a28664eb3bba.png)

**Comment by rusefi** [comment]
maybe attach a .bat file?

**Comment by darxfame** [comment]
> может прикрепить файл .bat?
@rusefi attach it
[!compile-prometheus.zip](https://github.com/rusefi/rusefi/files/2751364/compile-prometheus.zip)

**Comment by darxfame** [comment]
[arm-none-eabi-gcc-v.txt](https://github.com/rusefi/rusefi/files/2751845/arm-none-eabi-gcc-v.txt)

**Comment by andreika-git** [comment]
Forgot to mention that is was compiled with USE_FPU = softfp

**Comment by andreika-git** [comment]
Also I have to remind that earlier firmware versions worked fine with DEBUG/RELEASE mode on the same config. We need to investigate when it happened - maybe during ChibiOS3->4 migration?

**Comment by rusefi** [comment]
@andreika-git do you have hardware and interest to look into this? There is no change that I will ever have time go grab my F469 and investigate :( maybe @fpoussin has a F469

**Comment by andreika-git** [comment]
I do have hardware and interest, but I have no human resources currently :( Maybe I'll find some time in two weeks...

**Comment by mck1117** [comment]
seems like it's been a long time since this, bug probably fixed?
