### ISSUE TITLE
small-can-board does not start

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#6738]
hellen/small-can-board hellen F7 firmware does not start

expected: blue LED and USB
actual  result: no blue LED, no USB

**Comment by rusefillc** [comment]
@dron0gus any chance you can try on uaefi?

**Comment by rusefillc** [comment]
We even have https://github.com/rusefi/rusefi/blob/50a698fdafd2a660900f71c63d7189e90df56e70/firmware/config/boards/hellen/small-can-board/compile_small-can-board_debug.sh

**Comment by rusefillc** [comment]
![image](https://github.com/user-attachments/assets/53f99449-5790-461b-944b-9656b23dc754)

![image](https://github.com/user-attachments/assets/4b7d8578-8082-4c99-b2f5-8d615357519f)

**Comment by dron0gus** [comment]
Done in https://github.com/rusefi/rusefi/pull/6740 , @rusefillc can we close?
