### ISSUE TITLE
Why is default baudrate at 9600?

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#6741]
**Describe the bug**
Every time I make a new project it insists that correct baud is 9600, is it not supposed to be 115200?

**Hardware**
 - Board: ALL

**To Reproduce**
Create a new project and autodetect ecu

**Expected behavior**
The default baudrate is 115200
**Screenshots**
![image](https://github.com/user-attachments/assets/6c111812-dc07-4a60-b5b1-45c00013222f)

**Comment by mck1117** [comment]
the baud rate over USB does literally nothing

**Comment by rusefillc** [comment]
See above.

**Comment by ElDominio** [comment]
as someone who came from speeduino and is used to serial-USB chips,  i was concered by it. thank you
