### ISSUE TITLE
updater openblt does not work

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#6757]
simple updater does not work in openblt mode - looks like something wrong about working folder?

**Comment by rusefillc** [comment]
![image](https://github.com/user-attachments/assets/df6c7276-513b-4c12-b571-eaae8ebcafca)

**Comment by rusefillc** [comment]
![image](https://github.com/user-attachments/assets/2902ef72-c73d-458e-9df1-f51ac12faca3)

**Comment by kifir23917** [comment]
I cannot reproduce this issue, but I suspect that it relates to [the comment](https://github.com/rusefi/rusefi/issues/6788#issuecomment-2288759852) and will be fixed in the scope of #6788.
Let's return to this ticket if we reproduce something similar again.
