### ISSUE TITLE
HARDWARE VALIDATION FAILED what does it mean in case of injector

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#6762]
![image](https://github.com/user-attachments/assets/631df348-8a17-4d6b-b5e3-45c39c17c8ac)

``The error goes away if I remove B5 injector output 2``

**Comment by larsnergard** [comment]
Just to add. This error came while using a Discovery board. Not on the actual ECU.

**Comment by rusefillc** [comment]
Ohh, so user error of mixing wrong firmware snd hardware?

**Comment by larsnergard** [comment]
You could say that.

Did not think it would matter as long as the right processor was used. It was a STM32F407G-DISC1 board.
