### ISSUE TITLE
changes are not being saved

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#6775]
connect to proteus F7 ECU
change displacement
hit burn

actual result: pending changes stay forever :(

![image](https://github.com/user-attachments/assets/7dbece9e-af47-4681-9b1c-279a7f1c8ea5)

**Comment by romioRN** [comment]
I tried a lot of bundles and I discovered that starting with this one it doesn't work. 
 https://github.com/rusefi/rusefi/actions/runs/10145151558

**Comment by rusefillc** [comment]
caused by https://github.com/rusefi/rusefi/pull/6753

**Comment by rusefillc** [comment]
Fixed by https://github.com/rusefi/rusefi/pull/6794
