### ISSUE TITLE
Why is 36-2-1-1 "rise only"?

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#6776]
**Describe the bug**
As seen on https://github.com/rusefi/rusefi/wiki/All-Supported-Trigger , 36-2-1-1 is rising only, but this is a VR sensor. Edge should depend on what is used to convert from sine to sqaure, and in my case I am using a MAX9924 which _should_ be used in falling as far as i understand.

**Hardware**
 - Board: custom paralelaEJ207

**To Reproduce**
1. Go to 36-2-1-1
2. Set to falling
3. No RPM because trigger is ONLY rising

**Expected behavior**
I can choose which edge, since it depends on my converter

**Screenshots**
![image](https://github.com/user-attachments/assets/2014b18f-8c9d-41a7-ad67-cd670e34c917)

**Comment by rusefillc** [comment]
@ElDominio i think you are not the first one using MAX992x for VR. If you believe that all triggers are wrong or terminology is wrong please create a separate ticket focusing on that. Whatever way we use MAX992x we plan to use it.

Please design hardware to match firmware. Unless you have $4M there is no chance we would have configurable not even sure what.
