### ISSUE TITLE
Remove Mitsubishi 4g92/3/4 Cam 29

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#6785]
**Describe the bug**
This is a vestigial trigger from testing 4g series trigger
![image](https://github.com/user-attachments/assets/7c6242b1-87c8-45f2-9137-79d824879f28)

**Comment by rusefillc** [comment]
@ElDominio hiding it from the list while it stays to support VVT_MITSUBISHI_4G9x VVT right?
