### ISSUE TITLE
f7 smoke in a very weird configuration

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#6797]
brand new https://github.com/rusefi/hellen154hyundai/ from box

using 4k-gdi firmware for test (yes totally wrong firmware for that board)

got fatal ![image](https://github.com/user-attachments/assets/17401a69-d2fe-4e70-9b91-43d386b0e25a)

had +12v from lab power supply

had USB cable

hit 'reset' on PCB

expected: reboot

actual result:
a) high pitch noise
b) smoke in the middle of stm32f7

**Comment by rusefillc** [comment]
misconfigured 33810 for example OUT_EN?

**Comment by Qwerty-OFF** [comment]
![image](https://github.com/user-attachments/assets/53d4ac80-5d38-47c3-ba3f-3e0540841a61)
