### ISSUE TITLE
openblt port detection which same serial is used part two

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#6803]
https://github.com/rusefi/rusefi/issues/6747

windows 7
maybe slower device detection?

![image](https://github.com/user-attachments/assets/10efb57c-f69f-4291-a33b-89fd021efdb7)

**Comment by rusefillc** [comment]
![image](https://github.com/user-attachments/assets/235f9c4d-696a-4bde-83d9-9e3e4f160204)

**Comment by kifir23917** [comment]
I'm closing this ticket because the problems on screenshots above should be fixed in scope of #6788 (first one) and #6713 (second one)

**Comment by rusefillc** [comment]
happy!

![image](https://github.com/user-attachments/assets/ab62fb43-9cb4-463b-9709-07d9d75a7bd2)
