### ISSUE TITLE
SD card in SDIO mode

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#683]
Random boards like https://wiki.stm32duino.com/images/6/69/Vcc-gnd.com-STM32F407VET_mini-schematic.pdf have SD card wired to SDIO. While SDIO shares pins with SPI3, I believe SPI code would not work for instance because SDIO clock is PC12 but SPI clock is PC10.

We need SDIO SD card implementation.

**Comment by ahmadmn** [comment]
is it useful example:
[](http://stm32f4-discovery.net/2014/07/library-21-read-sd-card-fatfs-stm32f4xx-devices/)

**Comment by rusefillc** [comment]
@dron0gus @andreika-git we might need faster SD write for "smart ecu" meta epic. Open question if SDIO would help with performance or not.

**Comment by rusefillc** [comment]
We now have SDIO mode as compile time option EFI_SDC_DEVICE

No official boards are using SDIO as of today
