### ISSUE TITLE
rusefi allows selecting inactive cam signal for engine sync resolution

### ISSUE THREAD

**Issue by ggurov** [rusefi/rusefi#6830]
**Describe the bug**
it is possible to select inactive cam to be used for engine sync resolution and beat head against wall wondering why full sequential doesn't work

**Hardware**
 - Board: doesn't matter
 - Engine info: things with exhaust cam single tooth or whatever

**To Reproduce**
1. Go to Trigger
3. set cam sensor bank 1 intake to: NONE
4. set cam sensor bank 1 exhaust to: SOMETHING
5. set Cam for engine sync resolution to: INTAKE FIRST BANK

**Expected behavior**
Some sort of error or warning to pop up saying that engine sync resolution selection is impossible with current setings

**Screenshots**

![image](https://github.com/user-attachments/assets/545fbebd-c7fd-4089-b064-ffced575a6b5)

![image](https://github.com/user-attachments/assets/44f46d6f-ab9d-42b4-819e-5654266d2fe5)

![image](https://github.com/user-attachments/assets/75acdf39-3e89-4095-94ef-3444f3a67382)

![image](https://github.com/user-attachments/assets/deafdca2-8153-42f7-b755-90c40b14a862)

fuel is somehow sequential in this case, but ignition is not

![image](https://github.com/user-attachments/assets/f67a33a0-d247-415b-9222-06adea27197f)

**Additional context**
Engine will probably run, but customer states that fuel was sequential and ignition was not.

vvvv 

[sequential_troubles_wrong_cam.msq.txt](https://github.com/user-attachments/files/16664680/sequential_troubles_wrong_cam.msq.txt)

**Comment by rusefillc** [comment]
@ggurov this could be fixed now, thank you for the defect report!
