### ISSUE TITLE
open loop boost control does not allow Y axis MAP values greater than 100, even when Y axis is set to MAP

### ISSUE THREAD

**Issue by ggurov** [rusefi/rusefi#6840]
**Describe the bug**
Boost control open loop table does not allow Y bins to be set greater than 100, yet allows Y axis to be set to MAP. The purpose of this would be to create a "valley" to vary boost control % based on boost in a preset manner.

**Hardware**
 - Board: doesn't matter
 - Engine info doesn't matter

**To Reproduce**
1. Go to 'Boost control open loop'
2. change 'Y axis' to "MAP"
3. change top load bin to 101

**Expected behavior**
Ability to set  Y bins to useful MAP values

**Screenshots**
![image](https://github.com/user-attachments/assets/09edbbca-04d4-4bae-9a35-b4e69e336c10)

**Additional context**
It may be silly and not work in practice... but it should still let me shoot myself in the foot.

**Comment by rusefillc** [comment]
#4802

**Comment by rusefillc** [comment]
Follow up separate issue https://github.com/rusefi/rusefi/issues/6843
