### ISSUE TITLE
AFR Protection: Protection for leaning out under high load

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#6841]
**Is your feature request related to a problem? Please describe.**
This feature is related to reacting to lean conditions under high load, so I guess it is a problem

**Would we need new configuration fields?**
TPS% For Protection: minimum TPS value for which we check to see if we are over our target safety AFR
MAP for Protection: same as above, but for MAP
Minimum RPM Limit: minimum RPM to check for AFR cut
AFR Maximum: Maximum AFR value we can be at before we apply a cut
Time for protection: time in ms we need to be over the Maximum AFR to trigger a cut event.

Cut conditions are removed once (MAP and TPS) OR RPM are under their limit values

**Describe the solution you'd like**
A cut that looks at AFR and checks if we are not too lean, to save engine from lean conditions

**Comment by ggurov** [comment]
![image](https://github.com/user-attachments/assets/1de315a6-700e-44b9-8f6f-d09ce03be843)


is lambda protection not what you're looking for ?

**Comment by ElDominio** [comment]
It 100% is.... why is it not in the PROTECTIONS MENU!!!!!!!!!!!!!!!!!!
![image](https://github.com/user-attachments/assets/1b665293-b057-4137-8863-08fd6fc09018)

![image](https://github.com/user-attachments/assets/505c2d9d-0144-42fb-b7f3-1fdb92863acc)
WHAT

**Comment by ggurov** [comment]
also, watch out, that table is lambda difference, regardless of what's used for main, afr or lambda. 

lambda protection table is lambda, but it works and it's great.
