### ISSUE TITLE
After upgrade - Controller Error: Burn Page failed CRC Check. - resistor pullup values

### ISSUE THREAD

**Issue by ggurov** [rusefi/rusefi#6844]
**Describe the bug**
Message received: "Controller Error: Burn page failed CRC Check - Check log for full data Dump of local and controller Page 1 data"

**Hardware**
 - Board: uaefi
 - Engine info: 2jz-gte (bench really)

**To Reproduce**
1. Have v20240625@59822223 firmware installed,  open TS, save current tune as something which will be used later
2. Close TS
3. Upgrade to v20240822@1431655765 firmware using auto_updater, or whatever
4. Open TS, update signature
5. See difference report from previous load
6. Click "Send current Tunerstudio Settings"
7. Receive "Controller Error: Burn page failed CRC Check - Check log for full data Dump of local and controller Page 1 data" message
8. Close TS
9. Open TS - connect to controller
10. Click File -> Compare tune , and pick the tune we saved in step #1, click open
11. see difference report indicate 2 grayed out Pullup Resistor (ohm) fields, controller having 4700, and saved tune from step 1 showing 0:
![image](https://github.com/user-attachments/assets/120371d9-8eb0-4d77-840c-a385559d3f81)

12. click "Load settings from $file)
13. Receive the same "Controller Error: Burn page failed CRC Check - Check log for full data Dump of local and controller Page 1 data" message again

**Expected behavior**
I dunno what it should do. the controller updated correctly, and really did the right thing, of setting default pullup resistor value. The scary message and uncertainty that entire tune loaded correctly, except for the value that was rejected. Maybe this could somehow go into the "tune load errors" dialog that usually shows incompatible differences

**Screenshots**

![image](https://github.com/user-attachments/assets/712de26d-bb5e-4991-9a2d-cd45dbcccffd)

**Additional context**

**Comment by rusefillc** [comment]
you are failing to change it because uaefi forces all four pull-ups to be 4700

fix for now: hide settings which are not allowed to be changed
more proper fix one day: make settings which are not allowed to be changed visible but unchangeable
