### ISSUE TITLE
ConfigurationImageFile add header

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#6863]
We have ConfigurationImageFile.java with readFromFile and saveToFile methods

Let's have a useful header
* file format version
* 4 bytes size
* signature
* payload

**Comment by rusefillc** [comment]
SerialSandbox
```
I 240830 131424.806 [ECU AutoDetectPort9] SerialAutoChecker - Got signature=rusEFI master.2024.08.30.hd81.3580009858  from serial=COM52
```

**Comment by rusefillc** [comment]
in addition to how we just save a binary can we please also automatically save same binary into a zip file as well?

**Comment by rusefillc** [comment]
See also shared_io binary_config_image

**Comment by kifir23917** [comment]
Now when we press `Connect` button in console UI, console creates in its folder `current_configuration.binary_image` file. This file is zip archive with two files:
1. `Image.bin` with image binary representation
2. `ConfigurationImageMetaVersion0_0.yaml` with image metadata
The screenshot below illustrates structure of `ConfigurationImageMetaVersion0_0.yaml` file:
![image](https://github.com/user-attachments/assets/a4dd9763-5a87-499c-8347-13af9b566709)
