### ISSUE TITLE
Fixed timing is rarely fixed

### ISSUE THREAD

**Issue by firebat-hacs** [rusefi/rusefi#6878]
timing is set to 10 degrees fixed in tunerstudio
which means the two lines should overlap (PIP - Crank wheel/blue signal and SPOUT - output to ignition box/orange signal)
but it drifts like 27 degrees per 1000rpm
[timing issue.zip](https://github.com/user-attachments/files/16830296/timing.issue.zip)

https://youtu.be/Unv5erS-94o?si=MO84EsvVuYmojZae

![image](https://github.com/user-attachments/assets/97dc8e81-d8e4-44cd-8ce8-83ef24e87912)

**Comment by rusefillc** [comment]
zero RPM: ignition timing gauge shows selected fixed timing value as expected

![image](https://github.com/user-attachments/assets/886b6ada-ae90-4f0c-91ba-a484d1f2e9aa)

**Comment by rusefillc** [comment]
during cranking we do not show fixed timing, is this broken or expected?

![image](https://github.com/user-attachments/assets/68811859-d239-47bb-824d-18373ea1a094)

**Comment by rusefillc** [comment]
@firebat-hacs can you help by grabbing some release maybe from six months ago and checking if ignition: timing gauge used to show fixed value below cranking RPM threshold and above cranking RPM threshold?

**Comment by rusefillc** [comment]
@firebat-hacs thank you this looks better now! pretty much before pulling the scope please confirm what the gauges are showing - this was not timing drift, this was totally ECU commanding dynamic timing

![image](https://github.com/user-attachments/assets/0da8f2df-47e8-426d-9baa-0f4fe7edec56)
