### ISSUE TITLE
Ability to use an 8x8 table for after-start fuel multiplier that depends on CLT and engine run time

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#6919]
@ElDominio what do you think about https://github.com/FOME-Tech/fome-fw/commit/6a202f40dd14c891385e2421384599ecf52874cb

**Comment by ElDominio** [comment]
Is that not exactly 
![image](https://github.com/user-attachments/assets/29ee20ca-1464-45f7-abc7-088a353df63e)

? Only this is 6x6?

I also see that X axis is time but.... can't we just keep using engine cycles?
