### ISSUE TITLE
Why do we use so much stack?

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#695]
why is UTILITY_THREAD_STACK_SIZE currently 400 and not 200 or 800?

why is PORT_INT_REQUIRED_STACK so high at 768?

**Comment by rusefi** [comment]
CH_DBG_FILL_THREADS

**Comment by rusefi** [comment]
interpolate2d() invocation cost = 40 bytes
interpolateMsg() invocation cost = 72 bytes

**Comment by rusefi** [comment]
Actually F7 chconf does NOT define PORT_IDLE_THREAD_STACK_SIZE and PORT_INT_REQUIRED_STACK and it looks like F7 is running with less stack?

FYI @andreika-git @mck1117

**Comment by mck1117** [comment]
this got fixed - PORT_IDLE_THREAD_STACK_SIZE and PORT_INT_REQUIRED_STACK were reduced to the chibios recommended values

**Comment by mck1117** [comment]
this got fixed - PORT_IDLE_THREAD_STACK_SIZE and PORT_INT_REQUIRED_STACK were reduced to the chibios recommended values
