### ISSUE TITLE
fail to generate F7 DFU files

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#696]
```
Loading build/rusefi.hex...
ERROR: Image appears to have invalid initial program counter
```

:( See https://community.st.com/s/question/0D50X00009XkeovSAB/dfu-fail-verify-8-byte-align-magic

**Comment by fpoussin** [comment]
Need more context. Which program gives this error?

**Comment by rusefi** [comment]
the command in build script:
..\misc\hex2dfu\HEX2DFU.exe build/rusefi.hex -out build/rusefi.dfu

this is an utility from Clive 2.0 see https://community.st.com/s/question/0D50X00009XkeovSAB/dfu-fail-verify-8-byte-align-magic

@andreika-git has just implemented an alternative utility also there is something on https://github.com/encedo/hex2dfu

**Comment by rusefi** [comment]
https://github.com/encedo/hex2dfu needed some changes to compile so we now have https://github.com/rusefi/hex2dfu
