### ISSUE TITLE
hybrid injection: separate fuel pressure handling

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#6972]
At the moment we have staged injection - two injectors per cylinder with adjustable ratio between injectors

in case of hybrid injection (GDI and MPI) we need different fuel pressures on different injectors

**Comment by rusefillc** [comment]
getFuelDifferentialPressure

```
	FuelPressureLow, // in kPa
	FuelPressureHigh, // in kPa
	FuelPressureInjector,
```

**Comment by rusefillc** [comment]
https://www.youtube.com/watch?app=desktop&v=sz8cqygvPC4

![image](https://github.com/user-attachments/assets/61d22695-5838-4573-bea7-be2832bf85ee)


![image](https://github.com/user-attachments/assets/ca763fed-039f-48fe-808b-765f31311e06)



https://www.hella.com/techworld/us/Technical/Sensors-and-actuators/Checking-a-high-pressure-fuel-pump-69306/

![image](https://github.com/user-attachments/assets/f7bee2f1-af36-4616-ab82-c5c5d61b373b)

**Comment by rusefillc** [comment]
https://www.youtube.com/watch?v=MIDItBqX3SQ

**Comment by kifir23917** [comment]
For primary injectors we allow user to configure the following settings:
- `Injector flow`
- `Injector flow compenstaion mode`
- `Injector reference pressure(kPa)`

![image](https://github.com/user-attachments/assets/cc2de582-38dc-4ab0-b673-2eaf06df9bbd)

For secondary injectors we allow user to configure only `Secondary injector flow`:

![image](https://github.com/user-attachments/assets/982740d3-6e29-4364-967d-5b47a79dec21)

As I understand to support adequately hybrid injection (GDI and MPI) we need to implement
- `Secondary injector flow compenstaion mode`
- `Secondary injector reference pressure(kPa)`
settings in addition to the existing `Secondary injector flow` setting and to use these settings in mathematics for secondary injectors.

@ElDominio, are you agree?

**Comment by ElDominio** [comment]
This is correct. They have very different pressures so this is reasonable

**Comment by kifir23917** [comment]
Surprise-surprise :) Neither [Injector flow](https://github.com/search?q=repo%3Arusefi%2Frusefi%20injector_flow&type=code) nor [Secondary injector flow](https://github.com/search?q=repo%3Arusefi%2Frusefi+injectorSecondary_flow&type=code) parameters from the screenshots above are not used in our C++ code.

**Comment by kifir23917** [comment]
I've implemented `Secondary injector flow compensation mode` and `Secondary injector reference pressure (kPa)` settings:

![Image](https://github.com/user-attachments/assets/c3950c59-1b06-45eb-a651-6cf239cfc6c0)
