### ISSUE TITLE
FUel Level Sensor should have a RAW option

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#6979]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when I can't see the voltage on the pin for the Fuel Level Sensor

**Would we need new configuration fields?**
No, only a new gauge

**Describe the solution you'd like**
Add a rawFuelLevel gauge under the raw gauges section

**Describe alternatives you've considered**
Using a multimeter? lol

**Comment by rusefillc** [comment]
@FDSoftware does it?
