### ISSUE TITLE
Lua 'startCrankingEngine' method

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#6983]
We need ``startCrankingEngine`` Lua function behaving similar to physical start button

**Comment by rusefillc** [comment]
@ElDominio please test

**Comment by ElDominio** [comment]
About startCrankingEngine, does it accept values? startCrankingEngine(1) means startcranking and startCrankingEngine(nil) means no more cranking request?

**Comment by rusefillc** [comment]
@ElDominio zero arguments

see https://github.com/rusefi/rusefi/wiki/Lua-Scripting#startcrankingengine

**Comment by ElDominio** [comment]
![image](https://github.com/user-attachments/assets/a95e81e6-54fd-4f71-aed9-12850f13214d)


Can't assign starter output if I don't choose a physical crank pin

**Comment by ElDominio** [comment]
console says: "2024-10-19_16_23_28_537: EngineState: Let's crank this engine for up to 3 seconds via 6C - High Side 2!" 

but i get no starter? strange

**Comment by rusefillc** [comment]
``EngineState: Let's crank this engine for up to 3 seconds via 6C - High Side 2!"`` is printed after toggling of physical output

@ElDominio please also share what console says few seconds later? wither way I would expect another line about disengaging starter?

**Comment by rusefillc** [comment]
@ElDominio please use DMM or oscilloscope or on-board LED to confirm if physical cranking actually happens

**Comment by ElDominio** [comment]
physical cranking is ok, it was me being a dumb. confirmed working
