### ISSUE TITLE
Detected gear is ok, but current gear is 0

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#6986]
**Describe the bug**
Detected gear is correct, but current gear is 0. Is it my problem?

**Hardware**
 - Board: Platinum
 - Engine info LS3
 
**To Reproduce**
1. Set up gear detection
2. see gear being detected
3. current gear is 0

**Expected behavior**
detected gear = current gear

**Additional context**
Tune and log
https://rusefi.com/online/view.php?msq=1710

**Comment by rusefillc** [comment]
renaming to "TCU: Current Gear" and hiding
