### ISSUE TITLE
Add I-term bounds for Alternator Control

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#6988]
Is your feature request related to a problem? Please describe.
Yes, the issue occurs with the I term of the alternator control algorithm. When the system cannot reach the target for any reason, the I term continues to grow indefinitely. This uncontrolled growth causes the I term to spiral upward without bounds, even when the conditions that caused the initial discrepancy have stabilized. This leads to poor control behavior and instability in the system.

Would we need new configuration fields?
Yes, new configuration fields would be required to define the upper and lower bounds of the I term. These bounds should be configurable to suit different system requirements and scenarios.

Describe the solution you'd like
The addition of configurable bounds to the I term within the alternator control algorithm. This would prevent the I term from growing to infinity when the system is not able to reach its target. Once bounds are set, the I term will stop accumulating beyond these values, stabilizing the system while maintaining control performance.

Describe alternatives you've considered

    Implementing a soft saturation mechanism where the I term growth slows down progressively instead of stopping abruptly at the bounds.
    Resetting the I term under specific conditions, such as when the error becomes small or stable. However, this could cause abrupt control behavior and may not be as smooth as bounding the I term.

Additional context
This issue can cause significant control problems in systems where achieving the target output isn't always feasible due to external conditions. Bounding the I term would improve stability and reliability without negatively affecting normal operation.

please tell me it sounds smart

**Comment by rusefillc** [comment]
@ElDominio you sounded smart here!
