### ISSUE TITLE
uaefi121 ADC list incomplete

### ISSUE THREAD

**Issue by ggurov** [rusefi/rusefi#6991]
**Describe the bug**
There are very few labeled ADC inputs in TS, and lack of definition of remaining pins

**Hardware**
 - Board: uaefi121
 - Engine info ; bench

**To Reproduce**
1. Go to 'map sensor'
2. Click on 'map input'
3. Scroll down to lack of MAP sensor
4. See error of ways

**Expected behavior**
Ability to select ADC channels by their name

**Screenshots**
![image](https://github.com/user-attachments/assets/a8e83a22-dcb2-4d51-966c-c21bb923f622)

![image](https://github.com/user-attachments/assets/c8b2da25-026e-4f2a-ae4b-53e414cb2af0)

**Comment by rusefillc** [comment]
not a solution, just a useful link for myself https://rusefi.com/docs/pinouts/hellen/uaefi121/

**Comment by rusefillc** [comment]
random https://github.com/andreika-git/hellen-one/issues/394

**Comment by rusefillc** [comment]
@ggurov just pushed info for five more pins, feel free to reopen if you can point on any more missed pins
