### ISSUE TITLE
Pre-defined triggerOffsets for OEM trigger wheels

### ISSUE THREAD

**Issue by andreika-git** [rusefi/rusefi#702]
It seems that a precise triggerOffset definition is non-trivial even for reasonably advanced users.
That's why I suggest to prepare some pre-defined values for popular OEM trigger wheel configurations like 60-2. And set them as defaults when the trigger shape is changed.

The problem is that "common sense" teeth counting is non-intuitive (0-based trigger event counting logic is used in the firmware), and 20-th tooth is not 20*6=120 degrees...

**Comment by rusefi** [comment]
@andreika-git I believe you are proposing to add "60/2 at 20th" trigger?
what is tdcOffset for such standard trigger?

**Comment by andreika-git** [comment]
I believe it's 114:
![image](https://user-images.githubusercontent.com/15104768/54151559-c3ccfe80-4443-11e9-9b67-bad8d1d4a768.png)

**Comment by OrchardPerformance** [comment]
Unfortunately the 60-2 has multiple variations, volvo is 90 degrees, early BMW is 84 degrees and the late BMW is 324 degrees. 

Best we can possibly do is to compile a list of as many as we can on the wiki.

**Comment by mck1117** [comment]
we do this for very well known triggers
