### ISSUE TITLE
bare minimum nucleo F767 HW CI

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#7033]
We need a happy HwCiNucleoF7 test suite for off the shelf nucle F767

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi/commit/db94786a99374fa8ce5c6c0caa0900b8fbd0de39 did not do it for some reason

**Comment by rusefillc** [comment]
@FDSoftware please help if you can?

**Comment by FDSoftware** [comment]
> @FDSoftware please help if you can?

sure, I can't assign myself the issue, but I'll take this one and 7034
