### ISSUE TITLE
Serial-over-usb driver connectivity issue

### ISSUE THREAD

**Issue by andreika-git** [rusefi/rusefi#705]
The existing Serial-over-USB driver (usbconsole.c) doesn't work on some STM32F407VET6 boards (See https://rusefi.com/forum/viewtopic.php?f=4&t=1498). The PC shows "usb device not recognized" error. 
It may depend on the PC hardware/OS and/or STM32 board/USB-cable/SWD-programmer connected or not, etc...
We suspect that the problem is with the following code:

```/*
	 * Activates the USB driver and then the USB bus pull-up on D+.
	 * Note, a delay is inserted in order to not have to disconnect the cable
	 * after a reset.
	 */
	usbDisconnectBus(serusbcfg.usbp);
	chThdSleepMilliseconds(1500);
	usbStart(serusbcfg.usbp, &usbcfg);
	usbConnectBus(serusbcfg.usbp);
```

**Comment by rusefi** [comment]
I have five boards work fine on my Windows 7 64 bit using the following driver

![image](https://user-images.githubusercontent.com/7377949/54357688-f558ec00-4634-11e9-9596-a467d65d8ecf.png)

what is your OS exactly? can you please attach similar driver info picture?

**Comment by andreika-git** [comment]
The same Win7-64,
![image](https://user-images.githubusercontent.com/15104768/54357982-f6574100-4667-11e9-89ef-a95df2640161.png)

**Comment by rusefi** [comment]
[rusefi_master_no_changes_mini_board.zip](https://github.com/rusefi/rusefi/files/2966594/rusefi_master_no_changes_mini_board.zip)

**Comment by andreika-git** [comment]
http://www.chibios.com/forum/viewtopic.php?f=16&t=4981
(wasn't updated lately but still related...)

**Comment by rusefi** [comment]
We have no idea what this issue is about, right?

**Comment by mck1117** [comment]
USB serial is very stable these days, close?
