### ISSUE TITLE
"60/2 with variable cam location" trigger

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#707]
In order to avoid massive confusion about rusEfi trigger we need a way to define 60/2 + cam or 36/1 + cam as a trigger with variable cam shaft mark position, not as a VVT configuration

**Comment by rusefi** [comment]
JRD McLAREN wrote: ↑Thu Mar 14, 2019 2:46 pm
I'm think, the right name for your trigger wheel templates are:

60/2 with Hall sensor (60/2)
60/2 with VR sensor (60/2 VW)

...some OPEL / Vauxhall car have HALL sensor on crank ...

See https://rusefi.com/forum/viewtopic.php?f=2&t=1519&p=32088#p32088

**Comment by rusefi** [comment]
@andreika-git @darxfame @dron0gus we need to get back to this...

**Comment by rusefi** [comment]
https://rusefi.slack.com/messages/CJ9JH3Y21/details/

I believe there was a table on github somewhere, need to check my skype history for the link

**Comment by andreika-git** [comment]
https://github.com/rusefi/rusefi_documentation/blob/master/triggers/readme.md

**Comment by mck1117** [comment]
this works now - you can configure a cam with "first half" or "second half" and things work properly
