### ISSUE TITLE
rawFlex gauge to show actual flex fuel hz

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#7082]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to open console and use some easily-forgettable command to check flex fuel hz. this should be a gauge on TunerStudio

**Describe the solution you'd like**
add a "rawFlex" in  Raw 2 that shows current hz of a flex fuel sensor

**Describe alternatives you've considered**
that one command i forgot

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi/issues/6949
