### ISSUE TITLE
ALS no switch available

### ISSUE THREAD

**Issue by Artux0418** [rusefi/rusefi#7083]
**Describe the bug**

**Hardware**
 - Board: UAEFI121
 - Engine info 1.8T vw

**To Reproduce**
1. Go to Controller
2. Click on Anti Lag ALS
3. Scroll down to Switch Input

**Expected behavior**
Select 3 programmable buttons or other inputs.

**Screenshots**
![image](https://github.com/user-attachments/assets/64d70e47-de08-4ce3-9e0a-229fee4e2761)

**Additional context**

**Comment by rusefillc** [comment]
@Artux0418 thank you!
