### ISSUE TITLE
two extended can broadcasts use the same 29bit id for 2 sets of data

### ISSUE THREAD

**Issue by ggurov** [rusefi/rusefi#7088]
**Describe the bug**
0x0770004 is used for 2 sets of data, consecutively

**Hardware**
 - Board: mega100
 - Engine info : na

**To Reproduce**
1. Enable extended can broadcast
2. Sniff can bus
3. observe 0x0770004  arriving twice, carrying 2 sets of data
4. find code:
```

void sendQcBenchButtonCounters() {
    CanTxMessage msg(CanCategory::BENCH_TEST, (int)bench_test_packet_ids_e::BUTTON_COUNTERS, 8, /*bus*/0, /*isExtended*/true);
    msg[0] = TRUNCATE_TO_BYTE(engine->brakePedalSwitchedState.getCounter());
    msg[1] = TRUNCATE_TO_BYTE(engine->clutchUpSwitchedState.getCounter());
    msg[2] = TRUNCATE_TO_BYTE(engine->acButtonSwitchedState.getCounter());
    // todo: start button
}

void sendQcBenchAuxDigitalCounters() {
    CanTxMessage msg(CanCategory::BENCH_TEST, (int)bench_test_packet_ids_e::BUTTON_COUNTERS, 8, /*bus*/0, /*isExtended*/true);
  for (int i =0;i<LUA_DIGITAL_INPUT_COUNT;i++) {
      msg[i] = TRUNCATE_TO_BYTE(engine->luaDigitalInputState[i].state.getCounter());
  }
}

```

bot can messages use  `(int)bench_test_packet_ids_e::BUTTON_COUNTERS` package id

**Expected behavior**
Ability to distinguish between packet data contents deterministicly by id

**Screenshots**

![image](https://github.com/user-attachments/assets/05c9ca80-b93c-4cb1-bdfd-e635053f9f4f)

**Comment by rusefillc** [comment]
@ggurov WOW thank you!!!
