### ISSUE TITLE
Migrate to newer ChibiOS

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#710]
Why not? Also H7 support is probably better in version 19 and version 20?

Custom 19 branch:
https://github.com/rusefi/ChibiOS/tree/stable_19.1.rusefi

Custom 20 branch:
https://github.com/rusefi/ChibiOS/tree/stable_20.3.x.rusefi

http://www.chibios.com/forum/viewtopic.php?f=7&t=5430

See https://github.com/rusefi/rusefi/tree/master/firmware/docs for details

**Comment by rusefi** [comment]
@mck1117 maybe we can even skip 19 and just dive into 20?

**Comment by rusefillc** [comment]
@mck1117 @dron0gus any takers? :)

**Comment by rusefillc** [comment]
@mck1117 any interest? :)

**Comment by rusefillc** [comment]
@chuckwagoncomputing any interest? :)

**Comment by rusefillc** [comment]
@dron0gus reports some progress

**Comment by dron0gus** [comment]
@rusefillc should I close this issue?
