### ISSUE TITLE
Lua: onCanRx parameter value to be use Lua-indexing

### ISSUE THREAD

**Issue by jankovalski** [rusefi/rusefi#7110]
I have a board with two CAN buses physically connected to each other. I’m sending messages from one bus to the other using Lua. While txCan only accepts bus 1 (primary) or bus 2 (secondary), as stated in the wiki, the onCanRx function returns bus 0 (primary) or bus 1 (secondary). Is this expected? Is onCanRx incorrect, or is the wiki wrong?

> bus: Hardware CAN bus index, only '1' on most rusEFI boards, '1' or '2' on Proteus. If this parameter is omitted, messages will be received from any bus.

![lua1](https://github.com/user-attachments/assets/5bf3bd1a-90fd-4ba6-8081-86d994ff3964)
![lua2](https://github.com/user-attachments/assets/bb6c4bb3-e05d-4d30-bbc4-3f66ba1b6f59)

**Comment by rusefillc** [comment]
Technically there are two separate things - index you specify while subscribing to CAN messages, and the way CAN messages are actually provided to you.

See fix https://github.com/rusefi/rusefi/commit/0d87acc8a49ae732fdfc7fc6343e40200b101e98
