### ISSUE TITLE
Clutch switch should be able to be shared by Torque Reduction same as by Launch Control

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#7117]
**Describe the bug**

Launch is smart to reuse clutch

![image](https://github.com/user-attachments/assets/2c9aabd0-e326-4ddc-b253-039298eafd66)

but other dialogs are missing similar - Torque Reduction

**Hardware**
 - Board: h154
 - Engine info bk theta

**To Reproduce**
Set clutch switch as both clutch switch input inside chassis sensors, and as torque reduction input

**Expected behavior**
No error, since the same sensor is used for different functions

**Screenshots**
![image](https://github.com/user-attachments/assets/b9ebc2d6-a787-41b4-95fa-6216385d3e04)

**Comment by rusefillc** [comment]
1) @ElDominio you are in violation of https://en.wikipedia.org/wiki/XY_problem
2) @ElDominio please RTFM

![image](https://github.com/user-attachments/assets/2c9aabd0-e326-4ddc-b253-039298eafd66)

**Comment by ElDominio** [comment]
This works for Launch, does NOT work for shift torque since Clutch Down Switch is not an option @rusefillc

**Comment by ElDominio** [comment]
![image](https://github.com/user-attachments/assets/b9ebc2d6-a787-41b4-95fa-6216385d3e04)
 and this just happened

**Comment by ElDominio** [comment]
XY:

I am trying to share Clutch Input Switch defined in Chassis Sensors to be used for Shift Torque Reduction and Launch Control

**Comment by kifir23917** [comment]
@ElDominio, I have added `Cluch Down Switch` as an `Activation Mode` option on `Shift Torque Reduction (Flat Shift)` dialog

![Image](https://github.com/user-attachments/assets/71598bd8-49b3-4394-9c5f-8abbeb0d40e6)

**Comment by ElDominio** [comment]
Both clutch up and down should be options. Some people use up some people use down

**Comment by kifir23917** [comment]
I have added `Clutch Up Switch` option:

![image](https://github.com/user-attachments/assets/af04d7c4-d762-4dd5-b04d-35e3ab6ffd0a)

**Comment by kifir23917** [comment]
BTW: `Launch Control` doesn't provide `Clutch Up Switch` option for its `Activation Mode`:

![image](https://github.com/user-attachments/assets/c3e3f2d4-24f7-450b-9892-70feba72e713)

Is it OK?

**Comment by ElDominio** [comment]
> BTW: `Launch Control` doesn't provide `Clutch Up Switch` option for its `Activation Mode`:
> 
> ![image](https://private-user-images.githubusercontent.com/159958110/396807646-c3e3f2d4-24f7-450b-9892-70feba72e713.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MDgzNTUsIm5iZiI6MTczNDUwODA1NSwicGF0aCI6Ii8xNTk5NTgxMTAvMzk2ODA3NjQ2LWMzZTNmMmQ0LTI0ZjctNDUwYi05ODkyLTcwZmViYTcyZTcxMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOFQwNzQ3MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNzFkYTIzYTkyM2VjMTkyMzc0YjY5NmQ4ZDFjMTk0NmZiOTBmNWQ1NzM2MGI4ZTVjNDNhMmRlNTVhOTczYmJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.zIIprgsKAZO17wJpSXnIlKhbxHJOT9i3uuz8BcfQQ8I)
> 
> @ElDominio , is it OK?

Should have "Clutch Up Switch"  also selectable

> I have added `Clutch Up Switch` option:
> 
> ![image](https://private-user-images.githubusercontent.com/159958110/396806894-af04d7c4-d762-4dd5-b04d-35e3ab6ffd0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MDgzNTUsIm5iZiI6MTczNDUwODA1NSwicGF0aCI6Ii8xNTk5NTgxMTAvMzk2ODA2ODk0LWFmMDRkN2M0LWQ3NjItNGRkNS1iMDRkLTM1ZTNhYjZmZmQwYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOFQwNzQ3MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kM2FjZWM5MmQ2M2MzYjk0YmFjNTE1YTFhZTg5MmJmMjFkNTczN2I1YThlZWExMGI4NDBiZjIzNzMxMDExMTcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.37J-fcMLQSwI3gBt0fegpWMjlV1pl2L4Fi1c6PhXq2w)

This one is perfect 

"Mode" should be hidden on both Launch and Torque reduction

**Comment by kifir23917** [comment]
> "Mode" should be hidden on both Launch and Torque reduction
@ElDominio, is my understanding correct that we should get rid of `Launch Button Mode` setting on `Launch Control` dialog as well?

![image](https://github.com/user-attachments/assets/8118fc57-f830-4949-8c2a-cd0d2b9e5bfb)

**Comment by rusefillc** [comment]
Related to https://github.com/rusefi/rusefi/issues/6951
