### ISSUE TITLE
STM32F767ZI nucleo USB and Ethernet broken in latest release

### ISSUE THREAD

**Issue by joesphan** [rusefi/rusefi#7118]
**Describe the bug**
It seems that ethernet might be broken in latest release.

**Hardware**
 - Board: STM32F767ZI nucleo bare board

**To Reproduce**
1. Download rusEFI master.2024.11.22.stm32f767_nucleo.4047957739 onto f767 with ethernet
2. plugin ethernet directly to pc and set 192.168.10.10 as ip, 192.168.10.1 as gateway, default netmask 
3. No ping, but TunerStudio connects with 192.168.10.1 port 29000
4. so that is the working version. 
5. if you download latest,  rusEFI master.2024.12.02.stm32f767_nucleo.4278423622
6. repeat the steps, will result in no ping no tunerstudio connection

**Expected behavior**
Ethernet to connect

**Screenshots**
![image](https://github.com/user-attachments/assets/bbcfee23-bdd1-4c08-af10-ba30dfc1073f)
![image](https://github.com/user-attachments/assets/79532e8c-5639-4b29-867d-e5d0f53ecb74)
![image](https://github.com/user-attachments/assets/63bf701f-9d48-4929-8139-8f6756a8f5ac)

**Additional context**

**Comment by joesphan** [comment]
Upon further inspection it looks like the latest release is broken in general. no usb connection either.

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi/issues/6242 is a recent change specifically for that board

**Comment by rusefillc** [comment]
@FDSoftware is your unit affected by this?

**Comment by FDSoftware** [comment]
> @FDSoftware is your unit affected by this?

yep, I have the same issue, later I will try adding a commit reverting 45ac95e

**Comment by joesphan** [comment]
Just spitballing here, it seems like larger flash size might eat into bootloader space, can this be the case?

**Comment by rusefillc** [comment]
revert of 2mb did not help me
I've reverted openblt and things are blinking blue happily

i will now re-apply 2mb without openblt

**Comment by rusefillc** [comment]
2mb re-enabled, things seem to blink as expected

Separate https://github.com/rusefi/rusefi/issues/7124 follow-up ticket for later

**Comment by joesphan** [comment]
X2 Happy to report it works now too
