### ISSUE TITLE
Target AFR blend feature

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#7123]
Users would like to add/remove fuel at a certain temperature such when the bike is too hot in order to quench the motor. With closed loop control that means Target AFR blend feature

**Comment by rusefillc** [comment]
@ElDominio what did you say about having four of these? Do you mean four different tables applied consecutively one by one?

I guess let's start with one configurable for now.

**Comment by benassi124** [comment]
if i recall correctly he wanted essentially a blend table but instead of modifying VE it would be modifying lambda target

**Comment by benassi124** [comment]
@ElDominio It would be nice to also have a target lambda blend table for Ethanol %

**Comment by ElDominio** [comment]
if there is a generic blend table, you can choose your blend parameter as Ethanol%, making it exactly what you ask for

**Comment by rusefillc** [comment]
@ElDominio @kifir23917 https://github.com/rusefi/rusefi/issues/7170

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi/pull/7171

**Comment by rusefillc** [comment]
@kifir23917 do we have any coverage for any blend at all? if not please create a separate ticket
