### ISSUE TITLE
we need TLE8888 driver

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#714]
First step would be to execute Output Enable command

**Comment by rusefi** [comment]
See also https://github.com/dron0gus/rusefi/blob/board-subaru/firmware/config/boards/subaruej20g/board.c#L91

**Comment by rusefi** [comment]
Next chapter is to get smart outputs working. At the moment smart pins are not working

@dron0gus 

![image](https://user-images.githubusercontent.com/7377949/56082371-2d934c00-5de6-11e9-9bd7-bc758cb7065f.png)

**Comment by rusefi** [comment]
Still failing to get 
https://github.com/rusefi/rusefi/blob/master/firmware/config/engines/custom_engine.cpp#L369
to work as expected on a bench

**Comment by rusefi** [comment]
A bit better status
![image](https://user-images.githubusercontent.com/7377949/56092738-b5806100-5e8d-11e9-97a2-d43fc3397cf4.png)

and TLE_20 smart output works now!!!

**Comment by dron0gus** [comment]
FYI: current implementation has a lot of limitations.
Most annoying for now is that driver can not handle TLE8888_PIN_1..4 and TLE8888_PIN_24..27 (direct driven INJ and IGN channels).
Driver knows these are direct drive outputs but has no knowledge which STM pins should be used to control these outputs.
So please use STM native ports when configuring IGN and INJ channels.
Later we should switch to TLE8888_PIN_* if we want to map diagnostic information from chip to smart gpios...

Also we should add TLE8888_PIN_24..27 to enum and extend TLE8888_OUTPUTS to 28.

**Comment by rusefi** [comment]
see #697

**Comment by rusefi** [comment]
direct outputs work, smart pins work - good enough for now :)
