### ISSUE TITLE
RawFlex gauge not working, flexinfo in console works

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#7156]
**Describe the bug**
As  the title says
**Hardware**
 - Board: h154

**To Reproduce**
1. Put raw flex gauge
2. no reading
3. put flexinfo in console
4. 
![image](https://github.com/user-attachments/assets/43d0f52a-30d0-4790-8546-ebe35dd2e89b)

**Expected behavior**
Rawflex shows the same as flexinfo

**Screenshots**
![image](https://github.com/user-attachments/assets/ad318c5c-2f7c-430e-b31a-a81072ac606e)
![image](https://github.com/user-attachments/assets/35cd5bf2-027c-462b-ab44-5144e33add70)

**Additional context**
Tiniest log in the world
[2024-12-12_14.02.10.mlg.zip](https://github.com/user-attachments/files/18115715/2024-12-12_14.02.10.mlg.zip)

**Comment by rusefillc** [comment]
I see that #6949 is still open
