### ISSUE TITLE
CRITICAL: h154 mc33810 max dwell setting is not visible with default value of 2ms, also no warning/error if exceeded

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#7157]
**Describe the bug**
60-2 triggers are advancing on their own. We have seen a drift of more than 40 degrees with timing FIXED at 0

**Hardware**
 - Board: h154 https://github.com/rusefi/hellen154hyundai/

**To Reproduce**
1. Set trigger to 60-2 on a 60-2 car
2. set timing to fixed
3. use timing light to confirm timing
4. timing will drift with RPM

**Expected behavior**
Timing does not drift

**Proposed test* 
may 15, 2023 firmware to start

**Additional context**

[timing locked map.zip](https://github.com/user-attachments/files/18119254/timing.locked.map.zip)

[timingadvanced.zip](https://github.com/user-attachments/files/18119255/timingadvanced.zip)

**Comment by ElDominio** [comment]
https://youtube.com/shorts/LoxhhP2Z2Ts video showing timing drifting

**Comment by rusefillc** [comment]
@ggurov do you have relent bench setup?

**Comment by ElDominio** [comment]
I have removed 74LVC2G17GW
Problem is gone

**Comment by rusefillc** [comment]
@ElDominio plz a photo of what you have removed? Is the any markng on the chip? Location? Ref number?

**Comment by ElDominio** [comment]
U108 and U109

![image](https://github.com/user-attachments/assets/52726261-26bd-49eb-a97a-5845de9aadc0)

**Comment by rusefillc** [comment]
this part is supposed to be protecting inputs same part used all the way back to Proteus see https://github.com/mck1117/proteus/issues/122

Does not @mck1117 run 60/2 Hall GM engine with this input circuitry?

**Comment by mck1117** [comment]
I doubt the veracity of a 40 degree claim while running 60-2. That's more than 6 teeth. How would it drift more than a tooth? Are you sure you have the coil polarity right and you aren't firing the coil when you mean to start charging it?

**Comment by rusefillc** [comment]
@dron0gus could this be F4 vs F7? Could this be https://jlcpcb.com/parts/componentSearch?searchTxt=C94189 vs https://jlcpcb.com/partdetail/Nexperia-74LVC2G17GW125/C80500?

**Comment by mck1117** [comment]
> could this be F4 vs F7?

no

> Could this be C94189 vs C80500?

no

**Comment by mck1117** [comment]
you physically can't get a hardware drift of >1 tooth (or really >0.5 tooth or so)

**Comment by ElDominio** [comment]
> you physically can't get a hardware drift of >1 tooth (or really >0.5 tooth or so)

I mean, the videos are there, the broken engines are there. I did not touch a laptop between the videos

**Comment by ElDominio** [comment]
![image](https://github.com/user-attachments/assets/818e5708-5dbb-4432-9450-be0decd96a95)

**Comment by rusefillc** [comment]
@ggurov has a great proposal: since we've got hall here, do a three ECU bench test!

first ECU is producing whatever signal we need to be produced
second ECU is the "real" ECU
lastly third ECU reads ignition output as VVT and that gives us VVT output data!!!

**Comment by Qwerty-OFF** [comment]
I would like to see the input and output signal simultaneously with an oscilloscope
![image](https://github.com/user-attachments/assets/2ead8482-e7f7-4b62-ab0f-7c46f0a78109)

**Comment by mck1117** [comment]
@ElDominio can you change the dwell and see if your timing changes?

**Comment by rusefillc** [comment]
> @ElDominio can you change the dwell and see if your timing changes?

See also: MC33810 max dwell setting, and MC33810 in general.

**Comment by ElDominio** [comment]
![image](https://github.com/user-attachments/assets/a5f7bcd2-9739-4043-94dd-f563863208dc)

currentdwell settings just inc ase

[tunejustincase.zip](https://github.com/user-attachments/files/18132927/tunejustincase.zip)

**Comment by ElDominio** [comment]
[CurrentTune.zip](https://github.com/user-attachments/files/18137716/CurrentTune.zip)

That is the current untouched tune with locked timing at 0 degrees

[nomodrevE.zip](https://github.com/user-attachments/files/18137720/nomodrevE.zip)

unmodified RevE
first channel is IN 
second channel is OUT
third channel is one of the coil gates

**Comment by ElDominio** [comment]
![image](https://github.com/user-attachments/assets/ffbf5bc8-0f9e-4900-901e-0fb266c39033)

18 teeth in idle

about 3 teeth at higher rpm
![image](https://github.com/user-attachments/assets/9759ac25-ba96-437d-95ea-f337f4c9c8eb)

**Comment by ElDominio** [comment]
i removed the 74 chip, still has an issue
[removed74stillproblem.zip](https://github.com/user-attachments/files/18137817/removed74stillproblem.zip)

i removed all lua, still an issue
[removedluastillproblem.zip](https://github.com/user-attachments/files/18137837/removedluastillproblem.zip)

**Comment by ElDominio** [comment]
With the max dwell setting, firmware should truncate dwell in software too. If a dumb user sets dwell to 10ms and dwell protection is 8ms, they will get advanced timing as a result. Truncating it from software side gives us an additional safety layer that this does happen (i assume mc33810 overdwell is good for truncating dwell if there is an MCU side fuckup)

**Comment by rusefillc** [comment]
@ElDominio yes https://github.com/rusefi/rusefi/issues/7174

**Comment by rusefillc** [comment]
also https://github.com/rusefi/rusefi/commit/302250d8d4a3c4383d436dc31885a3437cd7780d
