### ISSUE TITLE
Add Lua hook for Shift Cut Torque Reduction request

### ISSUE THREAD

**Issue by ElDominio** [rusefi/rusefi#7160]
**Is your feature request related to a problem? Please describe.**
I would like to be able to set Shift Cut Torque Reduction request

**Would we need new configuration fields?**
Add "Lua" as a request input, basically in the list in the screenshot

**Describe the solution you'd like**
Add an option that says "Lua" that can be set from Lua

**Additional context**
![image](https://github.com/user-attachments/assets/1abc5d75-6f4c-42f4-8dee-f98d68a630cc)

**Comment by rusefillc** [comment]
Somewhat related https://github.com/rusefi/rusefi/issues/7117

**Comment by kifir23917** [comment]
@ElDominio, I decided not to add new item to `Activation Mode` combobox and to implement `setTorqueReductionState` Lua hook with approach that is already used for `Clutch Down Switch` and `Brake Pedal`:
`setTorqueReductionState` Lua hook will turn on/off Shift Torque Reduction only when corresponding pin is NONE. If corresponding pin is valid, it will override state configured with `setTorqueReductionState` Lua hook.

**Comment by kifir23917** [comment]
@ElDominio, `setTorqueReductionState` works only when `Activation Mode` is `Torque Reduction Button` and `Torque Reduction Button` is `NONE`.

![image](https://github.com/user-attachments/assets/b2a92d0a-64f5-4af4-b620-51bece4f191d)

**Comment by jankovalski** [comment]
BUG:
If:
`Activation Mode` is `Torque Reduction Button`
and
`Torque Reduction Button` is `NONE`.

Means lua hook is possible but `Settings` are grayed out!
![image](https://github.com/user-attachments/assets/696b5ff2-0a13-495c-9be3-8a08bbbdb448)

**Comment by rusefillc** [comment]
@jankovalski please create a separate issue
