### ISSUE TITLE
target AFR load axis usability

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#7183]
We need nice dynamic name  like "map, kpa, tps % etc" for Y/load axis instead of afrTargetyaxis

somewhat similar to #7182

![image](https://github.com/user-attachments/assets/bd0cfa84-f2de-4142-9c2b-ecea7259d17b)

**Comment by rusefillc** [comment]
@ElDominio please approve

**Comment by ElDominio** [comment]
Correctc. Anything configurable should reference the chosen configuration
