### ISSUE TITLE
1KHz logging

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi#7202]
Sometimes we want to focus on specific problems, how can we data log 1KHz and more?

all datapoints: X1 rate
only two datapoints: X2 rate?

**Comment by rusefillc** [comment]
scatter

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi/commit/5d5fcf0460832edbf049f17be0486099cde4b74b

**Comment by rusefillc** [comment]
ts_protocol.txt
#define TS_GET_SCATTERED_GET_COMMAND '9'

**Comment by kifir23917** [comment]
It looks like we could get near 1KHz logging with [11.2.3 Full Optimized - High Speed](https://www.efianalytics.com/TunerStudio/docs/EFI%20Analytics%20ECU%20Definition%20files.pdf) `OutputChannel Capture`  mode, if we limited number `Logged fields`:

![Image](https://github.com/user-attachments/assets/b064c18a-d317-44f6-9962-3b8925e4cd49)

To enable `Full Optimized - High Speed` mode we need to:
- revert commit [484c5be](https://github.com/rusefi/rusefi/commit/484c5bea5ac59316b06591738638821d40e1bbdd) in `rusefi_hd81.ini` file (you can find my file in archive
[rusefi_hd81 (scattered_mode).zip](https://github.com/user-attachments/files/18254156/rusefi_hd81.scattered_mode.zip) and 
- select patched file as `Other / Browse` `Firmware`:
![Image](https://github.com/user-attachments/assets/8ccdcfe7-4ecf-4927-8be7-1ee6bb6d3d00)
- select `Slower / Wireless` `Protocol Profile`:
![Image](https://github.com/user-attachments/assets/82a312b1-5ebd-41fc-8da0-b3d7fc5ff893)

As result we receive log file with near 1KHz frequency, that can be found in archive [2024-12-26_18.51.44-rpm+uptime (scattered_mode).zip](https://github.com/user-attachments/files/18254226/2024-12-26_18.51.44-rpm%2Buptime.scattered_mode.zip)

**Comment by rusefillc** [comment]
@kifir239 please create '1khz' test branch

**Comment by kifir23917** [comment]
It looks like we could get near 1KHz logging with [11.2.3 Full Optimized - High Speed](https://www.efianalytics.com/TunerStudio/docs/EFI%20Analytics%20ECU%20Definition%20files.pdf) `OutputChannel Capture`  mode, if we limited number `Logged fields`:

![Image](https://github.com/user-attachments/assets/b064c18a-d317-44f6-9962-3b8925e4cd49)

I've enabled `Full Optimized - High Speed` mode in [test-scattered-get-enabled](https://github.com/rusefi/rusefi/tree/test-scattered-get-enabled) test branch.

**Comment by kifir23917** [comment]
This functionality was turned off nine months ago because users met some unwanted side-effects because scatter table is located on the same page with the settings.
