### ISSUE TITLE
generate_memory_usage_report/gcc_map_reader BUG?

### ISSUE THREAD

**Issue by andreika-git** [rusefi/rusefi#721]
Current version of java_tools/gcc_map_reader shows only partial RAM usase.
Example MAP file:
[rusefi.map.zip](https://github.com/rusefi/rusefi/files/3025289/rusefi.map.zip)
The output of gcc_map_reader:
[buggy_ram_report.txt](https://github.com/rusefi/rusefi/files/3025292/buggy_ram_report.txt)
The complete (correct) RAM usage report generated by "AMAP" software:
[correct_ram_report.txt](https://github.com/rusefi/rusefi/files/3025294/correct_ram_report.txt)
The first problem is gcc_map_reader doesn't process .data section (DATA_RAM), only .bss section is processed.
The second problem is gcc_map_reader doesn't even parse ALL .bss fields! For example, this one is missing: .bss.ch_idle_thread_wa (1552 bytes).

**Comment by rusefi** [comment]
Just fixed the second problem - missed ch_idle_thread_wa

**Comment by rusefi** [comment]
Good enough now?

**Comment by rusefi** [comment]
В самом начале .map файла идут "Discarded input sections", т.е. всё, что там перечислено, gcc решил в целях оптимизации не размещать в памяти. У них всех нулевые адреса. Их нужно игнорить. А "правильные" поля идут уже ниже, после "Linker script and memory map"

**Comment by rusefi** [comment]
@andreika-git is this good enough to close ticket?

**Comment by andreika-git** [comment]
Yes!
