### ISSUE TITLE
defined(__DOXYGEN__) ?

### ISSUE THREAD

**Issue by andreika-git** [rusefi/rusefi#748]
Do we really need a defined(__DOXYGEN__) everywhere?
There are some #ifs without it.
hardware.cpp:
#if EFI_MAP_AVERAGING
#if HAL_USE_ADC
#if EFI_HISTOGRAMS
#if EFI_INTERNAL_FLASH
#if EFI_CAN_SUPPORT
etc.

**Comment by rusefi** [comment]
at the moment for example https://rusefi.com/docs/html/hardware_8cpp.html is very limited

![image](https://user-images.githubusercontent.com/7377949/56066775-d5593d00-5d46-11e9-8ec0-7188d0bfb121.png)

trying to change some magic options...
