### ISSUE TITLE
cj125 and hip125 and else SPI broken with chibi18 migration

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#757]
```
static SPIConfig cj125spicfg = { /* end_cb */ NULL,
	/* HW dependent part.*/
		/* ssport */ NULL, /* sspad */ 0, /* cr1 */ SPI_CR1_MSTR | SPI_CR1_CPHA, /* cr2*/ 0 };
```
chibi18 has added circular so everything has shifted

@andreika-git @darxfame @mck1117 how come we did not notice?

**Comment by andreika-git** [comment]
It's just a "warning: initialization from incompatible pointer type" in pure arm-elf-gcc C compiler :(

**Comment by rusefi** [comment]
actually we can make it an error, i am working on it. its explicitly set to noerror right now
