### ISSUE TITLE
Frankenstein "project_name-cache.lib" file

### ISSUE THREAD

**Issue by Old-Grey6** [rusefi/rusefi#763]
Is there a "project_name-cache.lib" file with the original Frankenstein KiCad project?

There is none on the GIT, and I'm told it's something that I needed to remap symbols.

Thanks

**Comment by rusefi** [comment]
@Old-Grey6  Just added

In light of all the KiCAD migration drama I see that we should start merging those more often than not.

**Comment by Old-Grey6** [comment]
Well that fixed it.

Here I am swearing at the KC4 to KC5 migration, and it was just a missing file.

I opened the SCH, it remapped, and now it’s all working. Simple and no effort at all.

Happy as Larry now. :slightly_smiling_face:
