### ISSUE TITLE
USB and TLE8888 not working for F4 or F767

### ISSUE THREAD

**Issue by 960** [rusefi/rusefi#764]
With current configuration, I can not get USB to connect, and not TLE8888 to work.

I did this to get USB back working, but still no TLE8888 working.

#define BOARD_TLE6240_COUNT         0

**Comment by rusefi** [comment]
@960 yes, there is an issue here. trying to fix it.

**Comment by rusefi** [comment]
problem with PD8 pin used by joystick.

No idea how is this related to SPI pins so far

![image](https://user-images.githubusercontent.com/7377949/56432416-40e96000-629b-11e9-98c7-0bdf56610a4f.png)

**Comment by rusefi** [comment]
With some changes now we are at

![image](https://user-images.githubusercontent.com/7377949/56439484-3c7d7100-62b4-11e9-8768-27db218afbde.png)

**Comment by rusefi** [comment]
@dron0gus finally getting to something interesting

![image](https://user-images.githubusercontent.com/7377949/56446326-106fe900-62d0-11e9-9eb9-894229fc2cf5.png)

**Comment by 960** [comment]
Have you found why TLE8888 isn't working?

**Comment by rusefi** [comment]
It's a bit of a hot mess - turned out that ICU/PAL migration had issues, also continues integration had issues :( a bit of everything. in the end default firmware now has 8888 enabled

**Comment by rusefi** [comment]
@960 I believe this is now resolved
TLE8888 is now enabled in default firmware
