### ISSUE TITLE
BURN via serial USART disconnects TS

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#766]
TunerStudio integration can run over USART serial or over build-in serial-over-USB (microUSB port on the bottom of the stm32f4disvovery)

native USB connection survives BURN while uart disconnects :(

See https://rusefi.com/forum/viewtopic.php?f=5&t=1545

**Comment by rusefi** [comment]
See also #6

a work-around for this issue would be to get faster BURN which would not freeze rusEfi - this would require hardware changes

**Comment by mck1117** [comment]
I don't think this happens any more, TS channels have been completely rewritten
