### ISSUE TITLE
input mode control and other pin mode control

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#767]
we still have too much pin modes hard-coded in board.h file

also recent ICU to PAL input trigger conversion might have introduced new issues in this area

**Comment by rusefi** [comment]
See https://rusefi.com/forum/viewtopic.php?p=32767#p32767

**Comment by rusefi** [comment]
@dron0gus we need dynamic pin configuration for EXTI inputs
please make trigger_input more consistent with joystick which 
a) configures pin for input
b) marks it used as a consequence of that

**Comment by rusefillc** [comment]
description too vague and too much has changed since 2020
