### ISSUE TITLE
All corrections should be ratio, 1.0 = no correction 

### ISSUE THREAD

**Issue by OrchardPerformance** [rusefi/rusefi#773]
"IAT fuel", "Cranking TPS" and "Cranking CLT" are decimal multipliers while "Warmup Fuel Manual multiplier" and "Warmup Idle multiplier" are % values.

% values need changing to ratio so that "no correction" is always "1.0"

**Comment by rusefi** [comment]
TODO at least one curve displays 100 instead of 1 for ratio

![image](https://user-images.githubusercontent.com/7377949/56622300-74aae980-65fd-11e9-8116-747464ec8925.png)


FYI @mck1117

**Comment by rusefi** [comment]
@mck1117 poke :)

**Comment by rusefi** [comment]
See also #811

**Comment by rusefi** [comment]
@mck1117 I would like to state for the record that a month ago I've poked and I was hoping to get at least _some_ response within a month.

**Comment by rusefi** [comment]
Thank you @mck1117  for the patience, great change!

**Comment by mck1117** [comment]
I think this can close

**Comment by rusefi** [comment]
@mck1117 says
```
The conclusion with ratio vs. % was that the generator tool needs to be able to emit things like:
```#if USE_PERCENT
    cltFuelCorr                        = array, F32,    10336,    [16],    "%", 100, 0, 0.0, 500.0, 0
#else
    cltFuelCorr                        = array, F32,    10336,    [16],    "ratio", 1, 0, 0.0, 5.0, 2
#endif```
```
