### ISSUE TITLE
idle using ETB

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#783]
we need ETB implementation of idle control

**Comment by 960** [comment]
What is the status of this?

**Comment by rusefi** [comment]
First version of done of ETB idle control but not tested on any real hardware.

"use ETB for idle" is used to enable target ETB adjustment for idle RPM purposes, and "ETB Idle range" is the maximum TPS percentage to control idle.

"ETB Idle range" value of 5 is my random guess for this setting.

**Comment by rusefi** [comment]
See #835 for debug mode "ETB Logic" info
