### ISSUE TITLE
NA6 pnp: automatic idle VS TPS

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#800]
manual NA6 has no TPS potentiometer only TPS switch

automatic idle logic has idlePidDeactivationTpsThreshold

need to set the right switch and potentially adjust idle logic to use switch input

**Comment by mck1117** [comment]
Why not just wire the switch to the TPS input with a pull up(or down) resistor in the ECU?  That will let you use the TPS threshold normally.

**Comment by stefanst** [comment]
Seems to work with pullup and Voltage imput. Can be closed.
