### ISSUE TITLE
Kg/H airflow gauge displays incorrect value

### ISSUE THREAD

**Issue by OrchardPerformance** [rusefi/rusefi#801]
Tuner studio "Air Flow" gauge reads roughly half of the value in the MAF transfer table. This is consistent throughout the range of the MAF. 

![image](https://user-images.githubusercontent.com/49926376/57985625-7a5fe780-7a62-11e9-9570-dd52427288c6.png)

**Comment by OrchardPerformance** [comment]
10kg/h on the table reads 6.1kg/h on the gauge
100kg/h on the table reads 56.4kg/h on the gauge
500kg/h on the table reads 250.6kg/h on the gauge

So it looks like the MAF kg/h value is being halved somewhere.

**Comment by mck1117** [comment]
Can I propose we also switch to g/s instead of kg/hr? SI base units are much preferable to hours.

**Comment by OrchardPerformance** [comment]
kg/h is industry standard for air flow, the majority of MAF transfer functions will be in kg/h. 
It also helps hide any inaccuracy of the measurement values the user inputs, being 0.1kg/h out is only 0.027g/s but 0.1g/s is 0.36kg/h so rounding or interpolation errors are exaggerated.

**Comment by mck1117** [comment]
> so rounding or interpolation errors are exaggerated

That's not necessarily the case - we use floating point internally, so we get ~9 digits of decimal precision.  No rounding happens until the very end when we convert to a pulse width, and even then, that's in microseconds, so we still get 4 or 5 significant digits.

That said - it does help the user not screw it up by getting the conversion wrong if they have kg/h handy already.

**Comment by OrchardPerformance** [comment]
I was thinking more the kind of rounding a user would do when copying out of an excel sheet or typing it in badly. :) 

I agree if its going to already be in kg/h from their spec sheet or OEM calibration then that's a good reason not to alter it.

**Comment by OrchardPerformance** [comment]
Things appear to be working since Matt's fix, I have tested it in my MAF branch and its  reading perfectly now.

**Comment by mck1117** [comment]
For sake of accurate record keeping, that was #880
