### ISSUE TITLE
tle8888 driver bug

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#803]
@960 reports a crash in
<img width="960" alt="stm32cubeide_51a64fw5pu" src="https://user-images.githubusercontent.com/7377949/58373380-576a8300-7efb-11e9-95d4-72c3c5be3917.png">

```
	if (isIsrContext()) {
		// this is for normal runtime
		int wasLocked = lockAnyContext();
		chSemSignalI(&tle8888_wake);
		if (!wasLocked) {
			unlockAnyContext();
		}
	} else {
		// this is for start-up to not hang up
		chSemSignal(&tle8888_wake);
	}
```

**Comment by rusefi** [comment]
@dron0gus  I wonder if we do not need the whole "isIsrContext()" check, can we just always use top branch of code?

**Comment by dron0gus** [comment]
@rusefi top branch was proposed by you. As a fix when this code is called from interrupt context.
Will in work for normal context?
As far as I understand from ChibiOS manuals, chSemSignal**I** will not call reschedule. It is ok for interrupt context, as re-schedule will happen on interrupt exit.
But when this code is called from normal context?

**Comment by rusefi** [comment]
@960 please remind me what are steps to reproduce?

**Comment by rusefi** [comment]
@mck1117 un-doing the fix since the fix breaks other things

![image](https://user-images.githubusercontent.com/7377949/59153613-69840f80-8a2b-11e9-8f40-880c52dceba0.png)


![image](https://user-images.githubusercontent.com/7377949/59153612-625d0180-8a2b-11e9-843f-1f045a105ed6.png)

**Comment by rusefi** [comment]
this is on start up, wonder how come this worked for you with @960 while your testing?

![image](https://user-images.githubusercontent.com/7377949/59153616-7e60a300-8a2b-11e9-8beb-105678bbf401.png)

**Comment by 960** [comment]
The boards I had did not run at all after some firmware changes today.
Maybe this change. 
Tried with tree different boards, with different designs.
Full crash for all, dont even boot.

**Comment by 960** [comment]
The tune that bricks it:

[Audi_A4_Alt.zip](https://github.com/rusefi/rusefi/files/3269099/Audi_A4_Alt.zip)

**Comment by mck1117** [comment]
is this issue now fixed?

**Comment by rusefi** [comment]
I assume this was resolved somewhere
