### ISSUE TITLE
"Calibrate TPS" broken in TS

### ISSUE THREAD

**Issue by 960** [rusefi/rusefi#805]
TS depends on TPS channel being named exactly "tpsADC"
with recent rename in order to add 2nd TPS, Calibrate TPS standard TS button got broken

JRD McLAREN reports probably same at https://rusefi.com/forum/viewtopic.php?f=5&t=1581&e=1&view=unread#p33454

AbricosVW reports same issue with a very nice error report video https://www.youtube.com/watch?v=Fq7GN1JaKng

**Comment by rusefi** [comment]
By popular demand I have to fix it.
