### ISSUE TITLE
EFI_IDLE_INCREMENTAL_PID_CIC should be a runtime parameter

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#806]
little point in having business logic defined at compile time in my opinion, EFI_IDLE_INCREMENTAL_PID_CIC should be a runtime parameter as anything else

**Comment by andreika-git** [comment]
Note that PidCic uses 128 bytes more of RAM! That's why it was defined at compile time...

**Comment by rusefi** [comment]
@andreika-git can you please PR some additional English documentation for PID_CIC idle?
