### ISSUE TITLE
re-fork https://github.com/ChibiOS/ChibiOS

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#820]
@fpoussin says "FIY I had to rebuild the https://github.com/ChibiOS/ChibiOS repo. you'll have to re-clone it, branches names are similar but commit ids are different."

**Comment by fpoussin** [comment]
Hold on a little for that, I might be able to save the old mirror after all.

**Comment by fpoussin** [comment]
You can close it, no need to re-fork. :)

**Comment by mck1117** [comment]
can we close this?
