### ISSUE TITLE
We need GP-Pwm maps in TS

### ISSUE THREAD

**Issue by 960** [rusefi/rusefi#843]
We need six GP-Pwm maps with selectable axis in TS.

**Comment by rusefi** [comment]
Please split into individual tickets - at the moment looks like multiple requests are mixed together.

Also need WAY more detailed description of the desired functionality.

**Comment by 960** [comment]
<img width="960" alt="YqOJQG8a4J" src="https://user-images.githubusercontent.com/9406140/59554521-6d241300-8fa4-11e9-8b21-2a2fb3065098.png">

**Comment by 960** [comment]
This is a example of a GP-PWM map.

I can split it up.

**Comment by rusefi** [comment]
Related to #811

**Comment by rusefi** [comment]
See also https://rusefi.com/forum/viewtopic.php?f=5&t=1597
