### ISSUE TITLE
ADC issue on F7

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#854]
@mck1117 believes that the ADC issues @960 has originally reported are related to F7 memory caching mechanism:

@mck1117 says here's how the ADC works:
1) timer triggers ISR which starts the ADC, writing to DMA
2) ADC generates samples, DMA controller copies them to SRAM
3) "ADC is done" interrupt fires, CPU reads values from SRAM, averages, and writes back in to sample buffer
on an f7, there's an extra half step
step 2b) is that the DMA controller DOES NOT notify the CPU cache that it should invalidate those cache lines
so in step 3), if you get cache hits, you read old numbers

**Comment by rusefi** [comment]
@mck1117 @960 @andreika-git @dron0gus 

Here is ChibiOS code
```
/* TRUE means that DMA-accessible buffers are placed in a non-cached RAM
   area and that no cache management is required.*/
#define DMA_BUFFERS_COHERENCE TRUE


#if !DMA_BUFFERS_COHERENCE
/* Note, the buffer is aligned to a 32 bytes boundary because limitations
   imposed by the data cache. Note, this is GNU specific, it must be
   handled differently for other compilers.
   Only required if the ADC buffer is placed in a cache-able area.*/
#if defined(__GNUC__)
__attribute__((aligned (32)))
#endif
#endif
static adcsample_t samples1[ADC_GRP1_NUM_CHANNELS * ADC_GRP1_BUF_DEPTH];


size_t nx = 0, ny = 0;
static void adccallback(ADCDriver *adcp, adcsample_t *buffer, size_t n) {

#if !DMA_BUFFERS_COHERENCE
  /* DMA buffer invalidation because data cache, only invalidating the
     half buffer just filled.
     Only required if the ADC buffer is placed in a cache-able area.*/
  dmaBufferInvalidate(buffer,
                      n * adcp->grpp->num_channels * sizeof (adcsample_t));
#else
  (void)adcp;
#endif
```

I believe it would make more sense for us to flip the meaning of this variable and have it like

#define EFI_NEED_DMA_BUFFERS_PROTECTION TRUE

Opinions?

**Comment by 960** [comment]
I tested with 

#define DMA_BUFFERS_COHERENCE TRUE

today.

Nothing at all on the board works, and I get Fatal error after about 20 seconds..
