### ISSUE TITLE
Reduce RAM usage for 16x16 configuration tables

### ISSUE THREAD

**Issue by abelom** [rusefi/rusefi#868]
Too many of our tables are 16x16x4, some of those should be reduced to 16x16x2 or even 16x16x1 to free up some RAM for new additional tables

**Comment by abelom** [comment]
This is required for #866

**Comment by mck1117** [comment]
Another option is to eliminate some of the "x axis" tables for temperature compensation.  For example, CLT fuel multiplier and CLT idle multiplier can probably use the same table for temperature.

**Comment by rusefi** [comment]
@mck1117 absolutely, but 16x16 are probably the best cost/benefit deals

**Comment by OrchardPerformance** [comment]
Small one but frees ram for other tables that are needed for flex fuel and table blending.

**Comment by rusefillc** [comment]
relates to #3193

**Comment by rusefillc** [comment]
@mck1117 done right?
