### ISSUE TITLE
CAN not working with new MRE setup

### ISSUE THREAD

**Issue by 960** [rusefi/rusefi#869]
Not sure where the issue are(HW/SW), but I cant get CAN working now.

I have tried all possible settings, can sniffer and logic analyzer.

With can sniffer, there are nothing.

With logic analyzer I see traffic at CAN L, but nothing at CAN H.

Tested at two boards to validate.

**Comment by mck1117** [comment]
What does the signal look like on CANL?

**Comment by 960** [comment]
It's a logic signal that looks rational.

Just looked thru mcuconf.h for F767, and it does not look like we have can enabled.
Tried to add this, but still not working.

#define STM32_CAN_USE_CAN1                  TRUE
#define STM32_CAN_USE_CAN2                  TRUE

**Comment by rusefi** [comment]
@960 something seems wrong. Please paste exact github URL which you believe does not have CAN.

**Comment by 960** [comment]
I had looked in wrong file.

So, I am back to having no idea at all what could be wrong

**Comment by 960** [comment]
Can this be related to F7 having different speed, and wrong prescaler?

**Comment by rusefi** [comment]
@960 I think yes, it could be related to speed and prescaler

**Comment by mck1117** [comment]
I've confirmed with scope that F7 CAN is running 29% too fast, 1.29 = 216mhz/168mhz

**Comment by 960** [comment]
When I connect a instrument cluster at bench now, the read counter in TS starts counting.

No output at all still.
Nothing at can-sniffer.

The send counter in TS goes to 3 at startup, and thats it.

**Comment by mck1117** [comment]
@rusefi I'm not sure this is closed, he hand applied #872 and that didn't seem to fix it

**Comment by 960** [comment]
Still not working.

Do you capture anything at the MRE output?

**Comment by 960** [comment]
Now it's finally solved.

It was actually a bit more complicated..

**Comment by rusefi** [comment]
@960 so what was it?

**Comment by rusefi** [comment]
https://rusefi.slack.com/messages/C4P8TSCJF/details/ says we have no idea what was wrong (if anything?) on top of scaling
