### ISSUE TITLE
Cranking base fuel should be taken from fuel map

### ISSUE THREAD

**Issue by 960** [rusefi/rusefi#870]
The cranking base fuel pulse width setting should be removed, and the pulse width should be the same as output from fuel-map.

This way, all enrichments have one common base-factor.

Cranking enrichment, post-start enrichment and warmup enrichment will go seamless. 

All of the correction/enrichment maps will be % of normal fueling.

I am used to working with ratio/multiplier myself, but only in OEM who are quite different.
In a aftermarket ecu this mix will just make mess and confusion, so % all over are way better.

**Comment by OrchardPerformance** [comment]
We have an option for this? 
Does it work?

**Comment by 960** [comment]
Hi!

It works just right, 100%.

Closing
