### ISSUE TITLE
VVT support for VAG trigger

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#883]
@960 is asking for a new VVT trigger. Tooth shape is available at https://rusefi.com/forum/viewtopic.php?f=5&t=1602

VVT trigger system overall could use some refactoring to reduce code duplication with normal trigger

**Comment by 960** [comment]
Are there any progress on this?

**Comment by rusefi** [comment]
http://www.maxxecu.com/webhelp/trigger_system-vw_18t_cam.html

**Comment by mck1117** [comment]
I think this is the same as #1368

**Comment by 960** [comment]
I still havent got this working..

Tried every setting with inverted etc..

Usually it only shows vvt position of 0, but sometimes it shows a large value of 9xx.
Only a static value.

I am just controlling VVT to two positions (on/off) based on rpm, but would be cool to have it working

**Comment by rusefillc** [comment]
hard to test without tune on rusEFI online, could also he a HW issue

**Comment by 960** [comment]
Hw input looks good in both Logic analyzer and Logger:

![image](https://user-images.githubusercontent.com/9406140/101665184-f78bec80-3a4c-11eb-8ad5-c20fbeb84df4.png)

**Comment by rusefillc** [comment]
VVT tuning usability is a mess, hard to tell without your tune on rusEFI online
