### ISSUE TITLE
Hello World project for TMS570

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#89]
We need a hello world application for TMS570 platform - something with LED blinking, serial console & ADC input probably.

Probably FreeRTOS? Need to figure out TI HAL wizard

Reported by: rusefi

**Comment by rusefi** [comment]
Definitions
LAUNCHXL2-TMS57012 is an automotive-grade microcontroller family based on ARM Cortex - see http://www.ti.com/product/tms570ls1224

LAUNCHXL2-TMS57012 inexpensive evaluation board containing TMS570LS1224 (main MCU) and TM4C129 (TODO#1 - what is the role of TM4C129)?

Code Composer Studio (CCS) is an IDE. It's an Eclipse extension with bundled proprietary TI optimized compiler (TODO#2 - is this true?)

CCS is free as long as we are using a Launchpad board OR XDS100 debug probe - looks like this really works for us?! See http://processors.wiki.ti.com/index.php/Licensing_-_CCSv6#Free_Licenses

Blinky
http://processors.wiki.ti.com/index.php/LAUNCHXL2_TMS57012:_Project_0

**Comment by dron0gus** [comment]
TODO1: TM4C129 implements on-board debugger.

**Comment by mck1117** [comment]
close as probably not important?
