### ISSUE TITLE
Internal trigger simulator shouldn't be stored in persistent config

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#897]
Suppose an unsuspecting user (in this case, me) does the following:

1) Plug ECU in on the bench, activate self stimulation to investigate why the injectors aren't firing.
2) Finds & fixes the problem.
3) Plug ECU in to car, turn on ignition. Injectors and coils start firing, what's going on?

I propose that we move "enable self stimulation" to be a button on the "Bench Test" page, instead of a persistent setting that's flashed to the controller.

**Comment by rusefi** [comment]
board testing firmware is a special case but up for debate if even it should be persisted. maybe there should be two ways - more visible "enable temporary self stimulation" and more hidden persisted self stimulation

**Comment by mck1117** [comment]
I did it again yesterday :grin:

I plugged the ECU in to the car, turned the key to on, and heard a lot of injector clicking...

**Comment by mck1117** [comment]
+1 for users who've been tripped up by this...

**Comment by rusefi** [comment]
Jimmy lunztel was confused by a board in QA configuration

**Comment by mck1117** [comment]
+1 for this happening to a user.  Happened again.

**Comment by mck1117** [comment]
And one more.
