### ISSUE TITLE
make iTerm limits visible for idle RPM pid 

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#913]
We kind of have iTerm limits on ETB as a bit of a lazy hack.

There is a desire to enable similar hack to idle as well

**Comment by andreika-git** [comment]
Also please note that this doesn't affect EFI_IDLE_INCREMENTAL_PID_CIC configurations (e.g. Prometheus and Subaru-EJ20G boards), so it's still safe to use the old settings for them.
