### ISSUE TITLE
TLE8888 still does not start reliably

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#916]
NB2 real vehicle tests show that current TLE8888 start-up code is only successful sometimes.

Open question if logic changes are needed or longer timeouts.

**Comment by mck1117** [comment]
This may be a potential dupe of #904.  @rusefi do you have a real oscilloscope you can probe the +12v rail with while cranking?

**Comment by rusefi** [comment]
@mck1117  I have DSO Quad which I am not too comfortable with

@abricosvw has a Rigol which I might be able to borrow

**Comment by rusefi** [comment]
See relevant change #918

**Comment by mck1117** [comment]
is this fixed?

**Comment by rusefi** [comment]
Maybe probably
