### ISSUE TITLE
instant RPM for idle control

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#925]
@stefanst is wondering if one of the ways to improve idle control would be to use instance RPM value instead of current per-cycle RPM value

There is a chance that per-cycle RPM takes too long to refresh and we are loosing valuable time

**Comment by stefanst** [comment]
Correct. On a 1.6l Miata engine, coming off of 2000rpm, free-revving, we have 3 full crankshaft revolutions from rpm>1000 (which is the target) to a stalled engine. The "I" factor has only 2-3 true iterations to adjust.

**Comment by rusefi** [comment]
Reminder that we have "INSTANT_RPM" debug mode which allows to monitor that instant RPM value vs "regular" RPM which is currently used more often

**Comment by mck1117** [comment]
We use instant RPM already for closed loop idle timing correction, which is the part that really matters.

**Comment by OrchardPerformance** [comment]
@mck1117 - Can this be closed? Do you feel we have resolved this one?

**Comment by mck1117** [comment]
this is well past fixed, and instant rpm wasn't even the problem.
