### ISSUE TITLE
very few SD cards work

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#942]
Do we have any bugs in SD card layer?

looks like only ONE SD card is reliable on my Frankenso via SPI
one shows sporadic writes, most never write
maybe need to lower SPI speed or fix some defect

**Comment by rusefi** [comment]
https://sourceforge.net/p/chibios/bugs/530/ is part of life

**Comment by stefanst** [comment]
This seems to have been dis-proven. Close?
