### ISSUE TITLE
HardFault related to auto r = convertFromInputValue(inputValue);

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#948]
I have a discovery with old and probably invalid configuration

I've flashed it with current firmware

First I get a fatal error
![image](https://user-images.githubusercontent.com/7377949/65397740-8ea15180-dd80-11e9-9266-f4f1b9c3b9b8.png)

But we kind of expect to handle all fatals so that at least console is up and running and we can read fatal error message and fix configuration.

But next I get:
![image](https://user-images.githubusercontent.com/7377949/65397725-716c8300-dd80-11e9-9326-9e08bc9f52b2.png)

**Comment by rusefi** [comment]
@mck1117 please advise

**Comment by rusefi** [comment]
@mck1117 

![image](https://user-images.githubusercontent.com/7377949/65398922-f4450c00-dd87-11e9-8a5a-7de83bba53b5.png)

**Comment by rusefi** [comment]
@mck1117 attached are my _current_ .map and .elf files. NOT matching  affected tag

https://github.com/rusefi/rusefi/commit/344919a60b4ea2f3745e5fdfa786701e943ff82e

I hope this version is still affected. Let me know if it's not and I will roll back to https://github.com/rusefi/rusefi/commit/344919a60b4ea2f3745e5fdfa786701e943ff82e and compile it

**Comment by mck1117** [comment]
The bug is that `ltoa_internal` would always write the next 11 bytes, even if the buffer wasn't that long (which it didn't know).

I've rewritten `ltoa_internal` so that it doesn't write any more than it needs to in the output buffer, using a stack buffer instead of the destination for intermediate scratch work.
