### ISSUE TITLE
how do we plan to use flash

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#951]
Do we have a plan for IS25LP256D on MRE?

See m25q.h in ChibiOS
See hal_jesd216_flash.h in ChibiOS
See jesd216

**Comment by rusefi** [comment]
See http://www.chibios.com/forum/viewtopic.php?f=38&t=3320&start=10

**Comment by rusefi** [comment]
![image](https://user-images.githubusercontent.com/7377949/65823849-fac20080-e22b-11e9-833a-d2a7f0d10f78.png)

ChibiOS seems to have a driver for N25Q128 

![image](https://user-images.githubusercontent.com/7377949/65823853-07deef80-e22c-11e9-9137-e2c8669975f7.png)

**Comment by rusefi** [comment]
"Changed the m25q -> s25f for use with Cypress S25FL116/132/162 Flash Devices."

**Comment by rusefi** [comment]
See also https://github.com/vooon/chibios-flash
See also https://github.com/nimaltd/w25qxx

**Comment by mck1117** [comment]
we don't, because we've stopped putting it on boards in lieu of SD card
