### ISSUE TITLE
absolute fuel pressure flow calculation

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#954]
Initially rusEfi only supported "map referenced" flow rate - i.e. fuel rail pressure follows manifold pressure (vacuum line into fuel regulator is part of mechanical setup)

Some vehicles like US Miata NB2 have absolute fuel pressure setup - i.e. no vacuum line to regulator and constant fuel pressure.

We shall add "absolute fuel pressure" mode with fuel system pressure configuration setting.

**Comment by rusefi** [comment]
http://performancefuelsystems.com/InjectorFlowRatesatDifferentPressures-TechCorner.htm

**Comment by rusefi** [comment]
Nice write-up at https://rusefi.com/forum/viewtopic.php?f=5&t=1636

**Comment by mck1117** [comment]
This mode is now working and set to the default on the NB miata tune.
