### ISSUE TITLE
Many tests depend on working fuel math

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#959]
Why does `misc.testRpmCalculator` fail if fueling math doesn't return the correct value?

**Comment by rusefi** [comment]
because unit tests are pretty much really not unit tests but integration tests

**Comment by mck1117** [comment]
that's exactly why I filed the bug

we need unit tests

**Comment by mck1117** [comment]
The problem is that when you change something - completely unrelated tests start failing.

Unit tests should rely on mocks to test only one part of the system.

Integration tests can't rely on mocks, as they need to test the system as a whole.

**Comment by rusefi** [comment]
I agree completely but in my opinion this is totally unrealistic.

**Comment by mck1117** [comment]
Why is that unrealistic?

**Comment by mck1117** [comment]
Let me ask the question that prompted this:

Suppose I change how some system works (clt/iat sensors, for example).  Unrelated tests start failing.  What do?

**Comment by rusefi** [comment]
I believe that the benefits do not justify the investments. It is my opinion that while so little firmware progress is done, it would make no sense to spend resources on improving unit tests from current acceptable state to a better state.

**Comment by mck1117** [comment]
But the cost of that right now is that progress is extremely difficult to make. Trying to make a change results in spending hours chasing down why that changed a test behavior.

**Comment by rusefi** [comment]
I am open to PRs
