### ISSUE TITLE
Fuel Pressure Regulator solenoid Control

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#96]
We should control said solenoid

Reported by: rusefi

**Comment by OrchardPerformance** [comment]
I cannot see a reason for this valve to exist with rusEFI, All it does is shut off the vacuum to the fuel pressure regulator to increase the fuel pressure temporarily on a hot restart.
This is to prevent vapor in the fuel rail on hot restart. A long fuel pump priming time will do the same thing. 
Remove this valve and tune this engine like any other. 

Suggest this ticket is closed and a wiki entry is created to prevent a future question?

**Comment by rusefi** [comment]
Let's close once we have this documented on the wiki.

**Comment by OrchardPerformance** [comment]
https://github.com/rusefi/rusefi/wiki/Mazda-PRC-Valve
