### ISSUE TITLE
validate flash size on start

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#964]
firmware should dynamically inquire and assert flash size

**Comment by rusefi** [comment]
See https://stm32f4-discovery.net/2014/12/library-44-stm32f4-unique-id-and-flash-size/

**Comment by mck1117** [comment]
So as to trip an error if we try to read/write config past the end of flash?

**Comment by rusefi** [comment]
Not just that but potentially execute past end of flash

**Comment by mck1117** [comment]
Sure - but it's difficult to guarantee that all of the code required to detect/report that error gets located in the first N bytes of flash.  So long as we keep the full image below the minimum flash size of any MCU we support (512k, I believe), then we're safe on execution out of bounds.

**Comment by mck1117** [comment]
We can also have efifeatures set an expected signature for the ECU - that will prevent against both "wrong size flash" and "wrong mcu" execution.

**Comment by mck1117** [comment]
we now dynamically handle flash size on F7
