### ISSUE TITLE
Measurement of CPU load

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#972]
How busy is the CPU?

Are interrupts regularly waiting on one another?

Is our generous use of global locking causing issues?

**Comment by rusefi** [comment]
ChibiOS has some mechanisms and rusEfi already has some custom mechanisms. Looks like better documentation of those is needed :)

**Comment by mck1117** [comment]
We could easily generate traces convertible to view with this:
https://github.com/catapult-project/catapult/tree/master/tracing

**Comment by rusefi** [comment]
@mck1117 please PR and document your tracing setup. What is the workflow exactly?

```ScopePerf perf(PE::MainTriggerCallback);``` is great but please elaborate a bit.

**Comment by rusefi** [comment]
@mck1117 I am still very interested in this :)

**Comment by mck1117** [comment]
99% covered by the perf tracing implementation
