### ISSUE TITLE
[MOST IMPORTANT TICKET] Both HandleFuel and PeriodicFastCallback call GetBaseFuel

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi#973]
Why do both of these compute the same thing? Should one be storing it for the other to use?

![image](https://user-images.githubusercontent.com/568254/66712449-a05b9080-ed51-11e9-9ff5-5420855f2194.png)

Top row is the trigger interrupt.  Bottom row is the periodic timer running PeriodicFastCallback.

**Comment by mck1117** [comment]
Some napkin math: the trigger interrupt invocation, on a 60-2 wheel, at 6000 RPM, gets called 5800 times per second, representing around 14% CPU usage.

**Comment by rusefi** [comment]
![image](https://user-images.githubusercontent.com/7377949/66803112-b18cd480-eeec-11e9-98a0-067f78801eb2.png)

I can only think of acceleration enrichment as a reason?

**Comment by mck1117** [comment]
A reasonable compromise may be:
1) remove it from `handleFuel`
2) increase `PeriodicFastCallback` to 200hz

**Comment by mck1117** [comment]
That will only use up around 2% CPU for the `PeriodicFastCallback`, and will run it at a lower priority than it currently runs, to prevent starvation of the trigger decoder interrupt.

**Comment by rusefi** [comment]
Prior to merging existing PR I would like to add more unit tests to ensure that functionally we would not be affected

**Comment by rusefi** [comment]
Fixed by #979
