### ISSUE TITLE
60/2 vs 60/2 VW mess

### ISSUE THREAD

**Issue by rusefi** [rusefi/rusefi#988]
We have two versions of 60/2 trigger - "60/2" and "60/2 VW"

looks like this is due to misunderstanding of how VR works, one is theoretical nice 60/2 Hall while the other one is real 60/2 VR signal

See also https://github.com/rusefi/rusefi/issues/707

**Comment by rusefi** [comment]
See https://github.com/rusefi/rusefi_documentation/raw/master/triggers/hall_vs_vr.png at https://rusefi.com/forum/viewtopic.php?f=2&t=1519

**Comment by rusefi** [comment]
Matthew Kennedy 9:39 PM
a hall sensor engine will work fine with the VR config (ie, only decode one edge)
event every 6 degrees vs. event every 3 degrees isn't a difference, other than sucking up cpu cycles
new messages
whatever edge and type of sensor you have, if you see gap ratios of 1-1-1-2-2-1-1-1 instead of 1-1-1-3-1-1-1 then the polarity is wrong
russian 9:42 PM
hold on
do you mean
1-1-1-2-2-1-1-1 means polarity is wrong
and in case of wrong polarity, you will see 1-1-1-2-2-1-1-1?
Matthew Kennedy 9:42 PM
Yes

**Comment by rusefi** [comment]
![2019-11-15_pin32_trigger_neg_2B_incorrect](https://user-images.githubusercontent.com/7377949/68988160-4131e580-0801-11ea-866a-2f82ebd8d8b3.png)
![2019-11-15_pin32_trigger_pos_2A_correct](https://user-images.githubusercontent.com/7377949/68988161-4131e580-0801-11ea-812b-f51c8e2dcb8f.png)

this is from my M73 confirming above opinion

**Comment by OrchardPerformance** [comment]
Should these be referred to as 60-2 High gap and 60-2 Low gap.
Then it identifies the two traces by the physical feature of the wheels. 
I think one signal comes from each kind of trigger wheel gap.

**Comment by OrchardPerformance** [comment]
![image](https://user-images.githubusercontent.com/49926376/82767437-773eca80-9e1f-11ea-8134-5c2c7a1fcbfb.png)
Low gap

**Comment by OrchardPerformance** [comment]
![image](https://user-images.githubusercontent.com/49926376/82767454-93db0280-9e1f-11ea-99a7-e70a174c3440.png)
high gap

**Comment by OrchardPerformance** [comment]
![image](https://user-images.githubusercontent.com/49926376/82767659-1617f680-9e21-11ea-8822-e3061be082ea.png)

**Comment by rusefillc** [comment]
Status update: we are still a bit confused :)

But at least we now have nicer wheel shapes documentation at

https://github.com/rusefi/rusefi/wiki/All-Supported-Triggers#vw-602
and
https://github.com/rusefi/rusefi/wiki/All-Supported-Triggers#602

**Comment by mck1117** [comment]
Neither of those patterns matches the Renault pattern.  The renault pattern missing tooth looks similar, but the first tooth after the gap is longer.

**Comment by rusefillc** [comment]
@mck1117 FYI

**Comment by mck1117** [comment]
Nik's trigger looks like this:
![image](https://user-images.githubusercontent.com/568254/123555387-4de72100-d73a-11eb-92dc-ed96fe63b251.png)

**Comment by mck1117** [comment]
My missing tooth (missing gap) looks like this:
![77323465-5479-45CF-9AC8-893042BB61EE](https://user-images.githubusercontent.com/568254/123555447-9ef71500-d73a-11eb-8fb4-98a21850cbc3.jpeg)

**Comment by mck1117** [comment]
As far as I can tell, these are the same, but one is inverted from the other.

**Comment by mi-hol** [comment]
My take from above comments is:
- there is no real technical issue but just unclear documentation

Is this correct understanding?

**Comment by rusefillc** [comment]
Not sure. Documentation implies user would manually locate documentation and understand it, I would prefer that we do smarter things like auto-detect the issue etc.

**Comment by mi-hol** [comment]
> I would prefer that we do smarter things like auto-detect the issue etc.

While I understand and support this view, realistically [auto-detect trigger pattern](https://github.com/rusefi/rusefi/issues/418) seems a too big task considering the currently available resources to fix this within a reasonable amount of time. Auto-detection had apparently no activities since 2017!
A viable short term fix to move forward with https://github.com/rusefi/rusefi_documentation/issues/459 seems the approach with documentation only.
I'd be happy to be proven wrong though

**Comment by rusefillc** [comment]
M73 with VW trigger

![image](https://github.com/rusefi/rusefi/assets/48498823/e5da1fdf-87af-4cc7-889f-a0a2c7da4d34)

https://github.com/rusefi/rusefi/wiki/Trigger-Configuration-Guide#determine-correct-polarity says it's flipped

**Comment by rusefillc** [comment]
same M73 engines now flipped wires

![image](https://github.com/rusefi/rusefi/assets/48498823/9e9c8f43-cbb6-46a0-870f-f8cfbb513daa)

**Comment by rusefillc** [comment]
https://rusefi.com/forum/viewtopic.php?p=49489#p49489
